### ISSUE TITLE
Need API docs for dynamic dependencies

### ISSUE THREAD

**Issue by asklar** [microsoft/WindowsAppSDK#1003]
Searching online for `mddBootstrapInitialize` doesn't turn up any good hits. Ideally we should have api docs on docs.microsoft.com but something on here would work. There is a dynamic dependencies spec that mentions the architecture/design of DD, but not an API reference page.

**Comment by DrusTheAxe** [comment]
You're not wrong just ahead of the curve. The feature's currently experimental and per the [Channels decision](https://github.com/microsoft/WindowsAppSDK/discussions/637) under "Bars for getting a feature into each release..."

| Bar | Experimental (== main) | Preview | Stable |
--- | --- | --- | ---
| Docs | At least an API spec or GitHub Issue with some examples devs can work from | Preview of primary docs experience published on docs site (either conceptual or API ref) | Conceptual and API ref docs |

[The roadmap](https://github.com/microsoft/WindowsAppSDK#roadmap) doesn't clearly show it but the "Unpackaged desktop apps" row includes Dynamic Dependencies so docs are coming. But API information should already be available if you check [MddBootstrap.h](https://github.com/microsoft/WindowsAppSDK/blob/main/dev/ProjectReunion_BootstrapDLL/MddBootstrap.h) or [the spec](https://github.com/microsoft/WindowsAppSDK/blob/main/specs/dynamicdependencies/DynamicDependencies.md#612-mddbootstraph) the prototypes include full doc-comments.

[Tutorial: Build and deploy an unpackaged app](https://docs.microsoft.com/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=cpp) includes sample usage (step 3. "You are now ready to use the dynamic dependencies API to initialize the Bootstrapper..."). It's also used in some of the 0.8 samples, e.g. MRTCore's [console_unpackaged_app.cpp](https://github.com/microsoft/WindowsAppSDK-Samples/blob/main/MrtCore/console_unpackaged_app/console_unpackaged_app.cpp). Were you aware of these? Do they help provide a working understanding to unblock you?

**Comment by asklar** [comment]
thanks Howard; I'm not currently blocked on this, just thought I'd bring it up since developers will eventually need something like it. 
I actually found this API from the tutorial (and then found the spec), and I wanted to learn more about it and what other APIs are available, which I would have found through links on DMC : )

**Comment by DrusTheAxe** [comment]
Agreed on the needs. Docs are in plan they just weren't ready as quickly as the code. But thanks for the feedback. It sparked some (more) discussions regarding documentation and discovery. Stay tuned!

P.S. DMC=?

**Comment by asklar** [comment]
Thanks @DrusTheAxe, good to know! Feel free to ping me internally about auto-generating docs from winmd if you are looking to do that as i've done this for react native for windows : )
DMC=docs.microsoft.com. more pronounceable :)

**Comment by DrusTheAxe** [comment]
https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/win32/mddbootstrap/nf-mddbootstrap-mddbootstrapinitialize
