### ISSUE TITLE
Publishing a simple app fails with "project.assets.json not found"

### ISSUE THREAD

**Issue by Symbai** [microsoft/WindowsAppSDK#1015]
**Describe the bug**
I created a new app using the WinUI Template Studio. Its a WinUI 3.0 Desktop C# app. I can debug it but when I try to publish (right click on Package solution -> Publish -> Create app package -> Uncheck auto updates and press 'next' until it tries to publish) I always receive this publish error:

> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error		Assets file 'C:\Users\User\Desktop\TestApp\TestApp\obj\wappublish\win10-x86\project.assets.json' not found. Run > a NuGet package restore to generate this file.	TestApp (Package)	C:\Program Files\dotnet\sdk\5.0.400- preview.21277.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	242	

I've restored nuget packages via right click on the solution and then restore nuget packages. It was successful but I still receive the error above. I've ran the nuget console in VS and used "dotnet restore", it was successful but I still receive the error above. I've restarted VS, deleted all "obj" folders etc. but the error still appears. Because I'm new to WinUI I have no idea what I'm doing wrong.

Are there any steps that needs to be done after a creating a project before I can publish it?

**Version Info**
Windows 10 21H1
Project Reunion (Preview) 0.8.0.44306308
Windows Template Studio 4.1.21179.1
Visual Studio 2019 Preview Community Project Version 16.11.0 Preview 2.0

**Comment by ghost1372** [comment]
I have the same problem to solve it temporarily:
Go to the path below in your project:
`obj\wappublish
`
Create the following subfolders
```
win10-x64
win10-x86
```
Now copy the contents of the `win-x86` and `win-x64` folders into them
The problem is that the following folders are created when rebuilding
```
win-x64
win-x86
```
But when packaging, Visual Studio looks for the following folders
```
win10-x64
win10-x86
```
If you have other platforms, do the same for them

**Comment by iceberg1370** [comment]
This is a bug in Visual Studio affecting publish. Things were fine in 2019 16.9 then broke in 16.10.1 through 16.10.3. I am working with the VS folks to hopefully get a fix in VS 16.10.4. 

In my experience even if you solve the project.assets.json issue the app still doesn’t launch at runtime.

**Comment by btueffers** [comment]
Hi @iceberg1370, is there a visual studio issue we can reference to close this out?

**Comment by ivberg** [comment]
Yes - here you go @btueffers  - https://developercommunity.visualstudio.com/t/Unable-to-package-a-WinUI-3-App-with-Pro/1467291

**Comment by Symbai** [comment]
Because it says it's fixed in next VS update, I'm closing this issue then.
