### ISSUE TITLE
Getting "Cannot resolve symbol 'XXXXXX'" error after upgrading from WinUI3 to Project Reunion 0.8 stable version

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/WindowsAppSDK#1032]
I recently upgraded my WinUI3 desktop app to Project Reunion 0.8 version using the upgrade instructions.
When I open any XAML file, I am getting "Cannot resolve symbol 'XXXXXX'" suggestions/warnings. All these are related to Microsoft.UI.XAML namespace. However, the app builds and runs fine.
I tried repro on a new app using the template and it does not have this issue. Seems like some missing links between Project-Reunion package and how Microsoft.UI.XAML is packaged into it, not sure.
Am I missing anything?

**Steps to reproduce the bug**
Take an existing WinUI3 app and upgrade it to Project Reunion 0.8 either directly or to 0.5 and then 0.8.

**Expected behavior**
XAML should resolve without any issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/52011872/124705160-0aaf4f80-deaa-11eb-9f79-4efd13828dd5.png)

**Version Info**
 Project-Reunion: 0.8
 OS Build: 19042

**Comment by MikeHillberg** [comment]
@abhi-msft, what version of Visual Studio are you using? Errors showing up in VS but not in build usually means something related to Intellisense is out of sync.

**Comment by abhi-msft** [comment]
Thought so, I am using VS 16.10.3.

**Comment by MikeHillberg** [comment]
I think that's the latest public release. @alwu-msft might have ideas?

**Comment by abhi-msft** [comment]
Yes, that's the latest public release.
VS 16.11.0 Preview 2.0 version does not have this issue.

**Comment by alwu-msft** [comment]
How are you upgrading your project: VS's Nuget Package Manager, or in a text editor/nuget.exe and then opening the upgraded project in VS? Does this persist after restarting VS? My instinctive thought is that stale information is hanging around in VS's caches.

**Comment by abhi-msft** [comment]
Used VS Package Manager. Tried all I can think of restarting VS, deleting the packages folder under my user, and restarting the machine itself.

**Comment by alwu-msft** [comment]
Bizarre! Would you mind sharing the upgraded project? One final thought... maybe there's something stale left in `bin/` or `obj/`?

**Comment by abhi-msft** [comment]
Oh yeah, that's one more thing I did in my list of tries, Cleaned them as well 😁 but same result 🙄

**Comment by LegendaryBlair** [comment]
Not applicable today as WinUI 3 project template implies WinAppSDK. No upgrade is required.
