### ISSUE TITLE
Error when installing stable Windows App SDK Extension for Visual Studio: "Not all privileges or groups referenced are assigned to the caller"

### ISSUE THREAD

**Issue by lyahdav** [microsoft/WindowsAppSDK#1052]
**Describe the bug**
I get an error when following the steps here to install the stable release: https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=windows-app-sdk#install-the-stable-release

**Steps to reproduce the bug**

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=windows-app-sdk#install-the-stable-release

**Expected behavior**
Extension installs

**Screenshots**
![Screen Shot 2021-07-12 at 5 07 49 PM](https://user-images.githubusercontent.com/359157/125370706-f5b43f80-e333-11eb-9446-f215e4b2d6cd.png)

**Version Info**

NuGet package version: 
The version of the extension listed in the Manage Extensions window is: 0.8.0.46122163

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 19043 | Yes |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
Here's the installer log:
```
7/12/2021 5:07:10 PM - Microsoft VSIX Installer
7/12/2021 5:07:10 PM - -------------------------------------------
7/12/2021 5:07:10 PM - vsixinstaller.exe version:
7/12/2021 5:07:10 PM - 16.11.9
7/12/2021 5:07:10 PM - -------------------------------------------
7/12/2021 5:07:10 PM - Command line parameters:
7/12/2021 5:07:10 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:16.10.31424.327,/appidname:Microsoft Visual Studio Professional 2019,/culture:en-US,/noep,C:\Users\lyahdav\AppData\Local\Temp\VSIXfru00cpd.vsix,/callingprocessid:11664,/installas:2092
7/12/2021 5:07:10 PM - -------------------------------------------
7/12/2021 5:07:10 PM - Microsoft VSIX Installer
7/12/2021 5:07:10 PM - -------------------------------------------
7/12/2021 5:07:10 PM - System.ComponentModel.Win32Exception (0x80004005): Not all privileges or groups referenced are assigned to the caller
   at System.Diagnostics.Process.SetPrivilege(String privilegeName, Int32 attrib)
   at System.Diagnostics.Process.EnterDebugMode()
   at VSIXInstaller.UserImpersonationHelper.DuplicateSuppliedToken(IntPtr token, UInt32 callingProcessId)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

I also tried the steps listed [here](https://jigneshdarji.com/error-vsix-installer-not-all-privileges-or-groups-referenced-are-assigned-to-the-caller/) to change privileges of the Microsoft Visual Studio folder to my user and restarting my machine but it didn't help.

**Comment by asklar** [comment]
@lyahdav which version of the vsix were you installing?
@DefaultRyan fyi

**Comment by lyahdav** [comment]
If you're referring to the version listed in the Manage Extensions window, it's 0.8.0.46122163

**Comment by lyahdav** [comment]
Figured this out. I had to run VS as admin before installing the extension.

**Comment by lyahdav** [comment]
Actually, reopening so that the documentation is updated. On https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=windows-app-sdk#install-the-stable-release it should probably say something about needing to run as admin.

**Comment by AreYouReallyGhostAreYouGettingBannedNo** [comment]
> Actually, reopening so that the documentation is updated. On https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=windows-app-sdk#install-the-stable-release it should probably say something about needing to run as admin.

wasted hours on this. VSIX Installer won't install/uninstall anything without running as admin.

**Comment by codendone** [comment]
The extension has been deprecated for a while, with Windows App SDK functionality now directly part of Visual Studio. Closing.
