### ISSUE TITLE
wapproj not updated when moving from 0.8.0 to 0.8.1

### ISSUE THREAD

**Issue by stevewhims** [microsoft/WindowsAppSDK#1061]
**Describe the bug**
wapproj wasn't updated when moving from 0.8.0 to 0.8.1; had to move back to 8.0 then to 8.1 again for the file to be updated.

**Steps to reproduce the bug**
1. Begin with a Windows App SDK 0.5 project (in my case it was a Direct3D project). Make sure it builds and runs.
2. Upgrade it to 0.8.0. Still builds and runs.
3. Upgrade it to 0.8.1. Direct3D content no longer renders.
4. Revert to 0.8.0.
5. Upgrade a second time to 0.8.1. App now builds and runs again.

It was only that final step that seemed to make the necessary changes to my `*.wapproj` file, because previously that file was missing PackageReferences to Microsoft.ProjectReunion.DWrite, Microsoft.ProjectReunion.Foundation, Microsoft.ProjectReunion.InteractiveExperiences, and Microsoft.ProjectReunion.WinUI. That last step added those references, and then the app ran ok. So evidently at least one of those was necessary for the app to run properly.

**Expected behavior**
App works at step 3.

**Screenshots**
N/A

**Version Info**
See info above.

NuGet package version: 
See info above

Saw the problem on latest Win10 and latest Win11 Insider.

**Additional context**
N/A

**Comment by anawishnoff** [comment]
Hey @stevewhims, did you by chance follow [these instructions](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/update-existing-projects-to-the-latest-release#update-from-08-preview-to-08-stable-or-between-stable-08-versions) while updating the app from 0.8 -> 0.8.1? It should be a pretty simple process but can require some manual updates to your .wapproj file.

**Comment by stevewhims** [comment]
Thanks, @anawishnoff! I didn't notice that documentation, but I can infer from it that my expectations weren't correct w.r.t just using the VS UI (once) to do the upgrade. In fact, though, using the VS UI twice (as I did) worked; I didn't even need to manually edit anything, so the experience was actually better than documented! :)

I'll go ahead and close this issue now, since this is known.

Thanks!
Steve
