### ISSUE TITLE
Windows.System.Profile.AnalyticsInfo.VersionInfo.ProductName returns the wrong name

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#1065]
On Windows 11, Windows.System.Profile.AnalyticsInfo.VersionInfo.ProductName returns Windows 10 {edition} instead of Windows 11 {edition}.

![image](https://user-images.githubusercontent.com/45227503/125737812-1568307c-27a3-44e1-8512-6d64b5000c0a.png)

**Comment by Jaiganeshkumaran** [comment]
It seems to pull the information from the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProductName which's value hasn't been updated however Windows Settings correctly identities it as Windows 11 Pro.

**Comment by btueffers** [comment]
Thank you for your feedback! We're following up internally with folks since this isn't for the Windows App SDK.
