### ISSUE TITLE
C++ projects - Enable setting executable details without .rc file

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/WindowsAppSDK#1092]

**Comment by riverar** [comment]
Sigh. Can you provide more details?

**Comment by sylveon** [comment]
Why? What's the issue with .rc files? Most people never end up touching them to begin with because there's a visual editor for it.

**Comment by sylveon** [comment]
> First it's a separate file in your projects.

So is C# AssemblyInfo.cs

> And .rc isn't just for version info, but it's also for other things. 

If you don't need to do the other things that .rc files support, just don't use that part of .rc files? You can have .rc files which hold only version info.

> I shouldn't require a .rc file just for version info.

"I shouldn't require an AssemblyInfo.cs just for version info." Then where would version info come from? It has to be stored somewhere.

> Managed .NET projects have a assembly info dialog where you can fill in the details but something like that doesn't exist currently in C++ projects.

The dialog just fills AssemblyInfo.cs. It would be better to ask for a visual editor that fills a .rc file's version table. The same end result is achieved.
