### ISSUE TITLE
Please get rid of dynamicClass.IL_STUB_CLRtoWinRT and vice versa

### ISSUE THREAD

**Issue by jtorjo** [microsoft/WindowsAppSDK#1102]
**Describe the bug**

IMO, there's waaaay too much time spent in `IL_STUB_CLRtoWinRT` and their counterpart (`IL_STUB_WinRTToCLR`).

Is WindowsAppSDK getting rid of this?

**Steps to reproduce the bug**

I will provide screenshots from my project (it's UWP), where I  do this:

For 25 seconds, every second, I create 20 instances of `keyframe_ctrl` and 20 instances of `keyframe_movement_ctrl`. They start by taking 80ms (which is waaay too much anyway), and take more and more time, and end up taking 180ms .

![image](https://user-images.githubusercontent.com/13891601/126596419-192f785e-16ae-4f84-bf5b-625b7c93f4ef.png)

Before showing the xaml for each class. Please note that out of 41.45% spent time, roughly 28% is "external code" -- why?

Both classes are rather trivial, here's their XAML:

	<UserControl
		x:Class="basic_ui_complete.keyframes.keyframe_ctrl"
		xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
		xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
		xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
		xmlns:iconPacks="using:MahApps.Metro.IconPacks"
		xmlns:extensions="using:Microsoft.Toolkit.Uwp.UI.Extensions"
		xmlns:binding="using:common2.binding"
		xmlns:keyframes="using:basic_ui_complete.keyframes"
		mc:Ignorable="d"
		DataContextChanged="Keyframe_ctrl_OnDataContextChanged"
		d:DesignHeight="300"
		d:DesignWidth="400">
		<Canvas>
			<Canvas x:Name="canvas">
				<StackPanel Orientation="Vertical" 
							PointerEntered="enter_hover" PointerExited="exit_hover"
							Canvas.Left="-6" Canvas.Top="-6" Height="24" Background="Transparent" >
					<Grid Width="12" Height="12">
						<Grid Width="12" Height="12" Background="Transparent" 
							  PointerPressed="value_pressed" PointerReleased="value_released" PointerMoved="value_moved" x:Name="value_ctrl"
							  binding:vc_dep.Visible="{Binding is_not_color}"
							  >
							<iconPacks:PackIconMaterial Kind="Rhombus" Width="12" Height="12" 
														Foreground="Black" 
														VerticalAlignment="Center" HorizontalAlignment="Center"
														binding:vc_dep.Visible="{Binding is_group_keyframe}"
							/>
							<iconPacks:PackIconMaterial Kind="Rhombus" Width="8" Height="8" 
														Foreground="{Binding color}" 
														VerticalAlignment="Center" HorizontalAlignment="Center"
														binding:vc_dep.Visible="{Binding is_group_keyframe}"
							/>
							<iconPacks:PackIconMaterial Kind="Rhombus" Width="10" Height="10" 
														Foreground="{Binding color}" 
														VerticalAlignment="Center" HorizontalAlignment="Center"
														binding:vc_dep.Visible="{Binding is_not_group_keyframe}"
							/>
						</Grid>

						<Rectangle binding:vc_dep.Visible="{Binding meta.is_color}" 
								   Fill="{Binding value.color_value.to_brush}" 
								   PointerEntered="enter_color" PointerExited="exit_color" PointerMoved="hover_color" PointerPressed="click_color"
								   Stroke="{ThemeResource OrangeBrush}" StrokeThickness="{Binding color_rect_thickness}"
						/>

						<Popup x:Name="color_popup" IsLightDismissEnabled="True" HorizontalOffset="20" VerticalOffset="{Binding color_picker_vert_offset}">
							<Grid x:Load="false" x:Name="color_grid" Padding="5" Background="{ThemeResource PaneBackgroundBrush}" >
								<keyframes:color_ctrl x:Name="color_ctrl" x:Load="false"/>
							</Grid>
						</Popup>
					</Grid>

					<Grid Width="10" Height="12" Background="Transparent" 
						  binding:vc_dep.Visible="{Binding is_hovered_or_selected}"
						  PointerPressed="ms_pressed" PointerReleased="ms_released" PointerMoved="ms_moved" x:Name="ms_ctrl"
						  >
						<iconPacks:PackIconMaterial Kind="Circle" Width="6" Height="6" 
													HorizontalAlignment="Center" VerticalAlignment="Bottom"/>
					</Grid>
				</StackPanel>

				<Grid Canvas.Left="15" Canvas.Top="-8" Height="16" PointerEntered="text_enter" PointerExited="text_exit"
					  Padding="5 2" Background="#7f000000"
					  binding:vc_dep.Visible="{Binding show_text}" 
					  >
					<TextBlock Text="{Binding text}" VerticalAlignment="Center" FontSize="10" />
				</Grid>
			</Canvas>
		</Canvas>
	</UserControl>

and

	<UserControl
		x:Class="basic_ui_complete.keyframes.keyframe_movement_ctrl"
		xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
		xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
		xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
		xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
		xmlns:binding="using:common2.binding"
		xmlns:extensions="using:Microsoft.Toolkit.Uwp.UI.Extensions"
		xmlns:winrte="using:WinRTXamlToolkit.Controls.Extensions"
		DataContextChanged="Keyframe_movement_ctrl_OnDataContextChanged"
		SizeChanged="Keyframe_movement_ctrl_OnSizeChanged"
		mc:Ignorable="d"
		d:DesignHeight="300"
		d:DesignWidth="400">

		<Canvas x:Name="canvas" >
			<Polyline binding:vc_dep.Visible="{Binding is_not_linear}" StrokeThickness="{Binding stroke_thickness}" 
						  Fill="{Binding brush}" Stroke="{Binding brush}" 
						  x:Name="path" />
			<Polyline binding:vc_dep.Visible="{Binding is_not_linear}" 
					  StrokeThickness="{Binding hit_testing_thickness}" Stroke="Transparent" Fill="Transparent" 
					  PointerEntered="path_enter" PointerExited="path_exit" PointerPressed="path_down" PointerReleased="path_up" PointerMoved="path_move"
					  x:Name="interactive_path"
			/>

			<Line binding:vc_dep.Visible="{Binding is_linear}" StrokeThickness="{Binding stroke_thickness}" 
				  Fill="{Binding brush}" Stroke="{Binding brush}" 
				  x:Name="line" />
			<Line binding:vc_dep.Visible="{Binding is_linear}" 
				  StrokeThickness="{Binding hit_testing_thickness}" Stroke="Transparent" Fill="Transparent" 
				  PointerEntered="line_enter" PointerExited="line_exit" PointerPressed="line_down" PointerReleased="line_up" PointerMoved="line_move"
				  x:Name="interactive_line"
				  />
			
			<Grid binding:vc_dep.Visible="{Binding is_hovered_or_selected}" 
				  Padding="5 2" Background="#7f000000"
				  x:Name="tooltip_ctrl"
			>
				<TextBlock Text="{Binding text}" VerticalAlignment="Center" FontSize="10" />
			</Grid>
		</Canvas>
	</UserControl>

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

**Comment by AaronRobinsonMSFT** [comment]
@jtorjo This is by-design and something that is needed for interoperability with the base WinRT implementation - which is largely written in C++. These methods are dynamically generated for passing data between a .NET environment and a native environment (that is, C or C++). They are historically generated at runtime but moving forward in .NET 5+ we are using [C#/WinRT](https://github.com/microsoft/CsWinRT). These stubs are typically optimized to be as fast as possible but in some cases they can be slow due to the expensive transition cost in and out of the .NET environment.

The reason they are marked "External" is because they aren't associated with an assembly in the current solution so the VS Profiler marks them as such. Additionally some of the code here is likely hidden and is native code (that is, C/C++). As long as there is a mixture of native and managed (that is, .NET) code in an application these types of "stubs" must exist. The point about their performance cost is important and something that we are constantly trying to lower.

**Comment by btueffers** [comment]
Similar issues can be filed with the [Visual Studio developer community](https://developercommunity.visualstudio.com/home)!

**Comment by jtorjo** [comment]
@btueffers I'm not really sure why you closed this. Also, this doesn't seem to have anything to do with VS.

**Comment by jtorjo** [comment]
@AaronRobinsonMSFT What you're saying makes a lot of sense. What strikes me are 2 things:

1. I would assume something could be optimized for loading in bulk (like, pre-creating 100 controls or so)
2. Load times get higher and higher as I create more controls - this makes no sense.

Side-note: clearly, a great way to make this work would be the ability to create controls on a different thread, but I'm assuming that's out of the question.

**Comment by riverar** [comment]
> @btueffers I'm not really sure why you closed this. Also, this doesn't seem to have anything to do with VS.

Probably because this isn't applicable to the Windows App SDK. Probably worth transferring to https://github.com/dotnet/runtime/issues although with C#/WinRT already on the books as the way forward, probably no value in keeping this issue open.

**Comment by jtorjo** [comment]
@riverar Thanks! Wasn't aware - so hypothetically, this won't be an issue when I port to winUI3 Desktop, if I understand correctly.

**Comment by AaronRobinsonMSFT** [comment]
>Probably because this isn't applicable to the Windows App SDK.

Right. This specific manifestation is a UWP/WinRT issue but the fact that stubs exist at all is a general .NET issue.

>Also, this doesn't seem to have anything to do with VS.
>Might be worth transferring to https://github.com/dotnet/runtime/issues

Note that https://github.com/dotnet/runtime/issues is for CoreCLR specifically (so .NET Core 3.*, .NET 5+). For .NET Framework related issues, which is the only supported version of the CLR runtime for UWP, issues should be filed at https://developercommunity.visualstudio.com/home and will be triaged by the appropriate owners.

**Comment by AaronRobinsonMSFT** [comment]
>@riverar Thanks! Wasn't aware - so hypothetically, this won't be an issue when I port to winUI3 Desktop, if I understand correctly.

Quite possibly but it depends on the scenario. The support for WinRT in .NET 5+ is entirely new and now handled by the C#/WinRT tool chain. If performance issues are found there, which there are several known, start with https://github.com/microsoft/CsWinRT and if need be the runtime team will be looped in.

**Comment by jtorjo** [comment]
@AaronRobinsonMSFT Got it, thanks. Will look into this further when I will port my app to WinUI3 Desktop.
