### ISSUE TITLE
App built with Windows App SDK 0.8.1 fails to launch if installed from the Store

### ISSUE THREAD

**Issue by RedSaltyFish** [microsoft/WindowsAppSDK#1105]
**Describe the bug**

I built an app with the newly released Windows App SDK 0.8.1 and published it to the Store, only to find that it won't launch if installed from the Store. The app never showed a window and didn't yield any information about what could be wrong so I looked it up in Event Viewer, and found an `Application Error` of my app, with an error code of `0xc000027b` in module `KernelBase.dll`.

The app works pretty well if deployed directly using Visual Studio with `Release` configuration.

The app somehow passed the validation process of the Store and I had to mark it as unavailable after discovering the issue.

**Steps to reproduce the bug**

1. Build an app using Windows App SDK 0.8.1, package it and upload it to the Store;
2. Install it from the Store and launch it.

**Expected behavior**

The app launches and works just like deployed using Visual Studio.

**Screenshots**

None.

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I can make the source code public if it helps to find the problem.

**Comment by RedSaltyFish** [comment]
**More information about what could be wrong**

Attaching the debugger to the package didn't get any useful information, only an exception `Microsoft C++ exception: winrt::hresult_error at memory location 0x000000EE2C77CC20`

Here are some *unusual* things I did when developing this app.
- I made the generated `App.m_window` field static and public;
- I set MainWindow's `ExtendsContentIntoTitleBar` to `true` in its constructor, right after its `InitializeComponent()` is called;
- I did some subclassing tricks to set MainWindow's minimum width and height, as described [here](https://github.com/microsoft/microsoft-ui-xaml/issues/2945#issuecomment-776446712).

And here is another *unusual* thing I did when trying to package the app.
- Since Visual Studio 16.10.4 hadn't been published when I tried to package the app, I had to perform the workaround described [here](https://github.com/microsoft/WindowsAppSDK/issues/1015#issuecomment-873206533) to generate a package without any errors.

**Comment by huichen123** [comment]
can you share a crash dump? I submitted a blank WinUI C# app using 0.8.1 to the Store, and had no problem downloading/launching it.

**Comment by RedSaltyFish** [comment]
> can you share a crash dump? I submitted a blank WinUI C# app using 0.8.1 to the Store, and had no problem downloading/launching it.

The crash didn't generate any dumps on my device. I've sent you an email which contains a promotional code of my app, hopefully this will help to find what is wrong.

**Comment by huichen123** [comment]
is there a link to your app in store?

**Comment by RedSaltyFish** [comment]
> is there a link to your app in store?

Here it is: https://www.microsoft.com/store/apps/9NFNRQ6LF8HM

**Comment by huichen123** [comment]
It fails to load fishauth.dll due to failing to load WinRT.Runtime 1.3. The version in your app is 1.2 (mine has 1.3). Not sure how this happened. Can you add following to your project (replace 19041 to your target platform version if it's different) and see whether it solves your problem?

~~~
<ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.19041.18" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.19041.18" />
</ItemGroup>
~~~

**Comment by RedSaltyFish** [comment]
The app is re-submitted. I'll update this comment once it passes the validation process and I get time to test it.

**Comment by huichen123** [comment]
did you also update the project for building fishauth.dll? Project Reunion 0.8.1 only requires winrt.runtime 1.2. Something else in your project must have requested 1.3. Not sure what it is though. Another thing may help you is install .NET SDK 5.0.302. For quick verification, you can check the version of winrt.runtime.dll in your msixuupload package. If it's 1.3, it's probably good.

**Comment by huichen123** [comment]
I noticed there might be some cleanup issue with rebuild that prevents winrt.runtime.dll being updated in wapproj/appxpackage. Please delete all build outputs before rebuild/create package.

**Comment by RedSaltyFish** [comment]
> I noticed there might be some cleanup issue with rebuild that prevents winrt.runtime.dll being updated in wapproj/appxpackage. Please delete all build outputs before rebuild/create package.

After deleting all build outputs before creating the package solved the problem. Never thought this could be the problem. Thanks for saving me so much time.
