### ISSUE TITLE
Using DrawTextLayout after 0.8.1 update with DirectWriteCore creating TextLayout

### ISSUE THREAD

**Issue by robhurry** [microsoft/WindowsAppSDK#1109]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1108

<div type='discussions-op-text'>

<sup>Originally posted by **robhurry** July 23, 2021</sup>
After updating to 0.8.1 from 0.8.0 my application that I had successfully transfered to the windows app sdk because the DrawTextLayout to the ID2D1DeviceContext now fails. 

I see from the documentation of DWriteCore that (https://docs.microsoft.com/en-us/windows/win32/directwrite/dwritecore-overview):
"However, currently, Direct2D and DWriteCore don't interoperate. For example, if you create an IDWriteTextLayout using DWriteCore, and pass it to D2D1RenderTarget::DrawTextLayout, then that call will fail."

I assume this explains why it no longer works in version 0.8.1 (Because the DirectWriteCore package is now added) so I assume my IDWriteTextLayout is created using DWriteCore.

So my question is in a Windows App SDK app using 0.8.1 how do you draw a text layout to a D2D1RenderTarget?

</div>

**Comment by niklasb-ms** [comment]
You're correct that DWriteCore does not interoperate with Direct2D.

If I understand correctly, your app is creating the IDWriteTextLayout using a factory object returned from DWriteCreateFactory. For now, both DWrite.dll and DWriteCore.dll export this function, so whether your scenario works or not depends on which module the linker resolves your DWriteCreateFactory call to. There's no change between 0.8.0 and 0.8.1 that would explain this, but it's possible that just updating nuget packages would change the link order.

If you're not actually using DWriteCore, you could try just removing the Microsoft.ProjectReunion.DWrite nuget package from your project. This would remove the linker reference to DWriteCore.lib. Alternatively, you might be able to fiddle with the link command line to ensure DWrite.lib comes first. If all else fails, you could explicitly load DWrite.dll using LoadLibrary.

Note that in 0.8, DWriteCore.dll exports both DWriteCreateFactory and DWriteCoreCreateFactory functions as a transitional measure, but the former has been removed in 1.0. Therefore, in WindowsAppSDK 1.0, you won't have to worry about linker order. Calling DWriteCreateFactory function will unambiguously invoke the system implementation.
