### ISSUE TITLE
WAS runtime installer adds unwanted tiles to Start

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1120]
**Describe the bug**
After installing the WAS runtime, Start contains a bunch of unwanted tiles. (I understand 0.8-preview support is non-existent. Just making sure these issues are in the backlog.)

**Steps to reproduce**
1. .\ProjectReunion-0.8Preview-Install-x64.exe
2. Observe results

![image](https://user-images.githubusercontent.com/475132/126943503-e997ac10-f982-4553-89a8-9cdc4b6ecf59.png)

ProjectReunion-0.8Preview-Install-x64.exe
Windows Server 2019 17763.1

**Comment by DrusTheAxe** [comment]
Known issue in 0.8-preview (manifests were missing `...AppListEntry="none"`).

Already fixed in upcoming 1.0 releases

Sorry about the inconvenience in the meantime
