### ISSUE TITLE
UWP - Provide a way to display title bar context menu

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#1123]
# Proposal: UWP - Provide a way to display title bar context menu
The default title bar has a context menu however a UWP app can't display it programmatically without input injection which requires a restricted capability.

## Summary
The default UWP title bar only has the title text and the caption buttons unlike desktop apps and Windows 8.1 apps and this was the style that was adopted for most apps. However now with Windows 11, many apps are starting to adopt a style with the app icon as well as the title text. If you are a desktop app and using the default title bar, you already have the icon but with UWP apps, you need to create a custom extended title bar. One of the main features of the default Win32 title bar is that, when you click on the icon, you get the title bar context menu however this isn't possible with a custom title bar in UWP so now you've inconsistent behavior across Win32 and UWP apps. Input injection can be used for displaying the menu however it requires a restricted capability and for this simple behavior that Win32 apps already have, you shouldn't need it.

## Rationale

* Making it easier to use the same consistent behavior from Win32 title bar in a custom UWP title bar.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to display the title bar context menu programmatically at a specific position | Must |

## Important Notes

The default title bar for UWP can be updated with the addition of app icon with the same Win32 behavior so this proposal is only for apps choosing to extend content into title bar and build a custom one.

**Comment by ghost0000000000000** [comment]
* last time _CoreWindow([aka system managed hWnd ](https://kennykerr.ca/2012/11/09/windows-8-whered-you-put-my-hwnd/)aka UWP)_ app model(not ui) got any _real_ improvement was in 2017 
* it's 2021, when MS finally back into it's senses - new age of windowsappsdk and modern win32   -  it's high time to move on

**Comment by rkarman** [comment]
This is indeed the design decision made for UWP apps, and as such CoreWindow/ApplicationView does not support showing an icon in the TitleBar. We currently have no plans to change that design decision, which also means that we have no plans of adding this feature to CoreWindow/ApplicationView.

**Comment by Jaiganeshkumaran** [comment]
> This is indeed the design decision made for UWP apps, and as such CoreWindow/ApplicationView does not support showing an icon in the TitleBar. We currently have no plans to change that design decision, which also means that we have no plans of adding this feature to CoreWindow/ApplicationView.

However many of the inbox UWP apps in Windows 11 show an icon in the title bar and since they're custom, they can't replicate the same click behavior that the default Win32 title bar has, creating inconsistency. While these are possibly going to stick with custom title because they have more than the icon, by default it should be consistent.

New Microsoft Store: 
![image](https://user-images.githubusercontent.com/45227503/127089370-1ea50867-30e3-4385-ba2d-ba588e93f6ec.png)

New Security dialog:
![image](https://user-images.githubusercontent.com/45227503/127091157-92c10749-afcc-4091-abc0-b34f422fd23e.png)

New Photos app (unreleased):
![New photos](https://user-images.githubusercontent.com/45227503/127091581-a6d81e82-54b9-4c18-94e3-459ecdd95c2c.png)
