### ISSUE TITLE
Add AssetTargetFallback to C++ WinUI wapproj template

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/WindowsAppSDK#1130]
**Describe the bug**

For [C#/WinRT authoring](https://github.com/microsoft/CsWinRT/blob/master/docs/authoring.md) scenarios, we need to be able to reference a C#/WinUI library project from a C++ WinUI app, but currently need to workaround by adding the property `<AssetTargetFallback>net5.0-windows$(TargetPlatformVersion);$(AssetTargetFallback)</AssetTargetFallback>` to the C++ WinUI wapproj template. We should add the AssetTargetFallback property to the C++ WinUI wapproj templates to avoid needing this workaround. This property is already set in the C# WinUI wapproj template and therefore this error doesn't occur with C# WinUI app -> C# WinUI library references.

Another workaround is setting `<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>` from the default 10.0.17763.0. But this workaround doesn't make sense, as the C# library project sets TPMV to 10.0.17763.0

Without using either of these workarounds we get NU1201 build errors, for example : NU1201 Project AuthoringUserControl is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763) / win10-arm. Project AuthoringUserControl supports: net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0)	CppWinUI (Package)	

**Steps to reproduce the bug**

1. Create a WinUI C# class library project
2. Create a WinUI C++ app (packaged) and reference the library.
3. Will get NU1201 build errors

**Expected behavior**

.wapproj template should already have `AssetTargetFallback` specified so that a project reference from C++ to C# should just work without manual intervention from developer.

**Version Info**

Reunion 0.8.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

C#/WinRT authoring scenarios should work out of the box for WinAppSDK 1.0.

**Comment by LegendaryBlair** [comment]
According to this [supported matrix](https://github.com/microsoft/CsWinRT/blob/master/docs/authoring.md#support-matrix), C++ desktop app consuming CsWinRT component from a WAP project is not supported.
