### ISSUE TITLE
GraphicsCapturePicker UI needs updating to Windows 11 styling

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/WindowsAppSDK#1137]
# Proposal: [GraphicsCapturePicker UI needs updating to Windows 11 styling] 

## Summary

The UI shown by GraphicsCapturePicker hasn’t been significantly updated since introduction, and now looks quite out of place on Windows 11. This UI should be updated to use the new WinUI 2.6 styles

## Rationale

* Make the OS consistent with all its apps and components (in this case an app might be using this API and would look ugly with it)

## Important Notes
Screenshot of what I am referring to
![image](https://user-images.githubusercontent.com/43090263/127379785-ce65f925-f412-41bb-89ee-1b36c0c29b02.png)

**Comment by btueffers** [comment]
This feedback isn't directly Windows App SDK related. We've reached out to the appropriate team internally so they're aware of the issue 😊
