### ISSUE TITLE
Question: how to check network connection?

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsAppSDK#1139]
NetworkHelper.Instance.ConnectionInformation.IsInternetAvailable
NetworkInterface.GetIsNetworkAvailable()
are **True**
even when WLAN switch is off for my app, and my app can't access network. so I need a way to check network connection.

**Comment by HppZ** [comment]
THANKS!

not physical hardware and switches, it is in Windows Settings:
> Network & Internet > Wi-Fi > Choose apps that can use your Wi-Fi data.

actually I want to detect if this switch is on or off for my app, but found no way.

**Comment by andrewleader** [comment]
Hey HppZ, thanks for asking this question! And Matt, thanks for the super detailed answers 😊

@HppZ, so your ask is for an API that tells you if the toggle switch in `Network & Internet > Wi-Fi > Choose apps that can use your Wi-Fi data.` is on or off on your app, correct? I can check with the team to see if an API for that exists, and if not, see whether it's been considered.

**Comment by andrewleader** [comment]
Actually @HppZ I can't even find that setting on my computers, I checked both a Windows 10 and Windows 11 PC. Can you send me a screenshot of that settings page and where you found it?

**Comment by riverar** [comment]
This feature requires CTA policy to be enabled (China). Try using `AppCapability.Create("wifiData").CheckAccess()` to check if your app is being limited.

**Comment by riverar** [comment]
@andrewleader If you're curious, the feature looks like this. It's actually really neat, wish it was generally available to all of us!

![image](https://user-images.githubusercontent.com/475132/127569964-baaa2898-9755-4d41-a895-f22907e1642d.png)
![image](https://user-images.githubusercontent.com/475132/127570007-d810b77f-e1ba-40ea-9a5c-352d9d254066.png)

**Comment by HppZ** [comment]
THANK YOU ALL.


> This feature requires CTA policy to be enabled (China). @HppZ Try using `AppCapability.Create("wifiData").CheckAccess()` to check if your app is being limited.

Do you have any doc about **CTA policy** and AppCapability `wifiData`? I found nothing on google.

**Comment by riverar** [comment]
@HppZ Did it work?

There's not a lot of documentation in the public, I'm afraid.

https://docs.microsoft.com/bs-latn-ba/windows-hardware/customize/desktop/unattend/microsoft-windows-deviceaccess-setregionspecificprivacyaccesspolicy is how OEMs/device manufacturers turn it on. There's no real documentation on what it affects, sorry.

@andrewleader might be able to get more info from the team!

**Comment by HppZ** [comment]
`AppCapability.Create("wifiData").CheckAccess()` always return `Allowed` not matter that switch is on or off.

**Comment by riverar** [comment]
@HppZ Is it a `runFullTrust` desktop app? UWP app? Or?

**Comment by HppZ** [comment]
pure UWP app.

**Comment by riverar** [comment]
@HppZ OK, I'll try building a sample. One more question, can you screenshot "winver" please and paste it here?

**Comment by HppZ** [comment]
![0STAMY((OM7$JAYIU{G%~%C](https://user-images.githubusercontent.com/12285582/127600240-f2138b4f-8d7c-4520-8d1a-9aea84a58331.png)

**Comment by HppZ** [comment]
any update?

**Comment by riverar** [comment]
@HppZ I've verified `AppCapability.Create("wifiData").CheckAccess()` works, but only on machines with active China policies and with cellular capabilities.

**Comment by riverar** [comment]
@HppZ Following up on this, wrote a short blog post about it https://withinrafael.com/2021/12/12/programmatically-determining-uwp-app-can-use-wlan-data-china/
