### ISSUE TITLE
[RNW] GetForCurrentView API alternatives for islands

### ISSUE THREAD

**Issue by asklar** [microsoft/WindowsAppSDK#114]
[React Native for Windows](https://microsoft.github.io/react-native-windows/) doesn't currently _officially_ support islands today (on system xaml nor winui3) but I’m doing work to bring up islands support. 

We have usages of a few WinRT types via GetForCurrentView which won't work in island scenarios, this tracks pursuing alternatives in Reunion that allow us to have a unified calling pattern for both win32 and UWP.

Members of DisplayInformation we use (after doing a GetForCurrentView):
-	DpiChanged
-	ResolutionScale
-	LogicalDpi
-	ScreenWidthInRawPixels, ScreenHeightInRawPixels
These last 2 are used to expose them to the JS side of apps and libraries.

There are a couple of other places where we do things like GetForCurrentView that we’ll need to figure out how to achieve with islands:
-	CoreInputView -> GetCoreInputViewOcclusions -> OcclusionsChanged
We do that to know when the on screen keyboard shows/hides and raise JS events to that effect so that the UI can re-layout.
-	SystemNavigationManager -> BackRequested and AppViewBackButtonVisibility
This might be ok to not hook up in island scenarios if we never have a device with back buttons that can also run Win32 apps
-	ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView() -> QualifierValues -> Lookup(“LayoutDirection”)
This is used to determine whether we should display in RTL or LTR. I’m assuming the alternative is to do GetLayout(hwnd) == LAYOUT_RTL instead?

**Comment by jonwis** [comment]
Thanks - I see a bunch of APIs for this already available to your needs.  You could potentially add the layer of indirection now, then help us make that indirection functionality part of Project Reunion.  For example:

* DPI Change - Recheck the DPI on a window change message
* Resolution Scale - Use `MonitorFromWindow` then `GetScaleFactorForMonitor`
* Logical DPI - Use `GetDpiForWindow`
* Screen physical size - Use `MonitorFromWindow` then `GetMonitorInfo`

**Comment by asklar** [comment]
@jonwis any ideas for the other scenarios? e.g. detecting when the software keyboard shows/hides, etc.?

**Comment by jonwis** [comment]
For soft keyboard, can you use https://docs.microsoft.com/en-us/windows/win32/api/inputpaneinterop/nn-inputpaneinterop-iinputpaneinterop and then https://docs.microsoft.com/en-us/windows/uwp/design/input/respond-to-the-presence-of-the-touch-keyboard ?

What's left?

**Comment by stevewri** [comment]
@asklar - anything left (see Jon's question above)?

**Comment by asklar** [comment]
@stevewri @jonwis I was hoping Reunion would be this magic box I could call an API on and it would just work regardless of context (uwp/island/...). 
So maybe I should step back and ask...what is Reunion/how does it help me write converged uwp/win32 code? :)
(happy to have this discussion offline too)

**Comment by michael-hawker** [comment]
@marb2000 @azchohfi these are the similar transitions needed for XAML Islands, those were all documented somewhere on docs.microsoft.com, right? Any insights here you can provide?

**Comment by imbushuo** [comment]
+1 for case in `DisplayInformation`. In this specifically case, a lot of Win32 applications do not have `CoreWindow` presence, for easier display information retrieval, something like `DisplayInformation.GetForHwnd(hwnd)` should be added. This will make querying HDR information on Win32 apps easier.

**Comment by marb2000** [comment]
@asklar, @imbushuo  I wrote several samples using the Win32 APIs that cover the majority of the gaps that there are in the platform. You can take a look at https://github.com/marb2000/DesktopWindow.  Per the current engineering plan, these functionalities are not in Reunion v1.

**Comment by jeffstall** [comment]
Currently, it is recommended to use the various I*Interop APIs using HWNDs. See 
[IPrintManagerInterop](https://docs.microsoft.com/en-us/windows/win32/api/printmanagerinterop/nn-printmanagerinterop-iprintmanagerinterop) for an example. We are tracking this feature request to make improvements in the future.
