### ISSUE TITLE
WinAppSdk Nuget package should automatically set DPI Awareness in manifest

### ISSUE THREAD

**Issue by evelynwu-msft** [microsoft/WindowsAppSDK#1179]
Currently, the WinAppSdk project templates include a [app.manifest](https://github.com/microsoft/WindowsAppSDK/blob/main/dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/app.manifest) that sets the default DPI awareness for the app. This obviously only works for WinUI apps created using the project template; if a developer were to *add* a reference to WinAppSdk to their existing non-WinUI app, then they would need to create the app.manifest themselves. It'd be really nice if WinAppSdk could handle that boilerplate on developers' behalf.

**Comment by riverar** [comment]
I disagree for several reasons.

1. The developer chose not to use the template, so I don't think you should bother them with more templates.

2. WinUI doesn't require it.

3. I feel like the Windows App SDK is already getting bloated with these built-in implicit behaviors that have to be worked around in other languages / other build systems. I discovered the other day, for example, adding a WinUI dependency to a MSBuild-based project suddenly and unexpectedly activates a bunch of XAML tasks, like bringing in XAML styles I didn't ask for (despite not even having XAML at all).

4. Marking your app as DPI aware comes with [a bunch of responsibility](https://docs.microsoft.com/en-us/windows/win32/hidpi/declaring-managed-apps-dpi-aware) that the developer may not want to take on. They may be perfectly content with no DPI awareness and/or the appcompat scaling the OS provides.

**Comment by sylveon** [comment]
I already have my own app manifest which does declare per monitor V2 DPI support (among other things) and wouldn't want the app SDK messing with it to do something I already do.

**Comment by MarkIngramUK** [comment]
I would much prefer all of the additional "secret" build steps that are activated when adding a package be fully documented, so that we can reproduce all or parts of those steps when using other build systems.
For example, if you make a blank Win32 project, then add a resw file to it, and build your project, nothing happens. The resw file isn't automatically compiled to a .pri file, without adding a reference to the WindowsAppSDK.

**Comment by alwu-msft** [comment]
Thanks for the feedback! The idea is to provide a sensible *default* setting for DPI awareness that developers can choose to override; it should also be noted that this would *supplement* any existing manifest provided by the developer, rather than outright replace it.

**Comment by evelynwu-msft** [comment]
Superseded/obsoleted by https://github.com/microsoft/WindowsAppSDK/pull/1748.

**Comment by riverar** [comment]
@evelynwu-msft That commit just changes the default manfiest contents. This issue covers the scenario where folks add the Nuget to their app. I don't necessarily want that (as outlined above) but to close this seems incorrect. Or are you implicitly saying you are no longer looking to do what you wanted (https://github.com/microsoft/WindowsAppSDK/issues/1179#issuecomment-899760992)?

**Comment by evelynwu-msft** [comment]
> @evelynwu-msft That commit just changes the default manfiest contents. This issue covers the scenario where folks add the Nuget to their app. I don't necessarily want that (as outlined above) but to close this seems incorrect. Or are you implicitly saying you are no longer looking to do what you wanted ([#1179 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/1179#issuecomment-899760992))?

The latter. I feel much less strongly about my original proposal than I used to. :)

**Comment by riverar** [comment]
@evelynwu-msft Sounds good, thanks for closing the loop!
