### ISSUE TITLE
Folder could not be created in ApplicationData Path

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#1181]
**Describe the bug**

It does not seem possible to create a folder in ApplicationData Path
**Steps to reproduce the bug**

Create a folder with the following code

```
var myPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
var _path = Path.Combine(myPath, "Test");
Directory.CreateDirectory(_path);
```

If I change the folder path to the desktop, a folder will be created

**Expected behavior**

Create folder in everywhere
**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.WindowsAppSDK 0.8.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by ghost1372** [comment]
this worked =             `Directory.CreateDirectory(@"C:\Users\Mahdi\AppData\Roaming\Test");`

this worked =   
```
var myPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
var _path = Path.Combine(myPath, "Test");
Directory.CreateDirectory(_path);
```

but `SpecialFolder.ApplicationData` not worked

**Comment by btueffers** [comment]
@ptorr-msft would you be able to provide some insight into this question?

**Comment by ptorr-msft** [comment]
@ghost1372 some questions for you. 

1. What is the final string being passed to `CreateDirectory`?
1. Is this a packaged full-trust MSIX app?
2. What does "not worked" mean -- do you get an exception or do you just not see the folder if you look in Explorer?

**Comment by ghost1372** [comment]
1.  `C:\Users\Mahdi\AppData\Roaming\myNewFolder`
2.  Yes, WinUI 3 Packaged App
3.  No exceptions will be received and the program will not crash, and folder is not created in the desired location and is not seen in File Explorer

I created a project
[App16.zip](https://github.com/microsoft/WindowsAppSDK/files/6943980/App16.zip)

**Comment by ptorr-msft** [comment]
[This is by-design](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes); the folder is created in a private location for your app, so it will be cleanly removed when the app is uninstalled. The folder is there and you can read and write files just like normal. If you want to find the real on-disk location with Explorer, look in `%localappdata%\Packages\Your_package_name`

**Comment by ghost1372** [comment]
@ptorr-msft 
Thank you, my problem was solved, but I realized one thing.
According to the documentation, each folder that is created in the following path

`C:\Users\Mahdi\AppData\Roaming\`

a copy of it is created in the following path (For security and to delete information after uninstalling the program)

`%localappdata%\Packages\Your_package_name\LocalCache\Roaming
`

But I noticed that if the folder already exists in the following path
`C:\Users\Mahdi\AppData\Roaming\myFolder`

information will not be stored in the following path
`%localappdata%\Packages\Your_package_name\LocalCache\Roaming\myFolder
`

And after deleting the program, the information remains

**Comment by ptorr-msft** [comment]
@andreww-msft is this by-design? The docs are a bit ambiguous, but the observed makes sense for compat with existing SxS installed apps. 

Also @ghost1372 please note that the file redirection is not a security mechanism. It's to better isolate apps and make cleaning up private app data easier when the user no longer wants the app.
