### ISSUE TITLE
Proposal: PiP for every Window

### ISSUE THREAD

**Issue by lorisobi** [microsoft/WindowsAppSDK#1199]
# Proposal: PiP for every Window

## Summary
At the moment Picture in Picture is a function only used when app developers want to. But Task Manager shows us ( [Video](https://forums.pureinfotech.com/t/how-to-open-task-manager-always-on-top-even-when-frozen-full-screen-apps/112) ), that keeping a window in foreground could theoretically be universal. An option to keep a window in foreground should be part of the Window title bar right-click-menu.

## Rationale

* speeds up every workflow
* is very intuitive
* no need for dev optimization
* good addition to new Windowing Zones

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow users to have a pip view of every possible window | Must |
| The max-PiP-number is normally 3 | Should |
| This max-PiP-number is adjustable | Could |
| This proposal will stop developers from building specialized PiP-Views in their apps | Mustn't |

## Open Questions
Is this even the right repo for this issue? I hope so.

**Comment by andrewleader** [comment]
Hey @lorisobi, thanks for submitting this idea! This idea is actually more of a Windows user request (since developers wouldn't need to do anything). The right place to submit Windows end-user-related suggestions would be Feedback Hub: https://docs.microsoft.com/en-us/windows-insider/feedback-hub/feedback-hub-app

I'll close this issue here. Thanks!

**Comment by Jaiganeshkumaran** [comment]
Something similar to iPadOS's slideover feature could be done where you add multiple apps to a overlay menu and can switch without disrupting the main screen. Currently 500*500px is the max for compact overlay which might not work well with all UIs so if this feature was added, there should be a way to opt-out.
