### ISSUE TITLE
Contextual Content API for Conversational Agents

### ISSUE THREAD

**Issue by lukeblevins** [microsoft/WindowsAppSDK#120]
# Proposal: Contextual Content API for Conversational Agents

## Summary

The contextual content API would allow the ConversationalAgent to have access to general information from the current foreground app(s). This may include visible images and text. Applications may optionally provide additional context to the conversational agent, so it can produce more intelligent output.

## Rationale

* This capability is present in other systems such as [Android](https://developer.android.com/training/articles/assistant#providing_context), Chrome OS, and (maybe) iOS; and would make bringing conversational agents to the Windows platform more compelling.
* Future accessibility features could leverage the context provided for app information to enhance the functionality.
* Conversational agents like Cortana and Alexa would be empowered to provide output relevant to the apps you're viewing.
* This could leverage the existing **Windows.Media.Ocr** APIs to capture general data from foreground application(s)

This may not be on the roadmap for Project Reunion, which is completely fine, but the Conversation Agent APIs were added to WinRT with the latest stable Windows version (19041). This seems like a logical step forward to enhance their functionality.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Allow developers to capture general information from foreground app(s) for use in their conversational agents upon it being invoked | Must |
| Provide a way for end users to revoke access to this general information in Privacy Settings from conversational agents | Must |
| Easily empower developers to enhance conversational agent output by providing relevant context with the general information captured | Must |
| Provide a way for developers of conversational agents to check if their app is granted this capability. | Must |
| Facilitate exclusion of some/all general information by app developers  | Could |
| Make changes to Cortana so it make use of this newly provided capability | Won't |

## Important Notes

This could introduce a new capability for packaged conversational agent apps: "contextualDataReceiver" . 

Additionally, developers can enable their agent apps so users can easily invoke the conversational agent while, say, viewing a picture online. Saying "Add this to my document" will add the image to their open Word document. No more copying, pasting, and reformatting! The possibilities for users AND developers are endless here.

## Open Questions

Should this functionality be limited to the default conversational agent only?

What format should the contextual information from app developers be provided in? (i.e., JSON, WinUI image/text property)

How can we encourage developers from both areas to make use of this technology?

How else can this technology be used for accessibility purposes?

Are there any form factors where granting this capability to conversational agents would NOT make sense?

**Comment by stevewri** [comment]
In Windows, foreground means the single application which will receive keyboard or other non-locator input. This sounds like the more general idea of any app that has content visible on the screen, is that right?

**Comment by derekpiasecki** [comment]
Have there been any discussions with the clipboard #63 and drag and drop #70 teams?  There are a number of similarities to some of the scenarios this enables that might benefit from some commonality or integration.
