### ISSUE TITLE
Microsoft.ApplicationModel.Resources.ResourceManager.TryGetValue outputs to debug window on failure to find value

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/WindowsAppSDK#1213]
**Description**
`Microsoft.ApplicationModel.Resources.ResourceManager.TryGetValue` outputs to debug window on failure to find a value for the given key. As this is a `Try` API, I don't think it's necessary to log to the debug window - it generates too much noise. I guess it's from an exception being thrown and caught internally, and if that's the case, I would also suggest that throwing and catching an exception is probably a bit excessive when using a `Try` API (a missing key isn't really an exceptional circumstance in this scenario). Example output: 

> D:\a\_work\1\s\dev\MRTCore\mrt\Core\src\MRM.cpp(279)\MRM.dll!00007FFD64CE4FA1: (caller: 00007FFD64CE77C3) ReturnHr(1) tid(aaec) 80073B17 NamedResource Not Found.

**Steps to reproduce**
```
using namespace winrt::Microsoft::ApplicationModel::Resources;
auto factory = winrt::get_activation_factory<ResourceManager, IResourceManagerFactory>();
auto manager = factory.CreateInstance(L"myresources.pri");
auto value = manager.MainResourceMap().TryGetValue("nonexistent_key");
```

**Expected**

Not to output the debug message

**Version Info**
1.0 experimental1

Tested on Windows 10 21H1.

**Comment by huichen123** [comment]
The error comes from WIL (RETURN_IF_FAILED). As the same code is used for TryGetValue and GetValue, it's not trivial to distinguish the behavior. If you are really annoyed by the debug messages, you can disable it by setting wil::g_fResultOutputDebugString to false. But then it will also hide legit errors you may care.

**Comment by MarkIngramUK** [comment]
> As the same code is used for TryGetValue and GetValue

This is what I was suggesting in the original post, they should be separate, or the `GetValue` defined in terms of `TryGetValue`, not the other way around. 

I appreciate this is only minor, but I'd prefer to not globally disable exception messages, because I don't want to miss a legitimate error.

**Comment by huichen123** [comment]
It'd be excessive to distinguish whether the caller is GetValue or TryGetValue (e.g. pass a flag to all the functions down the road). One thing we could do is ignore this specific error, which is the most common reason of using TryGetValue, from WIL from the call stacks of Try/GetValue. If resource is not found, TryGetValue will be quiet, and GetValue will see an exception thus still obvious.

**Comment by MarkIngramUK** [comment]
Thanks @huichen123 👍
