### ISSUE TITLE
Update and standardize markdown specs to WindowsAppSDK

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/WindowsAppSDK#1215]
WindowsAppRuntime and WinAppRuntime should move to WindowsAppSDK in, e.g.:
https://github.com/microsoft/WindowsAppSDK/blob/main/specs/Deployment/MSIXPackages.md

**Comment by DrusTheAxe** [comment]
*Runtime was an intentional decision as part of the ProjectReunion->WindowsAppSDK rename. See https://github.com/microsoft/WindowsAppSDK/pull/1202#issuecomment-897369710

**Comment by Scottj1s** [comment]
Thanks Howard, hard to keep up!
