### ISSUE TITLE
1.0-exp1: WAS runtime installer missing for ARM64

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1221]
A Windows App SDK runtime installer for the `arm64` platform is missing. The redistributable provided in the 1.0.0-experimental1 announcement (https://download.microsoft.com/download/b/8/b/b8b4508e-ea29-4381-85d9-69b824151f8d/Microsoft.WindowsAppSDK.Redist.1.0.0-exp.zip) only contains an installer for x86 and x64 platforms.

MSIX packages for arm64 _are_ included, however.

cc: @DrusTheAxe

**Comment by DrusTheAxe** [comment]
@dkbennett is this due to [Installer build and runtime detection of ARM64 is incorrect #479](https://github.com/microsoft/WindowsAppSDK/issues/479)

**Comment by zaryaf** [comment]
The latest installer does come in ARM64. Closing issue.
