### ISSUE TITLE
PrintManager

### ISSUE THREAD

**Issue by BarcodeResource** [microsoft/WindowsAppSDK#1224]
**Describe the bug**
Is PrintManager supported in v1.0 experimental? Or will it be supported in v1.0 release? 

**Steps to reproduce the bug**

                PrintDocument printDocument = new PrintDocument();
                printDocument.AddPages += new AddPagesEventHandler(printDoc_AddPages);
                //printDocument.Paginate += new PaginateEventHandler(printDoc_Paginate);
                //printDocument.GetPreviewPage += new GetPreviewPageEventHandler(printDoc_GetPreviewPage);
                IPrintDocumentSource printDocumentSource = printDocument.DocumentSource;
                PrintManager printManager = PrintManager.GetForCurrentView();

Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll

"   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)\r\n   
at ABI.Windows.Graphics.Printing.IPrintManagerStatic.global::Windows.Graphics.Printing.IPrintManagerStatic.GetForCurrentView()\r\n   
at Windows.Graphics.Printing.PrintManager.GetForCurrentView()\r\n   
at App7.MainWindow.myButton_Click(Object sender, RoutedEventArgs e) in C:\\Users\\james\\source\\repos\\App7\\App7\\App7\\MainWindow.xaml.cs:line 51"

**Version Info**
Windows App SDK 1.0.0 experimental1

NuGet package version: 
Windows App SDK 1.0.0 experimental1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes  |

**Comment by andrewleader** [comment]
@AdamBraden is PrintManager supported by desktop apps?

**Comment by AdamBraden** [comment]
@angelazhangmsft as FYI.

GetForCurrentView is a CoreWindow concept not supported in WinUI3 desktop apps. You need to use the interop helpers. See:

https://docs.microsoft.com/en-US/windows/apps/desktop/modernize/desktop-to-uwp-supported-api
https://docs.microsoft.com/en-US/windows/apps/desktop/modernize/winrt-com-interop-csharp
https://docs.microsoft.com/en-us/windows/win32/api/printmanagerinterop/nn-printmanagerinterop-iprintmanagerinterop
