### ISSUE TITLE
Win App SDK Template Icons should be different across project types for usability

### ISSUE THREAD

**Issue by mrlacey** [microsoft/WindowsAppSDK#1225]
**Describe the bug**
All the icons in the template selectors (project & item) use the same icon, this adds extra cognitive load to distinguish between them making selection slower and more error prone.

I know you like the new icon but this over-use of it is unhelpful in aiding the ability to distinguish between the different options.

**Steps to reproduce the bug**
Open a New project or new Item dialog

**Expected behavior**

The icons should be unique to help enable differentiation.

**Screenshots**

New Project dialog
![image](https://user-images.githubusercontent.com/189547/68197725-a04a5b80-ffb2-11e9-87dd-d08ed8af65d6.png)

New Item dialog
![image](https://user-images.githubusercontent.com/189547/68197760-ac361d80-ffb2-11e9-9947-9043be0a6d9b.png)

**Version Info**

WinUI 3.0 Alpha (the only public version)

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by bkudiess** [comment]
Transferring this to the WindowsAppSDK repo, seems the appropriate place for it now.

**Comment by SeriouslyWhyIAmAGhost** [comment]
@andrewleader @btueffers this issue should be closed because WinUI 3 is long past the Alpha phase.
