### ISSUE TITLE
Unable to Create new Pages in VS 2022 Preview 3

### ISSUE THREAD

**Issue by jjwb96** [microsoft/WindowsAppSDK#1236]
Been working on a new app using VS 2022 Preview 3 and Windows App SDK 0.8. I tried to add a new item, however there is no option to add a new page.

I had to go back to VS 2019 to add the new page, then I was able to continue working in VS 2022.

**Comment by ryancheung** [comment]
Same issue here, unable to create new projects, it's empty!

**Comment by mrlacey** [comment]
I think this is an issue with the dependencies (prerequisites) specified in the installer and what comes with 17.0.0 Preview 3.0

The installer [lists a dependency](https://github.com/microsoft/WindowsAppSDK/blob/5a9fc9082ea2e6c3558f9d13c0f785c62f550adf/dev/VSIX/Extension/source.extension.vsixmanifest#L42) on "C++ (v142) Universal Windows Platform tools"

BUT, 17p3 includes version 143 of the UWP C++ tools

![image](https://user-images.githubusercontent.com/189547/129488421-66f8f3b5-39fc-486b-9d97-1cd4c96d65f5.png)

142 is just part of the display name, but I can't see anything else that may explain this.

Checking the components available in the VSSetupInstance, I see

Id       : Microsoft.VisualStudio.ComponentGroup.UWP.VC
Version  : 16.10.31205.180

So this shouldn't be an issue.

**Comment by ryancheung** [comment]
So install "C++ (v142) Universal Windows Platform tools" fix this?

**Comment by mrlacey** [comment]
> So install "C++ (v142) Universal Windows Platform tools" fix this?

I don't think so. I was just documenting what I found while investigating. :(

**Comment by alwu-msft** [comment]
The component @mrlacey is referring to is selected via the **Workloads** tab of the VS Installer, as an optional component in the **Installation details** pane on the right. @jjwb96 can you double check that you have this component installed?

![image](https://user-images.githubusercontent.com/50890554/129619687-17fb9d96-78d5-46af-9735-48b0434c8247.png)

**Comment by jjwb96** [comment]
It looks like I don't have it installed. I will install it and report back if I am able to install the Project Reunion extension.

**Comment by jjwb96** [comment]
Looks like that did the trick! Thanks All!

**Comment by ryancheung** [comment]
I have the C++ v143 Universal Windows Platform workload installed but has this issue.

**Comment by alwu-msft** [comment]
> I have the C++ v143 Universal Windows Platform workload installed but has this issue.

@ryancheung You mentioned in your original comment that you had issues creating new **projects** which, at least on the face of it, is distinct from what is described here, which was an inability to add new **pages** to an existing project. Can you double check that you have the project templates extension installed in the version of Visual Studio that you are using (you can check via Extensions > Manage Extensions > Installed)? If, after ensuring that the extension is installed, you still do not have an option to create new WinUI projects, can you please open a new issue?

**Comment by vld-b** [comment]
> The component [@mrlacey](https://github.com/mrlacey) is referring to is selected via the **Workloads** tab of the VS Installer, as an optional component in the **Installation details** pane on the right. [@jjwb96](https://github.com/jjwb96) can you double check that you have this component installed?
> 
> ![image](https://user-images.githubusercontent.com/50890554/129619687-17fb9d96-78d5-46af-9735-48b0434c8247.png)

Yes what a code-saver thank you! This was the solution needed after searching for a few of tens of minutes. Idk how this component disappeared all of a sudden, but reinstalling fixed it!
