### ISSUE TITLE
Please provide final Windows App SDK naming, terms, acronyms

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1250]
Lots of specs and commentary flying around with a mish mash of Windows App runtimes, redists, SDKs, etc. Can you please update the docs/communicate the new terminology?

**Comment by andrewleader** [comment]
Thanks Rafael for bringing that up! To briefly answer (will work on updating docs)...

The full name is "Windows App SDK". For things that don't allow spaces, `WindowsAppSDK`, and for abbreviation, if necessary, `WinAppSDK`. Twitter hashtags are `#WindowsAppSDK`. StackOverflow tag is [`windows-app-sdk`](https://stackoverflow.com/questions/tagged/windows-app-sdk).

**End-user facing pieces** (things they might see when installing an app or looking in All Apps) are called `Windows App Runtime`.

**Comment by mqudsi** [comment]
As another issue I've had w/ the recently released/updated docs for 1.0.0-preview1, @andrewleader can you comment on the disparity between namespaces in the C++ API and in the C# API? Is it intended for the same (effective) APIs to ultimately be exposed from both? The docs are completely silent on the scope of the WinRT APIs exposed by the WindowsAppSDK packages for C++ vs C#, and it (currently) seems that more low-level WinRT APIS are available via the C++ API (e.g. I just looked at the docs again and the first such thing I ran into was `ActivationRegistrationManager`) but not in the C# API.

**Comment by andrewleader** [comment]
@mqudsi I believe the lack of some C# projections is just a temporary oversight and something our team is working on addressing, @DrusTheAxe were you working on some of those? We definitely plan on having the APIs available by both C++ and C# 😊

**Comment by DrusTheAxe** [comment]
> disparity between namespaces in the C++ API and in the C# API? Is it intended for the same (effective) APIs to ultimately be exposed from both? The docs are completely silent on the scope of the WinRT APIs exposed by the WindowsAppSDK packages for C++ vs C#, and it (currently) seems that more low-level WinRT APIS are available via the C++ API (e.g. I just looked at the docs again and the first such thing I ran into was `ActivationRegistrationManager`) but not in the C# API.

As @andrewleader notes we do intend full fidelity for C# developers. Which C# are you using - .NET Core or .NET Framework, and what verison?

WinRT APIs should be directly consumable by .NET Framework.

For .NET Core we're providing projections (via C#/WinRT for the implementation). That coverage is partially complete with more coming online. For instance, I just checked in [Added C# WinRT projections for DynamicDependency and AppLifecycle WinRT APIs #1208](https://github.com/microsoft/WindowsAppSDK/pull/1208) providing C# projection APIs for AppLifecycke and DynamicDependency APIs, MRT Core already had projections and I'm aware of others are in progress.

WinRT is our primary vehicle for APIs with a few Flat-C APIs (for reasons), and projections are the mechanism we're using to bring them to C# developers. The only API I'm aware of that's only Flat-C (no WinRT) is the Bootstrap API...and I'm working on a C# equivalent :-)

Regardless of implementation, full functionality should be available to C# (in natural C#-friendly ways). Everything's not in the box yet but we're working on it. If you see gaps please inquire as they _should_ merely be a matter of timing, not intent - and if we overlooked something we're very keen to identify and correct it.

Thank you for your patience and assistance in helping to make Windows App SDK a roaring success.

**Comment by DrusTheAxe** [comment]
> WinRT is our primary vehicle for APIs with a few Flat-C APIs (for reasons), and projections are the mechanism we're using to bring them to C# developers. The only API I'm aware of that's only Flat-C (no WinRT) is the Bootstrap API...and I'm working on a C# equivalent :-)

Speak the devil's name and he shall appear... 😄 

[Add Bootstrap C# API. Spec Bootstrap C# and get GenerationId (Flat-C/WinRT) APIs #1274](https://github.com/microsoft/WindowsAppSDK/pull/1274)

**Comment by mqudsi** [comment]
Yup, the bootstrap api was the second one I noticed missing. 

If I have issues with factually incorrect statements  in the new docs prior to the final release, should I post them here or use the “report an issue” button to open an issue in the overall msdn GitHub repo?

**Comment by riverar** [comment]
> If I have issues with factually incorrect statements  in the new docs prior to the final release, should I post them here or use the “report an issue” button to open an issue in the overall msdn GitHub repo?

Add your comments to the PR. Am eager to hear what you think is factually incorrect.

**Comment by mqudsi** [comment]
Sorry, I wasn’t referring to the bootstrap api PR. In fact, I was mistaken - I followed a link from the Windows App SDK docs that took me to the UWP docs but I didn’t realize it and thought I was still on the new docs site. 

(It’s that GetActivatedEventArgs() doesn’t  return null if called twice under Windows App SDK, but of course that was for UWP.. My bad!)

**Comment by riverar** [comment]
Closing this. It's mostly done and is an ongoing effort.
