### ISSUE TITLE
Incorrect Dialog when starting WinUI project

### ISSUE THREAD

**Issue by btueffers** [microsoft/WindowsAppSDK#1252]
**Steps to reproduce the bug**

1. Following the instructions on starting a new app here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui
2. The dialog box for choosing platform versions mentions UWP rather than WinUI.

**Screenshots**
![image](https://user-images.githubusercontent.com/82911735/129616866-45c182f3-5911-46a8-930b-309e33fce2f7.png)

**Comment by AdamBraden** [comment]
@alwu-msft are you customizing this dialog as part of your single project packaging work? Or do we need to sync with VS on updates?

**Comment by Jaiganeshkumaran** [comment]
Since the dialog isn't just for UWP or WinUI apps but also things like the packaging project, it could be renamed to New Windows project. Also it should say your Windows project and not application because it doesn't need to be an application.

**Comment by haonanttt** [comment]
The dialog's wording already changed
