### ISSUE TITLE
Can't exit full-screen

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#1255]
**Describe the bug**
When setting the AppWindow Presenter to FullScreen, you can't return back to overlapped.

**Steps to reproduce the bug**
Create a new WinUI C# Desktop app.

Add the following code:
```cs
        [System.Runtime.InteropServices.DllImport("Microsoft.UI.Windowing.Core.dll", CharSet = System.Runtime.InteropServices.CharSet.Unicode)]
        private static extern IntPtr GetWindowIdFromWindowHandle(IntPtr hwnd, out Microsoft.UI.WindowId result);

        private void ToggleFullscreen()
        {
            var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            GetWindowIdFromWindowHandle(hwnd, out var windowId);
            var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
            System.Diagnostics.Debug.WriteLine($"Presenter: {appWindow.Presenter.Kind} WindowID={ windowId.Value} hwnd={hwnd}");
            if (appWindow.Presenter.Kind == Microsoft.UI.Windowing.AppWindowPresenterKind.Overlapped)
            {
                var result = appWindow.TrySetPresenter(Microsoft.UI.Windowing.AppWindowPresenterKind.FullScreen);
                System.Diagnostics.Debug.WriteLine("Entering Fullscreen result: " + result);
            }
            else
            {
                var result = appWindow.TrySetPresenter(Microsoft.UI.Windowing.AppWindowPresenterKind.Overlapped);
                System.Diagnostics.Debug.WriteLine("Exiting Fullscreen result: " + result);
            }
        }
```
In the `myButton_Click` method replace the method body with a call to `ToggleFullscreen();`

Run the application and click the button to enter full-screen. Click it again to try and exit but observe it stays full-screen (subsequent clicks does correctly change the presenter to fullscreen, but still won't exit).

Also see output window showing the second click it doesn't detect it is already in full-screen:
```
Presenter: Overlapped WindowID=3084970 hwnd=3084970
Entering Fullscreen result: True
Presenter: Overlapped WindowID=3084970 hwnd=3084970
Entering Fullscreen result: True
Presenter: FullScreen WindowID=3084970 hwnd=3084970
Exiting Fullscreen result: True
Presenter: Overlapped WindowID=3084970 hwnd=3084970
Entering Fullscreen result: True
Presenter: FullScreen WindowID=3084970 hwnd=3084970
Exiting Fullscreen result: True
```

**Expected behavior**
App exits full-screen.

**Version Info**

NuGet package version: 
1.0.0-experimental1.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

I noticed that if I perform the toggle the fullscreen mode like this, it does actually exit full-screen:
```
        private async void ToggleFullscreen()
        {
            var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
            GetWindowIdFromWindowHandle(hwnd, out var windowId);
            var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
            appWindow.TrySetPresenter(Microsoft.UI.Windowing.AppWindowPresenterKind.FullScreen);
            await System.Threading.Tasks.Task.Delay(2000); // wait 2 seconds
            appWindow.TrySetPresenter(Microsoft.UI.Windowing.AppWindowPresenterKind.Overlapped);
        }
```
Not sure why that is though. The `windowId` and `appWindow` returned are the same, so it doesn't appear because it changes.

**Comment by andrewleader** [comment]
Hey @rkarman, any ideas on this AppWindow bug?

**Comment by rkarman** [comment]
Yeah, @dotMorten and I have been talking on Twitter ahead of this issue being created, and I've asked the dev team to take a look at it since I can't repro it with the sample project but can when using the "create new project" from the official 1.0-experimental SDK. 🤔

**Comment by dotMorten** [comment]
The plot thickens:
![fullscreen](https://user-images.githubusercontent.com/1378165/129649782-84849947-9f4d-45bf-ae41-ba0e8fc93759.gif)

**Comment by rkarman** [comment]
Yeah, something seems to be out of sync in the platform here, but only for the FullScreen presenter so there's clearly a bug hiding there. Interesting that it does not show up in the sample project, but does when using the "create new WAP" from the Experimental release install in Visual Studio. The plot indeed thickens... I've added some additional information and pointed to this issue from our internal tracking and will make sure it gets assigned and prioritized.

**Comment by riverar** [comment]
Peeking at the internals, it appears `Microsoft.UI.Windowing.AppWindow.GetFromWindowId` creates a new `AppWindow` instance every time it's called. I suspect whatever backs the presenter stuff is getting trashed and re-created leading to this out-of-sync behavior.

It's not clear if this API is safe to call multiple times, the documentation doesn't say either way. But do observe how [the documented sample caches a single instance forever](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview).

Caching the AppWindow instance as documented does resolve the issue.

**Comment by dotMorten** [comment]
@riverar Nice find. Confirmed that caching the instance does help.

**Comment by rkarman** [comment]
The state should be in sync across all AppWindow objects that are backed by the same WindowId/HWND. But yes, caching is definitely the way to go, if possible, in your app code.

**Comment by dotMorten** [comment]
Caching is problematic for SDKs though, who might have one cache, and the application have another.

**Comment by rkarman** [comment]
Following back up on this. We have a fix for this issue and it will be included in the next SDK release. Thanks for diving into it and bringing it to our attention!

**Comment by thombrink** [comment]
@rkarman did de fix include a rename/relocation of the GetWindowIdFromWindowHandle? After installing 1.0 preview 1 it can't be found in Microsoft.UI.Windowing.Core.dll anymore.

**Comment by rkarman** [comment]
Yes, Preview 1 changed the name of the DLL, as per the [documentation](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/windowing/windowing-overview). The C# sample should have been updated along with this. Hey, @samanthamsong is there a PR sitting for updating sample here? If not, I'll go create one.

**Comment by rkarman** [comment]
Thanks for confirming @riverar ! Regarding the import: With Preview 2 you can stop using imports and instead use the newly added WinRT wrappers for this: Microsoft.UI.Win32Interop.GetWindowIdFromWindow(windowId).
