### ISSUE TITLE
[Bug] ExtendViewIntoTitleBar = true renders differently between Xamarin Forms/UWP and MAUI/WinUI3

### ISSUE THREAD

**Issue by Daniellled** [microsoft/WindowsAppSDK#1266]
**Describe the bug**
When `ExtendViewIntoTitleBar` is set to `true` this causes the titlebar not to show up in MAUI. However on Xamarin Forms/UWP the titlebar does not show up but the minimize, maximize and close buttons show up and can be styled.

**Steps to reproduce the bug**

_Xamarin_
1. Create a new xamarin app
2. In the UWP application open the App.xaml.cs
3. Add the following code to the OnLaunched method
`CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = true;`

_MAUI_
1. Create a new maui app - Run `dotnet new maui`2. 
2. In the WinUI application open the Platform/Windows/App.xaml.cs
3. Add the following code to the OnLaunched method
`MauiWinUIApplication.Current.MainWindow.ExtendsContentIntoTitleBar = true;`

**Expected behavior**

The UWP and MAUI applications would either both show the minimize, maximize, and close buttons or they wouldn't

**Screenshots**

-Xamarin-
![image](https://user-images.githubusercontent.com/83433189/129976903-2373cf68-79b3-436b-81f4-4ca65b188f42.png)

-MAUI-
![image](https://user-images.githubusercontent.com/83433189/129977068-9454feb7-ecef-4625-bbfc-85f4a91d915c.png)

**Version Info**

NuGet package version: 

Microsoft.ProjectReunion 0.8.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |

**Additional context**

**Comment by btueffers** [comment]
Hi @Daniellled, thanks for the feedback! This appears to be an issue related to the .Net Maui team. Please file it under that teams [repo](https://github.com/dotnet/maui) for them to appropriately triage!
