### ISSUE TITLE
[Use32] Common controls lack Windows 11 style

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/WindowsAppSDK#1273]
**Describe the bug**
The major common controls in Windows 11 have been repainted to support the new design theme, however, there are still many parts that have been left out (and haven't been updated since Windows 7/Vista) and still show the old design. This feels very out of place and gives an overall "cheap" feeling to Win32 apps.

**Expected behavior**
Every visual style & part of common controls should be updated to match the Windows 11 theme. WinRT XAML controls have every part of them updated, so Win32 common controls shouldn't be left out either.

**Screenshots**

**Old expand/collapse button from ListView control**
![image](https://user-images.githubusercontent.com/42058942/130163770-e149eb96-681a-45c3-aa23-9c497fa1df18.png)

**ComboBox/ComboBoxEx control still uses old-style dropdown (no rounded corners, light Win11 colors, or newer shadows**
![image](https://user-images.githubusercontent.com/42058942/130164141-0b1c7e74-49c4-4ea0-aac2-f45764494d52.png)

**DateTime control has same issues as ComboBox control**
![image](https://user-images.githubusercontent.com/42058942/130164273-3cbc975a-4e50-47db-9f93-fece2fa23e6e.png)

**ListBox has same problem as ComboBox/ComboBoxEx**
![image](https://user-images.githubusercontent.com/42058942/130164597-b0516d04-ad0a-4d1e-8ecd-82a646d81f72.png)

Any control that scrolls (Listview/Listbox,ComboBox, etc.) has had this annoying problem for *years* where if you scroll with the mouse wheel the scroll is laggy and jumps from position to position. It would be nice to see this finally fixed.

**Spin control uses old style buttons with older theme colors**
![image](https://user-images.githubusercontent.com/42058942/130164826-b4d6720b-5bcc-42db-b6bc-b5d1b7cbc007.png)

**New edit control has blue line underneath scrollbars**
![image](https://user-images.githubusercontent.com/42058942/130164904-34255c7c-e899-4c7e-9bd9-011e9e874681.png)

**New edit control does not properly render the cursor when height is low**
![image](https://user-images.githubusercontent.com/42058942/130165046-29b968d8-85d6-463b-865c-1a9a9b56f84d.png)

Also important: Windows with the `WS_BORDER` style still have a solid, flat black line that borders them. This border looks out of place with Win11 design language, especially with Win11 placing so much emphasis on "elevation" in its UIs.

| Windows 11 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.132)              | Yes   |

**Additional context**
There are so many more shortcomings with win32 common control styling; this list is nowhere near complete, I just didn't post everything so that this wouldn't be a super long issue.

**Comment by asklar** [comment]
The win32 Common controls are not part of the WindowsAppSdk, please file feedback via Feedback Hub.

**Comment by riverar** [comment]
@asklar When shuffling people off to Feedback Hub, it's critical that you tell them where to file feedback to trigger the correct on-demand traces. Which categories/subcategories do you suggest they use for this particular problem?

**Comment by asklar** [comment]
there are no comctl-specific traces so any general profile should work. Developer platform->All other issues for example.

**Comment by AzAgarampur** [comment]
Feedback is here https://aka.ms/AAdks7i
