### ISSUE TITLE
GetActivatedEventArgs() returns null for unsupported activation types

### ISSUE THREAD

**Issue by mqudsi** [microsoft/WindowsAppSDK#1280]
I have observed GetActivatedEventArgs() returning null (immediately after entering user code in a custom Program.cs) in packaged WinMain applications under Project Reunion 0.8.x and Windows App SDK 1.0.0-experimental1.

I have a hunch that this might be because the kind of activation is one of the ~34 other types that @andreww-msft didn't explicitly mention (Launch, File, Protocol, StartupTask, ToastNotification, ShareTarget, CommandLine, Restart). 

Is it intended for this API to return null if the ActivationKind is not explicitly handled/propagated in the WinAppSDK? Shouldn’t it return ActivationType.Other/Unknown for that one field but at least return an object in response to the call?

Separately, is there no way for packaged (or unpackaged) WinMain apps to handle being activated in response to such an event, even if it requires manually piecing together an instance of IActivatedEventArgs from various, disjoint sources and then invoking App.OnActivated/App.OnBackgroundActivated/etc yourself?

If the answer is no, might I humbly request also handling background task invocation? (Registering a COM CLSID to handle background tasks is only available on 2004, and I really need to target at least 18362.)

**Comment by andreww-msft** [comment]
Hi mqudsi - apologies for the delay in replying. Can you clarify: exactly what kind of activation are you using in your WinMain app that isn't one of the ones we've provided support for so far?

**Comment by mqudsi** [comment]
@andreww-msft this is upon background activation.

> that isn't one of the ones we've provided support for so far?

[Per the Windows App SDK documentation](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation),  

> Packaged apps that use the Windows App SDK support all 44 of UWP's activation kinds. Each activation kind has its own corresponding implementation of IActivatedEventArgs which contain properties relevant to that specific kind of activation.

but at the top of the page, it also lists just 4 activation types that are supported in the API… but like I was saying, I would expect an enum  to return a default value of ActivationKind.Unknown rather than an unholy `null`

**Comment by andreww-msft** [comment]
Thanks @mqudsi for the feedback. We've updated the docs to clarify the null return and supported activation types: https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.getactivatedeventargs?view=windows-app-sdk-1.0
