### ISSUE TITLE
RS5 Compatibility: GetCurrentPackageInfo2 not available through DynDep

### ISSUE THREAD

**Issue by huzaifa-d** [microsoft/WindowsAppSDK#1287]
**Describe the bug**

APIs that use FrameworkUDK fail to be called on RS5 systems.

**Steps to reproduce the bug**

The CPPTestApp from ReunionInternal can be used to repro.
Changes in user/modanish/PowerNotif-IntegTest branch.
1. Build the solution and deploy the test on a RS5 VM.
2. Run the test using te.exe
3. Optionally, run the test app and press the "Power Supply Status" button.

**Expected behavior**

API call expected to succeed.

**Screenshots**

![image](https://user-images.githubusercontent.com/16077119/130300766-1b90d819-fdec-4de1-852a-011954d89da6.png)

**Version Info**

NuGet package version: 

1.0.0-20210819.1-CI

RS5_Release_SVC_2110c

**Additional context**

**Comment by asklar** [comment]
@JesseCol

**Comment by JesseCol** [comment]
I don't think this is a FrameworkUdk issue -- as far as I can tell, the GetCurrentPackageInfo2 simply doesn't exist in RS5.

**Comment by huzaifa-d** [comment]
I agree. The only thing is that my APIs have a reliance on FUDK so I didn't know how to title the bug better. Other AppSDK APIs seem to be running fine.

**Comment by asklar** [comment]
thanks - so this isn't a fudk issue but either the app/test needs to be updated, or the API needs to be polyfilled on rs5

**Comment by huzaifa-d** [comment]
Agreed.

**Comment by DrusTheAxe** [comment]
The problem is `GetCurrentPackageInfo2` doesn't exist in RS5. Dynamic Dependencies needs to use it when available and thus play nice on all releases down to RS5.

Working on it...

**Comment by DrusTheAxe** [comment]
> The problem is `GetCurrentPackageInfo2` doesn't exist in RS5

There's a 2nd problem: `GetPackageInfo2` doesn't exist in RS5 either (shocking, I know :P).

I've got a branch with the former addressed. The latter is a little more involved due to internal implementation reasons, threading the code through several layers to address the problem is a little complex (in the time-consuming sense, not rocket-science). Workingh on it.
