### ISSUE TITLE
UWP apps should better handle unsaved/working data to prevent accidental data loss during App Updating.

### ISSUE THREAD

**Issue by 77376** [microsoft/WindowsAppSDK#129]
# Proposal: UWP apps should  better handle unsaved data to prevent data loss during App Updating

**Comment by jonwis** [comment]
Is your app [handling suspend/resume](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/suspend-an-app) already? The same mechanism (suspend, terminate, update, resume) is used during any package updates.

**Comment by m98770** [comment]
> Is your app [handling suspend/resume](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/suspend-an-app) already? The same mechanism (suspend, terminate, update, resume) is used during any package updates. 

It is handling suspend/resume already. Still updating the app package locally neither suspend the unsaved documents nor resume it .  It actually terminates all the instances of the app right after installing updates. thus losing unsaved/working data. Actually this is the case with almost every other UWP apps. Any documentation using the same suspend/resume mechanics during package updating ?

**Comment by ecovio1** [comment]
I agree with the OP that all packaged apps be it win32 or UWP suffer from this Packaged Apps Update issue. they never save **_the current app data state_** during package updates and also never **_restarts itself_** after an update has been installed. so if an update has been installed all the unsaved data gets lost.😕

I will like Project Reunion consider & provide something like :.

installing package updates (store or I myself locally through App Installer) ➡ check if the app is open ➡ if not open , apply update silently ||| or if open, save all the unsaved current working data/app state ➡ terminate the process & apply package updates ➡ restart the app itself and restore the all the unsaved current working data/app state.           everybody happy.         

This is a pain and needs to be fixed ASAP.

**Comment by ecovio1** [comment]
I agree with the OP that all packaged apps be it win32 or UWP suffer from this Packaged Apps Update [issue](https://github.com/microsoft/ProjectReunion/issues/129).   they just never save **_the current app data state_** during package updates and also never **_restarts itself_** after an update has been installed. so if an update has been installed all the unsaved data gets lost.😕

I will like Project Reunion consider & provide something like :.

installing package updates (store or I myself locally through App Installer) ➡ check if the app is open ➡ if not open , apply update silently ||| or if open, save all the unsaved current working data/app state ➡ terminate the process & apply package updates ➡ restart the app itself and restore the all the unsaved current working data/app state.           everybody happy.         

This is a pain and needs to be fixed ASAP.

**Comment by ecovio1** [comment]
I agree with the OP that all packaged apps be it win32 or UWP suffer from this **Packaged Apps Update** issue.   they just never save **_the current app data state_** during package updates and also never **_restarts itself_** after an update has been installed. so if an update has been installed all the unsaved data gets lost.😕

I will like Project Reunion consider & provide something like :.

installing package updates (store or I myself locally through App Installer) ➡ check if the app is open ➡ if not open , apply update silently ||| or if open, save all the unsaved current working data/app state ➡ terminate the process & apply package updates ➡ restart the app itself and restore the all the unsaved current working data/app state.           everybody happy.         

This is a pain and needs to be fixed ASAP.

**Comment by ecovio1** [comment]
I agree with the OP that all packaged apps be it win32 or UWP suffer from this **Packaged Apps Update** issue.   they just never save **_the current app data state_** during package updates and also never **_restarts itself_** after an update has been installed. so if an update has been installed all the unsaved data gets lost.😕

This is a pain and needs to be fixed ASAP.


I will like Project Reunion consider & provide something like :.

installing package updates (store or I myself locally through App Installer) ➡ check if the app is open ➡ if not open , apply update silently ||| or if open, save all the unsaved current working data/app state ➡ terminate the process & apply package updates ➡ restart the app itself and restore the all the unsaved current working data/app state.           everybody is  happy. 👍

**Comment by jonwis** [comment]
We'll check into this, thanks for the report.  If you can, collect a feedback hub trace during an update (Win+F, category "Install and Update" subcategory "App installation issues"). Use the "reproduce while collecting data" option.  Somewhere in the description add "from project reunion 129" or "task 30813592" so we can find it more easily.

Windows folks, reference http://task.ms/30813592

**Comment by ecovio1** [comment]
@jonwis  Done !! https://aka.ms/AAaei0v

**Comment by stevewri** [comment]
See also https://github.com/microsoft/ProjectReunion/issues/300

**Comment by kanismohammed** [comment]
> > Is your app [handling suspend/resume](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/suspend-an-app) already? The same mechanism (suspend, terminate, update, resume) is used during any package updates.
> 
> It is handling suspend/resume already. Still updating the app package locally neither suspend the unsaved documents nor resume it . It actually terminates all the instances of the app right after installing updates. (and Of course the app model never let devs, to ask the user to save or cancel current state.) thus losing unsaved/working data. Actually this is the case with almost every other UWP apps including Microsoft Store itself. Any documentation explaining usage of the same suspend/resume mechanism during package updating ?

**Comment by kanismohammed** [comment]
> > Is your app [handling suspend/resume](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/suspend-an-app) already? The same mechanism (suspend, terminate, update, resume) is used during any package updates.
> 
> It is handling suspend/resume already. Still updating the app package locally neither suspend the unsaved documents nor resume it . It actually terminates all the instances of the app right after installing updates. (and Of course the app model never let devs, to ask the user to save or cancel current state.) thus losing unsaved/working data. Actually this is the case with almost every other UWP apps including Microsoft Store itself. Any documentation explaining usage of the same suspend/resume mechanism during package updating ?

This [documentation ](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle) goes over app suspension and the deferrals that are required to prevent the app from suspending until the save is complete. Please take a look at the app suspend section in the document. If you have called these API's in your app, please file a feedback through the feedback hub with a repro of your app update under the section Developer Platform -> App Deployment. This would collect the necessary logs for us to diagnose the specific issue that you are hitting.

**Comment by kanismohammed** [comment]
> I agree with the OP that all packaged apps be it win32 or UWP suffer from this **Packaged Apps Update** issue. they just never save **_the current app data state_** during package updates and also never **_restarts itself_** after an update has been installed. so if an update has been installed all the unsaved data gets lost.😕
> 
> This is a pain and needs to be fixed ASAP.
> 
> I will like Project Reunion consider & provide something like :.
> 
> installing package updates (store or I myself locally through App Installer) ➡ check if the app is open ➡ if not open , apply update silently ||| or if open, save all the unsaved current working data/app state ➡ terminate the process & apply package updates ➡ restart the app itself and restore the all the unsaved current working data/app state. everybody is happy. 👍

Package update goes through the same flow that you have described above. It supports both silent updates and force updates. In case of silent updates, the package is not updated while the app is running. Platform would wait for the user to close the app before updating the package. In case of force updates, the apps are sent a suspend notification and then terminated. This documentation goes over app suspension and the deferrals that are required to prevent the app from suspending until the save is complete. Please take a look at the app suspend section in the document. 

Feedback that you provided does not capture any repro. Can you please file a feedback through the feedback hub with a repro of your app update under the section Developer Platform -> App Deployment. This would collect the necessary logs for us to diagnose the specific issue that you are hitting.

**Comment by ecovio1** [comment]
@kanismohammed  Thanks for the app update scenario clarification. 

>In case of force updates, the apps are sent a suspend notification and then terminated. This [documentation ](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle)goes over app suspension and the deferrals that are required to prevent the app from suspending until the save is complete. Please take a look at the app suspend section in the document.

Does the same UWP specific save-suspend-resume mechanism apply to **_a packaged win32 app_** also?

Win32 apps don't support this suspend-save-resume scenario at least not yet. so, what happens when a user forcibly updates a running win32(packaged)  app? does the app immediately terminate all of its instances and thus also lose those current unsaved data?

> Feedback that you provided does not capture any repro. Can you please file a feedback through the feedback hub with a repro of your app update under the section Developer Platform -> App Deployment. This would collect the necessary logs for us to diagnose the specific issue that you are hitting.

Sorry. For some reason , my machine is not sending the diagnostics.zip file.  here https://aka.ms/AAah8ox, I've attached it manually. now it should be there.

**Comment by kanismohammed** [comment]
> @kanismohammed Thanks for the app update scenario clarification.
> 
> > In case of force updates, the apps are sent a suspend notification and then terminated. This [documentation ](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle)goes over app suspension and the deferrals that are required to prevent the app from suspending until the save is complete. Please take a look at the app suspend section in the document.
> 
> Does the same UWP specific save-suspend-resume mechanism apply to **_a packaged win32 app_** also?
> 
> Win32 apps don't support this suspend-save-resume scenario at least not yet. so, what happens when a user forcibly updates a running win32(packaged) app? does the app immediately terminate all of its instances and thus also lose those current unsaved data?
> 
> > Feedback that you provided does not capture any repro. Can you please file a feedback through the feedback hub with a repro of your app update under the section Developer Platform -> App Deployment. This would collect the necessary logs for us to diagnose the specific issue that you are hitting.
> 
> Sorry. For some reason , my machine is not sending the diagnostics.zip file. here https://aka.ms/AAah8ox, I've attached it manually. now it should be there.

For Win32 apps, We follow the RestartManager shutdown logic
   1. WM_QUERYENDSESSION is sent to all processes.
   2.  WM_ENDSESSION/WM_WMCLOSE is sent to windows applications & Ctrl+C to console applications.
We use the information registered in the RestartManager (if any) to restart the packaged win32 apps. But we do restart all apps even if they are not registered with RestartManager. 

Let me dig into the logs in the feedback and get back to you.

**Comment by andreww-msft** [comment]
We have investigated this issue thoroughly, including the logs provided, and the platform is following the standard suspend-before-terminate flow. UWP apps have the opportunity to save state during suspend. Unpackaged Win32 apps can use the RestartManager as described above. So, the requirement is already covered for both packaged and unpackaged apps, using one or other of the techniques available today. Note however that we are considering extending Restart behavior in the Windows App SDK for the 1.1 release. More details to follow.

**Comment by mg-christian-axelsson** [comment]
Out of curiosity, what's the alternative for UWP applications that can't save its state in a manner that makes them resumable. I'm (of course) talking about Windows Terminal (https://github.com/microsoft/WindowsAppSDK/issues/300) where one could have running processes in a shell , open remote connections doing all kind of things on the remote side, etc.
