### ISSUE TITLE
No Close() on DataWriter

### ISSUE THREAD

**Issue by mlynch** [microsoft/WindowsAppSDK#1294]
**Describe the bug**

There is no method available to `Close()` a `DataWriter` or the `IRandomAccessStream` that comes from `file.OpenAsync`. Either there is a bug in the Windows App SDK version of `DataWriter` or the documentation is wrong (this is all I could find: https://docs.microsoft.com/en-us/uwp/api/windows.storage.streams.datawriter?view=winrt-20348)

**Version Info**

`0.8.1` of  `Microsoft.ProjectReunion` and the `Foundation` and `WinUI` packages.

NuGet package version: 

Version	10.0.19042 Build 19042

**Comment by Jaiganeshkumaran** [comment]
@mlynch Are you using C#? The Close method of the IClosable interface is mapped to Dispose so you can call Dispose instead or use an using statement.

**Comment by mlynch** [comment]
Ah okay, seeing that now. I'm porting some UWP JS over so it makes sense that I was confused by that existing in JS but not in C#. Closing.
