### ISSUE TITLE
Published app uses newer WinUI version than specified in appinstaller file

### ISSUE THREAD

**Issue by Marv51** [microsoft/WindowsAppSDK#1296]
**Describe the bug**
My app is broken in 0.8.2 because of microsoft/CsWinRT#971. So I stay on 0.8.1 for now. 

But if I build and release a msix package, if I install it on a device with another app installed that requires 0.8.2, then my app crashes on launch. Leading me to suspect that it is loading 0.8.2 instead and triggering the exception.

**Steps to reproduce the bug**
Have app that requires 0.8.2. Install via appinstaller file. 

Extract from appinstaller file:
```xml
<Dependencies>
  <Package
     Name="Microsoft.ProjectReunion.0.8"
     Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"
     ProcessorArchitecture="x64"
     Uri="file:///[my path]/Dependencies/x64/Microsoft.ProjectReunion.0.8.msix"
     Version="8001.186.2159.0" />
```

In Powershell after install I notice 

```
PS C:\Users\Marvin> Get-AppxPackage -Name Microsoft.ProjectReunion.0.8

Name              : Microsoft.ProjectReunion.0.8
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 8002.222.1805.0
PackageFullName   : Microsoft.ProjectReunion.0.8_8002.222.1805.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8002.222.1805.0_x64__8wekyb3d8bbwe
IsFramework       : True
PackageFamilyName : Microsoft.ProjectReunion.0.8_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

Notice how the installer file request version 800**1**.186.2159.0 but the installed version is 800**2**.222.1805.0.

**Expected behavior**
I thought the whole reason to decouple WinUI from the OS was to make this kind of thing impossible?

**Version Info**

NuGet package version: 
WinUI 3 - Windows App SDK 0.8: 0.8.1-2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |  

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by AdamBraden** [comment]
The root cause of this issue was fixed. For information on deployment options see https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deployment-architecture
