### ISSUE TITLE
Windows.Data.Html.HtmlUtilities.ConvertToText crash.

### ISSUE THREAD

**Issue by HppZ** [microsoft/WindowsAppSDK#1326]
![image](https://user-images.githubusercontent.com/12285582/131138896-3248a3c4-94dd-4888-8cde-c37ec8d067d9.png)
can't repro in demo app.

uwp app.
windows 19042.985
Microsoft.NETCore.UniversalWindowsPlatform 6.2.12

**Comment by btueffers** [comment]
Hi @HppZ, since this doesn't look directly related to the Windows App SDK the more appropriate forum for this question would be the [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)

**Comment by HppZ** [comment]
SH*T
