### ISSUE TITLE
DataTransfer.ShowShareUI() throws COMException: 'Element not found.

### ISSUE THREAD

**Issue by mlynch** [microsoft/WindowsAppSDK#1335]
**Describe the bug**

When calling the `DataTransfer.ShowShareUI()` method, the `System.Runtime.InteropServices.COMException: 'Element not found.` exception is thrown.

**Steps to reproduce the bug**

Build a WinUI3 and Windows App SDK non-sandboxed project, and call `DataTransfer.ShowShareUI()` and this exception will be thrown.

**Expected behavior**
The share UI is shown

**Version Info**
Project Reunion 0.8.1
Windows 10

**Comment by btueffers** [comment]
Hi @mlynch, are you using MSIX? For unpackaged apps Share is not yet supported.

**Comment by mlynch** [comment]
I think so. I'm building a C# win32 app with Windows App SDK, not a sandboxed UWP app

**Comment by andrewleader** [comment]
@mlynch does your project have two projects, one called (Package) as seen below?

![image](https://user-images.githubusercontent.com/13246069/131393708-273590ac-1711-4618-899d-ff0c2d6e0cf3.png)

**Comment by mlynch** [comment]
@andrewleader yep, just like that. Started using the Project Reunion VS Extension's WinUI3 C# Desktop template https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion&ssr=false

**Comment by andrewleader** [comment]
Thanks - that means you're using MSIX and are a packaged desktop app.

To use the DataTransfer APIs, you need to associate them with your window, which needs to be done manually since this isn't a UWP app.

Right now, the steps to do that are a bit complicated, hopefully in a future version of the Windows App SDK we can improve this.

1. Install the [`
System.Runtime.InteropServices.WindowsRuntime` NuGet package](https://www.nuget.org/packages/System.Runtime.InteropServices.WindowsRuntime/).
1. Create a new class file called `DataTransferManagerHelper.cs` and put this code in it and then use IntelliSense suggestions to add the using statements...

```csharp
    static class DataTransferManagerHelper
    {
        static readonly Guid _dtm_iid = new Guid(0xa5caee9b, 0x8708, 0x49d1, 0x8d, 0x36, 0x67, 0xd2, 0x5a, 0x8d, 0xa0, 0x0c);

        static IDataTransferManagerInterop DataTransferManagerInterop
        {
            get
            {
                return (IDataTransferManagerInterop)WindowsRuntimeMarshal.GetActivationFactory(typeof(DataTransferManager));
            }
        }

        public static DataTransferManager GetForWindow(IntPtr hwnd)
        {
            return DataTransferManagerInterop.GetForWindow(hwnd, _dtm_iid);
        }

        public static void ShowShareUIForWindow(IntPtr hwnd)
        {
            DataTransferManagerInterop.ShowShareUIForWindow(hwnd);
        }

        [ComImport, Guid("3A3DCD6C-3EAB-43DC-BCDE-45671CE800C8")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        interface IDataTransferManagerInterop
        {
            DataTransferManager GetForWindow([In] IntPtr appWindow, [In] ref Guid riid);
            void ShowShareUIForWindow(IntPtr appWindow);
        }
    }
```

3. Obtain your current HWND and call the new Helper API...

```csharp
// "this" in GetWindowHandle(this) must be a reference to
// your current window
var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

// And show the Share UI
DataTransferManagerHelper.ShowShareUIForWindow(hwnd);
```

**Comment by mlynch** [comment]
Thank so much @andrewleader, I will give this a try!

**Comment by qmatteoq** [comment]
Hello @andrewleader , should this work also for a packaged WPF or Windows Forms app based on .NET 5.0?
I'm getting the following exception when I try to use the `DataTransferManagerHelper `class:

```
System.TypeLoadException: 'Could not load type 'System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal' from assembly 'System.Runtime.InteropServices.WindowsRuntime, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.'
```

The application is packaged and it's using the specific Windows 10 TFM (`net5.0-windows10.0.19041`).

Thanks!

**Comment by andrewleader** [comment]
Hey @qmatteoq, it supposedly should work for WPF, I got that code from this WPF code sample from the team: https://github.com/microsoft/Windows-classic-samples/tree/main/Samples/ShareSource/wpf

I also got the same error as you though... so maybe something changed.

**Comment by manodasanW** [comment]
@qmatteoq @andrewleader for .NET 5, I would point you to [this](https://github.com/microsoft/CsWinRT/issues/970#issuecomment-902500420) which demonstrates using DataTransferManagerInterop.

**Comment by AdamBraden** [comment]
@angelazhangmsft - are we missing DataTransferManagerInterop in the interop docs? https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp

**Comment by angelazhangmsft** [comment]
> @angelazhangmsft Angela Zhang (SHE/HER) FTE - are we missing DataTransferManagerInterop in the interop docs? https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp

Since DataTransferManagerInterop doesn't implement IInspectable, C#/WinRT isn't able to help here with the wrapper classes. This would be something we need to consolidate with CsWin32

**Comment by mikebattista** [comment]
Related issue: https://github.com/microsoft/CsWin32/issues/246

cc @aarnott @sotteson1

**Comment by yoshiask** [comment]
Are there any updates on this? I am building a packaged desktop app using `1.0.0-preview3` and none of the mentioned solutions have worked. I still get the `TypeLoadException` when calling `DataTransferManagerInterop.GetForWindow`.

**Comment by angelazhangmsft** [comment]
@yoshiask - there is a workaround [here](https://github.com/microsoft/CsWinRT/issues/970#issuecomment-902500420) that was mentioned above, can you confirm that you tried that and still got the `TypeLoadException` issue?

**Comment by yoshiask** [comment]
> @yoshiask - there is a workaround [here](https://github.com/microsoft/CsWinRT/issues/970#issuecomment-902500420) that was mentioned above, can you confirm that you tried that and still got the `TypeLoadException` issue?

I don't get a `TypeLoadException`, but I do get the `COMException` that this issue was opened for.

**Comment by andrewleader** [comment]
@angelazhangmsft that workaround works but doesn't easily expose the ShowShareUIForWindow method, I've integrated that updated workaround into the previous Helper class that I found above and now this seems to work end-to-end!

@yoshiask try the code below!

**Copy/paste this Helper class to your project**

```csharp
public static class DataTransferManagerHelper
{
    static readonly Guid _dtm_iid = new Guid(0xa5caee9b, 0x8708, 0x49d1, 0x8d, 0x36, 0x67, 0xd2, 0x5a, 0x8d, 0xa0, 0x0c);

    static IDataTransferManagerInterop DataTransferManagerInterop => DataTransferManager.As<IDataTransferManagerInterop>();

    public static DataTransferManager GetForWindow(IntPtr hwnd)
    {
        IntPtr result;
        result = DataTransferManagerInterop.GetForWindow(WindowHelper.GetHwndForCurrentWindow(), _dtm_iid);
        DataTransferManager dataTransferManager = MarshalInterface<DataTransferManager>.FromAbi(result);
        return (dataTransferManager);
    }

    public static void ShowShareUIForWindow(IntPtr hwnd)
    {
        DataTransferManagerInterop.ShowShareUIForWindow(hwnd);
    }

    [ComImport]
    [Guid("3A3DCD6C-3EAB-43DC-BCDE-45671CE800C8")]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IDataTransferManagerInterop
    {
        IntPtr GetForWindow([In] IntPtr appWindow, [In] ref Guid riid);
        void ShowShareUIForWindow(IntPtr appWindow);
    }
}
```

**Then, in your code...**

```csharp
// Initialize the DataTransferManager event handler using your current HWND (only needs to be initialized once for lifetime of app)
var dataTransferManager = DataTransferManagerHelper.GetForWindow(myHwnd);
_dataTransferManager.DataRequested += (sender, args) =>
{
    args.Request.Data.SetText("Text from the Windows App SDK Gallery!");
    args.Request.Data.RequestedOperation = DataPackageOperation.Copy;
    args.Request.Data.Properties.Title = "DataTransferManager demo";
};

// Show the Share UI using your current HWND
DataTransferManagerHelper.ShowShareUIForWindow(myHwnd);
```

Here's a full end-to-end example: https://github.com/andrewleader/WindowsAppSDKGallery/blob/main/WindowsAppSDKGallery/SamplePages/ShareSamples/DataTransferManagerPage.xaml.cs#L39

**Comment by vishal2447** [comment]
We tried using the share feature in WindowsAppSDK Gallery sample app , It worked in some systems but, Fails to show the ShareUI in some other systems. What could be the reason for this behavior? and how to make it work in all systems?
![Animation](https://user-images.githubusercontent.com/55207492/155692706-9068d45b-486a-4d1d-8a98-7c4075479752.gif)
