### ISSUE TITLE
Order WAP-based project template solution files to ensure that WAP project is default startup project 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/WindowsAppSDK#1343]
The default startup project is determined by simple order in the sln file.  Many developers inadvertently F5 with the startup project set to the head project.  Project templates should be reordered to eliminate this.

**Comment by riverar** [comment]
@Scottj1s Clever!

**Comment by alwu-msft** [comment]
Did VS become less deterministic about the order in which it creates projects in a multi-project template? We've always had the .wapproj specified first ([C#](https://github.com/microsoft/WindowsAppSDK/blob/aa4e265fa6cd02154981e75a288e85b39ab22357/dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/WinUI.Desktop.Cs.PackagedApp.vstemplate#L34) / [C++/WinRT](https://github.com/microsoft/WindowsAppSDK/blob/aa4e265fa6cd02154981e75a288e85b39ab22357/dev/VSIX/ProjectTemplates/Desktop/CppWinRT/PackagedApp/WinUI.Desktop.CppWinRT.PackagedApp.vstemplate#L34)) in the parent .vstemplate for precisely this reason as it is the closest we can get to controlling the order in which the projects are listed in the solution.

**Comment by evelynwu-msft** [comment]
We already specify our templates in such a way that the .wapproj is listed first in the generated solution.
