### ISSUE TITLE
How to change max target version?

### ISSUE THREAD

**Issue by asklar** [microsoft/WindowsAppSDK#1367]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1084

<div type='discussions-op-text'>

<sup>Originally posted by **Jaiganeshkumaran** July 18, 2021</sup>
I'm trying to reference a C++ Runtime Component project from a C# WinUI 3 app which targets the latest Insider SDK however I get this error while building the C# app: ```C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2526,6): warning MSB3851: This project targets "Windows, Version=10.0.19041.0", but it is attempting to reference "C:\Users\jaiga\Desktop\source\OneToolkit\x64\Debug\OneToolkit\OneToolkit.winmd" targeting "UAP,Version=10.0.22000.0", which is invalid.```

I checked the packaging project and it is set to 10.0.22000.0 but I can't find anything like that for the app project.</div>

---
Hitting the same issue as Jaiganesh. In my case, there is a bug in older SDKs that prevents me from using them (microsoft/microsoft-ui-xaml#5828). So I have to use the 22000 SDK. However, I can't reference the 22000 SDK from C#:

```
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 10.0.22000.0 is not a valid TargetPlatformVersion for Windows. Valid versions include:
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 10.0.20348.0
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 10.0.19041.0
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 10.0.18362.0
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 10.0.17763.0
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 8.0
1>C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(213,5): error NETSDK1140: 7.0
1>Done building project "Microsoft.ReactNative.WindowsAppSDK.csproj" -- FAILED.
```

Specifying an older SDK on the C# side, results in a warning that should actually be an error: microsoft/CsWinRT#892
Tracking for the "make this cswinrt warning an error" is microsoft/CsWinRT#906

**Comment by asklar** [comment]
@Scottj1s

**Comment by asklar** [comment]
My workaround for the time being, is to use the older SDK (the one that has the MIDL bug), but point the build to use the midl.exe from the new SDK. Obviously I can't merge this in as-is, so for the time being I'm able to locally validate my code, but I can't check it in.

```xml
<Project>
  <PropertyGroup Condition="'$(SolutionName)'=='Microsoft.ReactNative.WindowsAppSDK'">
    <UseWinUI3>true</UseWinUI3>
    <!-- <WindowsTargetPlatformVersion>10.0.22000.0</WindowsTargetPlatformVersion> -->
    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
    <!-- 
      ******** TODO *********
      Temporary workaround until the 22000 SDK is shipped 
      We use WinAppSDK 1.0-experimental - this means certain types like xaml's Application are marked experimental
      There is a bug in older versions of MIDL where it doesn't understand [experimental] correctly
      This was fixed in the 22000 SDK.

      However, we can't use the 22000 because we don't have a TargetFramework for it, like net5.0-windows10.0.22000.168
      So: use the 18362 SDK, but use the 22000 midl.exe
    -->
    <MIDLToolPath>C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64</MIDLToolPath>
  </PropertyGroup>
</Project>
```

**Comment by manodasanW** [comment]
To target the insider SDK TFM in a .NET 5 app, you need to set the `UseWindowsSdkPreview` property added in the .NET SDK 5.0.8 update.

More details [here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK) under Install the SDK Insider Preview.

**Comment by asklar** [comment]
thanks @manodasanW , I can confirm that setting these properties lets me reference the preview sdk targetframework!
