### ISSUE TITLE
Address Notifications for unpkg apps comments

### ISSUE THREAD

**Issue by danielayala94** [microsoft/WindowsAppSDK#1372]
1) Telemetry change: log processName in the AUMID field
2) Test SDK on a STA environment: Are we seeing API calls fail for STA?
3) Verify if we need to call CoInitializeEx before cocreating the LRP

**Comment by loneursid** [comment]
Item 1 is addressed by this PR: https://github.com/microsoft/WindowsAppSDK/pull/1385
