### ISSUE TITLE
In C# UWP Desktop App, how can I access sensor metadata like Model (DEVPKEY_Sensor_Model)?

### ISSUE THREAD

**Issue by thomas-t1** [microsoft/WindowsAppSDK#1387]
I've created a desktop C# app using the reunion aka Windows App SDK nuget packages and I am able to access my CustomSensor(s) thought the Sensor API and read sensor samples and some sensor properties. However I'm interested in also reading the sensor specific properties like Model (DEVPKEY_Sensor_Model), is this possible through the UWP CustomSensor API?

**Comment by sastorer-ms** [comment]
Hey! Sorry this took so long, but we have a few samples of how to use custom sensors in UWP here: [https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/CustomSensors/cs/Scenario1_DataEvents.xaml.cs](https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/CustomSensors/cs/Scenario1_DataEvents.xaml.cs)

It's also possible to use DEVPKEYs like this:

`try
    {
       sensorModel = deviceInfo.Properties[Constants.Properties["Sensor_Model"]].ToString();
    }
 catch { }`

Where `Constants.Properties["Sensor_Model"]` corresponds to this in a dictionary: `{ "Sensor_Model", "{D4247382-969D-4F24-BB14-FB9671870BBF} 8" }` and `deviceInfo` is a `Device Information` object.

**Comment by sastorer-ms** [comment]
Please feel free to reach out if the above does not solve your issue!
