### ISSUE TITLE
Support running elevated across Win10 and Win11

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1407]
## Summary
WinAppSDK currently doesn't support running elevated on Windows 10 (only on Windows 11). Support running elevated on all versions of Windows that WinAppSDK supports.

**Comment by chigy** [comment]
Thank you for the feature request. In order for us to be transparent to our community members, we are proactively closing any feature requests that we do not believe we can realistically get to in the next 1-2 years. If you feel this is feature is critical and urgent, and need to be prioritized over other issues our team is currently looking to delivering, please add detailed information about how the app ecosystem would benefit from it when reopening the issue. It will be very helpful for us, thanks!
