### ISSUE TITLE
ApplicationView.GetForCurrentView thows an error

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/WindowsAppSDK#1414]
Hi, in my WinUI3 desktop app, I'm trying to call `ApplicationView.GetForCurrentView()` and got next error:
**System.Runtime.InteropServices.COMException: 'Element not found. (0x80070490)'**

Is the ApplicationView removed from WinUI3?

NuGet package version: 
Microsoft.ProjectReunion 0.8.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by LeftTwixWand** [comment]
`CoreApplication.GetCurrentView()` throw the same exception.

**Comment by Jaiganeshkumaran** [comment]
@LeftTwixWand `ApplicationView.GetForCurrentView` and `CoreApplication.GetCurrentView()` are only for UWP apps. For WinUI 3 desktop apps, use the Window class for some of the functionality. I'm not completely sure but some of them also now a GetForWindowId method.

**Comment by LeftTwixWand** [comment]
@Jaiganeshkumaran Thank You!
