### ISSUE TITLE
Template generated packaging project produces NUGET warnings on build (NU1701)

### ISSUE THREAD

**Issue by smaillet** [microsoft/WindowsAppSDK#1430]
**Describe the bug**
Building a package  project from the packaging project created by the template produces NUGET warning
`[...] (Package).wapproj : warning NU1701: Package 'Microsoft.ProjectReunion.InteractiveExperiences 0.8.3' was restored using 'net5.0-windows10.0.19041, .NETCoreApp,Version=v3.1, .NETCoreApp,Version=v3.0, .NETCoreApp,Version=v2.0, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, net6.0-windows10.0.19041, .NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.19041'. This package may not be fully compatible with your project.`

No clue why it thinks UAP is involved in this at all, it's not, this is a fullTrust app.

**Expected behavior**
Template generated projects should build without errors or warnings. 

**Version Info**
NuGet package version: 
0.8.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by andrewleader** [comment]
Hey @smaillet, can you try using [1.0 Preview 1](https://github.com/microsoft/WindowsAppSDK/discussions/1437)? I think we've fixed this in 1.0 Preview 1, I'm no longer seeing this warning there.

**Comment by andrewleader** [comment]
Closing this as fixed in 1.0 Preview 1, but if you still see the problem please reopen!
