### ISSUE TITLE
Preview1: Where did Microsoft.WindowsAppSdk.Bootstrap.dll go?

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1438]
Sending up a flare for @DrusTheAxe

**Comment by DrusTheAxe** [comment]
Not yet ready for action. There's a bug in the implementation so it won't do what it should. Will be fixed in preview2.

**Comment by riverar** [comment]
@DrusTheAxe Thanks, any details? Am just curious if it's related to my WinUI failures.
