### ISSUE TITLE
AppInstance redirection APIs don't transfer foreground rights

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1439]
**Describe the bug**

I'm trying to use AppLifecycle.AppInstance redirection APIs to redirect to a single instance (and then bring that instance to the foreground), however it seems the foreground rights aren't being passed to the main instance when using RedirectActivationTo().

**Steps to reproduce the bug**

1. Create a WinUI 3 desktop app using 1.0 Preview 1 and add AppInstance with single-instance redirection
    1. Call GetCurrent().GetActivatedEventArgs() first
    1. Then call FindOrRegisterForKey("main")
    1. If that main instance is current, register the Activated event
    1. Otherwise, call main.RedirectActivationToAsync(args)
1. Within the Activated event, attempt to bring the window to the foreground
    1. Get the DispatcherQueue to enter the UI thread
    1. Then call the Activate() method on your window
    1. **Expected**: Window comes to foreground
    1. **Actual**: Nothing happens

**Version Info**

NuGet package version: 

Microsoft.WindowsAppSDK 1.0.0-preview1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by andrewleader** [comment]
Fixed for 1.0 Preview 2 via #1416

**Comment by duracellko** [comment]
How does this work? It doesn't seem to work in my app.

I created small sample. 
[SingleAppInst.zip](https://github.com/microsoft/WindowsAppSDK/files/13533176/SingleAppInst.zip)

Could you have a look at what is missing there?

When I select the app in the Start menu second time, the app does not go to foreground.

**Comment by duracellko** [comment]
> How does this work? It doesn't seem to work in my app.
> 
> I created small sample. [SingleAppInst.zip](https://github.com/microsoft/WindowsAppSDK/files/13533176/SingleAppInst.zip)
> 
> Could you have a look at what is missing there?
> 
> When I select the app in the Start menu second time, the app does not go to foreground.

I found the way. Instead of `Window.Activate()` use https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow

```csharp
[DllImport("user32.dll")]
[return: MarshalAs(UnmanagedType.Bool)]
internal static extern bool SetForegroundWindow(IntPtr hWnd);

IntPtr hWnd = WindowNative.GetWindowHandle(window);
SetForegroundWindow(hWnd);
```
