### ISSUE TITLE
AppInstance.GetCurrent().GetActivatedEventArgs() crashes on a WPF unpackaged app

### ISSUE THREAD

**Issue by qmatteoq** [microsoft/WindowsAppSDK#1449]
**Describe the bug**
If I try to get the activation args in an unpackaged WPF app which uses Windows Apps SDK, the application crashes with the following error:

```
Exception Info: System.ArgumentException: Value does not fall within the expected range.
```

**Steps to reproduce the bug**

1. Create a WPF application based on .NET 5
2. Follow the instructions on the docs to integrate Windows Apps SDK
3. Follow the instructions on the docs to call the Bootstrapper APIs
4. Use the following code to register for file type activation:

```
ActivationRegistrationManager.UnregisterForFileTypeActivation(new string[] { ".foo", ".fee" }, Process.GetCurrentProcess().MainModule.FileName);
```

5. Add the following code in `App.xaml.cs` to handle the activation:

```
public partial class App : Application
{
    public App()
    {
        MddBootstrap.Initialize(0x00010000, "preview1");
           
    }

    protected override void OnStartup(StartupEventArgs e)
    {
        MainWindow window = new MainWindow();

        var args = AppInstance.GetCurrent().GetActivatedEventArgs();
        if (args.Kind == ExtendedActivationKind.File)
        {
            var fileActivation = args.Data as IFileActivatedEventArgs;
            string filePath = fileActivation.Files[0].Path;
            window.FilePath = filePath;
        }

        window.Show();
    }

    protected override void OnExit(ExitEventArgs e)
    {
        MddBootstrap.Shutdown();
    }
}
```
6. Double click on a file with .foo extension

**Expected behavior**
The application starts and, from the activation parameters, I can get the path of the selected file.

What I observe is that, if the registration works fine (the file type is properly associated and when I double click on it, the application starts), when I call `AppInstance.GetCurrent().GetActivatedEventArgs();`, it fails with the following error:

```
Exception Info: System.ArgumentException: Value does not fall within the expected range.
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.Windows.AppLifecycle.IAppInstance.global::Microsoft.Windows.AppLifecycle.IAppInstance.GetActivatedEventArgs()
   at Microsoft.Windows.AppLifecycle.AppInstance.GetActivatedEventArgs()
   at FileTypeSample.App..ctor() in C:\Users\mpagani\Source\Events\DevDays2021-September\04-AppWindowSample (Unpackaged)\FileTypeSample\App.xaml.cs:line 27
   at FileTypeSample.App.Main() in C:\Users\mpagani\Source\Events\DevDays2021-September\04-AppWindowSample (Unpackaged)\FileTypeSample\obj\x64\Debug\net5.0-windows10.0.19041\App.g.cs:line 51
```

**Version Info**
Windows Apps SDK 1.0 Preview 1 on Windows 11 22000.194

NuGet package version: 
Microsoft.WindowsAppsSDK 1.0.0-preview1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.194)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by aeloros** [comment]
This is fixed with https://github.com/microsoft/WindowsAppSDK/pull/1553
