### ISSUE TITLE
NuGet package requires being explicitly referenced, doesn't support implicitly being used as a dependency in a library

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1469]
**Describe the bug**

Internal bug: https://microsoft.visualstudio.com/OS/_workitems/edit/36531364

If a library (like MAUI or other third-party controls libraries) depends on WinAppSDK, when an app developer wants to use that library, they also have to explicitly install the WinAppSDK NuGet package in their apps and projects.

This is non-standard and shouldn't be required, as NuGet supports dependencies which should handle this correctly.

NuGet has a `buildTransitive` folder that we can use to fix this.

As dotMorten said in https://github.com/microsoft/WindowsAppSDK/issues/977#issuecomment-924552927 ...

> We're seeing [stuff like this](https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj#L48-L54) in projects. We can't just reference a nuget package (like Maui) that takes a dependency on the WinAppSDK, but have to magically know to also add an explicit reference to the WinAppSDK in every single project in the project graph and maintain the versions on those as well. This is why NuGet has transitive build support. I don't really get from the above thread at all why the WinAppSDK can't make use of this?

**Comment by dotMorten** [comment]
Usually all you need to do is copy the `build` folder contents to `buildTransitive` for the WinAppSDK and build tools packages.

**Comment by andrewleader** [comment]
I was figuring it was something like that, @dotMorten any chance you can help validate if doing that fixes this? You could locally create a new NuGet with the build folder copied and test that? If you can test and validate that's all we have to do, that would really help fit this into 1.0.

**Comment by dotMorten** [comment]
LOL I did that months ago with the old packages (that email thread where I complained about the package hierarchy), and worked for me in _my_ scenario. I just assumed there was a reason you didn't do this, so wasn't sure of there were other scenarios.

Currently the nuget has a \buildTransitive\Rules\ folder, and I'm not entirely sure what the purpose of that is? It's basically a bunch of XAML files, which makes no sense to me.

Also while I was inspecting the nuget, I did find this file was empty and could just be deleted:
`microsoft.windows.sdk.buildtools.10.0.20348.19.nupkg\build\Microsoft.Windows.SDK.BuildTools.targets`

**Comment by BenJKuhn** [comment]
Note this is now also tracked as OS issue 36531364.

**Comment by mqudsi** [comment]
You might want to settle on a policy to fix this for all related packages; the same issue caused me an insane amount of grief with WinUI 3: https://github.com/microsoft/microsoft-ui-xaml/issues/5746

**Comment by DefaultRyan** [comment]
This is fixed for 1.1. Leaving this open while I propose servicing for 1.0.

**Comment by DefaultRyan** [comment]
This was fixed for 1.0.1.

**Comment by dotMorten** [comment]
@DefaultRyan Funny you should say that, because I was just about to log an issue around this for the packaging project. I still need to explicitly reference it there, or the run will fail with:

> An unhandled exception of type 'System.DllNotFoundException' occurred in MyApplication.dll
> Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

This is rather problematic, because I forgot to update the version there to 1.0.1, but only updated my main application project. This resulted in the 1.0.0 runtime being used when running on a PC that never had 1.0.1 installed, and would just on those PCs crash, when for instance I tried using multiple windows. It led me to log an invalid bug here because of this senseless behavior (ie works on some PCs, fails on others). Can we reopen this since packaging projects still require an explicit reference?
