### ISSUE TITLE
For packaged apps using BI (PushTrigger) handle foregroundHandled=false scenario

### ISSUE THREAD

**Issue by sharath2727** [microsoft/WindowsAppSDK#1490]
Description: For packaged apps using BI (PushTrigger enabled), if channel Object is present and foregroundHandled is set to false handle the scenario to do protocol activation.

**Comment by pmpurifoy** [comment]
The Handled property has been removed from PushNotificationReceivedEventArgs so this issue doesn't apply anymore.
