### ISSUE TITLE
Question: WinUI3 desktop how to restart application?

### ISSUE THREAD

**Issue by sudongg** [microsoft/WindowsAppSDK#1492]
I try to use uwp code
`CoreApplication.RequestRestartAsync(launchArguments);`
But it didn't work.

**Comment by ghost1372** [comment]
I can restart application with the following code (WASDK 1.1.0-preview1)

`Microsoft.Windows.AppLifecycle.AppInstance.Restart("");
`

**Comment by LegendaryBlair** [comment]
PR https://github.com/microsoft/WindowsAppSDK/pull/1134 resolved this issue
