### ISSUE TITLE
C# AnyCPU Exe using Dynamic Dependencies - Do not copy native bootstrapper binary to bin folder

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/WindowsAppSDK#1496]
**Describe the bug**

When building a C# WinAppSDK project, the Dynamic Dependencies bootstrapper native binary, Microsoft.Windows.Bootstrap.dll, is getting copied into the project output folder. This is not necessary and causes the app to fail to load in AnyCPU scenarios.

**Steps to reproduce the bug**

1. Create New C# Console app targeting net5.0
2. Add reference to latest WinAppSDK nuget package
3. Change the <targetframework> to win10:
 - <TargetFramework>net5-windows10.0.19041</TargetFramework>
4. Add the following code to Program.cs:
```
using System;
using System.Threading.Tasks;
using Windows;
using Microsoft.Windows.ApplicationModel.DynamicDependency;

namespace ConsoleApp11
{
    class Program
    {
        static async Task Main(string[] args)
        {
            // Take a dependency on Windows App SDK 1.0 Preview 1.
            // If using version 1.0 Experimental, replace with MddBootstrap.Initialize(0x00010000, "experimental1").
            // If using version 0.8 Preview, replace with MddBootstrap.Initialize(8, "preview").
            Bootstrap.Initialize(0x00010000, "");
            Console.WriteLine("Hello World!");
            // Release the DDLM and clean up.
            Bootstrap.Shutdown();
        }
    }
}
```
5. F5 to build an "AnyCPU" project

Result: System.BadImageFormatException
Exception thrown: 'System.BadImageFormatException' in Microsoft.WindowsAppRuntime.Bootstrap.Net.dll
Exception thrown: 'System.BadImageFormatException' in System.Private.CoreLib.dll

The exception is because the C# wrapper is attempting to load the native component in the current folder, rather than using the lookup mechanism and folder structure from <exe>.deps.json.  
Currently the bootstrapper props/targets are copying the x86 dll for AnyCPU, but AnyCPU defaults to "prefer 64bit" so this fails.

**Expected behavior**

Expect the app to run, console window to display "Hello World"

The build should not be copying native binaries into the binplace root folder for .net apps. 

NuGet package version: 

**Additional context**

**Comment by riverar** [comment]
Heads up: This needs to continue happening for < .NET 5 (and non-.NET) scenarios.

**Comment by AdamBraden** [comment]
Agree that yes it needs to be copied in non-NET scenarios.
WinAppSDK will only be supported on NET5+.
