### ISSUE TITLE
Add VERSION_INFO block to Microsoft.WindowsAppRuntime.Bootstrap.dll

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1499]
Because this native library must match, so to speak, with an installed runtime, it would be greatly helpful if it had a VERSION_INFO block with origin information.

![Screenshot of bootstrap DLL property window](https://user-images.githubusercontent.com/475132/135147604-1ca82e15-7f79-4d68-9549-d895227a87c0.png)

https://task.ms/39906681

**Comment by sredna** [comment]
It would also be nice if it disclosed what "Mdd" actually stands for in its description (and if not there, somewhere in the documentation?).

**Comment by riverar** [comment]
@sredna Microsoft.DynamicDependencies

**Comment by DrusTheAxe** [comment]
VERSIONINFO is in the Insights.dll in 1.2. Injecting it into other DLLs is complicated due to the info not known until after they're built so they'll have to wait for vNext

**Comment by EricJohnson327** [comment]
Fixed.
