### ISSUE TITLE
Deployment API's DeploymentManager::Initialize() returns Access Denied when called from app with 'runFullTrust' capability

### ISSUE THREAD

**Issue by zaryaf** [microsoft/WindowsAppSDK#1518]
**Issue:**
DeploymentManager::Initialize() returns Access Denied from PackageManager when called from VS with WinAppSDK nuget and VSIX extension installed.

**Impact:**
The impact of this bug is that the key scenario for which Initialize() is intended to run - to deploy the Main and Singleton packages from a Store-deployed or Sideloaded MSIX - is non-functional. 

**Workaround:**  Full trust app will need to carry and run the Installer.

**Root cause:** Working on identifying the root cause here, and why tests function fine but built in VS does not.

**Repro steps:**
- Install latest Windows App SDK VSIX 
- Create new WindowsAppRuntime project which uses the Deployment API
- Add latest nuget to the project
- Call DeploymentManager::Initialize() from the app.

**Comment by sachintaMSFT** [comment]
https://task.ms/38181094 is tracking this issue. Currently, working on a fix for this issue.

**Comment by DrusTheAxe** [comment]
Fixed in 1.1
