### ISSUE TITLE
File Type Associations incorrectly encode %1 to be %251 when setting the Verb handler's command line template.

### ISSUE THREAD

**Issue by aeloros** [microsoft/WindowsAppSDK#1524]
Example of the incorrect template data in the registry: "C:\path\myApp.exe ----ms-protocol:ms-encodedlaunch://App/?ContractId=Windows.File&Verb=edit&File=%251"

This results in Unpackaged apps not getting a correct command line, and subsequently AppInstance::GetCurrent()::GetActivatedEventArgs() throws an exception.

**Comment by zaryaf** [comment]
Scott, what's the end impact of this? For example, what task/scenario can't be completed as a result of this? And do we have a workaround?

**Comment by aeloros** [comment]
File Type association launches crash the app.  You can manually edit the registry value to be %1 instead as a partial workaround.  If the target file path has a space in it, then it will still fail and there is no workaround for that scenario.

**Comment by aeloros** [comment]
I added more details to the issue that should answer your questions.  Let me know if I missed anything.
