### ISSUE TITLE
Launcher.LaunchUriAsync doesn't work for all uri

### ISSUE THREAD

**Issue by dhabierre** [microsoft/WindowsAppSDK#1531]
**Describe the bug**

The Launcher.LaunchUriAsync() method does not open uri starting with __http://192.168.1.1__

```cs
// This uri exists => the browser is not opened => returns false
await Launcher.LaunchUriAsync(new Uri("http://192.168.1.1/html/index.html#/login"));

// This uri does not exist => the browser is opened => returns true
await Launcher.LaunchUriAsync(new Uri("http://192.168.2.1/html/index.html#/login"));
```

**Steps to reproduce the bug**

```cs
var f = Launcher.LaunchUriAsync(new Uri("http://192.168.1.1/html/index.html#/login"));
var t = Launcher.LaunchUriAsync(new Uri("http://192.168.2.1/html/index.html#/login"));
```

It also works with:
- http://192.168.3.1/html/index.html#/login
- http://192.168.4.1/html/index.html#/login
- http://192.168.5.1/html/index.html#/login
- http://192.168.6.1/html/index.html#/login

**Expected behavior**

The Launcher.LaunchUriAsync() method should open uri starting with __http://192.168.1.1__

**Version Info**

Windows 11 21H2 (OS Build 22000.194)

NuGet package version: 

- Microsoft.UI.Xaml 2.7.0
- Microsoft.NETCore.UniversalWindowsPlatform 6.2.12

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.194)              | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

Thank you for any idea.

**Comment by asklar** [comment]
Please see the Remarks section in the API doc for requirements on this API, e.g. make sure you are calling the launcher api from the UI thread, that the app is visible, etc.
https://docs.microsoft.com/uwp/api/windows.system.launcher.launchuriasync

**Comment by andrewleader** [comment]
Since this is a platform API and not a Windows App SDK API, if the advice from asklar didn't work, please file a bug through the Feedback Hub app under the Developer Platform -> App to App Communication and Sharing category.

Closing this bug since this is a platform API that should be tracked through Feedback Hub.

**Comment by asklar** [comment]
I imagine you might be missing the private network app capability, please see the doc I linked. This API isn't part of the WinAppSDK (this repo) so if that doesn't work then maybe try feedback hub, or stackoverflow etc
