### ISSUE TITLE
Upgrade Microsoft.WindowsAppSDK.WinUI to preview1

### ISSUE THREAD

**Issue by curia-damiano** [microsoft/WindowsAppSDK#1542]
# Proposal: please Upgrade Microsoft.WindowsAppSDK.WinUI to preview1

## Summary
Upgrade Microsoft.WindowsAppSDK.WinUI to preview1

## Rationale
I am upgrading a solution of a customer; I can't move to Microsoft.WindowsAppSDK preview1 because the NuGet package Microsoft.WindowsAppSDK.WinUI still references experimental1.
This is a blocker that prevents the upgrade of dependent packages like WindowsCommunityToolkit and Microsoft.XamlBehaviors.

## Scope
This proposal will allow to align multiple NuGet packages to preview1.

**Comment by andrewleader** [comment]
Hey @curia-damiano, in Preview 1 we've consolidated to a single NuGet package. You should **uninstall** all the other NuGet packages and only have *Microsoft.WindowsAppSDK* as your sole NuGet package! That makes updating in the future even easier as there's just one package to update 😊

**Comment by curia-damiano** [comment]
Thank you Andrew for the info!
I will do as you suggest here.
