### ISSUE TITLE
Unable to load bootsrap.dll

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/WindowsAppSDK#1548]
Hello, I'm trying to deply unpackaged app, but receave this error: : 'Unable to load DLL 'Microsoft.WindowsAppRuntime.Bootstrap.dll' (0x8007007E)'.

Sdk .401 
Microsoft.WindowsAppSDK 1.0.0-preview1
Visual studio 2022

I followed [this](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=csharp-dotnet) guide.

**Comment by Petrarca181** [comment]
Thank you for the reply.  But I still barely understand what I should to do.  I should just wait for previw 2?

**Comment by DrusTheAxe** [comment]
> Thank you for the reply. But I still barely understand what I should to do. I should just wait for preview 2?

Unpackaged WinUI3 apps aren't quite ready yet. We're working hard to connect the last dots for Preview3 so please stay tuned.
