### ISSUE TITLE
WINAPPSDKGENERATEPROJECTPRIFILE : warning : PRI257: 0xdef00522 language resources

### ISSUE THREAD

**Issue by get-flat** [microsoft/WindowsAppSDK#1565]
**Describe the bug**
Getting warning when trying to localize strings using language resources
Followed instructions from:
https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?tabs=csharp#localize-your-winui-desktop-app

(not sure if this is a right place to report this)

**Steps to reproduce the bug**
Add language resource folder
- Strings\pl-PL\Resources.resw
- Strings\de-DE\Resources.resw

Set Package.appxmanifest "Default language" to
- "pl-PL" - WINAPPSDKGENERATEPROJECTPRIFILE : warning : PRI257: 0xdef00522 - Resources found for language(s) 'pl-pl' but no resources found for default language(s): 'pl-PL'.
- "pl-pl" - WINAPPSDKGENERATEPROJECTPRIFILE : warning : PRI257: 0xdef00522 - Resources found for language(s) 'pl-pl' but no resources found for default language(s): 'pl-pl'.
- "pl" - No Warning
- "de-DE" - No Warning

(Although there are warnings it seems that resources are correctly localized)

**Expected behavior**
No warnings expected for "pl-PL"

**Version Info**
OS version(s): 19042.1237

NuGet package version: 
Microsoft.WindowsAppSDK 1.0.0-preview2

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by huichen123** [comment]
This is a bug in makepri.exe tool. It has been fixed internally, but will not be available until next release of SDK.

**Comment by get-flat** [comment]
Still present in WASDK 1.0.0

**Comment by huichen123** [comment]
The fix is in makepri.exe which is part of Windows SDK (not Windows App SDK).

**Comment by ilovepumpkin** [comment]
Hello, could you please check out the issue opened - https://github.com/microsoft/WindowsAppSDK/issues/1980 ? I want to confirm if my issue has same cause as this one?
