### ISSUE TITLE
Not copy generated DLL into "*(Package)" project build folder

### ISSUE THREAD

**Issue by XeonKHJ** [microsoft/WindowsAppSDK#1574]
**Describe the bug**

When building a C++ WAP packed app, some referenced dll files are generated in the main project build path, but not in "projectname (Package)" project build path. But pressing F5 in VS2019 launchs the exe that generated in "projectname (Package)" project build path. I have to manually copy all dlls into that build path everytime, other wise app will failed to launch and showing a error dialog said some dll are missing etc.

**Steps to reproduce the bug**

1. New a WinUI3 C++ WAP project
3. Include some header that depends on DLL.
2. Press F5 to run the app.

**Expected behavior**
When start the app in VS2019, building process copys all the required dlls into the build path of "projectname (package)", then run the app.

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.WindowsAppSDK 0.1.0-prerelease2

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| Windows 11 (22000.194)        | Yes   |

**Additional context**

**Comment by haonanttt** [comment]
Close this issue as not repro.
