### ISSUE TITLE
PATH Environment Variable Corruption Issue (Fixed in Preview 3)

### ISSUE THREAD

**Issue by andreww-msft** [microsoft/WindowsAppSDK#1599]
**This issue has been fixed in 1.0 Preview 3, released on 10/27!!** If you've previously used 1.0 Preview 1 or Preview 2, you still must follow the steps below to fix your path.

The new EnvironmentManager API in 1.0 Preview 1 and Preview 2 of the Windows App SDK includes a mechanism to clean up any environment variable changes made by a packaged app when that app is uninstalled. This feature is in an experimental state, and the first release includes a known bug which can corrupt the system PATH environment variable. 

This happens when the Undocked Deployment Extension Handler (DEH) executes, and this component executes whenever *any* packaged app is uninstalled, regardless of whether that app uses the Windows App SDK. The PATH is only corrupted if it contained the variable expansion character ‘%’.

**Specifics:**

The System PATH entry in the registry here:

```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\Path
```

…should be of type REG_EXPAND_SZ, but the DEH changes this to REG_SZ. This makes the PATH unusable if it contained the variable expansion character ‘%’.

**Affected releases:**

- 1.0.0-preview1
- 1.0.0-preview2

**Mitigation:**

To get your machine back into a good state, take the following steps:

1. Check if the PATH in the registry is corrupt, and if so, reset it.
2. Uninstall all apps that use the Windows App SDK 1.0 Preview1 or Preview2.
3. Uninstall the Windows App SDK 1.0 Preview1/Preview2 packages, including the package that contains the DEH.

These steps can be accomplished with the following Windows PowerShell script (must use the latest version of Windows PowerShell, and run it elevated, don't use PowerShell Core):

```powershell
# This script must be run from an elevated Windows PowerShell window (right-click Windows PowerShell in the Start menu, and select Run as Administrator).

# Remove the Windows App SDK 1.0 Preview1/2, and all apps that use it.

$winappsdk = "Microsoft.WindowsAppRuntime.1.0-preview*"
Get-AppxPackage | Where-Object { $_.Dependencies -like $winappsdk } | Remove-AppxPackage
Get-AppxPackage $winappsdk | Remove-AppxPackage


# If the PATH in the registry has been set to REG_SZ, delete it and recreate it as REG_EXPAND_SZ.

$EnvPath = 'Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment'
$Environment=Get-Item $EnvPath
$PathKind = $Environment.GetValueKind('Path')

if ($PathKind -ne 'ExpandString') {
  $Path = $Environment.GetValue('Path')
  Remove-ItemProperty $EnvPath -Name Path
  New-ItemProperty $EnvPath -Name Path -PropertyType ExpandString -Value $Path
}
```

 

**Fix:**

The EnvironmentManager functionality in the Undocked DEH component will be removed in the upcoming Release 1.0 Preview 3. This functionality may be reintroduced at a later date, when all bugs have been fixed and thoroughly tested.

**Comment by kmgallahan** [comment]
So as long as you don't uninstall any packaged app on the system the bug shouldn't trigger?

Do any packaged apps ever get uninstalled by Visual Studio automatically while developing packaged apps?

Trying to balance productivity of downgrading vs. just being careful. Is Preview 3 coming relatively soon™?

**Comment by ParkhutRoman** [comment]
It's not like windows will start crashing with corrupted PATH environment variables(I didn't even notice it for 2 months). For me the way out of this is open PowerShell window with given above 2 part of script, and runing it after work, it is too tedious for me to roll back to 0.8.5

**Comment by stevewhims** [comment]
Also see [Important issue impacting 1.0 Preview 1 and Preview 2](https://docs.microsoft.com/windows/apps/windows-app-sdk/preview-channel#important-issue-impacting-10-preview-1-and-preview-2) on docs.microsoft.com.
