### ISSUE TITLE
Unable to reliably open WinUI 3 apps using System.Diagnostics.Process

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsAppSDK#1618]
**Describe the bug**

I am trying to test my app using UIAutomation and attempted following code to open the installed WinUI3 application

```cs
var applicationIdOrPath = "SpecItEasy.App_234w23j4aqe43!App"
Process p = new Process();
ProcessStartInfo startInfo = new ProcessStartInfo();
startInfo.UseShellExecute = true;
startInfo.FileName = startInfo.FileName = @$"shell:appsFolder\{applicationIdOrPath}";
startInfo.Arguments = string.Join(" ",arguments);

if (Setting.StartFullScreen)
  startInfo.WindowStyle = ProcessWindowStyle.Maximized; 

ApplicationProcess = Process.Start(startInfo);
```
`ApplicationProcess = Process.Start(startInfo)` returns before the application becomes visible, and the important things is that the method returns `null`. 

Also, ` startInfo.WindowStyle = ProcessWindowStyle.Maximized; ` has no impact.

**Expected behavior**

The method should return a valid object and it should be possible to open the app in full screen using the arguments.

**Version Info**

0.8.5, .Net 5.0, 20H1

NuGet package version: 

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

The arguments passed is also not passed to the application.

**Comment by asklar** [comment]
Launching an app this way does not wait until the app becomes visible, it doesn't actually even wait until the app launches. It starts an explorer.exe instance asking to open that appsfolder location, explorer realizes it isn't the main (usually the only) explorer instance, so it sends a message to the main explorer instance to open that location, and exits. At that point, your app would get that the launched process exited. Some milliseconds later, the main explorer process will see the message to launch that appsfolder location and process it.

For the officially supported way to launch a packaged app, see [Automate launching UWP apps](https://docs.microsoft.com/windows/uwp/xbox-apps/automate-launching-uwp-apps#command-line-1)

**Comment by harvinders** [comment]
@asklar , I tried both the methods listed there at [Automate launching UWP apps](https://docs.microsoft.com/windows/uwp/xbox-apps/automate-launching-uwp-apps#command-line-1). However, both of them return well before the application is launched. And none of them allow me to get the process information that is required to for `UIAutomation`. Or am I missing something?

**Comment by harvinders** [comment]
The one thing that works is to use app alias. Add following to the Package.appxmanifest

```xml
<Package
  xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10"
  xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest"
  xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10"
  xmlns:uap5="http://schemas.microsoft.com/appx/manifest/uap/windows10/5" // uap5 namespace is Required
  xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
  xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/templatestudio"
  xmlns:com="http://schemas.microsoft.com/appx/manifest/com/windows10"
  xmlns:desktop="http://schemas.microsoft.com/appx/manifest/desktop/windows10"
  IgnorableNamespaces="uap uap5 rescap genTemplate"> // uap5 is Required
...
<Extensions>
        <uap5:Extension Category="windows.appExecutionAlias">
          <uap5:AppExecutionAlias>
            <uap5:ExecutionAlias Alias="MyApp.exe"/>
          </uap5:AppExecutionAlias>
        </uap5:Extension>
</Extensions>
```
