### ISSUE TITLE
Unable to pass arguments to the WinUI 3 application

### ISSUE THREAD

**Issue by harvinders** [microsoft/WindowsAppSDK#1619]
**Describe the bug**

Command line arguments are not made available to the application. 

**Steps to reproduce the bug**

1. Create an WinUI packaged application 
2. pass commandline argument as shown here
![image](https://user-images.githubusercontent.com/8557046/137899823-98a42ef7-5ebd-431c-a0fd-14b5f9fd738f.png)

3. The code below `args.Arguments` is `null`
```cs
        protected override async void OnLaunched(LaunchActivatedEventArgs args)
        {
            base.OnLaunched(args);
            var activationService = Ioc.Default.GetService<IActivationService>();
            await activationService.ActivateAsync(args);
        }
```
**Expected behavior**

**Version Info**

0.8.5
20H1

NuGet package version: 

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
Same behaviour is noticed if application is launched through `System.Diagnostics.Process`, please see example code in #1618 
```cs
var applicationIdOrPath = "SpecItEasy.App_234w23j4aqe43!App"
Process p = new Process();
ProcessStartInfo startInfo = new ProcessStartInfo();
startInfo.UseShellExecute = true;
startInfo.FileName = startInfo.FileName = @$"shell:appsFolder\{applicationIdOrPath}";
startInfo.Arguments = string.Join(" ",arguments);

if (Setting.StartFullScreen)
  startInfo.WindowStyle = ProcessWindowStyle.Maximized; 

ApplicationProcess = Process.Start(startInfo);
```

**Comment by riverar** [comment]
Thanks just wanted to close the loop with @harvinders :)
