### ISSUE TITLE
Replace all old file picker APIs and make them a wrapper on top of WinRT Picker APIs

### ISSUE THREAD

**Issue by jaigak** [microsoft/WindowsAppSDK#1627]
# Proposal: Replace all old file picker APIs and make them a wrapper on top of WinRT Picker APIs
Even though the Explorer based picker is now preferred, many apps are still using old style pickers. Even the Explorer based picker lacks some features like file picker apps when accessed through the IFileDialog interface. Consider replacing those APIs and making them a wrapper on top of WinRT picker APIs for consistency and better user experience.

## Summary
Make those APIs a wrapper on modern Windows.Storage.Pickers* APIs. Since these are system APIs, the changes would have to made to the next version of Windows rather than a Reunion feature. This will apply to all existing apps using built-in APIs without code change. Some of the Windows.Storage.Pickers APIs don't support all the features of other file picker APIs, so it must be done carefully and features that are required can be added. IFileDialog  doesn't probably need to wrapped as I think Windows.Storage.Pickers APIs already IFileDialog however others must be updated as they are clunky to use. Also make it possible to use Windows.Storage.Pickers APIs without a window.

## Rationale

* Provide a consistent, modern user experience in all apps.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end users to use a modern file picker experience with features like file picker apps in all Windows apps| Must |

**Comment by ptorr-msft** [comment]
Unfortunately there is far too much complexity in the old-style dialogs to do this. For example, the classic dialogs run in-proc and you can participate in the message loop of the dialog. This is not possible with the new pickers.

It sounds like maybe what you're looking for is "add picker apps to the classic file picker?"
