### ISSUE TITLE
Referencing a WinUI 3 project from a packaging project that also references a WinUI 2.x project doesn't work

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/WindowsAppSDK#1650]
**Describe the bug**
When you reference a WinUI 3 project from a packaging project that also references a WinUI 2.x project, you get a duplicate error due to having an App.xbf file in both projects: `3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1946,5): error APPX1111: Payload contains two or more files with the same destination path 'App.xbf', but they are different sizes. Source files: 
`
**Steps to reproduce the bug**

1. Create a new WinUI 3 desktop project.
2. Add a WinUI 2.x project to the solution and reference it from the solution.
3. See the error.

**Expected behaviour**
Both WinUI 2.x and WinUI 3 projects should be referencable from the packaging project.

**Comment by MuyuanMS** [comment]
The issue seems to be addressed by #4583 - please reopen if issue still persists in 1.6 and the mentioned issue does not help
