### ISSUE TITLE
The function "Is64BitProcess" on type "System.Environment" is not available

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/WindowsAppSDK#1652]
**Describe the bug**

When building a C# project that references `Microsoft.WindowsAppSDK` using `dotnet build`, the following error happens:

```
.nuget\packages\microsoft.windows.sdk.buildtools\10.0.20348.19\build\Microsoft.Windows.SDK.BuildTools.props(4,37): error MSB4185: The function "Is64BitProcess" on type "System.Environment" is not available for execution as an MSBuild property function.
```

**Steps to reproduce the bug**

Create a csproj with the following content:
```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.WindowsAppSDK">
			<Version>1.0.0-preview2</Version>
		</PackageReference>
	</ItemGroup>

</Project>
```

Then run `dotnet build` in the folder containing the project.

**Expected behavior**
The build passes.

**Version Info**
VS 2022 Preview 6
dotnet `6.0.100-rc.2.21505.57`, but also happens on earlier versions

NuGet package version: 
Microsoft.WindowsAppSDK 1.0.0-preview2

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by snickler** [comment]
This also occurs on Preview 3 and with version `10.0.22489-preview` of `Microsoft.Windows.Sdk.BuildTools`

`.nuget\packages\microsoft.windows.sdk.buildtools\10.0.22489-preview\build\Microsoft.Windows.SDK.BuildTools.props(4,37): error MSB4185: The function "Is64BitProcess" on type "System.Environment" is not available for execution as an MSBuild property function.`

**Comment by snickler** [comment]
@jeromelaban - It looks like these are the culprits that define whether `Is64BitProcess` is available to use or not. From the code, it makes sense why it only builds when calling `msbuild` from the VS Developer Command line 

https://github.com/dotnet/msbuild/blob/ad0ea36eb0e5670454c8cc7a3942717d4db9dab1/src/Build/Resources/Constants.cs#L306

https://github.com/dotnet/msbuild/blob/a7d579050450d7ee8c156cd652af18ee42b3570c/src/Directory.BeforeCommon.targets#L19-L20

**Comment by tibel** [comment]
Looks like no one tested building with .NET SDK :cry:

@snickler So this is an MSBuild issure right? Maybe you could report this in dotnet/msbuild project.

**Comment by jeromelaban** [comment]
This is probably not an msbuild issue, but rather the fact that the WinAppSDK (and the WinUI 3 XAML compiler, if you manually fix this issue) rely on the behavior of the .NET framework 4.x.

**Comment by Daniellled** [comment]
Does anyone know if and when this will be fixed? I see some code getting merged but I do not see any movement on this issue.

**Comment by riverar** [comment]
This is an upstream bug in `Microsoft.Windows.SDK.BuildTools`. Latest preview (10.0.22504-preview) and latest stable (10.0.22000.196) are both affected. (It's not clear if `dotnet build` is even supported with BuildTools in general.) Looping in @mikebattista.

**Comment by mikebattista** [comment]
@sotteson1 could you take a look?

The BuildTools package is not working with `dotnet build`, affecting projects that use the App SDK.

**Comment by Daniellled** [comment]
Does this mean the only way to build a WinUI3 application is via Visual Studio. All command line options are out?

**Comment by andrewleader** [comment]
I don't believe we support `dotnet build`, we only support `msbuild` at this time. @evelynwu-msft or @sotteson1 or @DefaultRyan  would any of you be the one to confirm?

**Comment by andrewleader** [comment]
And @Daniellled you can use `msbuild` from command line. Here's an example of a CI script using msbuild to build and generate MSIX packages from a single-project WinUI 3 app: https://github.com/andrewleader/WindowsAppSDKGallery/blob/main/.github/workflows/dotnet-desktop.yml#L102

**Comment by Daniellled** [comment]
Good to know. In your CI pipeline are you using physical machines with a full install of Visual Studio or are you using docker images? If docker do you know if you have any documentation on what components a docker image needs to compile WinUI3?

**Comment by evelynwu-msft** [comment]
Windows App SDK, independent of the Windows SDK Build Tools Nuget package, does not support `dotnet build` at this time.

**Comment by andrewleader** [comment]
@Daniellled I'm using GitHub Workflows hosted agents, which has basically all of the VS components installed: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions

I'm not sure what the minimal set of components that would be required. At a high level, the workloads that would be required (from the Installer) would be the .NET workload and the Universal Windows Platform workload. If you include all components inside those workloads, you should be good.

**Comment by mikebattista** [comment]
> Windows App SDK, independent of the Windows SDK Build Tools Nuget package, does not support `dotnet build` at this time.

I'd still like to investigate the BuildTools package issue. Assigned to @sotteson1 for that.

**Comment by andrewleader** [comment]
Since `msbuild` is supported for command-line, and supporting `dotnet build` with the Windows App SDK is a net-new feature, I'm going to close this issue.

If you need/want `dotnet build` to be supported, please [vote on that feature here](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/57-support-dotnet-build?utm_medium=social&utm_source=portal_share) and tell us why you need it over msbuild!

*(Steve might also share some updates in the future about the BuildTools investigation on this closed thread since there's no public BuildTools repo to share updates about that investigation)*.

**Comment by mikebattista** [comment]
Internal bug on BuildTools is http://task.ms/37199033.

**Comment by mikebattista** [comment]
FYI that this issue will be fixed in .NET 6.0.300 per https://github.com/dotnet/msbuild/issues/7329.

**Comment by mlynch** [comment]
Unfortunately, I got bit by the issue as well. For some reason it must have been working fine last fall because we were able to use `dotnet add package` from the command line, but that started breaking recently for our Windows App SDK and WinUI3 project.

Does anyone know what the `msbuild.exe` command line alternative is for adding new nuget packages to a Windows App SDK project?
