### ISSUE TITLE
NuGet package incorrectly allows installing into an app that's not using .NET 5

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1658]
**Describe the bug**

Internal bug: https://microsoft.visualstudio.com/OS/_workitems/edit/36839691

In our current preview NuGet packages, we're not using any TFMs, so you can technically install WinAppSDK into any app, including a .NET Framework app, and then we'll silently fail later on since we only support .NET 5 and higher.

This is a **regression**, in previous ProjectReunion 0.8 versions, some of our sub-packages specified TFMs which then caused an error to occur when trying to install into a .NET Framework or .NET Core 3 app (giving the developer immediate and actionable feedback).

**Steps to reproduce the bug**

1. Create a .NET Framework or .NET Core WPF app
2. Try to install `Microsoft.WindowsAppSDK-1.0.0-preview2`
3. Notice the install succeeds (unexpected)
4. Uninstall and try to install `Microsoft.ProjectReunion-0.8.5`
5. Notice the install fails (expected)

**Expected behavior**
Installing the NuGet package should fail when installing to .NET Framework / .NET Core / UWP apps. It should only install on app types that are supported. We can use the TFMs to declare `net5.0-windows10.0.17763` and I think for C++, the `native` TFM.

**Comment by LegendaryBlair** [comment]
The latest behavior is to show user a warning message and fail the build. 
However, nuget package installation is still successful, which should be fine.
