### ISSUE TITLE
Templates listed wrong under "Platform"

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#1665]
**Describe the bug**
The WinUI templates also adds a "Windows App SDK" category that incorrectly gets placed under platform:
![image](https://user-images.githubusercontent.com/1378165/139162163-8420cd25-97a6-44f1-bff8-35c8156f5111.png)

I'm not sure what the purpose of this category is though, it already has a WinUI category which is probably what you'll be using to start a WinUI app. I'd suggest removing the category #LessIsMore

**Steps to reproduce the bug**

1. Install the preview 3 C#extension for VS2022
2. Create a new project and check the project dialog

**Expected behavior**
Windows App SDK isn't under the 'platform' section.

**Screenshots**
![image](https://user-images.githubusercontent.com/1378165/139162163-8420cd25-97a6-44f1-bff8-35c8156f5111.png)

**Version Info**

NuGet package version: 1.0.0 preview 3
VS 2022 RC3.

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by DrusTheAxe** [comment]
@BenJKuhn serve, return volley... :-) Forgot to tag you on the [reply above](https://github.com/microsoft/WindowsAppSDK/issues/1665#issuecomment-953483721). Are you asking about that? Is the 'fix' that simple?

**Comment by andrewleader** [comment]
@BenJKuhn @DrusTheAxe any updates on this? We definitely should NOT be introducing a new Platform category here, sounds like we always had this (previously as Project Reunion) though, but we shouldn't have this.

It definitely seems like it should be as simple as just removing that line from the VS templates. We already correctly have the `Windows` platform tag so we show up there.

@DefaultRyan would this be something you'd own? Are there any internal bugs tracking this yet?

**Comment by andrewleader** [comment]
I've created an internal bug to track this [Bug 36933899: WinAppSDK VSIX incorrectly adds Windows App SDK as a "Platform" in the new project choices](https://microsoft.visualstudio.com/OS/_workitems/edit/36933899).

We'll fix this in a 1.0 servicing release after GA. Thank you @dotMorten for bringing this to our attention!

**Comment by DefaultRyan** [comment]
Thanks @andrewleader. I'm playing with the VSIXs a lot lately, so I'm happy to take it, or if @DrusTheAxe wants to keep this assigned to him, that's fine with me as well.

**Comment by DrusTheAxe** [comment]
> Thanks @andrewleader. I'm playing with the VSIXs a lot lately, so I'm happy to take it, or if @DrusTheAxe wants to keep this assigned to him, that's fine with me as well.

All yours :-)
