### ISSUE TITLE
Add support for Mac and Linux with uno platform.

### ISSUE THREAD

**Issue by chiddekel** [microsoft/WindowsAppSDK#1668]
Add support installation runtime and library (WinRT/UWP) to Linux and Mac just like adding installation package for
.net core to any of dose. Multiplatform support to SDK can be powered by [Uno platform](https://platform.uno).
In that way, runtime, lib, and SDK will be truly Multiplatform solutions provided by Microsoft and can bring Microsoft store apps to any platform.

**Comment by andrewleader** [comment]
Thanks @chiddekel, .NET MAUI is our supported platform and where we are investing for writing a desktop app that runs on Windows and Mac: https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui

And it looks like MAUI has some Linux support provided by the community according to their docs: https://docs.microsoft.com/en-us/dotnet/maui/supported-platforms#additional-platform-support
