### ISSUE TITLE
MddBootstrapAutoInitializer.cpp: `error C3861: 'exit': identifier not found`

### ISSUE THREAD

**Issue by shelllet** [microsoft/WindowsAppSDK#1683]
I use 1.0-preview3  to create new project and then move old project files to new project.
when finnaly compiling, the flowing error appeared ,  I am very confused!

![image](https://user-images.githubusercontent.com/16729017/139516730-b31c3b77-a42b-4890-b9ab-b13887614128.png)

**Comment by DrusTheAxe** [comment]
@Scottj1s `exit()` is a C API. Should this be `ExitProcess()` to minimize dependencies?

Or should the autoinitializer be replaced by inline-code in the XAML generated main?

Or the WinUI generated main have an optional callout at its start to PreMain? That can be done without adding a new source file to compile e.g.

```
#if __has_include(<WinUI-Main-Extensions.h>)
#define __USE_WINUI_MAIN_EXTENSIONS 1
#else
#undef __USE_WINUI_MAIN_EXTENSIONS
#endif

main()
{
...
#if defined(__USE_WINUI_MAIN_EXTENSIONS)
    const auto hrWinUIMainExtension{ WinUI::Main::Extension::PreMain() };
    if (FAILED(hrWinUIMainExtension))
    {
        ExitProcess(hrWinUIMainExtension);
    }
#endif
```

and  the autoinitializer logic can move into `WinUI-Main-Extensions.h` e.g.

```
namespace WinUI::Main::Extension
{
HRESULT PreMain()
{
    ...call MddBootstrapInitialize()...
}

HRESULT PostMain()
{
    MddBootstrapShutdown();
    return S_OK;
}
}
```

Perhaps just make the main change and update **templates** to provide WinUI-Main-Extensions.h like above? That wouldn't be XAMLgenerator just a file in a project so not overwritten if/when the generator's re-run. This way devs could alter that if/when they choose (and do other things if they need).

**Comment by Scottj1s** [comment]
@ShashankNay - looks like replacing exit() with failfast still needs to be done

**Comment by Scottj1s** [comment]
I like the idea of a #if __has_include(...) as a developer hook for overriding error handling behavior - @ShashankNay, let's discuss.  One approach is to use a function template to provide default behavior (DebugBreak, MessageBox, etc), and allow the developer to 'override' that with a non-templated function via #if __has_include inclusion.
