### ISSUE TITLE
[1.0-preview3]Global `DependencyProperty` cause app crash ' 0x80040154 : 'Class not registered'.'

### ISSUE THREAD

**Issue by shelllet** [microsoft/WindowsAppSDK#1684]
the flowing code  cause app crash. 1.0-preview3
```
static Microsoft::UI::Xaml::DependencyProperty G_title_property = DependencyProperty::Register(
    L"Title",
    winrt::xaml_typename<winrt::hstring>(),
    winrt::xaml_typename<App1::MainWindow>(),
    nullptr
);
```

1. Create a new app using the "Blank App, Packaged (WinUI 3 in Desktop)" project template.
2. Add `<WindowsPackageType>None</WindowsPackageType>`
3. Change `
<AppxPackage>false</AppxPackage>
<AppContainerApplication>false</AppContainerApplication>
`
4. Delete package.appxmanifest from the project.

![image](https://user-images.githubusercontent.com/16729017/139518172-31f2f8c8-61a9-4dc8-b521-586bc31bfa4a.png)

compile and debug app:

crush:
```
Exception thrown at 0x00007FFB0370466C (KernelBase.dll) in App1.exe: WinRT originate error - 0x80040154 : 'Class not registered'.
Exception thrown at 0x00007FFB0370466C in App1.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x00000045FEEFEDF8.
'App1.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
Unhandled exception at 0x00007FFB0370466C in App1.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x00000045FEEFEDF8.

```

**Comment by seven-mile** [comment]
COM, WinRT and WinAppSDK all need initialization. You apparently cannot create object before initialization.
Use `static Microsoft::UI::Xaml::DependencyProperty G_title_property {nullptr};` instead, and initialize it at a proper time (Application::OnLaunch or singleton pattern, etc).

**Comment by shelllet** [comment]
So I have to change a lot of code to upgrade to p3 for unpackage app.

**Comment by shelllet** [comment]
> COM, WinRT and WinAppSDK all need initialization. You apparently cannot create object before initialization. Use `static Microsoft::UI::Xaml::DependencyProperty G_title_property {nullptr};` instead, and initialize it at a proper time (Application::OnLaunch or constructor, etc).

Thks

**Comment by BenJKuhn** [comment]
@shelllet can you confirm whether the advice from @seven-mile resolved your issue, you whether you still have questiosn / concerns.

**Comment by shelllet** [comment]
Thks
So what api should I call to set the default language?

**Comment by shelllet** [comment]
Thks this should  be work,   but i  encounter that another question in my project and  and  asking for help now . i  can't start my unpack app  to test.

**Comment by andrewleader** [comment]
It sounds like this specific issue has been resolved, marking as closed. If you still need help on the other issues, please add a comment to the other issues and keep the discussion on those issues. Thank you!
