### ISSUE TITLE
Windows without Titlebar has a white border when maximized.

### ISSUE THREAD

**Issue by martibravo** [microsoft/WindowsAppSDK#1693]
**Describe the bug**
Using the OverlappedPresenter.SetBorderAndTitlebar(false,false) to hide caption buttons and borders.

- Hiding the titlebar creates a 1px white stripe on top of the window when maximized.

**Expected behavior**
(1) There should not be any white stripes at the top or the bottom of the app when maximized.

**Screenshots**
![image](https://user-images.githubusercontent.com/7605780/139605556-207ef6ae-be7d-47d1-b817-0051386bbcf5.png)

**Version Info**
WindowsAppSDK-1.0.0-preview3

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22483)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by rkarman** [comment]
Tracked by http://task.ms/36947410

**Comment by ionvasilian** [comment]
The reported issue was fixed with version 1.1 of the WindowsAppSDK. Thank you for the report.
