### ISSUE TITLE
If (When?) global C# usings are added, include %(Platform) metadata

### ISSUE THREAD

**Issue by jonathanpeppers** [microsoft/WindowsAppSDK#1700]
# Proposal: C# global usings

## Summary

If C# global usings, are added for the Windows App SDK, then .NET MAUI needs a way to turn them off in MSBuild. A `Platform="Windows"` item metadata would make this possible.

Currently, the plan for .NET 6 is for MAUI to do something like:

```xml
<ItemGroup Condition=" '$(UseMaui)' == 'true' and ('$(ImplicitUsings)' == 'true' or '$(ImplicitUsings)' == 'enable') ">
  <Using Remove="@(Using->HasMetadata('Platform'))" />
</ItemGroup>
```

They are working on a potential better design in .NET 7.

If the Windows App SDK doesn't add C# global usings, then you don't need to do anything. Thanks!

## Rationale

If .NET MAUI doesn't have a way to turn these off, then `Microsoft.Maui.Button` and the Windows `Button` (and every other type that has the same name), will conflict.

## Important Notes

Related: https://github.com/dotnet/sdk/issues/21996

**Comment by DrusTheAxe** [comment]
@Scottj1s more your lane than mine. Tag you're it :P

**Comment by DrusTheAxe** [comment]
> If the Windows App SDK doesn't add C# global usings, then you don't need to do anything. Thanks!

That's out intent. The proposed patch to make the auto-initializer be agnostic to others using global usings is righteous but WinAppSDK has no intention to use or require global usings.

**Comment by jonathanpeppers** [comment]
I think the guidance for https://github.com/dotnet/sdk/issues/21996 is that adding global usings in a NuGet package is not recommended yet. (There isn't a good design for it yet in .NET 6)

If the Windows App SDK is ever a .NET workload, global usings might be a nice feature to add, though.

**Comment by Scottj1s** [comment]
I concur with @DrusTheAxe - no action needed now
