### ISSUE TITLE
List of APIs that don't work from unpackaged apps

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1702]
Starting this issue to track APIs that don't work from unpackaged apps, so we can then figure out a plan for how we should address these.

API | Behavior | Expected behavior
--|--|--
Windows::Globalization::ApplicationLanguages::PrimaryLanguageOverride | Throws an error #1687 | Would make sense if it worked
Microsoft.Windows.ApplicationModel.Resources.<br>[ResourceManager.MainResourceMap.ResourceCount](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourcemanager.mainresourcemap?view=windows-app-sdk-1.0) | Throws "The process has no package identity." https://github.com/microsoft/WindowsAppSDK/issues/1702#issuecomment-957066788 | Since this is a WinAppSDK API, it probably should work for all types of apps?

**If you have APIs to add to the list, add a comment and I'll add it to the table!**

**Comment by riverar** [comment]
@andrewleader How shall folks contribute? Open a normal issue and you maintain this meta issue?

**Comment by andrewleader** [comment]
People can add comments to this issue and I'll update the thread, but yeah I'll also link and update other issues to this too

**Comment by shelllet** [comment]
So ,how should unpackaged apps set default language?

**Comment by shelllet** [comment]
The process has no package identity.
```
ResourceManager().MainResourceMap().ResourceCount();
```

**Comment by shelllet** [comment]
If my desktop app can be started smoothly and deploy successful under the unpacked application, then I think the 1.0 unpacked feature is basic completed. but now it's far way from ended. i was blocked by this now.

**Comment by andrewleader** [comment]
@shelllet we'll help you with how to set default language on your other thread #1687

And I've added ResourceManager.MainResourceMap to the list, thanks!

**Comment by huichen123** [comment]
I don't think ResourceManager.MainResourceMap.ResourceCount throws. WIL will show a message in the VS debugger output window, but the code does not throw.

**Comment by andrewleader** [comment]
I just found out we have an excellent list of APIs that don't work from unpackaged apps in our docs already: https://docs.microsoft.com/windows/apps/desktop/modernize/desktop-to-uwp-supported-api

I'll close this issue and we'll use that docs page as the official list. I've already asked for these two APIs to be added to that docs page, if anyone else finds any additional APIs not listed, you can either add a comment here or add a comment on the docs page!

**Comment by huichen123** [comment]
@andrewleader Please don't add ResourceManager.MainResourceMap.ResourceCount into the list. It's a WindowsAppSDK API, and should work for unpackaged. If it doesn't it would be a bug, and I think it works.

**Comment by andrewleader** [comment]
Thanks @huichen123, could you (at some point) test out ResourceCount in a sample and verify it works from unpackaged? Thanks!

**Comment by huichen123** [comment]
@andrewleader I did, and it didn't throw.

**Comment by shelllet** [comment]
@huichen123  [Walkthrough: Create a C#/WinRT component and consume it from C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/create-windows-runtime-component-cswinrt)

C#/Winrt compoent don't work from unpackaged app.

**Comment by andrewleader** [comment]
@shelllet you can use CsWinRT to create a C# WinRT component that's consumable by C++ apps, [here's some docs on that](https://github.com/microsoft/CsWinRT/blob/master/docs/authoring.md), if you have issues you can report it on [their repo](https://github.com/microsoft/CsWinRT).

**Comment by shelllet** [comment]
@andrewleader  i just  want to say  `cppwinrt`  refrecence  `cswinrt ` compoent   aslo throws "The process has no package identity."
