### ISSUE TITLE
Single project MSIX VSIX doesn't get automatically installed on VS 2019

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1729]
### Describe the bug

**Internal bug (for MS employees):** https://microsoft.visualstudio.com/OS/_workitems/edit/36926828

**What is the product/business impact?**
(This works fine on VS 2022). Users that download the Windows App SDK VSIXs for **VS2019** will not automatically get the single-project MSIX packaging VSIX. As far as I know, there won't be a prompt telling them to download the VSIX, they'll just get errors when building or deploying a non-WAP app.

**What is the issue?**
Dev16 VSIXs built manifest is missing the extension pack reference to the single-project MSIX packaging VSIX.
Conditional logic was added that would keep the MSIX packaging VSIX in Dev17 standalone builds destined for the marketplace, but excluded if from the component builds destined for Visual Studio integration. Unfortunately, that logic also made it into the Dev16 VSIX builds, where the conditional was handled differently, so the MSIX packaging VSIX ended up being unconditionally excluded from Dev16.

**What is the fix and most likely regression?**
The fix is to revert the Dev16 VSIX back to including the MSIX packaging VSIX unconditionally.
This is a change that only affects how the VSIX is built and installed, so that installing the Windows App SDK Dev16 VSIXs will install also install the MSIX packaging VSIX. This is how the Dev17 VSIXs are already configured, and so we're simply restoring parity between Dev16 and Dev17.

No product regressions are expected. We have had difficulties in past releases with the VS Marketplace backend not handling the VS extension pack properly, but they have assured us the issue is fixed, and will rapidly resolve any future problems of this sort. To reiterate, this functionality already exists in the Dev17 VSIXs, so restoring this functionality to the Dev16 VSIXs does not introduce any new risk.

### Steps to reproduce the bug

1. Install VS 2019
2. Attempt to install the WinAppSDK VSIX
3. Notice it gives an error about not being able to install Single Project MSIX VSIX

### IDE

Visual Studio 2019

### NuGet package version

Microsoft.WindowsAppSDK 1.0.0-preview3

**Comment by DefaultRyan** [comment]
This is fixed in main and release/1.0-stable
