### ISSUE TITLE
Availability of the `uap10-xx` target framework in 1.0

### ISSUE THREAD

**Issue by BenJKuhn** [microsoft/WindowsAppSDK#1730]
The existence of this folder is causing some confusion & concern, both in terms of people using and valuing it, and in how it facilitates an unsupported developer scenario. These two considerations seem at odds. I'm opening this as an issue to track working out the best way to update our package layout or metadata (if at all) to provide the best experience practical with the tools available.

### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1655

<div type='discussions-op-text'>

<sup>Originally posted by **jeromelaban** October 27, 2021</sup>
As the UWP target has been officially announced as not being supported by the WinAppSDK, what will be the fate of the `uap10.0` projections in the `Microsoft.WindowsAppSDK.*` packages? 

Are they still going to be included, and for how long?

![image](https://user-images.githubusercontent.com/5839577/139088416-61649125-d4ba-4d27-8249-dea329ec9a7f.png)</div>

**Comment by Jaiganeshkumaran** [comment]
You support .NET 5 WinForms and WPF apps but not UWP?

**Comment by riverar** [comment]
> You support .NET 5 WinForms and WPF apps but not UWP?

Yes.

**Comment by Gavin-Williams** [comment]
> You support .NET 5 WinForms and WPF apps but not UWP?

It seems crazy doesn't it.

**Comment by Jaiganeshkumaran** [comment]
To be fair to UWP, Microsoft should also not support WinForms and WPF anymore especially with latest .NET support.

**Comment by LegendaryBlair** [comment]
Close as by design.
