### ISSUE TITLE
Cannot publish app using 0.8.5 to Store

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1749]
### Bug summary

Two customers have reported being unable to publish an app that's using Project Reunion 0.8.5 to the Store, while publishing an app using 0.8.4 seemingly works.

![image](https://user-images.githubusercontent.com/13246069/140814416-afb6d5d1-dae5-431e-a4c7-ba9eb7fd30a3.png)

### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1695

<div type='discussions-op-text'>

<sup>Originally posted by **giraudremy** November  1, 2021</sup>
Hi,

I have update my projet to 8.2 => 8.5, I have generate my package to update my store app, but when I upload the package to the Microsoft Store I have this error :

Votre package Microsoft.ProjectReunion.0.8 spécifie la version 8005.278.2204.0, alors que 8000.167.1906.0 est la version minimale disponible.

I don't know what I need to change to solve this issue.

Any Idea ?

Thank </div>

**Comment by BenJKuhn** [comment]
The servicing update had been published to Nuget.org but not deployed to the store. The updated framework is now available in the store as well.

**Comment by andrewleader** [comment]
Closing as 0.8.5 is now available in the Store as Ben said!
