### ISSUE TITLE
.NET 6  and WINUI3 fails to start  Unable to load DLL 'Microsoft.ui.xaml.dll'

### ISSUE THREAD

**Issue by devlead** [microsoft/WindowsAppSDK#1762]
### Describe the bug

When running WINUI3 on Windows 10 ( 21H1 19043.1083 ) looks like the application never launches, but is application crashes with the below error in the event log

```
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

### Packaged
1. Install Windows 10 21H1 19043.1083 
1. Install the latest Microsoft.WindowsAppRuntime.Redist.1.0.0
1. Install MSIX dependencies
1. Install application MSIX
1. Launch the application
1. Application never launches (well crashes)

### Unpackaged, 
1. Install Windows 10 21H1 19043.1083 
1. Install the latest Microsoft.WindowsAppRuntime.Redist.1.0.0
1. Copy compiled output
1. Launch the application
1. Application never launches (well crashes)

### Packaged
1. Install Windows 10 21H2 2200.194
1. Install the latest Microsoft.WindowsAppRuntime.Redist.1.0.0
1. Install MSIX dependencies
1. Install application MSIX
1. Launch the application
1. Application never launches (well crashes)

### Unpackaged, 
1. Install Windows 10 21H2 2200.194 
1. Install the latest Microsoft.WindowsAppRuntime.Redist.1.0.0
1. Copy compiled output
1. Launch the application
1. Application never launches (well crashes)

### Expected behavior

For the application to launch.

### IDE

Visual Studio 2022

### NuGet package version

Microsoft.WindowsAppSDK 1.0.0-preview3

### Project type

- Packaged
- Unpackaged

### Windows version

Windows 11 (22000), May 2021 Update (19043)

**Comment by kmgallahan** [comment]
https://github.com/CommunityToolkit/WindowsCommunityToolkit/pull/3998#issuecomment-963546873

**Comment by devlead** [comment]
Currently, get same issue with .NET 5 too though
```
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at .Program.XamlCheckProcessRequirements()
```

Works on a Machine with Visual Studio and Visual Studio Extension installed.

**Comment by devlead** [comment]
Seems like others are having similar issues #974

**Comment by MikeHillberg** [comment]
I've seen that when the [VCRedist ](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) wasn't installed on the target machine, which would explain why you don't see it on a machine with VS installed.

**Comment by stewienj** [comment]
@MikeHillberg Thanks, that was the solution to this problem.

**Comment by devlead** [comment]
@MikeHillberg this indeed sorted the issue 👍

**Comment by stewienj** [comment]
I think the problem here is the assumption that you can just xcopy your build output to another PC and run it when you put this in your project file:
```xml
<!-- This bundles the .NET Core libraries -->
<SelfContained>true</SelfContained>
<!-- This bundles the WinUI3 components -->
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
```
I see a few potential fixes for people running into this problem:
- The app should detect the missing C++ runtime DLLs and throw up a message, or log a message stating the C++ runtime needs to be installed.
- There should be a nuget package available from Microsoft that allows you to bundle the C++ runtime DLLs with your app.
- There could be a project file flag that copies the required DLLs to the build directory

**Comment by MikeHillberg** [comment]
Yes, <SelfContained> is WRT the .NET runtime, not the WindowsAppSDK runtime.

**Comment by bryaan** [comment]
I'm having this issue as well and don't know what the solution is.  I already have the Redistributable.

**Comment by yshteinm** [comment]
When I run Packaged app on my machine it works. When I run Unpackaged app it doesn't. When I run exe from console it doesn't work. When I deploy an app to another machine it doesn't work. When I say it doesn't work it maens I am getting an error either in Event Viewer or dialog box "Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies"

**Comment by candritzky** [comment]
I'm still having the same problem, also after reinstalling VCredist 14.30.30704.

**Comment by stewienj** [comment]
@candritzky I had the same issues on Windows 10 version 1909 and installing the VC++ runtime didn't fix it. I copied the following DLLs from my dev PC to my apps directory on the target PC and it worked. They might not all be required though:
concrt140.dll
msvcp140.dll
msvcp140_1.dll
msvcp140_2.dll
msvcp140_atomic_wait.dll
msvcp140_codecvt_ids.dll
vcruntime140.dll
vcruntime140_1.dll

**Comment by pjc2007** [comment]
I just installed VS 2022, and the WindowsAppSDK.Cs.Extension.Dev17.Standalone.vsix

I started a new WinUI3 project form the templates. F% debug running **packaged** is ok, but I get this error when I select **WinUIDeploy (Unpackaged)** . This is trying to start within VS.

**Comment by KerryRJ** [comment]
I had to change this in the .wapproj, from
```xml
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
```
to
```xml
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0">
  <IncludeAssets>build</IncludeAssets>
</PackageReference>
```
and finally got the packaged app to install and run on my dev pc (outside of VS2022) and a on two non-dev pcs.

I didn't need to install the VC redistributables.

**Comment by turkerdev** [comment]
If you are trying to run unpackaged version, do not forget to add this code to "csproj" file.
```xml
<WindowsPackageType>None</WindowsPackageType>
```
[Microsoft reference](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-csharp)

**Comment by bryaan** [comment]
> I had to change this in the .wapproj, 
> ```
> <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0">
>   <IncludeAssets>build</IncludeAssets>
> </PackageReference>
> ```

When I try this the code doesn't compile because it is now missing all xaml references.  For example, Application and Window are no longer found.

**Comment by wstaelens** [comment]
has this been resolved? same issue.

**Comment by niels9001** [comment]
@MikeHillberg Ping on this - I'm getting the same issue with 1.0.1.

**Comment by markolbert** [comment]
I'm getting the same problem on 1.0.1 as well. Any timeline on when it'll be resolved/fixed?

**Comment by FrogsLegs** [comment]
I'm getting the same problem on 1.0.2 also today. Is there any known workarounds until this is resolved?

**Comment by markolbert** [comment]
> I'm getting the same problem on 1.0.2 also today. Is there any known workarounds until this is resolved?

FWIW my problem ended up being an exception being thrown deep inside the logging subsystem of my code. Which kept the logging system from reporting on anything. 

But the problem only occurred on test machines, not on my development machine (due to the nature of the bug). Since this was outside the Visual Studio environment I couldn't see the actual bug when I ran the app under WinDbg on the test machine. It was a royal PITA to find (you can read about [how I found it on my blog](https://www.jumpforjoysoftware.com/2022/04/the-dog-in-the-night/)).

Why that manifested itself as a failure to load Microsoft.ui.xaml.dll I have no idea.

**Comment by smdhz** [comment]
Since it still happens now,
I wonder why the issue is closed.

**Comment by FrogsLegs** [comment]
> When I run Packaged app on my machine it works. When I run Unpackaged app it doesn't. When I run exe from console it doesn't work. When I deploy an app to another machine it doesn't work. When I say it doesn't work it means I am getting an error either in Event Viewer or dialog box "Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies"
> I am running Released version 1.0.0

This is the exact issue we're seeing with v1.0.2

**Comment by Kromi75** [comment]
I have the same issue with v1.0.3 on my dev machine. No matter how I publish my app (self-contained, framework-dependent), the app crashes immediately after starting. In the Windows event log I find the error "Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies".

**Comment by s3nt1n3l-hub** [comment]
We are also having this issue. Reinstalling VCRedist didn't help, nor did any of the other suggestions above. We also recreated the issue by creating a new WinAppSDK packaged app, publishing/installing/executing it. We also attempted to change the TargetFramework from net6.0xxx to net5.0xxx but continued to receive the error.

**Comment by FrogsLegs** [comment]
@devlead should this issue be reopened?

**Comment by joaquinlopez61** [comment]
I recently install visual studio 2022 and testing maui app with windows and I getting this error. All solutions proposed above has been done, but error persists

![image](https://user-images.githubusercontent.com/104583625/165795299-1582b680-447f-4494-a6c7-ea667ef1e404.png)

**Comment by myokeeh** [comment]
Trying to get into WinUI with the new Template Studio for WinUI and this is what I run into right away.

**Comment by itsbeer** [comment]
Ditto to @myokeeh I am in the same bucket. Running the project packaged fails to run with VS reporting "The project doesn't know how to run the profile {insert profile name here} (Package)" [ it actually lists the profile name in between the curly brackets ] and running unpackaged results in "System.DllNotFoundException: 'Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)'". Both tries had x86 and Debug set (that was the default when I created the project using the new Template Studio extension.

**Comment by clamchoda** [comment]
I just tried the latest preview to give MAUI Blazor a shot. Running the Windows application from within Visual Studio works fine but any of the built executables fail to load. In the event viewer you'll find the same exception listed in this thread;

```
Application: FMaps.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at FMaps.WinUI.Program.XamlCheckProcessRequirements()
   at FMaps.WinUI.Program.Main(String[] args) in C:\Users\username\Documents\Visual Studio 2022 Preview\FMaps\FMaps\obj\Release\net6.0-windows10.0.19041.0\win10-x64\Platforms\Windows\App.g.i.cs:line 28
```

OS Name	Microsoft Windows 10 Home
Version	10.0.19044 Build 19044

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 5.0

**Comment by Fox15145** [comment]
Also having the issue, tried a lot...
Waiting for an answer

**Comment by mikebattista** [comment]
@myokeeh @itsbeer 

First, make sure you have the WinAppSDK prerequisites installed per https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b. "The project doesn't know how to run the profile" errors suggest you might be missing some prerequisites like the tooling for single-project packaging that comes with the VS components.

Second, if for unpackaged you just changed the dropdown to Unpackaged, that's not expected to work, and I get the same Microsoft.ui.xaml.dll error as you. You need to set `<WindowsPackageType>None</WindowsPackageType>` in the csproj per https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app#non-msix-packaged-create-a-new-project-for-a-non-msix-packaged-c-or-c-winui-3-desktop-app, but also there's a different implementation of settings storage for unpackaged vs. packaged in the [Template Studio](https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForWinUICs) projects. If you want to try unpackaged, remove the MSIX feature in the Template Studio wizard when you create the project and it will set everything up for you. Also be sure to install the latest [WinAppSDK 1.0 runtime](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-10) which is required for framework-dependent unpackaged apps. Self-contained deployment won't require this runtime but that's not supported until 1.1 and the Template Studio projects currently target 1.0.1.

**Comment by myokeeh** [comment]
@mikebattista that got it going. Thanks for the help.

**Comment by mikebattista** [comment]
Awesome. The next update to Template Studio will have a .vsconfig that will prompt you to install any required VS components you might be missing.

https://github.com/microsoft/TemplateStudio/issues/4479

**Comment by jevonsflash** [comment]
I have the same problem  https://github.com/microsoft/WindowsAppSDK/issues/2448#issuecomment-1120113181
If I set up <WindowsPackageType>None</WindowsPackageType> and run Unpack, I will get a System.Runtime.InteropServices.COMException error

**Comment by mikebattista** [comment]
> I have the same problem [#2448 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/2448#issuecomment-1120113181) If I set up None and run Unpack, I will get a System.Runtime.InteropServices.COMException error

Usually that means you don't have the WinAppSDK Runtime installed from https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-10.

**Comment by joaquinlopez61** [comment]
![image](https://user-images.githubusercontent.com/104583625/167311955-52ca4ba5-e1f1-4e63-86d3-16c5e034de60.png)
After install this component downloaded from this link  https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-10 the problem was fixed. 

Thanks for you help @mikebattista

**Comment by h3dev** [comment]
After updating to VS 2022 17.2.1 my old project does not run
![image](https://user-images.githubusercontent.com/69046210/169620340-ed6cdfdb-6528-4f53-bdbd-e330427122a3.png)

When creating a new WinUI3 project with new Template Studio the new project compiles and start. But the old and finished project does not.
What could be this error?

**Comment by CaffeineAU** [comment]
I experienced this issue with a PC running within Visual Studio 2022 17.2.1 on Win 10 1909 (18363.2094) with all of the appropriate packages installed, as per this thread.

The target version OS version in the project was 10.0.19041.0. I changed that to 10.0.18362.0 and the project ran successfully.

**Comment by Axemasta** [comment]
I was experiencing this issue on a repository stored in git, but not with a file new maui app. The issue was that the `launchSettings.json` hadn't been checked in and once updated I was able to launch the winui app:

```json
{
  "profiles": {
    "Windows Machine": {
      "commandName": "MsixPackage",
      "nativeDebugging": false
    }
  }
}
```

**Comment by Noemata** [comment]
Today (July 27, 2022) I did a fresh install of VS2022 and the Windows App SDK components.  I ran into two separate issues.  The information here helped me resolve the Unpackaged problem.  Yes, if you hunt around the provided documentation it is possible to get to a working state independently, but I doubt that will be the case for most users attempting to try out WinUI.  The biggest issues was having to install this "https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17" which is still labeled as a preview causing one to question whether it is still a prerequisite.  The provided installation documentation is also incorrect/misleading.  Selecting Unpackaged from the dropdown should insert/adjust the required WindowsPackageType flag.  The requirement of the Packaging Tools needs to be made a part of the templates download list.  Incorrect/misleading information needs to be removed through proper vetting.

**Comment by kaptainkev** [comment]
https://nicksnettravels.builttoroam.com/packaged-unpackaged-self-contained/
This Link has the answer that helped me. It was a life saver.

The blog shared this: 

The main this is you want to run your application as unpackaged. Do these two things first
1. Add a property to the csproj file for your application, <WindowsPackageType>None</WindowsPackageType> under   <PropertyGroup> tag
2. Remove the package.appxmanifest file from your project
3. Run the Application as Unpackaged

**Comment by Nerklers** [comment]
@kaptainkev You saved my day! Thank you so much for sharing this!

**Comment by dotMorten** [comment]
I'm still getting reports from people hitting this issue left and right, both maui and vanilla winui projects.
If there indeed is a component missing issue or a project deployment/configuration issue, could we please have the build tooling detect this before launching the app, and warn the developer with the proper corrective action and guidance, instead of this completely unhelpful error message? This goes back to improving the overall developer experience, and this one seem so common - I hear about it almost every week, and we never know for sure what the resolution is this time. @ryandemopoulos? @andrewleader

**Comment by dshe** [comment]
In your **csproj** file, under the `<PropertyGroup>` tag, try adding:
         `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`

[Windows App SDK deployment guide for self-contained apps](https://docs.microsoft.com/en-us/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps)

**Comment by gmgallo** [comment]
And here is another case for your list. I hope this sheds some light on where to look for. In my case I was working on a Template Studio project for weeks running on the VS machine. When I reached the point earlier this week to start packing the project and remote debug on the target machine evrithing went array. Now, when I try to run the app unpacked, locally or remote, I get the this error.  Switching back to an earlier version of this same app it still runs fine locally and generates the package with compilation (I didn't mess with this one to remote debug so I have a safe place to roll back if needed). Comparing both project files there are clear differences. However, the problem is not there. Both apps with identical project setttings one runs unpacked and the other don't.

**Comment by mikebattista** [comment]
What do you mean by packed and unpacked? With MSIX (packaged) and without MSIX (unpackaged)?

**Comment by gmgallo** [comment]
Yes MSIX packed. 
Right now I gave up trying to fix the crippled project. Started a new TS with two blank pages and made sure that MSIX packed and unpacked runs fine local and remote. So far so good, they do. Do you want a copy of the bad project to have a look?

**Comment by mikebattista** [comment]
What did you change between the known good version and the crippled version?

**Comment by gmgallo** [comment]
As commented earlier, the problem started when I setup for remote debug over the local network. I had to try and error a couple of times until I got the settings right to work with MSIX packed to remote debug on the target, but at that point I lost the capacity to run the app unpacked anyware. 
Before that, last week I created a couple of Publish profiles: release x86 and release x64, and ran them. At that time I was not doing remote debug. Maybe that threw a wrench in the settings somewhere?
Both project files had differences but after make the bad one identical to the good one made no difference. 
Very frustrating, I wasted countless hours faighting the tool instead of doing my work.

**Comment by gmgallo** [comment]
The good news on this one is that I did find the source of the problem in the publish profiles. While trying to get the settings right for remote debugging I changed the default target locations in the Publish Profles. Replacing the files in the project->Properties->PublishProfiles with a copy of the untouched ones from the good project fixed the problem.  The crippled app now runs normally (I haven't try the remote debug yet).
I can see that there is a copy of the missing Microsoft.ui.xaml.dll in the good app project here: 
`...\Good App\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\AppX\Microsoft.ui.xaml.dll`
But it is missing in:
`...\Crippled App\bin\x86\Debug\net6.0-windows10.0.19041.0\win10-x86\AppX`
Maybe Windows caches it somewhere?

Lesson learned: **Don't mess with the publishing profies!**

**Comment by dotMorten** [comment]
In one case.the launch settings file got hidden from git and didn't get checked in. The launch error is completely unhelpful trying to troubleshoot this

**Comment by gmgallo** [comment]
Well, it seems that I claimed victory too soon. The crippled app started to fault again in Main() ->   XamlCheckProcessRequirements();
Now both projects have the same unmodified files in the PublishProfiles folder.
I don't see any substantial difference in the project files, but genrating Debug x86 in both projects ceates a subtatially different set of output filles with missing files and folders. Notably AppX is not there as well as Microsoft.ui.xaml.dll, and all its cousins. I created dir listings of both projects attached here.
[bad_dir.txt](https://github.com/microsoft/WindowsAppSDK/files/9492049/bad_dir.txt)
[good_dir.txt](https://github.com/microsoft/WindowsAppSDK/files/9492050/good_dir.txt)

**Comment by OldManWangJY** [comment]
If the target platform is X64, there will be problems, X86 will not have any problems

**Comment by SamusAranX** [comment]
I'm getting this exact error message when trying to run the default WinUI 3 project template. How do I fix this?

**Comment by gmgallo** [comment]
Once the app started to fail, I couldn't find a way to fix it. So, I started the project from scratch a couple of times, and gave up trying to debug it to a remote machine.  In my case the release MSIX pack installs fine in the target machine.

**Comment by niels9001** [comment]
Make sure VS and other required stuff is up to date. Try to delete all WASDK/WinUI cache in the .nuget folder. That did the trick for me the other day.

**Comment by mwkldeveloper** [comment]
This issue occurs when starting the packaged project via WinUI App project directly.
--> the packaged project must start /set packaging project as startup
https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/pull/1256#issuecomment-1601880006

Add `<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` or  `<WindowsPackageType>None</WindowsPackageType>` to WinUI  csproj both can fix the issue.

But this is not intuitive, when you try to change packaged project to non-packaged project/ run WinUI App project directly.

If you create WInUI project only (the template without packaging project), no such issue, and don't need to add    
`<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>` or  `<WindowsPackageType>None</WindowsPackageType>`

This is so confused and inconsistent to handle WinUI App project. 
What I think to change packaged project to non-packaged project is just simple delete the packaging project or set startup project to WinUI App project directly, and all should work fine.

**Comment by dotMorten** [comment]
I’ve tried to make that argument many times. It’s how all the other packaged app projects work. No idea why WinUI needed to be 
 different but I agree its a serious developer experience flaw that has hurt so many people getting started.

**Comment by mwkldeveloper** [comment]
This is not WinUI project problem.  Yes, it is developer experience flaw.

It is quite stranger for a new dotnet developer:
When create WInUI project only (without packaging project) , it doesn't need `<WindowsPackageType>None</WindowsPackageType>`,  

But when create WInUI project with packaging project, and I try to run it directly I need add `<WindowsPackageType>None</WindowsPackageType>'`

Event I delete the packaging project, the solution still thinks it refence packaging project.

**Comment by esmorun** [comment]
Having this problem when I try to publish my app as self contained. Here are my properties, what am I doing wrong?

```
<PropertyGroup>
   <OutputType>WinExe</OutputType>
    <TargetPlatformMinVersion>10.0.18362</TargetPlatformMinVersion>
    <RootNamespace>MyWinUIApp</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <TargetFrameworks>net6.0-windows10.0.18362</TargetFrameworks>
    <StartupObject></StartupObject>
    <SelfContained>true</SelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <Nullable>enable</Nullable>
</PropertyGroup>
```

**Comment by gmgallo** [comment]
And here we go again a year later. This nasty problem cripped again in a new app that I was working for months now. Compiled and debug hundred of times without a problem except for the debugger that crassed a couple of time all the way to a blue screen (BugCheck).  But the project itself ran just fine until I tried to run a Packed release version without debuger. Then things tarted to go bad. The app didn't start, tried to run Unpacked. Same result. Going back to debug packed, the problem persists, now it doesn't run in any mode. I can't find the way to reverse it back to run debug packed. The non graphical part of the app keeps running in the backgroung and must be killed by the debugger (Ctrl+F5) or by task manager if ran drectly from file Explorer. Both VS and TemplateStudio are up to date. This must be a WinUI problem. I ran the app undr WinDbg Preview and got this out:
```
odLoad: 00007ffc`ef680000 00007ffc`ef6b0000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007ffc`2e840000 00007ffc`2e8a0000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\hostfxr.dll
ModLoad: 00007ffc`2e7d0000 00007ffc`2e834000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\hostpolicy.dll
ModLoad: 00007ffc`2e2d0000 00007ffc`2e7c8000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\coreclr.dll
ModLoad: 00007ffc`ed750000 00007ffc`ed87b000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ffc`ed960000 00007ffc`edcb4000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ffc`ed890000 00007ffc`ed95d000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007ffc`ecf40000 00007ffc`ecfc2000   C:\WINDOWS\System32\bcryptPrimitives.dll
(2e44.2e48): Unknown exception - code 04242420 (first chance)
ModLoad: 00007ffc`2d1b0000 00007ffc`2dccb000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\System.Private.CoreLib.dll
ModLoad: 00007ffc`2d030000 00007ffc`2d1ab000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\clrjit.dll
ModLoad: 00007ffc`eb540000 00007ffc`eb552000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ffc`2cf30000 00007ffc`2d025000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\TSDataLoggerApp.dll
ModLoad: 000001ab`59cf0000 000001ab`59cfe000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\System.Runtime.dll
ModLoad: 00007ffc`ea5c0000 00007ffc`ea65e000   C:\WINDOWS\system32\uxtheme.dll
ModLoad: 00007ffc`2c190000 00007ffc`2cf27000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\Microsoft.WinUI.dll
ModLoad: 00007ffc`2c000000 00007ffc`2c185000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\WinRT.Runtime.dll
ModLoad: 00007ffc`2bfc0000 00007ffc`2bffe000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\System.Collections.Concurrent.dll
ModLoad: 00007ffc`2bf80000 00007ffc`2bfbf000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\System.Collections.dll
ModLoad: 00007ffc`4db40000 00007ffc`4db53000   E:\Code\SC200\TSDataLoggerApp\bin\Release\Publish\System.Threading.dll
ModLoad: 00007ffc`ed570000 00007ffc`ed597000   C:\WINDOWS\System32\BCrypt.dll
(2e44.2e48): C++ EH exception - code e06d7363 (first chance)
ModLoad: 00007ffc`cc730000 00007ffc`cc95e000   C:\WINDOWS\SYSTEM32\icu.dll
(2e44.2e48): CLR exception - code e0434352 (first chance)
(2e44.2e48): CLR exception - code e0434352 (!!! second chance !!!)
KERNELBASE!RaiseException+0x69:
00007ffc`ed11cf19 0f1f440000      nop     dword ptr [rax+rax]
```
as you can see, the real offender icu.dll.
None of the proposed solutions here have worked for me. I must resort to the only method that works: start from scratch a new project and move all my files there, adjust namepsaces, and keep going.

**Comment by zipswich** [comment]
> If you are trying to run unpackaged version, do not forget to add this code to "csproj" file.
> 
> ```
> <WindowsPackageType>None</WindowsPackageType>
> ```
> 
> [Microsoft reference](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-csharp)

Today is December 19, 2023, and I still got the System.DllNotFoundException error after creating a barebone new app with the template:
![image](https://github.com/microsoft/WindowsAppSDK/assets/6095671/00aa5419-5a31-481d-bcb8-f80412781561)

This solution from Jan 20, 2022 still saved me.

**Comment by gmgallo** [comment]
Yes, I tried that, several references to it are in this thread, but once the damage is made, that won't fix it.  
Also I just discovered a few days ago while trying to narrow into this problem that refactoring the base namespace of a MVVM project also creates the same problem and, sometimes, compiler errors, despite the fact that, as far as I can see, refactoring do a thorough job working all over the source code and XAML files. However, some the compiler generated code, those o.i.cs files, still refer to the old namespace. Reverting the namespace back to its original at the project creation time solves the error. That strongly suggest that this is a disconnected or unresolved namespace that manifests at run time. 

And by the way, the same error happens if you try to run a freshly created WinUI3 packed project available in the VS templates. Instead, you should **run the pack project created alongside** and everything works fine, which I find counter intuitive.

**Comment by dantra13** [comment]
I'd like to share some of my experiences as I was transitioning from Unpackaged to Packaged and encountered the already discussed issue. The program ran well alongside Visual Studio, but when generating the MSIX and installing it, launching the application was blocked, both on the development machine and on others where I had set up everything needed to run the application. The error in the event log is the same:

```
Faulting application name: Crono.exe, version: 1.0.0.0, time stamp: 0x656f70bc
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.4.0, time stamp: 0xd8e270fd
Exception code: 0xc000027b
Fault offset: 0x00000000003ba2f4
Faulting process id: 0x0xDA48
Faulting application start time: 0x0x1DA749FAA3F4B7C
Faulting application path: C:\Users\mella\OneDrive\Escritorio\app\Crono.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.4_4000.1136.2333.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: ce939508-e0e0-401a-beb1-e2749a330203
Faulting package full name: 
Faulting package-relative application ID: 
```

Inspired by a blog post from @markolbert, which related similar problems to path handling in their application, led me to investigate the configuration of my project, which uses Sqlite3 with Entity Framework Core, as well as references to assets required by the project. I identified that the problem arose when trying to access the database. To solve it, I made significant changes in the way the database was accessed in the code.

Change made:

Originally, the database configuration was done as follows:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    var path = AppDomain.CurrentDomain.BaseDirectory + @"\settings.db";
    optionsBuilder.UseSqlite($"Data Source={path}");
}
```

After modifying the configuration:

```
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    string databasePath = Path.Combine(ApplicationData.Current.LocalFolder.Path, "settings.db");
    optionsBuilder.UseSqlite($"Data Source={databasePath}");
}
```

Although this modification resolves the issue, I don't understand the connection to the problem seen in the event log. I am relatively new to desktop application development, especially with WinUI3. I hope this can also be of use to you, and that you do not disregard the recommendations already mentioned.
