### ISSUE TITLE
AppInstance: Closing first instance causes second instance to crash if second instance called GetInstances()

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1766]
### Describe the bug

It seems that if the second instance of the app calls GetInstances() and then later you exit the first instance of the app, the second instance freezes up and then crashes after being frozen for 10 seconds.

### Steps to reproduce the bug

1. Install the Windows App SDK Gallery: https://github.com/andrewleader/WindowsAppSDKGallery/releases/tag/v0.0.1
2. Launch two instances of the app
3. In the second instance, go to `App Lifecycle -> Manage Instances`, and then execute the `GetInstances()` API
4. Now close the first instance (using the normal "X" window button)
5. Notice the second instance has now frozen up, and in 10 seconds, the second instance crashes

### Expected behavior

Second instance shouldn't crash.

### Screenshots

![Crash](https://user-images.githubusercontent.com/13246069/141182742-ef00b0d1-e073-4991-87fc-2e3f58b6530d.gif)

### NuGet package version

1.0.0-preview3

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

**Comment by aeloros** [comment]
This is fixed with #1636 which is not in Preview3, but made it into GA.
