### ISSUE TITLE
PowerManager.EffectivePowerMode doesn't reflect selections in the classic Control Panel power settings page

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1768]
### Describe the bug

Internal bug: https://microsoft.visualstudio.com/OS/_workitems/edit/37068244

PowerManager.EffectivePowerMode does not appear to be returning the correct results if I change my power plan in the classic Control Panel Power Options settings.

### Steps to reproduce the bug

1. Open Power Options (classic Control Panel) and set plan to `High Performance`.
2. Create new packaged WinUI 3 project (C#)
3. Alter `myButton_Click` handler

    ```csharp
    private async void myButton_Click(object sender, RoutedEventArgs e)
    {
        myButton.Content = (await Microsoft.Windows.System.Power.PowerManager.EffectivePowerMode).ToString();
    }
    ```
4. Build/deploy app
5. Click the button and observe returned power mode is `Balanced`

### Expected behavior

EffectivePowerMode::HighPerformance result

### NuGet package version

1.0.0-preview3

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by andrewleader** [comment]
@aeloros do you own the PowerManager APIs?

**Comment by andrewleader** [comment]
Also @riverar I wasn't able to repro this problem. I'm using 1.0 Preview 3 and tried on both the public non-insider Win11 and my latest internal build of Win11.

![EffectivePowerMode2](https://user-images.githubusercontent.com/13246069/141219015-9b28f1b4-6b37-4bb6-abe7-ca924d09dc84.gif)

Are you using the modern settings app or setting the power mode elsewhere?

Here's that app I'm using to test it: https://github.com/andrewleader/WindowsAppSDKGallery/releases/tag/v0.0.2 (and the source code is there too)

**Comment by aeloros** [comment]
I don't own them.  Take a look at Git history, and it might show who does all the work.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by riverar** [comment]
Ah, I was not using the modern options. I was using the Power Options applet (pictured below). Might be worth noting this somewhere in docs.

![image](https://user-images.githubusercontent.com/475132/141227612-c6512d2d-b3f0-4fad-a0f1-85e67f73c9ad.png)

**Comment by jonwis** [comment]
(PS: I've asked @huzaifa-d and @brialmsft to chat with our power folks; if there's really a difference in what the API, modern settings, and legacy control panel show here that's something we should figure out.)

**Comment by jonwis** [comment]
Also, this `EffectivePowerMode` property should be a simple value, not an `IAsyncOperation<T>` - see #1770 tracking work on that.

**Comment by riverar** [comment]
Thanks @jonwis. Feel free to re-open if you feel it's warranted.

**Comment by tristanb-ntdev** [comment]
@riverar This is a discrepancy between the configuration model used by the power control panel's power schemes vs. the power mode exposed in the settings app. The power control panel is a legacy mechanism which offers fixed behaviors for power/performance tradeoffs, compared to the modern power mode which combines user preferences with scenario/workload detection for better optimization. As it is currently implemented, the EffectivePowerMode interface only tracks the modern power mode, and so changes to the legacy power scheme are not reflected here.

The high performance and power saver power schemes are mutually exclusive with the modern power mode, but I do think that it makes sense for the system to translate those schemes into the closest equivalent effective power mode when they are selected. I've reactivated this issue and will work with @huzaifa-d to make sure the WinAppSDK is updated as soon as possible. Thanks for reporting this issue.

**Comment by LegendaryBlair** [comment]
The issue is by design, EffectivePowerMode only reflects modern power mode.
