### ISSUE TITLE
PowerManager.EffectivePowerMode should not be IAsyncOperation<T> typed as a property

### ISSUE THREAD

**Issue by jonwis** [microsoft/WindowsAppSDK#1770]
### Describe the bug

This property should instead be `EffectivePowerMode EffectivePowerMode { get; }` - WinRT properties aren't supposed to be of type `IAsyncOperation<T>` or `IAsyncAction` except in some very special cases.

See #1142 for where this was introduced, https://github.com/microsoft/WindowsAppSDK/blob/97943aa2c8f17573d4d71e7ad71dc507363f1f24/dev/PowerNotifications/PowerNotifications.idl#L98 for details.

### Steps to reproduce the bug

Try to use the `PowerManager.EffectivePowerMode` property, observe that it is async-op instead of just the mode.

### NuGet package version

1.0.0-preview3

**Comment by riverar** [comment]
Why are we concerned about breaking changes when preview to GA is **expected** to introduce breaking changes?
