### ISSUE TITLE
Build warning of missing winmds in 1.0 for C++ project

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1775]
### Describe the bug

Internal bug: https://microsoft.visualstudio.com/OS/_workitems/edit/37005396

When building C++ project, it will show following warnings. That's because we removed those winmds from 1.0 stable, but didn't remove the references in the targets.

> 1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2298,5): warning MSB3106: Assembly strong name "D:\winui\BlankAppCpp1\packages\Microsoft.WindowsAppSDK.1.0.0-20211109.1-CI-stable\build\native\..\..\lib\uap10.0\Microsoft.Windows.System.winmd" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).

> 1>C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(2298,5): warning MSB3106: Assembly strong name "D:\winui\BlankAppCpp1\packages\Microsoft.WindowsAppSDK.1.0.0-20211109.1-CI-stable\build\native\..\..\lib\uap10.0\Microsoft.Windows.PushNotifications.winmd" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\).

### Steps to reproduce the bug

1. Create a C++ project using 1.0
2. Notice the warnings that appear

### Expected behavior

No warnings should be present

**Comment by huichen123** [comment]
should have been fixed by https://github.com/microsoft/WindowsAppSDK/pull/1799
