### ISSUE TITLE
C++ apps - define a macro for WinUI 3

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#1784]
Many C++ libraries are often header-only or define their public API surface in a header file. I expect many libraries to support WinUI 3 and they may need conditional compilation to support other existing frameworks/platforms. While they could tell users to define a macro for that, since this will be common, consider defining a preprocessor directive in the C++ project templates for WInUI 3.

**Comment by btueffers** [comment]
Hi @Jaiganeshkumaran, thanks for the feedback! We're tracking this request internally with [productboard](https://portal.productboard.com/winappsdk/1-windows-app-sdk) and considering it for a future release.

**Comment by sylveon** [comment]
```cpp
#if __has_include("winrt/Microsoft.UI.Xaml.h")
```

**Comment by Jaiganeshkumaran** [comment]
> ```c++
> #if __has_include("winrt/Microsoft.UI.Xaml.h")
> ```

WinUI 2.x apps also have the Microsoft.UI.Xaml header, but they don't have the Microsoft.UI.Xaml header so this could be used instead: ```cpp
#if __has_include("winrt/Microsoft.UI.h")
```
