### ISSUE TITLE
KeyboardInput doesn't exist in Microsoft.UI.Input for WindowsAppSDK 1.0

### ISSUE THREAD

**Issue by anovik** [microsoft/WindowsAppSDK#1811]
### Describe the bug

I have the error for WindowsAppSDK 1.0 release while running the following code:

`KeyboardInput.GetKeyStateForCurrentThread(VirtualKey.Shift);`

This is the error text:

The name 'KeyboardInput' does not exist in the current context	

In the documentation the [method](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.input.keyboardinput.getkeystateforcurrentthread?view=winui-3.0) still exists. Is it a bug?

### Steps to reproduce the bug

I had the following code working for 0.8 release:
```

using Microsoft.UI.Input;

KeyboardInput.GetKeyStateForCurrentThread(VirtualKey.Shift);

```

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

May 2021 Update (19043)

### IDE

Visual Studio 2022

**Comment by riverar** [comment]
I can reproduce this, seems missing from 1.0 metadata as well. @andrewleader Wondering if this got mistakenly dropped when `ExpKeyboardInput` got dropped? Or?

**Comment by asklar** [comment]
@jlnordin @JesseCol fyi

**Comment by AtomicBlom** [comment]
I've spent the past few days testing the waters to see how my company's application will port to WinUI 3 desktop, and have been following the documentation for App SDK 1.0 Preview 3.

I've been using `Microsoft.UI.Input.InputKeyboardSource.GetKeyStateForCurrentThread(VirtualKey.Shift)`, which seems to mirror what you have with a name change.

Now that I've updated to the release App SDK 1.0, I'm still seeing InputKeyboardSource in my code, however it's missing from the 1.0 API documentation on docs.microsoft.com. I'm also seeing a Microsoft.UI.Input.Experimental in the online documentation that intellisense isn't resolving in my IDE.

Are the wrong versions of the documentation uploaded perhaps?

**Comment by andrewleader** [comment]
Thanks for reporting this folks!

I'm going to investigate with the feature teams, in the meantime, what seems most likely is that the API was renamed from 0.8 to 1.0 (and `InputKeyboardSource` is the new one going forward is my guess), and the API docs for the Input namespaces for 1.0 Stable somehow got the wrong metadata.

I'll report back when I have more info!

**Comment by jlnordin** [comment]
We found the documentation issue and it should now be corrected. @anovik:  `InputKeyboardSource.GetKeyStateForCurrentThread` is the correct API for WinAppSDK 1.0, just as @AtomicBlom mentioned. @AtomicBlom: The API documentation for InputCursor for 1.0 has also now been corrected.

**Comment by anovik** [comment]
`InputKeyboardSource` works fine for me, thanks for clarification.
