### ISSUE TITLE
Single-Project MSIX does not create .appinstaller or index.html files for auto-updates

### ISSUE THREAD

**Issue by mjfusa** [microsoft/WindowsAppSDK#1821]
### Describe the bug

When building MSIX packages with a single project MSIX for automatic updates, the <project name>.appinstaller and index.html files are not created

### Steps to reproduce the bug

1. Install the Windows App SDK 1.0 C# VSIX for Visual Studio 2022. (https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-10)
2. Create a new project: (Blank App, Packaged WinUI 3 in Desktop)
3. Close and reload solution (Known issue #1664)
4. Select "Package and Publish" > "Create App Packages"
5. Check 'Sideloading and 'Enable Automatic Updates' > Next
6. Select 'Create' a new certificate > Next
7. Accept all defaults > Next
8. Specify network share path: \\TEMP\share  (doesn't have to exist)
9. Click 'Create'
10. Click link to open AppPackages folder

### Expected behavior

App packages get created in the AppPackages folder as expected, however the expected <proejctname>.appinstaller and index.html files are not created. This prevents the app from receiving automatic updates.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

**Comment by riverar** [comment]
@mjfusa Can you try building in Release? I have a faint memory of this (or something packaging project related) that just silently does nothing when building in Debug configurations.

**Comment by mjfusa** [comment]
Thanks for the suggestion @riverar - unfortunately I get the same result (no appinstaller or index.html files) in Release.

**Comment by MartinRothschink** [comment]
After changing my existing two project with separate packaging project into a single project I made the same observation. The index.html and app installers are missing.

**Comment by andrewleader** [comment]
This is a known gap, single-project MSIX unfortunately doesn't support creating the appinstaller file. You can use the classic Windows Packaging Project (two projects) for now.

How important is appinstaller support in single-project MSIX for you? **You can add your vote here: https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/55-support-generating-appinstaller-file-in-single-project-msix**

**Comment by MartinRothschink** [comment]
Thanks, voted.

**Comment by germanfortiz** [comment]
I can't see this problem solved in 1.0.2. What's more, only the last platform selected is generated (x86, x64 or arm64), and the msixbundle is not created either.

![image](https://user-images.githubusercontent.com/20989942/163607314-518ed048-48c9-4414-92e8-57e62c8e93f9.png)

![image](https://user-images.githubusercontent.com/20989942/163607401-a9aa17ae-9c1e-4263-bb2f-09382cffac28.png)

**Comment by evelynwu-msft** [comment]
Single-project MSIX Packaging won't support creation of .msixbundle packages until WinAppSdk 1.2 at the earliest. Until that support is added, the VS wizard is effectively just setting some MSBuild properties that get ignored if you tell it to produce a bundle.

Regarding the missing .appinstaller even after upgrading to 1.0.2, can you verify that you checked this box at the beginning of the wizard?
![image](https://user-images.githubusercontent.com/50890554/163622850-da5f6e34-e797-461b-8428-9b0a3e797ece.png)

**Comment by germanfortiz** [comment]
Hi!
Thanks for the quick response!

Starting the Create App Packages wizard:

![image](https://user-images.githubusercontent.com/20989942/163623652-34f7964f-a8f9-4324-90fd-ac04a0a17fbf.png)

The image at the end of the process:

![image](https://user-images.githubusercontent.com/20989942/163623814-78f44f86-1272-4020-910a-a15c7451f570.png)


And the final folders:

![image](https://user-images.githubusercontent.com/20989942/163623871-627b1c69-a417-451d-b03f-00c9d342e76a.png)

As a note: when creating the package, I see VS genererate x86 target, but when VS begins compiling x64 target, it inmediatly deletes the _x86 target.

Thanks!

**Comment by evelynwu-msft** [comment]
That is bizarre... I'm using what should be identical settings, but I'm seeing the expected behavior (both architectures present in `$(AppPackageDir)`, and a `.appinstaller` for each):
![image](https://user-images.githubusercontent.com/50890554/163625387-4b69970c-0958-435c-9ca7-1e2841428d11.png)

**Comment by germanfortiz** [comment]
I think I found the problem in my settings: in the **Create App Packaged** wizard, the option **Generate App Bundle** must be set in **Never**. This way the wizard create the .appinstallers and the index.html.

![image](https://user-images.githubusercontent.com/20989942/163651365-2e14a5d4-222e-43a0-9348-d123e88e3c64.png)

![image](https://user-images.githubusercontent.com/20989942/163651393-84d67ccd-c1e4-4b08-bd0c-a79465b033ca.png)

Thanks for the support!

**Comment by headerjson** [comment]
Is there a supported MSBuild option to generate this index.html for single-project MSIX? 
 
I'm setting up an Azure DevOps CI/CD pipeline and am able to generate the .msix and .appinstaller for the single-project MSIX using the following MSBuild options: 
```
/p:AppxPackageDir=D:\AppxPackages\ 
/p:GenerateAppxPackageOnBuild=true 
/p:AppxBundle=Never 
/p:UapAppxPackageBuildMode=SideLoadOnly
/p:GenerateAppInstallerFile=true
/p:AppInstallerUri=https:\\foo.net
/p:HoursBetweenUpdateChecks=24
```
The index.html file is still missing.

**Comment by riverar** [comment]
@headerjson Double-check that's being built in a Release configuration. If I remember correctly, nothing happens (silently) if in Debug. (Or this behavior changed and you can ignore me.)

**Comment by fabiocannas** [comment]
> /p:AppxPackageDir=D:\AppxPackages\ 
> /p:GenerateAppxPackageOnBuild=true 
> /p:AppxBundle=Never 
> /p:UapAppxPackageBuildMode=SideLoadOnly
> /p:GenerateAppInstallerFile=true
> /p:AppInstallerUri=https:\\foo.net
> /p:HoursBetweenUpdateChecks=24

you saved my life :) thank you
