### ISSUE TITLE
WinRT API for DWriteCore that exposes the full surface

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/WindowsAppSDK#1822]
Provide a WinRT API for DWriteCore that exposes the full surface. While libraries such as Win2D can provide a WinRT wrapper on top, they don't provide the full API surface as it is.

**Comment by pjmlp** [comment]
I have the feeling they would expect us to write C++ and use nano-COM instead, given the feedback that DirectX team doesn't care about us.

https://github.com/microsoft/WindowsAppSDK/issues/14

**Comment by duncanmacmichael** [comment]
Hi @Jaiganeshkumaran, thanks for opening this issue! We're curious to hear what your interest is for a full WinRT exposure of DWriteCore, as this might be something we can investigate for a future feature request. What sort of use cases and scenarios do you have in mind?

Thanks!

**Comment by Jaiganeshkumaran** [comment]
> Hi @Jaiganeshkumaran, thanks for opening this issue! We're curious to hear what your interest is for a full WinRT exposure of DWriteCore, as this might be something we can investigate for a future feature request. What sort of use cases and scenarios do you have in mind?
> 
> Thanks!

To access DWriteCore easily from languages other than C++ such as C# in a natural familiar way (unlike using interop assemblies such as the Win32 Metadata project).
