### ISSUE TITLE
WinAppSdk app templates should generate code following coding best practices

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/WindowsAppSDK#1823]
### Describe the bug

@angelazhangmsft updated the templates for the WinAppSDK samples in [this PR](https://github.com/microsoft/WindowsAppSDK-Samples/pull/107). These types of changes should be made to the templates that generate the WinAppSdk Apps.

### Steps to reproduce the bug

1. in VS create a new WinAppSdk C++ app using the templates
2. inspect the code

### Expected behavior

expected: the code follows best practices, for example using
```cpp
namespace winrt
{
    using namespace Microsoft::UI::Xaml;
}
```
instead of 
```cpp
using namespace winrt;
using namespace Microsoft::UI::Xaml;
```

**Comment by Jaiganeshkumaran** [comment]
I think using the winrt namespace is fine as long as the project only uses C++/WinRT and doesn't use C++/CX and/or WRL along with it.

**Comment by ChrisGuzak** [comment]
This is the recommended best practice that we want templates to follow.

**Comment by bpulliam** [comment]
@ChrisGuzak are there any remaining issues in the templates located in https://github.com/microsoft/WindowsAppSDK/tree/main/dev/VSIX?

**Comment by LegendaryBlair** [comment]
According to the discussion in this [draft PR](https://github.com/microsoft/WindowsAppSDK/pull/4851), close this issue as won't fix.
