### ISSUE TITLE
Build issue .NET 6 WinUI 3 APPX1101

### ISSUE THREAD

**Issue by paulober** [microsoft/WindowsAppSDK#1830]
### Describe the bug

Does anybody have an idea how i can solve this build issue?

APPX1101 Payload contains two or more files with the same destination path 'MyProjekt.deps.json'. Source files: 
C:\MyProjekt\MyProjekt\obj\x64\Debug\net6.0-windows10.0.22000.0\win10-x64\MyProjekt.deps.json
C:\MyProjekt\MyProjekt\bin\x64\Debug\net6.0-windows10.0.22000.0\win10-x64\MyProjekt.deps.json
C:\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.target

### Steps to reproduce the bug

...

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

### Additional context

.NET 6

**Comment by pavll** [comment]
Getting this error in a WinUI 3 project where the package is in the main project and not in a separate project. And when I try to package my app with an external package, it crashes and says every time I want to access `ApplicationView.GetForCurrentView()` or `CoreApplication.GetForCurrentView()`: `System.Runtime.InteropServices.COMException: "Element not found. (0x80070490)"`

**Comment by roxk** [comment]
I'm not sure about the package issue without more info, but `GetForCurrentView` and friends are [not supported in WinUI 3](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api). Please refer to that list and use the appropriate APIs instead.

**Comment by pavll** [comment]
Ok, and what's then the alternative for `CoreApplication.GetCurrentView().TitleBar.ExtendViewIntoTitleBar = true;
            ApplicationView.GetForCurrentView().TitleBar.ButtonBackgroundColor = Colors.Transparent;`?

**Comment by ParkhutRoman** [comment]
@pavll https://github.com/microsoft/WindowsAppSDK/issues/1626

**Comment by andrewleader** [comment]
Hi @pavll, any chance you can share a repro project that demonstrates this build issue you're running into? I think we'll need more info than what you provided to help.

**Comment by pavll** [comment]
@andrewleader [Here is a link to a copy of the original repo with the same build error in VS 2022 and .NET 6 and WinUI 3 Release 1.0](https://github.com/pavll/IssueShare)

**Comment by Scottj1s** [comment]
This is fixed in Windows App SDK 1.2 Preview 2. For a workaround, see: https://github.com/microsoft/WindowsAppSDK/issues/1856#issuecomment-1262705228
