### ISSUE TITLE
Enabling ImplicitUsings breaks compilation

### ISSUE THREAD

**Issue by drjofu** [microsoft/WindowsAppSDK#1831]
### Describe the bug

Setting
<ImplicitUsings>Enable</ImplicitUsings>
in project file causes an error:
'Version' is an ambiguous reference between 'Microsoft.WindowsAppSDK.Runtime.Version' and 'System.Version'	

### Steps to reproduce the bug

create WinUI3 unpackaged project, enable implicit usings for project

### Expected behavior

no error

**Comment by DrusTheAxe** [comment]
Known issue and already addressed in main via [feat: Added global:: to MddBootstrapAutoInitializer. #1685](https://github.com/microsoft/WindowsAppSDK/pull/1685). Queued up for 1.0 servicing

You can workaround this for now by updating your local file with the content from the PR

**Comment by BenJKuhn** [comment]
For tracking purposes, the original issue is #1686. The PR that addresses it is #1685. Closing this as this is a duplicate and marking the original issue as a servicing candidate.
