### ISSUE TITLE
App packaged with wap project builds for the wrong architecture

### ISSUE THREAD

**Issue by lhak** [microsoft/WindowsAppSDK#1848]
### Describe the bug

A C# app (project type "Packaged with WAP (WinUI3 in Desktop)")) which is build on a x64 machine does not build arm64 binaries even if the arm64 architecture is selected in the dropdown menu.

### Steps to reproduce the bug

1. Create a new blank c# app packaged with a WAP project
2. Select arm64 as the target architecture
3. Build the project itself or the WAP package
4. The generated binaries are x64 instead of arm64

Adding the PublishProfile property to the app project seems to fix this issue

### Expected behavior

App should be built according to the selected architecture

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 (22000)

### IDE

Visual Studio 2022

**Comment by haonanttt** [comment]
Close this issue as not repro.
