### ISSUE TITLE
Installing stable Windows App SDK extension for Visual Studio 2022 fails with multiple Visual Studio versions installed

### ISSUE THREAD

**Issue by christiannagel** [microsoft/WindowsAppSDK#1849]
### Describe the bug

The installation of the stable version of the Windows App SDK extension for Visual Studio 2022 fails with this error:
Modifications failed

Modifications of multiple extensions can only be applied to one product at a time

From the installation log file:
11/27/2021 12:40:21 PM - Searching for applicable products...
11/27/2021 12:40:21 PM - Found installed product - Global Location
11/27/2021 12:40:21 PM - Found installed product - Visual Studio Enterprise 2022
11/27/2021 12:40:21 PM - An extension with a matching Identifier is already installed to this product.
11/27/2021 12:40:21 PM - Found installed product - Visual Studio Enterprise 2019
11/27/2021 12:40:21 PM - Found installed product - Visual Studio Enterprise 2022 Preview
11/27/2021 12:40:21 PM - System.InvalidOperationException: Modifications of multiple extensions can only be applied to one product at a time. ---> System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at VSIXInstaller.MultipleChangePage..ctor(ExtensionData data)
   at VSIXInstaller.LoadingPage.<>c__DisplayClass15_1.<OnLoaded>b__2()

I have Visual Studio 2019, 2022, and 2022 preview installed, as well as .NET MAUI.

### Steps to reproduce the bug

1. Install Visual Studio 2019, Visual Studio 2022, and Visual Studio 2022 preview
2.  Downloaded the stable release from https://aka.ms/windowsappsdk/stable-vsix-2022-cs (as described in https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022)
3. Start the VSIX installation

### Expected behavior

Expect to install the SDK successfully 

### NuGet package version

1.0.0

### Windows version

Insider Build (xxxxx), Windows 11 (22000)

### IDE

Visual Studio 2022

**Comment by DefaultRyan** [comment]
I believe the root issue here is that our VSIX includes the [Single-Project MSIX Packaging Tools](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftSingleProjectMSIXPackagingToolsDev17) extension via a [Visual Studio Extension Pack](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthough-create-extension-pack?view=vs-2022). This is why the error message says the VSIX installer is trying to modify multiple extensions.

You should be able to work around this by manually invoking the VSIX installer (`vsixinstaller.exe`) from a Visual Studio Developer Command Prompt. This way, you can tell it to ignore the extension pack with `/noextensionpack` and install the MSIX Packaging Tools manually.

I'm looking into ways of improving this experience, but let me know if this workaround unblocks you in the meantime.

PS: vsixinstaller.exe also has some options that purport to let you target a specific instance of VS, but I haven't tested these, so I can't vouch for their effectiveness. Feel free to experiment with `/appIdInstallPath`, `/appIdName`, `/skuName`, and `/skuVersion`. A full list of vsixinstaller options can be displayed by simply running vsixinstaller from the command line with no arguments.

**Comment by christiannagel** [comment]
this unblocks, thanks @DefaultRyan

**Comment by LegendaryBlair** [comment]
Solution provided and issue got resolved.
