### ISSUE TITLE
Unable to register for UWP Store push notifications anymore

### ISSUE THREAD

**Issue by jimm98y** [microsoft/WindowsAppSDK#1854]
### Describe the bug

Currently, it seems it is no longer possible to get the old UWP Store push notifications working. The original flow as far as I remember was: 
1) Register app in the Store, note the SID
2) Register the app in Live Services and get the secret
3) Execute the registration flow, then use the SID and secret to send the push notification from the backend (or Notification Hub)

Currently, it is no longer possible to retrieve the "secret" from Live SDK because it has been deprecated in favor of Azure App Registration. Azure Push Notification hub is unusable for Windows platform as it requires SID and the secret as well. Azure App Registration does not seem to be available for UWP Store apps yet as all I have found was a Push Notification Preview for Windows App SDK. 

What is the recommended way to get push notifications working for new UWP Store apps these days?

### Steps to reproduce the bug

1) This seems to be deprecated: https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh913756(v=win.10)?redirectedfrom=MSDN (last update in 2015). 

2) This https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-windows-store-dotnet-get-started-wns-push-notification refers to the "Live Services Site" in step 3, but that is no longer available.

3) Live SDK registration page shows the following message:
"Live SDK applications 
 Starting February 2021, you can no longer create new Live SDK applications here. The Azure portal now supports applications for personal Microsoft accounts. We recommend registering new applications there. Go to the Azure portal"

4) Azure App Registration does not seem to fully replace SID/secret and new Push Notifications for Windows App SDK seem to be still in Preview. There is no mention about UWP in the preview site either.

### Expected behavior

I'd expect there should be some way to make UWP Store push notifications working at this moment without having to sign up for unfinished preview features. 

### Packaging type

Packaged (MSIX)

### Windows version

May 2021 Update (19043)

### IDE

Visual Studio 2019

**Comment by riverar** [comment]
Hi @jimm98y.

Sorry to redirect you, but this is not the right place for UWP discussions.

Here's some alternate resources:
* [Microsoft Q&A windows-uwp tag](https://docs.microsoft.com/en-us/answers/topics/46321/windows-uwp.html): Has a dedicated support staff that helps answer questions there.
* [Stackoverflow](https://stackoverflow.com/questions/tagged/uwp)
* [UWP Community Discord](https://discord.com/invite/uwp) Very tight nit and supportive community.

**Comment by btueffers** [comment]
Thanks @riverar those are great suggestions!
