### ISSUE TITLE
WinUI needs revision!

### ISSUE THREAD

**Issue by DmitryBorodiy** [microsoft/WindowsAppSDK#1863]
1. I have a bad development experience with WinUI 3.

Microsoft needs to revisit WinUI applications.
WinUI 3 apps do not work across the entire Windows ecosystem. Does Panos Panay even know about your WinUI traffic? This something that works on the old WPF platform looks out of date. My favorite Windows and Surface device is the Surface Hub 2S, and you haven't bothered to add support for your ecosystem. Hike Microsoft is not the same company that it used to be. There is no innovation and support for new technologies like UWP. No matter how ridiculous it may sound, you are back to where you started in 2015 and this is a complete failure! You wiped out the Windows mobile marketplace and now take on what's left.

2. Microsoft should also overhaul Windows 11

Windows 11 is an even bigger problem for Microsoft, it is completely incompatible and has a poor experience with tablets, HoloLens and Surface Hub 2S. At the moment I see no point in number 11 on my devices.

Microsoft CEO, review your Windows development policy.

The only thing I liked was the new Microsoft Store, it is really cool compared to the old one, and it is also good that it still remains universal.

**Comment by andrewleader** [comment]
Hi @DmitryBorodiy, thanks for the feedback. Feature requests (like Surface Hub support) should be submitted through our productboard portal: https://aka.ms/winappsdkportal

I've already linked up your feedback for Surface Hub support though, so you don't need to do anything, your request is captured and tracked! But in the future, please submit feature requests through our portal!

General Windows 11 feedback should be submitted through the Feedback Hub app. Our team is the developer platform and doesn't take consumer feedback.
