### ISSUE TITLE
ResourceLoader doesn't load resources.resjson, resources.resw, per docs

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#1872]
## Summary
The documentation for [ResourceLoader .ctor](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourceloader.-ctor?view=windows-app-sdk-1.0&WT.mc_id=WD-MVP-5002756#Microsoft_Windows_ApplicationModel_Resources_ResourceLoader__ctor) states, under Remarks:
> The empty constructor typically allows access relative to a resource file's resources (resources.resjson or resources.resw).

This is not accurate.

## Actual
Constructing a new `ResourceLoader` fails due to a missing `resources.pri`. (`ResourceLoader.GetDefaultResourceFilePath()` does admittedly return the right filename.)

I can't file bugs on Docs against this docset due to broken edit links/publishing errors.

## Expected
Documentation to explicitly state the default resource filename is `resources.pri` and a fallback is `[executable-module-name].pri`.

**Comment by huichen123** [comment]
This is the same remark copied from system MRT (https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.resourceloader.-ctor?view=winrt-22000). I think it means the source of resources, not the PRI file. i.e. If you add resources from a resources.resw or resources.resjson, you can access them with default ResourceLoader.

**Comment by riverar** [comment]
Agree, but that assumes this API is being called from an app built with Visual Studio and/or some extra processing of those files occurs.

I think the API docs should instead simply refer to what it requires and leave the intermediate information for other docs.

**Comment by axelandrejs** [comment]
Incorrect comment removed from docs:https://github.com/MicrosoftDocs/winapps-winrt-api/pull/2
