### ISSUE TITLE
CS5001:	Program does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by btueffers** [microsoft/WindowsAppSDK#1877]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/1873

<div type='discussions-op-text'>

<sup>Originally posted by **iomismo** December  4, 2021</sup>
Hi everyone!
Weird error: any Windows App SDK project that is created from VS 2022 / 2019 Templates throws CS5001 error. When creating a new project it first shows app.manifest, App.xaml and MainWindow.xaml files and after a second they are automatically removed from the project tree. Adding them mannually does not solve the problem.

Thought that it was only on my old Project Reunion projects after upgrading them to Windows App SDK 1.0 and .NET 6, but it happens even creating a new project / solution, no matter VS 2019 or 2022. 

Code inside App.g.cs or any other page g.cs file is not being generated.
In App.i.g.cs file, the autogenerated Program class that contains Main method is missing. 

Cleaned, rebuild, deleted obj and bin folders, not working.</div>

**Comment by aepot** [comment]
Seems to be a problem with environment not Windows App SDK itself, just guessing.

Try reinstall .NET SDK / both Visual Studios if that works for you.

**Comment by iomismo** [comment]
Still with no fix. Tried reinstall Visual Studio, uninstall and install again. Is there any log file where I can find more info about what is going on?
