### ISSUE TITLE
Proposal: ability to disable rounded window corners for a UWP app in Windows 11

### ISSUE THREAD

**Issue by benstevens48** [microsoft/WindowsAppSDK#1879]
# Proposal: ability to disable rounded window corners for a UWP app in Windows 11

## Summary
(If this is already possible, please let me know!) There should be an API to disable rounded window corners for a UWP app (using CoreWindow) in Windows 11.

## Rationale
I have a UWP app which is a photo viewer, and I do not want rounded window corners because then the corner of the photo is clipped (depending on window aspect ratio and zoom level etc) and I want it to provide a pixel perfect view of the image (since the app may be used for serious purposes). Ideally I would want to be able to provide it as an option in my app that users could change.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Add an API to disable rounded window corners for UWP (CoreWindow) apps in Windows 11. | Must |
| The change should ideally take effect without restarting the app, but that is not essential. | Should |

**Comment by MikeHillberg** [comment]
Moving this CoreWindow feature to the WindowsAppSDK repo

**Comment by Jaiganeshkumaran** [comment]
> I do not want rounded window corners because then the corner of the photo is clipped

The best solution is to have a margin for the picture when the app isn't maximized or full screen.

**Comment by BenJKuhn** [comment]
In full trust (including packaged full trust) applications, you can access to the HWND and call DwmSetWindowAttribute with DWMWA_WINDOW_CORNER_PREFERENCE option and a value of DWMWCP_DONOTROUND. 

There's no way to do the equivalent in UWP. Per discussion [here](https://github.com/microsoft/WindowsAppSDK/discussions/1615), there's no plan to add this capability for UWP applications.
