### ISSUE TITLE
UWP migration to WinUI3 for Windows.Storage.BulkAccess

### ISSUE THREAD

**Issue by Ponant** [microsoft/WindowsAppSDK#1884]
We are using in a production app virtualization all the way. The reason being the app allows a user to search through tens of thousands of photography images. Given the large amount of files to be displayed in the UI, the `Windows.Storage.BulkAccess` turned out to be central to make the app consume little ram while being more performant than fetching all files. In particular the `FileInformationFactory.GetVirtualizedItemsVector()` methods. As we have seen an announcement that invites us to migrate to WinUI3, I would appreciate knowing if the FileInformationFactory is supported, or if there is a better or newer alternative in WinUI? Again, what made the `GetVirtualizedItemsVector()` great is its capability to query the Windows index to retrieve thumbnails with meta information about photography images.
Thank you

**Comment by Jaiganeshkumaran** [comment]
Windows.Storage APIs aren't UWP specific. They should work in any kind of app.

**Comment by btueffers** [comment]
Hi @Ponant! @Jaiganeshkumaran's response above is correct so we're going to close this issue. Let us know if you do run into any issues!
