### ISSUE TITLE
Migrating from Microsoft.WindowsAppSDK.1.0.0-experimental1 to Microsoft.WindowsAppSDK.1.0.0 crashes (UWP) app

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/WindowsAppSDK#1894]
### Describe the bug

Attaching a zip file with both good and bad vcxproj in a solution
[test.zip](https://github.com/microsoft/WindowsAppSDK/files/7688803/test.zip)

Good -> uses Microsoft.WindowsAppSDK.1.0.0-experimental1 Runs fine (Empty WebView2)
Bad -> Uses Microsoft.WindowsAppSDK.1.0.0 . 

Crashes with the following message

WinUI: Error creating an UWP Window. Creating an UWP window is not allowed.'.

### Steps to reproduce the bug

Open the solution run good or bad

### Expected behavior

Both good and bad run successfully

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

The difference between Good and bad is simply a different SDK version and app runtimes

Bad:
Microsoft.WindowsAppRuntime.1.0_0.319.455.0_x64__8wekyb3d8bbwe

Good:

Microsoft.WindowsAppSDK.1.0-experimental1_0.218.840.0_x64__8wekyb3d8bbwe

**Comment by ankurverma85** [comment]
[test.zip](https://github.com/microsoft/WindowsAppSDK/files/7688802/test.zip)

**Comment by ankurverma85** [comment]
FWIW preview1 is "bad" as well

Only the experimental1 seems to work and it works flawless

**Comment by Jaiganeshkumaran** [comment]
UWP isn't supported as a target for 1.0.0

**Comment by ankurverma85** [comment]
Given it works on experimental, I'm assuming 

1. It has artificially been turned off (perhaps because it's not release ready, though functional)
2. There's a roadmap to get that enabled 

Are these correct ?

Is there a way I can use the non-experimental package and turn it on locally ?

The experimental sdk seems to be a few months behind the released one and doesnt seem to be unified

**Comment by ankurverma85** [comment]
Also Whats even more mind boggling is that it actually works when i run it from visual studio even though I clearly hit a "Fail-fast-exception". 
The window just blinks and shows my webview. 
its when I run it without debugger that the whole thing blows up. 
So I'm assuming there's a way to not-artificially blow up

**Comment by riverar** [comment]
@ankurverma85 It's not _artificially_ failing. And there is no way to make this scenario work with preview/1.0 bits. It's just not supported.

**Comment by ankurverma85** [comment]
I want to believe you but I do have it working in-fact

1. WindowsAppSDK 1.0.0 it works if I continue past in the debugger
2. With WindowsAppSDK 1.0.0-experimental1 it simply works. 

Which is why i attached the zip file because I'm curious about the delta.

I understand it might not be officially supported now and I'm curious when it might be become officially available. 

The link you posted does not clearly state that

**Comment by riverar** [comment]
@ankurverma85 UWP support is not coming; it's not on the roadmap. The overall migration strategy can be found at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/overall-migration-strategy.

I understand that's frustrating for some to hear. If you hit any particular gotchas (e.g. missing controls, APIs), do create an issue!

**Comment by ankurverma85** [comment]
Interesting ... Thanks for the information

What I really actually only need is WebView2 in an UWP ? and Ideally i'd like to not create separate apps for other micrososft devices (non-desktop)

So, is this SDK along with WinUI3 only on desktop?
What about Xbox, Hololens or any other devices?

My understanding of both WinUI effort and ProjectReunion was that WinUI3 supercedes all that and so WebView2 is going to be available (along with all the other controls on UWP too, so we create one-app for all microsoft devices.

Did that vision get lost along the way or did I read too much into what it actually was ?

**Comment by ankurverma85** [comment]
Perhaps the right question (so we dont get lost in the jargons like winui, winrt, desktop, win10, uwp, msix, appx etc ) is : 

As a (c++) store developer I have these options available for submitting a package:

![image](https://user-images.githubusercontent.com/31362771/145518057-fe747064-b20d-4c23-8998-2117cea7e5dc.png)

And so far the only way to create a single binary that runs across all (in C++) is to go the winrt Windows.Ui.Xaml route with UWP

And my understanding was that WinUI3 replaces Windows.UI.xaml with microsoft.ui.xaml and allow for WebView2 and other awesome controls and then eventually let you create a single binary that runs across all platforms ?

Is that not the goal ?
And if it is when is that planned ?

**Comment by riverar** [comment]
@ankurverma85 Your questions have really opened my eyes to how poorly the documentation describes what Windows App SDK is. Sorry about the confusion.



The quick and plain English version is: Windows App SDK is a collection of APIs, frameworks, and tools to help you build **desktop apps** targeting Windows 11 and earlier (back to Windows 10 version 1809, in most cases). It doesn't currently target other devices such as HoloLens, Xbox, Mobile, etc.

To touch on your comments / answer your questions:

> And so far the only way to create a single binary that runs across all (in C++) is to go the winrt Windows.Ui.Xaml route with UWP

Yep.

> And my understanding was that WinUI3 replaces Windows.UI.xaml with microsoft.ui.xaml and allow for WebView2 and other awesome controls and then eventually let you create a single binary that runs across all platforms? Is that not the goal? And if it is when is that planned?

WebView2 is actually working on/has support for [WinUI 2 (UWP)](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2) and [WinUI 3 (WinAppSdk)](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui)!

WinUI 2 is still actively supported for UWP/Xamarin.Forms and is still a viable solution if you're trying to target desktop and non-desktop (e.g. Hub, HoloLens, Xbox). WinUI 3 is the _next generation_ of the WinUI framework that currently only targets desktop apps. (Whether it's truly a _replacement_ for WinUI 2 has yet to be seen.)

I'm not aware of any plans for WinAppSDK or WinUI 3 to support other platforms. And I don't believe any such work is in any plans for the next few years to come. Looping in @andrewleader for more official words.

Hope that helps clarify a little bit.

**Comment by ankurverma85** [comment]
Yes. It does. Thanks a lot for the answers 

I'm starting to realize I assumed winui3 is the next version and an evolution of winui2
And got probably excited by the fact that the experimental sdk actually worked as per my flawed understanding.

Thanks again for clarifying

**Comment by andrewleader** [comment]
Thanks Rafael for helping clarify!

@ankurverma85 since you said what you really only need is WebView2, I would suggest looking into the [WebView2 preview for WinUI 2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2) as Rafael linked to! And as Rafael mentioned, we currently don't have any plans to support other platforms than Desktop with WinUI 3.

Also, to set some expectations for Experimental features, Experimental features may be removed at any point in time, if something's experimental, that's not a guarantee it's going to ship. Once a feature is promoted to a Preview release, that's when it's very certain the feature will ship and the API surface is probably mostly stable.

Closing this issue. Sorry for the confusion, let us know if you have any further questions!
