### ISSUE TITLE
High memory allocation without freeing it

### ISSUE THREAD

**Issue by xmine64** [microsoft/WindowsAppSDK#1895]
### Describe the bug

I noticed that my WinUI 3 apps uses a lot of memory, so I tried to profile it to find the problem and then I noticed that there's a high memory usage in unmanaged memory, not in .NET heap. I have no idea, I guess it's just a memory leak in runtime. There's a screenshot from the memory profiler.

### Steps to reproduce the bug

1. Create an unpackaged multi-page app with WinUI 3
2. Put a ListView in a page and bind it to an array
3. Navigate to that page, it allocates a lot of memory
4. Navigate back from that page, even with `PageCacheMode="Disabled"` and clearing BackStack and ForwardStack, it won't free that used memory

### Screenshots

![image](https://user-images.githubusercontent.com/21140798/145547654-e0e5b9ae-0348-4740-bbfb-ae1d26399033.png)

![image](https://user-images.githubusercontent.com/21140798/145547706-0b5f967a-4d1d-474b-a711-2c21770888d7.png)

![image](https://user-images.githubusercontent.com/21140798/145547799-1c466eb9-5f64-4dcf-a3cf-b4db6e55b8b9.png)

![image](https://user-images.githubusercontent.com/21140798/145547870-40773a9b-3346-428b-a8b9-ff595a052bf6.png)

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2019

**Comment by Jaiganeshkumaran** [comment]
@minusium Are you using compiled bindings (x:Bind)?

**Comment by minusium** [comment]
> Are you using compiled bindings (x:Bind)?

Yes I do.

**Comment by BenJKuhn** [comment]
We've been working through some memory leak issues related to C# WinRT, event handling, and cycles. We have a servicing update coming to the 0.8 release later this month and 1.0 early next year that will incorporate quite a bit of C# /WinRT performance work. I'd love to know if that addresses the leak. If it doesn't resolve the issue I may need to get more information from you to create a minimal repro that we can analyze.

- Ben

**Comment by minusium** [comment]
Thanks @BenJKuhn 
But is there any workaround for now?

**Comment by minusium** [comment]
I tried to reproduce problem in a simple project but it was fine there, so I removed all controls from my DetailsPage on my main project and I only kept ListView, now when I open DetailsPage memory usage doesn't go higher even one MB, problem is with something else.

**Comment by Jaiganeshkumaran** [comment]
@minusium Compiled bindings (x:Bind) may also cause memory leaks especially when the bounded object outlives the page. Could you try calling Bindings.StopTracking under OnNavigatedFrom?

**Comment by minusium** [comment]
@Jaiganeshkumaran I added Bindings.StopTracking and this is the result:

![image](https://user-images.githubusercontent.com/21140798/145676910-a4d6bfc2-a103-4a3b-862d-06a6bfd5b3d4.png)

First red line is when DetailsPage is loaded, and second red line is when I navigate back.

This is memory usage when I remove all elements except the ListView that is binded to an IList:
![image](https://user-images.githubusercontent.com/21140798/145676948-8ea5ec02-2665-4667-b4e1-8e5085ee8923.png)

This is memory usage when I remove all elements except Image with a container on top of it with `SystemControlAcrylicElementBrush` as background:
![image](https://user-images.githubusercontent.com/21140798/145676980-4db49425-af2a-413d-b36d-12fbe3ad7029.png)

Image source is online. I guess leak is in the Image control.

**Comment by minusium** [comment]
Thanks for your help, but I could fix my problem by reimplementing my DetailsPage xaml code.
I don't know how to reproduce that, memory usage used to go high randomly, even once went to 800MB from 70MB in a navigation to DetailsPage. I simplified my layout in reimplementing it and I used less Grids and I dropped a ScrollViewer.
