### ISSUE TITLE
WebView2 unable to connect to any websites

### ISSUE THREAD

**Issue by ChasTechProjects** [microsoft/WindowsAppSDK#1910]
### Describe the bug

I am attempting to code a small web browser in Visual Studio 2019 using the Windows App SDK, WinUI3, and C#. In my MainPage.xaml, I have WebView2 defined as myWebView, with the source set to go to http://google.com. However, when I run the app, it stays on a blank page for a while and then loads the Microsoft Edge "ERR_NAME_NOT_RESOLVED" error page. I have tried this with several different websites. On the other hand, if I try to access Google through its numerical IPv4 address I get ERR_NETWORK_ACCESS_DENIED (your internet access is blocked). Microsoft Edge runs fine. I've tried disabling Windows Firewall and that changes nothing.

### Steps to reproduce the bug

1. Create a WinUI3 blank C# application project in Visual Studio.
2. In the MainPage.xaml, paste in the following code:
`<WebView2 x:Name="myWebView" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" Source="http://google.com"/>`
3. Run the code and wait around 10-20 seconds until the error page loads.
4. Replace the Source with an IP address of a website (with http:// before) and you will get ERR_NETWORK_ACCESS_DENIED.

### Expected behavior

WebView2 will load the page specified.

### Packaging type

Unpackaged

### Windows version

Insider Build (xxxxx)

**Comment by andrewleader** [comment]
Hi @ChasTechProjects, since this is a WebView2 bug, please report it on the WebView2Feedback repo: https://github.com/MicrosoftEdge/WebView2Feedback/issues
