### ISSUE TITLE
Unable to change the title bar icon for a winui 3.0 app

### ISSUE THREAD

**Issue by MarkvanWinkelen** [microsoft/WindowsAppSDK#1914]
I am unable to change the title bar icon for my packaged winui 3.0 app. It is possible to change the title bar title, to in my case 'Koraalbewerkingen'. Can you make it possible to change the icon as easy as the title is changed in C#?
![image](https://user-images.githubusercontent.com/95351448/146336023-a5f8be11-8237-4881-b31b-b8d2c70bfbf7.png)

**Comment by andrewleader** [comment]
Hi @MarkvanWinkelen, you can change the title bar icon using the [AppWindow APIs](https://docs.microsoft.com/windows/apps/windows-app-sdk/windowing/windowing-overview). Here's an example...

```csharp
// Get the AppWindow from the XAML Window ("this" is your XAML window)
IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
WindowId myWndId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
var appWindow = AppWindow.GetFromWindowId(myWndId);

// And then set the icon
appWindow.SetIcon("yourIconPath");
```

In the future we're going to work on better integrating the AppWindow APIs with the XAML Window so you can more easily use all the great functionality that's within AppWindow without writing those 3 lines of verbose code! Here's the feature request for that item: [Integrate AppWindow with WinUI 3](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/48-integrate-appwindow-with-winui-3).

**Comment by chausner** [comment]
It's worth mentioning that `SetIcon` appears to accept only files in ICO format. Also, it does not seem possible to use `ms-appx` or similar URIs. The path must be a full path to the file on disk.

**Comment by mluepkes** [comment]
Same problem here, I also get an InvalidCastException

![image](https://user-images.githubusercontent.com/4066460/175375840-5b18b382-f557-4472-828b-fbc5b50cbc1e.png)

**Comment by riverar** [comment]
GetWindowHandle expects a window, not a page.

**Comment by mluepkes** [comment]
Ah, well, that makes sense and when run with the window from App.OnLaunched() it works. Thanks for the help!

**Comment by ApoorvaPetkar** [comment]
@mluepkes , can you please help me know how you set the app title first?

**Comment by ApoorvaPetkar** [comment]
And also I'm getting the same cast exception. What changes did you make?

**Comment by lopehole** [comment]
> And also I'm getting the same cast exception. Where did you make the above changes? Can you please help me by posting the screenshot or code? And also how you are setting the App title? @mluepkes @greatoceansoftware @riverar

Regarding App Title - it can be set under MainWindow.xaml.cs, under public MainWindow add a line for:
`this.Title = "app_name"`
