### ISSUE TITLE
WebView 2 ContentLoading is missing

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#1939]
### Describe the bug

by installing     
`<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1054.31" />
` 
nuget package i can use
webView.ContentLoading += WebView_ContentLoading;
in wpf app, but in winui 3 and default webview2, This event does not exist

### Steps to reproduce the bug

1.Create webview2
`        <WebView2 Name="webView"/>`
2.Create Content Loading Event

### Expected behavior

The event must exist

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by andrewleader** [comment]
Hi @ghost1372, the WebView2 feedback has a dedicated repo for WebView2 feedback, you can post this issue [on their repo here](https://github.com/MicrosoftEdge/WebView2Feedback/issues) to make sure it's seen by their team. I'll close this issue. Thanks!
