### ISSUE TITLE
Sample cs-winui miss languages after it is published as a package

### ISSUE THREAD

**Issue by ilovepumpkin** [microsoft/WindowsAppSDK#1980]
### Describe the bug
I am following the cs-winui sample project ( https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/ResourceManagement/cs-winui) to add globalization support to my project, but I found it always displays the default language set in package.manifest after building a package and running it. And I tried cs-winui sample project  and found the same problem, so I come to open this issue to ask for help.

When I run the sample cs-winui ( https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/ResourceManagement/cs-winui) in Visual Studio (mine is VS 2019) - after clicking "Override Language" button, I can see the German text is displayed as expected.

![image](https://user-images.githubusercontent.com/11310645/149122314-4ab67a34-9dac-4a1d-93c0-5264751e3802.png)

However, after I publish it as a sideloading package and install it - right click on package project, select Publish > Create App Packages ... . 
![image](https://user-images.githubusercontent.com/11310645/149122810-d9cd77b3-6fce-4c1c-9c7d-a39128f54e45.png)

When I click "Override Language" button, it shows me the text in English.
![image](https://user-images.githubusercontent.com/11310645/149124885-7e896419-01ef-4d9b-86be-ef58c24c99c7.png)

It seems that resources in German is gone after packaging.  Is this a bug or any additional configuration is needed ? And if this is a known issue, is there any workaround I could apply? 

### Steps to reproduce the bug

1. Pull https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/ResourceManagement/cs-winui
2. Build a sideloading package in Visual Studio
3. Install and launch it
4. Click "Override Language" button

### Expected behavior

The text in German should be displayed

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2019

**Comment by ilovepumpkin** [comment]
Actually my Windows display language and preferred language are both set to Chinese, and I added Resources.lang-zh-cn.resw as well. When clicking "Default Language" button, the text in Chinese is expected, but it still displays "English Sample" text. This behavior is same in both Visual Studio and sideloading package. Not sure if I should open a different github issue or not.

**Comment by axelandrejs** [comment]
When you say you added the resources, do they show up here in the project file:

  <ItemGroup>
    <PRIResource Include="Resources.lang-de-de.resw" />
    <PRIResource Include="Resources.lang-en-us.resw" />
  </ItemGroup>

Also, in the packaging case, did you build as bundle or as single package? Bundles install only resources that are applicable to the current set of languages, though that should have picked up Chinese for you.

**Comment by huichen123** [comment]
When you create appx package from VS, the default behavior is create bundle. When bundle is installed, you probably don't have de-DE listed as one of the user language, thus the de-DE package won't be installed. So the German string, you either not create appx bundle, or add German to your user preferred language list.
As of the text underneath Default language button, it's not localized.

**Comment by ilovepumpkin** [comment]
Thank you guys!  It seems that the key is that I should select "Never" for "Generate app bundle" instead of "Always", then it will generate .msix instead of .msixbundle. 

![image](https://user-images.githubusercontent.com/11310645/149526209-adc5a974-ff7c-4eab-8a56-499ab7a60a52.png)

After I install .msix, everything works as expected.

**Comment by huichen123** [comment]
msixbundle works for me if i add german to preferred language list. It's worth checking whether the german language package is installed when you install the bundle.

**Comment by ilovepumpkin** [comment]
@huichen123 how/where should I check if the german language package installed or not?

**Comment by huichen123** [comment]
When I run "Get-AppxPackage -name 323858f2-34e1-48a5-8244-5c1bc0c1f889*" from Windows Terminal, it shows "323858f2-34e1-48a5-8244-5c1bc0c1f889_1.0.1.0_neutral_split.language-de_ew1zb5244bwa6" in Dependencies.

**Comment by ilovepumpkin** [comment]
@huichen123 , here is what I got - there is no German language package in Dependencies. 

```
PS C:\Users\Administrator> Get-AppxPackage -name 323858f2-34e1-48a5-8244-5c1bc0c1f889*


Name              : 323858f2-34e1-48a5-8244-5c1bc0c1f889
Publisher         : CN=IBM
Architecture      : X64
ResourceId        :
Version           : 1.0.6.0
PackageFullName   : 323858f2-34e1-48a5-8244-5c1bc0c1f889_1.0.6.0_x64__qbwk4wmnhe60a
InstallLocation   : C:\Program Files\WindowsApps\323858f2-34e1-48a5-8244-5c1bc0c1f889_1.0.6.0_x64__qbwk4wmnhe60a
IsFramework       : False
PackageFamilyName : 323858f2-34e1-48a5-8244-5c1bc0c1f889_qbwk4wmnhe60a
PublisherId       : qbwk4wmnhe60a
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.WindowsAppRuntime.1.0_0.319.455.0_x64__8wekyb3d8bbwe, Microsoft.VCLibs.140.00.UWPDesktop
                    _14.0.30704.0_x64__8wekyb3d8bbwe, Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Developer
Status            : Ok

```

**Comment by huichen123** [comment]
make sure you do have language-de.msix in your msixbundle, and de-DE is in your preferred language list.

**Comment by rohanp-msft** [comment]
Hi @ilovepumpkin, is this still an issue or was it resolved through Hui's help above? Thanks

**Comment by rohanp-msft** [comment]
> Hi @ilovepumpkin, is this still an issue or was it resolved through Hui's help above? Thanks

@ilovepumpkin a ping for this question.

**Comment by rohanp-msft** [comment]
Closing issue. If there is still an issue, please let us know.
