### ISSUE TITLE
PrefetchVirtualMemory does not prefetch virtual memory (windows api bug)

### ISSUE THREAD

**Issue by no-j** [microsoft/WindowsAppSDK#1992]
I tested [PrefetchVirtualMemory](https://docs.microsoft.com/en-us/windows/win32/api/memoryapi/nf-memoryapi-prefetchvirtualmemory) to minimize page faults when creating a file mapping, and measured the performance (compiler ticks using __rdtsc() intrinsic) and the actual count of page faults (using GetProcessMemoryInfo) when processing files, with and without a call to PrefetchVirtualMemory.

To my surprise, PrefetchVirtualMemory does not work as advertise and does not do it's only job, which was to actually fetch the memory from disk as efficiently as possible to minimize page faults.

I used the following process for testing, loading a range of file sizes (I'll share my results for a ~500MB file):
I opened a file handle, created a memory map and a view of the whole file, then I processed the whole file making sure to touch every page of the allocated view, and got 12,145 page faults.
Then I repeated the process, and called PrefetchVirtualMemory on the view before processing the file. During PrefetchVirtualMemory I got 26 page faults, and during the actual processing of the file I got 12,120 page faults.

To add insult to injury, the performance was slightly **worse** with PrefetchVirtualMemory, making the whole thing useless as it is its only job.

**Comment by AzAgarampur** [comment]
sounds like a good performance-based issue for https://github.com/microsoft/Windows-Dev-Performance
