### ISSUE TITLE
CanvasImageSource in UWP disappears when minimize or screen lock

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/WindowsAppSDK#1998]
### Describe the bug

Xamarin forms uses the CanvasImageSource for font icons. https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs#L39

https://github.com/xamarin/Xamarin.Forms/issues/8293
https://github.com/xamarin/Xamarin.Forms/issues/14323

### Steps to reproduce the bug

Set an Image Source to a CanvasImageSource drawn [in this manner](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Platform.UAP/FontImageSourceHandler.cs#L39) . - Renders ok

Minimize or lock screen.

Show the app

Icon disappeared.

### Expected behavior

Icon not disappeared.

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022

### Additional context

Example https://github.com/tonyhallett/FontSvgImageSource

**Comment by btueffers** [comment]
Hi @tonyhallett, since this issue is related specifically UWP rather than WinAppSDK a better forum for your issue would be the [Microsoft Q&A for UWP](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

**Comment by tonyhallett** [comment]
@btueffers WinUi repo referred me here.
