### ISSUE TITLE
PowershellSDK no longer works when running Import-Module command

### ISSUE THREAD

**Issue by bogdan-patraucean** [microsoft/WindowsAppSDK#2003]
### Describe the bug

I started to develop an app using Project Reunion 0.5 with PowershellSDK 7.1.2 on Windows 10 (unpackaged project), Visual Studio 2019.

Running this code was giving me the desired results:

```
using PowerShell shell = PowerShell.Create();
shell.AddScript("Set-ExecutionPolicy Unrestricted");  
shell.AddScript("Import-Module Appx -UseWindowsPowerShell");  
shell.AddScript("Get-AppxPackage | Select Name, PackageFullName, InstallLocation | Sort-Object -Property Name");  
result = await shell.InvokeAsync();  
```

After updating to Windows **11**, Visual Studio **2022** and upgrading my app to WindowsAppSDK **1.0** & PowershellSDK **7.2.1** this code no longer works, giving me this error everytime: _{ The 'Get-AppxPackage' command was found in the module 'Appx', but the module could not be loaded. For more information, run 'Import-Module Appx'. }_

Sometimes I see this error in the shell object, under Streams.Errorr, otherwise, depending on the code I try I only see it if I specifically try to get the error with shell.AddScript("Get-Error"). HadErrors property is true everytime.

What I tried and still having the same error:
1. Installing manually pwsh.exe from github, and manually setting this in my code: 
```
Environment.SetEnvironmentVariable("$env:PSModulePath", @"the value got from running $env:PSModulePath in pwsh.exe");
```
2. Running the script like this:
```
shell.AddScript("$s = New-PSSession -UseWindowsPowerShell; try { Invoke-Command - Session $s { Get-AppxPackage | Select Name, PackageFullName, InstallLocation | Sort-Object -Property Name }} finally { $s | Remove-PSSession }");
```
3. Tested on Windows **10** with WindowsAppSDK **1.0** & PowershellSDK **7.2.1**
4. Tested on Windows **10** with WindowsAppSDK **1.0** & PowershellSDK **7.1.2** (the version that was previously working)
5. Tested both with a packaged MSIX and unpackaged
6. Tested on Windows **11** with WindowsAppSDK **1.1** & PowershellSDK **7.2.4**

I don't know if it's a WindowsAppSDK, a PowershellSDK or a Windows problem so sorry if it's not the right repo to open the issue.

If I try to run this command in a terminal using powershell it's working perfect.

### Steps to reproduce the bug

1. Create a new WindowsAppSDK project with WindowsAppSDK 1.0 & PowershellSDK 7.2.1
2. Use the default  **myButton_Click** event handler  that's generated in MainWindow.xaml.cs to add the same code I tried:
```
using PowerShell shell = PowerShell.Create();
shell.AddScript("Set-ExecutionPolicy Unrestricted");
shell.AddScript("Import-Module Appx -UseWindowsPowerShell");
shell.AddScript("Get-AppxPackage | Select Name, PackageFullName, InstallLocation | Sort-Object -Property Name");
result = await shell.InvokeAsync();
```
3. result Count property is 0, no matter what I try, there are no apps returned, only the error I reported

### Expected behavior

```
using PowerShell shell = PowerShell.Create();
shell.AddScript("Set-ExecutionPolicy Unrestricted");
shell.AddScript("Import-Module Appx -UseWindowsPowerShell");
shell.AddScript("Get-AppxPackage | Select Name, PackageFullName, InstallLocation | Sort-Object -Property Name");
result = await shell.InvokeAsync();
```

This code should be able to return the list of installed apps.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Insider Build (xxxxx), Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by asklar** [comment]
not a windows app sdk issue, this is a powershell core issue: https://github.com/PowerShell/PowerShell/issues/13138

**Comment by bogdan-patraucean** [comment]
> not a windows app sdk issue, this is a powershell core issue: [PowerShell/PowerShell#13138](https://github.com/PowerShell/PowerShell/issues/13138)

Now the question is, why did it work with the scenario described above? I mean, I tried the exact same version of the SDK that previously worked, and now it doesn't.

**Comment by bogdan-patraucean** [comment]
Tested the same code using a normal **console app with .NET 6** and the code works flawless there. It looks like there is some limitation with this WASDK project.

**Comment by bogdan-patraucean** [comment]
Due to no updates /  activity on this issue and having [this ](https://github.com/PowerShell/PowerShell/issues/13138#issuecomment-1181956453) in mind I will close the issue. I found a workaround for what I needed that does not imply using AppxModule. If it's needed and the issue will be updated I will reopen it.
