### ISSUE TITLE
Cant install vsix package

### ISSUE THREAD

**Issue by jarno9981** [microsoft/WindowsAppSDK#2004]
### Describe the bug

When installing latest windows app sdk msix package on visual studio 2022 preview 3 it says unsupported because version is to low

### Steps to reproduce the bug

1. Install visual studio 2022 preview3
2. Try to install latest windows app sdk from microsoft site
3. Error will display when clicking motify after a few secondes

### Expected behavior

What i think should hebben that the installer says succes installing and then that i can build winui3 apps

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

**Comment by jarno9981** [comment]
![20220123_210041](https://user-images.githubusercontent.com/53493418/150695930-597a50f3-89e8-4a57-9ed0-df0bf8ce3038.jpg)
![20220123_210004](https://user-images.githubusercontent.com/53493418/150695933-c2b1f856-1116-4a99-9992-e389832676cc.jpg)

**Comment by aepot** [comment]
VSIX extension is not MSIX package.

**Comment by jarno9981** [comment]
Sorry my mistake that i say it wrong

**Comment by aepot** [comment]
First of all, install VS 2022 from Current Channel instead of Preview.
https://docs.microsoft.com/en-us/visualstudio/productinfo/release-rhythm
Then install the extension corresponding to the VS version, SDK and the programming language
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by jarno9981** [comment]
@aepot now it works fine

**Comment by plonkaadam** [comment]
@jarno9981: no need to install the VSIX, since preview 3 newer version is available through installer
see: https://github.com/microsoft/WindowsAppSDK/discussions/2014

**Comment by WebsiteHostJarno** [comment]
@plonkaadam okay thank you

**Comment by jarno9981** [comment]
@plonkaadam thank you
