### ISSUE TITLE
Add WinRT API version of GetSecurityDescriptorForAppContainerNames

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/WindowsAppSDK#201]
#188 brought up a good idea for a WinRT API equivalent of this new function, that will return the security descriptor in SDDL string form. I'll plan to do this, but don't have time to address it right now, and it wasn't part of the original plan. Creating this issue to track that part of the feature.

**Comment by omikhailov** [comment]
Since the most common use case for this function is sharing named objects between Win32 and WinRT applications, it makes sense to create a wrapper for GetAppContainerNamedObjectPath too.

https://docs.microsoft.com/en-us/windows/uwp/communication/sharing-named-objects
