### ISSUE TITLE
EnableDynamicLoading causes framework assemblies to be included in project build output

### ISSUE THREAD

**Issue by williamfigtree** [microsoft/WindowsAppSDK#2036]
### Describe the bug

Including `<EnableDynamicLoading>true</EnableDynamicLoading>` in .net sdk style projects causes the WindowsAppSDK framework assemblies `WinRT.Runtime.dll` and `Microsoft.Windows.SDK.NET.dll` to be included in the build output. [EnableDynamicLoading](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enabledynamicloading) should not include framework dlls as only one version of these can be loaded at a given time.

### Steps to reproduce the bug

1. In VisualStudio create a new Class Library (WinUI 3 in Desktop) project
2. Add `<EnableDynamicLoading>true</EnableDynamicLoading>` to the project's PropertyGroup
3. Build the project
4. Observe the includion of `WinRT.Runtime.dll` and `Microsoft.Windows.SDK.NET.dll` in the build output

### Expected behavior

`WinRT.Runtime.dll` and `Microsoft.Windows.SDK.NET.dll` should not be present in the build output.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 1909 (18363, November 2019 Update)

### IDE

Visual Studio 2022

### Additional context

This problem causes issues when dynamically loading modules using AssemblyLoadContext as runtime exceptions are thrown when the additional framework assemblies are detected and loaded at runtime.

**Comment by manodasanW** [comment]
@williamfigtree can you clarify your scenario where you are trying to load multiple different versions of WinRT.Runtime / Microsoft.Windows.SDK.NET?  Are you trying to use multiple libraries using C#/WinRT projections built with different versions of CsWinRT in a native library or something else?

**Comment by williamfigtree** [comment]
@manodasanW I am trying to write a C# WinUI3 desktop application which loads plugins by reflection. The application and plugins are built, packaged, and deployed separately. Plugins are packaged as optional packages. VisualStudio does not have a template for this (https://github.com/microsoft/microsoft-ui-xaml/issues/2638) so I am using the "Class Library (WinUI 3 in Desktop)" template and a custom script to package the build output. In order to include plugin nuget dependencies in that build output I use `<EnableDynamicLoading>true</EnableDynamicLoading`. This has the side-effect of also including `WinRT.Runtime.dll` and `Microsoft.Windows.SDK.NET.dll` from the `Microsoft.WindowsAppSDK` nuget package. I do not believe these should be included. They should only be present in the application package so that only the application's copy of these is found at runtime by `AssemblyDependencyResolver`.

From https://github.com/dotnet/sdk/issues/3339 it looks like Microsoft.WindowsAppSDK may need the type `runtimepack` to designate it as framework.
