### ISSUE TITLE
Error while trying to build simple package with CsWinRT

### ISSUE THREAD

**Issue by btueffers** [microsoft/WindowsAppSDK#2042]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/2034

<div type='discussions-op-text'>

<sup>Originally posted by **bryaan** January 27, 2022</sup>
I install Microsoft.Windows.CsWinRT version 1.5.0-prerelease.220124.4 but I get the following build error:

`  Microsoft.WindowsAppSDK.targets(29, 97): [MSB4086] A numeric comparison was attempted on "%(NuGetPackageVersion)" that evaluates to "1.5.0-prerelease.220124.4" instead of a number, in condition "'%(Filename)%(Extension)'=='WinRT.Runtime.dll' and %(NuGetPackageVersion)>1.3".`</div>

**Comment by j0shuams** [comment]
I think using MSBuild [property functions](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-version-comparison-functions) instead of `&gt` will fix this.

In the rules listed on the function, it says anything following a "-" will be ignored

**Comment by Scottj1s** [comment]
@j0shuams  good call. Meantime, this will work around:
`<WindowsAppSDKVerifyWinrtRuntimeVersion>false</WindowsAppSDKVerifyWinrtRuntimeVersion>`

**Comment by bryaan** [comment]
@Scottj1s I added that line to my csproj file under PropertyGroup, but I still get an error:

`  Microsoft.NET.ConflictResolution.targets(112, 5): [NETSDK1152] Found multiple publish output files with the same relative path: C:\Users\Bryan\.nuget\packages\microsoft.web.webview2\1.0.1018-prerelease\lib\netcoreapp3.0\Microsoft.Web.WebView2.Core.dll, C:\Users\Bryan\.nuget\packages\microsoft.web.webview2\1.0.1018-prerelease\build\..\runtimes\win-x64\native_uap\Microsoft.Web.WebView2.Core.dll.`

**Comment by MuyuanMS** [comment]
Closing the issue as workaround has been provided to original issue and issue shouldn't exist now after 2 years where the file has been changed a few times meanwhile.
