### ISSUE TITLE
AppWindow::GetFromWindowId locks Window Styles

### ISSUE THREAD

**Issue by tom-huntington** [microsoft/WindowsAppSDK#2049]
### Describe the bug

In project reunion, we where able to change window styles with SetWindowLongPtrA.

But with the Windows App SDK, with the new `AppWindowPresenter` update, it seems like you have taken this away, forcing us to use the new (more limited) windowing APIs.

Very unhappy. Need Freedom

### Steps to reproduce the bug

```
auto print_styles = [=]() 
{
    auto styles = GetWindowLongPtrA(m_hwnd, GWL_STYLE);

    std::stringstream ss;
    ss << styles << std::endl;
    for (unsigned i = 63; i < 64; i--)
        ss << (((1ull << i) & styles) != 0);
     ss << std::endl;
     OutputDebugStringA(ss.str().c_str());
};
print_styles();
SetWindowLongPtrA(m_hwnd, GWL_STYLE, 0);
print_styles();
```

**Comment by riverar** [comment]
@tom-huntington Can you describe the problem and expected results here?

**Comment by riverar** [comment]
Here's a sample C++ project that uses your code above + Windows App SDK 1.0, on Windows 11 22543. Seems to work great.
[was_issue_2049.zip](https://github.com/microsoft/WindowsAppSDK/files/7983984/was_issue_2049.zip)

So we'll need a bit more info to figure out what's going on. (Is your HWND valid? How did you retrieve it?)

**Comment by tom-huntington** [comment]
Thanks @riverar, it only happens in my main project.

Should really should check in a Blank App before I waste your time.

**Comment by riverar** [comment]
Feel free to ping this thread if you get stuck. Maybe check for sneaky calls to GetActiveWindow or GetWindow.

**Comment by tom-huntington** [comment]
I think this happened because I upgraded from Project Reunion.

Migrating to a fresh solution usually solves issues that don't occur in a blank app.

**Comment by tom-huntington** [comment]
I was right. Although this only occurs after calling `AppWindow::GetFromWindowId`.

Here's a minimal reproducible example:

https://github.com/tom-huntington/CantChangeWindowStylesBug

I don't know if I would really call this a bug though, just the new behaviour. Feel free to close.

**Comment by riverar** [comment]
Before calling `AppWindow::GetFromWindowId`
![no_call](https://user-images.githubusercontent.com/475132/152257884-d20f77d6-8649-4657-89d9-1a8dd8acaff9.gif)

After calling `AppWindow::GetFromWindowId`
![after_call](https://user-images.githubusercontent.com/475132/152257898-b47c1dce-1d27-47bd-905d-02c956603ec4.gif)

Appears there's indeed some unexpected behavior here.

@rkarman Is this something you're tracking?
cc: @andrewleader

**Comment by rkarman** [comment]
Tracked by http://task.ms/36947410

**Comment by Jaiganeshkumaran** [comment]
Maybe this is because of subclassing?

**Comment by rkarman** [comment]
We are looking into this in the feature team. For some of the Presenters this is expected behavior (as in, once you apply say a FullScreen presenter we will try to block certain style changes), but for the default/overlapped presenter I did not expect this to happen. I'll get back here as soon as we have an update.
