### ISSUE TITLE
Fails to run app published to Microsoft Store

### ISSUE THREAD

**Issue by kingcean** [microsoft/WindowsAppSDK#2095]
### Describe the bug

Cannot open the app which is developed on WindowsAppSDK and published to Microsoft Store. Looks like the application never launches but the application crashes with the error below in the event log.

> CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
...

But the app can run correctly on the PC with WindowsAppSDK dev environment. So sounds the Publish wizard does not include all necessary references/assemblies nor Windows does not install them automatically.

### Steps to reproduce the bug

1. Create a project by "Blank App, Packaged (WinUI in Desktop)" template and code something. Ensure it can build and run correctly under Package mode.
2. Generate the .msix files by Visual Studio.
3. Generate the .msixbundle file by `MakeAppx bundle` and publish to Microsoft Store.
4. Install the app from Microsoft Store in another non-dev PC.
5. Fails to launch sadly. It says, "unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies" in event viewer.

The following is copied from my project file.

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.22000.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
    <AppxBundle>Always</AppxBundle>
    <AppxBundlePlatforms>x86|x64|arm64</AppxBundlePlatforms>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <!-- Other nodes -->
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.197" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  <!-- Other nodes -->
</Project>
```

### Expected behavior

The app launches well just like what I am debugging.

### Screenshots

Following is from event viewer.

> CoreCLR Version: 6.0.222.6406
.NET Version: 6.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
...

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

This is not about DEV environment but about the app has been published to Microsoft Store and installed in other PC without the DEV environment of WindowsAppSDK.

**Comment by kmgallahan** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/1762
