### ISSUE TITLE
Installation of Microsoft.WindowsAppSDK.Cpp.Dev17 failed. The extension has a lower version than required by Visual Studio.

### ISSUE THREAD

**Issue by MartinSnowden** [microsoft/WindowsAppSDK#2114]
### Describe the bug

Tried to install C++ Visual Studio 2022 extension for the Windows App SDK Stable Release Verion 1.0 (WindowsAppSDK.Cpp.Extension.Dev17.Standalone.vsix) on a newly installed Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.0. Using Windows 11 21H2 (Version 10.0.22000 Build 22000.)

The install failed with this error in the error log:

_2/17/2022 9:07:26 AM - Installation of Microsoft.WindowsAppSDK.Cpp.Dev17 failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.
2/17/2022 9:07:26 AM - Install Error : System.InvalidOperationException: Installation of Microsoft.WindowsAppSDK.Cpp.Dev17 failed. The extension has a lower version than required by Visual Studio.  Please install the extension from Visual Studio Installer instead.
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureComponentAndPackageAreHigherVersion(ILogger logger, IDependencyGraph dGraph, Catalog catalog, Component vsixComponent_

Also as it says:  _Please install the extension from Visual Studio Installer instead._, I went into the Visual Studio 2022 Installer but could find no option for the Windows App SDK.

Complete error log:

[dd_VSIXInstaller_20220217090435_40c0.log](https://github.com/microsoft/WindowsAppSDK/files/8087690/dd_VSIXInstaller_20220217090435_40c0.log)

### Steps to reproduce the bug

1) Install Visual Studio 2022 Community Edition 17.1.0 (WindowsAppSDK.Cpp.Extension.Dev17.Standalone.vsix download from: https://visualstudio.microsoft.com/free-developer-offers/)
2) Attempt to install the Windows App SDK Stable Channel Release Version 1.0 C++ Visual Studio 2022 extension  (download from https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel)

### Expected behavior

Expected a successful install...

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

![image](https://user-images.githubusercontent.com/65728515/154458939-eb054ead-3a50-48e0-9331-501290e23d35.png)

**Comment by DefaultRyan** [comment]
From the installation instructions here (https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b)

For VS 17.1 and newer, you install the extension via the VS installer, not downloading the VSIX. It's in the "Installation Details" for the .NET Desktop and C++ Desktop workloads. There is an existing VS feedback item to make the extension more discoverable here https://developercommunity.visualstudio.com/t/the-windows-app-sdk-templates-are-supposed-to-be-p/1668209
