### ISSUE TITLE
Unable to release to the Microsoft Store

### ISSUE THREAD

**Issue by MrAsterisco** [microsoft/WindowsAppSDK#2117]
### Describe the bug

I have a very simple app built with Visual Studio 2022, using the new WinUI 3 Blank Project template. The app works normally when installed via Visual Studio (using the Packaged target), but when published on the Microsoft Store and downloaded on a brand new Windows 10 or 11 system, it crashes on startup with the following error:

```
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at MyProgram.Program.Main(String[] args)
}
```

I found #1762 , which seems to be having the same problem and the proposed solution is to install the [VCRedist](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) on the target machine. Doing this, fixes the crash.

As the linked issue is marked as closed, I’m opening this new one because that solution isn’t really feasible for apps distributed via the Microsoft Store. It means that people that download the app from the Store need to be instructed on how to install the aforementioned library, otherwise they’ll never be able to run the app. Also, the only page I could find where there are download links (the one linked above), it’s not very user friendly and seems to be addressed to developers.

### Steps to reproduce the bug

1. Create a new WinUI 3 Blank Project with Visual Studio 2022.
2. Publish the project to the Microsoft Store.
3. Install it on a new Windows 10/11 machine without any additional software installed.

### Expected behavior

The Microsoft Store should take care of installing the required dependencies, if they aren’t available.
In alternative, a NuGet package could be provided to allow apps to embed the VCRedist.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000), Windows 10 version 21H2 (19044, November 2021 Update), Windows 10 version 21H1 (19043, May 2021 Update), Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022

**Comment by DrusTheAxe** [comment]
>I found https://github.com/microsoft/WindowsAppSDK/issues/1762 , which seems to be having the same problem and the proposed solution is to install the [VCRedist](https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) on the target machine. Doing this, fixes the crash.

This is fixed in the upcoming 1.1 release.

The root problem is much of WindowsAppSDK's implemented in C++ and thus needs the C/C++ Runtime (aka CRT). The CRT comes in multiple forms (static libs, DLLs, UniCRT built into the OS). Earlier releases (0.1 thru 1.0) were built with a dependency on the CRT as DLLs. This was _partially_ changed in 1.0 using the [HybridCRT](https://github.com/microsoft/WindowsAppSDK/blob/34cf5fb8d2312dcbb1591595c37d385a24339d18/docs/Coding-Guidelines/HybridCRT.md) technique (mix of UniCRT + static libs) but not everything could be converted in time for release (e.g. WinUI3). Thus the CRT is needed.

This conversion will be completed for 1.1.

@AdamBraden I don't see mention of the CRT prerequisite in [1.0-Stable's Release Notes](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-10). Am I holding it wrong?

**Comment by DrusTheAxe** [comment]
As a workaround does the problem still occur if you add a VCLibs dependency to your appxmanifest?

```
<PackageDependency Name="Microsoft.VCLibs.140.00" MinVersion="14.0.30035.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
```

Not sure if that's the right MinVersion but should be enough to see if it satisfies the missing DLL dependency.

**Comment by MrAsterisco** [comment]
@DrusTheAxe thanks for getting back to me!

> This conversion will be completed for 1.1.

So, just to be super clear, this means that once version 1.1 is out, apps built with that version will automatically embed the necessary libraries, right? Meaning that users installing the app from the Microsoft Store will get everything they need with a single download, right?

Do you have an ETA on when version 1.1 will be released?

> As a workaround does the problem still occur if you add a VCLibs dependency to your appxmanifest?

I added it as part of the `Dependencies` section of my `Package.appxmanifest` and then uploaded a new version to the Store. Unfortunately, nothing changed. The app still crashes on startup with the same error.

**Comment by BenJKuhn** [comment]
A more appropriate workaround would be to add a package reference to the UWPDesktop C/C++ libraries. 
https://docs.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge

This will install with your package, and avoid the need for customers to separately install the VC redist.

Ben

**Comment by MrAsterisco** [comment]
I'll have a look at the linked docs, thanks @BenJKuhn .

Maybe it makes sense to add this to the docs? I'm assuming I'm not the only one with this problem, right?

**Comment by AdamBraden** [comment]
@MrAsterisco - this is a bug in the Single Project MSIX packaging vsix. For 1.0, it should have the vclibs dependency. Note that if you use the Windows Application Packaging Project (*.wapproj) it correctly includes the vclibs dependency. You can manually add the correct version to your package manifest:

o	Release - <PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.30035.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>
o	Debug - <PackageDependency Name="Microsoft.VCLibs.140.00.Debug.UWPDesktop" MinVersion="14.0.30035.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US"/>

Docs were updated recently to call this out:
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-packaged-apps#prerequisites

fyi @Scottj1s

**Comment by DrusTheAxe** [comment]
>The app still crashes on startup with the same error.

Have you tried the change suggested by [Ben](https://github.com/microsoft/WindowsAppSDK/issues/2117#issuecomment-1045061934) or [Adam](https://github.com/microsoft/WindowsAppSDK/issues/2117#issuecomment-1048171846)? Does that fix your problem?

**Comment by MrAsterisco** [comment]
@AdamBraden apologies for my late reply, I had other priorities in front of this. I finally got around to test your solution: I added the dependency as described in the docs, I published an update to the Microsoft Store and… it still crashes.
To be fair, it now crashes with a different error, but I’m not sure how would I go about and debug this one, as it’s even less clear than the previous one.

I quickly tested on another machine with the infamous VSRedist installed and the app works flawlessly.

```
Log Name:      Application
Source:        Application Error
Date:          18/04/2022 11:16:32
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-KDSR7FR
Description:
Faulting application name: <AppName>.exe, version: 1.0.0.0, time stamp: 0x61954b73
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1503, time stamp: 0xb2acaea9
Exception code: 0xc000027b
Fault offset: 0x000000000010b382
Faulting process ID: 0x1dfc
Faulting application start time: 0x01d8530d5ffedde6
Faulting application path: C:\Program Files\WindowsApps\<AppName>_2.0.3.0_x64__aajmxhxqkmfjr\<AppName>.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: e1bdc899-3395-4b71-983b-90b8182849ac
Faulting package full name: <AppName>_2.0.3.0_x64__aajmxhxqkmfjr
Faulting package-relative application ID: App
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-04-18T10:16:32.9072522Z" />
    <EventRecordID>923</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-KDSR7FR</Computer>
    <Security />
  </System>
  <EventData>
    <Data><AppName>.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>61954b73</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1503</Data>
    <Data>b2acaea9</Data>
    <Data>c000027b</Data>
    <Data>000000000010b382</Data>
    <Data>1dfc</Data>
    <Data>01d8530d5ffedde6</Data>
    <Data>C:\Program Files\WindowsApps\<AppName>_2.0.3.0_x64__aajmxhxqkmfjr\<AppName>.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>e1bdc899-3395-4b71-983b-90b8182849ac</Data>
    <Data><AppName>_2.0.3.0_x64__aajmxhxqkmfjr</Data>
    <Data>App</Data>
  </EventData>
</Event>
```

**Comment by Scottj1s** [comment]
@MrAsterisco Can you share the msix that you uploaded to the Store?

**Comment by MrAsterisco** [comment]
@Scottj1s is there a way for me to share it privately? I wouldn't want to upload it here, as it's distributed as a hidden app on the Store.

**Comment by Scottj1s** [comment]
Can you direct email? sjones@microsoft.com

**Comment by Scottj1s** [comment]
@MrAsterisco any progress? should we keep this issue open?

**Comment by MrAsterisco** [comment]
@Scottj1s I apologize, I was focusing on other things and lost this notification. I am still unable to publish to the Microsoft Store, I am still getting the same crash error. We can keep this issue closed for now and I'll reopen it as soon as I get time to look into it.
