### ISSUE TITLE
Change GetComRegistrationFromRegistry to return GUID

### ISSUE THREAD

**Issue by danielayala94** [microsoft/WindowsAppSDK#2118]
### Describe the bug

Returning HRESULT makes the code more difficult to write, since it is called for both packaged and unpackaged scenarios, even when it's only valid for packaged.

### Steps to reproduce the bug

Code inspection

**Comment by sharath2727** [comment]
https://github.com/microsoft/WindowsAppSDK/pull/2094 - Addressed the bug as part of this PR. Thanks.
