### ISSUE TITLE
Need serious opinions: WINUI Accessibility Issue with Single Instance Apps

### ISSUE THREAD

**Issue by akash07k** [microsoft/WindowsAppSDK#2121]
Hi all,
I want to know your opinions about below thing about which I'm very
concerned and alarmed today.
I saw the new code which is published by WinUI teams on Github.
 (Related to single instancing).
I'm very, very much surprised that just for making an app single
instance, more than 200 lines of code?
That too with P/Invoke methods?
Ridiculous.
Is this the good user and developer experience for which Microsoft
advertises itself heavily on all social platforms and in media?
I have more than 10 years of extensive experience in programming with
.net and other technologies. So obviously I can follow the tutorial.
However, I want to ask that how will a beginner who is just starting
to learn .net and WinUI development grasp such a complex code?
Obviously beginners generally don't learn P/Invoke stuff much.
How can Microsoft expect that it can be a beginner friendly tutorial or code?
And if this is not a beginner friendly tutorial/code, then why
shouldn't they mentioned that it is targetted towards advanced users?
By that way beginners will be careful and will stay away from this.
The thing is that I have a student who wants to learn WinUI and has
some experience with  .net (Specificly C# and Winforms) and he
approached me for training him into WinUI development.
First I told to follow him this tutorial/code today and he just came
back to me a very demotivating mindset and directly said that this
technology doesn't suit him.
And I got curious and alarmed, and when I myself read the new code, I
got horriblly surprised.
And below is that code which I'm talking about:
https://raw.githubusercontent.com/microsoft/WindowsAppSDK-Samples/main/Samples/AppLifecycle/Instancing/cs-winui-packaged/CsWinUiDesktopInstancing/CsWinUiDesktopInstancing/Program.cs
Please give your opinions on this kind of move by Microsoft.

**Comment by andreww-msft** [comment]
Thank you for your feedback, you make several very good points. 

Note that we do already have an improved implementation on the backlog for some future release: [Improvements to the instancing redirection API](https://github.com/microsoft/WindowsAppSDK/issues/1709.)

**Comment by akash07k** [comment]
@andreww-msft 
First of all I'm getting page not found error while clicking on this issue:
![image](https://user-images.githubusercontent.com/6381747/154619929-bce2800b-67f9-4cc1-890b-f0a8f6e1c336.png)

And why is such an important thing is on backlog?
When are you planning to release? and what is blocking MSFT from releasing such an important feature in production/preview?
It is even not available in preview as per my research.
Is single instancing that much uncommon and rare? I don't think so.

**Comment by wbokkers** [comment]
I came up with my own class: SingleInstanceDesktopApp using named pipes that works well. I wanted to share it, but as soon as I heard that MS came up with their own solution, I dropped that idea.

**Comment by wbokkers** [comment]
In general I think the WinUI 3 is not really concerned about accessible features. There's one WinUI PM coming up with all kind of P/Invoke solutions for features that should have a native WinUI implementation (title bar icons, window sizing, etc...).

**Comment by akash07k** [comment]
@wbokkers 
Microsoft's implementation is very complex and not intuitive. If you have good implementation then please share  with me. I'll be thankful to you

**Comment by akash07k** [comment]
@wbokkers 
You are right. I too think that WinUI team is not much interested in user experience.

**Comment by wbokkers** [comment]
This is my solution:
https://gist.github.com/wbokkers/af326da5391bdb13b58529e720540178

**Comment by akash07k** [comment]
Thanks a lot bro. I'll try it

**Comment by andreww-msft** [comment]
My apologies - there was a trailing period in the link. I've fixed it now.

As to when exactly we'll release this, we don't yet have a committed target release. I'd be very interested in getting any feedback on the proposal in the meantime.

**Comment by andreww-msft** [comment]
No new feedback for a couple of weeks, so I'll go ahead and close this item now. Feel free to comment further on the instancing API improvements I previously linked: [https://github.com/microsoft/WindowsAppSDK/issues/1709](https://github.com/microsoft/WindowsAppSDK/issues/1709)
