### ISSUE TITLE
Support for win2d in Desktop apps (WinUI)

### ISSUE THREAD

**Issue by jtorjo** [microsoft/WindowsAppSDK#213]
Since UWP is pretty much in maintenance mode (read: there's close to nothing done on it), focus has been on .Net 5 / WinUI /Desktop Apps. This is great!

**I would like to be able to use win2d from a Desktop application** (no XAML islands). I'm pretty sure I'm far from the only one here.
There's a ticket since July 2019 (https://github.com/microsoft/Win2D/issues/707)

Please let me know if I should post this to the WinUI repository.

**Comment by jschroedl** [comment]
We really want this as well in a desktop app which currently uses GDI+ for graphics in OnDraw() functions (C++) and would LOVE to move it to WinUI + Win2d!

**Comment by jtorjo** [comment]
@stevewri It's awesome you guys are looking into this! Is it safe to assume this will be ready within a 6-9 months timeframe?
Clearly, the sooner the better -- I have an app that I'd like to port from UWP to Desktop as soon as possible (the only reason I used UWP was for win2d).

**Comment by stevewri** [comment]
We can't commit to future timeframes, but we keep this issue posted with any progress.

**Comment by jtorjo** [comment]
@stevewri Got it, thanks.

**Comment by Jaiganeshkumaran** [comment]
@jtorjo UWP is not in maintenance mode. It's still the way to go unless your scenario doesn't work in UWP and requires full trust access

**Comment by jtorjo** [comment]
@Jaiganeshkumaran How would you know that?

**Comment by pjmlp** [comment]
How come UWP is not in maintainance mode, given that Microsoft is silent on .NET Native's future and modern .NET support?

**Comment by codendone** [comment]
Closing as completed, as Win2D has bee available for WinUI 3 / WinAppSDK for a while now. If there are any issues requests related to it, those requests should be logged in the Win2D repo.
