### ISSUE TITLE
Proposal: remove requirement for CRT Redist if app is not using the CRT itself

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/WindowsAppSDK#2143]
### Describe the bug

The docs call out a requirement to explicitly include a CRT redistributable - either the VCLibs framework package or the VCRedist msi:
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deployment-architecture#additional-requirements

This requirement is solely due to implementation details of Windows App SDK binaries.  For example, microsoft.ui.xaml.dll dynamically links to the CRT, requiring app installers to provision those binaries at runtime.  

Ideally, only an app's use of the CRT should necessitate the CRT redistributable.

### Steps to reproduce the bug

1. Create a Windows App SDK app from a C# template
2. Configure the project as needed for packaged/unpackaged deployment
3. Build and deploy either locally or remotely to a device without the VCLibs.UwpDesktop framework package installed (for a packaged app) or the VCRedist installed (for an unpackaged app)
4. The app fails at launch with missing dependencies when trying to load microsoft.ui.xaml.dll (or other Windows App SDK binaries).

See related:
https://github.com/microsoft/WindowsAppSDK/issues/2117

### Expected behavior

A Windows App SDK app that does not use the CRT should run without the CRT redist present on a target machine.

**Comment by mikebattista** [comment]
This should work for self-contained as well. Packaged/unpackaged self-contained C# apps shouldn't require any CRT redist.

**Comment by Scottj1s** [comment]
@mikebattista correct, the solution here will use "Hybrid CRT" linkage for WinAppSDK binaries, rather than simply hiding dynamic CRT linkage from apps.  So self-contained apps that embed the WinAppSDK binaries will benefit as well.

**Comment by Scottj1s** [comment]
Fixed in WinAppSDK 1.0.2 servicing release
