### ISSUE TITLE
MddBootstrapInitialize needs samples/tests for non-default minVersion

### ISSUE THREAD

**Issue by asklar** [microsoft/WindowsAppSDK#2190]
All of the tests/samples for `MddBootstrapInitialize` are using the default-initialized value for `minVersion`. We should add tests and samples that exercise this API parameter with non-default values too.

**Comment by DrusTheAxe** [comment]
The samples show how to use the Bootstrap API with the version information of the WindowsAppSDK you built with. There are reasons you may want other values, but those are uncommon or advanced scenarios. The API allows you to specify other values and how to do so is straightforward, so the value of samples showing a different `minVersion` is low.

It's also problematic. You could, say, build using 1.1.0 and specify `minVersion` = <whatever-the-msix-version-is-for-1.1.3> but to _run_ you'd need 1.1.3+ installed. That wouldn't "just work" for everyone, posing its own complications.

The [C# Bootstrap API in 1.0](https://github.com/microsoft/WindowsAppSDK/blob/main/dev/Bootstrap/CS/Microsoft.WindowsAppRuntime.Bootstrap.Net/Bootstrap.cs) and the [new C++ equivalent in 1.1](https://github.com/microsoft/WindowsAppSDK/pull/2191) fewer simplify matter with their rich overloads. The samples are being updated to use these and docs are coming soon.

Samples aren't meant to exhaustively exercise every value for every parameter of every API.  For example, we don't plan to have a sample calling `Microsoft::Windows::ApplicationModel::DynamicDependency::Bootstrap::InitializeFailFast()`. We _do_ plan to have full documentation.
