### ISSUE TITLE
The documentation "Unpackaged: Create a new project for an unpackaged C# or C++ WinUI 3 desktop app" does not work for C++

### ISSUE THREAD

**Issue by Dragnalith** [microsoft/WindowsAppSDK#2212]
### Describe the bug

I following the tutorial to create in unpackaged C++ WinUI 3 desktop app.
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app

I set `<AppxPackage>false</AppxPackage>` as specificed in the doc. The build is successful, but the debugger do not run. I got an error: _The project 'App 10' cannot be started directly. In order to debug this project, you must consume it from an application project that creates a package and is marked as the Startup Project_.

(Notice I do not have the drop-down menu "App 10 (Package)", "App 10 (Unpackage)" to chose how to start the debugger.)

### Steps to reproduce the bug

1. Create a new Blank App, Packaged (WinUI 3 Desktop) project.
2. Set `<AppxPackage>false</AppxPackage>` on the .vcxproj
3. Notice the problem explained above.

### Expected behavior

The app should run and be debuggable.

### Screenshots

![image](https://user-images.githubusercontent.com/993556/156926603-42eb7f6d-6d84-4290-88b1-011bb6a3d014.png)
![image](https://user-images.githubusercontent.com/993556/156926679-470190bb-fc43-48f0-b463-8aa70e754761.png)

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022

### Additional context

I run the exact same issue with Visual Studio 2019, same version of the Windows App SDK C++ VS2019 Template (1.0.0.59203546).

I have read on some note the `<AppxPackage>false</AppxPackage>` should generate some code to call the Bootstrap API. I have check all the generated file but I did not find such code.

**Comment by asklar** [comment]
FYI @stevewhims

**Comment by asklar** [comment]
@Dragnalith You have to also set WindowsPackageType as the docs say
```xml
<AppxPackage>false</AppxPackage>
    <ApplicationType>Windows Store</ApplicationType>
    <WindowsPackageType>None</WindowsPackageType>
```

**Comment by Dragnalith** [comment]
@asklar 
Indeed, I misread I thought <WindowsPackageType>None</WindowsPackageType> was only for .csproj.

Actually it works as expected. Thank you.
