### ISSUE TITLE
Need a way to opt of out AutoInitialize logic

### ISSUE THREAD

**Issue by asklar** [microsoft/WindowsAppSDK#2215]
The [AutoInitialize code](https://github.com/microsoft/WindowsAppSDK/blob/e3d85eae6094134386a053437a1ff75fe368104f/dev/WindowsAppRuntime_BootstrapDLL/MddBootstrapAutoInitializer.cpp) runs at dll attach. This is fine for apps that are 100% winappsdk apps/winui3. However for apps that want to host islands of winappsdk/winui3 content (and they don't delayload winappsdk), this runs prematurely.

a) we should make it easy to delayload winappsdk until it is needed
b) or at least, to defer the initialization until it is needed (e.g. first winui3 dialog being shown)

**Comment by Scottj1s** [comment]
There is a project property you can define to disable the autoinitialization logic, allowing your app to take responsibility:
WindowsAppSdkBootstrapInitialize
And here is an issue requesting documentation for this property:
https://github.com/MicrosoftDocs/windows-uwp/issues/3714
