### ISSUE TITLE
If an 'unpackaged' app is packaged, it silently fails

### ISSUE THREAD

**Issue by fredemmott** [microsoft/WindowsAppSDK#2216]
### Describe the bug

Apps built as 'unpackaged' use MddBootstrapAutoInitializer; at present, if the app is being ran from a package, this makes the app instantly exit with:
- no crash dump, even if enabled
- no messages in the windows event viewer
- run with no messages in Visual Studio -> Debug -> Other Debug Targets -> Debug Installed Package...

### Steps to reproduce the bug

1. build an app as unpackaged
2. build and install an appx/msix with this binary
3. try to run it
4. silent exit
5. check logs

An alternative to steps 1 and 2 is to download the msix from https://github.com/fredemmott/OpenKneeboard/actions/runs/1942621414

### Expected behavior

Ideally, it should work. Unpackaged runs can be useful for debugging, and it's also useful to be able to distribute the same binaries in multiple forms, have one set of PDB files, etc.

Alternatively, it should - by default - log a clear error to the application log in event viewer.

Alternatively, throwing an exception would be a big improvement.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Other

**Comment by fredemmott** [comment]
As a workaround for this issue (and a solution for #2215):

- Add `DISABLE_XAML_GENERATED_MAIN=1` to your project's preprocessor definitions
- set `WindowsAppSdkBootstrapInitialize` to `false` in your project's global properties
- copy the default generated `wwinmain()` to your code, removing the `#ifndef DISABLE_XAML_GENERATED_MAIN`
- add something like the following:

```C++
  UINT32 packageNameLen = MAX_PATH;
  wchar_t packageName[MAX_PATH];
  const bool isPackaged
    = GetCurrentPackageFullName(&packageNameLen, packageName) == ERROR_SUCCESS;
  if (!isPackaged) {
    PACKAGE_VERSION minimumVersion {WINDOWSAPPSDK_RUNTIME_VERSION_UINT64};
    winrt::check_hresult(MddBootstrapInitialize(
      WINDOWSAPPSDK_RELEASE_MAJORMINOR,
      WINDOWSAPPSDK_RELEASE_VERSION_TAG_W,
      minimumVersion));
  }

  // ORIGINAL GENERATED wWinMain CODE STARTS HERE
  {
    void(WINAPI * pfnXamlCheckProcessRequirements)();
  //  ... MORE GENERATED CODE, THEN END WITH:
  
  if (!isPackaged) {
    MddBootstrapShutdown();
  }

  return 0;
}
```

**Comment by Scottj1s** [comment]
@fredemmott yours is an interesting scenario we had not considered - supporting WindowsAppSDK app execution in both packaged and unpackaged modes.  We could certainly take something like your workaround and incorporate it.  The concern would be for projects that have not intentionally packaged a call to MddBootstrapInitialize, which would constitute a configuration error.  The safe route might be to define a project property to opt into dual mode support, quietly skipping the call to MddBootstrapInitialize if packaged.  Thoughts?

**Comment by fredemmott** [comment]
That sounds ideal :) Though, to me, the biggest thing isn't that it isn't easy - it's the silent failure. Whether this becomes properly supported or not, it would be good to improve the error handling when done incorrectly - e.g. add an OutputDebugString or event saying that "This application was built as unpackaged and is attempting to initialize the dynamic bootstraper, but is running from an package"

**Comment by Scottj1s** [comment]
Yes, agreed - when done incorrectly (not opting in to "dual mode"), we need better diagnostics.  We're discussing how best to do that.

**Comment by DrusTheAxe** [comment]
> That sounds ideal :) Though, to me, the biggest thing isn't that it isn't easy - it's the silent failure

How about if we address both ;-)

[Rich information on Bootstrap initalization failure #2316](https://github.com/microsoft/WindowsAppSDK/pull/2316) improves discoverability, diagnosability and error handling for Bootstrapper initialization.

Errors are noted via ETW events but that's transient and unnoticed unless someone's actively listening for them or you're running under a debugger. So let's do better.

#2316 adds a log entry to the event log's Application channel for any error during initialization.

The new `MddBootstrapInitialize2` adds options for additional discoverability on error:

* `MddBootstrapInitializeOptions_OnError_DebugBreak`
* `MddBootstrapInitializeOptions_OnError_DebugBreak_IfDebuggerAttached`
* `MddBootstrapInitializeOptions_OnError_FailFast`

Plus `MddBootstrapInitializeOptions_OnNoMatch_ShowUI` if you want a messagebox to appear when a compatible WinAppSDK runtime isn't found, for that .NETCore-esque experience :-)

Plus `MddBootstrapInitializeOptions_OnPackageIdentity_NOOP` so packaged apps can call the API and succeed.

NOTE: These are the Flat-C API. There's equivalents in the C# and inline C++ APIs.

You can also set environment variables for similar results. Very handy for testing w/o recompiling:

* SET MICROSOFT_WINDOWSAPPRUNTIME_BOOTSTRAP_INITIALIZE_DEBUGBREAK=1
* SET MICROSOFT_WINDOWSAPPRUNTIME_BOOTSTRAP_INITIALIZE_FAILFAST=1
* SET MICROSOFT_WINDOWSAPPRUNTIME_BOOTSTRAP_INITIALIZE_SHOWUI=1

The autoinitializers are changing to use this, with their default of option=MddBootstrapInitializeOptions_OnNoMatch_ShowUI and an option to override the default at compile time.

About the only form of discoverability/reporting the Bootstrapper isn't doing is an explicit call to `OutputDebugString` or `RoOriginateError`. The Bootstrapper uses [WIL's error handling helpers](https://github.com/Microsoft/wil/wiki/Error-handling-helpers) which largely does that so I'm reluctant to add an explicit call. Or at least, not yet - waiting to see how folks find the improvements before assuming these are needed.

@Scottj1s and I've also discussed messages and knobs at compile-time to make it easy for developers to know the auto-initializers exist and ways to control them. Those won't be in #2316 but a subsequent PR. Ideally a developer new to WinAppSDK can File/New Project, build, run and fully understand if something is wrong or incomplete and what to do about it -- without ever having to look at the documentation.

Not that docs are bad. Docs are great. But one has to know the right question to ask, or even that there's a question one could ask. Better if ItJustWorks(TM) :-)

If you have thoughts on the subject how we can improve the product and/or make developers (i.e. your) lives easier please speak up. As always, feedback is welcome and appreciated.

**Comment by shelllet** [comment]
my unpackaged app is packaged  and uploaded to ms store, rejected with crash. can  this bug be fixed and update released soon?

**Comment by fredemmott** [comment]
Thanks, that’s so much better than I was hoping for - I especially appreciate the dialog box pointing users at downloads.

> The Bootstrapper uses [WIL's error handling helpers](https://github.com/Microsoft/wil/wiki/Error-handling-helpers)

> Not that docs are bad. Docs are great. But one has to know the right question to ask, or even that there's a question one could ask. Better if ItJustWorks(TM) :-)

This is very tangential: there seem to be thorough docs on how to make WIL and C++/winrt interoperate, I’m not seeing an explanation of *why* someone would want to/should use WIL in a new c++/winrt app.

For context, I mostly do cross platform development, and got the impression that c++/winrt + winui3 would be the most “future-proof” way to write a full trust modern C++ windows GUI app - I was aware that WIL exists, but it didn’t seem to be part of the “this is the future” message

**Comment by jonwis** [comment]
> there seem to be thorough docs on how to make WIL and C++/winrt interoperate, I’m not seeing an explanation of why someone would want to/should use WIL in a new c++/winrt app.

WIL is a great pile of helpers to interoperate with the lowest layers of the Windows platform stack. Lifecycle managers for handles, wrappers that convert the tangle of `HRESULT` vs `GetLastError` to a uniform exception (or return with appropriate disposition) model for C++ consumers. It's what we use to build Windows itself in many cases - using a common framework to address the platform layer eliminates entire categories of bad code.

If your app is staying at the top edge of WinRT and WinUI, you don't need WIL in your own code.  But if you _do_ drop to the Win32 ABI, you might like [wil::get_token_information](https://github.com/microsoft/wil/wiki/Token-Helpers) better than using the two-call-pattern Win32 API instead.  Or you might like `wil::unique_hfind` to manage the return of `FindFirstFile`.

**Comment by DrusTheAxe** [comment]
> my unpackaged app is packaged and uploaded to ms store, rejected with crash. can this bug be fixed and update released soon?

The current behavior isn't a bug it's ByDesign. As Scott noted it hadn't come up in earlier planning but it's a good idea.

Per the [roadmap](https://github.com/microsoft/WindowsAppSDK#roadmap) WinAppSDK 1.1 (Stable) is expected to release in Q2 2022.

You can workaround this as mentioned above by checking for package identity before calling the Bootstrap API. Then once `MddBootstrapInitialize2()` is available you can replace your check with the new parameter.

**Comment by shelllet** [comment]
it's too complex, i'm fuzzy, can it  be fixed in preview-2?

**Comment by fredemmott** [comment]
Thanks, just started to try upgrading to 1.1 - fyi, https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-run-time links to https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/win32/mddbootstrap/nf-mddbootstrap-mddbootstrapinitialize2 , which is a 404

**Comment by DrusTheAxe** [comment]
The issue originally reported has been addressed via the MddBootstrapInitializeOptions_OnPackageIdentity_NOOP option so closing this issue.

P.S. @fredemmott 

> Thanks, just started to try upgrading to 1.1 - fyi, https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-run-time links to https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/win32/mddbootstrap/nf-mddbootstrap-mddbootstrapinitialize2 , which is a 404

The link issue looks like it was a temporary timing issue, accessing the MddBootstrapInitialize2 docs before published (linker page was updated and accessed before the linkee was published?). That resolves now as expected. Please do let us know if you find any such problems in the future. Thanks!
