### ISSUE TITLE
Introduce AppNotification default icon for unpackaged apps

### ISSUE THREAD

**Issue by danielayala94** [microsoft/WindowsAppSDK#2228]
### Describe the bug

Add default icon -> see #2192 commits for the first approach.

Also, address:
- Change LOG_IF_FAILED to THROW macros
- displayName.length() == 0 to displayName.empty()
- Set uppercase for display name built from exe filepath 

### Steps to reproduce the bug

Bug fix

**Comment by pmpurifoy** [comment]
displayName.length() == 0 to displayName.empty() taken care of here: 
https://github.com/microsoft/WindowsAppSDK/pull/2238/files

**Comment by robertzhou-wpn** [comment]
This issue has been fixed
