### ISSUE TITLE
Use methods from shell32.dll causes XAML parsing failure

### ISSUE THREAD

**Issue by JohnCido** [microsoft/WindowsAppSDK#2250]
### Describe the bug

I was trying to use this method: `SHGetKnownFolderPath`. But once I use `DllImport` and call the method, the app throws a XAML parsing failed exception at launch.
I also tried to use the [Microsoft.WindowsAPICodePack-Shell](https://www.nuget.org/packages/Microsoft.WindowsAPICodePack-Shell/), but this package causes loads of XAML conflicts.

### Steps to reproduce the bug

1. Create a new blank WinUI project
2. Call any method from the shell32.dll

### Expected behavior

No XAML parsing failures.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

I was trying to list all the installed apps on the system and provide the ability to launch them via my app. I don't want to use the registry method since it also includes all the un-launchable apps and seems does not include UWP apps.

**Comment by riverar** [comment]
@JohnCido Hey John, [remember your other issue](https://github.com/microsoft/WindowsAppSDK/issues/2302)? A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)

**Comment by JohnCido** [comment]
@riverar Sorry for the late update on this. I just tried using the `SHGetKnownFolderPath` method, both with `DllImport` and `Pinvoke.Shell32` NuGet package. I can't reproduce it at the moment. So I'll close it for now. I'll re-open it if I encountered this issue again in the future.
In the meantime, sorry for the inconvenience.
