### ISSUE TITLE
GetExeFromPath doesn't work if the .exe exists in the same directory

### ISSUE THREAD

**Issue by pmpurifoy** [microsoft/WindowsAppSDK#2263]
https://github.com/microsoft/WindowsAppSDK/blob/d4fd51ac87f0e2bd44abd82ef7ba5ad4c3700d05/dev/PushNotifications/PushNotificationUtility.h#L158

The function parses the \ from the path and returns the exe but if the path is just the exe it will throw.

**Comment by LegendaryBlair** [comment]
Confirmed with the author, close this one as won't fix.
