### ISSUE TITLE
Add missing usings feature doesn't add all required usings

### ISSUE THREAD

**Issue by logany-hi** [microsoft/WindowsAppSDK#2266]
### Describe the bug

Having copied code into my file that references classes in different namespaces, the context menu's "add missing usings" item adds some namespaces, but not always all the ones I need.

For example, I have a class library called `LoganData` in which I have a namespace called `Models` which holds data models used for Entity Framework.

When I make use of "Add missing usings", Visual Studio adds `using LoganData`, but doesn't add `using LoganData.Models` so I have to manually add that reference.

### Steps to reproduce the bug

1. In a new project (eg. Project1), define a namespace with some classes in it
2. Reference this project in a separate project
3. Write code in the separate project that would reference the namespace in Project1 (entire call to Project1 class would be Project1.Foo.Bar)
4. Perform a cut/copy and paste operation in the file
5. Open Quick Actions and select "Add missing usings"

### Expected behavior

The namespace containing the referenced class in the test project will not be added, but the project containing that namespace will.

I expect that if I reference `Project1.Foo.Bar`, adding a missing using in a file where I make use of the `Bar` class of `Foo` in `Project`, the feature in Visual Studio would add `using Project1.Foo` rather than just `using Project1`.

### IDE

Visual Studio 2022-preview, Visual Studio 2022

### Additional context

Visual Studio version indicated is:

```
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0
```

**Comment by BenJKuhn** [comment]
Unfortunately, this sounds like a Visual Studio issue. We aren't the right team to help you with this. Please submit this using the feedback tool in Visual Studio, which will also capture the metadata that the Visual Studio team will need to further diagnose this issue.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/12173217/160470685-05d1d977-44a3-420d-a836-4bbbb0e23cc9.png">

Thanks,

Ben
