### ISSUE TITLE
Product board and roadmap are now out of sync

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#2271]
Looks like the ancillary roadmap was just updated (https://github.com/microsoft/WindowsAppSDK/pull/2270) but product board (the **current primary roadmap**) was not. [Product board](https://portal.productboard.com/winappsdk/1-windows-app-sdk/tabs/2-planned) still claims 1.1 planning is in progress and none of the features are locked in but the other roadmap seems to confirm they are. Also, items such as Background Acrylic aren't listed in 1.1 on Product Board. Which one is right? Is Product Board still the authoritative source?

**Comment by marb2000** [comment]
Thanks, @riverar, I have updated Product Board.

**Comment by riverar** [comment]
Did this change roll out? Just looked and acrylic is still in the same spot.
