### ISSUE TITLE
Setting Maximized for PreferredLaunchWindowingMode in UWP is not workingBug title

### ISSUE THREAD

**Issue by kumaresan-cgvak** [microsoft/WindowsAppSDK#2311]
### Describe the bug

Setting `ApplicationViewWindowingMode.Maximized` for `ApplicationView.PreferredLaunchWindowingMode` is not working in Xamarin Forms UWP projects.

`ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.Maximized`

Sample:
[MaximiseSample.zip](https://github.com/microsoft/WindowsAppSDK/files/8326346/MaximiseSample.zip)

### Steps to reproduce the bug

1. Create a Xamarin Forms app compatible with UWP
2. Add the code `ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.Maximized` in App.xaml.cs
3. Run the app in UWP.

### Expected behavior

App should Maximise on launch / consecutive launches

### Windows version

Windows 11 version 21H2 (22000), Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022, Visual Studio 2019

**Comment by UWPIsDeadInTheWater** [comment]
UWP IS DEAD. It is as dead as Silverlight , XNA , Windows Phone is dead. 

`CoreWindow`/`ApplicationView` aka UWP   is/will not be supported in Windows App SDK. https://github.com/microsoft/WindowsAppSDK/issues/1889#issuecomment-990221146 

Windows App SDK only supports Win32 Apps. https://github.com/microsoft/WindowsAppSDK/discussions/1615

**Comment by dongle-the-gadget** [comment]
> UWP IS DEAD. It is as dead as Silverlight , XNA , Windows Phone is dead.
> 
> `CoreWindow`/`ApplicationView` aka UWP is/will not be supported in Windows App SDK. [#1889 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/1889#issuecomment-990221146)

Stop with this all kind of FUD

**Comment by UWPIsDeadInTheDeepWater** [comment]
> Stop with this all kind of FUD

FUD ? 
There's a fine line of difference between FUD and Reality. Ignoring the reality is called Delusion.
I get it. It must have seen so hurtful to see the demise of the UWP cult.

**Comment by dongle-the-gadget** [comment]
This is getting annoying - literally creating new accounts just to send a comment about how UWP is dead and then deleting it entirely.

**Comment by UWPIsDeeadInTheDeepWater** [comment]
> This is getting annoying - literally creating new accounts just to send a comment about how UWP is dead and then deleting it entirely.

Ah. Classic Personal Incredulity fallacy.

Anyway, Point stands. UWP IS DEAD. shilling for it doesn't make it less dead.

**Comment by BenJKuhn** [comment]
I'm going to delete some of the inappropriate posts on this issue. Although we're not focused on new feature development for UWP it remains a supported platform for Windows Apps. We're asking around to see who might know more about this issue.

**Comment by rkarman** [comment]
This is not exclusive to Xamarin based UWP projects, this has never worked for UWP on Windows Desktop. The values added to the [ApplicationViewWindowingMode](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationviewwindowingmode?view=winrt-22000) in 1809 were only supported on Windows 10X. The Windows Desktop version did not add support for these types as direct launch-into states.

I have filed a task to update MSDN to properly reflect this: [task.ms/38740221](http://task.ms/38740221)

**Comment by rkarman** [comment]
Not from within the UWP app container. This is only achievable with a full trust component. For UWP apps that full trust component would have to get the HWND for the CoreWindow in question and then use the ShowWindow API on the parent HWND (the appframehost HWND) to make it maximized.
