### ISSUE TITLE
v1.1 breaking api change

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#2332]
### Describe the bug

The latest v1.1.0-preview contains a breaking binary change in the `Microsoft.Web.WebView2.Core` namespace 

![image](https://user-images.githubusercontent.com/1378165/160740920-9fc6d722-1e15-4d84-bdbf-925fe4d138cb.png)

### Steps to reproduce the bug

1. Create a class library that targets v1.0.0 and uses the removed APIs. Example:
```cs
    public class Class1
    {
        private readonly CoreWebView2 webView;
        public Class1(CoreWebView2 webView)
        {
            this.webView = webView;
            this.webView.ClientCertificateRequested += WebView_ClientCertificateRequested;
        }

        private void WebView_ClientCertificateRequested(CoreWebView2 sender, CoreWebView2ClientCertificateRequestedEventArgs args) => args.SelectedCertificate = GetCertificateAction?.Invoke();
        public Func<CoreWebView2ClientCertificate> GetCertificateAction { get; set; }
    }
```
2. Create an application that targets v1.1.0-preview1, and tries to use the class library above:
```cs
            var lib = new MyClassLib.Class1(null);
            lib.GetCertificateAction = () =>
            {
                return new Microsoft.Web.WebView2.Core.CoreWebView2ClientCertificate();
            };
```

Observe the build error:
>Error	CS7069	Reference to type 'CoreWebView2ClientCertificate' claims it is defined in 'Microsoft.WinUI', but it could not be found	App1	

### Expected behavior

There should be no binary compatibility breaking changes in minor releases.

### Screenshots

![image](https://user-images.githubusercontent.com/1378165/160741382-e0a3e9c7-a19a-492f-8593-d4566d809621.png)

### NuGet package version

1.1.0-preview1

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview, Visual Studio 2022

**Comment by dotMorten** [comment]
On a side note I'd recommend you use the Baseline Package Validator to catch things like this. It'll fail the pack operation when there are breaking changes introduced: https://docs.microsoft.com/en-us/dotnet/fundamentals/package-validation/baseline-version-validator

**Comment by asklar** [comment]
@champnic @david-risney looks like this is a breaking change in WV2 that is "leaking" through WinAppSDK. Can we do something to catch these, or should we expect the WV2 APIs to be fluid / possibly have abi breaks?

**Comment by MikeHillberg** [comment]
We're fixing the issue and adding test coverage to the pipeline. (We're using a tool that's used in Windows too, I'm not sure if it's the same as Baseline Package Validator.)
