### ISSUE TITLE
This line results in trying to delete the console window

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/WindowsAppSDK#2340]
https://github.com/microsoft/WindowsAppSDK/blob/b419d6d9d551f8e083f97f647f0e51f654a319a3/test/TestApps/PushNotificationsDemoApp/main.cpp#L98

wil::unique_hwnd calls DestroyWindow() when it runs down. That will fail if that window is from a different thread, but this should not be used in this case.

**Comment by danielayala94** [comment]
I have removed the code that sets icon/displayName using the Shell APIs, since we aren't doing anything with it during app registration anymore.
