### ISSUE TITLE
Failed to submit to Microsoft Store because of no Microsoft.ui.xaml.dll

### ISSUE THREAD

**Issue by kingcean** [microsoft/WindowsAppSDK#2346]
### Describe the bug

Microsoft Store Report App Team rejects the app submission because it unexpectedly terminated at launch. The app targets .NET 6 Windows 10.0.22000 and Windows App SDK 1.0.1. Event viewer shows that unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies.

However, the app can run in my dev environment.

For reference, following are the details of the app in Microsoft Partner Center. But of course, you can't find it directly in Microsoft Store because its first submission is rejected several times. Maybe you can contact Microsoft Store Report App Team (reportap@microsoft.com) to get details and repro.

| Key | Value |
| ---------- | ------------------------------------- |
| App ID | `9NBLGGH4NBXB` |
| App name | 爱奇艺 Preview |
| App name in English | iQIYI Preview |
| Package ID | `0C72C7CD.61910B44FC902` |

Following is the file output from event viewer by Microsoft Store Report App Team.

- __[AppEventLog.zip](https://github.com/microsoft/WindowsAppSDK/files/8396281/AppEventLog.zip)__

### Steps to reproduce the bug

1. Create a WinUI 3 packaged app with some features. Ensure it can run correctly.
2. Package it.
3. Submit it to Microsoft Store.

### Expected behavior

It can be available in Microsoft Store.

That means it won't crash anymore during reviewing by Microsoft Store Report App Team and running in end-users' devices.

### Screenshots

Following is the report about the reason the team of Microsoft Store rejects the submission. It says the app crashes at launch.

![image](https://user-images.githubusercontent.com/1724940/161230923-d3f20093-9aa2-485e-b6f0-b0f86f76dd1b.png)

Following is the screenshot that the app runs correctly in my local dev environment.

![image](https://user-images.githubusercontent.com/1724940/161232468-aa7db549-7a45-403e-8367-f4e8601bcb97.png)

It also works well by launch from Start Menu without debug in my local environment.

![image](https://user-images.githubusercontent.com/1724940/161232800-8ffe0518-9771-4907-903f-ce4e974a9e49.png)

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

It says...

> The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at IQIYI.UI.Program.Main(String[] args)

Following is an excerpt from the `PropertyGroup` section of the app project file (`.csproj`).

```csproj
<OutputType>WinExe</OutputType>
<TargetFramework>net6.0-windows10.0.22000.0</TargetFramework>
<TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
<AssemblyName>iQIYI</AssemblyName>
<RootNamespace>IQIYI.UI</RootNamespace>
<ApplicationManifest>app.manifest</ApplicationManifest>
<Platforms>x86;x64</Platforms>
<RuntimeIdentifiers>win10-x86;win10-x64</RuntimeIdentifiers>
<PublishProfile>win10-$(Platform).pubxml</PublishProfile>
<UseWinUI>true</UseWinUI>
<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
<Product>iQIYI</Product>
<Authors>Kingcean Tuan</Authors>
<Company>iQIYI, Inc.</Company>
<Version>6.0.160</Version>
<AssemblyVersion>6.0.160.0</AssemblyVersion>
<FileVersion>6.0.160.0</FileVersion>
<Description>iQIYI Windows app.</Description>
<Copyright>Copyright (c) 2022 iQIYI, Inc. All rights reserved.</Copyright>
<RepositoryType>git</RepositoryType>
<DefaultLanguage>zh-Hans</DefaultLanguage>
<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
<ApplicationIcon>..\iQIYI.ico</ApplicationIcon>
```

Related package references.

- `Microsoft.WindowsAppSDK`: `1.0.1`.
- `Microsoft.Windows.SDK.BuildTools`: `10.0.22000.197`.

P.S.: The app is the official UWP app in next generation of iQIYI (the top streaming platform hosted in mainland China).

**Comment by hez2010** [comment]
Known issue: https://github.com/microsoft/WindowsAppSDK/issues/2117

You may try the workaround [here](https://github.com/microsoft/WindowsAppSDK/issues/2117#issuecomment-1045061934).

**Comment by kingcean** [comment]
Thanks @hez2010 , I will have a try soon.

**Comment by hez2010** [comment]
For reference https://github.com/microsoft/WindowsAppSDK/issues/1762.

**Comment by Scottj1s** [comment]
@kingcean you may be running into an issue that removes all framework package references, including the one you attempted to add above, to Microsoft.VCLibs...UWPDesktop.  You can work around that by adding this empty target to your project:
`    <Target Name="_RemoveFrameworkReferences" />`

**Comment by Richasy** [comment]
From the description of the issue, you may are running in debug mode (even launching from the start menu), maybe you can try to adjust the deployment mode to Release in VS, or generate a side-load package and install it locally to see if it crashes.

![image](https://user-images.githubusercontent.com/27713596/161934017-b5c6fe8b-497f-436f-bb09-dc4f2e8fbe5d.png)

I have encountered a similar situation, when trying to import shadow effect in CommunityToolkit, it works fine in Debug mode, but in Release mode it crashes.

**Comment by kingcean** [comment]
I have tested generating a MSIX bundled package to install locally, and it works great. But it does crash when I run in Release mode by Visual Studio as what you said, @Richasy . But the exception is not the one provided by Microsoft Store review team.

![image](https://user-images.githubusercontent.com/1724940/161950107-d4f4c0e3-0058-49f8-bf96-5347aa16ac0c.png)

It runs when I modify target `10.0.22000.0` to `10.0.19041.0`.

```diff
- <TargetFramework>net6.0-windows10.0.22000.0</TargetFramework>
- <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
+ <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
+ <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
```

Currently, I submitted one 1-2 days ago with modification recommended by @Scottj1s . Its status is in Certification now. I will try to update this way to submit if that still fails.

**Comment by Richasy** [comment]
There doesn't seem to be a clear fix for this error. But that's also a risk if downgrading can fix it. As far as my personal development experience is concerned, Windows App SDK 1.0 has different performances on Win11 and Win10. For example, `AppWindowTitleBar` will return null on Win10 ([Platform options](https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#platform-options)). I noticed that in your screenshot, it seems that you use this feature. Maybe you can find a Win10 device to test it before publish

**Comment by kingcean** [comment]
Yes, that is why I target the app to `10.0.22000.0`. It can't customize/hide the app window in Windows 10. I have added code to catch that exception mentioned by you and it will have a default window title bar and a default icon (not the one of app). I am not sure if I can limit the OS versions by `TargetDeviceFamily`'s `MinVersion` in `Dependencies` section of `Package.appxmanifest` file.

**Comment by Scottj1s** [comment]
@kingcean, have you resolved everything reported in this issue?  Can we close it?

**Comment by kingcean** [comment]
@Scottj1s No, I am still trying to find the root cause and fix it.

**Comment by hez2010** [comment]
Seems that 1.0.2 may include the fix. Can you try updating to 1.0.2?

https://github.com/microsoft/WindowsAppSDK/releases/tag/v1.0.2

**Comment by kingcean** [comment]
@hez2010 Yes, I have also noticed that and have already updated to have a try. Thanks for your notice!

**Comment by kingcean** [comment]
Thanks for all your help and support! Especially @hez2010 @Richasy . Finally, the app has published (its first attempt of submission is on Mar 18th).

ms-windows-store://pdp/?productId=9NBLGGH4NBXB

The app is in Preview currently and obviously there is a long way to go. We can also see that Windows App SDK also needs to continue to improve and perfect as we can expect since it still has lots of issues and incomplete features (e.g. media player element which is required by iQIYI).

### Workaround

Let me summarize what I have done to work around this issue (one or more apply to).

Update reference `Microsoft.WindowsAppSDK` to the latest version in `ItemGroup` section of the project file (.csproj).

```diff
- <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.1" />
+ <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.2" />
```

Update `Package.appxmanifest` file to add reference to `Microsoft.VCLibs.140.00.UWPDesktop`.

```diff
<Dependencies>
-  <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.22000.0" />
-  <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.22000.0" />
+  <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.22000.0" MaxVersionTested="10.0.22000.0" />
+  <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.22000.0" MaxVersionTested="10.0.22000.0" />
+  <PackageDependency Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.30035.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
</Dependencies>
```

Rollback project file (.csproj) to make sure the TFM is not `net6.0-windows10.0.22000.0`. The modification is in its `PropertyGroup` section.

```diff
- <TargetFramework>net6.0-windows10.0.22000.0</TargetFramework>
- <TargetPlatformMinVersion>10.0.22000.0</TargetPlatformMinVersion>
+ <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
+ <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
```

Add following node in the project file (.csproj).

```diff
+ <Target Name="_RemoveFrameworkReferences" />
```

For reference, the app I am publishing includes customized window title bar (requires usage of `AppWindow`) and Edge WebView2.

**Comment by kingcean** [comment]
> > I am not sure if I can limit the use of the specific OS versions by `TargetDeviceFamily`'s `MinVersion` in `Dependencies` section of `Package.appxmanifest` file.
>
> You can. That will restrict installing your package on >=10.0.22000.0
> TFM controls .NET runtime, but you won't get that far if you restrict MSIX's install

No, it won't restrict in fact...

I have set the minimum version to Windows 11 (10.0.22000.0) in `TargetDeviceFamily` (both `Windows.Universal` and `Windows.Desktop`), but I can still install it on Windows 10 (10.0.19044.1645).

![image](https://user-images.githubusercontent.com/1724940/163409711-850eebd1-b3b7-472f-943f-0c5bf051ff7c.png)

There is an unexpected window title bar and the default icon (not the one of app), because window customization (referencing `AppWindow`) doesn't work on Windows 10. That's the reason I want to restrict the installation.
