### ISSUE TITLE
App will be Crash if Published as FrameworkDependent or Self-Contained

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#2347]
### Describe the bug

If the app is published as a FrameworkDependent or Self-Contained, it will crash and not run. but It runs without any problems in Visual Studio.

### Steps to reproduce the bug

1.Create a New WinUI 3 Project
2.Change To Unpackaged Project
`<WindowsPackageType>None</WindowsPackageType>`
3. Add InfoBar on MainWindow

```
<Window
    x:Class="App1.MainWindow">
    <StackPanel>
        <InfoBar
                        Title="Up To Date"
                        IsClosable="False"
                        IsOpen="True"
                        Severity="Success" />
    </StackPanel>
</Window>
```
4. Publish Project as FrameworkDependent or Self-Contained
5. Run Published App

### Expected behavior

app should run without any problems

### NuGet package version

1.0.0

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

nuget version:
WASDK 1.1.0-preview1
WASDK 1.0.1
WASDK 1.0.0

i uploaded a repro project, just publish and run it.
[App1.zip](https://github.com/microsoft/WindowsAppSDK/files/8397841/App1.zip)

**Comment by blake-fm** [comment]
My current "workaround" for this is setting PublishSingleFile to false (and adding numerous DLLs to my once-simple installer).  Only tested on 1.0.1, but builds publishes fine on Win11, and runs on Win11/Win10 21H2.

**Comment by ghost1372** [comment]
> My current "workaround" for this is setting PublishSingleFile to false (and adding numerous DLLs to my once-simple installer).  Only tested on 1.0.1, but builds publishes fine on Win11, and runs on Win11/Win10 21H2.

Did you test it with single **InfoBar** element on your window/page?

**Comment by blake-fm** [comment]
Nope.  Just did now, though - same result.  If you are getting different results, there may be something in my WinUI project template that could help.  Let me know, and I'll throw it somewhere.

**Comment by ghost1372** [comment]
Yes thank you, it will be helpful if you can upload your example

**Comment by blake-fm** [comment]
[InfoBarTest.zip](https://github.com/microsoft/WindowsAppSDK/files/8405779/InfoBarTest.zip)
Left the standard Assets folder out - hope this helps.

**Comment by ghost1372** [comment]
@blake-fm Thanks for your repo, I realized that the problem is with the PublishSingleFile = true
I will close this issue and create a new issue with correct detailed information
