### ISSUE TITLE
WinAppSdk is difficult to use with reg-free WinRT due to class/file naming, pairs

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#2352]
## Problem

Windows App SDK (WAS) 1.1-preview1 added the ability to ship as part of a _self-contained_ application. What this generally means is that WAS components are now activatable without registration (registration-free WinRT). Instead of relying on registration information stored in the Windows Registry, WAS tooling now/currently stuffs a large manifest into your app replicating that function.

To support this feature outside Visual Studio/Msbuild C++/C#, developers must:
* carefully author this manifest manually (or carry around a generic one and maintain it)
* distribute it with their app internally (as a manifest resource) or externally (my.exe.manifest)

To avoid manifestation altogether, projections such as C++/WinRT and C#/WinRT alternatively turn to a simple algorithm to locate activatable classes and their activation factory. These projections:
1. remove the class name (from the fully-qualified class name)
2. look for a library with that name
3. if that's not found, remove the most-specific segment name and repeat step 2

Unfortunately, WAS [does not adhere to best WinRT component naming practices](https://docs.microsoft.com/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt#naming-best-practice-for-windows-runtime-component-dlls). WAS files have unexpected names and/or host classes that don't have related namespaces.

Here's a snippet of what the class <-> file relationship looks like today:

| Library | Classes |
|---|---|
Microsoft.WindowsAppRuntime.dll | Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependency<br> Microsoft.Windows.ApplicationModel.DynamicDependency.PackageDependencyRank<br> Microsoft.Windows.System.EnvironmentManager<br>...|
Microsoft.UI.Xaml.dll | Microsoft.UI.Xaml.Controls.DragItemsStartingEventArgs<br> Microsoft.UI.Xaml.Controls.ItemClickEventArgs<br> Microsoft.UI.Xaml.Controls.SelectionChangedEventArgs<br> Microsoft.UI.Xaml.Controls.SemanticZoomViewChangedEventArgs<br> ...|
Microsoft.UI.Xaml.Controls.dll | Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider<br> Microsoft.UI.Xaml.Controls.XamlControlsResources<br> Microsoft.UI.Private.Controls.MUXControlsTestHooks<br> Microsoft.UI.Xaml.Controls.Primitives.CornerRadiusToThicknessConverter<br> Microsoft.UI.Xaml.Controls.Primitives.CornerRadiusFilterConverter<br>...|
WinUIEdit.dll | Microsoft.UI.Text.FontWeights<br> Microsoft.UI.Text.TextConstants<br>
Microsoft.Web.WebView2.Core.dll | Microsoft.Web.WebView2.Core.CoreWebView2ControllerWindowReference<br> Microsoft.Web.WebView2.Core.CoreWebView2Environment<br> Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions<br>
CoreMessagingXP.dll | Microsoft.UI.Dispatching.DispatcherQueue<br> Microsoft.UI.Dispatching.DispatcherQueueController<br>...|

[(The full table, as of 1.1-preview1, can be found here.)](https://gist.github.com/riverar/c58d6702903a6a0045a11a046701b569)

Observe in the above snippet:
* `Microsoft.WindowsAppRuntime.dll` hosts classes in the `Microsoft.Windows.ApplicationModel.*` and `Microsoft.Windows.System.*` namespaces
* Both `Microsoft.UI.Xaml.dll` and `Microsoft.UI.Xaml.Controls.dll` host classes in the `Microsoft.UI.Xaml.Controls.*` namespace
* `WinUIEdit.dll` hosts classes in the `Microsoft.UI.Text` namespace
* etc.

I explored the possibility of simply renaming the libraries to compatible names, but `Microsoft.UI.dll` and `Microsoft.UI.Xaml.dll` both contain types that would fail the aforementioned search algorithm.

## Considered workarounds/solutions

1. Rename all WAS libraries and move the classes to the right spots.
Requires WAS code change. Could be considered a major change (2.0).

2. Continue using the internal/external manifest.
This does not follow WinRT component recommendations, is generally non-idiomatic, and is unfriendly for some projections (e.g. Rust).

3. Change language projections to deal with non-ideal layout.
Requires all projections to change. Involves working with sensitive projection code.

   Projections could perhaps:
   * consume the manifest (oracle)
   * rename the libraries, creating a saner layout, adding numbers to "dupes" (e.g. UI.Xaml.1, UI.Xaml.2, ...)
   * adjust activation factory search algorithm as needed

4. Did I miss any?

**Comment by riverar** [comment]
Thanks, sounds like this is intentional then. Will close.

My guidance to language projection authors will be to embed the manifest (if they have the tooling to do so) or parse the manifest and bake the class id<->file map in. I'm working on the latter approach with the windows-app rust crate at the moment.

**Comment by DrusTheAxe** [comment]
> My guidance to language projection authors will be to embed the manifest (if they have the tooling to do so) or parse the manifest and deal with the class id<->file map at codegen time. I'm working on the latter approach with the windows-app rust crate at the moment.

I'd advise caution. The downside to the SxS manifest is the 'registration info' is separate from the implementation. Any changes to the implementation can impact the registration info, e.g. if v1.2.3 adds a new runtimeclass not in v1.2.2. If/when we use _internal_ runtimeclasses amongst WinAppSDK components not exposed as public APIs, you need to use the same registration info as the matching implementation. Incomplete or mismatched registration info vs runtime can produce 'undefined behavior'.

I forgot to ask but thanks for remining me...

>2. Continue using the internal/external manifest. This does not follow WinRT component recommendations

What WinRT component recommendations are you referring to? Got link?

>and is unfriendly for some projections (e.g. Rust).

Can you elaborate?

**Comment by riverar** [comment]
> I'd advise caution. The downside to the SxS manifest is the 'registration info' is separate from the implementation. Changes to the implementation can impact the registration info, e.g. if v1.2.3 adds a new runtimeclass not in v1.2.2. If/when we use _internal_ runtimeclasses amongst WinAppSDK components not exposed as public APIs, you need to use the same registration info as the matching implementation

I think you're warning folks to ensure they keep up on manifests. That's a fair warning and something I automate (for Rust). Every time I regenerate the crate for a major/minor/bugfix, we will retrieve a fresh copy. Sound good?

> What WinRT component recommendations are you referring to? Got link?

It's linked at the top, but easy to miss. [Here's another copy](https://docs.microsoft.com/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt#naming-best-practice-for-windows-runtime-component-dlls).

> Can you elaborate?

There's no easy/portable/idiomatic way to copy the manifest around (or embed it into the image) at this time. It's a known gap in the ecosystem right now. 😞

**Comment by DrusTheAxe** [comment]
> I think you're warning folks to ensure they keep up on manifests

More like not to forget the manifest is tightly coupled with and part of the implementation. If you're using WinAppSDK's nuget and MSbuild support ItJustWorks™. If you're coloring outside the lines make sure to color _all_ the lines ;-)

> Every time I regenerate the crate for a major/minor/bugfix, we will retrieve a fresh copy. Sound good?

Yes. Just noting as the manifest is something easily overlooked.

> [Here's another copy](https://docs.microsoft.com/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt#naming-best-practice-for-windows-runtime-component-dlls). (Admittedly, this is in the context of C++/WinRT, which you addressed above.)

Thanks! I see that doesn't mention the complex case or the namespace-depth concern. We should correct that. And by we I mean...

@BenJKuhn we should expand the guidance for the complex cases (like WinAppSDK :-) that don't fit so well with the simple filename/lookup scheme. https://task.ms/38821629

> There's no easy/portable/idiomatic way to copy the manifest around (or embed it into the image) at this time. It's a known gap in the ecosystem right now. 😞

Which ecosystem, Rust or Windows?

**Comment by kennykerr** [comment]
I'm not sure how helpful it would be to update the docs to cover WinAppSDK's implementation details - I can't imagine we'd really recommend anyone else building something this complex as a best practice, which is what the docs are talking about.

**Comment by riverar** [comment]
> Which ecosystem, Rust or Windows?

Rust.

**Comment by DrusTheAxe** [comment]
> I'm not sure how helpful it would be to update the docs to cover WinAppSDK's implementation details

Not the ask. WinAppSDK is merely an instance of a complex implementation not served as well by the manifest-free guidance as a manifested one. We should document guidance for component authors not in the 'simple' case.

>I can't imagine we'd really recommend anyone else building something this complex as a best practice

Office. Photoshop. SAP. Lots other realworld codebases don't fit so well in the manifest-free model. I'm not saying we recommend developers write complex systems but it happens. When they do, we should have guidance (other than "rewrite your complex implementation to fit the manifest-free model").

**Comment by DrusTheAxe** [comment]
> > Which ecosystem, Rust or Windows?
> 
> Rust.

:-(

Rust crates have no convention for it? Yet? ;-)

**Comment by kennykerr** [comment]
https://github.com/rust-lang/cargo/issues/9661

**Comment by Lexikos** [comment]
> Your option #1 assumes resolution C.

Is there some reason that resolutions A and B wouldn't work just as well with option 1 as with the existing layout? If I understand correctly, the manifest avoids the need to crawl the filesystem, regardless of whether the class/file relationship supports registration-free activation or not. In other words, resolution C carries the performance penalty, not option 1.

> ... you *can't* put runtime `A.Foo` in just any file. 

Is that the class implementation, the activation factory for that class, the metadata...?

My understanding is that registration-free activation finds the DLL by relying on a naming convention, loads it and calls the DllGetActivationFactory entry point to get an activation factory. So the only real requirement is that the DLL is able to locate the activation factory for the given runtime class. The class implementation itself can be anywhere. Even the activation factory can be implemented elsewhere, as long as the entry point knows how to locate it. The DLL could be just a stub used for registration-free activation, perhaps comparable to an [API set](https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-apisets).

However, I'm likely missing something. For instance, I don't know how the metadata is located for a third-party component.
