### ISSUE TITLE
Multi-window still broken on some systems

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#2363]
### Describe the bug

With v1.0.1 and 1.1.0-preview we are supposed to be able to use multiple windows. This seems to work well on my Windows 11 PC, as well as a co-workers Win10 PC, but my Win10 PC this is crashing on, the moment the second Window constructor is hit.

### Steps to reproduce the bug

1. Clone WinUIEx: https://github.com/dotMorten/WinUIEx/
2. Run the sample app in the solution.
3. Notice the app will crash once it hits the constructor of MainWindow (because the splashscreen window is already loaded).

This doesn't happen on all PCs. Only some.

### Expected behavior

Multi-window support works on all devices.

### Screenshots

![image](https://user-images.githubusercontent.com/1378165/161647344-2f70eb74-e471-45ea-bfe4-b0fe9b83af2e.png)

### NuGet package version

1.0.1 and 1.1.0-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### Additional context

Dump: http://omds.xaml.dev/WinUIExSample_dump.zip

**Comment by riverar** [comment]
Howdy friend 👋,

Your packaging project is deploying mismatching 1.0 bits. (I'm not sure why this isn't computed automatically from the linked projects to prevent this from happening.)

```xml
<PackageReference Include="Microsoft.WindowsAppSDK" Version="[1.0.0]">
  <IncludeAssets>build</IncludeAssets>
</PackageReference>
```

Afterwards, you will then need to apply my fine fix to `SetTitleBarBackgroundColors`, as the `TitleBar` property is not supported in Windows 10:

```csharp
public static void SetTitleBarBackgroundColors(this Microsoft.UI.Xaml.Window window, Windows.UI.Color color)
{
    //var appWindow = window.GetAppWindow();
    //appWindow.TitleBar.ButtonBackgroundColor = color;
    //appWindow.TitleBar.BackgroundColor = color;
    //appWindow.TitleBar.ButtonInactiveBackgroundColor = color;
    //appWindow.TitleBar.ButtonPressedBackgroundColor = color;
    //appWindow.TitleBar.InactiveBackgroundColor = color;
}
```

**Comment by dotMorten** [comment]
@riverar Good find on the reference in the packaging project. I did miss that (and that gets me again started on that it shouldn't be necessary to reference this yet again in the packaging project but that's a different issue I've already beaten the dead horse on numerous times). That does oddly enough fix the issue. What is really weird though is that it still works on some PCs, just not this one PC. Perhaps it is because it never actually ran a WinUI 3 app before, so it is deploying 1.0.0, where other PCs already got 1.0.1 installed?
