### ISSUE TITLE
Admin Elevation does not work form Standard user nor User with Admin only built in Administrator (WASDK 1.1 preview) when deployed from vs

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/WindowsAppSDK#2371]
### Describe the bug

As in the title, when i install my app on standard user or user with Admin privileges it prompts me for password but upon entering it i get an error:

![image](https://user-images.githubusercontent.com/5243438/162203848-9103c542-7b07-4e8f-b0d7-70de8b9cf2bf.png)

What is win 11.

### Steps to reproduce the bug

create single package winui 3 app and use windows apps sdk 1.1 preview 

in app.manifest use
				<requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />

in package.appxmanifest use

  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
	<rescap:Capability Name="allowElevation" />
  </Capabilities>

deploy package using vs and start it form start menu

### Expected behavior

it should be possible to run the app from Standard user and user with admin accounts upon entering password for Administrator

**Comment by alexlamtest** [comment]
@KWodarczyk - Thank you very much for your interest in WASDK and reporting this issue! Assuming that you can still reproduce this issue, can you please use the Feedback Hub app to capture diagnostic information? Please select Category: Developer Platform -> App Deployment. Hit the Start Recording button, then reproduce the error.
Can you please also clarify your scenario, either here or in the feedback item that you will be filing? Are you installing your package as Standard user (User X) and expecting it to run As Admin User (User Y)?
Thanks!

**Comment by KWodarczyk** [comment]
_Are you installing your package as Standard user (User X) and expecting it to run As Admin User (User Y)?_ 
That is right, but im doing it from vs (deploy) it works fine when i create a package and install it manyally.

**Comment by alexlamtest** [comment]
@KWodarczyk - Have you captured logs using Feedback Hub? If so, did you use the same title as this issue? Thanks.

**Comment by KWodarczyk** [comment]
I have not captured the feedback because sending it would be against my company rules. I will try to do it using dummy app.

**Comment by KWodarczyk** [comment]
Ok I just new up new winui3 single msix project with both manifest settings as in description, deployed to remote machine on user account and same error happens so it very easy to reproduce

**Comment by alexlamtest** [comment]
@KWodarczyk - We apologize for the slow reply. There appears to be two ways to move forward. It would be great if both ways work for you, but even if only one is workable, we might still be able to make progress. 

1. Given that it's "easy to reproduce" for you, can you please send us the "winui3 single msix project" and related artifacts, together with **step-by-step instructions on how to reproduce the issue on our side**?
2. It's hard to enumerate all information that Feedback Hub collects here. An alternative is that we can give you a list of files under C:\Windows\System32\winevt\Logs and C:\ProgramData\Microsoft\Windows\AppRepository to capture from the repro machine? We can't be sure if such little information is sufficient for troubleshooting the issue at hand, but we are happy to give this a try.

Please let us know. Thank you.
