### ISSUE TITLE
Unable to download SDK of Version 1.0.2

### ISSUE THREAD

**Issue by zwlms** [microsoft/WindowsAppSDK#2385]
link https://aka.ms/windowsappsdk/1.0/1.0.2/vsix-2022-cpp It is displayed as CPP(C++) vsix, and the actual downloaded file is CS(C#) instead of CPP(C++).

**Comment by riverar** [comment]
@BenJKuhn Can you help escalate? (I don't mean _now_ during the weekend, of course.)

**Comment by riverar** [comment]
@jonwis @Scottj1s @DrusTheAxe @gabbybilka <taps mic> Hey guys, customers can't download 1.0.2 bits.

**Comment by jonwis** [comment]
Ack. Hunting around, I'll see if I can at least get you a downloads.microsoft.com direct link while we fix the aka.ms ones.

**Comment by jonwis** [comment]
Ok, until we fix the aka.ms link, use https://download.microsoft.com/download/2/c/9/2c97d019-e075-490b-80eb-631b64db61f2/WindowsAppSDK.Cpp.Extension.Dev17.Standalone.vsix instead.

**Comment by angelazhangmsft** [comment]
Thanks for reporting the issue, the link has been updated.
