### ISSUE TITLE
IsSelfContained() returns true even after runtime is installed

### ISSUE THREAD

**Issue by loneursid** [microsoft/WindowsAppSDK#2400]
### Describe the bug

In WAS v1.1 Preview2, IsSelfContained() returns true even after runtime is installed.

### Steps to reproduce the bug

Using this sample: https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Notifications/Push/cpp-console-unpackaged

1. Upgrade it to Preview2 (setup nuget and run the installer)
2. Run the sample. 

Observed: There was an error obtaining the WNS Channel URI

### Expected behavior

A message like this: The remoteId has not been set. Refer to the readme file accompanying this sample\nfor the instructions on how to obtain and setup a remote id.

which would indicate that the function failed but for an expected reason, not because it thinks the app is self contained.

### Packaging type

Unpackaged

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2019

### Additional context

this was discovered in v1.1 Preview2 but the selection isn't available yet, it seems.

**Comment by BenJKuhn** [comment]
Internal tracking:
https://task.ms/39088344

**Comment by DrusTheAxe** [comment]
The root problem is IsSelfContained refers to the framework's packagefamilyname at compile-time, but it's not defined until later (higher) in the Aggregator build pipeline. Solving this requires replacing the compile-time constant with a runtime lookup.

See [Fix IsSelfContained() to lookup framework packagefamilyname at runtime #2411](https://github.com/microsoft/WindowsAppSDK/pull/2411) for more details
