### ISSUE TITLE
ResourceLoader can not load the specified resource

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#2406]
### Describe the bug

i have multiple resources (resw) files 
![Untitled](https://user-images.githubusercontent.com/9213496/163683630-29591007-2bf3-4ec5-aec3-a7ea38e684b7.png)

i can load resources from **Resources.resw** file with this code:
`myButton.Content = new ResourceLoader().GetString("String1");`

but i can not load resources from **ErrorMessage.resw** file, i used this code:
`myButton.Content = new ResourceLoader("ErrorMessage").GetString("msg");`

but i get exception:
Exception thrown at 0x76C8ED42 (KernelBase.dll) in App15.exe: WinRT originate error - 0x80070002 : 'The system cannot find the file specified.'.

In this case, using the following namespace works without any problems
`myButton.Content = Windows.ApplicationModel.Resources.ResourceLoader.GetForViewIndependentUse("ErrorMessage").GetString("msg");
`

### Steps to reproduce the bug

1.Create a new WinUI 3 Project
2.Create multiple Resource file
3. try to load resource from resw files.
4. you should use **Microsoft.Windows.ApplicationModel.Resources** 

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by huichen123** [comment]
can you do:
myButton.Content = new ResourceLoader("resources.pri", "ErrorMessage").GetString("msg");

**Comment by riverar** [comment]
@axelandrejs Not sure this is ready to close. It seems like there's still a bug here?

**Comment by axelandrejs** [comment]
There are two constructors. One takes the file path, one the file path and the scope. You can't instantiate for a scope without also specifying the file. As such I don't think there is a bug here.

**Comment by riverar** [comment]
@axelandrejs Not sure what that means.

I think there are a few bugs here interacting with each other.

1. User has a file named `ErrorMessage.resw`. They are constructing a `ResourceLoader` with a filename as input using the constructor `ResourceLoader(string fileName)`.

The documentation indicates that an input of `ErrorMessage` will result in attempting to load `ErrorMessage.resw`, but that's not the case. It will attempt to load `ErrorMessage` (no extension) and fail.

2. This constructor doesn't seem to support loading resw files to begin with. If I drop that .resw into the target directory and attempt to load it, it results in an exception `System.Runtime.InteropServices.COMException: 'Invalid PRI File. (0x80073B16)'`

Highly related: https://github.com/microsoft/WindowsAppSDK/issues/1872

**Comment by axelandrejs** [comment]
Nothing can load resw files in the resource loader. It always loads pri files that were constructed from resw. The resw files are purely a build-time artifact. I'll see about making the documentation more clear on this point.

**Comment by huichen123** [comment]
@stevewri the doc is not correct. The fileName should be PRI file name. The doc seems to have incorrectly copied the comments for resourcemap name from the UWP counterpart (https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.resources.resourceloader.-ctor?view=winrt-22000).

**Comment by Balkoth** [comment]
This is highly confusing. My guess is that the filename, currently created as `resources.pri` is an implementation detail that can change anytime.

As `new ResourceLoader()` already loads a ResourceMap named `Resources.resw`, there should be a constructor that just takes the filename of the resw file you want to load.

I do not think that this is really what has to be used, if you want to load resources from that file programmatically?
![image](https://user-images.githubusercontent.com/80055480/184141538-2bd4360a-b895-4fb5-9e6e-20dbabcad79c.png)

![image](https://user-images.githubusercontent.com/80055480/184141704-5ad37aab-43a1-4db6-98df-b2018c2d9792.png)

**Comment by axelandrejs** [comment]
Internally, the .resw files are translated into resource maps, which are segments of the URI that describes the resource. So ErrorMessages.resw would translate to ms-resource://<app name>/ErrorMessages/<the string>

The default constructor of the resource loader always loads the hard-coded "Resources" resource map. This is to keep parity with the OS-provided version of MRT. The constructor that takes a resource map opens the file at the root then opens the specified resource map:

ResourceLoader::ResourceLoader(hstring const& fileName, hstring const& resourceMap)
{
    winrt::check_hresult(MrmCreateResourceManager(fileName.c_str(), &m_resourceManager));
    winrt::check_hresult(MrmGetChildResourceMap(m_resourceManager, nullptr, resourceMap.c_str(), &m_currentResourceMap));
    SetDefaultContext();
}

There is also the ResourceManager API, which is a more advanced version of the ResourceLoader. It will give you the root of the resources which you can then manually walk as needed.

**Comment by Balkoth** [comment]
And this information helps for what?

**Comment by RGarrido03** [comment]
I'm facing the same issue. I think that at least the docs should be rewritten, since following its steps lead to this bug.
