### ISSUE TITLE
Dotnet build fails for self contained application

### ISSUE THREAD

**Issue by lhak** [microsoft/WindowsAppSDK#2427]
### Describe the bug

Setting WindowsAppSDKSelfContained to true results in dotnet build failing:

Microsoft.WindowsAppSDK.SelfContained.targets(235,5): error MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild.

### Steps to reproduce the bug

Use dotnet build with a self contained application in 1.1 preview 2.

### Expected behavior

Should work

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Other

**Comment by hez2010** [comment]
You cannot use dotnet cli to build a WinUI app. Instead you should use Visual Studio or msbuild.

**Comment by LoopedBard3** [comment]
My team is also hitting this when trying to build/publish dotnet maui for windows desktop. This includes with both dotnet publish and dotnet msbuild. The full error message we receive is:
```
C:\Users\user\.nuget\packages\microsoft.windowsappsdk\1.1.0-preview2\buildTransitive\Microsoft.WindowsAppSDK.SelfContained.targets(235,5): error MSB4801: The task factory "CodeTaskFactory" is not supported on the .NET Core version of MSBuild. [C:\Users\user\Desktop\performance\src\scenarios\mauidesktop\app\MauiDesktopTesting.csproj]
C:\Users\user\.nuget\packages\microsoft.windowsappsdk\1.1.0-preview2\buildTransitive\Microsoft.WindowsAppSDK.SelfContained.targets(235,5): error MSB4175: The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Program Files\dotnet\sdk\6.0.300\Microsoft.Build.Tasks.Core.dll". The task factory must return a value for the "TaskType" property. [C:\Users\user\Desktop\performance\src\scenarios\mauidesktop\app\MauiDesktopTesting.csproj]
```
However, as stated above, switching over to the visual studio install of msbuild succeeds. I can provide a binlog if that is something that would be helpful.

**Comment by mikebattista** [comment]
+@manodasanW I believe we identified the problem and have a fix in place for 1.1.

**Comment by manodasanW** [comment]
Yes, this is resolved in 1.1 by instead using RoslynCodeTaskFactory.

**Comment by LoopedBard3** [comment]
It is great to see this resolved! What do I need to do to take advantage of this locally? Do I need to install it or can it be pulled down with dotnet restore? Thanks.

**Comment by LoopedBard3** [comment]
@manodasanW ^

**Comment by mikebattista** [comment]
You'll need to update to the 1.1 WinAppSDK NuGet package when that ships soon.
