### ISSUE TITLE
App crash while dragging to 2nd display (1.1.0-preview2)

### ISSUE THREAD

**Issue by ParkhutRoman** [microsoft/WindowsAppSDK#2438]
### Describe the bug

onecoreuap\windows\moderncore\inputv2\inputhost\outside\lifted\contentappwindowbridge.cpp(803)\Microsoft.UI.Input.dll!00007FFAC07A343D: (caller: 00007FFAC07A36A9) FailFast(1) tid(7fd0) 8000FFFF Catastrophic failure

### Steps to reproduce the bug

drag app to 2nd display 
![image](https://user-images.githubusercontent.com/12161245/165021410-23bc1c51-7836-4a68-a792-3a9f799321fb.png)

### Expected behavior

DOnt crash )

### Screenshots

![image](https://user-images.githubusercontent.com/12161245/165021343-1b4e65c3-b17c-47aa-bf0e-5089d4a9a2e6.png)

### NuGet package version

1.1.0-preview2

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

### Additional context

Edition	Windows 11 Pro
Version	22H2
Installed on	‎16.‎04.‎2022
OS build	22598.200
Experience	Windows Feature Experience Pack 1000.22598.200.0

**Comment by jeffstall** [comment]
Hi @ParkhutRoman,

Thanks for reporting this issue! The problem occurs when a window's orientation of a monitor changes. In this case, the window is being moved from a landscape monitor to a portrait monitor (or vice-versa). It would also occur if just changing the monitor's orientation. We are looking at fixing this in a future release, and we'll update this post when we have more information.

Thanks!
~ Jeffrey

**Comment by jeffstall** [comment]
This issue has been fixed with WinAppSDK 1.1.
