### ISSUE TITLE
1.1.0-preview2 "This version of WindowsAppSDK requires WinRT.Runtime.dll version 1.6 or greater." error even with latest SDK installed

### ISSUE THREAD

**Issue by MGRussell** [microsoft/WindowsAppSDK#2439]
### Describe the bug

The error about requiring an updated .NET SDK "This version of WindowsAppSDK requires WinRT.Runtime.dll version 1.6 or greater. Please update to .NET SDK 6.0.104, 6.0.202, 5.0.213 or **5.0.407** (or later)." is thrown when these are my current installed SDKs:

dotnet --list-sdks
**5.0.407** [C:\Program Files\dotnet\sdk]
6.0.101 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
6.0.300-preview.22204.3 [C:\Program Files\dotnet\sdk]

This is in a project targeting .NET 5 with a fresh install of Visual Studio with all prerequisites for WinUI development installed.

The alternative workaround specified in the error message (adding a WindowsSdkPackageVersion PropertyGroup item does work, but should not be necessary.

### Steps to reproduce the bug

Create a new project using the "Blank App, Packaged (WinUI 3 in Desktop)" template.

Build.

### Expected behavior

The project should detect that I have the necessary version of the .NET SDK installed.

### NuGet package version

1.1.0-preview2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2019

**Comment by ParkhutRoman** [comment]
My be VS2019 have old template, have you tried `<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>` ?
VS 2022 new project starting with preview2 without problem.  [CrashTest.csproj pastebin](https://pastebin.com/VGibWt4f)

**Comment by sigmarsson** [comment]
I also witnessed this on VS2022 and installed the RT as Nuget as `Microsoft.Windows.CsWinRT 1.6.1`

**Comment by manodasanW** [comment]
@MGRussell I believe what is going on is that Visual Studio detects the latest version of the .NET SDK that you have installed and uses that up to build you program.  In the case of VS 2019, I believe it is picking up `6.0.200` as the latest version (ignoring the preview version).  This version doesn't have `WinRT.Runtime 1.6`, but rather the `6.0.202` servicing update does.  VS picks up this SDK version even though you technically have a later servicing version of the .NET 5 SDK (`5.0.407`) installed with `WinRT.Runtime 1.6` as it treats the .NET 6 SDKs as newer versions than the .NET 5 SDKs and the .NET 6 SDKs are capable of building .NET 5 targeted projects.

When you used VS 2022, I believe it used the preview version of the .NET `6.0.300` SDK that you have installed which does have `WinRT.Runtime 1.6` and thereby you did not see the issue there.

Can you try updating your .NET 6 SDK to the latest (`6.0.202`) and see if that resolves your issue with VS 2019?

@sigmarsson you might be running into the same issue.

**Comment by riverar** [comment]
I think the onus is on Windows App SDK to not use SDKs that are not compatible. There's also a separate issue where servicing releases of 0.x, 1.x are introducing breaking SDK changes because of this behavior.

In other words, WAS probably need to ship with a `global.json` to stabilize which .NET SDKs are supported.

**Comment by MGRussell** [comment]
@manodasanW That does seem to be the issue, but I'm inclined to agree with @riverar as to whether this is a solution, so I'll leave this issue open and to the discretion of maintainers.

**Comment by sigmarsson** [comment]
@manodasanW I tried; VS2022 17.1.5 requires the Nuget package installed even with .NET7 preview, .NET 6.0.202.


![image](https://user-images.githubusercontent.com/43340959/165242983-65ac879e-0e6c-4045-8bc0-8897434e333e.png)

**Comment by minze-it** [comment]
Had the same problem - Check the content of your .csproj-file (i.e. Weather.History.Windows.Desktop) and change the line
`<WindowsSdkPackageVersion>10.0.XYZ.23</WindowsSdkPackageVersion>`
to
`<WindowsSdkPackageVersion>10.0.XYZ.24</WindowsSdkPackageVersion>`

**Comment by sigmarsson** [comment]
@minze-it  , true. Have increased and problem vanished.
