### ISSUE TITLE
Unable to submit a WinUI3 app to the Microsoft Store

### ISSUE THREAD

**Issue by jevonsflash** [microsoft/WindowsAppSDK#2448]
### Describe the bug

I have a simple application that relies on WindowsAppSdk , it work well on my PCs, it tested on both windows 10 and windows 11. when i submit it to Mircrosoft Store , It was rejected for the following reasons:

"App Policies: 10.2.4 Security - Software Dependencies
Notes To Developer
Products may depend on non-integrated software (such as another product or module) to deliver primary functionality only as long as the additional required software is disclosed within the first two lines of the description in the Store.

.NET Framework 6.0
Tested Devices: Dell Latitude 5480, Microsoft Surface Laptop"

and

"Notes To Developer
The product crashes at launch on a device which installed .NET Framework 6.0. "

what dose  .NET Framework 6.0. means?
I've been rejected again and again several times, and now I don't know what to do.

### Steps to reproduce the bug

1. Create a simple application with WinUI3 
2. Submit the application to the Microsoft Store.
3. it been rejected

### Expected behavior

NuGet package version is 1.0.3 which i didn't see it in selection below

### Screenshots

![8a98299ce330137c67bb7d6377f0907](https://user-images.githubusercontent.com/11273359/165737357-73cf6d39-c439-498e-90c4-563e486fac66.jpg)

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000), Windows 10 version 21H2 (19044, November 2021 Update), Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2022-preview

**Comment by BenJKuhn** [comment]
Thanks for submitting this issue. Is there anything else we should know about your app and how it uses .NET 6? Are you including the .NET runtime in the MSIX package? Can you provide the exact version of .NET that you're using?

Ben

**Comment by jevonsflash** [comment]
@BenJKuhn  Hi， I have set the generate application bundle to "always" in the Create app program , I only see a Microsoft.WindowsAppRuntime.Bootstrap.dll in msix package's runtime folder , here is msix's content looks like:
![image](https://user-images.githubusercontent.com/11273359/166390728-e5ff9935-9afb-4a57-84b4-0e81a39f4032.png)

and AppxManifest.xml:

![image](https://user-images.githubusercontent.com/11273359/166390863-580d8729-e666-480d-bfc7-a932cf218728.png)

im using the dotnet version 6.0.300-preview.22204.3
Is there anything else I can provide?

**Comment by hez2010** [comment]
Are you using WASDK 1.0.3?

**Comment by jevonsflash** [comment]
> ~Are you using WASDK 1.0.3?~ Can you try the workaround [#2346 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/2346#issuecomment-1098684991)?

ok,  switched the .NET version back to 6.0.202 and recompiled the MSIX package as he didhttps://github.com/microsoft/WindowsAppSDK/issues/2346#issuecomment-1098684991,  I am now waiting for the Microsoft review result

**Comment by jevonsflash** [comment]
> > ~Are you using WASDK 1.0.3?~ Can you try the workaround [#2346 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/2346#issuecomment-1098684991)?
> 
> ok, switched the .NET version back to 6.0.202 and recompiled the MSIX package as he did [#2346 (comment)](https://github.com/microsoft/WindowsAppSDK/issues/2346#issuecomment-1098684991), I am now waiting for the Microsoft review result

Microsoft told me the answer was no：
![b874e1c21236a9a7ed999191c5b0d82](https://user-images.githubusercontent.com/11273359/166937794-9df08c64-ca81-4635-936a-e2a3da820332.jpg)
It kept saying my products may depend on  .Net Framework 6.0 which I didn't declare it in description of Store.

**Comment by hez2010** [comment]
How did you publish and package your app? I think the .NET 6 runtime may be absent in your package.

**Comment by jevonsflash** [comment]
> How did you publish and package your app? I think the .NET 6 runtime may be absent in your package.

i I set the generate bundle to "always" ， which is follow Microsoft documentation. Is the.NET 6 runtime completely packaged into the msix or just declare it in somewhere of mainifest.

back to the .NET Framework era, the system would pop up an installation window asking users to install the runtime

**Comment by jevonsflash** [comment]
I've been struggling with this for a month and haven't figured out what the problem really is.  I'm going to public the MSIX package，let you see what's wrong with it .
[QinuFileUploader_1.0.0.0_x64.zip](https://github.com/microsoft/WindowsAppSDK/files/8636987/QinuFileUploader_1.0.0.0_x64.zip)

**Comment by hez2010** [comment]
Apparently the .NET 6 runtime doesn't get packaged into the msix. Can you post your csproj file?

**Comment by jevonsflash** [comment]
> Apparently the .NET 6 runtime doesn't get packaged into the msix. Can you share your csproj file and publish profiles (in Properties\PublishProfiles)?

Ok, i have open source the project, check it please
https://github.com/MatoApps/QinuFileUploader

**Comment by hez2010** [comment]
I'm not able to reproduce your issue. 
Are you using the Publish -> Pack workflow in VS for packaging? The size of misx package should be about 52mb with Release config.

![image](https://user-images.githubusercontent.com/14960345/167061735-2876aadd-9b35-449d-bda7-6729a4c7df23.png)

**Comment by jevonsflash** [comment]
Yes, there must be something wrong with my environment. After I re-installed VS on another computer, the package is exactly 53M instead of 9M i uploaded before. I submitted it to the App Store again and waited for the result.  If pass, I will close the question. 
Thank you for your help.
@hez2010 Thank you very much

**Comment by jevonsflash** [comment]
Yes, there must be something wrong with my environment. After I re-installed VS on another computer, the package is exactly 53M instead of 9M i uploaded before. I submitted it to the App Store again and waited for the result.  If pass, I will close the question. 
Thanks for inspire help @hez2010

**Comment by jevonsflash** [comment]
The store passed my submission , but the app didn't run, reported the error: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)

I have added a reference to Microsoft.VCLibs.140.00.UWPDesktop in the Package manifest, I tested that whether it is added or not, the packaged size is the same (53M)

I tried to use local running (pagacked) is no problem, if I use unpacked will report that error, 
![image](https://user-images.githubusercontent.com/11273359/167234140-df6fed47-4096-439f-a671-d2790ca5256f.png)

Isn't it uploaded to the store is packaged one?, it is confused
