### ISSUE TITLE
Unpackaged C# WinAppSdk 1.0.3 app crashes when RivaTuner Statistics server app running

### ISSUE THREAD

**Issue by stefansjfw** [microsoft/WindowsAppSDK#2468]
### Describe the bug

Following https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app
for C# unpackaged app I get:
```
The program '[20148] App6.exe' has exited with code 3221226107 (0xc000027b)
```
while trying to run the app and RivaTuner Statistics server app is running ( installed together with MSI afterburner https://www.msi.com/Landing/afterburner/graphics-cards):
![image](https://user-images.githubusercontent.com/57057282/166676675-681a7c10-439d-4910-999e-5e3ae12902c6.png)

When I set Application detection level to None 
![image](https://user-images.githubusercontent.com/57057282/166676778-c9520086-d5d3-45a8-a969-3b59dc98cea7.png)

App starts as expected:
![image](https://user-images.githubusercontent.com/57057282/166676822-a0141d1d-1eab-4df4-9657-e9ec999c24b5.png)

Tried with both Winappsdk 1.0.2 and 1.0.3

### Steps to reproduce the bug

1. Create Blank App, Packaged (WinUI 3 in Desktop) in VS
2. Add <WindowsPackageType>None</WindowsPackageType>
to csproj file
3. Change running profile to App(Unpackaged)
4. try running the app - observe crash
5. Close (or set application level to None) RivaTuner app
6. Try running app again - observe it's working

### Expected behavior

App is running without crash

### Packaging type

Unpackaged

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2022

**Comment by ShashankNay** [comment]
There seems to a bug in the RTSS hook process that affects WinUI apps. The hook process returning 1 on a CreateWindow call prevents creation of the window. This is manifesting itself in a ‘Module Not Found’. I suggest following up with Riva Tuner.

**Comment by riverar** [comment]
Common bug with RivaTuner. If you need help excluding particular apps, this may help https://github.com/File-New-Project/EarTrumpet/issues/1092#issuecomment-1070843085

**Comment by beeradmoore** [comment]
Hey @stefansjfw , I was never able to replicate this but does this still break for you?

RTSS put out an [update](https://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html) which should handle this better but I am still getting some users having the issue even with the updated RTSS.

**Comment by LegendaryBlair** [comment]
This was an issue on RivaTuner tool, hence closing this issue.

**Comment by beeradmoore** [comment]
Leaving this info here incase others need it.

If you get your WindowsAppSDK to build with NativeAOT you can in theory add dllexport tags (or include the result of [this C file](https://github.com/beeradmoore/dlss-swapper/blob/main/extras/RTSSHooksCompatibility/RTSSHooksCompatibility.c)) (I forget how) which would then result in any WindowsAppSDK app being ignored by RTSS without needed explicit exclusions from it.
