### ISSUE TITLE
Content items now fail to deploy with v1.1.0-preview3

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#2473]
### Describe the bug

When having assets in a packaged WinUI 3 app, the following error is generated:
> Error	NETSDK1022	Duplicate 'Content' items were included. The .NET SDK includes 'Content' items from your project directory by default. You can either remove these items from your project file, or set the 'EnableDefaultContentItems' property to 'false' if you want to explicitly include them in your project file. For more information, see https://aka.ms/sdkimplicititems. The duplicate items were: 'Assets\image.png'	App2	C:\Program Files\dotnet\sdk\6.0.300-preview.22204.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.Shared.targets	213	

### Steps to reproduce the bug

1. Create a new WinUI 3 with separate packaging project.
2. Add an `Assets` folder to the app project, and add an image to that folder.
3. Verify that the projects builds and runs fine.
4. Upgrade the two projects to reference `v1.1.0-preview3` instead
5. Observe the above invalid build error.

Sample project:
[App2.zip](https://github.com/microsoft/WindowsAppSDK/files/8627352/App2.zip)

### Expected behavior

Build succeeds

### NuGet package version

1.1.0-preview3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022-preview, Visual Studio 2022

### Additional context

1.1.0-preview2 doesn't have this behavior.

**Comment by hez2010** [comment]
Known issue, see workaround here: https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#other-known-limitations

**Comment by dotMorten** [comment]
Aaah you’re right. I misread how that bug was described, but re-reading it I see that now
