### ISSUE TITLE
Notifications needs elevation checks

### ISSUE THREAD

**Issue by pmpurifoy** [microsoft/WindowsAppSDK#2506]
### Describe the bug

- For unpackaged applications using PushNotifications, it is unable to CoCreateInstance the PushNotificationsLongRunningProcess which crashes the application
- AppNotifications are unable to correctly route an AppNotification activation to both unpackaged/packaged applications that are elevated.

### Steps to reproduce the bug

Run an unpackaged application using WindowsAppSDK and call into PushNotificationManager::Register. This leads to crash with error code CLASS_NOT_REGISTERED.

Run an unpackaged/packaged application using WindowsAppSDK and call into AppNotificationManager::Show and click on the AppNotification. It will launch a second instance of the app instead of being routed to the first instance.

**Comment by robertzhou-wpn** [comment]
done
