### ISSUE TITLE
Custom TitleBar is not working in RTL

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#2518]
### Describe the bug

i used Custom titlebar from here
https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#platform-options

now if we change App Language to RTL, Custom Titlebar is not working (Window can not be dragged and Close Button is not work)

### Steps to reproduce the bug

1.Create custom titlebar in RTL app

### NuGet package version

1.1.0-preview3

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by riverar** [comment]
@ghost1372 Can you provide a reproducible example? What language are you targeting?

This works for me on `1.1.0-preview1`, albeit on 25115. Trying 22000 now.
![image](https://user-images.githubusercontent.com/475132/168661858-bec61e88-4dff-4410-841b-2cf33552bc8a.png)

**Comment by ghost1372** [comment]
Hi @riverar 
please test with 1.1.0-preview3
![Animation](https://user-images.githubusercontent.com/9213496/168765623-3aff219a-abbc-4893-9df9-04072e54b430.gif)

[App25.zip](https://github.com/microsoft/WindowsAppSDK/files/8706523/App25.zip)

**Comment by riverar** [comment]
OK, this is more of a problem with the sample code at https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk#interactive-content. Can confirm it's broken and incorrectly assumes LTR layout.

Adding @rkarman @BenJKuhn

**Comment by mevey** [comment]
We've verified this bug and logged it here http://task.ms/39695482. We will add it as part of v1.2 planning.

**Comment by riverar** [comment]
Hope it is considered for servicing as it impacts global readiness.

**Comment by mevey** [comment]
Yes, this we will consider servicing the fix in in-market releases.

**Comment by riverar** [comment]
@mevey Great news, thanks for closing the loop!

**Comment by jamers99** [comment]
@mevey or @riverar do you think this will fix #2953?

**Comment by riverar** [comment]
@jamers99 The bug described here was ultimately a problem with the sample in the docs, so no don't think any changes here will fix that sadly.

**Comment by jamers99** [comment]
@riverar should this be closed then?

**Comment by riverar** [comment]
@jamers99 Doesn't look like the sample was updated yet, so think it needs to remain open. @mevey may have more info.

**Comment by jamers99** [comment]
@riverar thanks for the insight, makes sense. Do you have any idea if I should keep #2953 or microsoft/microsoft-ui-xaml#7392? How should I go about getting more priority for it? It's a big deal for our tab based app. Unless we find a workaround, I think it's a stopper.

**Comment by riverar** [comment]
@jamers99 I'd keep both, just to have data on how inattentive Microsoft is in the Microsoft UI XAML repository. I'll take a look at your issue and update you in the other thread.

**Comment by ghost1372** [comment]
This issue has been resolved in version 1.2 stable
