### ISSUE TITLE
error APPX1101: Payload contains two or more files with the same destination path 'AppEF.deps.json'.

### ISSUE THREAD

**Issue by Ika59** [microsoft/WindowsAppSDK#2524]
### Describe the bug

When building my app, I get this error:

![image](https://user-images.githubusercontent.com/95070338/168759578-26cc8abf-075c-48f4-978a-2ece65109725.png)

### Steps to reproduce the bug

1. Create a WinUI 3 app.
2. Add Microsoft.EntityFrameworkCore.Tools 6.0.5 from NuGet.
3. Build the app.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

It looks like this error occurs while executing the script Microsoft.Build.Msix.Packaging.targets:

![image](https://user-images.githubusercontent.com/95070338/168760745-51fdbedc-e2f3-46fc-a1a4-13da7ad8f131.png)

Moreover, the contents of these files are different:
.../bin/...
![image](https://user-images.githubusercontent.com/95070338/168761787-cae5a312-2057-4f80-ad1d-c0fe6fce8479.png)
.../obj/...
![image](https://user-images.githubusercontent.com/95070338/168762255-70fa5413-7f95-419e-9d4b-43af706c725f.png)

Maybe that's why duplicates are not deleted ???

**Comment by kmgallahan** [comment]
Dupe of #2237, #1856, et al.

**Comment by Ika59** [comment]
Thanks for the tip. I read https://github.com/microsoft/WindowsAppSDK/issues/2237 and https://github.com/microsoft/WindowsAppSDK/issues/1856. Tried the methods suggested there. Unfortunately, in my case, they do not provide a solution to the problem. The error message APPX1101 is still issued.

**Comment by Ika59** [comment]
I found a workaround for using EF Add-Migration and more in WinUI 3 in Desktop (Packaged) projects.

Workaround steps:

**Comment by Ika59** [comment]
> Workaround steps:

1. Create WinUI 3 in Desktop (Packaged) project

![image](https://user-images.githubusercontent.com/95070338/168996489-5888c397-7e6c-4ac4-9f50-a7179f6e1245.png)

**Comment by Ika59** [comment]
> Workaround steps:

2. Create new Project **AppEF.Model** -> _Class Library (WuinUI 3 in Desktop)_ . This project will be used to store the model description (DBContext). Add the necessary packages _Microsoft.EntityFrameworkCore..._ into it. From the main **AppEF** project, add a reference to it. This is the main configuration for developing the necessary software. However, if you add a package _Microsoft.EntityFrameworkCore.Tools_ to an **AppEF** project, the solution buid will fail.

![image](https://user-images.githubusercontent.com/95070338/168999771-ed1dd3bb-3702-43e9-8dbb-6038051468b9.png)

**Comment by Ika59** [comment]
> Workaround steps:

4. We start migration. We explicitly specify **AppEF.Console** (!!!) as the starup project.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/95070338/169007676-8dab0ad9-b7d7-40a2-85da-ea44954ebc57.png">

**Comment by Ika59** [comment]
As a result, the migration was successfully created. I will continue to check the compatibility of WinUI 3 and EF...

_Maybe you had to immediately use template with Windows Application Packaging (WAP) project (???)_

**Comment by Ewerton** [comment]
The workaround provided by @Ika59 works for Maui Native Mobile applications too. Thanks a lot!

**Comment by AlmightyLks** [comment]
MAUI is step by step releasing, yet this bug still hangs around.
Unbearable working conditions, I must say.

**Comment by Scottj1s** [comment]
This is fixed in Windows App SDK 1.2 Preview 2, at which point the workaround may be removed

**Comment by eduardobragaxz** [comment]
Hey @Scottj1s  I'm getting this when I set PublishTrimmed to "true". I get some trim analysis warnings -  one for WinRT.TypeExtensions, five for WinRT.Projections..cctor(); and one IL2104 for WinRT.Runtime.dll. And then error APPX1101.

 I assume my code is not the problem because it warned me about the code to enable Mica, so I had to take that off.

If I set PublishTrimmed to "false" it builds normally, no problems.

**Comment by Scottj1s** [comment]
@eduardobragaxz, yes the trim warnings are known and being investigated.  Are you seeing the APPX1101 with WinAppSDK 1.2 Preview 2?  And are you seeing it specifically with colliding deps.json files?  If so, please reopen this issue and provide a simple repro.  If you're seeing something else, please open a new issue.

**Comment by eduardobragaxz** [comment]
@Scottj1s yes, WinAppSDK 1.2 Preview 2. Submitted the issue [here](https://github.com/microsoft/WindowsAppSDK/issues/3030).

**Comment by armendimeri** [comment]
This issue still existing on latest release of VS

**Comment by QuickScoP3s** [comment]
I have this exact issue when I add `Microsoft.EntityFrameworkCore.Design` to the WinUI Application:
![image](https://user-images.githubusercontent.com/12516179/199616289-83a0abac-ab65-4efa-b922-1bbb1a233750.png)

When I remove only this package, the build works as normal, but I can't generate migrations
