### ISSUE TITLE
"The Windows App SDK (Experimental)" extension does not work with VS 2022

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/WindowsAppSDK#2526]
### Describe the bug

_I've learned offline that the 2022 and Experimental extensions can coexist, both can be used to create apps. The problem comes from the change WinAppSDK packaging. That change breaks upgrading to the lates in the NuGet package manager; hand-edit the .vcxproj and remove the unneeded packages._

I mistakenly installed the VS Extension for WinAppSDK on my VS 2022 install. Instead, experts told me, I should have added that optional feature from the VS installer (an optional feature that needs to be selected).

After doing this I created a VS app from the template. this worked, builds and runs.
Then I used the NuGet package manager to update packages to the latest version. This resulted in conflicting .prop file `<Import>`'s, e.g. `Microsoft.WindowsAppSDK.1.0.3` and `Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1`

From the owners, I learned this extension should not be used. 

### Steps to reproduce the bug

- In a VS 2020 session, use the VS extension manger to install `The Windows App SDK (Experimental)`
- File.New Project...Win App SDK C++ App
- build, run.
- Project.Manage nuget packages.. 
- go to the updates tab
- select the newer packages, "install"
- F5 to build. see errors below

```
1>------ Build started: Project: WinAppSdk2, Configuration: Debug x64 ------
1>C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.props(25,3): warning MSB4011: "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.UI.Xaml.Markup.Compiler.props" cannot be imported again. It was already imported at "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.WinUI.props (25,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\WinAppSdk2.vcxproj]
1>C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.WinUI.targets(77,3): warning MSB4011: "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.References.targets" cannot be imported again. It was already imported at "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.targets (76,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\WinAppSdk2.vcxproj]
1>C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.WinUI.targets(78,3): warning MSB4011: "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.AppX.targets" cannot be imported again. It was already imported at "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.targets (77,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\WinAppSdk2.vcxproj]
1>C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.WinUI.targets(80,3): warning MSB4011: "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.UI.Xaml.Markup.Compiler.targets" cannot be imported again. It was already imported at "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.targets (79,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\WinAppSdk2.vcxproj]
1>C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.1.0.3\build\Microsoft.WinUI.targets(82,3): warning MSB4011: "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.Build.Msix.targets" cannot be imported again. It was already imported at "C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\packages\Microsoft.WindowsAppSDK.WinUI.1.0.0-experimental1\build\Microsoft.WinUI.targets (81,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\WinAppSdk2.vcxproj]
1>64 bit MIDLRT Processing C:\Users\chrisg.NTDEV\source\repos\WinAppSdk2\App.idl
```

### Expected behavior

it builds

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by DefaultRyan** [comment]
This isn’t an issue with the experimental VSIX. There’s nothing stopping the experimental extension from peacefully coexisting with the preview/stable VSIX.

Instead, this is an incompatibility between how the <= 1.0.0-experimental1 NuGet packages were structured, and how the >=1.0.0-preview1 NuGet packages work.

Starting with 1.0.0-preview1, all of Window App SDK is in a single NuGet package. But prior to that, the main NuGet package was a mere wrapper/hook metapackage to bring in several other dependencies that had all the actual implementation (e.g. Microsoft.WindowsAppSDK.Foundation, Microsoft.WindowsAppSDK.WinUI, etc…). See the 1.0.0-experimental1 package’s dependencies tab [NuGet Gallery | Microsoft.WindowsAppSDK 1.0.0-experimental1](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.0.0-experimental1#dependencies-tab).

Apparently, when you use the NuGet package manager to upgrade a package, it doesn’t remove dependencies that are no longer needed. So when it leaves these separate dependencies around they now conflict with the logic in the “new” monolithic package.

It’s perfectly fine if you want to tinker with the experimental extension/NuGet. But if you create a project using “experimental” hoping to update it into using “preview/stable”, that’s not something we’re actively trying to support, and some degree of friction like this may occur.

There might be the option of using the NuGet package manager console to do a reinstall and ignore dependencies ([Reinstalling and Updating NuGet Packages | Microsoft Docs](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages#using-update-package)), but I haven’t tested it to know if that would yield non-breaking behavior. Uninstalling the package and its dependencies and then reinstalling the newer version is probably safer.

**Comment by riverar** [comment]
Given that Microsoft has deviated from its [release cadence/channel plans](https://github.com/microsoft/WindowsAppSDK/discussions/637) perhaps it's time to rethink [the VSIX situation](https://github.com/microsoft/WindowsAppSDK/discussions/742). That is, perhaps you'll be better off deleting all experimental-channel VSIX packages to reduce confusion/clutter.

**Comment by Scottj1s** [comment]
@riverar Yes, we're currently revamping the [Downloads page](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads) to remove now unsupported standalone VSIX packages (including experimental).

**Comment by riverar** [comment]
@Scottj1s Sounds good!
