### ISSUE TITLE
How to build it ?

### ISSUE THREAD

**Issue by pratikone** [microsoft/WindowsAppSDK#2538]
### Describe the bug

No public doc on how to build it or if one exists, it is not linked to main README.

### Steps to reproduce the bug

1. Goto winappsdk rep page on github
2. scroll down to section on instructions to build it

no section exists or no links embedded

### Expected behavior

winappsdk builds !!

**Comment by DrusTheAxe** [comment]
By "it" are you asking how to build *WinAppSDK*?

**Comment by pratikone** [comment]
yes

**Comment by bpulliam** [comment]
There is now the BuildAll script in the root.
