### ISSUE TITLE
Can't add WinUI3 Project item

### ISSUE THREAD

**Issue by Osirisoo0O** [microsoft/WindowsAppSDK#2542]
### Describe the bug

I can't add any winui3 project item.

### Steps to reproduce the bug

1. Create new project (blank app,packaged)
2. right click project,->add new item
3. can't find som winui3 project item (e.g. page,resources...)

### Screenshots

![shot](https://user-images.githubusercontent.com/14803729/169728904-3e0859be-78c9-48a1-8858-b6f54c361d50.jpg)

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by kmgallahan** [comment]
Try reinstalling the templates (or check that they are selected in the below bundle):

1. Open Visual Studio Installer > Modify
2. Uncheck .NET desktop development > Modify
3. Check .NET desktop development > Modify

**Comment by Osirisoo0O** [comment]
> 尝试重新安装模板（或检查是否在以下捆绑包中选择了这些模板）：
> 
> 1. 打开 Visual Studio Installer > Modify
> 2. 取消选中 .NET 桌面开发>修改
> 3. 检查 .NET 桌面开发>修改

Oh,it's worked!Thank you!
