### ISSUE TITLE
 Installation with System-Account doesn't work

### ISSUE THREAD

**Issue by stefansjfw** [microsoft/WindowsAppSDK#2546]
### Describe the bug

Trying to install Windows App SDK 1.0.3 with System-Account fails with 
```
Installing license: WAR_MAINPACKAGE_LICENSE
Install result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.0_3.469.1654.0_x64__8wekyb3d8bbwe
Package deployment result : 0x80073cf9 Install failed. Please contact your software vendor.
One or more install operations failed. Result: 0x80073cf9
```

Installing WinAppSDK on the same machine (clean VM) works correctly when installing as admin user.

First reported here:
https://github.com/microsoft/PowerToys/issues/18065

### Steps to reproduce the bug

- Download WinAppSDK 1.0.3 x64 runtime installer https://aka.ms/windowsappsdk/1.0/1.0.3/windowsappruntimeinstall-1.0.3-x64.exe
- Open cmd.exe with psexec ` .\PsExec.exe -s -i cmd.exe`
- Try running WinAppSDK installer from opened cmd `WindowsAppRuntimeInstall.exe`
- Observe the output

### Expected behavior

WinAppSDK installs correctly without errors

### Screenshots

![image](https://user-images.githubusercontent.com/57057282/169994844-0f9036b2-728b-407e-94c6-80477d9277ff.png)

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

**Comment by riverar** [comment]
Seems related to #2469. @DrusTheAxe

**Comment by DrusTheAxe** [comment]
The title implies this used to work and now doesn't in 1.0.3. What version did this previously work for? And was that on the same version of Windows (21H1)?

Are you trying to install the runtime for use by processes running as LocalSystem or are you trying to install the runtime for use by all users (aka provisioning)? It's an important distinction as the former is unsupported behavior (ByDesign) whereas the latter _should_ work but if it's not then it's a bug.

Here's a deeper explanation of the distinction:

>Open cmd.exe with psexec .\PsExec.exe -s -i cmd.exe

-s = Run the remote process in the System account

If you're trying to install the runtime for use by the LocalSystem account then it won't work. The one user account Windows can't register MSIX packages for is LocalSystem so when the installer is running as LocalSystem and calls pkgmgr.AddPackageAsync() it will fail.

If you're trying to install the runtime for all users (i.e. provisioning packages) the installer's implementation doesn't handle it. It 
_should_ work, so this would be a bug in the installer. As noted recently [here](https://github.com/microsoft/WindowsAppSDK/discussions/2515#discussioncomment-2807160) the installer's core logic is effectively

```
FOREACH p IN *.msix
    packagemanager.AddPackageAsync(p)
    IF !p.IsFramework and IsElevated()
        packagemanager.ProvisionPackagesForAllUsersAsync(p.packagefamilyname)
```

This is implemented in `installer\dev\install.cpp`, notably lines 259 (`AddPackage`), 269-270 (`IF...IsElevated`) and 275 (`ProvisionPackage`). `AddPackage` will fail if running as LocalSystem. If the intent is to provision the package for all users and not register it for LocalSystem (as Windows doesn't support that), the logic needs a small but critical alteration:

```
FOREACH p IN *.msix
    IF GetTokenInformation(TOKEN_USER) == CreateWellKnownSid(WinLocalSystem)
        packagemanager.StagePackageAsync(p)
    ELSE
        packagemanager.AddPackageAsync(p)
    IF !p.IsFramework and IsElevated()
        packagemanager.ProvisionPackagesForAllUsersAsync(p.packagefamilyname)
```

I've filed a bug to address this https://task.ms/39720940

**Comment by DrusTheAxe** [comment]
> Seems related to #2469

They're different root issues.

#2469 is due to DDLM packages not being Store signed. Here it's due to running the installer as LocalSystem (_why_ that's being done is unclear, but _what_ isn't).

The symptoms differ in small but significant ways. #2469's installer output shows it successfully installs some packages then fails on the DDLM whereas here it fails on the first package (the framework). The package order is intentional and deterministic (not random).

**Comment by w0** [comment]
I am running the installer as system because that what ConfigMgr uses to install software for my end users. The ability to do user based installs require support in the installer and/or users having the correct rights to install software on their local machine.

**Comment by DrusTheAxe** [comment]
> I am running the installer as system because that what ConfigMgr uses to install software for my users

No problem. This fix should address that.
