### ISSUE TITLE
VS2022 17.2.1 Build started... and freeze

### ISSUE THREAD

**Issue by Slion** [microsoft/WindowsAppSDK#2547]
### Describe the bug

Can't build blank template project.
Same issue with another more evolved project.
On another computer with older version of VS 2022 it worked.

### Steps to reproduce the bug

Create a new Windows App SDK project in Visual Studio and try to build it.

### Expected behavior

Project should build.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022 v17.2.2

**Comment by DefaultRyan** [comment]
I tried to reproduce this problem using VS 17.2.2, and I had no issues. The fact that you said this works on another computer with another version of VS indicates to me that this isn't a Windows App SDK issue, but is an issue with either VS or your specific installation.

You could try reinstalling VS on that machine, and if that doesn't work, I'd recommend you [report a problem in VS](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022). Perhaps you could try some troubleshooting using https://docs.microsoft.com/en-us/answers/questions/276699/visual-studio-always-hangs-and-freezes.html or StackOverflow.

**Comment by DefaultRyan** [comment]
I should add that if you can supply more information that points to this being something specific to Windows App SDK, please feel free to reopen this bug with the additional information.

Ryan

**Comment by Slion** [comment]
Ok, thanks for looking into it. Very likely something wrong with my VS setup then. Maybe I'm missing a package somehow...
