### ISSUE TITLE
TextBox.DoubleTapped Is it me or...?

### ISSUE THREAD

**Issue by CAKCy** [microsoft/WindowsAppSDK#2552]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/2550

<div type='discussions-op-text'>

<sup>Originally posted by **CAKCy** May 25, 2022</sup>
My TextBox_DoubleTapped is not working.
I set  "IsDoubleTappedEnabled" to true.
I changed the "IsReadOnly" from False to True.
No luck.

I welcome any ideas and I am very open minded about them! :)</div>

**Comment by BenJKuhn** [comment]
I see you opened both a discussion and an issue. I'm going to close this issue to avoid duplicate accounting. Discussion is here: https://github.com/microsoft/WindowsAppSDK/discussions/2550. If this turns out to be an App SDK bug, please open a new issue at that time.

Thanks,

Ben
