### ISSUE TITLE
ARM64 installer won't work on Windows 10

### ISSUE THREAD

**Issue by jaimecbernardo** [microsoft/WindowsAppSDK#2564]
### Describe the bug

When running the arm64 installer executable on Windows 10, it tries to install a x64 package, which fails, since Windows 10 doesn't have x64 emulation.

### Steps to reproduce the bug

1. Download the arm64 installer. https://aka.ms/windowsappsdk/1.0/1.0.3/windowsappruntimeinstall-1.0.3-arm64.exe
2. Try to run it on a Windows 10 ARM64 machine.

### Screenshots

![GetAttachmentThumbnail](https://user-images.githubusercontent.com/26118718/171608057-7a16cbb3-6ad5-499b-8a0f-a378aafa8057.png)

### Packaging type

Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

**Comment by sachintaMSFT** [comment]
The fix for this issue will be serviced in Windows App SDK 1.1.5 that is due in September.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.1.5` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-115)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.1.5)
