### ISSUE TITLE
WinUI 3 Gallery (SDK 1.1) crashes

### ISSUE THREAD

**Issue by anup-das** [microsoft/WindowsAppSDK#2573]
### Describe the bug

WinUI 3 Gallery App got automatically updated from the store. After update, the app no longer starts up. Event viewer is reporting crash

Faulting application name: WinUIGallery.DesktopWap.exe, version: 1.0.0.0, time stamp: 0x62571213
Faulting module name: CoreMessagingXP.dll, version: 10.0.22621.1000, time stamp: 0xc93a5eeb
Exception code: 0xc000027b
Fault offset: 0x0000000000090e1c
Faulting process id: 0x1644
Faulting application start time: 0x01d877ed655eba62
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WinUI3ControlsGallery_1.3.13.0_x64__8wekyb3d8bbwe\WinUIGallery.DesktopWap\WinUIGallery.DesktopWap.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe\CoreMessagingXP.dll
Report Id: c72780de-855f-4724-9d2d-4a6f4e0f3d05
Faulting package full name: Microsoft.WinUI3ControlsGallery_1.3.13.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App

### Steps to reproduce the bug

Let WinUI  3 Gallery app update from the store. Try launching the app - the app does not start

### Expected behavior

The app should start

### Windows version

Windows 11 version 21H2 (22000)

**Comment by anup-das** [comment]
Fault bucket 1608057854107112022, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.WinUI3ControlsGallery_1.3.13.0_x64__8wekyb3d8bbwe
P2: praid:App
P3: 1.0.0.0
P4: 62571213
P5: combase.dll
P6: 10.0.22000.708
P7: 9e680117
P8: 80070057
P9: 0000000000032b5b
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.454eb16b-b568-4343-a83b-7dba109f22ee.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.922b0e16-2f9b-4ede-97bc-6e4c362760ce.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6becb90d-1c99-4b10-9a88-31a048257aa2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8d6cc426-484e-46c3-8511-06ddfaef4b6c.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4c4fc4ab-f813-49d4-b0d2-92671837bbca.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Microsoft.WinUI3_a039df2b26457b3d4c155c7f422a9f35acd957_cba7efa0_1b252a3a-4a39-49cf-aed5-cd3f05b94c38

Analysis symbol: 
Rechecking for solution: 0
Report Id: a5c7845d-280b-473d-bf00-99097ca9c3ff
Report Status: 268435456
Hashed bucket: 6604051680f624e2f650f8193454d256
Cab Guid: 0

**Comment by anup-das** [comment]
[Report.zip](https://github.com/microsoft/WindowsAppSDK/files/8837309/Report.zip)

**Comment by JonPerkinsOldGit** [comment]
Yes, same experience for me

**Comment by riverar** [comment]
Is being tracked at https://github.com/microsoft/WinUI-Gallery/issues/988

**Comment by bpulliam** [comment]
We are aware of the problem, have a good local repro, and are working on a fix. Stay tuned!
