### ISSUE TITLE
Can't resize nor move window after exiting from full screen

### ISSUE THREAD

**Issue by kingcean** [microsoft/WindowsAppSDK#2576]
### Describe the bug

The user can't move, resize, minimize, maximize/restore nor close the window after exiting from full screen. And the window shadow, corner radius, and caption buttons disappear.

### Steps to reproduce the bug

Firstly, extend the window content into the title bar (maybe no need to extend).

```csharp
// var appWindow = ... The AppWindow instance of MainWindow
appWindow.TitleBar.ExtendsContentIntoTitleBar = true;
appWindow.TitleBar.SetDragRectangles(new RectInt32[]
{
    new RectInt32(0, 0, 10000, 40) // Set a rectangle for dragging
});
```

Enter full screen mode.

```csharp
appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
```

Then, exit full screen.

```csharp
appWindow.SetPresenter(AppWindowPresenterKind.Default);
```

You will see the window does not work correctly anymore.

### Expected behavior

The window should be restored to what it looks like before entering the full screen.

### Screenshots

![Before entering full screen](https://user-images.githubusercontent.com/1724940/172051351-c64cfa11-0b51-4856-b05a-09840735049d.jpg)
↑ The window looks good before entering full screen.

![Full screen](https://user-images.githubusercontent.com/1724940/172051355-2b219f14-4a6c-4ae1-b953-e6fb6e446d5a.jpg)
↑ Full screen

![Exited from full screen](https://user-images.githubusercontent.com/1724940/172051356-fe6559d4-8ec9-431f-b0da-ec11fa0212b3.jpg)
↑ Exit full screen. The window, shadow, corner radius, and caption buttons disappear. Users can't move, resize, minimize, maximize/restore nor even close the window.

### NuGet package version

1.1.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

It worked on Windows App SDK 1.0.3 but now fails on 1.1.0.

**Comment by sudongg** [comment]
Same problem.
The default window exits after full screen, and the title bar border is not visible.

If the window is full screen when the window is maximized, the window will not enter the full screen, and the title bar border will not be visible. After trying to enter the full screen again, you can enter the full screen, but you cannot exit the full screen.

**Comment by kingcean** [comment]
### Work-around

```csharp
OverlappedPresenter defaultPresenter;
private void SwitchFullScreen(bool enter)
{
    // var appWindow = ... The AppWindow instance of MainWindow
    if (!enter)
    {
        appWindow.SetPresenter(AppWindowPresenterKind.Default);
        return;
    }

    defaultPresenter = appWindow.Presenter as OverlappedPresenter;
    defaultPresenter.IsAlwaysOnTop = defaultPresenter.IsAlwaysOnTop;
    defaultPresenter.IsResizable = defaultPresenter.IsResizable;
    defaultPresenter.IsMinimizable = defaultPresenter.IsMinimizable;
    defaultPresenter.IsMaximizable = defaultPresenter.IsMaximizable;
    defaultPresenter.SetBorderAndTitleBar(defaultPresenter.HasBorder, defaultPresenter.HasTitleBar);
    appWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
}
```

**Comment by rkarman** [comment]
Yes, the workaround is as provided above, this is called out in the [1.1 release notes](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-11-stable) as a known issue.
@mevey can you please link the task here for reference? The fix is known and will be part of the next servicing update.

**Comment by mevey** [comment]
We are tracking this work here [task.ms/39909951](task.ms/39909951).

**Comment by kingcean** [comment]
It works now on Windows App SDK 1.1.1.
