### ISSUE TITLE
Latest VS Extension fails - Microsoft.Windows.Msix.VisualStudio.ProjectExtensions.Dev17.Standalone 1.1.0.2205131	

### ISSUE THREAD

**Issue by aherrick** [microsoft/WindowsAppSDK#2579]
### Describe the bug

Tried to install the latest VS Extension in 2022 and receiving and error (logs attached). 

`Error: cannot create a stable subkey under a volatile parent key`

Then tried to uninstall and received the attached logs. Now I think I'm in a weird limbo spot where I can't uninstall, but VS Extension Management UI doesn't report as installed. Yet when I run the installer, it says it can't install as its already been applied.

### Steps to reproduce the bug

1. Latest VS2022 Preview
2. Windows Build 19043.1706
3. Install/Update to latest MSIX Extension 1.1.0.2205131
4. Receive Error above

### Expected behavior

Not receive Error above

### Screenshots

![6-5-2022 11-03-25 AM](https://user-images.githubusercontent.com/586671/172057024-3b35ef49-0a7e-48cb-bfa4-820a3c93929c.png)
![2022-06-06_02-11-58](https://user-images.githubusercontent.com/586671/172108696-64e4c850-a617-4803-a76b-e6c470881018.png)
![2022-06-06_02-12-22](https://user-images.githubusercontent.com/586671/172108709-8eb904c4-1f9a-4ab4-88de-308cd4e0e4a9.png)

### Packaging type

Packaged (MSIX)

### Windows version

Windows Build 19043.1706

### IDE

Visual Studio 2022-preview

### Additional context
[dd_VSIXInstaller_20220606020901_65ac.log](https://github.com/microsoft/WindowsAppSDK/files/8842363/dd_VSIXInstaller_20220606020901_65ac.log)

[dd_VSIXInstaller_20220605105545_2154.log](https://github.com/microsoft/WindowsAppSDK/files/8840192/dd_VSIXInstaller_20220605105545_2154.log)

**Comment by aherrick** [comment]
any updates on this? i'm dead in the water here and i can't be the only one as i've seen this now on 2 different machines.

**Comment by DefaultRyan** [comment]
I'm looking into this right now. I suspect this may be a problem with Visual Studio 17.3 Preview, but I'm trying to get confirmation. The extension has been installing successfully onto VS 17.2.

**Comment by aherrick** [comment]
@DefaultRyan thank you :)
