### ISSUE TITLE
Can't build WinAppSDK 1.1 project in C++20 mode - "IComponentConnector2 identifier not found"

### ISSUE THREAD

**Issue by mikrause79** [microsoft/WindowsAppSDK#2582]
### Describe the bug

Compiler error "IComponentConnector2 identifier not found" in winrt/Microsoft.UI.Xaml.Markup.h.

This generated code:
        static constexpr bool m_has_connectable_base{
            impl::has_initializer<composable_base>::value &&
            impl::has_interface<D, IComponentConnector>() &&
            **impl::has_interface<D, IComponentConnector2>() };**

IComponentConnector2 doesn't exist - it was folded into IComponentConnector in WinUI.  this doesn't generate an error in C++17 mode, but does in C++20.

This is with latest non-preview (as of 6/5) Visual Studio, WinApp SDK 1.1, and C++/WinRT.
Visual Studio 17.2.3
C++/Winrt 2.0.220531.1 
Windows App SDK 1.1

### Steps to reproduce the bug

1. Create a WinAppSDK WinUI 3 Desktop project - no changes from template.
2. Build - confirm no errors.
3. Switch to C++20 mode in Language options in MSVC
4. Rebuild

### Expected behavior

Builds without errors.

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

This is with latest non-preview (as of 6/5) Visual Studio, WinApp SDK 1.1, and C++/WinRT.
Visual Studio 17.2.3
C++/Winrt 2.0.220531.1 
Windows App SDK 1.1

**Comment by shelllet** [comment]
i clean project and rebuild, everything is ok,
but today.
 i clean poject and rebuild,the same error occurs.

**Comment by mikrause79** [comment]
Thanks shelllet; I moved too many pieces at once and mis-attributed this.

**Comment by mikrause79** [comment]
Will follow up w/ an issue against C++/winrt.

**Comment by mikrause79** [comment]
https://github.com/microsoft/cppwinrt/issues/1155
