### ISSUE TITLE
AppNotifications can not be registered

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#2585]
### Describe the bug

i want to create AppNotifications, i am following [docs/samples](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs) but when i want to run my app i get exception in register method

![image](https://user-images.githubusercontent.com/9213496/172222865-4bc960b5-dc79-4253-a336-118fb1982575.png)

### Steps to reproduce the bug

1.create winui 3 1.1.0
2.follow docs for using AppNotifications
3.Run app

### NuGet package version

1.1.0-preview3

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

i am using version 1.1.0 stable

**Comment by loneursid** [comment]
Hi Mahdi,

Is this a packaged or unpackaged app? If it's an unpackaged app, that exception ('interface not registered') you're getting might indicate that the WindowsAppSDK isn't installed. If that's the case, you can download the installer from here: https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads.

**Comment by loneursid** [comment]
hmm, that seems right. Just to confirm that everything was working as expected on our end, I did the following:

1. removed all the WinAppSDK packages, 
2. downloaded a fresh copy of the sample (I used the C# unpackaged one), 
3. downloaded the WindowsAppSDKv1.1 installer and installed it 
4. built and ran the sample

Everything worked as expected.

Are you using the sample? If not have you tried it, to verify that your environment is setup correctly?

**Comment by ghost1372** [comment]
@loneursid 
I reinstalled my Windows 11 Pro
I reinstalled Visual Studio 2022 (Only .Net Workload with Windows App SDK and Windows 10/11 SDK (19041/22000/22621))
I installed the following winappsdk runtime
 
https://aka.ms/windowsappsdk/1.1/latest/windowsappruntimeinstall-1.1-x64.exe

![image](https://user-images.githubusercontent.com/9213496/172647056-f6f019f8-0cd9-4c77-9098-a99995391514.png)

I still can not run the sample (exception in register method)

I used exactly the sample codes

[App2.zip](https://github.com/microsoft/WindowsAppSDK/files/8862743/App2.zip)

**Comment by ghost1372** [comment]
Hi @loneursid 
Thank you for taking the time to fixing this issue.🙏
i fixed this issue with changing x86 to x64😅
![Untitled](https://user-images.githubusercontent.com/9213496/172648947-7cd26e90-5a3b-47a6-9b18-dd7c6eb8da20.png)

Do I need to install both x86 and x64 runtime on my system?
