### ISSUE TITLE
BadgeNotification not working

### ISSUE THREAD

**Issue by DierkDroth** [microsoft/WindowsAppSDK#2590]
### Describe the bug

Please see attached boiler plate repo: clicking the button should show a badge on the taskbar icon ... but doesn't.

 - Windows 11 with latest updates
 - Settings -> System -> Personalization -> Taskbar -> Taskbar behaviors -> Show badges (...) is checked
 - WindowsAsppSdk 1.1.0 
 
[Badge.zip](https://github.com/microsoft/WindowsAppSDK/files/8850340/Badge.zip)

### Steps to reproduce the bug

Please see above

### Expected behavior

Badges should work

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by vaheeshta** [comment]
We appreciate the bug report! Since this is a Windows platform bug and not a Windows App SDK bug, I've filed a bug with the platform team (internal bug #39959734) and asked them to follow up here with any updates. Closing this bug since this isn't an active issue with Windows App SDK itself.
