### ISSUE TITLE
Can't create package or associate with Store for single-project MSIX

### ISSUE THREAD

**Issue by JanRajnoha** [microsoft/WindowsAppSDK#2593]
### Describe the bug

I have default project for Windows App SDK and I try create package or associate it with Store, but Visual Studio throws error 0xe0434352 (screenshot included) and crashes.

**Logs from Event viewer:**
Faulting application name: devenv.exe, version: 17.3.32519.111, time stamp: 0x1a4dcbbf
Faulting module name: KERNELBASE.dll, version: 10.0.25131.1000, time stamp: 0x220a9ff1
Exception code: 0xe0434352
Fault offset: 0x000000000008fedc
Faulting process id: 0x0x3634
Faulting application start time: 0x0x1D87A8A55CDD947
Faulting application path: C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 4a406780-77cf-4b08-9151-1b4db2ec6b4c
Faulting package full name:
Faulting package-relative application ID:

Faulting application name: WerFault.exe, version: 10.0.25131.1000, time stamp: 0x387a2982
Faulting module name: ntdll.dll, version: 10.0.25131.1000, time stamp: 0xc471e3b0
Exception code: 0xc0000409
Fault offset: 0x00000000000a40c0
Faulting process id: 0x0x80C0
Faulting application start time: 0x0x1D87A8A6B550015
Faulting application path: C:\WINDOWS\system32\WerFault.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: d1ed6880-d902-48fd-9799-016d1c06f3c5
Faulting package full name:
Faulting package-relative application ID:

![image](https://user-images.githubusercontent.com/16069721/172434241-998d5c11-6c1c-41f0-8192-dc88d4fb1002.png)

### Steps to reproduce the bug

1. Create default Windows App SDK
2. Try associate with Store or create package
3. Crash

### Expected behavior

Should work

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

**Comment by JanRajnoha** [comment]
Windows App SDK version: 1.1 (This option missing in NuGet version list)

**Comment by JanRajnoha** [comment]
Problem reported in Visual Studio too if this won't be problem of WASDK

**Comment by DefaultRyan** [comment]
I just heard back from Visual Studio that this was an issue in their product. It was fixed in servicing for 17.2, but not 17.3 Preview 1.1. 17.3 Preview 2 will have the fix.

**Comment by JanRajnoha** [comment]
Sometimes problems happen :) thank you for answer
