### ISSUE TITLE
WindowsAppRuntimeInstaller.exe won't install missing components (e.g. DDLM) after runtime installed from winui 3 gallery dependency

### ISSUE THREAD

**Issue by fredemmott** [microsoft/WindowsAppSDK#2595]
### Describe the bug

I'm getting a bootstrap failure (which is the proximal trigger - not root cause - of #2592) because I don't have the 1.1 microsoft.winappruntime.ddlm package installed, however:

1. I have the 1.1 runtime installed, which was automatically installed by the windows store/update because I have the winui3 control gallery installed
2. The redist exe exits early because the main runtime is already installed - it won't install the ddlm msix

### Steps to reproduce the bug

1. Get a clean windows VM with no trace of windows app sdk
2. install the winui 3 controls gallery through the ms store
3. attempt to run an unpackaged app using the windows app sdk v1.1; crashes
4. run `WindowsAppRuntimeInstall.exe`; exits early as main runtime is installed, does not install ddlm:

```
PS C:\users\fred\Downloads\Microsoft.WindowsAppRuntime.Redist.1.1.0\WindowsAppSDK-Installer-x64> .\WindowsAppRuntimeInstall.exe
INFO: Provisioning of WindowsAppSDK packages will be skipped as it requires elevation.
Installing license: MSIX_MAINPACKAGE_LICENSE
Install result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install result : 0x0
Deploying package: Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe
Package deployment result : 0x80073cfb The provided package is already installed, and reinstallation of the package was blocked. Check the AppXDeployment-Server event log for details.
One or more install operations failed. Result: 0x80073cfb
```

5. attempt to run app, still fails
6. manually install `Microsoft.WindowsAppRuntime.DDLM.1.1.msix`
7. attempt to run app, starts fine

### Expected behavior

> attempt to run an unpackaged app using the windows app sdk v1.1; crashes

#2592 - this should log an error and optionally report the issue to the user, depending on the bootstrap options

> run `WindowsAppRuntimeInstall.exe`; exits early as main runtime is installed, does not install ddlm

Should install any missing components of the windows app runtime, even if the main package is already installed. In particular, it should install the ddlm package.

### Packaging type

Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Other

### Additional context

v1.1.0 nuget package, vscode

**Comment by fredemmott** [comment]
Thanks - the event log does indeed have more information:

```
AppX Deployment operation failed for package Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe with error 0x80073CFB. The specific error text for this failure is: Deployment of package Microsoft.WindowsAppRuntime.1.1_1000.516.2156.0_x64__8wekyb3d8bbwe was blocked because the provided package has the same identity as an already-installed package but the contents are different. Increment the version number of the package to be installed, or remove the old package for every user on the system before installing this package.
```

... and this is still showing up when I re-run the installer now I have DDLM

**Comment by riverar** [comment]
Yep, I hit this as well. It was especially painful because I was stuck on a version of the runtime that didn't have fix [5db5380](https://github.com/microsoft/WindowsAppSDK/commit/5db53804aef23e634d51b19dfa0b172bc565056d). Had to remove all apps with Store deps to move forward, which is pretty terrible.

**Comment by fredemmott** [comment]
FWIW, this still repros on v1.1.2

**Comment by fredemmott** [comment]
This appears fixed in v1.1.3, probably the same root cause as #2713 (fyi @gabbybilka )

**Comment by FrancisKoo** [comment]
This still repros on v1.1.4

**Comment by FrancisKoo** [comment]
@DrusTheAxe I have the same issue.
1. Install WindowsAppRuntimeInstaller.exe
2. Uninstall DDLM 
3. Instll WindowsAppRuntimeInstaller.exe ,an error occurs
![image](https://user-images.githubusercontent.com/20754529/190978499-a5e12aa5-30be-4890-9568-036a66a44cd0.png)
