### ISSUE TITLE
Please give good error checking/error messages a high priority early during development

### ISSUE THREAD

**Issue by RWeigelt** [microsoft/WindowsAppSDK#26]
# Proposal: High priority for good error checking/error messages right from the start

## Summary
Error checking and good error messages should not be treated as "polishing" that can come later. When using an API, silent crashes or naked HRESULTs should be the exception (no pun intended).

## Rationale
Learning a new technology is not always easy. Learning a "new new" technology can be challenging. If silent crashes happen or all you get is a cryptic HRESULT, you never quite know whether you made a mistake or the technology has a bug. Good error checking and error messages in that technology are important for leading developers on the right path. If finding mistakes is too difficult, this even may drive people away from the technology.

Two examples from my own experience:
1. Coming from WPF, writing UWP apps felt like a step backward. One little mistake in the XAML could lead to a crash that kept me wondering what happened. Trying to figure out the reason by walking back the changes took so much time that I stopped the whole project and switched to WPF on .NET Core.
2. It's been a long time, so my memory may not be exact, but back in the Silverlight days, one important productivity boost from Silverlight 2 and 3 to maybe 4, but especially version 5 was that the error messages got so much better. In SL2 and SL3 all you got was an HRESULT.

## Scope

| Capability | Priority |
| :---------- | :------- |
| If something is referenced "by string" (i.e. not checked by the compiler), a mistake in the reference (missing/typo) must result in a useful error message at runtime. | Must |

**Comment by sylveon** [comment]
There are already good error messages, .NET just doesn't report them. They are stashed within the IRestrictedErrorInfo associated with the error.

**Comment by jonwis** [comment]
This is a great topic, and one that's incredibly interesting to me.

We'll be implementing using code that pushes errors through [RoOriginateError](https://docs.microsoft.com/en-us/windows/win32/api/roerrorapi/nf-roerrorapi-rooriginateerrorw), and as @sylveon notes you can get this back through [GetErrorInfo](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-geterrorinfo).  Thread-bound error information objects can be hard in a threaded/async world, so figuring out the intersection of that plus .NET Exception types would be useful.

On the "strings as API parameters" ... agreed, this is a general problem.  We've identified a pattern like [AdaptiveCardBuilder.CreateAdaptiveCardFromJson](https://docs.microsoft.com/en-us/uwp/api/windows.ui.shell.adaptivecardbuilder.createadaptivecardfromjson?view=winrt-18362#Windows_UI_Shell_AdaptiveCardBuilder_CreateAdaptiveCardFromJson_System_String_) as a way to make this more manageable.  What if instead of returning an `IAdaptiveCard` object, it'd return an `AdaptiveCardBuildResult` which contains either the card or a descriptive "what didn't work" report?

**Comment by stevewri** [comment]
@RWeigelt - would @jonwis's suggestion be a good solution for your problem with string parameters?

**Comment by RWeigelt** [comment]
> @RWeigelt - would @jonwis's suggestion be a good solution for your problem with string parameters?

There are two error scenarios that I have in mind:

1. I call some API function with an invalid parameter value and now something goes wrong.
2. I specify a string in markup and some code that I didn't even write crashes.

In both cases the question is: Do I have the chance to find out *what* went wrong?

For scenario 1, the pattern of returning a BuildResult object helps me find the problem. But it is different from what I'm used to when writing C# using the .NET framework and it makes the code of the "success path" more complicated. 

A small aside: When I design UIs, I sometimes play the "unfair user game". Which means that no matter how good my reasons for a specific non-optimal user experience are (e.g. extra steps or in an unintuitive order, additional cognitive load), I assume a potential user's position of "I don't care about your reasons, I want it to just work, make it happen" for a moment. This forces me to rethink solutions - sometimes I find an alternative solution, sometimes I don't.

Applying this to APIs: As an "unfair API user", I would say "for almost twenty years, when I call a CreateSomething function in C#, I either get a *something* object or an exception gets thrown". I could write a wrapper function that calls the original function, looks at the BuildResult object and returns either the result or throws an exception. But then the question is "why do *I* have to write this code?"

Of course, if I'd have to choose between the BuildResult approach for getting error info or getting no error info at all, I'd take it.
But if there would be a way that I somehow could get an exception with meaningful info, I would prefer that.

For scenario 2, the BuildResult pattern does not help me, at least not directly. Without some kind of error info, this scenario is worse than 1. If it happens often enough, it can heavily influence my decisions regarding whether to use a specific technology.

**Comment by stevewri** [comment]
@jonwis - what do we need to close on a proposal for the project board?

**Comment by andrewleader** [comment]
Thanks @RWeigelt for the feedback, we've captured this feedback to keep in mind for future improvements. If you have a specific API that you would like better error messages for, please submit an idea on our feature portal: https://aka.ms/winappsdkportal

Thanks!
