### ISSUE TITLE
DWriteCore renders some fonts with unexpected spaces

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/WindowsAppSDK#2643]
### Describe the bug

In some fonts (i.e. Segoe UI Variable Display), DWriteCore would render them with unexpected spaces, as seen in the below screenshot of DWriteCoreGallery.

### Steps to reproduce the bug

1. Clone the Windows App SDK samples.
2. Open the DWriteCoreGallery sample solution.
3. Update Windows App SDK to 1.1.1.
4. Build and deploy the DWriteCoreGallery sample.
5. Go to Font Collection (typographic) scenario.
6. Select the Segoe UI Variable font.
7. Scroll down to see the Display variant having an unexpected space between the letter "s" and "p".

### Expected behavior

There shouldn't be any unexpected spaces between the characters.

### Screenshots

<img width="837" alt="Screenshot of DWriteCoreGallery sample. In the screenshot, the text Display has an unexpected space between s and p." src="https://user-images.githubusercontent.com/29563098/174292719-930b14a2-421a-4fe2-a470-b7ec3e860dca.png">

### NuGet package version

1.1.1

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (25140)

**Comment by niklasb-ms** [comment]
Thanks for the screen shot and detailed repro steps!
I could repro this in 1.0 and 1.1, but it's fixed in 1.2-preview1.
