### ISSUE TITLE
CppWinrt needs to be installed, else VS can't find Windows App SDK headers.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/WindowsAppSDK#2670]
### Describe the bug

[Adding Windows App SDk to an existing Project](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project) mentions only installing the Windows App SDK package.  Not CppWinrt.

This state is very confusing because VS can find some header files, but not any from Windows App SDK.

Solution was to the cppwinrt nuget package. No where does the page say "Make sure to include CppWinrt." I get it, some people might think "Windows App SDK uses CppWinrt, naturally the CppWinrt package also needs to be downloaded." I get that. However, for new developers, and new developers to either Windows App SDK or CppWinrt, the additional step of "Downloading CppWinrt" might not occur naturally.

### Steps to reproduce the bug

1. Make a project without Windows App SDK or CppWinrt.
2. Add the Windows App SDK nuget package.

### Expected behavior

The header files can be found and I can start coding.

Or, at least, a message saying "CppWinrt needs to be included as well"

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment]
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-in-existing-project
This has been added to the page:
If your existing project is a C++ project, and you want to call Windows Runtime APIs in the Windows App SDK, then you'll need to add support for C++/WinRT. See [Visual Studio support for C++/WinRT, XAML, the VSIX extension, and the NuGet package](https://learn.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package). Look for info there about the Microsoft.Windows.CppWinRT NuGet package. Without that package, your project won't be able to find the namespace header files for Windows Runtime APIs in the Windows App SDK.
