### ISSUE TITLE
Cryptic errors when WindowsPackageType is set to none.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/WindowsAppSDK#2671]
### Describe the bug

In [Using the bootsrapper in a non-MSIX package](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=csharp) the recommendation is to set `WindowsPackageType` to `none`.

VS throws two cryptic errors

  1. `"Visual C++ 2015-2019 Runtime for Universal Windows Platform Apps v14.0" which targets platform "UAP"`
  2. `Project "AppLifeCycleTest" targets platform "Windows", but references SDK "Visual C++ 2015-2019 UWP Desktop Runtime for native apps v14.0" which targets platform "UAP"`

The solution to remove these errors is to Include `<WinUISDKReferences>false</WinUISDKReferences>` in the `.*proj` file.

### Steps to reproduce the bug

1. Make a non-MSIX project that uses Windows App SDK.
2. Add `<WindowsPackageType>None</WindowsPackageType>` to the project file.

### Expected behavior

No errors.

### IDE

Visual Studio 2022

**Comment by LegendaryBlair** [comment]
This issue is fixed in Windows App SDK 1.2 and above, hence closing this issue.
