### ISSUE TITLE
Windows App SDK does not automagically update the framework package reference.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/WindowsAppSDK#2674]
### Describe the bug

If a package already depends on the Windows App SDK framework package then the framework package on the box is updated, the manifest isn't updated too.  It needs to be updated manually.

This causes pain and sometimes the issue "Referencing a non-existent package" isn't easily figured out.

### Steps to reproduce the bug

1. Make an MSIX package the declares a `PackageDependency` for a any version of the framework package.
2. Update the framework package on the box and remove the old version.
3. Run the MSIX made earlier.

### Expected behavior

Best case: Version is updated automatically.

Otherwise, a message notifying the developers that the version referenced isn't on the box anymore.

**Comment by chigy** [comment]
@dhoehna , This is not something we have seen community complain lately. Please repro with latest build and if you still need this fixed, please add detailed repro steps.
