### ISSUE TITLE
`WindowsAppSDKRuntime` looks like version mismatch

### ISSUE THREAD

**Issue by shelllet** [microsoft/WindowsAppSDK#2682]
![image](https://user-images.githubusercontent.com/16729017/173820916-bdbf1416-43ab-4303-9393-c1231964430d.png)

![image](https://user-images.githubusercontent.com/16729017/173820880-721da789-86eb-4e67-8c0d-81657d43a478.png)

why?

_Originally posted by @shelllet in https://github.com/microsoft/WindowsAppSDK/discussions/2626#discussioncomment-2955347_

**Comment by shelllet** [comment]
but there is no  1.1.1 version of WindowsAppRuntime  for download.

i remember that i download  latest version of WindowsAppRuntime in this link https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads

**Comment by DominicMaas** [comment]
@shelllet Scroll a bit further down -

![image](https://user-images.githubusercontent.com/5589453/176581720-e7363b89-c92a-4e07-90df-57c5184537b5.png)

**Comment by shelllet** [comment]
> @shelllet Scroll a bit further down -
> 
> ![image](https://user-images.githubusercontent.com/5589453/176581720-e7363b89-c92a-4e07-90df-57c5184537b5.png)

this does't work either, it seems like to load Microsoft.WinAppRuntime.DDLM.1000.468.658.0-x6-p2_1000.468.658.0_x64__8wekyb3d8bbwe , but this is not applicable.

![image](https://user-images.githubusercontent.com/16729017/176587116-07ef172c-b3f7-4ae7-9e46-01a40f6aae0e.png)

![image](https://user-images.githubusercontent.com/16729017/176587131-943477ca-3c22-4d07-bb6f-61751f62c064.png)

**Comment by shelllet** [comment]
![image](https://user-images.githubusercontent.com/16729017/176588643-5b02c26e-215e-4e4b-87bd-b37d3235155c.png)

**Comment by DrusTheAxe** [comment]
> ![image](https://user-images.githubusercontent.com/16729017/176587116-07ef172c-b3f7-4ae7-9e46-01a40f6aae0e.png)

That's odd how the x64 package installed but it thinks the x86 is already present and fails.

Please run the following command and share the output:

powershell -c "$(get-appxpackage micro*win*apprun*).packagefullname"

Is your app x86 or x64? Bootstrapper looks to match a DDLM package matching your architecture so knowing that plus the get-appxpackage output will help to figure out what's going on

**Comment by shelllet** [comment]
> powershell -c "$(get-appxpackage micro_win_apprun*).packagefullname"



> > ![image](https://user-images.githubusercontent.com/16729017/176587116-07ef172c-b3f7-4ae7-9e46-01a40f6aae0e.png)
> 
> That's odd how the x64 package installed but it thinks the x86 is already present and fails.
> 
> Please run the following command and share the output:
> 
> powershell -c "$(get-appxpackage micro_win_apprun*).packagefullname"
> 
> Is your app x86 or x64? Bootstrapper looks to match a DDLM package matching your architecture so knowing that plus the get-appxpackage output will help to figure out what's going on


C:\Users\admin>powershell -c "$(get-appxpackage microwinapprun*).packagefullname"

C:\Users\admin>powershell -c "$(get-appxpackage microsoft.winapprun*).packagefullname"
Microsoft.WinAppRuntime.DDLM.2.460.358.0-x6_2.460.358.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.2.460.358.0-x8_2.460.358.0_x86__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.3.469.1654.0-x6_3.469.1654.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.3.469.1654.0-x8_3.469.1654.0_x86__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.1000.468.658.0-x6-p2_1000.468.658.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.1000.468.658.0-x8-p2_1000.468.658.0_x86__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.1000.485.2229.0-x6-p3_1000.485.2229.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.1000.485.2229.0-x8-p3_1000.485.2229.0_x86__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.1000.516.2156.0-x6_1000.516.2156.0_x64__8wekyb3d8bbwe
Microsoft.WinAppRuntime.DDLM.1000.516.2156.0-x8_1000.516.2156.0_x86__8wekyb3d8bbwe

**Comment by shelllet** [comment]
when i reinstall Microsoft.WindowsAppRuntime.DDLM.1.1.msix from unzipped folder.

 Microsoft.WinAppRuntime.DDLM.1001.524.1918.0-x6_1001.524.1918.0_x64__8wekyb3d8bbwe showed in the list.
![image](https://user-images.githubusercontent.com/16729017/176598980-046ed70a-c380-468b-8b77-e71743ba1296.png)

![image](https://user-images.githubusercontent.com/16729017/176599271-8774c9ef-e537-4e12-a933-662425f686d5.png)

**Comment by DrusTheAxe** [comment]
From the list of DDLMs I’d guess you’ve previously run the installer for…
* 1.0.2
* 1.0.3
* 1.1-preview2
* 1.1-preview3
* 1.1.0

@sachintaMSFT @cwruss tag you're it

**Comment by shelllet** [comment]
> From the list of DDLMs I’d guess you’ve previously run the installer for…
> 
> * 1.0.2
> * 1.0.3
> * 1.1-preview2
> * 1.1-preview3
> * 1.1.0
> 
> @sachintaMSFT @cwruss tag you're it

👍

**Comment by DrusTheAxe** [comment]
> 👍 i also ran 1.1.1 ( WindowsAppRuntimeInstall.exe) Now, i can confirmed the 1.1.1 version of WindowsAppRuntimeInstall.exe can't work correctly.

Several bugs were fixed recently. Does this repro with the 1.1.3 installer?

**Comment by MuyuanMS** [comment]
Closing issue for now - reopen if the issue still repros now
