### ISSUE TITLE
Self contained apps fail to build with AnyCPU & RIDs

### ISSUE THREAD

**Issue by mattleibow** [microsoft/WindowsAppSDK#2684]
### Describe the bug

When building a self contained app that uses a RID instead of the platform, the build fails:

> C:\Users\mattl\.nuget\packages\microsoft.windowsappsdk\1.1.1\buildTransitive\Microsoft.WindowsAppSDK.SelfContained.targets(42,5): error : The platform 'AnyCPU' is not supported for Self Contained mode.

@Scottj1s I believe this is similar to another issue before with copying things. I copied the changes you made in the `_GetProjectArchitecture` target and it works here too.

![image](https://user-images.githubusercontent.com/1096616/176164533-c4b58f37-1e23-4119-8a74-838b1e336bfd.png)

### Steps to reproduce the bug

```
    <IsUnpackaged>true</IsUnpackaged>
    <WindowsPackageType Condition="'$(IsUnpackaged)' == 'true'">None</WindowsPackageType>
    <WindowsAppSDKSelfContained Condition="'$(IsUnpackaged)' == 'true'">true</WindowsAppSDKSelfContained>
    <SelfContained Condition="'$(IsUnpackaged)' == 'true'">true</SelfContained>
```

### Expected behavior

Builds

### NuGet package version

1.1.1

### Packaging type

Unpackaged

**Comment by sbanni** [comment]
@mattleibow The check needs to include "Any CPU" as well. When building a .sln a .metaproj gets generated that converts "Any CPU" to "AnyCPU" but if you build the .proj file directly this doesn't happen and this check breaks.

**Comment by mattleibow** [comment]
This AnyCPU vs Any CPU might affect the other locations as well then? AnyCPU is used a lot in the targets generally.

**Comment by sbanni** [comment]
> This AnyCPU vs Any CPU might affect the other locations as well then? AnyCPU is used a lot in the targets generally.

Yes, there is already another bug I filed [here](https://dev.azure.com/microsoft/OS/_workitems/edit/40111780) where I am hitting this issue. Would be a good idea to scrub the the whole repo.

**Comment by gary-89** [comment]
[Discussion/3026](https://github.com/microsoft/WindowsAppSDK/discussions/3026) helped me to solve this issue.
Just add the platform parameter to your command with `-p:Platform=...`.

**Comment by mattleibow** [comment]
In most modern frameworks - such as maui - we use RIDs. So, it does work with Platform, but I am explicitly not using it.

**Comment by mattleibow** [comment]
Related to https://github.com/microsoft/WindowsAppSDK/issues/4008

**Comment by mattleibow** [comment]
I added some more workarounds in https://github.com/microsoft/WindowsAppSDK/issues/893

**Comment by Scottj1s** [comment]
Workarounds now incorporated in Windows App SDK 1.6 Experimental 2
