### ISSUE TITLE
There is no SelectionChanged event in TreeView

### ISSUE THREAD

**Issue by tungox6** [microsoft/WindowsAppSDK#2690]
### Describe the bug

There is no SelectionChanged event in TreeView

### Steps to reproduce the bug

It is with WindowsAppSDK 1.1.1

**Comment by ghost1372** [comment]
`SelectionChanged` recently added in winui > 2.7
I think, Currently winui 3 is using  winui 2.6 so we need to wait until winui 3 update to latest winui 2.x

**Comment by btueffers** [comment]
This is being tracking in the XAML repo so we'll close this issue.
