### ISSUE TITLE
C++ VSIX tag exceeds max tag length of 50

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/WindowsAppSDK#2694]
### Describe the bug

PR #1805 added the tag "WinAppSDK" to the C++ VSIX, but this takes it slightly over the max tag length of 50. We need to shorten slightly, and C++ is slightly redundant with C++/WinRT.

Let's remove one of those.

### Steps to reproduce the bug

Running the VSIX publishing pipeline results in an error.

**Comment by DrusTheAxe** [comment]
SUGGESTION: Drop 'C++/WinRT'

BEFORE: `WindowsAppSDK, WinAppSDK, WinUI, XAML, C++, C++/WinRT` = 54 chars

AFTER: `WindowsAppSDK, WinAppSDK, WinUI, XAML, C++` = 43 chars

That aligns better with the C# VSIX tags `WindowsAppSDK, WinAppSDK, WinUI, XAML, C#, Managed` (=50 chars)

(I guess you could tack 'Native' onto the C++ string to be consistently redundant... :P How about that 'Managed' keyword? Is that all that meaningful?

**Comment by DrusTheAxe** [comment]
Do the tags need whitespace or just comma separator?

`<tags>WindowsAppSDK, WinAppSDK, WinUI, XAML, C++</tags>`

is it equally valid to say `<tags>WindowsAppSDK,WinAppSDK,WinUI,XAML,C++</tags>` ?

**Comment by riverar** [comment]
Looks wrong. Where did you get 50 characters from @DefaultRyan?

> <Tags> - This optional element lists additional semicolon-delimited text tags that are used for search hints. The Tags element is limited to 100 characters.

https://docs.microsoft.com/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2022
