### ISSUE TITLE
Windows App SDK docs are not on GitHub

### ISSUE THREAD

**Issue by sylveon** [microsoft/WindowsAppSDK#2710]
### Describe the bug

The Windows App SDK docs are not hosted on GitHub, contrarily to WinUI 2 and Win32 docs. This makes it impossible for outside contributors to suggest changes.

### Steps to reproduce the bug

1. Open a Windows App SDK doc page, for example [ItemsRepeater.ItemsSource](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.itemsrepeater.itemssource?view=windows-app-sdk-1.1).
2. Click the edit button
3. Notice you get brought to a MS-internal devops page

### Expected behavior

You get brought to the GitHub page for the specific documentation file you are attempting to edit

### Screenshots

![image](https://user-images.githubusercontent.com/6440374/177458965-e3fa9429-0437-4cad-966e-aca7c6dfb2a5.png)

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

### Additional context

N/A

**Comment by asklar** [comment]
fyi @MatchaMatch @stevewhims @Karl-Bridge-Microsoft

**Comment by Karl-Bridge-Microsoft** [comment]
This is a known issue that we're currently working to correct. Thanks for your patience!

**Comment by Karl-Bridge-Microsoft** [comment]
Public mirror repos have been created and hooked up to the private repos for both WinRT and Win32 APIs in Windows App SDK. I tested PRs with my personal ID in topics from both and was able to manage both with my Microsoft-associated ID.

https://github.com/MicrosoftDocs/winapps-winrt-api

https://github.com/MicrosoftDocs/winapps-win32-api

**Comment by Karl-Bridge-Microsoft** [comment]
@sylveon - please confirm and close issue if resolved. Thanks!

**Comment by sylveon** [comment]
Yep, appears to be fixed!
