### ISSUE TITLE
Exception thrown at 0x21792849 (threadpoolwinrt.dll) 0xC0000005: Access violation reading location 0x00000000.

### ISSUE THREAD

**Issue by shyamshr93** [microsoft/WindowsAppSDK#2712]
### Describe the bug

Closing the app while it is running and deployed from Visual Studio gives this exception. Only happens in version Windows App SDK 1.1 and after.

### Steps to reproduce the bug

1. Create a packaged Windows App SDK app (1.1 and above).
2. Run the app from Visual Studio.
3. Just close the app (not from visual studio "stop debug" button  ).

### Expected behavior

No exception should be given.

### Screenshots

![image](https://user-images.githubusercontent.com/25634212/177477126-39bef03c-1c20-4f37-8e13-d4bca8db2b82.png)

### NuGet package version

1.1.2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by manodasanW** [comment]
@shyamshr93 are you still able to repro this issue?  I tried your repro steps with a blank app on the OS version you mentioned but haven't been able to repro it.  If you are still able to repro it, can you confirm whether you see it with a blank app or just in your app?  And are you able to provide what you see under call stack in Visual Studio when you hit this?

**Comment by shyamshr93** [comment]
@manodasanW yes it is still happening in latest version (1.1.4) too as you can see below. My app has multiple webview2 if that can help. 
![image](https://user-images.githubusercontent.com/25634212/187842764-26134224-6bd7-4f56-a43d-997ac3da6eeb.png)

**Comment by codendone** [comment]
@shyamshr93 The `threadpoolwinrt.pdb` in your screenshot and your mention of WebView2 suggests you're seeing microsoft/microsoft-ui-xaml#7260. If you call `Close()` on the WebView2 elements before the app closes, hopefully that should workaround the issue.

**Comment by shyamshr93** [comment]
@codendone https://github.com/dotnet/maui/issues/7317#issuecomment-1231940453 this workaround seems to have fix the issue. I can't reproduce the bug now.

**Comment by codendone** [comment]
Excellent! Please use that workaround for now. You can track the issue I mentioned for when this gets fixed in the platform.
