### ISSUE TITLE
How to create a custom cursor?

### ISSUE THREAD

**Issue by ricd** [microsoft/WindowsAppSDK#2728]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/2722

<div type='discussions-op-text'>

<sup>Originally posted by **ricd** July 11, 2022</sup>
Setup:
Latest Windows App SDK (10.0.25151-preview).  A C#, Windows App SDK, Win UI 3 desktop application.

I need to change the cursor as the user interacts with a Grid.  I have sub-classed the Grid in order to provide access to its ProtectedCursor:
```
internal class Grid2 : Grid
{
	public InputCursor Cursor
	{
		get => ProtectedCursor;

		set => ProtectedCursor = value;
	}
}
```
I have created a .res file containing cursors (.cur) in a separate C++ DLL project and added that resource file as a Win32Resouce to my Windows App SDK/WinUI 3 desktop application project.

As a test, I am using the PointerPressed event from the subclassed Grid to change the cursor:
```
private void OnPointerPressed(object sender, PointerRoutedEventArgs e)
{
       // 102 is the resource id of a cursor in the .res file.
	var cursor = new CoreCursor(Windows.UI.Core.CoreCursorType.Custom, 102);

	var t = InputCursor.CreateFromCoreCursor(cursor);
	_rootGrid.Cursor = t;
}
```
However, the effect of the code above is to simply load a built-in cursor.  Indeed, as I play with the resource id value, setting it to values in the range [100, 118] I see a variety of 'standard' cursors including some that are not in the CoreCursorType enumeration.

The same .res file works in a UWP application, so I know the problem is not with the resources...  

If I change the resource id of one of the cursors to, say, 200, recreate the .res file and try to create a CoreCursor using that resource Id, I get a System.Runtime,InteropServices.COMException: The Specified resource name cannot be found in the image file.

Why  when creating a new CoreCursor  with CoreCursorType.Custom, and a uint resource Id am I seeing build-in cursors?</div>

**Comment by haonanttt** [comment]
From the original discussion thread https://github.com/microsoft/WindowsAppSDK/discussions/2722, the answer was got
