### ISSUE TITLE
Unable to attach to CoreCLR (Operation not supported) when launching WinUI 3 Unpackaged project.

### ISSUE THREAD

**Issue by xiaoli8848** [microsoft/WindowsAppSDK#2744]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/2743

<div type='discussions-op-text'>

<sup>Originally posted by **xiaoli8848** July 16, 2022</sup>
![屏幕截图 2022-07-16 101906](https://user-images.githubusercontent.com/45089374/179335819-dbdb135e-2c72-4501-9952-8b8feb072d01.png)

As shown in the picture, when I run a WinUI3 Unpackaged project, it immediately shows this error and stops debugging after clicking OK.It shows "**_Unable to attach to CoreCLR. Unknown error: 0x80004005_**".

I looked up articles on the web, but all the solutions given were for "access denied" errors. I also tried **resetting my computer**, but that didn't help either! What should I do?</div>

**Comment by smourier** [comment]
I have the same issue trying to debug for x64, and I ported my app to WinApp SDK 1.1.2 (previously it worked with WinApp SDK 1.1.1). Here are the relevant part of my csproj:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MyApp</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win10-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
  </PropertyGroup>

  <PropertyGroup>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.1" />
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <!-- Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
       Tools extension to be activated for this project even if the Windows App SDK Nuget
       package has not yet been restored -->
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnablePreviewMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
</Project>

```

**Comment by manodasanW** [comment]
@xiaoli8848 @smourier Can you confirm what version of Visual Studio you are using and whether you happen to have `PublishSingleFile` enabled in your publish profile?

**Comment by smourier** [comment]
> @xiaoli8848 @smourier Can you confirm what version of Visual Studio you are using and whether you happen to have `PublishSingleFile` enabled in your publish profile?

Hi, I'm now running

Visual Studio 17.3.3
WindowsAppSDK 1.1.4
Microsoft.Windows.SDK.BuildTools 10.0.22621.1

and the message has changed, it's now *"Unable to attach to CoreCLR. The debugger's protocol is incompatible with the debuggee."*

Indeed, the win10-x64.pubxml is configured like this (not sure how/why/when it ended up like this, was it created by default?):

```
<Project>
  <PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Platform>x64</Platform>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <PublishDir>bin\\\win10-x64\publish\</PublishDir>
    <SelfContained>true</SelfContained>
    <Configuration>Release</Configuration>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
</Project>
```

And if I change `PublishSingleFile` to `false`, I can now debug successfully.

**Comment by xiaoli8848** [comment]
@manodasanW @smourier 
Thanks for your help. Sorry for not continuing to provide more information as I'm busy with my open source project.
I'm sorry that some of the original project files were deleted because I solved the problem later.

I had this problem with Windows App SDK version 1.1.1 and 1.1.2 at the time, but when I created another new project and copied all the path structure and code of the original project to the new project, the problem disappeared.
I think I may have checked the PublishSingleFile option when the original project was packaged and released, which caused this problem?

**Comment by manodasanW** [comment]
Thanks @smourier and @xiaoli8848 for your replies.  This does look related to `PublishSingleFile` and is tracked by https://github.com/dotnet/runtime/issues/45382 which looks to be resolved for .NET 7 per the bug.

Looking at the current WinAppSDK template, `PublishSingleFile` does look to be disabled by default, but if Visual Studio was used to create the publish profile, it might have been enabled.
