### ISSUE TITLE
Deployment issue with 1.1.2 update

### ISSUE THREAD

**Issue by timmarriott** [microsoft/WindowsAppSDK#2749]
### Describe the bug

I attempted to move from 1.0.3 to 1.1.2 today and I am seeing a deployment issue after an incremental build.  It works fine after a clean build.  

My application is a desktop application which has 3 Windows Runtime Components included.  

=================================================================================
This is seen in VS deployment tab:

Creating a new clean layout...
Copying files: Total 282 mb to layout...
Checking whether required frameworks are installed...
Registering the application to run from layout...
DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE012: App manifest validation error: The app manifest must be valid as per schema: Line 50, Column 8, Reason: Content for element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}InProcessServer' is incomplete according to the DTD/Schema.
Expecting: {http://schemas.microsoft.com/appx/manifest/foundation/windows10}ActivatableClass.

=================================================================================
Here is the VS generated Manifest it seems to be complaining about:

<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" IgnorableNamespaces="uap rescap build" xmlns:build="http://schemas.microsoft.com/developer/appx/2015/build">
  
  <Identity Name="Hexagon.AGTEK.CloudView" Publisher="CN=AGTEK Development Company, O=AGTEK Development Company, S=California, C=US" Version="1.0.49.0" ProcessorArchitecture="x64" />
  <Properties>
    <DisplayName>CloudView</DisplayName>
    <PublisherDisplayName>Hexagon, Agtek Inc</PublisherDisplayName>
    <Logo>Assets\StoreLogo.png</Logo>
  </Properties>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.17763.0" MaxVersionTested="10.0.22000.0" />
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.19041.0" />
    <PackageDependency Name="Microsoft.WindowsAppRuntime.1.1" MinVersion="1002.543.1943.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.VCLibs.140.00.Debug" MinVersion="14.0.30704.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
    <PackageDependency Name="Microsoft.VCLibs.140.00.Debug.UWPDesktop" MinVersion="14.0.30704.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
  </Dependencies>
  <Resources>
    <Resource Language="EN-US" />
    <Resource Language="EN-AU" />
    <Resource Language="EN-GB" />
    <Resource Language="DA" />
    <Resource Language="DE" />
    <Resource Language="ES" />
    <Resource Language="FR" />
    <Resource Language="JA" />
    <Resource Language="NB" />
    <Resource Language="NL" />
    <Resource Language="SV" />
    <Resource Language="ZH-CN" />
  </Resources>
  <Applications>
    <Application Id="App" Executable="CloudView.exe" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements DisplayName="CloudView" Description="CloudView is a point cloud viewer and editing application used to read, view and clean point cloud data." BackgroundColor="transparent" Square150x150Logo="Assets\Square150x150Logo.png" Square44x44Logo="Assets\Square44x44Logo.png">
        <uap:DefaultTile Wide310x150Logo="Assets\Wide310x150Logo.png" />
        <uap:SplashScreen Image="Assets\SplashScreen.png" />
      </uap:VisualElements>
    </Application>
  </Applications>
  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
  </Capabilities>
  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>AccessServerWRC.dll</Path>
      </InProcessServer>
    </Extension>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>DSFWWRC.dll</Path>
      </InProcessServer>
    </Extension>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>PointCloudWRC.dll</Path>
      </InProcessServer>
    </Extension>
  </Extensions>
  <build:Metadata>
    <build:Item Name="cl.exe" Version="19.32.31332.0" />
    <build:Item Name="OptimizingToolset" Value="None" />
    <build:Item Name="TargetRuntime" Value="Native" />
    <build:Item Name="Microsoft.UI.Xaml.Markup.Compiler.dll" Version="1.0.0.0" />
    <build:Item Name="Microsoft.UniversalCRT.Debug" Version="10.0.22000.0" />
    <build:Item Name="makepri.exe" Version="10.0.22621.1 (WinBuild.160101.0800)" />
  </build:Metadata>
</Package>

### Steps to reproduce the bug

I don't know how to reproduce outside my application.  I suspect creating a basic application with a runtime component referenced might do it.

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by aborziak-ms** [comment]
Just got the same issue. Need to run Rebuild each time, otherwise getting the exact same error: 
```
DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE012: App manifest validation error: The app manifest must be valid as per schema: Line 39, Column 8, Reason: Content for element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}InProcessServer' is incomplete according to the DTD/Schema.
Expecting: {http://schemas.microsoft.com/appx/manifest/foundation/windows10}ActivatableClass.
```
WindowsAppSDK 1.1.3

**Comment by DrusTheAxe** [comment]
@BenJKuhn  ?

**Comment by DefaultRyan** [comment]
This is currently being tracked by internal bug http://task.ms/40265852, assigned to @evelynwu-msft .

**Comment by timmarriott** [comment]
Now I am seeing a bit of a different issue with 1.1.4.  The Blank Desktop App template will not deploy for debug.  It hangs trying on these messages:
Framework: Microsoft.WindowsAppRuntime.1.1/X64, app package version 1004.584.2120.0 is not currently installed.
Installing missing frameworks...

The specific project template is "Blank App, Packaged (WinUI 3 in Desktop)"

**Comment by timmarriott** [comment]
The problem appears to be that the AppManifest.xml file that Visual Studio creates in the intermediate AppX directory is wrong.  Specifically the Extensions section.  Here is that section after a "Clean Build":

  <Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>AccessServerWRC.dll</Path>
        <ActivatableClass ActivatableClassId="AccessServerWRC.AgFileModel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.AccessPageVM" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.LicenseKeyItem" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.AccessServerModel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.AgItemModel" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.AgItemTemplateSelector" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.AccessImportControl" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.AccessPage" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.Bounds" ThreadingModel="both" />
        <ActivatableClass ActivatableClassId="AccessServerWRC.XamlMetaDataProvider" ThreadingModel="both" />
      </InProcessServer>
    </Extension>
  </Extensions>

Here is the same section after an incremental build:

<Extensions>
    <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>AccessServerWRC.dll</Path>
      </InProcessServer>
    </Extension>
  </Extensions>

**Comment by Paul-CPlusPlus** [comment]
I'm also experiencing this issue after updating Visual Studio Community(17.3.2)  and packages recently.

WindowsAppSDK  1.1.4

AppManifest.xml file is affected as described by timmarriott.

**Comment by jessesna** [comment]
I can observe the same with VS 17.3.3 and AppSDK 1.1.3.
As soon as i install _Microsoft.Graphics.Win2D_ i have to rebuild after every change or this error will be thown while updating the layout:
```
DEP0700: Registration of the app failed. [0x80080204] error 0xC00CE012: App manifest validation error: The app manifest must be valid as per schema: Line 39, Column 8, Reason: Content for element '{http://schemas.microsoft.com/appx/manifest/foundation/windows10}InProcessServer' is incomplete according to the DTD/Schema.
Expecting: {http://schemas.microsoft.com/appx/manifest/foundation/windows10}ActivatableClass.
```
Upgrading to AppSDK 1.1.4 doesn't solve the problem.

**Comment by lyahdav** [comment]
Still happens on WindowsAppSDK 1.1.5

**Comment by timmarriott** [comment]
I have been able to update my Runtime components to 1.1.4 and leave my main application at 1.0.4 and it will deploy after an incremental build.  This is a pretty major issue for developers.  I can't move forward until it is fixed.  We are actually trying to get a product out the door.

**Comment by evelynwu-msft** [comment]
The fix for this will ship in 1.2. In the meantime, you can work around this issue by including the following in your project file:
```xml
<PropertyGroup>
  <AppxWinMdCacheEnabled>false</AppxWinMdCacheEnabled>
</PropertyGroup>
```

**Comment by Paul-CPlusPlus** [comment]
The fix works for me.  Thank you very much.
I'm about to add several large subsystems to my application and recompiling everything all the time would have been unpleasant.

**Comment by DenOsipov** [comment]
Reported this block bug.
Please upvote ticket by link below:
https://developercommunity.visualstudio.com/t/C-WinRT-App--WRT-Component-deploy-err/10175581

**Comment by Paul-CPlusPlus** [comment]
I confirm that WindowsAppSDK 1.2.221116.1 fixes this issue.
