### ISSUE TITLE
Embrace other MS teams to use MSIX instead of old MSI installers

### ISSUE THREAD

**Issue by jaigak** [microsoft/WindowsAppSDK#276]
# Proposal: Adopt MSIX for all Microsoft applications
Today many Microsoft apps like Teams, VS code are using MSI or EXE installers. Please tell them to use MSIX going forward on Windows if possible

## Summary
The problem with MSI and EXE installers is that they don't cleanly uninstall slowing down your PC over time and 20 different updaters run all the time in the background consuming and wasting resources instead of Windows Updates doing the job. Because of this Windows users need to reset their PC to get it fast again. Although I think Windows shouldn't restrict to the Store, they should definitely push MSIX installers and sideload it with the app installer more to avoid these issues and to stop destroying customer PC or slowing it down. Please tell other teams to use MSIX installers if possible.

## Rationale

* MSIX installers are verified and secure
* Windows PCs will be not slow down after installing/uninstalling these products
* Remove the need to use the Reset this PC option unless you want a fresh copy or you are donating your PC.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow end-users to download all their MS apps in a modern MSIX installer if possible | Must |
| Microsoft apps that provide an MSIX version shouldn't provide other installers unless it supports older Windows versions | Must |
| Provide free signed certifications on behalf of the Windows team for those who can't afford to pay | Could |

**Comment by stevewri** [comment]
@jonwis - is there an MSIX repo this could go to?

**Comment by jonwis** [comment]
@jvintzel  is very aware of this ask. I don't know of another place to go ask this specific question, but there is http://github.com/microsoft/msix-packaging which is the home of the MSIX team.

**Comment by jvintzel** [comment]
> @jvintzel is very aware of this ask. I don't know of another place to go ask this specific question, but there is [http://github.com/microsoft/msix-packaging](https://github.com/microsoft/msix-packaging) which is the home of the MSIX team.

My recommendation is to request MSIX with the specific product teams.  For example VS Code has the ask in their backlog and are working towards that along with other community asks.

**Comment by Jaiganeshkumaran** [comment]
@jvintzel Not all Microsoft products are open-source so what should I do?

**Comment by jvintzel** [comment]
> @jvintzel Not all Microsoft products are open-source so what should I do?

For apps that are not open source using the in-app feedback option is the best approach.

**Comment by Poopooracoocoo** [comment]
ideally microsoft would use msix, winui and uwp. you know. follow their own advice...

and @jvintzel suggests the feedback hub? that piece of shit?

powertoys switched from an msi installer to an exe. oh i've started giving examples... lets see. edge. skype. any actual microsoft product. the photos and films & tv apps are uwp apps that use winui but are total trash, both functionality and performance wise, making those techs look terrible.  

nah i can't be bothered explaining anymore. it's fuckin obvious.

**Comment by mshaikhcool** [comment]
@Jaiganeshkumaran MSIX is POS bro, NO ONE CARES examples including - Edge chromium, VS Code, VS, teams , Office. that's the whole reason that windows 11 store had to allow non-MSIX. 😆

**Comment by v1ckxy** [comment]
I just saw this thread and I have the moral obligation to write here:
Moving everything to msix and appx, was just a suicidal movement: Everything nonsensically tied to a license.xml file, even if its free or not.

**Comment by hoshiizumiya** [comment]
As far as I know, it’s not possible to launch an MSIX app as administrator by default, so I have to run additional shell commands at startup—and there’s no support for customizing the installation process either(short cut, startup and so on).

Rather than boasting about how great MSIX is, Microsoft should focus on developing genuinely useful features. In practice, MSIX installations often hang unexpectedly without any warning, unlike traditional MSI or EXE installers.

Overall, the benefits of MSIX are minimal compared to older packaging formats. And the stupid certificate install.
