### ISSUE TITLE
Failed to package and publish app project that uses .appinstaller

### ISSUE THREAD

**Issue by evelynwu-msft** [microsoft/WindowsAppSDK#2773]
### Describe the bug

*Copied from http://tasks.ms/40475506*

When an app project is configured to enable automatic updates of its package when it's sideloaded (i.e. `.appinstaller`), a build failure will be encountered when using VS 17.3.

### Steps to reproduce the bug

Steps to reproduce:
1. Create a C# Blank App, Packged (WinUI 3 in Desktop) Project.
2. Right click on project node -> Package and Publish -> Create App Packages
3. Select Sideloading with "Enable automatic updates" checked
4. Select "Yes, select a certificate" -> Create -> Next -> Next
5. Type a valid location in Installer location -> Create
6. Observe the result in output window

### Expected behavior

Expected result:
Publish successfully with app package and .appinstaller files created.

Actual Result:
Failed 1 error: The "Microsoft.Build.Utilities.TaskItem[]" type of the "AppInstallerFileWrites" parameter of the "WinAppSdkGenerateAppInstallerFile" task is not supported by MSBuild. App2 C:\Users\<username>\.nuget\packages\microsoft.windowsappsdk\1.1.0\buildTransitive\Microsoft.Build.Msix.Packaging.targets

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022-preview

**Comment by evelynwu-msft** [comment]
This has been fixed internally and will be included in the next Windows App SDK 1.1 servicing update. In the meantime, affected users should avoid updating to Visual Studio 2022 17.3.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.1.4` has been released which fixes this issue.

Handy links:
* [Release Notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-114)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.1.4)
