### ISSUE TITLE
KERNELBASE.dll, version: 10.0.19041.1826, 0xc000027b. Installed .msix MAUI windows APP ERROR. Facility_null, E_pointer

### ISSUE THREAD

**Issue by 8m0** [microsoft/WindowsAppSDK#2822]
### Describe the bug

Hello, i installed generated by MAUI .msix on other pc, not the one which i use to develop the app the. Everything is fine when i run it with VS2022 on pc i develop the app. The program when i launch doesn't even appear.

**Didn't help:**

1 - Installing: 
`<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.1.3" />`, with build and without it.
[relates to this](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-packaged-apps#stable-version)

2 - Setting to .csproj:
`<WinUISDKReferences>true</WinUISDKReferences> `
Or
`
<Target Name="_RemoveStaticWebAssetsDevelopmentManifest" BeforeTargets="GetCopyToOutputDirectoryItems">
		
		<ItemGroup>
			<ContentWithTargetPath Remove="$(StaticWebAssetDevelopmentManifestPath)" />
		</ItemGroup>
	</Target>
`
[relates to this](https://github.com/dotnet/maui/issues/5024#issuecomment-1072582009)

3 - Installing [latest-supported-vc-redist](https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

4 - Getting files out of WindowsApps folder. [relates to this...](https://en.wikipedia.org/wiki/Shit)

5 - Installing VS for Maui App UI development, .NET desktop development, including Windows App SDK C# Templates(I don't know which version it is!) on not working pc.

**Event Viewer:**
```
Faulting application name: qqq.exe, version: 1.0.0.0, time stamp: 0x6283e0e1

Faulting module name: KERNELBASE.dll, version: 10.0.19041.1826, time stamp: 0x299341e8
Exception code: 0xc000027b
Fault offset: 0x000000000010fb62
Faulting process id: 0x1de0
Faulting application start time: 0x01d8a84a08b3ec15
Faulting application path: C:\Program Files\WindowsApps\65645ABF-90EB-4C5D-BE8E-1B1FFABCD4F8_1.0.0.1_x64__48t02jydb15qe\qqq.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 83828384-16a0-413c-b50f-e0552c39eea6
Faulting package full name: 65645ABF-90EB-4C5D-BE8E-1B1FFABCD4F8_1.0.0.1_x64__48t02jydb15qe
Faulting package-relative application ID: App
```

### Steps to reproduce the bug

Followed the guide here:
https://docs.microsoft.com/en-us/dotnet/maui/windows/deployment/overview

### Expected behavior

Run normaly.

### Screenshots

WinDBG:

![photo_2022-08-05_11-54-45](https://user-images.githubusercontent.com/33127649/183065549-53b6debd-0f99-4f93-bafa-b6983142e2e9.jpg)
![photo_2022-08-05_11-54-47](https://user-images.githubusercontent.com/33127649/183065563-f0959c39-d912-45b7-9535-c00808ff9b6c.jpg)
![photo_2022-08-05_11-54-48](https://user-images.githubusercontent.com/33127649/183065569-ae9b1d3b-263a-4756-9529-a27e9169b1a7.jpg)
![photo_2022-08-05_11-54-54](https://user-images.githubusercontent.com/33127649/183065577-8d1eb0c8-3464-465b-9ede-7bdf548d0aa9.jpg)
![photo_2022-08-05_13-24-14](https://user-images.githubusercontent.com/33127649/183067790-1fddfa11-943a-4846-a0c2-a9a3e53c3233.jpg)

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2022-preview

**Comment by 8m0** [comment]
Ok, i have news. 
So for some reason after i updated NuGet packages, my app stopped seeing Android Resources Raw files(Ambiguous). After some tries to fix this i decided to clone my app from repository to another folder and understand what's exactly happened. When i ran my program for Windows i got null reference error trying to Deserialize Json(Newtonsoft.Json.JsonConvert.DeserializeObject<T>(json)), and the json string i get with Preferences.Get, because i save info there. That's stupid mistake by me, but at the same time i didn't get the error from at at least 100 runs from VS.
After i fixed everything is good.

So anyone who stuck as me, it makes sense to try clone your repository to another folder and try to run it with VS clean.

**Comment by MagicAndre1981** [comment]
ok, so you run into [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/5221), where the NULL reference exception is not handled and simply crashes the app directly. @Kristallranke also check your code for exceptions that you [don't handle in your issue](https://github.com/dotnet/maui/issues/7473)
