### ISSUE TITLE
Issue with resizing WASDK Apps

### ISSUE THREAD

**Issue by CalcuIator** [microsoft/WindowsAppSDK#2852]
When resizing a WASDK App, the content of the app's resizing  is delayed causing a white or black void. There's also more resizing issues like flickering

https://user-images.githubusercontent.com/104047615/184443764-3cd47ba6-fddd-4114-b5d5-b566bf6c8a4d.MOV

**Comment by castorix** [comment]
There was a similar issue about flickering on resizing : [#5148](https://github.com/microsoft/microsoft-ui-xaml/issues/5148)

**Comment by codendone** [comment]
Thanks for linking, @castorix! That is the correct issue for tracking. We don't yet have an ETA for improving this, though the multiple tasks required remain on our radar.
