### ISSUE TITLE
UWP DataTemplate LoadContent has memory leak when the template root element is not a framework control

### ISSUE THREAD

**Issue by h82258652** [microsoft/WindowsAppSDK#2855]
### Describe the bug

When calling ```DataTemplate.LoadContent```, the memory will leak if the root element is not a framework control.

### Steps to reproduce the bug

I create a repro demo here: https://github.com/h82258652/UWPDataTemplateLoadContentLeak
1. Launch demo.
2. Click the **FrameworkTemplate** button.
3. Click the **GC collect** button.
4. Click the **Show alive count** button, it should display **Alive reference count: 0**.
5. Click the **UserControlTemplate** button.
6. Click the **GC collect** button.
7. Click the **Show alive count** button, it should display **Alive reference count: 100**.
8. Click the **FrameworkControlHostUserControlTemplate** button.
9. Click the **GC collect** button.
10. Click the **Show alive count** button, it should display **Alive reference count: 0**.

### Expected behavior

The seven step should display **Alive reference count: 0**.

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Insider Build (22622.575)

### IDE

Visual Studio 2022

**Comment by btueffers** [comment]
Hi @h82258652, since this is a UWP issue the appropriate place would be either Feedback Hub or the [Microsoft UWP Q&A](https://docs.microsoft.com/en-us/answers/topics/uwp.html).
