### ISSUE TITLE
Restart API does not care if an updated version is available

### ISSUE THREAD

**Issue by Balkoth** [microsoft/WindowsAppSDK#2863]
### Describe the bug

If the app is distributed through an appinstaller calling `Microsoft.Windows.AppLifecycle.AppInstance.Restart("");` does not check if an update is available.

### Steps to reproduce the bug

1. Create a new packaged WinUI3 project
2. Update the app with a call to `Microsoft.Windows.AppLifecycle.AppInstance.Restart("");` in the OnClick event of the button
3. Add the following *.appinstaller file:
```
<?xml version="1.0" encoding="utf-8" ?>
<AppInstaller Uri="{AppInstallerUri}"
              Version="{Version}"
              xmlns="http://schemas.microsoft.com/appx/appinstaller/2018">

  <MainBundle Name="{Name}"
              Version="{Version}"
              Publisher="{Publisher}"
              Uri="{MainPackageUri}"/>

  <UpdateSettings>
    <OnLaunch HoursBetweenUpdateChecks="0"
              ShowPrompt="true"
              UpdateBlocksActivation="true" />
    <AutomaticBackgroundTask />
    <ForceUpdateFromAnyVersion>true</ForceUpdateFromAnyVersion>
  </UpdateSettings>

</AppInstaller>
```
4. Create an msix installer with through "Package and Publish" -> "Create App Packages..."
- Choose "Sideloading" and "Enable automatic updates" 
- Let the wizard create the AppPackages
5. Copy the results to the folder given in the wizard
6. Install through the appinstaller
7. Open the installed application
8. Increment the version and publish your app again
9. Click the button in the running app to get `Microsoft.Windows.AppLifecycle.AppInstance.Restart("");` to execute
10. Watch how the app restarts without prompting to update

### Expected behavior

The expected behaviour is that the app shows the user the appinstaller to update the app.

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by andreww-msft** [comment]
This is arguably a bug - but the initial feature scope didn't explicitly include this scenario, so I'll add it to our backlog as a feature request, and track it internally.
