### ISSUE TITLE
#including MddBootstrap.h produces 300 errors in a non-packaged CPPWinrt application.

### ISSUE THREAD

**Issue by dhoehna** [microsoft/WindowsAppSDK#2866]
### Describe the bug

Looking through the myrad of WIndows App SDK docs, if I want to call `MddBootstrapInitialize2 ` from a non-packaged cppwinrt app I need to 

1. declare `<WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>` from [Opting out of automatic module initialization](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-run-time#opting-out-of-automatic-module-initialization)
2. `#include "MddBootstrap/h"` from [MddBootstrapInitialize2 function](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/win32/mddbootstrap/nf-mddbootstrap-mddbootstrapinitialize2)
I do that.  Then I get, in this instance, 298 error.  Mostly it looks like somethig, somewhere, is redefining stuff in AppModel.h

### Steps to reproduce the bug

1. Create a new project
2. Select Windows Console Application (C+/WinRT)
3. Name the project what you want
    1. Target Version: 22621
    2. Minimum Version 17763
4.   Open up `Manage Nuget Packages for Solution"
5. Install Windows App SDK.  My example uses `1.1.4`
6. Add `#include "MddBootstrap.h"` to main.cpp
7. Build, or wait for intellisense to catch up.
8. Get errors.

### Expected behavior

No errors.

### Screenshots

![image](https://user-images.githubusercontent.com/2517139/185254359-a945d3d0-3dd9-4e73-b6f3-0c8d4239d834.png)

### NuGet package version

1.1.4

### Packaging type

Unpackaged

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

### Additional context

**Comment by DarranRowe** [comment]
If you include Windows.h before MddBootstrap.h, does this help?
I'm thinking that appmodel.h uses definitions from the core windows headers, but it doesn't include it itself. MddBootstrap.h only includes appmodel.h so it doesn't satisfy the requirements for including it.

**Comment by dhoehna** [comment]
@DarranRowe That was the fix.  Adding `#include <windows.h>` before `#include "MddBootstrap.h" fixed the issue.

**Comment by dhoehna** [comment]
Good bot.
