### ISSUE TITLE
Setting WindowsPackageType to None makes Visual Studio think it is missing SDK references

### ISSUE THREAD

**Issue by Balkoth** [microsoft/WindowsAppSDK#2870]
### Describe the bug

Setting WindowsPackageType to None makes Visual Studio think it is missing SDK references. I could not find any information on how to resolve this, the project builds and runs fine. Is there something wrong with my installation or is this common behaviour? 

What needs to be done to get rid of those exclamation marks?

### Steps to reproduce the bug

1. Create a new WinUI3 project
2. Add `<WindowsPackageType>None</WindowsPackageType>`
3. An SDK node gets added under Dependencies with exclamation marks showing something is wrong
![image](https://user-images.githubusercontent.com/80055480/185338865-e4eb46c9-4e4c-4bf3-8a39-eb8e01a1242c.png)

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by dhoehna** [comment]
Just curious.  I also ran into the, somewhat same issue with `<WindowsPackageType>None</WindowsPackageType>` are you getting any errors when building?  

This is what I got when I set the WindowsPackageType property to none.

https://github.com/microsoft/WindowsAppSDK/issues/2671

**Comment by Balkoth** [comment]
In a C# project I do not see any build errors.

**Comment by dhoehna** [comment]
I was able to repro the issue.

All locations referenced via VS are on my computer.  I verified all of them.

@btueffers do you know of any VS folks who could chime in and tell us what the issue is?  

Dotnet restore does not work.  Says everything is up to date.  @DrusTheAxe do you know if WASDK behind-the-scenes magic adds SDK depdencies?

**Comment by DrusTheAxe** [comment]
> Dotnet restore does not work. Says everything is up to date. @DrusTheAxe do you know if WASDK behind-the-scenes magic adds SDK depdencies?

If you're making a packaged app then yes, I think VCLibs may be automagically added to your manifest. Not sure that's going on here or any other 'magic' VS props/targets may be doing. But I know who to ask ;-)

@Scottj1s @evelynwu-msft  ?

**Comment by Scottj1s** [comment]
This issue is fixed in the next release of Windows App SDK, 1.2 Preview 1.

Internal:
https://dev.azure.com/microsoft/WinUI/_git/microsoft-ui-xaml-lift/pullrequest/7348995?_a=files

**Comment by dhoehna** [comment]
> This issue is fixed in the next release of Windows App SDK, 1.2 Preview 1.

Tight.  Can this be closed then?

**Comment by Scottj1s** [comment]
It's generally best to leave closing to the opener, after verifying.

**Comment by Balkoth** [comment]
With WASDK 1.2 and Visual Studio 17.4.1 no more SDK node is being shown, so i guess this is fixed.
