### ISSUE TITLE
Cannot F5/Debug Administrator WinAppSDK App.

### ISSUE THREAD

**Issue by ivberg** [microsoft/WindowsAppSDK#2880]
### Describe the bug

Cannot F5/Debug Administrator WinAppSDK App.

Program will elevate and launch. Visual Studio Debugger will appear to attach to the process but no breakpoints can be hit.

Workaround: Detach and re-attach to process OR deploy/launch app and then attach to it.

### Steps to reproduce the bug

1. Produce a C# WinAppSDK 1.1.4 app using VS 2022 on Win11
2. Modify app.manifest
--app.manifest--
`
\ <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
     <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator"/>
      </requestedPrivileges>
    </security>
  </trustInfo>  \
`
3. For MSIX package modify capabilities to allow Elevation
`
 \ <Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <rescap:Capability Name="allowElevation" />
  </Capabilities>  \
`

### Expected behavior

You can launch and debug app w/o needing workarounds

### NuGet package version

1.1.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

This was originally filed as this bug but it was marked closed fixed when WinAppSDK 1.1 officially supported admin. However, the debugger issue reported in that bug was never actually fixed
https://github.com/microsoft/WindowsAppSDK/issues/896

**Comment by ivberg** [comment]
FYI @mikebattista as he closed the original issue

**Comment by BenJKuhn** [comment]
We did some investigation and determined this isn't an App SDK issue. This is a limitation of how debugging for packaged applications work. 

The debugging workflow was originally designed for app container and "full trust" applications. This debugging launch workflow depends in part on data controlled by the user (non-elevated) and the OS intentionally fails rather than use that data when running elevated, since it requires less privileges to modify ("full trust"). Either Visual Studio, the OS, or both need changes to make this workflow succeed for apps running with administrative privileges. 

We're aware of and tracking this as an OS issue.

**Comment by ivberg** [comment]
@BenJKuhn  can you reference the OS issue here? This has not gotten traction or fixed since WinAppSDK was ReUnion 0.5. It's going nowhere. Meanwhile VS can post-attach just fine to an admin process. It feels like this a real issue affecting the WinAppSDK dev workflow and now on a supported feature. It should be left open because whether or not it's a bug somewhere else - it's unique to WinAppSDK and is still not fixed whatever the cause is.

**Comment by BenJKuhn** [comment]
I agree this is important to App SDK developers. There's nothing to do in the App SDK project to address this and as a general policy we don't track OS issues here.

Here's the work item tracking the underlying issue:
https://task.ms/40511962 (MS Internal only)

**Comment by seven-mile** [comment]
Still repro for 1.4preview2. Any progress on this? Excuse me. I have to reply here because I have no other way to track such issue.

**Comment by codendone** [comment]
@seven-mile Looking at the internal task, it is still pending with no ETA.

**Comment by AliShahesmaeili** [comment]
@BenJKuhn 
@codendone 
Any news? We are in 2025!

**Comment by tinodin** [comment]
One way to fix it is to set "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" "EnableLua" to 0 though this will run every application as admin no matter what.

This should be fixed immediately!
