### ISSUE TITLE
Unable to compile clean WinUI 3 app due to strange windowsappruntime dependency issue

### ISSUE THREAD

**Issue by xEsteem** [microsoft/WindowsAppSDK#2888]
### Describe the bug

Im trying to toy with WinUI 3 and so ive created a brand new blank WinUI 3 packaged app in Visual Studio. Upon compiling i get a strange error about a missing windowsappruntime dependency issue, in which the error lists a required version of the windows app runtime, but then goes on to list that exact same runtime in the list of currently installed windows app runtimes, making this very confusing.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF3] Windows cannot install package fcda12ca-4fd1-45e7-ac84-c219ab9fd2da_1.0.0.0_x64__wsz9wrv37504r because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.1" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 1003.565.600.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.1" currently installed are: {Microsoft.WindowsAppRuntime.1.1_1002.543.1943.0_x64__8wekyb3d8bbwe Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x86__8wekyb3d8bbwe Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe}	WinUI3App			
```

To try and remedy this, ive tried to uninstall and reinstall 1.1.3, and ive also tried installing 1.1.4, from here https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads#windows-app-sdk-11 but whenever i try to either uninstall or install a version of the windows app SDK, the process seems to run forever but never finish. For example, this is a screenshot of the install window for windows app sdk 1.1.4, and its just been like this for 2 hours, and never progresses beyond this point 

![image](https://user-images.githubusercontent.com/76792853/185757950-f4be6419-f2a7-4005-9abb-2923c95ed250.png)

same with trying to uninstall an old version, it just gets stuck on "initialized" and never gets any further.
```
>>remove-appxpackage -Package Microsoft.WindowsAppRuntime.1.1_1002.543.1943.0_x64__8wekyb3d8bbwe
Deployment operation progress: Microsoft.WindowsAppRuntime.1… [Initialized                                        ]
```

I'm sure i'm missing something here but its driving me nuts..!

### Steps to reproduce the bug

Create new Blank WinUI3 app in visual studio
Press f5 to run

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by xEsteem** [comment]
I noticed my reference to WindowsAppSDK was outdated, at 1.1.3, so i did update the nuget package reference to 1.1.4, but i get the same thing as mentioned above regarding installing a new version of the runtime. When i try and compile the project i just get
```
Creating a new clean layout...
Copying files: Total 102 mb to layout...
Checking whether required frameworks are installed...
Framework: Microsoft.WindowsAppRuntime.1.1/X64, app package version 1004.584.2120.0 is not currently installed.
Installing missing frameworks...
```
and it just gets stuck on "Installing missing frameworks..." forever

**Comment by DarranRowe** [comment]
The issue here is that if the redistributable fails, it is really no longer a Windows App SDK issue.
But to fully be sure, have you tried installing the .MSIX packages directly? The executable installer is just a wrapper around the Windows package manager API after all.
![2022-08-21](https://user-images.githubusercontent.com/52577874/185791449-2c385284-0b9b-4c80-b3a7-0ba04d44aa39.png)
I also have no issues getting the redistributable installed.

This is related because when the application is packaged, the last phase of the build process is to deploy the package. This installs any packages that it needs.

Do you have any issues installing or updating Windows Store applications or even the Windows Store application itself? The Windows App SDK redistributable uses the same packaging method after all.

**Comment by xEsteem** [comment]
Thanks for the reply.
I dont have any issue with the windows store, or installing applications from it. For example I downloaded the WinUI 3 Gallery app from the windows store without issue. 
Weirdly ive just tried running my app again and now all of a sudden it works... no idea why... but i'll close for now and see if this crops up again
