### ISSUE TITLE
MAUI XAML Hot Reload not working on certain 20h2 Windows Machine

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/WindowsAppSDK#2896]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MAUI-XAML-Hot-Reload-not-working-on-Wind/10116267)._

---
Steps Used to create:
Created a new ".NET MAUI App"
Run using the Windows Machine, 
- Hot Reload not working
- Live Visual Tree states: XAML Hot Reload is either disabled, not supported by the current application or the application execution is paused.

Run using Android Emulator:
- Hot Reload does work
- Live Visual Tree shows UI Info

Just upgraded to VS 2022 Version 17.3.0

---
#### Feedback Bot on 8/10/2022, 10:48 PM: 

(private comment, text removed)
#### Qiana Jiao (CSI Interfusion Inc) [MSFT] on 8/11/2022, 02:47 AM: 

(private comment, text removed)
#### Schultz, Dave on 8/11/2022, 03:37 AM: 

(private comment, text removed)
#### Dwaine Hewitt on 8/11/2022, 11:50 AM: 

(private comment, text removed)
#### Feedback Bot on 8/14/2022, 10:54 PM: 

(private comment, text removed)
#### Schultz, Dave on 8/16/2022, 11:38 AM: 

(private comment, text removed)
#### Dwaine Hewitt on 8/16/2022, 11:49 AM: 

(private comment, text removed)
#### Feedback Bot on 8/16/2022, 05:46 PM: 

(private comment, text removed)
#### Stephan Holzschuh on 8/16/2022, 11:07 PM: 

(private comment, text removed)
#### Don Thompson on 8/17/2022, 05:22 AM: 

(private comment, text removed)
#### Feedback Bot on 8/22/2022, 11:57 AM: 

(private comment, text removed)

---
#### chabiss [MSFT] solved on 8/16/2022, 11:21 AM, 3 votes: 

<p>Can you run this from an elevated command prompt and see if this fix it</p>
<p>takeown /f “C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe” /r /d y<br>
icacls.exe “C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1_1003.565.600.0_x64__8wekyb3d8bbwe” /grant Users:(RD,R,REA,RX) /t</p>

**Comment by evelynwu-msft** [comment]
Internal bug tracking this, along with discussion to date: https://task.ms/dd/1584535

**Comment by chabiss** [comment]
Dump of the get-acl below
\\ddfiles\Team\Public\chabiss\xamlacls.txt

**Comment by jaldinger** [comment]
I seem to be having this same issue, but on Windows 10 21H2, using VS Version 17.5.0 Preview 1.0 as well as 17.4.2.
I tried the **takeown** and **icacls** commands on the C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2_2000.684.1510.0_x64__8wekyb3d8bbwe folder, but it didn't fix it. Are there any other workarounds?

**Comment by DanGrowns** [comment]
> I seem to be having this same issue, but on Windows 10 21H2, using VS Version 17.5.0 Preview 1.0 as well as 17.4.2. I tried the **takeown** and **icacls** commands on the C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2_2000.684.1510.0_x64__8wekyb3d8bbwe folder, but it didn't fix it. Are there any other workarounds?

Same issue for me - unable to run the workaround scripts in my office environment. Rollback is not showing as an option for me on the VS installer either.

Windows 21H1 19043.2251, Visual Studio 17.4.2

**Comment by Whoopalla** [comment]
Same. Windows: 21H2. Visual studio 2022 17.4.3

**Comment by Davidoff81** [comment]
Same issue here. Hot reload worked for a day and then just died. I can't run any workaround scripts with my company laptop. Now I'm forced to continue development on my own PC.

**Comment by jakopo87** [comment]
The workaround worked for me after I executed against all folders matching "\*windowsappruntime\*" in 'C:\Program Files\WindowsApps\'.

From an elevated powershell prompt:

    cd 'C:\Program Files\WindowsApps\'
    ls *windowsappruntime* | % {
        takeown /f "$_" /r /d y
        icacls.exe "$_" /grant ('Users:(RD,R,REA,RX)') /t
    }

Note: if the language of your OS is not english, you have to change the value of `y` accordingly.

**Comment by codendone** [comment]
Looks like the internal bug was resolved as fixed at the end of January 2023. Closing.
