### ISSUE TITLE
Build should issue a warning if targeting < 19H1 and WindowsAppSdkUndockedRegFreeWinRTInitialize not enabled

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/WindowsAppSDK#2905]
### Describe the bug

Repro seen with WinUI test collateral failing on RS5, with the first WinRT runtime class (DispatcherQueue) failing to activate.

Fix is to set WindowsAppSdkUndockedRegFreeWinRTInitialize to true, but that raises two questions:
1. What is the default behavior?  Shouldn't it be enabled?
2. If WindowsAppSdkUndockedRegFreeWinRTInitialize is disabled and the app has a TargetPlatformMinVersion < 10.0.18362.0 (19H1), can the build issue a warning?  Maybe something like:

```
        <Warning Condition="('$(WindowsAppSdkUndockedRegFreeWinRTInitialize)' != 'true') and ('$(TargetPlatformMinVersion)' &lt; '10.0.18632.0'))"
            Text="Unpackaged self-contained apps targeting Windows builds prior to 10.0.18362.0 require Undocked Reg-Free WinRT support. See ...."/>

```

### Steps to reproduce the bug

See description

### Packaging type

Unpackaged

### Windows version

Windows 10 version 1809 (17763, October 2018 Update)

**Comment by DrusTheAxe** [comment]
>1. What is the default behavior? Shouldn't it be enabled?

Only if the project's output is an exe (OutputType=Exe | WinExe). It used to be applied to anything but that causes problem for DLLs (class libraries etc) as they don't own process context (but would change it). 1.2 defaults to only setting default WindowsAppSdkUndockedRegFreeWinRTInitialize=true if you're making an exe.

If you're making a DLL _and you do want the auto-initializer_ you can set the property. We can't unambiguously determine if this appropos for non-EXEs e.g. are you making a class library for use by apps or a test DLL for use by TAEF/MSTest/etc?


>2. can the build issue a warning?

If URFW auto-initializer is disabled != URFW is disabled. Warning spew is helpful or not, depending what you're building. Are people making DLLs overwhelmingly often for one of the scenarios?

I'm leery of spamming developers if URFW auto-init isn't commonly needed/wanted. Is the class library scenario rare? My hunch is no.

**Comment by LegendaryBlair** [comment]
Warning may not be necessary according to the discussion
