### ISSUE TITLE
v1.1.4 breaks CoreWebView Page.fileChooserOpened event Callback

### ISSUE THREAD

**Issue by minesworld** [microsoft/WindowsAppSDK#2921]
### Describe the bug

This code works in WinUI3 desktop apps using AppSDK 1.1.3, in best case under AppSDK 1.1.4 it doesn't work, sometimes throws an Address violation

```
await WebView2.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.enable", "{}");
WebView2.CoreWebView2.GetDevToolsProtocolEventReceiver("Page.fileChooserOpened").DevToolsProtocolEventReceived += OnPageFileChooserOpened;
await WebView2.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.setInterceptFileChooserDialog", "{\"enabled\": true}");
```

### Steps to reproduce the bug

1. install Microsoft Edge Dev 106.0.1356.0 or later
2. download project from https://github.com/minesworld/WindowsAppSDKBugs
3. change path to Edge dev in MainWindow.xaml.cs if needed
4. run (is on AppSDK 1.1.3)
5. put in an URL where a file chooser will be opend for upload
6. click "Go" button
7. on the website click an element to upload a file
8. the debug output should show OnPageFileChooserOpened
9. end run
10. change to AppSDK 1.1.4 and run again

### Expected behavior

AppSDK 1.1.4 should not break existing functionality

### NuGet package version

1.1.4

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by minesworld** [comment]
Doesn't seem to be realated to AppSDK 1.1.4 but the WebView2 - it crashes in AppSDK 1.1.3 too if many Objects are created and thus the GC fiddles them around... Gives either Access violations on write or read. Great waste of time. Will file a Bug in WebView2

**Comment by gabbybilka** [comment]
Tracking in WebView2Feedback, thanks for submitting. [#2733](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2733)
