### ISSUE TITLE
[Unpackaged Apps] Localization - ResourceLoader.GetForViewIndependentUse does not work in Windows10 machines 

### ISSUE THREAD

**Issue by JRallee** [microsoft/WindowsAppSDK#2928]
**Describe the bug**
[Unpackaged Apps] Localization - ResourceLoader.GetForViewIndependentUse does not work in Windows10 machines 
it throws "Unsupported MRT Profile Type" exception.

**Steps to reproduce the bug**
New WinUI unpackaged app using net6+

Added Resources.resw files for localization

Initialized ResourceLoader using, _resourceLoader.GetForViewIndependentUse("")

**Expected behavior**
App launches and localized strings are visible

**Actual Behavior**
App crashes with "Unsupported MRT Profile Type"

**Packaging type**
Unpackaged (also SelfContained = True)

**Important Note**
Please test this in standalone non dev boxes (No visual studio, no WinUi3 gallery app etc.)
All required prerequisites like .NET6, WindowsAppSDK etc. were installed and up-to date.

**Windows version**
Win10 & WIn11

**WindowsAppSDK Version**
1.1.4 (**Latest package**)
![image](https://user-images.githubusercontent.com/16042739/187923869-65930615-a776-4b94-a2b1-d111bfc51d04.png)

**Comment by axelandrejs** [comment]
You're using the in-box version of these APIs (you can tell by the fact that they are in the Windows namespace). Those have limited support for unpackaged apps, and no support on older OSes.

The WinAppSdk version of these APIs doesn't have the GetForViewIndependentUser function. You just use the constructor to create a new instance, it does the effectively same thing.

**Comment by JRallee** [comment]
Hi @axelandrejs ,

Thanks for your quick response, but I did not completely understand the issue as yet.
Is it because of the SelfContained attribute?
Or is it a given fact the ResourceLoader.GetForViewIndependentUse does not work with WinUI3 on Windows 10?

Also, is there a workaround to fix this.
Windows 10 support is kind of critical for our application.

**Comment by axelandrejs** [comment]
Hey!

You're calling the wrong API family. The resource loader comes in two flavors.

1. MRT, which comes with the OS and is targeted at UWP. 
2. MRT core, which ships as part of the WinAppSdk, and supports the entire WinAppSdk scenario matrix.

You're calling the former. You need to switch to the latter to make this work. The API looks very similar to the old one, but you can tell by the namespace (Microsoft.* versus Windows.*) You can find the docs here: https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourceloader?view=windows-app-sdk-1.1
