### ISSUE TITLE
Unable to build Windows App SDK self contained applications if the users folder contains a space

### ISSUE THREAD

**Issue by NicholasChrzan** [microsoft/WindowsAppSDK#2929]
### Describe the bug

When trying to build a self contained unpackaged app the build fails with the following error when the user folder contains a space:

general error c1010070: Failed to load and parse the manifest. Windows was unable to parse the requested XML data.

If you modify your user folder to not include spaces or build with a user folder that doesn't have spaces it will build correctly.

### Steps to reproduce the bug

Have a Windows App SDK app configured as unpackaged and self contained via the following project attributes

<WindowsPackageType>None</WindowsPackageType>
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

 and a user folder with a space in the name (i.e. "C:\users\John Doe\")

the build will fail being unable to find the manifest files for the App SDK. 

From the mt command line reported it looks like it's missing double qoutes for the path to the Microsoft.InteractiveExperiences.manifest and Microsoft.WindowsAppSdk.Foundation.manifest files

### Expected behavior

It should build regardless of whether the user name has a space or not.

### NuGet package version

1.1.4

### Packaging type

Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by Scottj1s** [comment]
Fixed in Windows App SDK 1.3.  See also https://github.com/microsoft/WindowsAppSDK/issues/1826
