### ISSUE TITLE
1.2 Preview 1, wrong behavior of windows after entering fullscreen

### ISSUE THREAD

**Issue by sudongg** [microsoft/WindowsAppSDK#2945]
### Describe the bug

This problem only appears in 1.2 Preview 1,
The window is in normal state => maximized => full screen => exit full screen => after dragging the title bar, the window size should be restored to the normal state under normal circumstances,
But the size didn't change in 1.2 Preview 1.
And the window animation is very strange during maximize => full screen.
If the official release doesn't fix this, I won't be able to upgrade to 1.2.

### Steps to reproduce the bug

. MainWindow.xaml add
```
    <Grid Background="Transparent" DoubleTapped="Grid_DoubleTapped">
    </Grid>
```
MainWindow.xaml.cs add

 ```
       public MainWindow()
        {
            this.InitializeComponent();
            AppWindow = AppWindowExtensions.GetAppWindow(this);
        }

        bool isFullScreen = false;

        private void Grid_DoubleTapped(object sender, Microsoft.UI.Xaml.Input.DoubleTappedRoutedEventArgs e)
        {
            isFullScreen = !isFullScreen;

            if (isFullScreen)
            AppWindow.SetPresenter(AppWindowPresenterKind.FullScreen);
            else AppWindow.SetPresenter(AppWindowPresenterKind.Default);
        }
```
. Run
. Maximize the window, double-click the window to enter full screen, double-click again to exit .
. Drag the title bar
. No change in window size

### Expected behavior

The window should revert to its normal state

### NuGet package version

1.2.220727.1-experimental1

### Packaging type

Unpackaged

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2022

**Comment by rkarman** [comment]
Routing to @ryandemopoulos and @ionvasilian to make sure this gets triaged correctly as I'm no longer PM:ing this feature area.
