### ISSUE TITLE
Path to `mspdbcmf.exe` could not be found

### ISSUE THREAD

**Issue by Tardigrade42** [microsoft/WindowsAppSDK#2963]
### Describe the bug

When I run `dotnet publish` to build a Maui-Application, I get the following warning:
```
C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\Microsoft.Build.Msix.Packaging.targets(341,5): warning : Path to `mspdbcmf.exe` could not be found. A symbols package will not be generated. Review https://aka.ms/windowsappsdkdocs and ensure that all prerequisites for Windows App SDK development have been installed. [D:\a\Maui-Issue-9879\Maui-Issue-9879\TestIssue9879\MauiApplication\MauiApplication.csproj]
```

This happens locally in my PowerShell and on GitHub Actions. The second option can be seen here:
[x86 run](https://github.com/mattleibow/Maui-Issue-9879/runs/8215556992?check_suite_focus=true)
[x64 run](https://github.com/mattleibow/Maui-Issue-9879/runs/8215556976?check_suite_focus=true)

### Steps to reproduce the bug

1. Create a Maui Application from the template
2. Run `dotnet publish` in your shell (happens with any Windows-RID-Options)
3. You shall see the warning

### Expected behavior

No warning. I don't know if the `mspdbcmf.exe` is important or not here.

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022-preview

**Comment by drewrodrigues** [comment]
I'm having this issue as well. Will update if I figure it out

**Comment by jtheisen** [comment]
It also happens on Azure DevOps Pipelines.

Where is this exe? How do I get it?

**Comment by jtheisen** [comment]
This issue means that MAUI apps can't publish debug symbols in their package, even those the publish UI suggests so.

**Comment by jamers99** [comment]
Not sure how, but this is working locally, but the same thing doesn't work on our build agents. ;(

**Comment by bogdan-patraucean** [comment]
same issue for WinUI 3

**Comment by MichalMucek** [comment]
It started to occur for me when I changed NuGet packages destination (by overwriting NUGET_PACKAGES environment variable) to another partition (C:\Users\user\.nuget\packages to B:\NuGet\packages). I needed to roll back to the user folder (default) in order to have the packages building working. I haven't checked if it would work on the same partition in another folder.

**Comment by joshua-lemli** [comment]
I have simple MAUI Blazor project and publishing with CLI per the instructions below causes this issue with `-c Debug`.
https://learn.microsoft.com/en-us/dotnet/maui/windows/deployment/publish-cli

**Comment by tipa** [comment]
> I think a workaround is to install the C++ workload in VS. I think it was the C++ workload, but may have been another.

Can confirm that this made the warning disappear

**Comment by MichalMucek** [comment]
@mattleibow @tipa Could you tell me what exact individual components you have selected? I have the below ones and the warning keeps appearing:
-  C++ core desktop features
- MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)
- C++ CMake tools for Windows
- Windows 11 SDK (10.0.22621.0)
- Windows 10 SDK (10.0.19041.0)

**Comment by Scottj1s** [comment]
Closing, as problem appears to have been a missing workload (not a WinAppSDK issue)

**Comment by tipa** [comment]
@MichalMucek  I think you need `MSVC v143 - VS 2022 C++ x64/x86 build tools (Latest)` & also  `MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (Latest)` - at least that's what's fixed it when I just had this issue reappear when setting up a new dev environment

**Comment by mattleibow** [comment]
@Scottj1s is there any hope/plans for a world in which the CLI is used with say VSCode and no full VS? VS is great and all, but if we are doing dotnet dev, we should not _need_ vs installed.

Is there maybe some standalone tool to install? Would it be possible for the required parts to be in a nuget like the BuildTools one? It does not have to be in that one, but maybe there can be a "C++ build tools" nuget that we could optionally install?

**Comment by alexlogvin** [comment]
This issue still happens for me.
With .NET 8/9 (8.0.400, 9.0.100), creating new MAUI app and then publishing with `dotnet publish`.
```
C:\Users\<user>\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\buildTransitive\Microsoft.Build.Msix.Packaging.targets(354,5): warning : Path to `mspdbcmf.exe` could not be found. A symbols package will not be generated. Review https://aka.ms/windowsappsdkdocs and ensure that all prerequisites for Windows App SDK development have been installed. [pathToProject.csproj::TargetFramework=net8.0-windows10.0.22621.0]
```

**Comment by RDMacLachlan** [comment]
@alexlogvin please create a new issue, and confirm whether you have workloads installed.

**Comment by PaulStSmith** [comment]
> Hi, i had the same problem and managed to fix it by manually supplying the path to the `mspdbcmf.exe` in the `dotnet msbuild` command. I made a small PowerShell function that will correctly retrieve the path as well.
> 
> Here is an example of how i use it
> 
> Function Find-mspdbcmf {
>     [string]$VisualStudioPath = . 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -prerelease -property resolvedInstallationPath

Thanks.
The script worked like a charm.

**Comment by HotCakeX** [comment]
@PaulStSmith glad to know that, you're welcome ^^
