### ISSUE TITLE
It is slow to display context menu when store app trail version expire

### ISSUE THREAD

**Issue by jerrylihz** [microsoft/WindowsAppSDK#2966]
### Describe the bug

Based on reply of the QA link here https://docs.microsoft.com/en-us/answers/questions/1005061/it-is-slow-to-display-context-menu-when-store-app.html, report a bug

We follow this link to create the context menu for supported files,
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extensions#context-menu

This is defination in Package.appxmanifest
</uap3:Extension>
<com:Extension Category="windows.comServer">
<com:ComServer>
<com:SurrogateServer DisplayName="Context menu verb handler">
<com:Class Id="1476525B-BBC2-4D04-B175-7E7D72F3DFF8" Path="QuickContextMenu.dll" ThreadingModel="STA"/>
</com:SurrogateServer>
</com:ComServer>
</com:Extension>
<desktop4:Extension Category="windows.fileExplorerContextMenus">
<desktop4:FileExplorerContextMenus>
<desktop5:ItemType Type=".mp3">
<desktop5:Verb Id="Command" Clsid="1476525B-BBC2-4D04-B175-7E7D72F3DFF8" />
</desktop5:ItemType>
<desktop5:ItemType Type=".wma">
<desktop5:Verb Id="Command" Clsid="1476525B-BBC2-4D04-B175-7E7D72F3DFF8" />
</desktop5:ItemType>

We upload the app to Microsoft store and set 7 days trail. There is no problem if in trial period.
But when trial expire and we right click the supported file, for example it is slow to display context menu when i select mp3 file, and will slow again when i select mp3 file twice, even we restart the computer. It is slow every time when we right click the file. Please see attached video.

We can accept not display the context menu when expire, but can’t accept if it is slow.

We can see the event log in system. Unable to start because the expire, but need much time.

Unable to start a DCOM Server: {1476525B-BBC2-4D04-B175-7E7D72F3DFF8} as Unavailable/Unavailable. The error:
"2151645194"
Happened while starting this command:
"C:\WINDOWS\system32\DllHost.exe" /Processid:{1476525B-BBC2-4D04-B175-7E7D72F3DFF8}

### Steps to reproduce the bug

1. install the app from the microsoft sotre
2. trial version expire
3. right click the context-mebu of windows explorer
4. Slow to display the context-mebu

### Expected behavior

So we want to know how to improve? I think below solution is acceptable

remove the context menu when expire

quick to return if unable to start DCOM server

not add context menu in trial verion and add context menu after user purchase the product. (Include configure in Store or create two installer)

### NuGet package version

1.0.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2019

### Additional context

And this is project target

> `<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Edit</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <StartupObject>Edit.Program</StartupObject>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ApplicationIcon>Icon\Audio_ico.ico</ApplicationIcon>
  </PropertyGroup>`

**Comment by gabbybilka** [comment]
@jerrylihz Needs more info, we do not see the video to help us understand your issue.

**Comment by haonanttt** [comment]
Author no reply for more than 2 years
