### ISSUE TITLE
Publish produces `resources.pri` file in addition to the exe for unpackaged app.

### ISSUE THREAD

**Issue by IvanDmitriev1** [microsoft/WindowsAppSDK#2978]
### Describe the bug

Publish produces `resources.pri` file in addition to the exe for unpackaged app.

### Steps to reproduce the bug

1. Add to .csproj
```
<WindowsPackageType>None</WindowsPackageType>
<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
```
2. Add to .manifest
 ```
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
	  <application>
		  <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
	  </application>
  </compatibility>
```
3. Publish settings

![Screenshot_9](https://user-images.githubusercontent.com/42055372/190968468-f6674247-fbb3-4064-a200-7961e150f754.png)

### Expected behavior

After publish should be produced one single exe file.

### Screenshots

![Screenshot_10](https://user-images.githubusercontent.com/42055372/190969475-b364929a-2fd4-40dc-af6d-9bcf41aab14c.png)

### NuGet package version

1.1.4

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

**Comment by Balkoth** [comment]
This was already reported in #1803
