### ISSUE TITLE
DEP0800 error when attempting to deploy clean MAUI project

### ISSUE THREAD

**Issue by danielmaharry-okta** [microsoft/WindowsAppSDK#2988]
### Describe the bug

The following exception occurs when I attempt to debug any MAUI app in a clean install of Visual Studio 17.3.4

DEP0800: The required framework "C:\Users\<username>\.nuget\packages\microsoft.windowsappsdk\1.1.3\buildTransitive\..\tools\MSIX\win10-x64\Microsoft.WindowsAppRuntime.1.1.msix" failed to install. [0x80070005]	MauiApp1			

### Steps to reproduce the bug

1. Install Visual Studio Community
2. Created a new MAUI Project
3. Hit F5
4. Exception occurs after build during deployment

### Expected behavior

I would expect the app to build, deploy and me be able to run and debug it.

### Screenshots

![image](https://user-images.githubusercontent.com/97525701/191734933-9c1b97a5-241b-4fbd-ae13-a6ce26a26671.png)

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

As this seems closely related to #2741 I should also say that I am running Windows 10 and Powertoys for Win10. 
Developer mode is switched on. 
Nuget package version seems to be 1.1.3 but there isn't an option for that in the bug reporter dropdown

**Comment by gabbybilka** [comment]
Known issue for new projects - try restarting Visual Studio and rebuilding.

**Comment by danielmaharry-okta** [comment]
Did so several times - produced same DEP0800 error each time.

**Comment by LegendaryBlair** [comment]
Cannot repro in VS MAUI project for VS 17.11.5, hence closing the issue
