### ISSUE TITLE
ArgumentException with StorageApplicationPermissions in Unpackaged Apps

### ISSUE THREAD

**Issue by mattleibow** [microsoft/WindowsAppSDK#2995]
### Describe the bug

When trying to add a picked file (from the file picker) to the `StorageApplicationPermissions.FutureAccessList`, the app will throw:

```
Exception thrown: 'System.ArgumentException' in WinRT.Runtime.dll
An exception of type 'System.ArgumentException' occurred in WinRT.Runtime.dll but was not handled in user code
Value does not fall within the expected range.
```

### Steps to reproduce the bug

1. File | New | WASDK App
2. Add the snippet below to the button click event.
3. Run the app and observe no crash
4. Switch to unpackaged
5. Run the app and observe a crash

Snippet:

```cs
var picker = new FileOpenPicker
{
    ViewMode = PickerViewMode.List,
    SuggestedStartLocation = PickerLocationId.DocumentsLibrary,
    FileTypeFilter = { "*" }
};

// required to init the picker?
var hwnd = WindowStateManager.Default.GetActiveWindow().GetWindowHandle();
WinRT.Interop.InitializeWithWindow.Initialize(picker, hwnd);

var picked = await picker.PickSingleFileAsync();
if (picked != null)
    StorageApplicationPermissions.FutureAccessList.Add(picked);
```

Th exception happens in this line: 

```cs
StorageApplicationPermissions.FutureAccessList.Add(picked);
```

Is this required still? Maybe not for unpackaged? Should it throw?

### Expected behavior

No crash

### NuGet package version

1.1.4

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by evelynwu-msft** [comment]
@MikeHillberg @gabbybilka Should we add `Windows.Storage.AccessCache.StorageApplicationPermissions` to the [list of WinRT APIs not supported in desktop apps](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)? I took a quick look under the debugger and it appears that the API needs a package identity in order to work.

**Comment by gabbybilka** [comment]
@evelynwu-msft Documenting sounds good to me, I'll follow up.

**Comment by gabbybilka** [comment]
Added to docs via https://github.com/MicrosoftDocs/windows-dev-docs/pull/4181
