### ISSUE TITLE
Make virtual webcams and microphones accessible to UWP apps

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/WindowsAppSDK#302]
# Proposal: Make virtual webcams and microphones accessible to UWP apps
I develop an instant messaging app that, among other features, it offers voice messages and voice/video calls.
One of the main complains from users is that they can't find their input devices in the app settings, and this is because they're using some virtual webcam/microphone software. This seems to be pretty confusing for them, and they obviously point this as a bug in my application. Especially, It isn't always easy to explain them that it's not a bug or a missing feature, when any other competitor software can properly list and use their devices.

**Comment by stevewri** [comment]
Looking for the right area owner.

**Comment by btueffers** [comment]
Hi @FrayxRulez! As [announced](https://github.com/microsoft/WindowsAppSDK/discussions/1615), the Windows App SDK is focusing on desktop-based project types and we're working on making it easy to [migrate](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/overall-migration-strategy) from UWP to desktop, which will provide you the ability to access virtual webcams and microphones just like other desktop apps do today!
