### ISSUE TITLE
Windows Widgets sample doesn't work

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#3023]
### Describe the bug

After creating and deploying the Windows Widgets project per docs, adding the example widgets causes the C++ runtime to abort. Widgets do not appear correctly, and general stability of the widget board is degraded.

![image](https://user-images.githubusercontent.com/475132/194222708-f4182870-12d0-4fc7-865a-a74ff23c7341.png)
![image](https://user-images.githubusercontent.com/475132/194222915-61ac2b14-cd5f-4972-b87a-cd86131c715c.png)

### Steps to reproduce the bug

1. Follow documentation to create sample project https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-win32
2. Observe failure

Sample completed project:
[WidgetDocsRepro.zip](https://github.com/microsoft/WindowsAppSDK/files/9721528/WidgetDocsRepro.zip)

### Expected behavior

Widget to appear. Valid docs/sample.

### NuGet package version

1.2.220930.4-preview2

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

### Additional context

Windows Dev 25211.1001.amd64fre.rs_prerelease.220923-1354
Widgets board 521.20060.1205.0

**Comment by asklar** [comment]
fyi @beervoley @paulcam206 @kesemz

**Comment by beervoley** [comment]
@rverar you'd need to add reference to winappsdk package in `.wapproj` so the running app can properly locate and load all the required binaries:
```
 <ItemGroup>
	  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.220930.4-preview2">
		  <IncludeAssets>build</IncludeAssets>
	  </PackageReference>  
  </ItemGroup>
```

**Comment by riverar** [comment]
Can confirm that fixes the issue.

**Comment by beervoley** [comment]
thanks :) closing the issue

**Comment by riverar** [comment]
Well we should leave this open until the corrected docs are published, right?

**Comment by beervoley** [comment]
> @beervoley Well we should leave this open until the corrected docs are published, right?

good point, I'll keep it open until docs are up :)

**Comment by beervoley** [comment]
@riverar docs are up: https://learn.microsoft.com/en-us/windows/apps/develop/widgets/implement-widget-provider-win32#add-a-reference-to-the-windows-app-sdk
