### ISSUE TITLE
VSIX Installer installation failed for install reunion

### ISSUE THREAD

**Issue by omides248** [microsoft/WindowsAppSDK#3025]
### Describe the bug

[dd_VSIXInstaller_20221006204656_0200.log](https://github.com/microsoft/WindowsAppSDK/files/9727440/dd_VSIXInstaller_20221006204656_0200.log)

### Steps to reproduce the bug

1. Open Visual Studio
2. Go to Extensions
3. Go Manage Extensions
4. Download and install Project Reunion version 0.8.12.814726693
5. Close visual studio
6. Click Yes for vsix install

### Screenshots

![image](https://user-images.githubusercontent.com/37228870/194386027-c57513da-780d-40a3-a5e5-288df2214780.png)

**Comment by gabbybilka** [comment]
Project Reunion 0.8 is currently in 'Maintenance' mode as per [release lifecycle docs](https://learn.microsoft.com/windows/apps/windows-app-sdk/release-channels#release-lifecycle). You can install the latest WinAppSDK 1.1 VSIX [here](https://learn.microsoft.com/windows/apps/windows-app-sdk/downloads#windows-app-sdk-11) or as part of the default WinAppSDK workload in Visual Studio 2022.
