### ISSUE TITLE
Error APPX1101: Payload contains two or more files with the same destination path 'WinUI3Test.pdb' when PublishTrimmed is true

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/WindowsAppSDK#3030]
### Describe the bug

Setting "PublishTrimmed" to true in the project's file gives me this error when trying to build the app.

![2](https://user-images.githubusercontent.com/50815710/194670588-bad42ef8-bad4-48c6-b4c6-f4933417d36a.png)

If I set the property to false it works normally and it builds without problems.

### Steps to reproduce the bug

1. Create a packaged WinUI 3 app.
2. Target .NET 7.
3. Set OS version and supported OS version to 22621.
4. Add the following properties to the project file and set them to true: WindowsAppSDKSelfContained and PublishTrimmed.
5. Build it.

### Screenshots

Visual aid for PropertyGroup:

![1](https://user-images.githubusercontent.com/50815710/194671568-28103339-e5bc-4815-8eeb-fa1b8227d91a.png)

### NuGet package version

1.2.220930.4-preview2

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022-preview

### Additional context

Windows 11 22H2

Like in [this](https://github.com/microsoft/WindowsAppSDK/issues/2524) issue this error seems to occur in Microsoft.Build.Msix.Packaging.targets.

**Comment by DarranRowe** [comment]
The project system can be sloppy updating files. Do you get this problem if you clean the project before you build?

**Comment by eduardobragaxz** [comment]
What does clean the project mean exactly? I deleted the bin and obj folders, and uninstalled the app before trying just now, and it doesn't work. BUT good news I think, I'm pretty sure I found the culprit: .NET 7. If I target .NET 6, it works. It builds. I didn't remember this until now, but I've had this happen before, but at the time deleting those folders fixed it. It doesn't now. I change to .NET 7 and the payload error shows up.

**Comment by lucasmenchon** [comment]
i have the same problem, when i create an app app Maui Blazor and i put microsoft.design and microsoft.tools it says i have two "duplicate deps.json"

**Comment by Scottj1s** [comment]
@eduardobragaxz Thanks for reporting this issue.  We'll have a fix in the next release.  In the meantime, here's a workaround you can include in your project/directory.build.targets:

```
    <Target Name="__BackCalculateOptimizationInputAssemblies"
            DependsOnTargets="__SnapshotResolvedFileToPublishBeforeOptimization;__SnapshotResolvedFileToPublishAfterOptimization"
            Returns="@(_OptimizationInputAssemblies)">
        <PropertyGroup>
            <IncludeDebugSymbolsProjectOutputGroup Condition="'$(IncludeDebugSymbolsProjectOutputGroup)' == ''">true</IncludeDebugSymbolsProjectOutputGroup>
        </PropertyGroup>
        <CallTarget Targets="DebugSymbolsProjectOutputGroup" Condition="'$(IncludeDebugSymbolsProjectOutputGroup)' == 'true'">
            <Output TaskParameter="TargetOutputs" ItemName="_DebugSymbolsProjectOutputGroupOutput"/>
        </CallTarget>
        <ItemGroup>
            <_OptimizationInputAssemblies Include="@(_BeforeOptimizationImagesSnapshot)" />
            <_OptimizationInputAssemblies Remove="@(_AfterOptimizationImagesSnapshot)" />
            <_OutputGroupOutputs Include="@(_DebugSymbolsProjectOutputGroupOutput)" />
            <_OutputGroupOutputsNotOptimized Include="@(_OutputGroupOutputs)" Exclude="@(_OptimizationInputAssemblies)" />
            <_OutputGroupOutputsOptimized Include="@(_OutputGroupOutputs)" Exclude="@(_OutputGroupOutputsNotOptimized)" />
            <_OptimizationInputAssemblies Include="@(_OutputGroupOutputsOptimized->'%(FinalOutputPath)')" />
        </ItemGroup>
    </Target>
```

**Comment by eduardobragaxz** [comment]
Thanks Scott. Where exactly do I put this in? Not in the file where the error comes from, is it?

**Comment by Scottj1s** [comment]
You can paste it at the bottom of your WinUI3Test.csproj, just inside the `</Project>` element.  You can also isolate it for easier removal later, by pasting it inside a standalone file named **directory.build.targets**, alongside WinUI3Test.csproj:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="__BackCalculateOptimizationInputAssemblies"
            DependsOnTargets="__SnapshotResolvedFileToPublishBeforeOptimization;__SnapshotResolvedFileToPublishAfterOptimization"
            Returns="@(_OptimizationInputAssemblies)">
        <PropertyGroup>
            <IncludeDebugSymbolsProjectOutputGroup Condition="'$(IncludeDebugSymbolsProjectOutputGroup)' == ''">true</IncludeDebugSymbolsProjectOutputGroup>
        </PropertyGroup>
        <CallTarget Targets="DebugSymbolsProjectOutputGroup" Condition="'$(IncludeDebugSymbolsProjectOutputGroup)' == 'true'">
            <Output TaskParameter="TargetOutputs" ItemName="_DebugSymbolsProjectOutputGroupOutput"/>
        </CallTarget>
        <ItemGroup>
            <_OptimizationInputAssemblies Include="@(_BeforeOptimizationImagesSnapshot)" />
            <_OptimizationInputAssemblies Remove="@(_AfterOptimizationImagesSnapshot)" />
            <_OutputGroupOutputs Include="@(_DebugSymbolsProjectOutputGroupOutput)" />
            <_OutputGroupOutputsNotOptimized Include="@(_OutputGroupOutputs)" Exclude="@(_OptimizationInputAssemblies)" />
            <_OutputGroupOutputsOptimized Include="@(_OutputGroupOutputs)" Exclude="@(_OutputGroupOutputsNotOptimized)" />
            <_OptimizationInputAssemblies Include="@(_OutputGroupOutputsOptimized->'%(FinalOutputPath)')" />
        </ItemGroup>
    </Target>
</Project>
```

**Comment by eduardobragaxz** [comment]
Alright. I added to the project file, but now it's throwing the unhandled exception.

**Comment by lhak** [comment]
The workaround seems to work for me for a quite simple application. However, I also had to add 
```<TrimMode>partial</TrimMode>``` to the project file.

**Comment by Scottj1s** [comment]
@eduardobragaxz I think you're seeing an issue with trimming.  @manodasanW and I will work on troubleshooting that.

@lhak thanks for the tip.

**Comment by JanRajnoha** [comment]
Any info on this bug?

**Comment by lucasmenchon** [comment]
do not install ef core
