### ISSUE TITLE
NETSDK1047 error using msbuild for WAP apps with project dependencies

### ISSUE THREAD

**Issue by tylersouthard** [microsoft/WindowsAppSDK#3034]
### Describe the bug

Attempting to build a (stock/template) WinUI 3 test app that depends on a .NET Standard 2.0 library via msbuild results in a NETSDK1047 error.

The build commands used are below. I kept some of the parameters (such as /p:VisualStudioVersion and /m) because these are ultimately what are used for our ADO pipeline via the VSBuild task.
1) Restore: `msbuild <path\to\TestApp>\TestApp.sln /nologo /nr:false /t:restore /m `
2) Build: `msbuild <path\to\TestApp>\TestApp.sln /nologo /nr:false /t:TestAppPackage /p:AppxPackageSigningEnabled=false /p:AppxBundlePlatforms="x86|x64" /p:AppxBundle=Always /p:PackageCertificateThumbprint="" /p:configuration="Release" /p:VisualStudioVersion="17.0" /m`

A minimal repro is attached.
[TestApp.zip](https://github.com/microsoft/WindowsAppSDK/files/9745462/TestApp.zip)

The error text is:
```
"C:\dev\TestApp\TestApp.sln" (TestAppPackage target) (1) ->
"C:\dev\TestApp\TestApp\TestApp (Package)\TestAppPackage.wapproj" (default target) (2) -> "C:\dev\TestApp\TestApp\TestApp\TestApp.csproj" (_GenerateAdditionalFrameworkSDKReference;_GetRecursiveResolvedSDKReferences;DesktopBridgeFrameworkSDKRegistrationOutputGroup target) (3:8) -> "C:\dev\TestApp\TestLibrary\TestLibrary.csproj" (_GenerateAdditionalFrameworkSDKReference;_GetRecursiveResolvedSDKReferences;DesktopBridgeFrameworkSDKRegistrationOutputGroup target) (4:10) -> (ResolvePackageAssets target) -> C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file 'C:\dev\TestApp\TestLibrary\obj\project.assets.json' doesn't have a target for 'netstandard2.0/win10-x64'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. You may also need to include 'win10-x64' in your project's RuntimeIdentifiers. [C:\dev\TestApp\TestLibrary\TestLibrary.csproj]


"C:\dev\TestApp\TestApp.sln" (TestAppPackage target) (1) ->
"C:\dev\TestApp\TestApp\TestApp (Package)\TestAppPackage.wapproj" (default target) (2) ->
"C:\dev\TestApp\TestApp.sln" (Build target) (1:3) ->
"C:\dev\TestApp\TestApp\TestApp (Package)\TestAppPackage.wapproj" (default target) (2:2) ->
"C:\dev\TestApp\TestApp\TestApp\TestApp.csproj" (_GenerateAdditionalFrameworkSDKReference;_GetRecursiveResolvedSDKReferences;DesktopBridgeFrameworkSDKRegistrationOutputGroup target) (3:17) ->
"C:\dev\TestApp\TestLibrary\TestLibrary.csproj" (_GenerateAdditionalFrameworkSDKReference;_GetRecursiveResolvedSDKReferences;DesktopBridgeFrameworkSDKRegistrationOutputGroup target) (4:28) -> C:\Program Files\dotnet\sdk\6.0.401\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1047: Assets file 'C:\dev\TestApp\TestLibrary\obj\project.assets.json' doesn't have a target for 'netstandard2.0/win10-x86'. Ensure that restore has run and that you have included 'netstandard2.0' in the TargetFrameworks for your project. You may also need to include 'win10-x86' in your project's RuntimeIdentifiers. [C:\dev\TestApp\TestLibrary\TestLibrary.csproj]
```

### Steps to reproduce the bug

1. Create a new "Blank App, Packaged with Windows Application Packaging Project (WinUI 3 in Desktop)" app (target 10.0.19041.0 and 10.0.17763.0 as the min).
2. Rename the TestApp (Package) project to TestAppPackage for ease of command line invocation
3. Remove arm64 as a platform, for simplicity
4. Run restore command (listed in description) (all commands are executed via Developer Command Prompt for VS 2022)
5. Run build command (listed in description)
6. Observe that build completes successfully, producing an (unsigned) msixbundle, as expected
7. Add a new .NET Standard 2.0 library project to the solution and reference it from the app
8. Clean the solution, removing all obj/bin folders, makeappx artifacts, etc
9. Run restore command (listed in description)
10. Run build command (listed in description)
11. Observe the error

### Expected behavior

The project builds successfully, without errors, like it did before adding the .NET Standard 2.0 library as a reference.

### Screenshots

![ss](https://user-images.githubusercontent.com/28648423/194856476-2ce29092-50c5-41ad-bcf9-282fabdfb60e.png)

### NuGet package version

Using VS 17.3.4, this causes Microsoft.WindowsAppSDK 1.1.3 to be used.

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

Looked at the following issues, but none of the resolutions resolved the issue.

- https://github.com/dotnet/sdk/issues/1321
- https://learn.microsoft.com/en-us/answers/questions/888006/how-to-build-a-wapproj-bundle-using-msbuild-comman.html
- https://stackoverflow.com/questions/49392196/assets-file-obj-project-assets-json-doesnt-have-a-target-vs2017
- https://github.com/microsoft/github-actions-for-desktop-apps/issues/28

**Comment by Scottj1s** [comment]
@tylersouthard Thanks for the excellent repro steps.  Per the error message, I was able to resolve the issue by adding this to TestLibrary.csproj:
    <RuntimeIdentifiers>win10-x86;win10-x64</RuntimeIdentifiers>

**Comment by Scottj1s** [comment]
@tylersouthard I'm glad you found a workaround.  I assume you no longer have a need to produce an msixbundle, having moved to Single-Project?  That's [still not supported](https://github.com/microsoft/WindowsAppSDK/issues/1808).  When that support is finally enabled, I would still expect the same change is necessary - to add RuntimeIdentifiers to TestLibrary.csproj.  The RuntimeIdentifiers-based multi-targeted build will still cause individual RuntimeIdentifier property assignments to flow from TestApp.csproj to TestLibrary.csproj, which will trip the error in the ResolvePackageAssets task.  You're not seeing that now, because the multi-targeted build machinery is not kicking in (I believe). 

Problem can occur in multiple ways, such as when the project does not contain an explicit Platform or PlatformTarget.  The convention for .NET Core projects is to now use RuntimeIdentifier(s) with a shared msil (AnyCPU) app assembly.  However, WinAppSDK only supports .NET SelfContained apps, which require RuntimeIdentifier and an arch-specific AppHost.  So WinAppSDK must simply prohibit creation of ProcessorArchitecture 'neutral' packages with an app host exe.

**Comment by tylersouthard** [comment]
@Scottj1s I see. Thanks for the info.

We are producing an msixbundle, but not via msbuild - we're building x64 and arm64 separately and then invoking makeappx to bundle them together. It's good to know to expect this issue if we react to #1808 by going back to building/bundling via our msbuild command.

Am I understanding correctly that it is known/expected that anyone making a cross-platform WinUI 3/Xamarin.iOS app depending on .NET Standard 2.0 libraries would need to add win10-x64 RIDs to every (cross-platform) .NET Standard 2.0 library? I haven't checked, but I would wonder if that would cause issues when building the Xamarin.iOS app?

**Comment by Scottj1s** [comment]
Yes, that's my understanding - that the RIDs are 'viral', propagating from the app (which must contain them as a requirement for SelfContained deployment, which is the only model Windows App SDK currently supports) to referenced library projects.  I'd be concerned about your Xamarin.iOS build as well.  Maybe a superset of RuntimeIdentifiers would work?  Or even placing Conditions on disjoint RuntimeIdentifiers elements.
