### ISSUE TITLE
Cannot change the precompiled header file

### ISSUE THREAD

**Issue by Woopsalla** [microsoft/WindowsAppSDK#3036]
### Describe the bug

When changing the precompiled header file the following files are still generated with the wrong entry `#include "pch.h"`:
XamlLibMetadataProvider.g.cpp
XamlTypeInfo.Impl.g.cpp

### Steps to reproduce the bug

1. Create a new C++ project with template Blank App, Packaged (WinUI 3 in Desktop).
2. Open project properties -> Configuration Properties -> C/C++ -> Precompiled Headers -> Change the "Precompiled Header File" (e.g. to global.h)
3. Build.
4. Check the generated files.

### Expected behavior

All generated entries "#include pch.h" will be replaced by entries with the new precompiled header file (e.g. #include "global.h").

### NuGet package version

1.2.220930.4-preview2

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022, Visual Studio 2019

### Additional context

The problem also occurs in old Windows App SDK versions, like 1.0.0 and 1.1.3

**Comment by Scottj1s** [comment]
Windows App SDK 1.3 will include support for a customized (or no) precompiled header
