### ISSUE TITLE
MicaController responds incorrectly to IsInputActive and Theme changes

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/WindowsAppSDK#3043]
### Describe the bug

If both `SystemBackdropConfiguration.IsInputActive` and `SystemBackdropConfiguration.Theme` gets changed after `MicaController` construction, `MicaController` will use the colors from the previous theme.

For example, if `IsInputActive` and `Theme` are `true` and `Dark` initially, setting `IsInputActive` to `false` and `Theme` to `Light` would cause a dark background to show up, instead of a light background as expected.

### Steps to reproduce the bug

Change the `IsInputActive` and `Theme` properties of the `SystemBackdropConfiguration` used by `MicaController` and observe the incorrect colors being used.

### Expected behavior

The correct colors should be used.

### NuGet package version

1.2.220930.4-preview2

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

### Additional context

This is a regression from 1.2 Preview 1.

**Comment by gabbybilka** [comment]
Thanks for filing, tracked internally with https://task.ms/41782869

**Comment by bpulliam** [comment]
This is fixed in the stable release of 1.2
