### ISSUE TITLE
Unable to debug .NET Framework application with single project packaging

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/WindowsAppSDK#3050]
### Describe the bug

Trying to onboard the Windows App Sdk for the single project with packaging capability - which mostly works, except that debugging does not.
I cannot just use the "MsixPackage"-target and hit Run, I have to deploy, then use Debug -> Debug Installed App Package in order to get managed debugging to work.

### Steps to reproduce the bug

1. Create WindowsAppSdk project, change to WPF
2. Set breakpoint in MainWindow constructor
3. Debug
4. Observe nothing stops

See attached repro.

### Expected behavior

Step debugging works.

### NuGet package version

1.1.5

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621)

### IDE

Visual Studio 2022

### Additional context

[App3.zip](https://github.com/microsoft/WindowsAppSDK/files/9775999/App3.zip)

**Comment by MuyuanMS** [comment]
I'm unable to repro it now. I will close this issue and please let me know if this still has been an issue now with latest WinAppSDK
