### ISSUE TITLE
Need to add a platform in Push/AppNotifications IsSupported

### ISSUE THREAD

**Issue by pmpurifoy** [microsoft/WindowsAppSDK#3063]
### Describe the bug

There is a possibility that an app on downlevel builds does not have access to activating the PushNotificationsLongRunningProcess when elevated due to a missing COM flag. The API should check for this scenario.

### Steps to reproduce the bug

Try to CoCreateInstance the LRP on a machine that is missing ALLOW_LOWER_TRUST_ACTIVATION flag support and it will fail.

**Comment by gabbybilka** [comment]
@pmpurifoy With the PR merge, is this issue resolved?
