### ISSUE TITLE
Payload contains two or more files with the same destination path 'System.Diagnostics.EventLog.dll'

### ISSUE THREAD

**Issue by night-fury-me** [microsoft/WindowsAppSDK#3074]
### Describe the bug

Dear Concern,

When I tried to build my **WinUI 3** project after installing **Microsoft.Extensions.Hosting** nuget package in one of my Class Library (WinRT component) projects under the same solution I faced the following issue - 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	APPX1101	Payload contains two or more files with the same destination path 'System.Diagnostics.EventLog.dll'. Source files: 
C:\Users\{USER_NAME}\.nuget\packages\system.diagnostics.eventlog\6.0.0\runtimes\win\lib\net6.0\System.Diagnostics.EventLog.dll
C:\Users\{USER_NAME}\.nuget\packages\system.diagnostics.eventlog\6.0.0\lib\net6.0\System.Diagnostics.EventLog.dll	
C:\Users\{USER_NAME}\.nuget\packages\microsoft.windowsappsdk\1.1.5\buildTransitive\Microsoft.Build.Msix.Packaging.targets
```

Please let me know how I can fix the issue.
I have tried to clear the nuget cache folder and restored nuget packages from command line using - “nuget restore” . But this did not fix my issue.

Environment:
Visual Studio Professional 2022 v17.3.6
WindowsAppSDK v1.1.5
Microsoft.Extensions.Hosting v6.0.1

### Steps to reproduce the bug

1. Create a WinUI 3 (C#) project using [Template Studio](https://github.com/microsoft/TemplateStudio) 
2. Create a [csWinRT](https://github.com/microsoft/CsWinRT) component (class library) in the same solution 
3. Install Microsoft.Extensions.Hosting nuget package in the CsWinRT (class library) project
4. Try to build the project, the above-mentioned error will be raised

### NuGet package version

1.1.5

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

### IDE

Visual Studio 2022

**Comment by Scottj1s** [comment]
@redwandipto I tried to follow your repro steps, but I don't see any build issues.  If possible, please create a repro project (e.g. on github) and share it here.

**Comment by MuyuanMS** [comment]
Closing the issue as can't repro after no response for long time
