### ISSUE TITLE
Proposal: Fixed size compact overlay mode

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#309]
# Proposal: Fixed size compact overlay mode

Today you can set the default size for compact overlay but there's no way to keep it fixed and prevent the user from resizing it.

## Summary

Although you could resize manually be handling SizeChanged and calling TryResizeView, it's not a good experience since the actual window is not fixed and thus the resize cursor is shown at the border. There should be an option to make it fixed size.

## Rationale

* More flexibility for developers

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to make compact overlay fixed size | Must |

**Comment by rkarman** [comment]
For the Windows App SDK AppWindow APIs the CompactOverlay windows are by default non-resizable. Closing this issue.
