### ISSUE TITLE
ApplicationData API is not working after Restart

### ISSUE THREAD

**Issue by boxing-wang** [microsoft/WindowsAppSDK#3098]
### Describe the bug

ApplicationData API  is not working after calling AppInstance.Restart().

### Steps to reproduce the bug

Create a new WinUI 3 desktop app using C++/WinRT.
call AppInstance.Restart()
A new app restarted and crashed at 

   auto appData = ApplicationData::Current();

### NuGet package version

1.1.5

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2019

**Comment by scout208** [comment]
I am having this same issue. It occurs when using C# as well.

**Comment by DrusTheAxe** [comment]
>ApplicationData API is not working after calling AppInstance.Restart().
>...
>Create a new WinUI 3 desktop app using C++/WinRT.
>call AppInstance.Restart()
>A new app restarted and crashed at
>
>auto appData = ApplicationData::Current();

That implies it's not ApplicationData so much as ApplicationData.Current failing because your process isn't running with package identity. Sounds like `AppInstance.Restart()` is doing something causing the app to not be restarted correctly.

@dhoehna ?

**Comment by dhoehna** [comment]
Just got back from India.  Haven't looked yet, but thank you for bringing this to my attention.

**Comment by aeloros** [comment]
I was not able to repro this with either C# or C++/WinRT.
