### ISSUE TITLE
PasswordBox: the 👁 icon/button is inaccesible after losing focus

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/WindowsAppSDK#3102]
### Describe the bug

(with default properties)
When a **PasswordBox** receives input, a 👁 is shown on the right side so I can click it to show/hide the actual password. This icon is only shown when the control has focus - it is LOST after losing focus.

### Steps to reproduce the bug

Can be observed in the WinUI 3 Gallery.

- Open the page for the PasswordBox
- Type something in the first control
- click the eye to show/hide the password
- focus to another control on this page
- focus back to first control
- try and click the eye again - if you can

### Expected behavior

I expect this eye/button to be always accessible.
(well, at least when the control _IsEnabled_, of course)

### Screenshots

https://user-images.githubusercontent.com/65828559/199506208-dd1a9b13-b060-43f3-9bbc-e9a091d183ec.mp4

### NuGet package version

1.1.5

### Packaging type

Unpackaged

### IDE

Visual Studio 2022

### Additional context

Windows 10 version **22H2** is not in the dropdown for Windows Version. Same for Win11 22H2.

**Comment by Jay-o-Way** [comment]
FYI @niels9001 ?

**Comment by Jay-o-Way** [comment]
> **Note**
> This is even visible in the log-in screen on Windows 11 (22H2)

**Comment by gabbybilka** [comment]
This is by design as a security precaution to ensure the password only visible when the user is actively typing their password.

**Comment by Jay-o-Way** [comment]
If one would have said "the password is only visible when the user is actively **holding the button down**", that would be 100% solid. The words "when the user is actively typing their password" aren't even accurate, because in order to make it possible to see any password, the input first has to be cleared. If there would be anybody physically present, the need to type it again is also a security issue?

**Comment by gabbybilka** [comment]
Here are the docs detailing the behavior in a bit more detail: https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.passwordbox?view=windows-app-sdk-1.1#password-reveal-mode

> Note that due to security reasons that button is shown only when the PasswordBox receives focus for the first time and a character is entered. If the PasswordBox loses focus and then regains focus, the button is not shown again unless the password is cleared and character entry starts over.
