### ISSUE TITLE
`vcmeta.dll` and incremental builds in .NET MAUI projects

### ISSUE THREAD

**Issue by jonathanpeppers** [microsoft/WindowsAppSDK#3128]
This is somewhat related to [this older issue](https://developercommunity.visualstudio.com/t/amd64-version-of-vcmetadll-is-missing/1626692).

We found installing the .NET MAUI workload in Visual Studio, incremental builds always hit time spent in:

![image](https://user-images.githubusercontent.com/840039/201175673-eae14a01-b98c-46f9-8217-7d0397620fa4.png)

But if you install this workload:

![image](https://user-images.githubusercontent.com/840039/201175804-009ea597-0f5c-4b15-968f-e103d24cd8e5.png)

Then the problem goes away:

![image](https://user-images.githubusercontent.com/840039/201175944-de54a6b8-e566-4172-afcb-4f492a87f8ca.png)

Debugging what is happening, I found the presence of:

```
VCInstallPath32 = C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX64\x86\vcmeta.dll
VCInstallPath64 = C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\vcmeta.dll
```
When these exist, incremental builds are able to skip extra work. When they are missing, you see:
```
Xaml Compiler Marker: 2:31:45 PM: 887 perfXC_FingerprintCheck, Local Assembly FingerPrint Changed
Xaml Compiler Marker: 2:31:45 PM: 887 perfXC_FingerprintCheck, Reference Assemblies Fingerprint Changed
```

**Ask**: Can we avoid `vcmeta.dll` usage? or ship this file as part of the Windows App SDK?

Details on how we are addressing this for now [here](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/435030). It unfortunately will add ~290MB to .NET MAUI's install footprint.

**Comment by mattleibow** [comment]
Is it possible to add the (hopefully) few bits to the https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools NuGet so `dotnet build` also works well when there is no VS installed?

BuildTools is great because it allows for a much smaller dev install and also removes the requirement of VS to build on CI.

**Comment by mattleibow** [comment]
I see in the WASDK targets `Microsoft.UI.Xaml.Markup.Compiler.interop.targets`:

```xml
    <Target Name="GetVCInstallPath" Condition="'$(VCInstallPath32)' == '' and '$(VCInstallPath64)' == ''">
      <GetLatestMSVCVersion MSVCDirectoryPath="$(VsInstallRoot)\VC\Tools\MSVC" Condition="'$(VCToolsInstallDir)' == '' and '$(VsInstallRoot)' != ''">
        <Output TaskParameter="LatestMSVCVersion" PropertyName="LatestMSVCVersion"/>
      </GetLatestMSVCVersion>
      <PropertyGroup Condition="'$(VCToolsInstallDir)' == '' and '$(VsInstallRoot)' != ''">
        <VCToolsInstallDir Condition="'$(VCToolsInstallDir)' == ''">$(VsInstallRoot)\VC\Tools\MSVC\$(LatestMSVCVersion)\</VCToolsInstallDir>
      </PropertyGroup>
      <PropertyGroup Condition="'$(VCToolsInstallDir)' != ''">
        <_VCInstallPathHostArchitecture Condition="'$(PROCESSOR_ARCHITECTURE)' == 'x86'">X86</_VCInstallPathHostArchitecture>
        <_VCInstallPathHostArchitecture Condition="'$(PROCESSOR_ARCHITECTURE)' != 'x86'">X64</_VCInstallPathHostArchitecture>
        <VCInstallPath32>$(VCToolsInstallDir)bin\Host$(_VCInstallPathHostArchitecture)\x86\vcmeta.dll</VCInstallPath32>
        <VCInstallPath64>$(VCToolsInstallDir)bin\Host$(_VCInstallPathHostArchitecture)\x64\vcmeta.dll</VCInstallPath64>
      </PropertyGroup>
    </Target>
```

Looking at this, it appears if the BuildTools NuGet could set the `$(VCInstallPath32)` and `$(VCInstallPath64)` paths, then this should be skipped?

**Comment by mattleibow** [comment]
Looking at the binlog for `dotnet build`, it does not actually follow the same path:

> Task "CompileXaml" skipped, due to false condition; ('$(UseXamlCompilerExecutable)' != 'true') was evaluated as ('true' != 'true').

Instead it uses an executable - but that also takes a long time:

```
Exec = 4.7s
    Assembly = Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
    Parameters
        Command = "C:\Users\mattl\.nuget\packages\microsoft.windowsappsdk\1.1.5\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Debug\net7.0-windows10.0.19041.0\win10-x64\\input.json" "obj\Debug\net7.0-windows10.0.19041.0\win10-x64\\output.json"
    CommandLineArguments = "C:\Users\mattl\.nuget\packages\microsoft.windowsappsdk\1.1.5\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\Debug\net7.0-windows10.0.19041.0\win10-x64\\input.json" "obj\Debug\net7.0-windows10.0.19041.0\win10-x64\\output.json"
```

**Comment by evelynwu-msft** [comment]
Tagging @mikebattista to comment on the feasibility of adding `vcmeta.dll` (from VC++ tools) to the `Microsoft.Windows.SDK.BuildTools` Nuget package; WinUI uses one of its exported functions to compare two assemblies/winmds and determine whether or not they have the same *public* APi surface.

**Comment by jonathanpeppers** [comment]
This is completed by: https://microsoft.visualstudio.com/WinUI/_git/microsoft-ui-xaml-lift/pullrequest/8128511

We ported `vcmeta.dll` usage to C# using System.Reflection.Metadata.
