### ISSUE TITLE
Changing visibility of ComboBox after selecting an option from the list results in 'Error HRESULT E_FAIL'

### ISSUE THREAD

**Issue by onslauth** [microsoft/WindowsAppSDK#3145]
### Describe the bug

Changing the visibility of a ComboBox to 'collapsed' after selecting a value causes the following error:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
Exception thrown at 0x763BE062 (KernelBase.dll) in TestComboBox.exe: WinRT originate error - 0x80004005 : 'Error HRESULT E_FAIL has been returned from a call to a COM component.'.
Exception thrown: 'System.Runtime.InteropServices.COMException' in System.Private.CoreLib.dll
Exception thrown at 0x763BE062 (KernelBase.dll) in TestComboBox.exe: WinRT originate error - 0x80004005 : 'Error HRESULT E_FAIL has been returned from a call to a COM component.'.
```

### Steps to reproduce the bug

I have provided an example application you can clone from [https://github.com/onslauth/TestComboBox](https://github.com/onslauth/TestComboBox)

Click the "Show" button to display the ComboBox
Select a value in the ComboBox
Click the "Hide" button to hide the ComboBox

Interestingly, if no value is selecting between displaying/hiding ComboBox, the crash does not occur.

### Expected behavior

There shouldn't be an error when hiding the ComboBox after selecting a value.

### NuGet package version

1.1.5

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H1 (19043, May 2021 Update)

### IDE

Visual Studio 2022

**Comment by castorix** [comment]
You must add a test in _ComboBox_SelectionChanged_ :

```
        private void ComboBox_SelectionChanged( object sender, SelectionChangedEventArgs e )
        {
            if (e.AddedItems.Count > 0)
            {
                var item = e.AddedItems[0] as Tuple<int, string>;
                this.index = item.Item1;
            }
        }
```

**Comment by onslauth** [comment]
@castorix Thank you very much for the solution to fixing this. I have tested it and can confirm that it works.

However, I am surprised that the `SelectionChanged` event is called when the ComboBox visibility changes, and I clearly I did not expect that to be the cause.

**Comment by onslauth** [comment]
@castorix Sorry to bother again, I do have one last question. 

Did your VS manage to catch the exception in the `SelectionChanged` event handler, or did you know the fix because you ran into this issue before?

**Comment by castorix** [comment]
> Did your VS manage to catch the exception in the `SelectionChanged` event handler, or did you know the fix because you ran into this issue before?

No, I thought there could be a problem with an array, so I added a BP at  _var item = e.AddedItems[0] as Tuple<int, string>;_
to check when it was called and what was in variables, mainly _AddedItems_
