### ISSUE TITLE
Crash on closing the TabView window

### ISSUE THREAD

**Issue by kingcean** [microsoft/WindowsAppSDK#3149]
### Describe the bug

If you have an app which pops up a window with TabView, it will crash on closing the window after closing any tab(s) there.

### Steps to reproduce the bug

Repro on WinUI 3 Gallery.

1. Turn to _TabView_ sample page under _Navigation_ group.
2. Click _Click here to launch the sample_ button in _Complete TabView windowing sample_ section.
3. Close any 1 tab or 2 tabs in the window.
4. Close the window; or close all tabs.

You will see the app crashes immediately. Following is copied from Event Viewer.

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <EventRecordID>4341</EventRecordID> 
  <Correlation /> 
  <Channel>Application</Channel> 
  <!-- something else… --> 
</System>
<EventData>
  <Data Name="AppName">WinUIGallery.DesktopWap.exe</Data> 
  <Data Name="AppVersion">1.0.0.0</Data> 
  <Data Name="AppTimeStamp">6331eb0e</Data> 
  <Data Name="ModuleName">Microsoft.ui.xaml.dll</Data> 
  <Data Name="ModuleVersion">3.0.0.2211</Data> 
  <Data Name="ModuleTimeStamp">6a51b790</Data> 
  <Data Name="ExceptionCode">c0000005</Data> 
  <Data Name="FaultingOffset">0000000000793127</Data> 
  <Data Name="ProcessId">0x7c10</Data> 
  <Data Name="ProcessCreationTime">0x1d8f8eaee2dfeda</Data> 
  <Data Name="AppPath">C:\Program Files\WindowsApps\Microsoft.WinUI3ControlsGallery_1.3.16.0_x64__8wekyb3d8bbwe\WinUIGallery.DesktopWap\WinUIGallery.DesktopWap.exe</Data> 
  <Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.2_2000.677.1750.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll</Data> 
  <Data Name="IntegratorReportId">e605dd71-f9c6-41a6-a764-8648329f3d24</Data> 
  <Data Name="PackageFullName">Microsoft.WinUI3ControlsGallery_1.3.16.0_x64__8wekyb3d8bbwe</Data> 
  <Data Name="PackageRelativeAppId">App</Data> 
</EventData>
</Event>
```

### Expected behavior

The window closes without crash or any other exceptions.

### Screenshots

![image](https://user-images.githubusercontent.com/1724940/201937043-20cb7982-867d-4df9-a093-779e7f3bfa4b.png)
Turn to TabView sample page under Navigation group. Then click _Click here to launch the sample_ button in _Complete TabView windowing sample_ section.

![image](https://user-images.githubusercontent.com/1724940/201937169-54f433c3-a80a-4301-9cff-3246bfe5f1c5.png)
Close a tab.

![image](https://user-images.githubusercontent.com/1724940/201937262-0c4f8381-4955-4a5e-9fc8-a219d9322e05.png)
Close the window.

### NuGet package version

1.2.221109.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

This is a critical issue for the app with tab titlebar styled window.

But it will not crash for the senario of `TabView` in the main window so you may repro it only for new window.

**Comment by codendone** [comment]
Top of the stack:
```
Microsoft_ui_xaml!DirectUI::FrameworkElementLayoutUpdatedTraits::detach_handler+0x5
Microsoft_ui_xaml!ctl::token_event_handler<ABI::Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable,DirectUI::FrameworkElementLayoutUpdatedTraits>::RemoveEventHandler+0x37
Microsoft_ui_xaml!ctl::event_handler_base<ABI::Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable,DirectUI::FrameworkElementLayoutUpdatedTraits>::Invoke+0x152617
Microsoft_ui_xaml!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,ABI::Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::Raise+0x87
Microsoft_ui_xaml!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,ABI::Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::UntypedRaise+0x71
Microsoft_ui_xaml!DirectUI::FrameworkElement::RaiseLayoutUpdated+0x46
Microsoft_ui_xaml!DirectUI::DXamlCore::OnLayoutUpdated+0xd8
Microsoft_ui_xaml!DirectUI::DXamlCore::RaiseEvent+0x352
Microsoft_ui_xaml!CLayoutManager::UpdateLayout+0x3e0
Microsoft_ui_xaml!CCoreServices::NWDrawTree+0x1e7
Microsoft_ui_xaml!CCoreServices::NWDrawMainTree+0x14a
Microsoft_ui_xaml!CWindowRenderTarget::Draw+0x6d
```

It appears that an event handler for the underlying CWindowChrome tried to disconnect earlier and only got handled at this point, with FrameworkElementLayoutUpdatedTraits crashing because RaiseLayoutUpdated passes in a null pSender.

**Comment by kingcean** [comment]
It can repro on v1.3.230724000.
Could you please let me know if have a plan to fix?

**Comment by kingcean** [comment]
It works well on v1.4.230822000 now.
