### ISSUE TITLE
SystemEvents.UserPreferenceChanged cannot be triggered

### ISSUE THREAD

**Issue by ArvinZJC** [microsoft/WindowsAppSDK#3158]
### Describe the bug

I tried to attach an event handler to [`SystemEvents.UserPreferenceChanged`](https://learn.microsoft.com/en-gb/dotnet/api/microsoft.win32.systemevents.userpreferencechanged?view=dotnet-plat-ext-7.0). However, it seems that the event is not triggered for the WinUI 3 desktop app using the Windows App SDK.

### Steps to reproduce the bug

You may just create a simple project with a main window and a main page on it. For the page_OnLoaded event, add:

```C#
using Microsoft.Win32;

# OnLoaded
SystemEvents.UserPreferenceChanged += SystemEventsOnUserPreferenceChanged;

private void SystemEventsOnUserPreferenceChanged(object sender, UserPreferenceChangedEventArgs e)
{
    throw new NotImplementedException();
}

# OnUnloaded
SystemEvents.UserPreferenceChanged -= SystemEventsOnUserPreferenceChanged;
```

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by castorix** [comment]
A workaround is to handle [WM_SETTINGCHANGE](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange) 
(tested on Windows 10 21H1)

**Comment by ArvinZJC** [comment]
> A workaround is to handle [WM_SETTINGCHANGE](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange) (tested on Windows 10 21H1)

Could you show me your code?

**Comment by castorix** [comment]
With _SetWindowSubclass_, like in some samples I posted ([MainWindow.xaml.cs](https://github.com/castorix/WinUI3_DirectShow_Capture/blob/dc298cce9f18ccae4faaaa4e97a2e6479139d6d8/MainWindow.xaml.cs) for declarations)

on main window handle _hWnd_  :

       hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
       SubClassDelegate = new SUBCLASSPROC(WindowSubClass);
       bool bReturn = SetWindowSubclass(hWnd, SubClassDelegate, 0, 0);
 
 with (I tested by changing System colors and I get : "_Settings = ImmersiveColorSet_") :
 
        public const int WM_WININICHANGE = 0x001A;
        public const int WM_SETTINGCHANGE = WM_WININICHANGE;
        
        private int WindowSubClass(IntPtr hWnd, uint uMsg, IntPtr wParam, IntPtr lParam, IntPtr uIdSubclass, uint dwRefData)
        {
            switch (uMsg)
            {              
                case WM_SETTINGCHANGE:
                    {
                        // Console.Beep(6000, 10);
                        string sText = Marshal.PtrToStringUni(lParam);
                        System.Diagnostics.Debug.WriteLine(string.Format("Settings = {0}", sText));
                    }
                    break;
            }
            return DefSubclassProc(hWnd, uMsg, wParam, lParam);
        }

**Comment by cnbluefire** [comment]
The events of SystemEvents class cannot be raised because when the SystemEventInvokeInfo object captures the SynchronizationContext of the current thread, the SynchronizationContext.Send is called when RaiseEvent, and DispatcherQueueSynchronizationContext has not implemented the Send method.

Solution:
```cs
SystemEvents.InvokeOnEventsThread(() =>
{
    // No need to set, the default is null
    //SynchronizationContext.SetSynchronizationContext(null);

    SystemEvents.DisplaySettingsChanged += (s, a) =>
    {
        Debug.WriteLine("DisplaySettingsChanged");
    };
});
```
