### ISSUE TITLE
Window's min size support

### ISSUE THREAD

**Issue by ArvinZJC** [microsoft/WindowsAppSDK#3163]
### Describe the bug

I know there is a way to use [WinUIEx](https://github.com/dotMorten/WinUIEx) or pinvoke to set the min size of a window. But should we have a simpler way like exposing properties to set the min size?

### Steps to reproduce the bug

AppWindow/Window does not have properties/methods to set the min size.

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by castorix** [comment]
There was a similar thread at : [#7296](https://github.com/microsoft/microsoft-ui-xaml/issues/7296)
