### ISSUE TITLE
Documentation of the Bootstrap API 'MddBootstrapInitialize(2)' is not clear

### ISSUE THREAD

**Issue by Woopsalla** [microsoft/WindowsAppSDK#3165]
### Describe the bug

The documentation of the function gives the impression that the parameters 'majorMinorVersion' and 'minVersion' only specify a minimum required SDK runtime version. Example: With majorMinorVersion => v1.1 and minVersion => v1.1.3 one could think that the application runs with runtime version v1.1.4, but also with v1.2.0, v1.4.4 and so on.
Only when looking into the source code of the Bootstrap DLL it becomes clear that only a runtime with exactly the major and minor version specified in 'majorMinorVersion' is loaded and that 'minVersion' only refers to the build and revision level of the version. This behavior is good, but it should also be clearly documented. Examples often do more than a thousand words here.  

### Steps to reproduce the bug

View the documentation.

**Comment by stevewhims** [comment]
Thanks for filing this issue, @Woopsalla. I've published an update to MddBootstrapInitialize and MddBootstrapInitialize2. I think the info there is clearer now, along the lines of your suggestions.

I can't close this issue, but perhaps somebody else can.

Thanks again!
-Steve

**Comment by Woopsalla** [comment]
Thanks for the quick fix.
