### ISSUE TITLE
Windows App Runtime 1.2 store installation and side-loaded packages conflict

### ISSUE THREAD

**Issue by BenJKuhn** [microsoft/WindowsAppSDK#3168]
### Describe the bug

The store and side-load packages of the Windows App Runtime 1.2 have different phone identities, causing installation of either to fail if the other is already installed. This was reported on Twitter here: https://twitter.com/dotMorten/status/1594737193666215937

I was also able to confirm the issue & repro.

### Steps to reproduce the bug

Install an app from the store that uses Windows App Runtime 1.2 package (e.g. WinUI 3 Gallery), then try to install Windows App SDK using the standalone installer.

### Expected behavior

Installs cleanly in either case, or does nothing if already installed.

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

**Comment by roxk** [comment]
This had happened before: https://github.com/microsoft/WindowsAppSDK/issues/1953#issuecomment-1039889981

Anyway to setup a test to catch this before rolling out a release? The test would install the stored-signed package and then install using `installer.exe`. Rollout should be blocked unless test succeeds.

**Comment by MikeHillberg** [comment]
[Internal tracking](http://task.ms/42339525)

**Comment by MikeHillberg** [comment]
@dotMorten, how are you installing when you see this? Using the Store? Using the WindowsAppRuntimeInstall.exe from the download center?

**Comment by dotMorten** [comment]
@MikeHillberg Installing? I'm just pressing F5 in Visual Studio.
I do think the WinUI 3 Gallery was installed via the store which is likely what it was conflicting with.

**Comment by bpulliam** [comment]
🎉Microsoft.WindowsAppSDK.1.2.221209.1 has been released which fixes this issue.

Handy links:

[Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/release-notes)
[Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1)
