### ISSUE TITLE
Unpackaged app compilation fail due to space in profile name

### ISSUE THREAD

**Issue by mattleibow** [microsoft/WindowsAppSDK#3173]
---
**Issue moved from dotnet/maui#11518**
- Please respond to @brignolff.

---

_From @brignolff on Monday, November 21, 2022 8:39:16 AM_

### Description

When building an unpackaged MAUI app, the build fails due to a white space in the "C:\\users\*profile name*" folder.

### Steps to Reproduce

1. Create a profile with a space in the name
2. create a MAUI app using the VS template
3. add the <WindowsPackageType>None</WindowsPackageType> node to a PropertyGroup in the .csproj
4. change the "CommandName" to "project" in the "launchSetting.json"
5. try to build in release or debug.

### Link to public reproduction project repository

none because linked to user profile and not project

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows, I was *not* able test on other platforms

### Affected platform versions

windows 10 21H2

### Did you find any workaround?

Had to make a new user profile without the space in the name

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#11518**
- Please respond to @jsuarezruiz.

---

_From @jsuarezruiz on Monday, November 21, 2022 3:13:01 PM_

Could you share more information like your bin logs?

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#11518**
- Please respond to @msftbot[bot].

---

_From @msftbot[bot] on Monday, November 21, 2022 3:13:08 PM_

Hi @brignolff. We have added the "s/needs-info" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.

**Comment by mattleibow** [comment]
---
**Issue moved from dotnet/maui#11518**
- Please respond to @brignolff.

---

_From @brignolff on Monday, November 21, 2022 5:27:25 PM_

Hi, 

As mentioned in the post I fixed the bug by creating à second user profile without the space in the name. 

After reinstalling everything and transfering my data I deleted the old profile and I'm now unable to provide log or reproduce the bug.

**Comment by Scottj1s** [comment]
Could be related to https://github.com/microsoft/WindowsAppSDK/issues/2929 (fixed in 1.3)

**Comment by evelynwu-msft** [comment]
Agreed, this looks to be a duplicate.
