### ISSUE TITLE
RedirectActivationToAsync throws System.Runtime.InteropServices.COMException: 'Interface not registered (0x80040155)'

### ISSUE THREAD

**Issue by nodew** [microsoft/WindowsAppSDK#3179]
### Describe the bug

I'm trying to build a single instance App with
```cs
    protected async override void OnLaunched(LaunchActivatedEventArgs args)
    {
        base.OnLaunched(args);
        
        var mainInstance = AppInstance.FindOrRegisterForKey("app-main");

        if (!mainInstance.IsCurrent)
        {
            var activatedEventArgs = AppInstance.GetCurrent().GetActivatedEventArgs();
            await mainInstance.RedirectActivationToAsync(activatedEventArgs);
            System.Diagnostics.Process.GetCurrentProcess().Kill();
            return;
        }

        await App.GetService<IActivationService>().ActivateAsync(args);
    }
```
When I activate the app with Protocol URI, `RedirectActivationToAsync` throws the following exception:
```
System.Runtime.InteropServices.COMException: 'Interface not registered (0x80040155)'
```

### Steps to reproduce the bug

OS: Windows 11H2 
Build: 22621.819
Visual Studio 2022 17.4
TargetFramework: net7.0-windows10.0.19041.0
WindowsAppSdk: 1.2.221116.1

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by jindal1979** [comment]
I also get the  COMException error on a significant number of user devices for GetActivatedEventArgs(), RedirectActivationToAsync(), GetFileFromPathAsync(), etc functions. I am using the latest Windows App SDK 1.2.1: 1.2.221116.1

**Comment by JasonWei512** [comment]
For some reason activation redirection works on my PC, but doesn't work with builds compiled on GitHub Action's Windows Server 2022 image.

**Comment by TomPMoleman** [comment]
I'm sadly facing the very same issue, but I found out what is actually causing this strange issue.
Basically I was comparing my code and configurations to [the following very basic sample](https://github.com/jingwei-a-zhang/WinAppSDK-DrumPad) (which did not expose this error!) just to find out, that upon declaring the sample to be a **packaged self-contained** app, the exception is finally thrown.

Thus, please retest it on your own by adding the following to a PropertyGroup within the sample's csproj:
`<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`

BR Thomas

**Comment by bogdan-patraucean** [comment]
@dhoehna hi! any updates on this?

**Comment by aeloros** [comment]
I'm unable to reproduce the issue locally on my machines.  If anyone watching this issue has a repro, there are some steps I'd love to have done to collect data about the problem.

Thanks
--Scott

**Comment by TomPMoleman** [comment]
Sorry, my bad, must have linked the wrong sample though: https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/AppLifecycle/Activation

Nevertheless, attached you may find a very basic project (based on the correct sample) in order for you to easily reproduce the issue:
[CsWinUiDesktopActivation.zip](https://github.com/microsoft/WindowsAppSDK/files/12214133/CsWinUiDesktopActivation.zip)

As already stated, the main cause for this ComException to be thrown is the _WindowsAppSDKSelfContained_ property within the csproj definition. Only upon setting it to a value of **'true'** you'll be able to encounter this issue.

=> Can you please check and reopen the ticket again?
Thanks, BR
Thomas

**Comment by TomPMoleman** [comment]
Hi @aeloros,

by any chance, did you find time to retest and reproduce this issue using the attached project?
The proposed workaround of using an extra packaging-project within the [linked ticket](https://github.com/microsoft/WindowsAppSDK/issues/3439) is not an option and this issue results in one of our apps being almost useless after migrating it from UWP to WinUi3 (thus we still did not submit it to the MS Store). :( 

Thanks, BR
Thomas

**Comment by aeloros** [comment]
> Hi @aeloros,
> 
> by any chance, did you find time to retest and reproduce this issue using the attached project? The proposed workaround of using an extra packaging-project within the [linked ticket](https://github.com/microsoft/WindowsAppSDK/issues/3439) is not an option and this issue results in one of our apps being almost useless after migrating it from UWP to WinUi3 (thus we still did not submit it to the MS Store). :(
> 
> Thanks, BR Thomas

I'm unable to reproduce this anymore on any of my machines.  If you could help gather data, it would help further diagnose the issue.  You can do this by using the "Recreate my problem" attachment inside Feedback Hub, when reporting a problem.  When you do this, use the "Include data about" checkbox with the "General" selection in the drop down.  This will upload information for me and others to look at that should help narrow down why it's doing this.

Thanks
--Scott

**Comment by RockNHawk** [comment]
I have this issue as well.
with this microsoft open-source app: https://github.com/microsoft/ai-dev-gallery
and this also https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error

**Comment by RDMacLachlan** [comment]
> I have this issue as well. with this microsoft open-source app: https://github.com/microsoft/ai-dev-gallery and this also https://github.com/justinsoderstrom/winappsdk-selfcontained-activation-error

Hi @RockNHawk, please create a new issue for this.
