### ISSUE TITLE
TabView buttons rendering error when extended into TitleBar

### ISSUE THREAD

**Issue by paulober** [microsoft/WindowsAppSDK#3193]
### Describe the bug

If you enable the `ExtendsContentIntoTitleBar` feature and have a TabView as root node of your window XAML all works well with the extending into the Titlebar. Except the buttons (add new tab; close tab) does not work correct. For example the hover animation only show if your cursor is not over the icon of these buttons and they are also not clickable if you click on the icon in the button. That is a unusable state of this component in combination with the titlebar extend feature for a production app as you have to carefully position your mouse cursor on the button and not hover over the icon inside.

### Steps to reproduce the bug

1. Create new Packaged Windows App SDK app. 
2. Create a TabView as root component of your MainWindow.xaml
3. Add a tab into the tab view xaml
4. Retrieve the AppWindow.TitleBar object in your MainWindow.xaml.cs and set `ExtendsContentIntoTitleBar` to `true`

Test the app and hover over the TabView Buttons like "add new tab" and "close tab" and you'll see the problem.

### Expected behavior

Function as their were not extended into the TitleBar where they work well.

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by paulober** [comment]
Any updates on this?

**Comment by paulober** [comment]
@gabbybilka Sorry for ping you directly. I just want to know if this bug is already on the to-do list of the devs and if there are plans to fix it, since I haven't heard anything about it for 3 months but the bug still exists (even in the latest release)?

**Comment by paulober** [comment]
[Small sample of the issue in a newly created project](https://user-images.githubusercontent.com/44974737/223557074-05fe85ac-9778-4e6f-8e97-76ec6d5df6f2.mp4)

**Comment by peterjtan** [comment]
Closing this issue for now as problem is resolved. Feel free to reopen it (or create a new one) if problem persists. Thanks!
