### ISSUE TITLE
WinUI templates should not show up in Blend

### ISSUE THREAD

**Issue by mgoertz-msft** [microsoft/WindowsAppSDK#3201]
### Describe the bug

VS and Blend do not have a designer for WinUI, so the WinUI templates should not be available in Blend, which is primarily for design experiences.

### Steps to reproduce the bug

1. Install Visual Studio and add the .NET Desktop and UWP workloads (make sure the Windows App SDK C# templates are selected in the optional components for the .NET Desktop workload)
2. Launch Blend from the Start menu
3. Click Create new project

WinUI templates show up with unfriendly titles and descriptions.

### Expected behavior

WinUI templates should not even be available in Blend, since there is no designer for WinUI.

### Screenshots

![image](https://user-images.githubusercontent.com/14282894/205119144-794d664f-fa28-446f-b90c-7401ea6e5de5.png)

### NuGet package version

None

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview

**Comment by MSLukeWest** [comment]
The likely fix is to just remove this line from the .vstemplate files:

`<AppIdFilter>blend</AppIdFilter>`

**Comment by MSLukeWest** [comment]
@evelynwu-msft This change seems to have made it into the latest 1.4 templates, as I no longer see these templates in Blend.  So, this issue can probably be closed.
