### ISSUE TITLE
Showing a ContentDialog in an AppWindow.Closing event handler abruptly terminates app

### ISSUE THREAD

**Issue by DHancock** [microsoft/WindowsAppSDK#3209]
### Describe the bug

I'm attempting to show a simple content dialog that prompts the user to save unsaved changes. It's shown inside the app window closing event handler. When the code reaches the ContentDialog.ShowAsync() call, no dialog is shown and the app abruptly terminates.

I've attached WinDbg but no exceptions appear to be thrown, the stack simply shows NtTerminateProcess is called.

### Steps to reproduce the bug

1. Run the attached solution.
2. Click the button - a content dialog is correctly shown.
3. Close the window - the same content dialog should be shown, but isn't.

[ContentDialogIssue.zip](https://github.com/microsoft/WindowsAppSDK/files/10146304/ContentDialogIssue.zip)

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by castorix** [comment]
A workaround can be to do :

        private async void AppWindow_Closing(AppWindow sender, AppWindowClosingEventArgs args)
        {
            args.Cancel = true;           
            ShowDialog();
        }
        
        private async void ShowDialog()
        {
            ContentDialog cd = new ContentDialog();

            cd.XamlRoot = this.Content.XamlRoot;
            cd.PrimaryButtonText = "Save";
            cd.SecondaryButtonText = "Don't Save";
            cd.CloseButtonText = "Cancel";
            cd.Content = "Do you want to save the file?";

            ContentDialogResult cdr = await cd.ShowAsync();
            if (cdr != ContentDialogResult.None)
            {
                // code....
                this.Close();
            }           
        }

**Comment by DHancock** [comment]
Thanks, but the problems is with the line:

`ContentDialogResult cdr = await cd.ShowAsync();`

The code never gets past that point, it's terminated immediately inside `ShowAsync()`

The problem seems to be with `ContentDialog` implementation that only shows when its called from an event handler that's invoked after a WM_CLOSE message has been recieved.

**Comment by castorix** [comment]
Have you added _args.Cancel = true;_    ?
I tested  on Windows 10 21H1, App SDK 1.1.0 and it works fine for me

**Comment by DHancock** [comment]
Ah, I see what you mean. It's not a bug at all, I'd forgotten that the await call isn't blocking, it's created a continuation routine. Thanks, I'll close this one.
