### ISSUE TITLE
Unable to build WinUI 3 app with WinForms enabled

### ISSUE THREAD

**Issue by shinta0806** [microsoft/WindowsAppSDK#3211]
### Describe the bug

In WinUI 3 project, build errors occur with WinForms enabled.

### Steps to reproduce the bug

1. Create new WinUI 3 project (Empty packaged app, Desktop WinUI 3). Build OK.
1. Enable Windows Forms in project property.
1. MC6000 error (project needs PresentasionCore, PresentationFramework) occurs.
1. Try to enable WPF in project property.
1. MC3074 error (tag 'XamlControlsResources' doesn't exist in XML namespace 'using:Microsoft.UI.Xaml.Controls') occurs.

Project files are:
https://github.com/shinta0806/TestWinUi3WithForms

### Screenshots

New WinUI 3 project:
![1](https://user-images.githubusercontent.com/7196473/205478648-2360e060-f867-4dba-b874-2cfc7db47ba0.png)

Enable Windows Forms:
![2](https://user-images.githubusercontent.com/7196473/205478658-21c25953-caf3-4ed5-bf9c-a590d5a247fd.png)

MC6000 error:
![2a](https://user-images.githubusercontent.com/7196473/205478682-d1e9d55f-5dc2-4403-a622-6e048ca305fd.png)

Enable WPF:
![3](https://user-images.githubusercontent.com/7196473/205478691-e54293e7-ffe7-48f9-974d-70cd0ca05af0.png)

MC3074 error:
![4](https://user-images.githubusercontent.com/7196473/205478702-80569dd8-db72-48f0-81a4-580710355dcd.png)

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Visual Studio 2022 Version 17.4.2

**Comment by christosk92** [comment]
Frameworkが全然違うので、WinUI 3でWinformsは使えないと思うんですけど..

**Comment by shinta0806** [comment]
説明が不足していましたが、まず、WinForms を使いたい目的ですが、Windows App SDK だけではまだ機能が足りないのではないかと思うからです。例えば、マルチディスプレイを扱うのは WinForms のほうが簡単なのではないでしょうか（System.Windows.Forms.Screen）。

そして、フレームワークが全然違っていても、両方のフレームワークは使えます。例えば、WPF で WinForms のクラスを使うことが出来ます。さらにはコントロールであっても、WindowsFormsHost がありますので使えます。

もし、Windows App SDK は他のフレームワークと排他であるということであれば、WinForms や WPF を有効にするオプションを表示しないで欲しいです。

**Comment by castorix** [comment]
You can use WinForms classes by adding Reference to System.Windows.Forms.dll and other DLLs
(from _C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\_...)
But it is usually not needed, as you can use any Win32 API in WinUI (P/Invoke in C#), which are also used by WinForms...

**Comment by shinta0806** [comment]
Thanks for the information.

**Comment by gabbybilka** [comment]
We aren't prioritizing building WinUI 3 apps with WinForms classes at this time. However, it looks like you have the information you need for this scenario. Thanks @castorix for hopping in.

**Comment by shinta0806** [comment]
This was resolved by splitting the project within the Solution.
https://zenn.dev/shinta0806/articles/winui3-winforms
