### ISSUE TITLE
ARM64 build in UWP project build with WAP (Windows application package) has no AssemblyInfo.cs data

### ISSUE THREAD

**Issue by sunjw** [microsoft/WindowsAppSDK#3213]
### Describe the bug

After build ARM64 config solution in UWP project build with WAP, I got an exe and a dll in WAP bin/ARM64 directory. The exe and dll have no FileVersion, Verion and other info defined in AssemblyInfo.cs. But x64 config build has all those data. The exe and dll produced under UWP project has AssemblyInfo in both x64 and arm64 config.

### Steps to reproduce the bug

1. Create an UWP project with WAP project.
2. Build the solution with ARM64 config

### Expected behavior

ARM64 WAP project output (main exe and dll from UWP project) has AssemblyInfo data.

### NuGet package version

None

**Comment by gabbybilka** [comment]
UWP on ARM64 isn't an app scenario we're actively supporting. We found a StackOverflow answer that may be able to help: https://stackoverflow.com/questions/53483291/unable-to-build-for-arm64-from-uwp-packaging-project-uwp-win32 Or, if you'd like to open a question on our repo about this topic, feel free to!
