### ISSUE TITLE
Package version is different from the version shown on application's installation window

### ISSUE THREAD

**Issue by petercoin** [microsoft/WindowsAppSDK#3220]
### Describe the bug

I have a C++ Desktop application Packaged with WAP project.
I have noticed that the package generated by WAP sometimes has different version number with the application itself.
For example, the msixupload shows 1.0.33.0 but the application shows 1.0.32.0.
This is not the first time I ran into this problem, but I didn't know how to reproduce it.
However, this is very annoying because our customer will ask why the version is inconsistent.
Could you check for this issue?

### Steps to reproduce the bug

N/A

### NuGet package version

1.1.5

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment]
First impression is that the version number may be updated by your build pipeline.  The resource inside the app may be using the old number, it gets updated, and then the packaging uses the new number.  If that is not the case, can you link to a repo or a store package we can look inside?

**Comment by petercoin** [comment]
@bpulliam 
As you said, I've found there are two AppxManifest.xml files and the one for upload package has a new number.
The version numbers in these two files are inconsistent.
After Clean Solution and Build Solution, this issue was gone.
However, I've never met this kind of issue while developing UWP before.
Is there any methodology to prevent this issue?

**Comment by bpulliam** [comment]
A simple first step is to add a test on your release pipeline to verify it. The next level would be to ensure that they are changed in sync.  If it is done manually, then have a comment that they both need to change.  If it is automated, then be sure that both are changed together.
