### ISSUE TITLE
The DisplayInformation class is missing DPI related functionality

### ISSUE THREAD

**Issue by ackh** [microsoft/WindowsAppSDK#3227]
### Describe the bug

The [`Microsoft.Graphics.Display.DisplayInformation`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.graphics.display.displayinformation) class introduced in the Windows App SDK 1.2 is missing all functionality related to DPI that was available in the [UWP version](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation).

Specifically, the following APIs are missing:
- `DpiChanged` event
- `LogicalDpi` property
- `RawDpiX` property
- `RawDpiY` property

The missing properties could be compensated by using the approach outlined in microsoft/microsoft-ui-xaml#4205. However, without the `DpiChanged` event is is unclear how a Windows App SDK app would react to DPI changes.

Will the `DisplayInformation` class be extended or do you consider that class to be complete?

### Steps to reproduce the bug

Use the `Microsoft.Graphics.Display.DisplayInformation` class in a Windows App SDK class and attempt to retrieve DPI information from it.

### Expected behavior

The same DPI related APIs as in the UWP version should be available. If that is not feasible please provide/document how DPI changes shall be handled by Windows App SDK apps.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

**Comment by jeffstall** [comment]
Thanks for the feedback. We'll look at how to improve this for the future. Closing this issue for now.

**Comment by BrunoBieri** [comment]
@jeffstall too bad you close this issue without answering the actual question!

> Will the `DisplayInformation` class be extended or do you consider that class to be complete?

**Comment by DarranRowe** [comment]
@BrunoBieri
There are two things to point out here.

First, with the "feature proposal" tag being added and the "We'll look at how to improve this for the future" statement, the answer should obviously be a "We don't know" statement.

Second, the answer to that is pretty much irrelevant anyway. There are two major reasons for this. Windows itself enabled access to the UWP version of this class for Windows 11 22H2 meaning that this functionality will become available to packaged and unpackaged desktop applications naturally over time via the UWP version of the class. Then the simple fact that the Windows App SDK doesn't have to design their classes in the exact same way as the UWP versions. This means that the DisplayInformation runtime class can end up being classed as complete and not touched in the future, but the DPI functionality is still added anyway.

**Comment by BrunoBieri** [comment]
@DarranRowe I see. Thank you for the clarifications.
