### ISSUE TITLE
CameraCaptureUI.CaptureFileAsync() returns null

### ISSUE THREAD

**Issue by LordBenjamin** [microsoft/WindowsAppSDK#3241]
### Describe the bug

See https://github.com/dotnet/maui/issues/5849.

The MAUI `MediaPicker.CapturePhotoAsync()` method returns `null` instantly on Windows. Expect to either see camera UI or an exception indicating a problem (e.g. lack of permissions, incorrect config, no camera available, etc).

Digging deeper, I am able to reproduce in a new, empty WinUI3 project:

```c#
var captureUi = new CameraCaptureUI();
var result = await captureUi.CaptureFileAsync(CameraCaptureUIMode.Photo);
// We get here straight away, result == null
...
```

Whereas the lower-level `MediaCapture` API works as expected:
```c#
var devices = await DeviceInformation.FindAllAsync(DeviceClass.VideoCapture);
DeviceInformation device = devices.FirstOrDefault(); // Finds one device, my webcam

MediaCaptureInitializationSettings settings = new MediaCaptureInitializationSettings();
settings.VideoDeviceId = device.Id;

MediaCapture mediaCapture = new MediaCapture();
await mediaCapture.InitializeAsync(settings);

StorageFolder storageFolder = ApplicationData.Current.LocalCacheFolder;
var result = await storageFolder.CreateFileAsync("test.jpg", CreationCollisionOption.ReplaceExisting);

await mediaCapture
    .CapturePhotoToStorageFileAsync(ImageEncodingProperties.CreateJpeg(), result)
    .AsTask();

// result is not null, JPEG file produced has a valid image inside
```

Captures a picture and displays the filename as expected.

So there doesn't seem to be a hardware / driver / OS / Windows SDK level issue. Seems to be `Windows.Media.Capture.CameraCaptureUI` that is misbehaving.

I created a `WinUI3` app (no MAUI) and the `CameraCaptureUI` code still returns `null`. I tried adding more permissions on top of `runFullTrust`:
```xml
  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <uap:Capability Name="videosLibrary"/>
    <uap:Capability Name="picturesLibrary"/>
    <DeviceCapability Name="webcam"/>
    <DeviceCapability Name="microphone"/>
  </Capabilities>
```
Which seems like all relevant capabilities.

### Steps to reproduce the bug

1. Create a new WinUI3 project using the Visual Studio template ("Blank App, Packaged (WinUI 3 in Desktop)
2. Change `myButton_Click()` in the generated `MainWindow.xaml.cs` to:
    ```c#
    private async void myButton_Click(object sender, RoutedEventArgs e)
    {
        var captureUi = new CameraCaptureUI();
        var result = await captureUi.CaptureFileAsync(CameraCaptureUIMode.Photo);

        myButton.Content = result == null ? "null result" : (result.DisplayName ?? "null DisplayName");
    }
    ```
3. Observe output
    - expect to see camera UI followed by the UI showing a filename
    - actually see the UI show `null result` instantly
4. Add `<DeviceCapability Name="webcam" />` to `Package.appxmanifest`
5. Repeat steps 1 - 3
6. Observe same behaviour

### Expected behavior

Expect to see camera UI, followed by the button caption showing a filename.

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H1): Build 19043

**Comment by evelynwu-msft** [comment]
Thanks for the pointer to https://github.com/microsoft/WindowsAppSDK/issues/1034 @kmgallahan. Marking this issue as duplicate.
