### ISSUE TITLE
C++/WinRT - unpackaged - Customized title bar controls not clickable & SetDragRectangle displays default titlebar

### ISSUE THREAD

**Issue by yki5000** [microsoft/WindowsAppSDK#3243]
### Describe the bug

Controls of customized titlebar are not clickable and only by setting "SetDragRectangle" the default titlebar appears and covers the customized titlebar.

As described in this post, the issue should be fixed in Windows App SDK 1.2 Preview 1 (at least in C#, in C++ it doesn't work).
I had 1.1.5 installed before.
https://github.com/microsoft/WindowsAppSDK/issues/2574

### Steps to reproduce the bug

Create an unpackaged WinUI 3 app.
Add the customized titlebar with controls and set "SetDragRectangle".

See my example (code in MainWindow.xaml.cpp):
https://github.com/yki5000/WinUI3_Unpackaged_CPP

See 2 example videos which show you the errors:
https://github.com/yki5000/WinUI3_Unpackaged_CPP/issues/1

### Expected behavior

Added titlebar controls should be usable by user input and SetDragRectangle shouldn't let the default titlebar appear (?!).

### NuGet package version

1.1.5

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
Just to be sure, have you tried doing this kind of thing without involving WinUI 3.

Don't forget, when you set a custom titlebar, this is set using Microsoft.UI.Xaml.Window, which is a different component to the AppWindowTitleBar used to remove the system title bar and set the drag regions.

It is possible that the AppWindowTitleBar is setting everything correctly, but the Xaml host is misbehaving.

**Comment by yki5000** [comment]
@DarranRowe 
I think I only partially understand what you're getting at. You mean it's maybe more a WinUI 3 issue and I should create an issue at the official Microsoft-UI-Xaml Repository?

I posted it originally in the MSDN forum and Castorix gave me the advice to post it in WindowsAppRepository, I'm a beginner in C++:
https://learn.microsoft.com/en-us/answers/questions/1104852/winui-3-controls-in-the-title-bar-are-not-clickabl.html

**Comment by bpulliam** [comment]
I would first try to add the compatibility section to your app.manifest., similar to https://github.com/microsoft/WindowsAppSDK/pull/2969
This is needed in both packaged and unpackaged apps, to allow the drag window to be created correctly.

**Comment by castorix** [comment]
> I would first try to add the compatibility section to your app.manifest., similar to #2969 This is needed in both packaged and unpackaged apps, to allow the drag window to be created correctly.

He aded it in [app.manifest](https://github.com/yki5000/WinUI3_Unpackaged_CPP/blob/master/app.manifest)

**Comment by yki5000** [comment]
@DarranRowe 
Indeed, testing it in WinApi (?!) would be too expensive since I’m not that experienced. 
(Oh man, WinUI 3 is an incredibly fantastic idea, especially for C++ but it also really get you down. 🫣)

**Comment by castorix** [comment]
> @DarranRowe Indeed, testing it in WinApi (?!) would be too expensive since I’m not that experienced. (Oh man, WinUI 3 is an incredibly fantastic idea, especially for C++ but it also really get you down. 🫣)

With Win32 APIs, it is done like in the MSDN sample  [Custom Window Frame Using DWM](https://learn.microsoft.com/en-us/windows/win32/dwm/customframe)
It works fine in C++/Win32 or C#/VB + P/Invoke, but I had tried to mix _DwmExtendFrameIntoClientArea_ and so on with WinUI 3 and I could not get correct results (with Windows App SDK 1.1.0) (I met problems with the child Composition window (_DesktopChildSiteBridge_ class))

**Comment by DarranRowe** [comment]
@castorix 
No, the titlebar customisation works with regular desktop applications. You can get an AppWindow associated with a HWND, the method of using Microsoft.UI.GetWindowIdFromWindow to get the window id, and then obtaining the AppWindow using Microsoft.UI.Windowing.AppWindow.GetFromWindowId is supported.
For Windows 11, and IIRC Windows 10 with 1.2, you can then use AppWindowTitleBar.ExtendsContentIntoTitleBar to enable full titlebar customisation.
You can't set Xaml elements as the titlebar, so you need to use some other means to do this, but that was the whole point. Having the drag rectangles set in such a way that the clicks can go through to the underlying window without Xaml being enabled.

**Comment by yki5000** [comment]
OK,
If I understand it correctly, this is the wrong place and it should be posted on the WinUI 3 page?!
(You don't know of a workaround?)

**Comment by yki5000** [comment]
There is also a bug that if you place a combo box under the title bar (anywhere) and then the dropdown list opens and juts out over the title bar, the part of the combo box item that sits over the title bar is no longer clickable . Is everything connected?!

**Comment by pratikone** [comment]
WinUI 3 and Appwindow titlebar now use the same implementation now and hence support the same features. The interactive titlebar can be created using InputNonClientPointerSource apis. I recently added an example in WinUI gallery on how to do it. You can follow it : https://github.com/microsoft/WinUI-Gallery/pull/1360 . It will work for both packaged and unpackaged. 

Do open a new issue if you still face some issue. Given this issue is fixed, I am closing this.
