### ISSUE TITLE
Unit Test does not work for Windows App SDK 1.2

### ISSUE THREAD

**Issue by ritt-app** [microsoft/WindowsAppSDK#3245]
### Describe the bug

Tried to add a Unit Test project to an existing WinAppSDK project, following the steps in this [blog](https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/). Could not build the Unit Test project.

### Steps to reproduce the bug

1. Create a new Blank App, Packaged (WinUI 3 in Desktop) called **App1**.
2. Follow steps in [blog](https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/) with the latest MSTest (v3.0.0) and Microsoft.TestPlatform.TestHost (v17.4.0) packages. Created new project called **App1.Test**.
3. Tried building and running test in **App1.Test**. It works!
4. Add Project Reference of **App1** to **App1.Test**. 
5. Tried to build **App1.Test**.  Failed with the following errors:

```
Error		PRI175: 0x80073b0f - Processing Resources failed with error: Duplicate Entry.	App1.Test	C:\VS\WinAppSDKUnitTest\App1\App1.Test\WINAPPSDKGENERATEPROJECTPRIFILE	1	
Error		PRI277: 0x80073b0f - Conflicting values for resource 'Files/MainWindow.xbf'	App1.Test	C:\VS\WinAppSDKUnitTest\App1\App1.Test\WINAPPSDKGENERATEPROJECTPRIFILE	1	
```

### Expected behavior

Test project should build and run without problems.

### Screenshots

See sample project attached: [WinAppSDKUnitTest.zip](https://github.com/microsoft/WindowsAppSDK/files/10227820/WinAppSDKUnitTest.zip)

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by vash72** [comment]
@ritt-app  in the linked blog post they are not adding a project for the tests but running them in place (i think cause of msix)
i tried and its seems to be working fine, i'm not sure about the side effect of having tests inside the "wasdk" project

**Comment by haonanttt** [comment]
Closing this issue as we already have documentation for testing. @ritt-app, please refer to the following links if necessary:
- https://learn.microsoft.com/en-us/windows/apps/winui/winui3/testing/
- https://learn.microsoft.com/en-us/windows/apps/winui/winui3/testing/create-winui-unit-test-project
Thank you!
