### ISSUE TITLE
Microsoft.Windows.SDK.BuildTools is missing buildTransitive

### ISSUE THREAD

**Issue by mattleibow** [microsoft/WindowsAppSDK#3251]
### Describe the bug

When including Microsoft.Windows.SDK.BuildTools transitively - for example you have a reference to the WASDK - it does not bring in the Microsoft.Windows.SDK.BuildTools targets. This is because the NuGet only has a `build` folder and is missing the `buildTransitive` folder.

This is why the package needs to be explicitly referenced in the WASDK templates:

https://github.com/microsoft/WindowsAppSDK/blob/4272e389baa0184a7232b2414a0ffc39ff2f10e5/dev/VSIX/ProjectTemplates/Desktop/CSharp/ClassLibrary/ProjectTemplate.csproj#L12

### Steps to reproduce the bug

1. File | New | WinUI app
2. File | New | WinUI library
3. Add a reference from the app to the librry
4. Remove the package reference to `Microsoft.Windows.SDK.BuildTools` AND `Microspft.WindowsAppSDK` from the app project
5. `dotnet build`
6. Observe the build fails if you do not have VS installed :)

[App19.zip](https://github.com/microsoft/WindowsAppSDK/files/10854295/App19.zip)

### NuGet package version

None

**Comment by evelynwu-msft** [comment]
@mikebattista @sotteson1 Is there a reason the `Microsoft.Windows.SDK.BuildTools` Nuget package doesn't implement `buildTransitive`? This is probably the only reason we have to hard-code it into the project templates (which can then cause problems on upgrade if WinAppSDK bumps up its own dependency).

**Comment by mattleibow** [comment]
Any chance this making it into a 1.2 servicing or 1.3? This will really help simplify the maui bits so that we don't have to depend on an explicit version for all projects.

**Comment by mikebattista** [comment]
@benkuhn @manodasanW @bpulliam is this just a matter of copying the content over to the buildTransitive folder?

**Comment by Scottj1s** [comment]
@mikebattista Yes, cloning 'build' to 'buildTransitive' is the simplest implementation and is the pattern we've used in WindowsAppSDK.

**Comment by chenss3** [comment]
The fix is in the SDK - BuildTools now has a buildTransitive folder, and it resolves the repro scenario @mattleibow described.

**Comment by mattleibow** [comment]
Amazing work! Gonna clean up some things for us in a big way and make other things easier to maintain.

**Comment by mattleibow** [comment]
Seems to be working!!! https://github.com/dotnet/maui/pull/13687

**Comment by Scottj1s** [comment]
Published as of: https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools/10.0.25309-preview
