### ISSUE TITLE
.targets file adds MRT Core binaries to `ReferenceCopyLocalPaths` but they are not present in Nuget package

### ISSUE THREAD

**Issue by mattleibow** [microsoft/WindowsAppSDK#3252]
### Describe the bug

The targets in the WASDK package refer to 2 files:
* Microsoft.Windows.ApplicationModel.Resources.dll
* MRM.dll

The `MrtCore.References.targets` targets file explicitly includes them, but they don't exist and we sometimes get an error:

> Error    MSB3030    Could not copy the file "C:\Users\mattl\.nuget\packages\microsoft.windowsappsdk\1.2.221109.1\buildTransitive\..\runtimes\win10-x64\native\Microsoft.Windows.ApplicationModel.Resources.dll" because it was not found.    
> Error    MSB3030    Could not copy the file "C:\Users\mattl\.nuget\packages\microsoft.windowsappsdk\1.2.221109.1\buildTransitive\..\runtimes\win10-x64\native\MRM.dll" because it was not found.

### Steps to reproduce the bug

Not sure, just was reading the targets

### NuGet package version

None

**Comment by LegendaryBlair** [comment]
Close this issue as no repro steps are available.
BTW, the mentioned DLLs, Microsoft.Windows.ApplicationModel.Resources.dll and MRM.dll, are distributed via WindowsAppRuntime packages.
