### ISSUE TITLE
Not all the dependencies are copied

### ISSUE THREAD

**Issue by mattleibow** [microsoft/WindowsAppSDK#3253]
### Describe the bug

When publishing an app, there are 4 msix dependencies that should get copied to the `Dependencies` folder:
* Microsoft.WindowsAppRuntime.1.2.msix
* Microsoft.WindowsAppRuntime.DDLM.1.2.msix
* Microsoft.WindowsAppRuntime.Main.1.2.msix
* Microsoft.WindowsAppRuntime.Singleton.1.2.msix

However, the `Microsoft.WindowsAppSDK.AppXReference.props` file only copies the 1:
* Microsoft.WindowsAppRuntime.1.2.msix

### Steps to reproduce the bug

1. Make an app
2. Publish the app from the CLI
3. Observe the msix are missing

### NuGet package version

None

### Additional context

This is my current workaround:

```xml
<Target Name="_BEFORE_GenerateAdditionalFrameworkSDKReference" BeforeTargets="_GenerateAdditionalFrameworkSDKReference">
	<ItemGroup>
		<_Current_AppxPackageRegistration Include="@(AppxPackageRegistration)" NewFilename="%(RootDir)%(Directory)$([System.String]::Copy('%(Filename)').Replace('Microsoft.WindowsAppRuntime.','Microsoft.WindowsAppRuntime.DDLM.'))%(Extension)" />
		<_Current_AppxPackageRegistration Include="@(AppxPackageRegistration)" NewFilename="%(RootDir)%(Directory)$([System.String]::Copy('%(Filename)').Replace('Microsoft.WindowsAppRuntime.','Microsoft.WindowsAppRuntime.Main.'))%(Extension)" />
		<_Current_AppxPackageRegistration Include="@(AppxPackageRegistration)" NewFilename="%(RootDir)%(Directory)$([System.String]::Copy('%(Filename)').Replace('Microsoft.WindowsAppRuntime.','Microsoft.WindowsAppRuntime.Singleton.'))%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<AppxPackageRegistration Include="@(_Current_AppxPackageRegistration -> '%(NewFilename)')" />
	</ItemGroup>
</Target>	
```

**Comment by Sweekriti91** [comment]
Related to this, if you apply the workaround, and then run the `install.ps1` script, it generates this error:

``` 
Found package: C:\code\AppName\appxtestAppName_1.0.0.0_Test\AppName_1.0.0.0_x64.msix
Installing app...                                                                                                       
Found dependency package(s):
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x86\Microsoft.WindowsAppRuntime.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x86\Microsoft.WindowsAppRuntime.DDLM.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x86\Microsoft.WindowsAppRuntime.Main.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x86\Microsoft.WindowsAppRuntime.Singleton.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x64\Microsoft.WindowsAppRuntime.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x64\Microsoft.WindowsAppRuntime.DDLM.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x64\Microsoft.WindowsAppRuntime.Main.1.2.msix
C:\code\AppName\appxtestAppName_1.0.0.0_Test\Dependencies\x64\Microsoft.WindowsAppRuntime.Singleton.1.2.msix
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict
validation.

Windows cannot install package 0A8834C6-F23D-4CEB-86B5-B57FD5D15D23_1.0.0.0_x64__9zz4h110yvjzm because this package
depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.DDLM.1.2" published
by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor
architecture and minimum version 2000.677.1750.0, along with this package to install.

NOTE: For additional information, look for [ActivityId] 5bfeccf6-0fe5-0001-8ef5-2d5ce50fd901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 5bfeccf6-0fe5-0001-8ef5-2d5ce50fd901

At C:\code\AppName\appxtestAppName_1.0.0.0_Test\Add-AppDevPackage.ps1:487 char:13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\code\fid-nxt....0.0.0_x64.msix:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

Error: Could not install the app.
Press Enter to continue...:
```

**Comment by mattleibow** [comment]
There is an issue where this caused an additional dependency: https://github.com/microsoft/WindowsAppSDK/issues/3316

But this may be desired, so maybe if that is true we copy the deps too?

**Comment by DrusTheAxe** [comment]
>Provide the framework "Microsoft.WindowsAppRuntime.DDLM.1.2" 

The DDLM packages are main packages, not frameworks. MSIX `appxmanifest.xml` has no way to express a dependency on a main package as you can on a framework (via `<PackageDependency>`) so I suspect Install.ps1's logic isn't sufficiently savvy to handle it.

Install.ps1 is a trivial wrapper over Add-AppDevPackage.ps1 which handles package registration via Add-AppxPackage (line 522?). If I'm reading this right it's assuming all packages in the Dependencies directory are just that, dependencies (line 483) and thus ultimately passes them all to `Add-AppxPackage` via the `-DependencyPath` parameter.

As `Add-AppxPackage` is just a glorified wrapper over `Windows.Management.Deployment.PackageManager.AddPackageAsync()` the Deployment stack is being told "here's a bunch of dependencies if you need" but some of those dependencies passed in a Main packages, not Framework packages, and PackageManager errors on the bad input.

That's my hunch. If you look at the `Microsoft-Windows-AppXDeploymentServer/Operational` channel (in EventViewer under `Applications and Services Logs` / `Microsoft` / `Windows` / `AppXDeployment-Server`) I suspect you'll see this error.

To workaround this you'd need to hack add-appxpackage.ps1 e.g.

1. Stick the DDLM+Main+Singleton packages in a not-Dependencies directory 
2. Change Add-AppDevPacakge.ps1 to process these
  a. Do what `InstallPackageWithDependencies` does but for `Join-Path $scriptDir "NotDependencies"` (or wherever)
  b. Ditto for their certs (handled in LaunchElevated?)
  c. Install the MSIX packages' licenses

Alternatively, you could copy `WindowsAppRuntimeInstaller.exe` into the `Dependencies` directory and run that before `InstallPackageWithDependencies` is called.
