### ISSUE TITLE
LocalSettings throws UnauthorizedAccessException after Restart

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/WindowsAppSDK#3254]
### Describe the bug

This one  #3244 seems to be a bug even though for some reason I posted it under Discussions. 

### Steps to reproduce the bug

See #3244

### Expected behavior

Should not cause an access exception after restart.

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022, Other

### Additional context

Comment, LocalSettings is IDisposable in Windows 11 but not in Windows 10.

**Comment by DrusTheAxe** [comment]
LocalSettings as in `ApplicationData.LocalSettings`?

Per [#3244](https://github.com/microsoft/WindowsAppSDK/discussions/3244) you're a C# app. Which version of .NET are you using, 6.0 or 7.0?

**Comment by sjb-sjb** [comment]
Yes, I obtain it from ApplicationData.LocalSettings on the Current object like this:

        private ApplicationDataContainer LocalSettings => this._localSettings ??= ApplicationData.Current.LocalSettings;
        private ApplicationDataContainer? _localSettings;

I am using Microsoft.WindowsAppSDK 1.2.220902.1-preview1, and in my project I am using TargetFramework net6.0-windows10.0.19041.0

**Comment by MuyuanMS** [comment]
I tried it out but failed to repro the issue on both Win10 and Win11 now. Given the issue has been here for almost 2 years I will close it for now, unless issue still exists on lastest Windows App SDK
