### ISSUE TITLE
Simultaneous Mouse and multi-touch input Crash (CppWinRT) 

### ISSUE THREAD

**Issue by techjogger** [microsoft/WindowsAppSDK#3257]
### Describe the bug

Simultaneous Mouse and multi-touch input causes an ...... Unhandled exception at 0x00007FF8408A26DB (Microsoft.InputStateManager.dll) in ***.exe: Fatal program exit requested.

### Steps to reproduce the bug

Run a Windows App SDK 1.2.2 App 
Simultaneously use the Mouse and two figures .
App crashes...

### Expected behavior

App does not crash!!!

### Screenshots

![crash](https://user-images.githubusercontent.com/13125455/208112810-630be2f1-25e3-4099-8e04-c9266e7681b0.png)

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by techjogger** [comment]
Any updates on a fix to this crash? Again, this will crash all Apps built with the WASDK.

**Comment by techjogger** [comment]
This crash is still present in WASDK 1.4 preview. Please fix!!

**Comment by dmitry-egorov** [comment]
I'm experiencing the same crash, when using pen and touch input at the same time. Using Microsoft.WindowsAppSDK 1.3.230602002.

**Comment by dmitry-egorov** [comment]
Just to provide some more context, here's what the app is writing to the debug output just before the crash:

> 14:55:11:372	onecoreuap\windows\moderncore\inputv2\systeminputhosts\lifted\lib\inprocinputhandler.cpp(653)\Microsoft.InputStateManager.dll!00007FF88347378D: (caller: 00007FF883475018) LogHr(1) tid(1820) 8007029C An assertion failure has occurred.
> 14:55:11:372	onecoreuap\windows\moderncore\inputv2\systeminputhosts\lifted\lib\inprocinputhandler.cpp(653)\Microsoft.InputStateManager.dll!00007FF88347378D: (caller: 00007FF883475018) FailFast(1) tid(1820) 8007029C An assertion failure has occurred.
> 14:55:11:981	Unhandled exception at 0x00007FF88347378D (Microsoft.InputStateManager.dll) in ***.exe: Fatal program exit requested. 

And here's the callstack:

> KernelBase.dll!RaiseFailFastException()
> Microsoft.InputStateManager.dll!wil::details::WilDynamicLoadRaiseFailFastException(struct _EXCEPTION_RECORD *,struct _CONTEXT *,unsigned long)
> Microsoft.InputStateManager.dll!wil::details::WilRaiseFailFastException(struct _EXCEPTION_RECORD *,struct _CONTEXT *,unsigned long)
> Microsoft.InputStateManager.dll!wil::details::WilFailFast(struct wil::FailureInfo const &)
> Microsoft.InputStateManager.dll!wil::details::ReportFailure_NoReturn<3>(void *,unsigned int,char const *,char const *,char const *,void *,struct wil::details::ResultStatus const &,unsigned short const *,enum wil::details::ReportFailureOptions)
> Microsoft.InputStateManager.dll!wil::details::ReportFailure_Base<3,0>(void *,unsigned int,char const *,char const *,char const *,void *,struct wil::details::ResultStatus const &,unsigned short const *,enum wil::details::ReportFailureOptions)
> Microsoft.InputStateManager.dll!wil::details::ReportFailure_GetLastError<3>(void *,unsigned int,char const *,char const *,char const *,void *)
> Microsoft.InputStateManager.dll!wil::details::in1diag3::_FailFast_GetLastError(void *,unsigned int,char const *)
> Microsoft.InputStateManager.dll!InProcInputHandler::PopulateContactInFrame(unsigned int,unsigned int,class std::vector<struct LiftedPointerData,class std::allocator<struct LiftedPointerData> > &)
> Microsoft.InputStateManager.dll!InputSinkInfrastructure::WindowProcedureCallback(struct HWND__ *,unsigned int,unsigned __int64,__int64)
> Microsoft.InputStateManager.dll!MessageOnlyWindow::WindowProcedure(struct HWND__ *,unsigned int,unsigned __int64,__int64)
> user32.dll!UserCallWinProcCheckWow()
> user32.dll!DispatchMessageWorker()
> dwmcorei.dll!CLocalMit::Run()
> kernel32.dll!BaseThreadInitThunk()
> ntdll.dll!RtlUserThreadStart()

This crash is really critical for our app, since it's core functionality involves simultanious use of pen and touch. It would be great to at least get a workaround for this issue. Nothing we can do on our side, since it's a fatal crash happening in the internals of the sdk.

**Comment by codendone** [comment]
Closing as dup of microsoft/microsoft-ui-xaml#8022.

Note that it seems there is a similar issue with pen and multi-touch: microsoft/microsoft-ui-xaml#8813

**Comment by stevenbrix** [comment]
Hey @codendone, #8022 is closed as a dupe of this one. Is that intentional?

**Comment by codendone** [comment]
@stevenbrix I corrected the duplicate id in microsoft/microsoft-ui-xaml#8022 to microsoft/microsoft-ui-xaml#7622. That bug is fixed in 1.4.

The **pen** plus multi-touch issue mentioned above, microsoft/microsoft-ui-xaml#8813, is still active and not fixed.

**Comment by 845541307** [comment]
<img width="2586" height="288" alt="Image" src="https://github.com/user-attachments/assets/01ca17db-7d6e-46bd-9aeb-26ef7ed001c9" />

<img width="2724" height="552" alt="Image" src="https://github.com/user-attachments/assets/e8d5f02c-9e8e-4216-9548-dac7d61e8f4f" />

The pen and hand touch on the drawing board caused the SDK to crash internally. No events were registered, only the input type was set to pen. Can you please help investigate what this is? I can provide a demo

**Comment by codendone** [comment]
It looks like microsoft/microsoft-ui-xaml#10802 was logged to track that pen+touch crash.
