### ISSUE TITLE
System.ArgumentException when OverlappedPresenter.IsModal is set to "true"

### ISSUE THREAD

**Issue by eduardobragaxz** [microsoft/WindowsAppSDK#3258]
### Describe the bug

When creating an OverlappedPresenet object and then setting the IsModal property to "true" the app breaks and throws the ArgumentException. I've tried setting the presenter of the AppWindow both before and after setting IsModal, but none work. It's interesting the exception is thrown on the appWindow.SetPresenter() if I call it after setting IsModal to "true". Don't know if it means anything.

### Steps to reproduce the bug

1. Create a WinUI3, Packaged app;
2. Add a new window to the project;
3. Set a button on MainWindow to open the new window;
4. On the new window get the handle for the AppWindow object;
5. Create an OverlappedPresenter, then set it's IsModal property to "true";
6. Then appWindow.SetPresenter(overlappedPresenter);
7. Run the app and try to open the new window.

You can try and reverse the order of 5 and 6.

### Expected behavior

The new window should open as a modal window.

### Screenshots

MainWindow.xaml
![MainWindowXAML](https://user-images.githubusercontent.com/50815710/208112907-07e7da1d-a8fb-4d8a-851a-2139cd66e154.png)

MainWindow.xaml.cs
![MainWindowCS](https://user-images.githubusercontent.com/50815710/208113007-e8d74867-e263-485a-8b33-23ab48c3032a.png)

BlankWindow1.xaml
![BlankWindow1XAML](https://user-images.githubusercontent.com/50815710/208113103-69fb8b9b-ed5e-464b-8917-66e915f87d72.png)

BlankWindow1.xaml.cs
![BlankWindow1CS](https://user-images.githubusercontent.com/50815710/208113167-600c8bc2-8570-4ce5-b4f0-aa0140e8991f.png)

The same exception on the same line:

![Captura de tela_20221216_104209](https://user-images.githubusercontent.com/50815710/208113571-dd9d88bc-4f09-4a23-94eb-28cefc27181b.png)
![Captura de tela_20221216_103922](https://user-images.githubusercontent.com/50815710/208113575-cdffb6d2-c0b0-4952-9682-86557e21ee0d.png)

### NuGet package version

Windows App SDK 1.2.1: 1.2.221116.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

The Windows App SDK version is 1.2.221209.1.

**Comment by eduardobragaxz** [comment]
I was searching about it and I guess it’s not a bug, it’s just not supported? I’m a little confused.

**Comment by wbokkers** [comment]
Setting IsModal only works when the Window has an owner window.
To add an owner after the window has been created, you can use:

```
    // HACK to set the OWNER of the window,
    // (needed for IsModal = true, otherwise it will crash!)
    Interop.SetWindowLongPtr(_hWnd, Interop.GWLP_HWNDPARENT, hWndOwner);
```
In the static Interop class, I have:
```
    public static IntPtr SetWindowLongPtr(IntPtr hWnd, int nIndex, IntPtr dwNewLong)
    {
        if (IntPtr.Size == 8)
            return SetWindowLongPtr64(hWnd, nIndex, dwNewLong);
        else
            return new IntPtr(SetWindowLong32(hWnd, nIndex, dwNewLong.ToInt32()));
    }

    [DllImport("user32.dll", EntryPoint = "SetWindowLong")]
    private static extern int SetWindowLong32(IntPtr hWnd, int nIndex, int dwNewLong);

    [DllImport("user32.dll", EntryPoint = "SetWindowLongPtr")]
    private static extern IntPtr SetWindowLongPtr64(IntPtr hWnd, int nIndex, IntPtr dwNewLong);
```

You may need the EnableWindow() win32 API to enable/disable the owner window when a modal window is shown

**Comment by wbokkers** [comment]
I think Microsoft should add a simple API for creating modal windows, also blocking the UI of the main window. Using EnableWindow, IsModal, and SetWindowLong is too error prone.

**Comment by wbokkers** [comment]
There are API's to create a window from an existing win32 window. If the win32 window already has a owner window, I guess the owner is already set. But as far as I know there is no way to create a Window from within WinUI with the owner set. This is a huge omission in the windowing API.

**Comment by eduardobragaxz** [comment]
Thank you :)
