### ISSUE TITLE
can't change the Timer Resolution for my App

### ISSUE THREAD

**Issue by mann1x** [microsoft/WindowsAppSDK#3263]
### Describe the bug

Sorry if this is not the right place to raise this issue.

I can't change the Timer Resolution for my App; the `SetProcessInformation` for `PROCESS_POWER_THROTTLING_STATE` and ControlMask `PROCESS_POWER_THROTTLING_IGNORE_TIMER_RESOLUTION` fails with Error 87, always.
ControlMask `PROCESS_POWER_THROTTLING_EXECUTION_SPEED` seems to work properly and reset as well.

This prevents any change of the Timer Resolution with timeBeginPeriod.

### Steps to reproduce the bug

I use this C function exported to the managed code:

```cpp

extern "C"
{
	__declspec(dllexport) int __stdcall setPowerThrottlingIgnoreTimer(INT pid, bool enable) {
		{
			PROCESS_POWER_THROTTLING_STATE PowerThrottling;
			RtlZeroMemory(&PowerThrottling, sizeof(PowerThrottling));
			PowerThrottling.Version = PROCESS_POWER_THROTTLING_CURRENT_VERSION;
			BOOLEAN bpriv;

			int _ret = 0;
			HANDLE hToken = nullptr;
			HANDLE hProcess = nullptr;

			::OpenProcessToken(::GetCurrentProcess(), TOKEN_ALL_ACCESS, &hToken);

			if (!SetPrivilege(hToken, SE_DEBUG_NAME, TRUE))
				_ret = -1;
			if (RtlAdjustPrivilege(20L, TRUE, FALSE, &bpriv) != STATUS_SUCCESS)
				_ret = -2;

			if (_ret == 0) {
				hProcess = ::OpenProcess(PROCESS_SET_INFORMATION | PROCESS_QUERY_LIMITED_INFORMATION | SYNCHRONIZE, FALSE, pid);

				if (!hProcess) _ret = -3;
			}

			//
			// Always ignore or honor Timer Resolution Requests.
			// Turn IGNORE_TIMER_RESOLUTION throttling off or on. 
			// ControlMask selects the mechanism and StateMask declares which mechanism should be on or off (0).
			//

			if (hProcess != nullptr && _ret == 0) {
				PowerThrottling.ControlMask = PROCESS_POWER_THROTTLING_IGNORE_TIMER_RESOLUTION;
				PowerThrottling.StateMask = 0;
				if (enable) PowerThrottling.StateMask = PROCESS_POWER_THROTTLING_IGNORE_TIMER_RESOLUTION;

				if (SetProcessInformation(hProcess,
					ProcessPowerThrottling,
					&PowerThrottling,
					sizeof(PowerThrottling)) == 0) _ret = GetLastError();
			}

			::CloseHandle(hToken);
			::CloseHandle(hProcess);

			return _ret;
		}
	}
}

```

SetProcessInfomation returns != 0 and GerLastError() = 87, Timer Resolution doesn't change

### Expected behavior

Return 1 and able to change the timer resolution.

### NuGet package version

None

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2019

**Comment by mann1x** [comment]
Thanks for the feedback.
I know 87 is invalid parameters but the parameters seems correct to me.
Exactly the same call for PROCESS_POWER_THROTTLING_EXECUTION_SPEED works fine.
There was a bug in Windows 11 (now fixed), on PROCESS_POWER_THROTTLING_EXECUTION_SPEED returning 87 for no reason, that's why.

What is different in your code is the GetCurrentProcess(); from C# I've tried to call the function with p/invoke and passing the handle from process.GetCurrentProcess() with the same results.
I thought it could be a problem of token or OpenProcess identifier but whatever I tried it doesn't work and I don't see any reason why it shouldn't.

I will try a dummy c++ App to see if I it works with your code.

Thanks

**Comment by DarranRowe** [comment]
Yeah, I tested that on Windows 11 22H2 (22621.963).

**Comment by mann1x** [comment]
Yep, I have restore my Windows 11 install and it works.

This time it's not 11 but 10 impacted :)

Is this the right place to report this bug or is should I open the issue somewhere else?

**Comment by gabbybilka** [comment]
This issue is outside of the scope of WinAppSDK, please open an issue on Feedback Hub. Thanks!

**Comment by mann1x** [comment]
I really hope a good Samaritan from MS engineering will one day stumble on this bug and fix it.

Reporting these kind of bugs on Feedback Hub it's just useless, a complete waste of time.
Nothing reported there that doesn't get a huge number of upvotes will ever be even read by anyone in MS.
Otherwise the only hope is someone with a paid business support contract will finally understand why its application is not working as expected and report it.

Almost half a century passed and MS is still unable to handle bugs reporting in a meaningful way... pity.
