### ISSUE TITLE
ActualHeight did not fire the callback through RegisterPropertyChangedCallback

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/WindowsAppSDK#3284]
### Describe the bug

ActualHeight DependencyProperty did not fire the PropertyChangedCallback. But SizeChanged event fired as expected. This issue leads the OneWay/TwoWay Binding related to ActualHeight failed in XAML

```csharp
            //BasicLayout is a Grid
            BasicLayout.RegisterPropertyChangedCallback(ActualHeightProperty, (sender, args) =>
            {
                //This callback never fired. Therefore, binding ActualHeight in XAML is not work
                System.Diagnostics.Debug.WriteLine($"PropertyChanged callback: {BasicLayout.ActualHeight}");
            });
            BasicLayout.SizeChanged += (sender, args) =>
            {
                System.Diagnostics.Debug.WriteLine($"SizeChanged callback: {BasicLayout.ActualHeight}");
            };
```

### Steps to reproduce the bug

1. Create a Grid or other controls in XAML
2. Register the callback through RegisterPropertyChangedCallback and SizeChanged event
3. SizeChanged event fired as expected, but PropertyChangedCallback never fired

### Expected behavior

ActualHeight should fire the callback we passed through RegisterPropertyChangedCallback on property changed

### Screenshots

![image](https://user-images.githubusercontent.com/42038175/209778865-60a9e141-7728-4e2c-99c0-239f505513f3.png)

### NuGet package version

Windows App SDK: 1.2.221209.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Demo: 
[ActualHeightTest.zip](https://github.com/microsoft/WindowsAppSDK/files/10312955/ActualHeightTest.zip)

**Comment by kmgallahan** [comment]
> Although it has an [ActualHeightProperty](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.frameworkelement.actualheightproperty?view=windows-app-sdk-1.2#microsoft-ui-xaml-frameworkelement-actualheightproperty) backing field, ActualHeight does not raise property change notifications and it should be thought of as a regular CLR property and not a dependency property.

https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.frameworkelement.actualheight?view=windows-app-sdk-1.2#remarks

**Comment by zhuxb711** [comment]
Ok then. Just to mention that CommunityToolkit has an Attached Property for the ActualHeight which could be used for binding.
