### ISSUE TITLE
UWP apps should be able to record internal audio

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/WindowsAppSDK#331]
# Proposal: [UWP apps should be able to record internal audio] 

## Summary

Currently UWP apps are able just to capture external audio, no way to record internal one

## Rationale

* I develop a screen recording app and I get so many negative feedbacks because I cannot record internal audio. I think for a screen recording app that's a must. I cannot compete with Win32 alternatives while having this kind of limitations.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W|Must|

**Comment by Gavin-Williams** [comment]
Hangon ... UWP apps can't record audio output? ROFL. That's funny. Please fix.

**Comment by Jaiganeshkumaran** [comment]
@Gavin-Williams It can record audio input but not the output from other apps

**Comment by emiliano84** [comment]
I hit a similar major roadblock in my app too, I found this:
https://social.msdn.microsoft.com/Forums/en-US/bc4da08c-c6e9-4917-90f9-b7c74e11774c/uwpwhy-is-quotloopbackquot-recording-not-possible-in-uwp?forum=wpdevelop
but looks like WASAPI loopback doesn't work

P.S.
@Jaiganeshkumaran was exactly what @Gavin-Williams was complaining about

**Comment by BreeceW** [comment]
I would like my UWP app to be able to let users have the option of sharing system audio along with a screen share. Zoom, for example, can do this. It seems like this is not possible for UWP today.

**Comment by stevewri** [comment]
Would it meet your needs if WASAPI loopback was available through a capability (so that the user installing the app agrees to let it record other applications' output?) That would be more in line with other UWP APIs that can listen across app container boundaries.

**Comment by MarcAnt01** [comment]
Yes, that would definitely make sense

**Comment by Gavin-Williams** [comment]
@stevewri That sounds good, and in line with UWP's approach to allowing the user to sign-off on capabilities, which is an approach I've always quite liked about UWP.

**Comment by MarcAnt01** [comment]
I just hope that issue will be given very high priority, otherwise I might be forced to use Desktop Bridge for my UWP app, but I really want to avoid that.
