### ISSUE TITLE
Navigation controls are garbled in the case of using Chinese content！

### ISSUE THREAD

**Issue by Linjie123** [microsoft/WindowsAppSDK#3322]
### Describe the bug

<Grid>
        <Grid.RowDefinitions>
            <RowDefinition />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>

        <NavigationView x:Name="NvSample"
                        Grid.Row="0"
                        IsBackButtonVisible="Collapsed"
                        IsPaneVisible="True"
                        IsSettingsVisible="True"
                        ItemInvoked="NvSample_ItemInvoked"
                        Loaded="NvSample_Loaded"
                        PaneDisplayMode="Left"
                        SelectionFollowsFocus="Enabled">
            <NavigationView.MenuItems>
                <NavigationViewItem x:Name="Home"
                                    Content="主页"
                                    Icon="Home" />
                <NavigationViewItem Content="学员管理"
                                    Icon="List"
                                    IsExpanded="True"
                                    SelectsOnInvoked="False">
                    <NavigationViewItem.MenuItems>
                        <NavigationViewItem x:Name="Studentmessage"
                                            Content="学员信息"
                                            Icon="Message" />
                        <NavigationViewItem x:Name="Upload"
                                            Content="批量导入"
                                            Icon="Upload" />
                    </NavigationViewItem.MenuItems>
                </NavigationViewItem>
                <NavigationViewItem Content="考勤管理"
                                    Icon="Switch"
                                    IsExpanded="True"
                                    SelectsOnInvoked="False">
                    <NavigationViewItem.MenuItems>
                        <NavigationViewItem x:Name="Attend"
                                            Content="考勤打卡"
                                            Icon="Document" />
                        <NavigationViewItem x:Name="Attendquery"
                                            Content="考勤查询"
                                            Icon="Document" />
                    </NavigationViewItem.MenuItems>
                </NavigationViewItem>
                <NavigationViewItem Content="成绩管理"
                                    Icon="Home"
                                    IsExpanded="True"
                                    SelectsOnInvoked="False">
                    <NavigationViewItem.MenuItems>
                        <NavigationViewItem x:Name="ScoreManage"
                                            Content="成绩管理"
                                            Icon="Sort" />
                        <NavigationViewItem x:Name="Scorequery"
                                            Content="成绩查询"
                                            Icon="Filter" />
                    </NavigationViewItem.MenuItems>
                </NavigationViewItem>
            </NavigationView.MenuItems>

            <Frame x:Name="ShellFrame">
                <Frame.ContentTransitions>
                    <TransitionCollection>
                        <NavigationThemeTransition />
                    </TransitionCollection>
                </Frame.ContentTransitions>
            </Frame>
        </NavigationView>

### Steps to reproduce the bug

none

### Screenshots

![image](https://user-images.githubusercontent.com/26216203/208049271-86554ca8-4706-4c84-96df-4321b1a085b0.png)

### NuGet package version

Windows App SDK ：1.2.221209.1
Windows App SDK ：1.2.221116.1
Windows App SDK ：1.2.221109.1
### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22623, 2022 Update)

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment]
You can ave the xaml file as Utf-8 to fix the problem.  I have also changed the templates to be Utf-8 to avoid this in the future.
