### ISSUE TITLE
Every new page is unable to load characters from other languages.

### ISSUE THREAD

**Issue by davidsi02** [microsoft/WindowsAppSDK#3323]
### Describe the bug

For the past few days, every time I create a new page, characters from the Portuguese language (such as é, ã, ç, ì) are displayed as the "unknown character" glyph. This issue does not occur with old pages or when I duplicate an older page.

### Steps to reproduce the bug

1. Add new page.
2. Insert a textblock using one of the following characters: é, ã, ç, ì.
3. Execute and check results.

### Screenshots

![imagem](https://user-images.githubusercontent.com/49164276/209538737-17c59661-1256-4e48-b5ff-4c5bd7df0377.png)
![imagem](https://user-images.githubusercontent.com/49164276/209538817-e7f63efa-7731-4c33-ba0e-3cbb1ceab800.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by bpulliam** [comment]
As @yki5000 mentioned, you can save the xaml file as Utf-8, but I've also changed the templates to be Utf-8 from the start.
