### ISSUE TITLE
C# Template Fix: File scoped namespaces

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WindowsAppSDK#3329]
### Describe the bug

C# 10 introduced file scoped namespaces: https://learn.microsoft.com/dotnet/csharp/language-reference/keywords/namespace

Since the Windows App SDK now targets .NET 6 (which has C# 10 as a default), the templates should be updated to use this new pattern and save a level of indentation in the file.

Follow-on request, related to template clean-up #3324; FYI @bpulliam 

### Steps to reproduce the bug

Create a new C# project

### Expected behavior

```cs
namespace MyNamespace;

/// <summary>
/// An empty window that can be used on its own or navigated to within a Frame.
/// </summary>
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }
```

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### IDE

Visual Studio 2022

**Comment by haonanttt** [comment]
Close this issue as the PR had been merged

**Comment by michael-hawker** [comment]
@haonanttt quick question, will this be tied to a VS version or just go out once 1.7 ships?

**Comment by haonanttt** [comment]
@michael-hawker template fixes will go with VS update
