### ISSUE TITLE
Cannot reference WindowsAppSdk and a WPF library in the same project: There was no runtime pack available for win10-arm

### ISSUE THREAD

**Issue by JaykeBird** [microsoft/WindowsAppSDK#3336]
### Describe the bug

I'm trying to build a class library that references both another class library (with `useWPF` set to true), and [Microsoft.WindowsAppSdk](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1). The combination of these two references in this one project seems to be incompatible, as I immediately start seeing these errors, and so far, nothing I've tried has resolved it.

```
There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win10-arm'.		C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448
There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win10-arm-aot'.		C:\Program Files\dotnet\sdk\7.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets	448	
```

Even after making sure I have the latest .NET SDKs and Visual Studio 2022 updates, this occurs. I'm not specifically targeting ARM64 in any way; my build configuration is set to "Any CPU".

I originally posted a bug report about this to dotnet/sdk, as there was an earlier bug report there that had a similar error message, but after some thought, I figured this might be a slightly better place to post it.

### Steps to reproduce the bug

I created a minimum reproduction of the issue I'm facing here: https://github.com/JaykeBird/RuntimePackErrorRepro

To create this on your own:
1. In a new solution, create a WPF class library.
2. In this library's csproj file, reference multiple .NET runtimes in the `<TargetFrameworks>`, such as `net6.0-windows;net7.0-windows`. I don't think referencing multiple runtimes is actually necessary, but I've done it as it reflects my larger library where I first encountered my issue. Also make sure the line `<UseWPF>true</UseWPF>` is present.
3. In this same solution, create another WPF class library.
4. In this second library's csproj file, set the `<TargetFramework>` to `net6.0-windows10.0.19041.0`.
5. Also with this second library, add a project reference to the first library and also add [Microsoft.WindowsAppSdk](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1).
6. Try building the second project.

### Expected behavior

I expect the library to build without this error occurring.

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

- Using Visual Studio 2022 17.4.4 (I also have Visual Studio 2019 installed, but I'm not using it in this scenario)
- Output of `dotnet --info` (I know there's a lot of runtimes, I can't seem to figure out how to remove the older ones):
```
C:\Users\jacob>dotnet --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by gabbybilka** [comment]
WinAppSDK does not support Arm32 like WPF. Marking as documentation so we can add this limitation to our docs.

We recommend editing your VS proj to not include Arm32:
`<Platforms>x86;x64;ARM64</Platforms>`

**Comment by JaykeBird** [comment]
I've been building for AnyCPU thus far, so I'll try the platforms line and will report back.

A more actionable error message or some way to detect this issue would be nice, but I'm suspecting there's some form of limitation that makes that not possible.

**Comment by JaykeBird** [comment]
Okay. I actually wasn't aware that WPF supported Arm32. I've been building for AnyCPU thus far, so I'll put in that platforms line and report back.

**Comment by JaykeBird** [comment]
I added that Platforms line to both the base WPF project and the referencing project (in my repro project https://github.com/JaykeBird/RuntimePackErrorRepro ), I still get the same result.

**Comment by JaykeBird** [comment]
I'm open to admitting there might be something on my computer that needs to be reset/reinstalled/cleaned out, but I've made sure I'm on the latest stable version available of .NET 7, Visual Studio 2022, and Windows. Trying to clean the solution (either via Visual Studio or dotnet cli) fails with the same error, and deleting the .vs folder in the solution doesn't make a difference.

**Comment by JaykeBird** [comment]
Okay, I've figured it out!

It's not the Platforms line that was needed. Instead, it was the RuntimeIdentifiers line.

`<RuntimeIdentifiers>win10-x64;win10-x86;win10-arm64</RuntimeIdentifiers>`
