### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by Alzhunter** [microsoft/WindowsAppSDK#3340]
### Describe the bug

Unable to scroll in an app using the windowsAppSDK

### Steps to reproduce the bug

Windows 11 Pro, 22H2, Windows Feature Experience Pack 1000.22638.1000.0, Version: 2.4.21.0
OS Version: 10.0.22621.1105

Unable to scroll at all in the files app

### Expected behavior

one should be able to scroll in the app

### NuGet package version

None

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Other

**Comment by gabbybilka** [comment]
Not enough information is provided to begin investigating. This could be an issue with WinAppSDK or the Files app. Is there a repro from Files?

**Comment by Josh-65** [comment]
The repository is here https://github.com/files-community/Files

**Comment by Josh-65** [comment]
I believe it related to this #2791
