### ISSUE TITLE
App is not started from notifications

### ISSUE THREAD

**Issue by asierpn** [microsoft/WindowsAppSDK#3342]
### Describe the bug

Tapping an app notification does not start the aplication if it is not running as tapping an application URI does.

### Steps to reproduce the bug

1. Configure the app to use app notifications as it is explained [here](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/toast-notifications?tabs=appsdk)
2. Create an app notification using AppNotificationBuilder
3. Tap the notification when the app is not running

### Expected behavior

The app should be started from the notification.

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by pmpurifoy** [comment]
Hi! I have a few clarifying questions.

- Does the NotificationInvoked handler trigger if the notification was activated while the app is open? 

- Does your appxmanifest has a ComServer defined with the exe and windows.toastActivationExtension that both use the same GUID?

- Do you have logic like the sample that conditionally brings up the window based on the activation? Are you calling AppNotificationManager.Register on activation as well (the app won’t receive the activation without this step)?

**Comment by asierpn** [comment]
> Does the NotificationInvoked handler trigger if the notification was activated while the app is open?

Yes, it works fine if the app is running

> Does your appxmanifest have a ComServer defined with the exe and windows.toastActivationExtension that both use the same GUID?

Yes, we have followed the instructions detailed at https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/toast-notifications?tabs=appsdk and both use the same custom created GUID

> Do you have logic like the sample that conditionally brings up the window based on the activation? Are you calling AppNotificationManager.Register on activation as well (the app won’t receive the activation without this step)?

Yes, all that logic is implemented, we call ShowWindow and SetForegroundWindow after activation ensuring it is executed in the UI thread using the DispatherQueue

To know if some method is called we are logging to a text file when each one is called (OnLaunched, NotificationInvoked) but none of them are logged when tapping the notification if the app is not running, if the app is running it works perfectly.

**Comment by pmpurifoy** [comment]
For the ComServer, how is your exe defined?

The example shows:
`<com:Extension Category="windows.comServer">

          <com:ComServer>
            <com:ExeServer Executable="YourProject.exe" Arguments="----AppNotificationActivated:" DisplayName="App notification activator">
              <com:Class Id="replaced-with-your-guid-C173E6ADF0C3" DisplayName="App notification activator"/>
            </com:ExeServer>
          </com:ComServer>
        </com:Extension>`

But for MSIX, the exe is in the app folder:
`<com:ExeServer Executable="YourProject\YourProject.exe"`

An example is here:
https://github.com/microsoft/WindowsAppSDK/blob/77761e244289fda6b3d5f14c7bded189fed4fb89/test/TestApps/PushNotificationsDemoPackage/Package.appxmanifest#L51

Another example is here (this is a push ComServer but same idea for path):
https://github.com/microsoft/WindowsAppSDK-Samples/blob/a8a835429f8d4a172187a347be9f7da8776d7298/Samples/Notifications/Push/cpp-console-packaged/cpp-console-package/Package.appxmanifest#L46

Make sure the manifest entry has the correct path. If this is the case, we should update our documentation to match the common MSIX scenario. @drewbatgit

**Comment by asierpn** [comment]
The ComServer was registered incorrectly, we did not specify the folder.

There is another thing that causes the application not to start tapping the notification, if you execute this code `var activatedArgs = Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs()` before registering the AppNotificationManager the application will not start.

**Comment by myfix16** [comment]
> The ComServer was registered incorrectly, we did not specify the folder.
> 
> There is another thing that causes the application not to start tapping the notification, if you execute this code `var activatedArgs = Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs()` before registering the AppNotificationManager the application will not start.

Strangely, In my application, the app launches normally after I click on the notification.
I am using `Windows App SDK 1.2.2: 1.2.221209.1` and `Windows 11 Beta 22623.1245`

**Comment by asierpn** [comment]
In our production application it works by correcting the ComServer registration with the path of the exe and calling `Microsoft.Windows.AppLifecycle.AppInstance.GetCurrent().GetActivatedEventArgs()` after registering the AppNotificationManager. Try this sample project ([App1.zip](https://github.com/microsoft/WindowsAppSDK/files/10536630/App1.zip)) and you will see that it doesn't work if you call GetActivatedEventArgs before registering the AppNotificationManager.

I'm using `Windows App SDK 1.2.2: 1.2.221209.1` and `Windows 10 19044.2486`

**Comment by pmpurifoy** [comment]
This is by design. You must register with the AppNotificationManger before calling GetActivatedEventArgs. Please check these activation steps to correctly receive AppNotfication activations in WinAppSDK: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/guides/toast-notifications?tabs=appsdk#step-3-handle-activation

**Comment by asierpn** [comment]
The documentation says to register for NotificationInvoked before calling Register(), but it says nothing about calling GetActivatedEventArgs() after registering, but in the example everything is called in the correct order, is weird having to do the calls in an exact order to make it work.

I'm closing this ticket, it now works in our app. Thank you very much.
