### ISSUE TITLE
Custom Title Bar Does not honor Windowing classes

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#3346]
### Describe the bug

Describe the bug
When a Windows App SDK WinUI 3 desktop app is using a custom title bar, in the case of using windowing classes, whatever you do with the presenter class, it will not be honored by WinUI.

As an example, trying to set IsMaximizable and IsMinimizable on an OverlappedWindowsPresenter class does nothing if the app is using a custom title bar.

Steps to reproduce the bug
Create a VS 2022 project using the Windows App SDK / WinUI 3 Desktop App template.
![image](https://user-images.githubusercontent.com/77593544/213140659-a2e33a02-038b-446b-b42a-75fdefecac6d.png)

On the MainWindow.xaml file, define your custom title bar element:
![image](https://user-images.githubusercontent.com/77593544/213140704-85a396e8-1c71-49c3-b9d9-246b0ea7de5f.png)

On the MainWindow.xaml.cs file, add the following inside the constructor method:
![image](https://user-images.githubusercontent.com/77593544/213140730-60b2a4a3-8a44-4137-8afa-006210fc0a20.png)

Run the project. A small window should appear. Notice that the Minimize and Maximize buttons are still present and displayed.

![image](https://user-images.githubusercontent.com/77593544/213140757-0e3f42d1-773e-4f42-89b6-ad611803cdc8.png)

### Steps to reproduce the bug

See bug description

### Expected behavior

The expected behavior is that when we use the IsMaximizable and IsMinimizable properties of the OverlappedWindowsPresenter class, the window should appear with only the Close button.On the example below, the ExtendsContentIntoTitleBar() and SetTitleBar() methods are commented out.
![image](https://user-images.githubusercontent.com/77593544/213141188-519a1ef9-1e40-434c-91b6-8cf7a2342cc3.png)

As you can see here, only the Close button is displayed.
![image](https://user-images.githubusercontent.com/77593544/213141116-e14cc1f3-95ae-4159-8856-3c92071eec72.png)

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
The problem here is that the Microsoft.UI.Windowing.AppWindowTitleBar's version of ExtendsContentIntoTitleBar should be the preferred option.

![Screenshot 2023-01-18 173046](https://user-images.githubusercontent.com/52577874/213252968-d6b99246-bea0-4040-8d2a-8cea262bdb2d.png)

This honours the window style properly and acts how you expect it to. But this should still have the annoying bug where it doesn't properly set the drag rectangles for the window when used in a Xaml application.

**Comment by gabbybilka** [comment]
This is an area we want to consolidate in a future release, thanks for filing.
