### ISSUE TITLE
System.Windows.Forms.OpenFileDialog Not working

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#3372]
### Describe the bug

Hi,

Just last week I can use the [OpenFileDialog class](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog?view=windowsdesktop-7.0) in a WASDK/WinUI3/C# desktop app.
But now, VS 2022 17.4.4 cannot even find the assembly via **using System.Windows.Forms;**

Here's a sample:

using Microsoft.UI.Xaml.Controls;
using System.Windows.Forms; // <-- This used to work just the other day

namespace MySampleNamespace
{
    public sealed partial class MySamplePage : Page
    {
        public MySamplePage()
        {
            this.InitializeComponent();
        }

        private void ImportFileButton_Click(object sender, Microsoft.UI.Xaml.RoutedEventArgs e)
        {
            using OpenFileDialog openFileDialog = new();
            openFileDialog.InitialDirectory = "";
            openFileDialog.Filter = "Comma-Separared Files (*.csv)|*.csv";
            openFileDialog.RestoreDirectory = true;
            openFileDialog.Title = "Select CSV File";
            if (openFileDialog.ShowDialog() == DialogResult.OK)
            {
				// Some code...
			}
		}
	}
}	

### Steps to reproduce the bug

1. Create a WinUI 3 C# project:
![image](https://user-images.githubusercontent.com/77593544/215111733-331008fa-d48c-432a-91eb-81b2e3ab6e4a.png)
2. Add a XAML blank page and use the OpenFileDialog similar to the one in the description.
3. Build the project, you should see an error:
![image](https://user-images.githubusercontent.com/77593544/215112276-4238c455-6746-46e4-b05e-42b2ce5cb0da.png)

### Expected behavior

Since the "Blank App, Packaged (WinUI 3 in Desktop)" VS 2022 project template uses C#, which is a .NET language, I should be able to use any namespace in the .NET 7 assembly or even in the .NET Windows Desktop 7 assembly.

### NuGet package version

Windows App SDK 1.2.2: 1.2.221209.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

I have these NuGet packages installed on my project:
![image](https://user-images.githubusercontent.com/77593544/215113005-24ded070-bd78-4b03-8c8c-0f541e113bd9.png)

**Comment by castorix** [comment]
You must add a Reference to the right version of the DLL
For example, on  my PC , I add a Reference to :

 "C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.13\System.Windows.Forms.dll"

And it works...
