### ISSUE TITLE
AppNotificationManager.Default.Setting in after upgrade to WindowsAppSDK 1.2 is always "Unsupported"

### ISSUE THREAD

**Issue by DarkNoir** [microsoft/WindowsAppSDK#3396]
App Notifications no longer work in SDK 1.2 or has there been a change that I cannot find any docs on? Rolling back to 1.1.5 corrects the issue. The templated and samples apps App Notifications all stop working also.

**Comment by pmpurifoy** [comment]
Does your app run as elevated? The only check happening is making sure the app isn't running as elevated.

**Comment by DarkNoir** [comment]
I am not specifically running it as elevated. Is there a way to verify that it is or isn't elevated?

**Comment by DarranRowe** [comment]
Task Manager.
If you go to the details page, right click on the list header and then choose Select Columns, you can find the Elevated column in there. If you enable this then Task Manager will tell you if a process is running elevated.

**Comment by DarkNoir** [comment]
Nice, thank you . That was much easier than all the other ways I was trying. All my issues are resolved
