### ISSUE TITLE
FilePicker: A device attached to the system is not functioning. (0x8007001F)Bug title

### ISSUE THREAD

**Issue by true-perfect-code** [microsoft/WindowsAppSDK#3422]
### Describe the bug

I wanted to easily select a file in my project and used FilePicker and the example from the MAUI documentation. The file selection dialogue opens and I can select a file, but when I click on Open, the following error is triggered:

**A device attached to the system is not functioning. (0x8007001F)**

I found out where the problem comes from, it was M.2 SSD. I took an SSD from another computer and connected it to SATA. Windows 10 pro is also installed on SSD, also Visual Studio and MAUI. So I could use exactly the same demo project. I was then able to select a text file via FilePicker and no error occurred

So I then bought a new SATA SSD and after a few hours I installed Windows and Visual Studio 2022 (MAUI, ASP.NET and WPF) on the new SSD.

Here is the summary:

- If SATA SSD is set as primary in BIOS, then it doesn't matter where the project/app is located in which you use FilePicker in MAUI (i.e. whether it's on SATA or M.2 drive).

- If M.2 SSD is set as primary, then the above error message "A device attached to the system is not functioning. (0x8007001F)" is generated when using the MAUI FilePicker function.

More informations on MAUI github: https://github.com/dotnet/maui/issues/13207

### Steps to reproduce the bug

- First get a PC that has M.2 SSD defined as boot drive 1
- Download my project from GitHub
- run it. and select file from dialog box
- In the Try Catch the error should be triggered after selecting a file from the file dialog.

GitHub: https://github.com/true-perfect-code/FilePickerError.git 

### NuGet package version

None

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Check please my post on https://github.com/dotnet/maui/issues/13207

**Comment by gabbybilka** [comment]
We recommend filing this via Feedback Hub so the File Picker owners can take a look with the correct telemetry. Thanks!

**Comment by true-perfect-code** [comment]
Can you please send me an appropriate link where I should report this? Thank you
