### ISSUE TITLE
WinAppSDK application crashes (KERNELBASE.dll) immediately when opened

### ISSUE THREAD

**Issue by s3nt1n3l-hub** [microsoft/WindowsAppSDK#3430]
### Describe the bug

When attempting to open the application on Windows 10 / Windows 11 machines that don't have Visual Studio installed, the application crashes immediately. The following information is available in EventViewer:

```
Faulting application name: ETI.TDHub.GUI.exe, version: 1.0.21.0, time stamp: 0x638f99ee
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1348, time stamp: 0x76fcd692
Exception code: 0xc000027b
Faul offset: 0x000000000010b302
Faulting process ID: 0x8fc
Faulting application start time: 0x01d93fc0f0652814
Faulting application path: C:\Program Files\WindowsApps\9989bc1e-77a1-4f02-b7ab-076f05e0038_1.0.22.0_x64__5jgsvtw2f5y9t\ETI.TDHub.GUI.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 88597352-3a22-4e2e-8de8-b8068daa31b7
Faulting package full name: 9989bc1e-77a1-4f02-b7ab-076f05e00e38_1.0.22.0_x64__5jgsvtw2f5y9t
Faulting package-relative application ID: App
```

We've tried to capture the issue in App.xaml.cs > App_UnhandledException (writing to the EventViewer) but the app doesn't ever reach this point. 

The application runs as expected on machines that have Visual Studio installed.

The application _did_ run previously on one of the Windows 11 test machines (without VS installed) for months without issue. The OS was then reset due to an unrelated issue - since then the application has been reinstalled and doesn't work.

### Steps to reproduce the bug

1. Create a new 'Blank App, Packaged (WinUI 3 in Desktop)' solution
2. Use 'Package and Publish' > 'Create App Packages...' to publish the app using a test certificate for signing
3. Install the test certificate
4. Install the application
5. Run the application

### Expected behavior

The application will display a white Window with a 'Click here' button in the centre.

### NuGet package version

Windows App SDK 1.2.3: 1.2.230118.102

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update), Windows 10 version 22H2 (19045, 2022 Update), Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

### Additional context

The app is running has `WindowsAppSDKSelfContained` set to true. 
We tried installing the latest VCRedist pack on two of the affected test machines (v14.34.31931) in the hopes that it may help - no success.

**Comment by s3nt1n3l-hub** [comment]
We have now also tried the following on the Windows 10 machine that worked previously, had Windows reset, and now no longer runs the app:

- Installed Microsoft Visual C++2015-2022 Redistributable (x64) - 14.34.31938
- Installed Microsoft.WindowsAppRuntime.Redist.1.0.1-20220317.0-46583170
- Installed Windows 10 SDK 10.0.19041.685
- Installed Microsoft Visual Studio Community (with WinAppSDK pre-reqs)
- Installed Windows App SDK 1.3.0 Experimental 1 (1.3.230202101 -experimental1)
- Installed Windows App SDK 1.2.3 (1.2.230118.102)
- Installed Microsoft.WindowsAppRuntime.Redist.1.2.230118.102

None of which have worked - we still receive the same KERNELBASE.dll error.

Further information relating to the application / setup:

-Using Microsoft Visual Studio v1.7.5

App is packaged via 'Package and Publish > Create App Package', Sideloading, Signed with a test certificate (SHA512), and configured as 'Release (x64)'.

The csproj file contains the following:

```
<OutputType>WinExe</OutputType>
<TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>   
<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
<Platforms>x86;x64</Platforms>
<RuntimeIdentifiers>win10-x86;win10-x64</RuntimeIdentifiers>
<PublishProfile>win10-$(Platform).pubxml</PublishProfile>
<UseWinUI>true</UseWinUI>
<EnableMsixTooling>true</EnableMsixTooling>
<PlatformTarget>x64</PlatformTarget>
<SignAssembly>True</SignAssembly>
<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
<AppxBundle>Never</AppxBundle>
<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
<Configurations>Debug;Release;Sideload</Configurations>
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
```

The win10-x64 publish profile contains:
```
<PublishProtocol>FileSystem</PublishProtocol>
<Platform>x64</Platform>
<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
<PublishDir>bin\\\win10-x64\publish\</PublishDir>
<SelfContained>true</SelfContained>
<PublishSingleFile>false</PublishSingleFile>
<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">true</PublishReadyToRun>
<Configuration>Release</Configuration>
<TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
<PublishTrimmed>false</PublishTrimmed>
```

**Comment by Xo3-ToBapbl** [comment]
@s3nt1n3l-hub could you please add information how you managed to fix this issue? We struggle with similar problem but not during application start. In our case application can fail in any random moment.

Something along the lines can be found here:
https://learn.microsoft.com/en-us/answers/questions/1191322/how-to-track-down-source-of-kernelbase-dll-error-(?comment=question

**Comment by rhenry74** [comment]
i can't figure out how to publish my new winui 3 app
it crashes immediately

**Comment by ssparach** [comment]
Appreciate your comments! As this thread is resolved, could you please file new issues including minimal repros? That will allow us to look into your scenarios thoroughly. Thanks!
