### ISSUE TITLE
UWP print bug: cannot remember print quality

### ISSUE THREAD

**Issue by benstevens48** [microsoft/WindowsAppSDK#345]
**Describe the bug**
When printing in a UWP app using the standard print preview dialog, it's not possible to get it to remember the selected output quality. It's possible this may depend on the printer (I'm using an Epson XP-640), but using the old-style preferences dialog from Word can correctly remember the print quality option.

**Steps to reproduce the bug**
Go through the necessary steps to enable printing in a UWP app. Add a `PrintTaksSourceRequestedHandler` that looks like the following.

```C#
void PrintTaskSourceRequested(PrintTask printTask, PrintTaskSourceRequestedArgs sourceRequested) {
      sourceRequested.SetSource(printDocumentSource);
      printTask.Completed += PrintTask_Completed;
      printTask.Options.DisplayedOptions.Clear();
      printTask.Options.DisplayedOptions.Add(StandardPrintTaskOptions.PrintQuality);
      printTask.Options.PrintQuality = PrintQuality.High;
      PrintTaskOptionDetails printDetailedOptions = PrintTaskOptionDetails.GetFromPrintTaskOptions(printTask.Options);
      printDetailedOptions.OptionChanged += PrintDetailedOptions_OptionChanged;
      printTask.Previewing += PrintTask_Previewing; //Implementation omitted
}

private void PrintDetailedOptions_OptionChanged(PrintTaskOptionDetails sender, PrintTaskOptionChangedEventArgs args) {
    System.Diagnostics.Debug.WriteLine(sender.Options.PrintQuality);
}

private void PrintTask_Completed(PrintTask sender, PrintTaskCompletedEventArgs args) {
    System.Diagnostics.Debug.WriteLine(sender.Options.PrintQuality);
}
```

Note that when opened, the print dialog output quality is set to standard, not high. Upon changing the print quality option or print completed, the quality is logged as `PrinterCustom`. It will print in high quality if high quality is selected, but there's no way to remember this option or set it in the first place. All the other options I tried to remember (such as paper type) work fine.

It seems that you actually have to have a real printer connected for this to happen. I only have one printer so cannot test with another one.

**Expected behavior**
`PrintTaskOptions.PrintQuality` should return the currently selected value instead of `PritnerCustom` and it should be possible to set this option without it changing back to standard when the preview dialog is displayed.

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by stevewri** [comment]
FWIW: I've seen the OneNote printer driver forget resolution when printing from Win32 apps.

**Comment by andrewleader** [comment]
Thanks for reporting this! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31584327) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!

If you'd like to track the status of the bug, you could submit this bug report through Feedback Hub and then share your link to your feedback so that I can link it up with the platform bug I created.

**Comment by benstevens48** [comment]
@andrewleader , thanks for filing the issue. I'm not a fan of the Feedback Hub, but I submitted it anyway - https://aka.ms/AAb117l

Actually I just remembered there is a relatively new GitHub repository for reporting issues, but they are only taking performance-related issues right now - https://github.com/microsoft/WinDev. Do you know if they are going to start accepting platform bugs any time soon?

Also, I'm wondering if there are certain classes of platform bug where project reunion could potentially provide a workaround API that works downlevel. I'm thinking that one of the project's goals is to ensure the user doesn't have to install a major OS update to get new features, but ideally this should also apply to bug fixes as well - perhaps even more so. Do you think that's realistic?
