### ISSUE TITLE
How to keep title bar min/max/close buttons to right side when arabic language is selected.

### ISSUE THREAD

**Issue by Sunilam** [microsoft/WindowsAppSDK#3452]
HI Team,

Its a Winui3 application.

how to keep title bar min/max/close buttons to right side when arabic language is selected.

![image](https://user-images.githubusercontent.com/7436855/220016948-d5abefdc-e5a7-4251-bc6b-633fc5b2279c.png)

Now i have selected arabic as default language in my system and launched my application. Here Min/Max/Close icons in the title bar is showing in the left side.

We want those min/max/close buttons to be shown in the right side of the title bar always for all the languages.

Note: Min/Max/Close buttons shows on right side of the title bar normally when english language is selected in the system.

**Answer from MSDN: https://learn.microsoft.com/en-us/answers/questions/1167352/how-to-keep-title-bar-min-max-close-buttons-to-rig

when can we expect this feature of showing min/max/close button to top right corner when arabic language is selected in the system.**

Best Regards,
Sunil

_Originally posted by @Sunilam in https://github.com/microsoft/WindowsAppSDK/discussions/3443_

**Comment by Sunilam** [comment]
HI Team,

Can i have the answer for the above requirement.

**Comment by peterjtan** [comment]
The AppWindow's title bar renders right-to-left (RTL) if the window style `WS_EX_LAYOUTRTL` is set. You could try removing `WS_EX_LAYOUTRTL` from the AppWindow's window style by calling `SetWindowLong`, and that should satisfy your requirement.

**Comment by peterjtan** [comment]
Closing this issue for now. Feel free to reopen it (or create a new one) if problem persists. Thanks!
