### ISSUE TITLE
Build error APPX1101 when trimming apps

### ISSUE THREAD

**Issue by praeclarum** [microsoft/WindowsAppSDK#3454]
### Describe the bug

I cannot build my app on Windows because the packager finds two different PDB files. One is trimmed the other is not. It doesn't seem to know what to do.

Build error:

```
Error: C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1504,5): error APPX1101: Payload contains two or more files with the same destination path 'ThreeDO.pdb'. Source files:  [D:\a\ThreeDO\ThreeDO\ThreeDO.UI\ThreeDO.csproj::TargetFramework=net7.0-windows10.0.19041.0]
[46](https://github.com/praeclarum/ThreeDO/actions/runs/4237074597/jobs/7362619012#step:7:47)
Error: C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1504,5): error APPX1101: D:\a\ThreeDO\ThreeDO\ThreeDO.UI\obj\Release\net7.0-windows10.0.19041.0\win10-x64\linked\ThreeDO.pdb [D:\a\ThreeDO\ThreeDO\ThreeDO.UI\ThreeDO.csproj::TargetFramework=net7.0-windows10.0.19041.0]
[47](https://github.com/praeclarum/ThreeDO/actions/runs/4237074597/jobs/7362619012#step:7:48)
Error: C:\Users\runneradmin\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.Build.Msix.Packaging.targets(1504,5): error APPX1101: D:\a\ThreeDO\ThreeDO\ThreeDO.UI\bin\Release\net7.0-windows10.0.19041.0\win10-x64\ThreeDO.pdb [D:\a\ThreeDO\ThreeDO\ThreeDO.UI\ThreeDO.csproj::TargetFramework=net7.0-windows10.0.19041.0]
```

The full build and code can be seen here: https://github.com/praeclarum/ThreeDO/actions/runs/4237074597/jobs/7362619012

Framework: net7.0-windows10.0.19041.0

### Steps to reproduce the bug

1. Create a new MAUI app
2. Change the CSPROJ to include:

```xml
	    <PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<PublishReadyToRun>true</PublishReadyToRun>
		<PublishTrimmed>true</PublishTrimmed>

```

### Expected behavior

Windows app builds

### NuGet package version

None

### Windows version

Windows 10 version 1909 (18363, November 2019 Update)

### IDE

Other

### Additional context

I just started with eh default MAUI template for .NET 7.0.101

**Comment by praeclarum** [comment]
How do you turn off APPX packaging? I cannot find a property to control it.

I tried

```xml
<AppxPackage>false</AppxPackage>
```

But it keeps trying to generate the package. I just want an EXE app. I don't want the installer.

**Comment by Balkoth** [comment]
I guess you need to read [this](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps) and use `<WindowsPackageType>None</WindowsPackageType>`.

**Comment by eduardobragaxz** [comment]
I have had the [same](https://github.com/microsoft/WindowsAppSDK/issues/3030) issue for a while. There are some workarounds in the responses. Still seeing this using .NET 8 preview 1 and WinAppSDK preview.

**Comment by ACGNnsj** [comment]
> I guess you need to read [this](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps) and use `<WindowsPackageType>None</WindowsPackageType>`.

Thanks, this works for me.

**Comment by devatrivanus18** [comment]
> I guess you need to read [this](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps) and use `<WindowsPackageType>None</WindowsPackageType>`.

it works, but when i try to publish the IDE visual studio immediately force close. how can i fix this issue?

**Comment by MuyuanMS** [comment]
Closing the issue as solution has been provided. For any followups that's not related to original issue, feel free to open another one with more information if it is still not working currently.
