### ISSUE TITLE
Visual Studio Templates 1.2.230217.4 manifest supported OS Windows 8.1

### ISSUE THREAD

**Issue by Balkoth** [microsoft/WindowsAppSDK#3460]
### Describe the bug

I don't know if it always was like this but this entry

```xml
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
  <application>
    <!--The ID below informs the system that this application is compatible with OS features first introduced in Windows 8. 
    For more info see https://docs.microsoft.com/windows/win32/sysinfo/targeting-your-application-at-windows-8-1 
    
    It is also necessary to support features in unpackaged applications, for example the custom titlebar implementation.-->
    <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" />
  </application>
</compatibility>
```

seems wrong to me.

Should be:

```xml
<compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
  <application>
    <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
  </application>
</compatibility>
```

### Steps to reproduce the bug

Create a new packaged application throuth the template.

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by castorix** [comment]
It is OK,  {4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}" is Windows 8 :

https://learn.microsoft.com/en-us/windows/win32/sysinfo/targeting-your-application-at-windows-8-1

**Comment by Balkoth** [comment]
Isn't Windows 10 version 1809 the minimum requirement for Windows App SDK Apps?

**Comment by JaiganeshKumaran** [comment]
Good that Microsoft still supports the best version of Windows ever made.

**Comment by castorix** [comment]
> Isn't Windows 10 version 1809 the minimum requirement for Windows App SDK Apps?

You set Windows 8 for example to support layered child windows (Note at [Layered Windows](https://learn.microsoft.com/en-us/windows/win32/winmsg/window-features#layered-windows)), like the Caption window (_DRAG_BAR_WINDOW_CLASS_ class)

**Comment by DarranRowe** [comment]
@Balkoth 
I understand what you mean, you would expect the Windows 10 compatibility declaration.

**Comment by Balkoth** [comment]
Exactly.

**Comment by bpulliam** [comment]
The change will be in the next drop of the templates.
