### ISSUE TITLE
communityToolkit.MVVM does not generate source code for classes inheriting ObservableObject

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#3466]
### Describe the bug

Can someone please have a look at this issue? 
https://github.com/CommunityToolkit/dotnet/issues/623#issue-1602180394

### Steps to reproduce the bug

1. Create a new Windows App SDK / WinUI 3 Packaged desktop app project
2. Install the ComunityToolkit.MVVM Nuget package, ver. 8.1.0
3. Create a class and inherit ObservableObject
``
      public partial class MyClassViewModel : ObservableObject
       {
           [ObservableProperty]
           string customerName;
       }
``
5. Build the project and go to Dependencies > Analyzers > CommunityToolkit.Mvvm.SourceGenerators > CommunityToolkit.Mvvm.SourceGenerators.ObservableObjectGenerator
![image](https://user-images.githubusercontent.com/77593544/221861905-fd822a83-cab4-4c23-804f-b95b995d2097.png)

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022-preview

**Comment by gabbybilka** [comment]
Looking into the linked issue, it seems like this is the root issue causing this error. Closing as external: https://github.com/dotnet/roslyn/issues/67123
