### ISSUE TITLE
Allowing snapping more than two apps in a column layout

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#347]
Today, only two apps can be snapped in a column layout and four apps can be snapped in a two-row layout. I would suggest adding the ability to snap more than two apps in a column layout on larger displays. FancyZones can do this but it lacks the splitter to resize the snap instead forcing to enter a manual size. Existing Windows snap can be adjusted to allow more snapping if space is available. This may sound difficult in a free windowed model but Microsoft should try to bring it back in Windows 10 while preserving the free windowed model instead of a fixed height windowing model.

![Image](http://cdn3.sbnation.com/assets/3402557/Split_Screen_Four_Apps-1024.jpg)

**Comment by Gavin-Williams** [comment]
Don't we already have this in PowerToys?

**Comment by riverar** [comment]
@Gavin-Williams FZ does not contain the proposed behavior.

**Comment by Jaiganeshkumaran** [comment]
Seems like the latest leaked build has a three app snap mode option in the new flyout

**Comment by Jaiganeshkumaran** [comment]
Closing this as Windows 11 has similar functionality built-in.
