### ISSUE TITLE
Winui3(Windows App SDK) MainWindow/AppWindow Bug title

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#3473]
### Describe the bug

使用AppWindow.Title属性或MainWindow.title属性修改应用的标题名称时，显示的标题名称不一致
When you modify the title name of an app using the AppWindow.Title property or the MainWindow.title property, the title name displayed is inconsistent

如图所示，我设置的应用标题名称为“获取商店应用”，实际上显示的是“获取商店”，缺少“获取商店”两字。
As shown in the image, the title name of the app I set is "获取商店应用", which actually shows "获取商店", missing the word "获取商店".

### Steps to reproduce the bug

无，具体内容在Describe the bug中
No, the details are described in Describe the bug

### Expected behavior

应用标题名称应该显示为正确的名称，如我的应用为“获取商店应用”。
The app title name should appear as the correct name, such as My app is "获取商店应用".

### Screenshots

![E45`}60 F}AVDE6GD3~ GLL](https://user-images.githubusercontent.com/49179966/222451487-e0693a23-30c0-40cf-b226-2e5c379c9cd7.png)

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by peterjtan** [comment]
Thanks for submitting this issue. However, I was not able to repro this locally. Could you provide a repo app, or point out where the affected line is located in your repo?

**Comment by Gaoyifei1011** [comment]
> Thanks for submitting this issue. However, I was not able to repro this locally. Could you provide a repo app, or point out where the affected line is located in your repo?

I feel this is a metaphysical problem, the corresponding wasdk version was 1.2.4 when this bug occurred. At that time when setting the title used appwindow title attribute, Window class title attribute and win32api setwindowtext, have appeared such a situation, and such a situation is under the simplified Chinese characters, English is not appeared. After the 1.2.5 release, it will display normally

**Comment by peterjtan** [comment]
That's kind of weird as SetWindowText has this issue too...
The WinAppSDK layer also calls that API when setting the title text, so the issue will also appear there if SetWindowText has this issue.

Anyways, would you mind closing the issue if this is not repo? You can reopen it (or create a new one) in the future if the problem persists.
