### ISSUE TITLE
BluetoothLEAdvertisementWatcher.Start throws COMException when adapter is disabled

### ISSUE THREAD

**Issue by jeremy-visionaid** [microsoft/WindowsAppSDK#3503]
### Describe the bug

Calling BluetoothLEAdvertisementWatcher.Start throws a COMException with ERROR_DEVICE_NOT_AVAILABLE when the adapter is disabled. However, the documentation indicates that it should raise a Stopped event with RadioNotAvailable.
https://learn.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisementwatcher.start?view=winrt-22621

### Steps to reproduce the bug

Disable the Bluetooth adapter in "Settings" -> "Bluetooth & devices".
Call BluetoothLEAdvertisementWatcher.Start

### Expected behavior

BluetoothLEAdvertisementWatcher.Stopped should be raised with BluetoothLEAdvertisementWatcherStoppedEventArgs.Error == BluetoothError.RadioNotAvailable

### NuGet package version

None

### Packaging type

Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment]
As this is not a WinAppSDK API, please file this issue under Feedback Hub.
