### ISSUE TITLE
WindowsAppSdk Application not getting installed from exe.

### ISSUE THREAD

**Issue by VarunTwri** [microsoft/WindowsAppSDK#3512]
### Describe the bug

Created exe after publishing from visual studio.
90MB exe file got created but unable to install.
Also followed below url for deployement still same.
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp

### Steps to reproduce the bug

1.Right Click on project from Visual studio.
2.Selected below settings.
![image](https://user-images.githubusercontent.com/102298041/225620642-d5d58abf-d021-42cf-9b7a-853cf8dec1c2.png)

3.Then Published, then unable to install .
![image](https://user-images.githubusercontent.com/102298041/225620876-a21549d7-2c50-41f9-a998-063296b1542c.png)

### Expected behavior

Exe should get installed

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by LegendaryBlair** [comment]
Follow this doc https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp, the user should do "packaging" instead of "publish".
