### ISSUE TITLE
Improve OCR Engine

### ISSUE THREAD

**Issue by TheJoeFin** [microsoft/WindowsAppSDK#3514]
# Proposal: Upgrade WinRT's OCR Engine with a more robust engine

## Summary
A more robust engine to do OCR on printed text, screen captures, handwriting, and distorted photos in challenging environments.

## Rationale
* OCR is becoming more valuable as an API.
* More robust engine would deliver more value to current OCR users
* OCR could be applied to more scenarios

## Important Notes
* Apple's OCR engine on iOS is very accurate and highlights the shortcomings of the Windows OCR API
* Table recognition would multiply the value of OCR in applications
* Layout recognition would reduce the time and custom code to return value from the API

## Open Questions
* Could Microsoft use Tesseract as the core OCR technology?

**Comment by JaiganeshKumaran** [comment]
The WinRT OCR Engine was originally a standalone [NuGet package](https://www.nuget.org/packages/Microsoft.Windows.Ocr/#readme-body-tab) so it could be updated. It was a mistake to add it to the OS because Windows has a slower release cycle.

**Comment by TheJoeFin** [comment]
Sounds like a good plan! What would it take to update the nuget package?

**Comment by lovettchris** [comment]
https://github.com/tesseract-ocr/tesseract works way better.
