### ISSUE TITLE
MSB3073 error when building a Windows app on an Azure pipeline agent

### ISSUE THREAD

**Issue by GabrielChouinardLetourneau** [microsoft/WindowsAppSDK#3545]
### Describe the bug

When building my Windows applications on an Azure pipline agent, the Build in release task fails with a MSB3073 error looking like this: `C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(726,9): error MSB3073: The command ""C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.2.221209.1\buildTransitive\..\tools\net5.0\..\net472\XamlCompiler.exe" "obj\x64\Release\net6.0-windows10.0.22000.0\win-x64\\input.json" "obj\x64\Release\net6.0-windows10.0.22000.0\win-x64\\output.json"" exited with code 1.`

I've tried with multiple targets and other version of the SDK without any success.

Additionally, the script that I am trying to run on the machine looks similar to this: 
```yaml
- script: >
    cd ${{ parameters.pathToSrc }}/app/${{ parameters.solutionName }}.Windows

    dotnet build
    -f:$(BuildTargetFramework)
    -c:Release
    -r:win-x64
    -bl:$(build.ArtifactStagingDirectory)/build-$(BuildTargetFramework).binlog
    -p:Platform=$(ApplicationPlatform)
    -p:ApplicationEnvironment=$(ApplicationEnvironment)
  displayName: 'Build solution in $(ApplicationConfiguration) | $(ApplicationPlatform)'
  ```

### Steps to reproduce the bug

1. Use `windows-latest` as the Azure pipeline agent
2. Run a pipeline of the `windows-latest` agent
3. Have the script mentioned above build your application 
4. The build should throw an error similar to the one at the core of this current issue

### NuGet package version

Windows App SDK 1.2.5: 1.2.230313.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

### Additional context

Microsoft.Windows.SDK.BuildTools version: `10.0.22621.756`

**Comment by Youssef1313** [comment]
I'm hitting this as well. It's a very annoying issue.

**Comment by LegendaryBlair** [comment]
Hi, @GabrielChouinardLetourneau, is this issue still valid?
You can tryout WindowsAppSDK 1.6 and see if the issue persists.

**Comment by GabrielChouinardLetourneau** [comment]
Hi, @LegendaryBlair, this does not seem to work. The project that has this issue depends on some packages that do not support the SDK version (1.6). I will note this for now and will close this issue. Thank you.
