### ISSUE TITLE
version conflict WindowsAppSDK 1.3 unpackaged

### ISSUE THREAD

**Issue by PetrAltman** [microsoft/WindowsAppSDK#3591]
### Describe the bug

After upgrading WindowsAppSDK to version 1.3 there are 3 build warnings about version conflict when using unpackaged application (<WindowsPackageType>None</WindowsPackageType>).

C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\include\MddBootstrapAutoInitializer.cs(34,38,34,77): warning CS0436: The type 'Release' in 'C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs' conflicts with the imported type 'Release' in 'Microsoft.WindowsAppRuntime.Release.Net, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs'.
C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\include\MddBootstrapAutoInitializer.cs(35,33,35,72): warning CS0436: The type 'Release' in 'C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs' conflicts with the imported type 'Release' in 'Microsoft.WindowsAppRuntime.Release.Net, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs'.
C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\include\MddBootstrapAutoInitializer.cs(36,49,36,96): warning CS0436: The type 'Version' in 'C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs' conflicts with the imported type 'Version' in 'Microsoft.WindowsAppRuntime.Release.Net, Version=1.3.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'C:\Users\x\.nuget\packages\microsoft.windowsappsdk\1.3.230331000\buildTransitive\..\include\WindowsAppSDK-VersionInfo.cs'.

Without <WindowsPackageType>None</WindowsPackageType> there are not any warnings.

### Steps to reproduce the bug

Create empty WinUI application, upgrade WinAppSDK to 1.3 and add <WindowsPackageType>None</WindowsPackageType>.

Version conflicts warnings appears.

### Expected behavior

There should be no build warnings.

### NuGet package version

Windows App SDK 1.3.0: 1.3.230331000

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by salmelo** [comment]
I just upgraded a new project and am getting the same issue.

**Comment by nickrandolph** [comment]
Seeing this issue as well!

**Comment by evelynwu-msft** [comment]
https://task.ms/44532535

**Comment by majaeger** [comment]
Is there any workaround possible to get past this?

**Comment by codendone** [comment]
Closing as fixed in 1.4.
