### ISSUE TITLE
The 1.3 versions of the C# & C++ Templates are not available

### ISSUE THREAD

**Issue by bpulliam** [microsoft/WindowsAppSDK#3635]
### Describe the bug

The WinAppSDK has been updated to version 1.3, but the templates in Studio are still 1.2.  The downloads of the VSIX have been removed from the downloads page, so how do I get the updated templates?

### Steps to reproduce the bug

1. Install VS 2022
2. Add WinAppSDK C# or C++ VS 2022 Templates 
3. Start a new project

### Expected behavior

The templates shoud at the very least point to WinAppSDK 1.3.  I would expect them to be 1.3 versions.

### NuGet package version

Windows App SDK 1.3.1: 1.3.230502000

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment]
The updates are on the way. We discovered a breaking C++ bug very late in the 1.3 cycle and then the templates exceeded a size limit. As for the downloads, using both standalone and component versions of the extensions were causing issues with upgrades. Standardizing on the component version should remove those issues (as long as we get them released 😳).  We apologize for the inconvenience.

**Comment by JaiganeshKumaran** [comment]
Can someone look into my pull request (#3619)? The C++ templates don't seem to have been cleaned up that much in the repo.

**Comment by bpulliam** [comment]
Updated templates are now available in Visual Studio 17.7 Preview 2. The current stable VS (17.6) will get them in the next update (17.6.4) which will be out in the next week or so.
In addition, we understand that this delay in updating the templates is painful. We are looking at solutions to make the WinAppSDK version and the templates version in Visual Studio loosely-coupled, so that each can be updated independently.
