### ISSUE TITLE
DevDrive: Windows cannot deploy to path AppX of file system type ReFS

### ISSUE THREAD

**Issue by Redth** [microsoft/WindowsAppSDK#3651]
### Describe the bug

Testing a .NET MAUI app out with the new Windows DevDrive, there is an error while trying to deploy and debug the app from Visual Studio:

```
DEP0700: Registration of the app failed. [0x80073CFD] Windows cannot deploy to path AppX of file system type ReFS.
```

This seems intentionally blocking, however given MAUI's use of multitargeted projects, this effectively means we cannot use DevDrive without some workaround.  

### Steps to reproduce the bug

1. File New MAUI App project
2. Save the project to a DevDrive (or otherwise ReFS partition)
3. Debug the Windows app

### Expected behavior

Expected to be able to deploy and debug

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

### Additional context

NuGet version is 1.3.230331000

If it's not possible to make this supported, we need to come up with some workaround to deploy to a non-ReFS partition if the MAUI project exists there.

**Comment by sylveon** [comment]
This is also blocking WinUI, UWP, packaged Win32 and Win32 app isolation development, making dev drives useless for those cases.

**Comment by Redth** [comment]
Update with a bit more info...

Apparently this only happens if you access the DevDrive from a mapped folder.

For instance i have created a DevDrive partition as `X:\`.  If I load my project from `X:\MyProject\MyProject.csproj`, using packaged apps works fine for deploy and debug.

But there's also an option to map the DevDrive to a folder elsewhere, so I have `D:\code\` mapped to it... I can access files from either `X:\` or `D:\code\` just fine but it seems the `D:\code\` folder appears as 'removable' to windows and is not allowed for appx deployment.

**Comment by evelynwu-msft** [comment]
As a workaround, you can set the `LayoutDir` MSBuild property in your project to a path on a drive that is not formatted with ReFS to tell VS to deploy the folder layout to different location.

**Comment by HotCakeX** [comment]
All of my non-OS drives have been ReFS, i can debug my WinUI3/C#/MSIX packaged app from ReFS drives without any problems.
I use the latest Windows 11.

Installing MSIX from ReFS also works just fine.

**Comment by AdamBraden** [comment]
@manodasanW  - I believe this bug was fixed back in fall 2023, either Windows 11 Sept 2023 release or at least Windows 11 23H2.
