### ISSUE TITLE
Can't build fsproj with WindowsPackageType=None

### ISSUE THREAD

**Issue by 0x0309** [microsoft/WindowsAppSDK#3663]
### Describe the bug

Using `<WindowsPackageType>None</WindowsPackageType>` in an F# Maui project doesn't compile. The `Microsoft.WindowsAppSDK` nuget package includes the following in one of the targets files: `<Compile Include="$(MSBuildThisFileDirectory)..\include\UndockedRegFreeWinRT-AutoInitializer.cs" />` which is invalid.
https://github.com/microsoft/WindowsAppSDK/blob/main/build/NuSpecs/Microsoft.WindowsAppSDK.UndockedRegFreeWinRT.CS.targets

### Steps to reproduce the bug

1. `dotnet new install Fabulous.MauiControls.Templates`
1. `dotnet new fabulous-mauicontrols -n MyApp`
1. `dotnet build` (this succeeds)
1. Add `<WindowsPackageType>None</WindowsPackageType>` to the fsproj file.
1. `dotnet build` (this fails)

### Expected behavior

I can build unpackaged F# Maui projects.

### NuGet package version

None

**Comment by 0x0309** [comment]
Work-around
```xml
<Target Name="RemoveUndockedRegFreeWinRTCS" AfterTargets="GenerateUndockedRegFreeWinRTCS">
  <ItemGroup>
    <Compile Remove="@(Compile)" Condition="'%(Extension)' == '.cs'" />
  </ItemGroup>
</Target>
```

Then add an equivalent F# file as was in the removed C# file.

**Comment by DrusTheAxe** [comment]
It's simpler than that. Add to your project file:

```
    <PropertyGroup>
        <WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
    </PropertyGroup>
```

Per `Microsoft.WindowsAppSDK.UndockedRegFreeWinRTCommon.targets` 

```
    <PropertyGroup Condition="'$(WindowsAppSdkUndockedRegFreeWinRTInitialize)'=='' and '$(WindowsAppSDKSelfContained)'=='true'">
        <!--Allows GenerateUndockedRegFreeWinRTCS/GenerateUndockedRegFreeWinRTCpp to run-->
        <WindowsAppSdkUndockedRegFreeWinRTInitialize>true</WindowsAppSdkUndockedRegFreeWinRTInitialize>
    </PropertyGroup>
```

i.e. if `WindowsAppSdkUndockedRegFreeWinRTInitialize` isn't defined and `WindowsAppSDKSelfContained`=`true` then compile the RegFreeWinRT auto-iniitalizer into the project. Explicitly set `WindowsAppSdkUndockedRegFreeWinRTInitialize`=`false` and no auto-initializer.

Would you mind sharing your equvialent F# file? I don't think Windows App SDK defines any F# projects (so far), but a ported auto-initializer would be a helpful :-)

**Comment by 0x0309** [comment]
@DrusTheAxe the almost equivalent F# code would be as below, except that F# doesn't support the `ModuleInitializerAttribute`. Without `ModuleInitializerAttribute` the developer has to call `Microsoft.Windows.Foundation.UndockedRegFreeWinRTFS.Initializer.AccessWindowsAppSDK ()` themselves at program start, and the SDK can't just rely on it being automatically injected by the targets file. Maybe the SDK could show a warning when building an F# project and meeting these conditions, with a link to docs that explain the need to call the function manually. Then add another build property to suppress the warning after.

```f#
namespace Microsoft.Windows.Foundation.UndockedRegFreeWinRTFS

open System.Runtime.InteropServices

module private NativeMethods =

    [<DllImport("Microsoft.WindowsAppRuntime.dll", CharSet = CharSet.Unicode, ExactSpelling = true)>]
    extern int WindowsAppRuntime_EnsureIsLoaded()

[<AbstractClass; Sealed>]
type Initializer =

    static member AccessWindowsAppSDK () =
        NativeMethods.WindowsAppRuntime_EnsureIsLoaded ()
        |> ignore // return value not required
```

**Comment by DrusTheAxe** [comment]
>the almost equivalent F# code would be as below, except that F# doesn't support the ModuleInitializerAttribute

Neat. Thanks for sharing.

>Maybe the SDK could show a warning when building an F# project and meeting these conditions, with a link to docs that explain the need to call the function manually. Then add another build property to suppress the warning after.

We've discussed more "Hey dev, you're doing something potentially problematic" sorts of build warnings with "Yes, I know, and it's fine" properties to acknowledge and suppress them. I'll add your feedback to the hopper. Thanks.

+@Scottj1s @bpulliam @MikeHillberg

**Comment by LegendaryBlair** [comment]
Workaround provided, hence closing the issue.
