### ISSUE TITLE
 WindowsAppSDK1.3 : DependencyProperty::RegisterAttached is not working in WinUI3 unpackaged application

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/WindowsAppSDK#3673]
### Describe the bug

When trying to registers an attached dependency property with the specified property name using the method the Microsoft::UI::Xaml::DependencyProperty::RegisterAttached() the application crashes at startup and throwing the following exception.

`Exception thrown at 0x00007FF968B2CF19 (KernelBase.dll) in SampleApp.exe: WinRT originate error - 0x80040154 : 'Class not registered'.
'SampleApp.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
Exception thrown at 0x00007FF968B2CF19 in SampleApp.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x000000C961BCFBF0.
Unhandled exception at 0x00007FF968B2CF19 in SampleApp.exe: Microsoft C++ exception: winrt::hresult_class_not_registered at memory location 0x000000C961BCFBF0.`

### Steps to reproduce the bug

1. Create a C++ WinUI3 project using "Blank App, Packaged (WinUI 3 in Desktop)" template.
2. Make it as unpackaged application using the steps described in the following link.
  [https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app#unpackaged-create-a-new-project-for-an-unpackaged-c-or-c-winui-3-desktop-app](url)
3. Registers an attached dependency property with the specified property name, property type, owner type, and property metadata for the property in MainWindow class.
4. Build the application.
5. Start the application.

### Expected behavior

The application would run without crashing or throwing an error.

### NuGet package version

Windows App SDK 1.3.1: 1.3.230502000

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

A sample application with the above-mentioned issue is attached.
[SampleApp.zip](https://github.com/microsoft/WindowsAppSDK/files/11744864/SampleApp.zip)

Any help would be greatly appreciated.

**Comment by DarranRowe** [comment]
This, interestingly enough, isn't a Windows App SDK problem.
What you are seeing is the C++ [static initialisation order fiasco](https://en.cppreference.com/w/cpp/language/siof) at work. The dependency property is a static class member being initialised at global scope. The Windows App SDK bootstrap is also done as a static global variable that is in the MddBootstrapAutoInitializer.cpp file which is compiled and linked to your application when you set the WindowsPackageType project setting to none.
So when this kind of situation happens, you tend to have little control over the order that global variables initialise, this is something that is completely implementation defined. Your best option is to delay the initialisation of the dependency properties until you get to the App constructor at the very least. The other option is to take control of when the Windows App SDK bootstrapper is run and make sure that your dependency properties initialise after the bootstrapper runs.

**Comment by Ajith-GS** [comment]
> This, interestingly enough, isn't a Windows App SDK problem. What you are seeing is the C++ [static initialisation order fiasco](https://en.cppreference.com/w/cpp/language/siof) at work. The dependency property is a static class member being initialised at global scope. The Windows App SDK bootstrap is also done as a static global variable that is in the MddBootstrapAutoInitializer.cpp file which is compiled and linked to your application when you set the WindowsPackageType project setting to none. So when this kind of situation happens, you tend to have little control over the order that global variables initialise, this is something that is completely implementation defined. Your best option is to delay the initialisation of the dependency properties until you get to the App constructor at the very least. The other option is to take control of when the Windows App SDK bootstrapper is run and make sure that your dependency properties initialise after the bootstrapper runs.

Thank you so much for your help.
The issue is fixed by initialising the static class member after the InitializeComponent() call.

**Comment by Ajith-GS** [comment]
> This, interestingly enough, isn't a Windows App SDK problem. What you are seeing is the C++ [static initialisation order fiasco](https://en.cppreference.com/w/cpp/language/siof) at work. The dependency property is a static class member being initialised at global scope. The Windows App SDK bootstrap is also done as a static global variable that is in the MddBootstrapAutoInitializer.cpp file which is compiled and linked to your application when you set the WindowsPackageType project setting to none. So when this kind of situation happens, you tend to have little control over the order that global variables initialise, this is something that is completely implementation defined. Your best option is to delay the initialisation of the dependency properties until you get to the App constructor at the very least. The other option is to take control of when the Windows App SDK bootstrapper is run and make sure that your dependency properties initialise after the bootstrapper runs.

Thank you so much for your help.
The issue is fixed by initialising the static class member after the InitializeComponent() call.
