### ISSUE TITLE
Launcher should snap the newly launched app if the current app is maximized in desktop mode

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#368]
# Proposal: Launcher should snap the newly launched app if the current app is maximized in desktop mode

In tablet mode, the launcher will snap the newly launched app however it doesn't in desktop mode. While if the current window that requested launch is not maximized yes it should not snap the newly launched app since there's free windowing. But if the current window is maximized I expect the newly launched window to be snapped if it supports resizing and snapping.

## Rationale

* Improved user experience for end users

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to disable this behaviour and let the target app use it's defaut size | Must |
| This proposal will allow end users to see launched app snapped if current app is maximized | Should |

**Comment by Jaiganeshkumaran** [comment]
If the original app is floating then it doesn't matter but when both are maximized it makes much more sense to snap instead of leaving them maximized

**Comment by rkarman** [comment]
I read this as a windows window management UX request, and not a windowing API feature as it is currently written. It is basically asking for "parts of TabletMode" to be moved into the Desktop environment. I.e. this is not a Reunion feature and should instead be logged as a suggestion using Feedback Hub.

**Comment by rkarman** [comment]
Almost a year has passed since last comment, and I see no comment about actually having filed a FeedbackHub issue/feature request. Closing the issue since it is not a Windows App SDK feature but a Windows UX one.

**Comment by Jaiganeshkumaran** [comment]
I finally created a Feedback Hub feature requested: https://aka.ms/AAgrsgl.
