### ISSUE TITLE
Unable to know if active high contrast scheme is dark or light

### ISSUE THREAD

**Issue by sylveon** [microsoft/WindowsAppSDK#3707]
### Describe the bug

The current ThemeSettings API only has a HighContrastScheme property returning a string. However, one might want to know if the high contrast theme being used is light or dark. One example where this is useful is to detect what kind of tray icon should be used: a light high contrast theme would use a dark tray icon, and vice versa. This is not a theorical: the Microsoft Store app quality team complained to me about this very thing, and I had to program in a hack to satisfy them.

Using strings for that property means it cannot reliably be used for that, as the scheme name can be translated and/or change in future versions of Windows.

### Steps to reproduce the bug

1. Try to use HighContrastScheme for something useful
2. Be sad :(

### Expected behavior

I expected for ThemeSettings to provide me more useful information about the high contrast theme being in use, instead of just its name.

### NuGet package version

Windows App SDK 1.4 Experimental 1: 1.4.230518007-experimental1

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update), Windows 11 version 21H2 (22000), Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by riverar** [comment]
High contrast has no real concept of dark/light mode. Instead, the app should be using an appropriate design token that has its color set from the active theme (e.g., `System.Windows.SystemColors.WindowTextColor` in WPF).

**Comment by sylveon** [comment]
Dynamic tray icon generation is not realistic though.

**Comment by riverar** [comment]
That's what we do in EarTrumpet 🥲. (I agree with you though.)

**Comment by riverar** [comment]
@bpulliam Why was this closed?

**Comment by tim-weis** [comment]
@bpulliam When you close an issue *"as completed,"* please link to the PR that resolves the issue so we mere mortals can know when the fix ships.
