### ISSUE TITLE
Why not provide windows app sdk 1.4 preview 1 update release notes

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#3733]
### Describe the bug

Why not provide windows app sdk 1.4 preview 1 update release notes?
Until now, the update log of Windows app sdk 1.4 preview 1 is not provided, please update the update log of Windows app sdk 1.4 preview 1 as soon as possible

### Steps to reproduce the bug

None

### Expected behavior

please update the update log of Windows app sdk 1.4 preview 1 as soon as possible

### Screenshots

None

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ghost1372** [comment]
https://aka.ms/windowsappsdk/1.4/1.4-preview1/release-notes

**Comment by duncanmacmichael** [comment]
Thanks for opening this issue, @Gaoyifei1011. The release notes have been updated to be more descriptive of the new features available in 1.4-preview1 (see link in previous comment).
