### ISSUE TITLE
API to add file and folder to "most recent file and folder" list

### ISSUE THREAD

**Issue by fabianoriccardi** [microsoft/WindowsAppSDK#3744]
### Describe the bug

It would be great to have an API to add and remove files and folders from the most recent file and folder (also called Quick Access) in Windows 10/11.

I know the existence of SHAddToRecentDocs(..) (more info [here](https://gotask.net/programming/c-sharp-how-to-add-or-remove-items-from-windows-recent-files/)), but to use this API I need to enable the flag "Enable unsafe code" (I don't like it, it feels weird if you consider you are using a very standard feature of Windows).

Moreover, I would have the possibility to add a path to a file or to a folder, and split the 2 categories. An example of what I mean is given by Visual Studio Code, in the following screenshot. Unfortunately, I don't get how Visual Studio Code can split file and folder in the appropriate section through SHAddToRecentDocs(..))...

![Immagine](https://github.com/microsoft/WindowsAppSDK/assets/7937648/67c3d53b-9996-45f6-80d6-b3510276ee18)

### Steps to reproduce the bug

...

### NuGet package version

None

### Packaging type

Packaged (MSIX)

**Comment by bpulliam** [comment]
Please log this in the feedback hub.

**Comment by fabianoriccardi** [comment]
I will, but I though Feedback Hub was intended for end users and not for developers...
