### ISSUE TITLE
AppointmentStore API is broken (AGAIN)

### ISSUE THREAD

**Issue by kinex** [microsoft/WindowsAppSDK#3748]
Every time Microsoft publishes an update to the Microsoft Calendar app, there is a high risk they brake the `AppointmentStore` API. This has happened again and the API has been unusable for 4 weeks now. 

So the problem is that `AppointmentStore.ShowEditNewAppointmentAsync` does not work. It should open Microsoft calendar app window for adding a new appointment. Currently it just shows the splash screen and then closes immediately.

My app published in Microsoft Store does not work at all due to this issue and users are contacting me to fix the issue.

When do you fix this?

Could you please test your changes before publishing updates to the Microsoft Calendar app. You should understand that there are many 3rd party apps in Microsoft Store that depend on the `AppointmentStore` API so it must not be broken.

Test environment: Windows 10.0.19045.3208 (Calendar app 16005.14326.21508.0)

**Comment by bpulliam** [comment]
Please log this issue in the Feedback Hub.

**Comment by kinex** [comment]
Feedback Hub is just a waste of time. This needs to be fixed ASAP.

**Comment by dotMorten** [comment]
@kinex Posting in a repo that isn’t responsible for the specific issue (you said yourself the app breaks it, not the Sdk) is even more waste of time though?

**Comment by kinex** [comment]
@dotMorten This is the closest related repo I could find. If this is not the correct repo, at least Calendar app / `AppointmentStore` API developers could find this anyway, and someone knowing the correct team could point them out this issue (developers of this SDK and the Calendar app developers work in the same company, right?). I need to get this fixed in a way or another as my users are angry and they blame me about this of course. Only Microsoft can fix this.

I am not sure if the `AppointmentStore` API is part of this SDK or not, I suppose it might be or maybe at least should be. It is just an implementation detail of the `AppointmentStore` API that it launches the Microsoft Calendar app for several operations. And it is a very problematic implementation detail as we all 3rd party calendar app developers know. 

And as a side note, if I have understood correctly the current Microsoft Calendar app is deprecated and is being replaced with a similar PWA app. This raises even more concerns. I hope they have not forgotten that the `AppointmentStore` API depends on the Calendar app currently. So what is your plan regarding the `AppointmentStore` API? I wonder if it is even technically possible to integrate the `AppointmentStore` API with their new PWA Calendar app. Maybe you should consider implementing fully independent `AppointmentStore` API in this SDK?

**Comment by jonwis** [comment]
So a little terminology & history...

The `AppointmentStore` was designed as a brokering system between calendar _readers_ and calendar _providers_.  The Windows calendar app is a _reader_ of information in the user's appointment stores - you could imagine other apps like social calendaring systems also reading the appointment stores and doing something useful with the information. Mail & Calendar (and Outlook, and maybe others) are _providers_ of appointment data.

Appointment _readers_ aren't allowed to directly create an appointment on behalf of a provider, so we added methods for a reader to request that the provider show its own "edit and modify" experience.  That's the `ShowEditNewAppointmentAsync` method you linked - calling that invokes the _provider_ to show a create-and-edit experience.

I'll hunt around for the Mail & Calendar owner to see if they know what's up.

**Comment by riverar** [comment]
@dotMorten The app ships with Windows inbox, so I'd argue it's closer to a platform API than not. And that's where posting here made sense--this repository _was_ once accepting platform API bugs.

**Comment by jonwis** [comment]
For the record, the Mail & Calendar teams are looking into this.  Cc @kentmai and @bencaratms

**Comment by kinex** [comment]
Current status as of January 2025 @jonvis @KentMai @bencaratms:

- The AppointmentStore API is completely broken, nothing works.
- In addition to earlier issues, also `AppointmentStore.FindAppointmentsAsync` is now broken, so you cannot even retrieve existing appointments from calendars.
- Based on the increasing user feedback I am receiving from my calendar app users, it appears you have made recent updates that ensure nothing works.

I suppose there have been periods also after 2023 when the API has worked for some lucky users (perhaps depending on their Mail & Calendar app version), as my app has still received downloads and even purchases.

I believe the Mail & Calendar team has been well aware of these issues but has chosen to ignore them. As a result, all third-party calendar apps that depend on this API are now useless and non-functional. This is difficult to explain to the users of my app who have paid for it.

I expected better communication regarding your plans for this API.

**Comment by dotMorten** [comment]
I have complained a million times to the Outlook team that they stopped populating these calendars with the forced update of the rewritten calendar app to move people to the new outlook.
My apps became useless for that reason as well

**Comment by colinmorris1992** [comment]
In June 2023, Microsoft announced that the Windows Mail & Calendar applications would end support on December 31, 2024 - [Outlook for Windows the Future of Mail Calendar and People](https://support.microsoft.com/en-us/office/outlook-for-windows-the-future-of-mail-calendar-and-people-on-windows-11-715fc27c-e0f4-4652-9174-47faa751b199)
