### ISSUE TITLE
Remove some duplicate Windows namespace classes, methods, and other content

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#3756]
### Describe the bug

In the Windows App Sdk, most of the categories are in the Microsoft.* namespace, but some classes in the Windows.* namespace have the same function as the classes in the Mcirosoft.* namespace. Please remove these duplicate contents.
在Windows 应用 sdk中，大部分类都是在Microsoft.*命名空间下的，然而部分Windows.*命名空间下的类与Mcirosoft.*命名空间下的类有着相同的功能，请将这些重复的内容剔除。

For example, the Windows app sdk used in the c# project generates DLLS, including Microsoft.WinUI.dll. The Windows.UI.Text namespace, Windows.UI.Xaml.Data namespace, Windows.UI.Xaml.Interop namespace, Windows.UI.Xaml.Markup namespace, and Windows.ui.xaml.markup namespace appear in the dll file. Most of these namespace classification and corresponding Microsoft.UI.Text namespace, Microsoft.UI.Xaml.Data namespace, Microsoft.UI.Xaml.Interop namespace, The classes provided by the Microsoft.UI.Xaml.Markup namespace have the same functionality as the corresponding methods.
例如，c#工程中使用到的Windows app sdk，生成的dll中，其中包含Microsoft.WinUI.dll。该dll文件中出现了Windows.UI.Text命名空间，Windows.UI.Xaml.Data命名空间，Windows.UI.Xaml.Interop命名空间，Windows.UI.Xaml.Markup命名空间，这些命名空间大部分类与相应的Microsoft.UI.Text命名空间，Microsoft.UI.Xaml.Data命名空间，Microsoft.UI.Xaml.Interop命名空间，Microsoft.UI.Xaml.Markup命名空间提供的类和对应的方法有着相同的功能。

### Steps to reproduce the bug

For example, the Windows app sdk used in the c# project generates DLLS, including Microsoft.WinUI.dll. The Windows.UI.Text namespace, Windows.UI.Xaml.Data namespace, Windows.UI.Xaml.Interop namespace, Windows.UI.Xaml.Markup namespace, and Windows.ui.xaml.markup namespace appear in the dll file. Most of these namespace classification and corresponding Microsoft.UI.Text namespace, Microsoft.UI.Xaml.Data namespace, Microsoft.UI.Xaml.Interop namespace, The classes provided by the Microsoft.UI.Xaml.Markup namespace have the same functionality as the corresponding methods.
例如，c#工程中使用到的Windows app sdk，生成的dll中，其中包含Microsoft.WinUI.dll。该dll文件中出现了Windows.UI.Text命名空间，Windows.UI.Xaml.Data命名空间，Windows.UI.Xaml.Interop命名空间，Windows.UI.Xaml.Markup命名空间，这些命名空间大部分类与相应的Microsoft.UI.Text命名空间，Microsoft.UI.Xaml.Data命名空间，Microsoft.UI.Xaml.Interop命名空间，Microsoft.UI.Xaml.Markup命名空间提供的类和对应的方法有着相同的功能。

### Expected behavior

 The Windows.UI.Text namespace, Windows.UI.Xaml.Data namespace, Windows.UI.Xaml.Interop namespace, Windows.UI.Xaml.Markup namespace, and Windows.ui.xaml.markup namespace appear in the dll file.
The c# project uses the dll generated by the Windows app sdk project, which contains Microsoft.WinUI.dll. The dll file has the Windows.UI.Text namespace, Windows.UI.Xaml.Data namespace, Windows.UI.Xaml.Interop namespace, These classes and methods in the Windows.UI.Xaml.Markup namespace should not exist in Microsoft.WinUI.dll
c#工程使用到的Windows app sdk项目生成的dll中，其中包含Microsoft.WinUI.dll。该dll文件中出现了Windows.UI.Text命名空间，Windows.UI.Xaml.Data命名空间，Windows.UI.Xaml.Interop命名空间，Windows.UI.Xaml.Markup命名空间中的这些类和方法不应该存在在Microsoft.WinUI.dll中

### Screenshots

Microsoft.* namespace content
![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/4a33a459-c94e-47ea-b8c2-a12b7237d4ca)
Windows.* namespace content(duplicated)
![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/7c98f20c-3aa4-4716-b089-815f16031563)

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ghost1372** [comment]
Windows namespaces is for uwp era, they will be gone in v2.0 there is a open issue for it.

**Comment by Gaoyifei1011** [comment]
> Windows namespaces is for uwp era, they will be gone in v2.0 there is a open issue for it.

It is already clear that Microsoft intends to release version 1.5 in the first half of 2024, when will version 2.0 be ready
目前已经很清楚的是微软打算在2024年的上半年发布1.5版本，2.0版本什么时候准备呢

**Comment by DrusTheAxe** [comment]
>Please remove these duplicate contents.

Why?

I wouldn't expect Windows.* types to go away. Windows.* namespaces are provided inbox by Windows itself<sup>1</sup> so removing such things would be a breaking change. While deprecation and eventual deletion is possible in theory<sup>2</sup>, the backwards compatibility breakage and ecosystem impacts make this much harder than it sounds (even in the ideal of cases, which this is not).

Is this a problem? What issue are you trying to solve by removing these 'duplicates'?

<sup>1</sup> Windows.* namespaces can only be declared and provided by Windows itself. The WinRT type resolution is wired to only look at Windows for Windows.* namespaces, and MSIX packages cannot declare Windows.* types. ByDesign.

<sup>2</sup> "In theory there is no difference between theory and practice. In practice there is."

**Comment by Gaoyifei1011** [comment]
> > Please remove these duplicate contents.
> 
> Why?
> 
> I wouldn't expect Windows.* types to go away. Windows.* namespaces are provided inbox by Windows itself1 so removing such things would be a breaking change. While deprecation and eventual deletion is possible in theory2, the backwards compatibility breakage and ecosystem impacts make this much harder than it sounds (even in the ideal of cases, which this is not).
> 
> Is this a problem? What issue are you trying to solve by removing these 'duplicates'?
> 
> 1 Windows.* namespaces can only be declared and provided by Windows itself. The WinRT type resolution is wired to only look at Windows for Windows.* namespaces, and MSIX packages cannot declare Windows.* types. ByDesign.
> 
> 2 "In theory there is no difference between theory and practice. In practice there is."

The duplicate apis in Windows namespaces that I describe here are relative to apis in Microsoft namespaces, not apis that contain all Windows namespaces. For example, compared with the API of Windows.UI.Xaml.Markup in the namespace of Microsoft.UI.Xaml.Markup, the API under Windows.UI.Xaml.Markup is not used in WinUI 3
我在这里描述的 Windows 命名空间下的重复 API 是相对于 Microsoft 命名空间下的 API 的，不是包含所有的 Windows 命名空间的API，比如 Microsoft.UI.Xaml.Markup 命名空间下相对于 Windows.UI.Xaml.Markup 的 API，Windows.UI.Xaml.Markup 下的 API 在 WinUI 3 中是不会用到的

**Comment by Gaoyifei1011** [comment]
The issue seems to be resolved in Windows App SDK 1.6 and the new version of CsWinRT compatible with Native AOT, and the issue is about to be closed.
问题好像在 Windows App SDK 1.6 和新版兼容 Native AOT 的 CsWinRT 中得到解决，该 Issue 即将关闭。
https://omds.xaml.dev/WinAppSDK_v1.5_v1.6.html
