### ISSUE TITLE
Please simply wrap the DataTransferManager interop class

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#3777]
### Describe the bug

Please simply wrap the DataTransferManager interop class

At present in desktop applications, if we want to invoke DataTransferManager class methods, the need to import IDataTransferManagerInterop interface, and implement the corresponding operation in accordance with the corresponding methods, it is a bit too cumbersome. Hope future versions can be a simple packaging IDataTransferManagerInterop interface, to call DataTransferManager method in a class.
目前在桌面应用中，如果我们想要调用DataTransferManager类的方法，需要自己导入IDataTransferManagerInterop接口，并按照相应的方法实现对应的操作，这有点太繁琐了。希望未来的版本中可以简单包装一下IDataTransferManagerInterop接口，能更快的调用DataTransferManager类中的方法。

This is the code in the official example.
这是官方示例中的代码。

// MainWindow.xaml.cs
...
public sealed partial class MainWindow : Window
{
    ...
    [System.Runtime.InteropServices.ComImport]
    [System.Runtime.InteropServices.Guid("3A3DCD6C-3EAB-43DC-BCDE-45671CE800C8")]
    [System.Runtime.InteropServices.InterfaceType(
        System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]
    interface IDataTransferManagerInterop
    {
        IntPtr GetForWindow([System.Runtime.InteropServices.In] IntPtr appWindow,
            [System.Runtime.InteropServices.In] ref Guid riid);
        void ShowShareUIForWindow(IntPtr appWindow);
    }

    static readonly Guid _dtm_iid = 
        new Guid(0xa5caee9b, 0x8708, 0x49d1, 0x8d, 0x36, 0x67, 0xd2, 0x5a, 0x8d, 0xa0, 0x0c);

    private void myButton_Click(object sender, RoutedEventArgs e)
    {
        // Retrieve the window handle (HWND) of the current WinUI 3 window.
        var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);

        IDataTransferManagerInterop interop =
        Windows.ApplicationModel.DataTransfer.DataTransferManager.As
            <IDataTransferManagerInterop>();

        IntPtr result = interop.GetForWindow(hWnd, _dtm_iid);
        var dataTransferManager = WinRT.MarshalInterface
            <Windows.ApplicationModel.DataTransfer.DataTransferManager>.FromAbi(result);

        dataTransferManager.DataRequested += (sender, args) =>
        {
            args.Request.Data.Properties.Title = "In a desktop app...";
            args.Request.Data.SetText("...display WinRT UI objects that depend on CoreWindow.");
            args.Request.Data.RequestedOperation = 
                Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;
        };

        // Show the Share UI
        interop.ShowShareUIForWindow(hWnd);
    }
}
...

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/b7bfbc69-638b-49a3-a899-5d92e27b0889)

### Steps to reproduce the bug

None

### Expected behavior

Please provide a DataTransferManagerInterop static class, the class has achieved IDataTransferManagerInterop interface, and provides the corresponding interactions. The following code
请提供一个DataTransferManagerInterop静态类，这个类内部已经实现了IDataTransferManagerInterop接口，并提供了相应的交互操作。如下面的代码

    public static class DataTransferManagerInterop
    {
        private static readonly Guid riid = new Guid(0xa5caee9b, 0x8708, 0x49d1, 0x8d, 0x36, 0x67, 0xd2, 0x5a, 0x8d, 0xa0, 0x0c);

        private static IDataTransferManagerInterop dataTransferManagerInterop = DataTransferManager.As<IDataTransferManagerInterop>();

        public static DataTransferManager GetForWindow(IntPtr window)
        {
            return MarshalInterface<DataTransferManager>.FromAbi(dataTransferManagerInterop.GetForWindow(window, riid));
        }

        public static void ShowShareUI(IntPtr window)
        {
            dataTransferManagerInterop.ShowShareUIForWindow(window);
        }
    }

In this wrapped class, if we need to use the methods provided in the DataTransferManager class, we only need one line of code:
在这个包装好的类中，如果我们需要使用DataTransferManager类中提供的方法，只需要一行代码：

DataTransferManager dataTransferManager = DataTransferManagerInterop.GetForWindow(/need to input window handle/);

To display the shared window, just:
想要显示共享窗口，只需要：
DataTransferManagerInterop.ShowShareUI(/need to input window handle/);

It can be called quickly.
即可快速调用。

### Screenshots

Defined static class
定义的静态类
![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/85039322-9fbd-4c99-85ea-0b0f8bcb8228)

快速调用示例
Quick call example
![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/5af85f96-0760-46a4-a78f-5d24f1336c54)

The definition of the DataTransferManagerInterop static class reference is DisplayInformationInterop static class definition
这个DataTransferManagerInterop静态类的定义参考的是DisplayInformationInterop静态类的定义

### NuGet package version

Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

None

**Comment by JaiganeshKumaran** [comment]
Related to #1063

**Comment by zhuxb711** [comment]
通过使用Vanara.Windows.Shell提供的Win32 API包装，应当能够将其简化为以下代码。但是确实WAS应该提供官方实现。
With Vanara.Windows.Shell, you could simplify it as the following, but we need the official implement, in indeed:

```csharp
Shell32.IDataTransferManagerInterop Interop = DataTransferManager.As<Shell32.IDataTransferManagerInterop>();
Interop.GetForWindow(<Your window handle>, Shell32.IID_DataTransferManager, out IntPtr ObjectPointer).ThrowIfFailed();
DataTransferManager.FromAbi(ObjectPointer).DataRequested += (s, e) =>
{
    DataRequestDeferral Deferral = e.Request.GetDeferral();

    try
    {
        e.Request.Data = new DataPackage();
        e.Request.Data.Properties.Title = <Your file name>;
        e.Request.Data.Properties.Description = <Your file type>;
        e.Request.Data.SetStorageItems(new IStorageItem[] { <Your file that want to share> }, false);
    }
    catch (Exception ex)
    {
        e.Request.FailWithDisplayText(ex.Message);
    }
    finally
    {
        Deferral.Complete();
    }
};

Interop.ShowShareUIForWindow(<Your window handle>).ThrowIfFailed();
```

**Comment by Gaoyifei1011** [comment]
> ### Describe the bug
> Please simply wrap the DataTransferManager interop class
> 
> At present in desktop applications, if we want to invoke DataTransferManager class methods, the need to import IDataTransferManagerInterop interface, and implement the corresponding operation in accordance with the corresponding methods, it is a bit too cumbersome. Hope future versions can be a simple packaging IDataTransferManagerInterop interface, to call DataTransferManager method in a class. 目前在桌面应用中，如果我们想要调用DataTransferManager类的方法，需要自己导入IDataTransferManagerInterop接口，并按照相应的方法实现对应的操作，这有点太繁琐了。希望未来的版本中可以简单包装一下IDataTransferManagerInterop接口，能更快的调用DataTransferManager类中的方法。
> 
> This is the code in the official example. 这是官方示例中的代码。
> 
> // MainWindow.xaml.cs ... public sealed partial class MainWindow : Window { ... [System.Runtime.InteropServices.ComImport] [System.Runtime.InteropServices.Guid("3A3DCD6C-3EAB-43DC-BCDE-45671CE800C8")] [System.Runtime.InteropServices.InterfaceType( System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)] interface IDataTransferManagerInterop { IntPtr GetForWindow([System.Runtime.InteropServices.In] IntPtr appWindow, [System.Runtime.InteropServices.In] ref Guid riid); void ShowShareUIForWindow(IntPtr appWindow); }
> 
> ```
> static readonly Guid _dtm_iid = 
>     new Guid(0xa5caee9b, 0x8708, 0x49d1, 0x8d, 0x36, 0x67, 0xd2, 0x5a, 0x8d, 0xa0, 0x0c);
> 
> private void myButton_Click(object sender, RoutedEventArgs e)
> {
>     // Retrieve the window handle (HWND) of the current WinUI 3 window.
>     var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
> 
>     IDataTransferManagerInterop interop =
>     Windows.ApplicationModel.DataTransfer.DataTransferManager.As
>         <IDataTransferManagerInterop>();
> 
>     IntPtr result = interop.GetForWindow(hWnd, _dtm_iid);
>     var dataTransferManager = WinRT.MarshalInterface
>         <Windows.ApplicationModel.DataTransfer.DataTransferManager>.FromAbi(result);
> 
>     dataTransferManager.DataRequested += (sender, args) =>
>     {
>         args.Request.Data.Properties.Title = "In a desktop app...";
>         args.Request.Data.SetText("...display WinRT UI objects that depend on CoreWindow.");
>         args.Request.Data.RequestedOperation = 
>             Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;
>     };
> 
>     // Show the Share UI
>     interop.ShowShareUIForWindow(hWnd);
> }
> ```
> 
> } ...
> 
> ![image](https://private-user-images.githubusercontent.com/49179966/257705024-b7bfbc69-638b-49a3-a899-5d92e27b0889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDQxODcsIm5iZiI6MTcxMDkwMzg4NywicGF0aCI6Ii80OTE3OTk2Ni8yNTc3MDUwMjQtYjdiZmJjNjktNjM4Yi00OWEzLWE4OTktNWQ5MmUyN2IwODg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZjYwOTc2MmMzNjc3YTAxMjRiZjg0YTA5ODA4NTU5MjBhMjkzM2U2NzQ1Zjk1NDlmODVkOTEzZDQ5ZWEzZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JY7beMrtBxqshcX6sYnP5LpKdAvRtxfd-alUdtmme3o)
> 
> ### Steps to reproduce the bug
> None
> 
> ### Expected behavior
> Please provide a DataTransferManagerInterop static class, the class has achieved IDataTransferManagerInterop interface, and provides the corresponding interactions. The following code 请提供一个DataTransferManagerInterop静态类，这个类内部已经实现了IDataTransferManagerInterop接口，并提供了相应的交互操作。如下面的代码
> 
> ```
> public static class DataTransferManagerInterop
> {
>     private static readonly Guid riid = new Guid(0xa5caee9b, 0x8708, 0x49d1, 0x8d, 0x36, 0x67, 0xd2, 0x5a, 0x8d, 0xa0, 0x0c);
> 
>     private static IDataTransferManagerInterop dataTransferManagerInterop = DataTransferManager.As<IDataTransferManagerInterop>();
> 
>     public static DataTransferManager GetForWindow(IntPtr window)
>     {
>         return MarshalInterface<DataTransferManager>.FromAbi(dataTransferManagerInterop.GetForWindow(window, riid));
>     }
> 
>     public static void ShowShareUI(IntPtr window)
>     {
>         dataTransferManagerInterop.ShowShareUIForWindow(window);
>     }
> }
> ```
> 
> In this wrapped class, if we need to use the methods provided in the DataTransferManager class, we only need one line of code: 在这个包装好的类中，如果我们需要使用DataTransferManager类中提供的方法，只需要一行代码：
> 
> DataTransferManager dataTransferManager = DataTransferManagerInterop.GetForWindow(/need to input window handle/);
> 
> To display the shared window, just: 想要显示共享窗口，只需要： DataTransferManagerInterop.ShowShareUI(/need to input window handle/);
> 
> It can be called quickly. 即可快速调用。
> 
> ### Screenshots
> Defined static class 定义的静态类 ![image](https://private-user-images.githubusercontent.com/49179966/257704629-85039322-9fbd-4c99-85ea-0b0f8bcb8228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDQxODcsIm5iZiI6MTcxMDkwMzg4NywicGF0aCI6Ii80OTE3OTk2Ni8yNTc3MDQ2MjktODUwMzkzMjItOWZiZC00Yzk5LTg1ZWEtMGIwZjhiY2I4MjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMzkwOGFkYzhiZjQyZTUzMWU4YTY3YmJjYjkyYmE1YTI3YTNmOGVjMjc5NzczOTFhNzJiYWNjYTQxMzRhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.31yZglFJT9W02yWWvAcZ3k3jPYoHMUSOdWDP0w9vFHw)
> 
> 快速调用示例 Quick call example ![image](https://private-user-images.githubusercontent.com/49179966/257704696-5af85f96-0760-46a4-a78f-5d24f1336c54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MDQxODcsIm5iZiI6MTcxMDkwMzg4NywicGF0aCI6Ii80OTE3OTk2Ni8yNTc3MDQ2OTYtNWFmODVmOTYtMDc2MC00NmE0LWE3OGYtNWQyNGYxMzM2YzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAzMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNjMyNWZkOTk0Njk0MjY2MzI1NTZlZDg4YWU4NWE3MzhjOWE2Y2NiZDQwNTJjOGVmZjFmYmJiZjM5YmU3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KMzE8vWqOzFK33HlUrB9PVIZOHw1wcQIlYh_4zEuF34)
> 
> The definition of the DataTransferManagerInterop static class reference is DisplayInformationInterop static class definition 这个DataTransferManagerInterop静态类的定义参考的是DisplayInformationInterop静态类的定义
> 
> ### NuGet package version
> Windows App SDK 1.4 Preview 1: 1.4.230628000-preview1
> 
> ### Packaging type
> Packaged (MSIX)
> 
> ### Windows version
> Windows 11 version 22H2 (22621, 2022 Update)
> 
> ### IDE
> Visual Studio 2022
> 
> ### Additional context
> None

See reference https://github.com/microsoft/CsWinRT/pull/1528
