### ISSUE TITLE
SoftwareBitmap.Copy() sometimes throw InvalidCastException

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/WindowsAppSDK#3824]
### Describe the bug

SoftwareBitmap.Copy() throw InvalidCastException randomly, I could not give a certain reproducible way.

Message: 
`No such interface supported`

StackTrace: 
```
        at WinRT.IObjectReference.As[T](Guid iid)
        at WinRT.BaseActivationFactory._As(Guid iid)
        at WinRT.ActivationFactory`1.As(Guid iid)
        at Windows.Graphics.Imaging.SoftwareBitmap.Make___objRef_global__Windows_Graphics_Imaging_ISoftwareBitmapStatics()
        at Windows.Graphics.Imaging.SoftwareBitmap.get__objRef_global__Windows_Graphics_Imaging_ISoftwareBitmapStatics()
        at Windows.Graphics.Imaging.SoftwareBitmap.Copy(SoftwareBitmap source)
```

### Steps to reproduce the bug

```
using (Stream FileStream = File.Open("<Image path>"))
{
    BitmapDecoder Decoder = await BitmapDecoder.CreateAsync(FileStream.AsRandomAccessStream());
    SoftwareBitmap OriginBitmap = await Decoder.GetSoftwareBitmapAsync(BitmapPixelFormat.Bgra8, BitmapAlphaMode.Premultiplied);
    SoftwareBitmap OriginBitmapBackup = SoftwareBitmap.Copy(OriginBitmap); // Throw InvalidCastException sometimes
}
```

### Expected behavior

Should not throw InvalidCastException

### NuGet package version

Windows App SDK 1.3.3: 1.3.230724000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

(Not sure) Seems this issue disappears if debug my app with `Native Debugger`. 
(Not sure) Only this issue will only throw if debug my app with `Managed Debugger`.

**Comment by codendone** [comment]
`SoftwareBitmap` is a Windows API which is not part of Windows App SDK. I've logged an [internal bug](http://task.ms/46437758) for the team which owns SoftwareBitmap.

Closing this issue as External. If I see any useful updates to that internal bug, I'll report them here. Without a repro, I'm not sure how much they'll be able to do unless they are familiar with this type of issue.

**Comment by zhuxb711** [comment]
Thanks @codendone

**Comment by zhuxb711** [comment]
@codendone Any reponse from the team?

**Comment by codendone** [comment]
@zhuxb711 The report was acknowledged by the team, but no other progress to report.

**Comment by codendone** [comment]
The owning team wasn't able to find anything. A repro or more information is needed.

Is there any consistency around which file(s) hit this issue? If the call fails with this exception, does retrying the call make a difference (some kind of transient error)?
