### ISSUE TITLE
Missing documentation for Microsoft.WindowsAppSDK 1.4.230822000

### ISSUE THREAD

**Issue by riverar** [microsoft/WindowsAppSDK#3825]
The Windows App SDK 1.4 package went out last night without any documentation. https://www.nuget.org/packages/Microsoft.WindowsAppSDK/

Are there any known issues? What's in this release? Hello?

**Comment by belka-ew** [comment]
> Are there any known issues?

After updating the title bar of my application became unresponsive (WinUI 3, Windows 11). Moving the window with the mouse doesn't work. Double clicking on the title bar doesn't resize the window. But I haven't looked in the issue further yet.

**Comment by dotMorten** [comment]
@belka-ew This doesn't look like the right place to report this.

**Comment by riverar** [comment]
New docs are live, closing this issue.

https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel

**Comment by DarranRowe** [comment]
@belka-ew
A basic custom title bar works without issue in 1.4.
I would suggest that you test this properly and then start your own bug report.

@riverar
My guess is that it takes longer for the documentation changes to filter through the system compared to how long it takes to nuget. I'm sure that I saw around a day mentioned somewhere, but that could be my memory playing tricks on me.

**Comment by riverar** [comment]
@DarranRowe No; note the today/10:25am PST timestamp on this merge https://github.com/MicrosoftDocs/windows-dev-docs/commit/d9ef4f47ca8dc3a47b042355a78e63ead4951e0a. I think this is just a standard case of someone didn't push the button until they rolled into the office. 😂

The docs are available now, and are good quality, so it's probably best we just accept it and move on.
