### ISSUE TITLE
[.NET 8 RC1] Error NETSDK1083 "The specified RuntimeIdentifier 'win10-x86' is not recognized" displays in error list after creating a WinUI project

### ISSUE THREAD

**Issue by XamlTest** [microsoft/WindowsAppSDK#3842]
### Describe the bug

There are 3 errors in error list after creating C# WinUI project with **.NET 8 RC1**.
Errors: 
Error NETSDK1083: The specified RuntimeIdentifier 'win10-x86' is not recognized.
Error NETSDK1083: The specified RuntimeIdentifier 'win10-x64' is not recognized.
Error NETSDK1083: The specified RuntimeIdentifier 'win10-arm64' is not recognized.

From the https://github.com/dotnet/docs/issues/36527, we try to update the `<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>` to `<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>`, there still an error: The specified RuntimeIdentifier 'win10-x86' is not recognized.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/e6a8303e-71cf-4d3a-80eb-0b44ba1a73ea)

### Steps to reproduce the bug

**Steps:**
1. Install VS from [Pipelines - Run main-34029.95](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8325241&view=results) (Contains the .NET 8 RC1)
2. Create C# "Blank App. Packaged (WinUI 3 in Desktop)" project
3. Open xxx.csproj file and update the TargetFramework to "net8.0-windows10.0.19041.0"
4. Save
5. Open the Error list to check the errors.

**Actual Result:**
There are 3 errors.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/9d0f0fa6-2306-4ba9-9bce-85f5f99be317)

### Expected behavior

No errors and warnings.

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

**Environment**: 
VS version: 17.8.0 Preview 2.0 [34029.95.main]
Windows App SDK version: 1.3.230602002

**Comment by XamlTest** [comment]
@eduardobragaxz Thanks for the workaround, setting `<UseRidGraph>true</UseRidGraph>` makes it work.

**Comment by eduardobragaxz** [comment]
@XamlTest you're welcome 😀

Hey @bpulliam I think this can be closed now.

**Comment by DDHSchmidt** [comment]
> @eduardobragaxz Thanks for the workaround, setting `<UseRidGraph>true</UseRidGraph>` makes it work.

Out of curiosity: The linked guide mentions to add 
```
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
</ItemGroup>
```

to the csproj file. Thanks to your comment (which I discovered very late :/ ) I recognized I actually had to add
```
<PropertyGroup>
    <UseRidGraph>true</UseRidGraph>
  </PropertyGroup>
```
to my csproj file. At least now one of my Maui 8 RC1 app can be built again without dotnet restore|publish crashing on me.

1. How did you know this was the right property? Have I overlooked some obvious documentation?
2. Why is the wrong (?) snippet still in the docs as "Recommended action" ?

**Comment by eduardobragaxz** [comment]
That's interesting. Mine works with the suggested one.

**Comment by mklemarczyk** [comment]
Please update documentation for this new requirement. Or make it not mandatory for final release of .NET 8.
PS: It would be nice if dotnet can write that suggestion in error message, so we do not need to wonder around. :)

Ref:
- https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/wpf-plus-winappsdk

**Comment by dotMorten** [comment]
So... is there a patch incoming now that this excuse isn't valid?  From release notes:
<img width="596" alt="image" src="https://github.com/microsoft/WindowsAppSDK/assets/1378165/1ada41d4-0d14-4df0-a07a-9bee6113f750">

Any info on confirming whether this is getting any visibility for a fix, and whether a fix is planned (github has a nice milestone feature you could use to show intent), would be helpful.

**Comment by ShashankNay** [comment]
This is being addressed, the older non-portable RIDs found in the project templates and publish profiles will be replaced with generic portable RIDs. The NuGet package will also no longer contain or reference non-portable RIDs in its use of runtime libraries. These changes are scheduled for the 1.5 Experimental release.

**Comment by orosbogdan** [comment]
Same issue faced on MAUI with .NET 8.

**Comment by e012345678** [comment]
Having the same issue on .NET 8 MAUI. How to fix this?

**Comment by eduardobragaxz** [comment]
What exactly is the problem are you having? Did you guys add <UseRidGraph>true</UseRidGraph> to the project file and edited your publish profile files?

**Comment by dotMorten** [comment]
Maui should be setting UseRidGraph for you

**Comment by e012345678** [comment]
The UseRidGraph needs to be set for every single dependency class library? The problem we are having is that the code doesn't compile. It gives the error 
`C:\hostedtoolcache\windows\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(90,5): error NETSDK1083: The specified RuntimeIdentifier 'win10-x64' is not recognized.`

**Comment by eduardobragaxz** [comment]
I don't know if the folder structure is the same with MAUI, but assuming it's the same, what I did was, using file explorer, I went to my project's folder then Properties > PublishProfiles and in the files in this folder I edited the RuntimeIdentifier property from, for example, win10-x64 to win-x64.

**Comment by e012345678** [comment]
We are not using publish profiles we are using dotnet publish from command. Tried a lot of different options but cannot get this to work in .NET 8. Getting this error:
`error : Packaged .NET applications with an app host exe cannot be ProcessorArchitecture neutral. Please specify a RuntimeIdentifier or a Platform other than AnyCPU. `

Getting this despite setting `-r:win-x64`as argument to dotnet publish

**Comment by eduardobragaxz** [comment]
Oh my bad.

**Comment by Gavin-Williams** [comment]
Why would we set use RID graph to true - isn't the point of this to remove the use of RID graphs? This is a horrible situation. Why should we have to do <arcane manipulations> to make our projects work? I do expect to be able to switch to .net 8 and my projects 'just work'.

**Comment by e012345678** [comment]
How we go forward with this right now? We cannot build our project for .NET 8 due to this error. Should we set `<UseRidGraph>true</UseRidGraph>` for every single class library and dependency?

**Comment by dotMorten** [comment]
Yes. Or set in once in your Directory.build.props file

**Comment by abenadar** [comment]
I used this workaround in a cross-platform class library. It shut off the initial error but now I receive another:

```
NETSDK1082	There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm'.	
NETSDK1082	There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm-aot'.	
```

**Comment by Mogikan** [comment]
Maybe it should work by default without adding line to fix compilation error. `<UseRidGraph>true</UseRidGraph>`
Sounds stupid, like adding a line FixCompilationBug true.

**Comment by Arlodotexe** [comment]
The Windows Community Toolkit is running into this issue when adding a `net8.0-windows10.0.22621.0` MultiTarget. Even after enabling `UseRidGraph`, we're still seeing:
```
C:\Program Files\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1082: There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm'.
C:\Program Files\dotnet\sdk\8.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(491,5): error NETSDK1082: There was no runtime pack for Microsoft.NETCore.App available for the specified RuntimeIdentifier 'win10-arm-aot'.
```

It's notable that we aren't defining `win10-arm` or `win10-arm-aot` anywhere in our project. All instance of the string `win10-*` was changed to `win-*` in [this commit](https://github.com/CommunityToolkit/Windows/commit/d03cc9b8129b74f046b2ff22bc4a30c9aedfdc69), and the binlog shows the RuntimeIdentifiers still being defined as:
```
RuntimeIdentifiers = win10-arm;win10-arm-aot;win10-arm64-aot;win10-x86;win10-x86-aot;win10-x64;win10-x64-aot
```

Single-project binlog: [CommunityToolkit.WinUI.Converters_Debug_AnyCPU_Build_2024-01-10T18_40_33.4371927-06_00.zip](https://github.com/microsoft/WindowsAppSDK/files/13906539/CommunityToolkit.WinUI.Converters_Debug_AnyCPU_Build_2024-01-10T18_40_33.4371927-06_00.zip)

Can be reproduced at commit [`d03cc9`](https://github.com/CommunityToolkit/Windows/commit/d03cc9b8129b74f046b2ff22bc4a30c9aedfdc69) on the repo/branch [CommunityToolkit/upgrade/wasdk/net8-windows](https://github.com/CommunityToolkit/Windows/tree/upgrade/wasdk/net8-windows)

**Comment by kmgallahan** [comment]
@Arlodotexe @bpulliam A potential cause is that dependencies work their runtime targets into WinUI 3 library `*.deps.json` files like so:

``` json
Microsoft.Graphics.Win2D/1.0.0.30": {
  "runtime": {
    "lib/net5.0-windows10.0.18362.0/Microsoft.Graphics.Canvas.Interop.dll": {
      "assemblyVersion": "1.0.26.0",
      "fileVersion": "1.0.26.0"
    }
  },
  "runtimeTargets": {
    "runtimes/win10-arm64/native/Microsoft.Graphics.Canvas.dll": {
      "rid": "win10-arm64",
      "assetType": "native",
      "fileVersion": "1.0.0.0"
    },
    "runtimes/win10-x64/native/Microsoft.Graphics.Canvas.dll": {
      "rid": "win10-x64",
      "assetType": "native",
      "fileVersion": "1.0.0.0"
    },
    "runtimes/win10-x86/native/Microsoft.Graphics.Canvas.dll": {
      "rid": "win10-x86",
      "assetType": "native",
      "fileVersion": "1.0.0.0"
    }
  }
},

...

Microsoft.WindowsAppSDK/1.4.231115000": {
  "dependencies": {
    "Microsoft.Windows.SDK.BuildTools": "10.0.22621.2428"
  },
  "runtime": {
    ...
  },
  "runtimeTargets": {
    "runtimes/win10-arm64/native/Microsoft.WindowsAppRuntime.Bootstrap.dll": {
      "rid": "win10-arm64",
      "assetType": "native",
      "fileVersion": "1.4.0.0"
    },
    "runtimes/win10-x64/native/Microsoft.WindowsAppRuntime.Bootstrap.dll": {
      "rid": "win10-x64",
      "assetType": "native",
      "fileVersion": "1.4.0.0"
    },
    "runtimes/win10-x86/native/Microsoft.WindowsAppRuntime.Bootstrap.dll": {
      "rid": "win10-x86",
      "assetType": "native",
      "fileVersion": "1.4.0.0"
    }
  }
},
```

This is causing the following warning for me on build:

```
C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(284,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.Graphics.Win2D, Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

So even the WASDK package isn't setup or being consumed correctly during build yet.

**Comment by ShashankNay** [comment]
@kmgallahan 

The reason we have retained the older non-portable RIDs in the current version is to avoid introducing a breaking change in a servicing release for users who are simply upgrading their NuGet package version.
 
In an upcoming minor release we will be aligning more closely with the .NET 8 standards. This means that the older, non-portable RIDs will be phased out in favor of the more general, portable RIDs as per the .NET 8 guidelines

**Comment by dotMorten** [comment]
It really shouldn't be a breaking change, since for instance a `win10-x64` RID would automatically include any `win-x64` resources as well and that applies for .NET 6 as well. 

However, I can understand wanting to keep changes at a minimum in a patch release, and if it was between this quick-fix or waiting for 1.5.0 which it was initially promised for, I'm more than happy with the current temporary quick-fix.

**Comment by bpulliam** [comment]
This is in 1.5 and can be confirmed in preview 1

**Comment by Diegorro98** [comment]
I'm having also this error, but in this case, the error happens at dependabot when tries to update a project with `<TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>`. See dependabot/dependabot-core#9099

**Comment by dylanh724** [comment]
Hmm, so how to resolve this?

**Comment by mklemarczyk** [comment]
No issue found on last release Visual Studio 2022, .NET SDK 8.0.300

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Trogon.ColumbaLivia</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
  </PropertyGroup>
```

Be aware that `win10-x86` is not longer a valid runtime identifier, any win10- prefix need to be changed to win-
Compiler prints a information about it in the output.

**Comment by ShashankNay** [comment]
@karmeye can you provide a repro if possible? What version of the Windows App SDK are you using in your project?

**Comment by kmgallahan** [comment]
@karmeye Your first comment points out which library is causing the issue: `Affected libraries: Microsoft.Graphics.Win2D`. Only the maintainers of the lib can resolve the issue, unless WASDK changes how `*.deps.json` is made https://github.com/microsoft/WindowsAppSDK/issues/3842#issuecomment-1887906059.
