### ISSUE TITLE
.NET 8 RC1 can not compile with Windows app sdk and CsWinRT

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#3851]
### Describe the bug

.NET 8 RC1 can not compile with Windows app sdk and CsWinRT

In.net8 RC1, the Marshal.QueryInterface() method is defined from
public static int QueryInterface (IntPtr pUnk, ref Guid iid, out IntPtr ppv);
Become a
public static int QueryInterface (IntPtr pUnk, in Guid iid, out IntPtr ppv);
Please update the content in WinRT.cs immediately, otherwise the application will not compile

### Steps to reproduce the bug

In describe bug

### Expected behavior

In describe bug

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/6e70d625-fb75-49dc-9a31-6a1c72559a29)

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by manodasanW** [comment]
Addressed by https://github.com/dotnet/runtime/issues/91981
