### ISSUE TITLE
XAML mini toolbar button is unclickable on apps with custom title bar

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#3865]
### Describe the bug

Using `AppWindow.TitleBar.ExtendsContentIntoTitleBar = true;` makes the XAML button to be unclickable. Please see the steps for more info. Thanks!

### Steps to reproduce the bug

1. Create a new project:
    1.1.  ![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/087f5f50-ff95-4ac4-86c8-26b26e56a51e)
    1.2. Any project name will do.
2. Once the project is created, hit F5. You will see that the small XAML button in the upper-middle of the app window is clickable.
![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/dfa75515-ec92-43e2-b070-80943f6257ef)
3. Stop the debugging and go to MainWindow.xaml file.
    3.1. Delete the <StackPanel>
    ![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/ec435108-afb1-41a7-b6da-42b5f29fe6bd)
    3.2. Replace it with this:
    `<Grid>`
    `    <Grid.RowDefinitions>`
    `        <RowDefinition Height="32" />`
    `        <RowDefinition Height="*" />`
    `    </Grid.RowDefinitions>`
    
    `    <!--  Custom title bar  -->`
    `    <Grid`
    `        x:Name="AppTitleBar"`
    `        Grid.Row="0"`
    `        Background="DeepSkyBlue">`
    `        <FontIcon`
    `            Margin="5,0,0,0"`
    `            HorizontalAlignment="Left"`
    `            Glyph="&#xE735;" />`
    `        <TextBlock`
    `            Margin="30,0,0,0"`
    `            HorizontalAlignment="Left"`
    `            VerticalAlignment="Center"`
    `            Text="SAMPLE TITLE BAR TEXT" />`
    `    </Grid>`
    `    <!--  Custom title bar  -->`
    
    `    <StackPanel`
    `        Grid.Row="1"`
    `        HorizontalAlignment="Center"`
    `        VerticalAlignment="Center">`
    `        <Button`
    `            x:Name="myButton"`
    `            Click="myButton_Click"`
    `            Content="Click me" />`
    `    </StackPanel>`
    `</Grid>`
4. On MainWindow.xaml.cs file, inside the MainWindow() constructor, under the `this.InitializeComponent();` line, type `AppWindow.TitleBar.ExtendsContentIntoTitleBar = true;`
5. Build and run the project. You should see an app window identical to this:
![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/7a351308-ad10-48c5-b9cd-202957b0759e)
6. Try to click on the same "XAML Button Thing", you will notice that it is unclickable and does absolutely nothing.

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ghost1372** [comment]
i think you should report this to visual studio team

**Comment by DJRM2021** [comment]
Just an update, the Visual Studio team has implemented an internal fix for this issue and it's pending release.
[link](https://developercommunity.visualstudio.com/t/XAML-mini-toolbar-button-is-unclickable-/10470387)
