### ISSUE TITLE
Broken aka.ms link to 1.4 latest

### ISSUE THREAD

**Issue by KarelChanivecky** [microsoft/WindowsAppSDK#3868]
### Describe the bug

The link for the latest 1.4 build is broken: https://aka.ms/windowsappsdk/1.4/latest/windowsappruntimeinstall-x64.exe

This is the link used by the big button in the latest downloads page:
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads
![image](https://github.com/microsoft/WindowsAppSDK/assets/46802352/b973ff37-4866-4c7e-a192-bfb5eb52aca4)

Incidentally, it is also the link we use in the installer for our application. We had to move from v1.3 to 1.4 after the 1.3 installer stopped working also due to broken links....

### Steps to reproduce the bug

1. go to 
2. Click the "Download the latest x64 stable installer" button

You are redirected to: https://www.bing.com/?ref=aka&shorturl=windowsappsdk/1.4/latest/windowsappruntimeinstall-x64.exe

### Expected behavior

The latest installer is downloaded

### NuGet package version

None

**Comment by kythant** [comment]
My apologies. This issue should be fixed now. There was some downtime transitioning over to the next patch.
