### ISSUE TITLE
Drag and drop in elevated process is still not supported

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/WindowsAppSDK#3921]
### Describe the bug

COMException:  Drag start failed. If this is an elevated process, drag/drop is currently not supported there

### Steps to reproduce the bug

1. Create an elevated process
2. Drag or drop any element

### NuGet package version

Windows App SDK 1.4.2: 1.4.231008000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
Closing this as duplicate to track this here: microsoft/microsoft-ui-xaml#7690
