### ISSUE TITLE
Windows App SDK not installing in windows docker image

### ISSUE THREAD

**Issue by amrutha95** [microsoft/WindowsAppSDK#3922]
### Describe the bug

The SDK is not installing inside windows docker images. Error is in the screenshot below.

### Steps to reproduce the bug

1. Create a Dockerfile with the following contents
 ```
FROM mcr.microsoft.com/windows:20H2 AS build
WORKDIR app

RUN powershell  Invoke-WebRequest -URI https://aka.ms/windowsappsdk/1.4/1.4.231008000/windowsappruntimeinstall-x64.exe -OutFile ./downloadwinappsdk.exe
RUN powershell .\downloadwinappsdk.exe -q

# Start PowerShell when the container starts.
CMD ["powershell", "Start-Sleep", "-s", "3600"]
```
2. Build the dockerfile. (Run "docker build -t test in the directory where the Dockerfile is stored)

### Expected behavior

SDK should install successfully

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/22471775/ef061a1b-5536-40b5-8f06-b3da0816b776)

### NuGet package version

Downloaded exe for version 1.4

### Windows version

Windows 10 version 20H2 (19042, October 2020 Update)

**Comment by DrusTheAxe** [comment]
MSIX isn't supported in Docker containers.

This is a Windows issue, not WinAppSDK (whether you run `WindowsAppRuntimeInstaller.exe` or directly install WinAppSDK's MSIX packages you'll get errors).

+@cwruss @dianmsft for visibility and vFuture consideration

**Comment by amrutha95** [comment]
Update: I was able to create a new user and then tried to install the MSIX as that user, but still ran into the same error. 
<img width="1040" alt="image" src="https://github.com/microsoft/WindowsAppSDK/assets/22471775/e6515486-aef4-452d-b36c-fa4607fcb618">

Adding @nmetulev @michael-hawker for visibility
