### ISSUE TITLE
Windows App SDK and socks proxy

### ISSUE THREAD

**Issue by fxzxmicah** [microsoft/WindowsAppSDK#3929]
It seems that Windows App SDK only supports socks4 and not socks5? Can anyone confirm that? I am not a developer, but I found this phenomenon on my computer.

**Comment by fxzxmicah** [comment]
At the very least, search in taskbar and Microsoft Store do not support socks5.

**Comment by bpulliam** [comment]
WinAppSDK and socks are indepndent of each other - it is neither supported or unsupported.

**Comment by fxzxmicah** [comment]
So, what is the reason why applications based on the Windows App SDK do not support Socks5?

**Comment by Scottj1s** [comment]
@fxzxmicah Can you elaborate on the SOCKS5 support you want from Windows App SDK?  Proxies are transparent to network connections.  Are you looking for a SOCKS5 management API?

**Comment by fxzxmicah** [comment]
@Scottj1s I just want to figure out what caused taskbar searches, Microsoft Store, and some other WindowsAppSDK based or UWP applications not to support Socks5 proxies. I don't know if this is related to the WindowsAppSDK or if it's just caused by Windows itself.

**Comment by jonwis** [comment]
@keith-horton or @aschoorl  can you help redirect?

**Comment by yesayi-hovnanyan** [comment]
@fxzxmicah, Windows WinINet and WinHTTP stacks support only the SOCKS4 Proxy protocol.

**Comment by fxzxmicah** [comment]
@yesayi-hovnanyan Fine. In 2023, this is indeed too outdated.
