### ISSUE TITLE
C++ templates should be updated to avoid calling InitializeComponent from constructors

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/WindowsAppSDK#3930]
### Describe the bug

With [this fix](https://github.com/microsoft/cppwinrt/pull/1130), the C++/WinRT templates were updated.  The C++ Windows App SDK templates should be similarly updated.

### Steps to reproduce the bug

1. Create new C++ project from WinAppSDK template.
2. Xaml constructors call InitializeComponent directly, which is unsafe.

### NuGet package version

Windows App SDK 1.4.2: 1.4.231008000

### Packaging type

Unpackaged

### Windows version

Windows 10 version 1809 (17763, October 2018 Update)

### IDE

Visual Studio 2022

**Comment by JaiganeshKumaran** [comment]
Already done in 1.4 stable? See #3745.

**Comment by DarranRowe** [comment]
@JaiganeshKumaran
Since the extension stopped being distributed independently of Visual Studio, the project templates are updated inline with Visual Studio itself. I only see this change in the 17.8 previews, 17.7.6 creates projects with the InitializeComponent call.

**Comment by LegendaryBlair** [comment]
Already fixed in VS project template (VS version >= 17.8), hence close the issue.
