### ISSUE TITLE
Implementing ShareTarget API opens 'Ghost'/Empty Unknown Window

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/WindowsAppSDK#3941]
### Describe the bug

Looking at the [Share Target API](https://learn.microsoft.com/en-us/windows/uwp/app-to-app/receive-data), it's hard to translate the UWP docs to the Windows App SDK, which leads to unexpected issues implementing the contract.

The [rich activation docs](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation) seem to indicate that any of these activation types should be supported, but don't cover this specific scenario. Similar to the [app instancing docs](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-instancing). They also have no C# examples for these concepts.

Using [my WinUI2/3 template](https://github.com/michael-hawker/WinUI2Plus3Template), I setup this scenario and have it working fine in UWP, but with what I have with the similar APIs in the Windows App SDK, results in an extra blank window:

![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/b380aa65-6aec-45ba-86e7-d401f9648f38)

Compared to UWP:

![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/b06843ee-74ba-496f-90fa-ae4aa4fa5514)

It's unclear if additional steps are required upon app activation in the Windows App SDK to use the same window instance being created by the Share API? Or if that's what's happening...

In UWP, the activation path is separate, but the developer follows the same idea of setting the Window's content. In the Windows App SDK space, the Window is normally created by the `OnLaunched` method...

### Steps to reproduce the bug

[WindowsShareExample.zip](https://github.com/microsoft/WindowsAppSDK/files/13273576/WindowsShareExample.zip)

1. Unzip the attached project
2. Build, deploy, and launch (without debugging) the UWP version of the app.
3. Build, deploy, and launch the WinAppSDK version of the app.
4. In the WinAppSDK app, type in the textbox and click on Share:
![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/bae582dc-7fcc-4bc8-bd4f-ab2fa95bd150)
5. Click on the UWP version of the app as the share target:
![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/119c2063-1e84-4142-9c21-d4fb599c9727)
6. You should see a new instance of the UWP app open with the received data (you can close this new window):
![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/0e81dd26-1c8e-4db6-be33-7dc7dc33c7da)
7. Repeat steps 4-6 but starting from the UWP app and selecting the WinAppSDK app as the target:
![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/ff0cc4d7-4606-428b-8d29-03abb9a07641)

![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/5912cd7f-2809-48d0-bb24-e7dbaac456c7)

See that the share data can be retrieved, but there is a 'ghost' window that was opened instead of our app taking ownership of that:
![image](https://github.com/microsoft/WindowsAppSDK/assets/24302614/f4fac8bd-905f-46f8-9163-2adbb7fab1d8)

I only see one activation event of the app for the Windows App SDK without an existing Window and with the share data, so it's unclear what's required here of a developer or if this is something unique to the hand-off required with a Windows App SDK app.

### Expected behavior

Able to implement ShareTarget API without extra empty Window, either replacing it or filling it with content, or something...

### NuGet package version

Windows App SDK 1.4.2: 1.4.231008000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Possibly Related Issues:
- https://github.com/microsoft/WindowsAppSDK/issues/3777
- https://github.com/microsoft/WindowsAppSDK/issues/2174

**Comment by DarranRowe** [comment]
I know it is a silly suggestion, but have you tried caching the instance of AppInstance in your Application class, and then registering the [Activated](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applifecycle.appinstance.activated?view=windows-app-sdk-1.4#microsoft-windows-applifecycle-appinstance-activated) event?
I know the documentation implies that you need to use the unpackaged "RegisterForxxxActivation" members of ActivationRegistrationManager, but the [rich activation documentation](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation#activation-details-for-packaged-apps) states:
"Packaged apps will always receive activation event arguments in their AppInstance.Activated event handler, and also have the option of calling AppInstance.GetActivatedEventArgs."
While this is a contradiction in the documentation, it also implies that this takes the place of CoreApplicationView.Activated or Windows.UI.Xaml.Application.OnShareTargetActivated.

**Comment by itonx** [comment]
@DarranRowe  Register the Activated event is not doing any difference. The result is the same even if you code your application to be a single or multi instance.

Current result for single-instance: You avoid to open a new instance of your application but the blank window appears.
Current result for multi-instance: Both the blank window and a new instance of your application appear.

@michael-hawker This seems to be a bug. I found a similar issue two days ago while working in a .NET MAUI application [see here](https://github.com/dotnet/maui/issues/18536). Notice that the blank window is not blank at all, it is showing the splash image for some reason, I described that in the related issues.

Also, same result for WinUI3. I just opened an issue with the steps for WinUI3 [here].(https://github.com/microsoft/WindowsAppSDK/issues/3943).

cc: @mattleibow

**Comment by DarranRowe** [comment]
Okay, finally, do you get the same result if you use Windows.ApplicationModel.AppInstance to handle the request instead? Yes, this is usable in a desktop application.
I feel that this is an important question because the Windows App SDK app lifecycle functionality should be built upon the inbuilt Windows activation functionality. So that window could be Explorer or something else waiting for the UWP activation signals which don't occur in any desktop application. That reminds me, is it a child or owned by Explorer?
Finally, I doubt that WinUI 3 or MAUI is even relevant here. I would guess that if you did the same thing in a packaged Windows API, Windows Forms or WPF application then the result would currently be the same.

**Comment by itonx** [comment]
@DarranRowe 

do you get the same result if you use Windows.ApplicationModel.AppInstance to handle the request instead? 

Single-instance application is the answer to this question. As I mentioned before, it's not doing any difference.
In a nutshell: same result.

Details:
By default,  Windows App SDK is multi-instance and so WinUI3 & .NET MAUI Windows platform apps (app instancing & app lifecycle stuff [here](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-instancing)). You turn the app into a single-instance by using Windows.ApplicationModel.AppInstance and the Activated event to handle the activation in the first instance created. Something like this (based on C++ example in the app lifecycle link):

```csharp
public App()
{
      if (AppInstance.GetInstances().Count > 1)
      {
          var app = AppInstance.GetInstances().Where(app => app.IsCurrent == false).First();
          var eventArgs = AppInstance.GetCurrent().GetActivatedEventArgs();
          Task.Run(async () =>
          {
              await app.RedirectActivationToAsync(eventArgs); //triggers the Activated event
          });
          Environment.Exit(0); //prevent multi-instance
      }
      InitializeComponent();
      //more code
     //...................
     //Registering the Activated event
     AppInstance.GetCurrent().Activated += App_Activated;
}

private void App_Activated(object? sender, AppActivationArguments e)
{
    if(e.Kind == ExtendedActivationKind.ShareTarget)
    {
        //do something in the first instance created...
    }
}
```

_is that window a child window of or owned by Explorer?_
I believe you're taking about Windows Explorer, right?
@michael-hawker's example is kind of different from mine. He's using the share target from his UWP to his WindowsAppSDK app. In the issues I opened, my example is from a Windows file to my WindowsAppSDK app.
Not sure if his results are different from mine (talking about the child window).

Here are the observations for my example:
Although you can't see the new window as a child in the task manager, the Windows Explorer folder/window where you selected the file gets blocked by the additional window. When I say _block_ I mean that you can't navigate/use the Windows Explorer folder/window where you selected the file while the additional window is being displayed. 
 
Before the additional window for single and multi instance:
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/48b9d39c-12fb-4304-a249-a8faa9f2bf62)

After the additional window for single-instance:
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/413252dd-d627-46d3-8045-ea5ba9846ca3)

After the additional window for multi-instance:
![image](https://github.com/microsoft/WindowsAppSDK/assets/47309081/7d7781d1-ce56-4b51-a367-ca9b26ae7426)

If WinUI3 or MAUI is not relevant here it's ok, I just provided all I've found until now. Hope someone else finds this useful while the issue remains.

Trying to find a workaround but not good results until now...

**Comment by castorix** [comment]
> Trying to find a workaround but not good results until now...

If you just want to share data between instances of an application a simple way is with _MemoryMappedFile_

**Comment by itonx** [comment]
@castorix That could be a workaround for @michael-hawker.

My app should be able to read files using the Share Windows context menu option. It's already doing but every time I share a file the other window is being displayed.

**Comment by DarranRowe** [comment]
Then let's take this outside of the realm of maybes and what ifs.
I have adapted a Windows API application to register for sharing. It doesn't have the Windows App SDK loaded at all, meaning that it exclusively uses Windows.ApplicationModel.AppInstance to handle this.

https://github.com/microsoft/WindowsAppSDK/assets/52577874/06cb3e9e-7ca5-4d72-9595-ac265bf5627c

What's more, that window which appears is owned by the explorer window.

https://github.com/microsoft/WindowsAppSDK/assets/52577874/0dc017f7-589f-4d3e-b707-70dae846510c

That explorer window is not being activated.

This hasn't implemented single instancing yet, but I don't feel the need to here. When a desktop application is packaged, single instancing basically means you look for any existing instances and redirects. This shows up for the first instance of the application.

**Comment by kmahone** [comment]
I took a look at this. To make the dummy window disappear you can call `ShareOperation.ReportCompleted();` once you have copied the data.


Here is code that worked well for me:
```
    protected override async void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
    {
        var text = string.Empty;

        var activationArguments = Windows.ApplicationModel.AppInstance.GetActivatedEventArgs();
        if(activationArguments.Kind == ActivationKind.ShareTarget)
        {
            ShareTargetActivatedEventArgs shareArgs = activationArguments as ShareTargetActivatedEventArgs;
            shareArgs.ShareOperation.ReportStarted();

            if (shareArgs.ShareOperation.Data.Contains(StandardDataFormats.StorageItems))
            {
                var storageItems = await shareArgs.ShareOperation.Data.GetStorageItemsAsync();
                text = string.Join(", ", storageItems.Select(item => item.Path));
            }

            shareArgs.ShareOperation.ReportCompleted();
        }

        Window = new MainWindow();
        Frame rootFrame = Window.Content as Frame;
        rootFrame.Navigate(typeof(MainPage), text);
        Window.Activate();
    }
```

Ideally the 'dummy' window would not show up at all. But it is not the WinAppSDK app process that is showing that window. It is the explorer.exe process. So there is nothing that the WinAppSDK app can do to prevent it from showing.

So it would be an update to Windows itself to make the window not show at all. We are tracking that issue internally.

But even without that change, as long as you call `ReportCompleted()` you get a reasonable experience.
