### ISSUE TITLE
WebView2 control now throwing exception when application is closed

### ISSUE THREAD

**Issue by johnt-star** [microsoft/WindowsAppSDK#3977]
### Describe the bug

Note that this may have been introduced in a recent update as this once worked properly.

Running an application with WebView2 control will throw an exception when the application is closed.

![image](https://github.com/microsoft/WindowsAppSDK/assets/77626323/62501a5a-dcfe-469a-9784-182c84d643e0)

### Steps to reproduce the bug

1.  Create a new project in VS using the Blank App (WinUI 3 in Desktop) template.
2.  In MainWindow.xaml, replace the contents of StackPanel with the contents shown in screen grab below
![image](https://github.com/microsoft/WindowsAppSDK/assets/77626323/670eaa2b-1f3d-471e-8eab-11a5e3aeb592)
3. Start app and ensure the web page is displayed
4. Close the application

At this point exception will occur.

### Expected behavior

Exception should not occur on shutdown.

### Screenshots

As shown above, following exception occurs upon closing app:

![image](https://github.com/microsoft/WindowsAppSDK/assets/77626323/f5f3e1ba-cdfa-4e6a-b10c-fcfa53ae92f0)

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Project files:
[WebView.zip](https://github.com/microsoft/WindowsAppSDK/files/13404748/WebView.zip)

**Comment by EmmettTsai** [comment]
Try this
https://github.com/microsoft/microsoft-ui-xaml/issues/6872

**Comment by johnt-star** [comment]
Thanks for the link!

Calling Close on WebView2 now prevents exception upon close
