### ISSUE TITLE
AppxManifest XSD schemas are missing

### ISSUE THREAD

**Issue by mikehearn** [microsoft/WindowsAppSDK#4011]
### Describe the bug

It would be great if this repository had an _automatically synced_ copy of the AppxManifest XSD schemas. New schemas are introduced all the time as the Windows platform evolves, but the only place on the internet that seems to have the schemas is the https://github.com/microsoft/msix-packaging repository which hasn't been updated for two years. Apparently the sync process is fully manual and not done on a schedule.

These files clearly exist inside Microsoft. Some of us do use them to validate our manifests! They're not sensitive and already open sourced elsewhere, so why not open source them properly so we can always get up to date copies?

Ideally they'd be served from the namespace URLs of course but presumably there's some complicated reason why that's not easy.

### Steps to reproduce the bug

1. Search for AppxManifest schemas for new namespaces.
2. Discover they aren't public.
3. Wonder how to validate schemas outside of using the MakeMsix tool (which I don't always want to do for various reasons).

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Other

**Comment by DarranRowe** [comment]
I think, currently, the best place to grab these from would be the [Windows SDK Build Tools NuGet package](https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools/10.0.22621.2428). That is assuming you don't want to get the entire SDK.
The big issue is that the preview versions haven't been updated in 3 months. The latest versions of Windows are 26002 for Canary and 23595 for Dev. However, the latest versions on NuGet are 25936 for Canary and 23531 for Dev.

**Comment by mikehearn** [comment]
Hey, thanks! That seems useful. Oddly though, the schemas in that build tools package seem incomplete (as well as out of date)? They don't match the files in the github repo or the `AppxPackaging.dll` file. Odd that there are different schemas out there...

**Comment by DarranRowe** [comment]
The schemas are not out of date. The schemas are associated with a version of Windows though. If you notice, I did link directly to 10.0.22621.2428, which is the latest release version of the Windows SDK. This was released in October (24th October to be exact).
These schema files match the versions in the Windows SDK exactly. But if you say that the Build Tools version is incomplete, then it is possible that the package only contains enough to validate the core UWP manifest.
The 10.0.22621.2428 NuGet packages do not contain any of the preview schemas. As an example, UAP 16 and 17 are not available in Windows 11 22H2 (this includes the 23H2 update). This means the Windows 11 22H2 SDK (10.0.22621.xxxx) only includes the schemas for features only available in that version of Windows.
If you want the latest additions then you would have to switch to the latest preview version. That is 10.0.25936-preview currently. This does have the schemas for the latest preview features, including UAP 16 and 17, Desktop 9 - 11 and more. I would have to double check the latest preview SDK, but these should currently be complete.

**Comment by mikehearn** [comment]
Thanks. I've written a script to extract them from AppxPackaging.dll which should, in theory, be the "ground truth" as long as the DLL used as a source is new enough. And it seemed like there are far more schemas in that than in the SDK, but it may be that some are obsolete, or the layout is different. Thanks for your advice, it's much appreciated. I'll take a look at what the best way to get these is.

**Comment by mikehearn** [comment]
Right. The XSDs from the DLL match the ones uploaded to the https://github.com/microsoft/msix-packaging/ repository (with the codename and split comments).

I think the problem we face is that we need to make MSIX packages that are compatible with as many versions of Windows as possible, whereas the SDK seems to assume that you only target a specific version. Like, if Win10 schema has one way to do something, and Win11 schema has a better way, then the answer is we have to use both ways for many years going forward because Win11 is not a straight upgrade on 10 and so many users are still stuck on 10 or choosing to stay there, and will do for quite a long time. Also some users seem to get stuck on old Win11 versions. For example, I have a Windows 11 VM that wouldn't upgrade past 21H2 ... it just told me it was fully up to date in the Windows Update screen, even though it wasn't. It was up to date with the 21H2 stream, yes, but seemed to be stuck in a 2021 timewarp. To resolve that I had to manually download some Win11 installer from Microsoft and run it, but I don't know why this was necessary.

So basically, in an ideal situation there'd be one set of schemas, centrally available somewhere (an SDK zip is fine), but it would be a single schema that defined every element that had ever been used. Only additions, no removals.

The SDK doesn't provide this but extracting the schemas from the DLL does, because now you can validate for every version of Windows simultaneously, which reflects the reality that you have users on every version of Windows simultaneously.

For anyone else who finds this thread and faces the same issue, here are some tips:

* You can extract the resources on non-Windows machines using `wrestool` from `icotools` (this is available via homebrew), e.g. `wrestool -x -a --raw -o resources AppxPackaging.dll` and then look for the files that match the glob `*_500_*`.
* Some of the schemas are buggy, or do things that only validate on MSXML. For example the schema for publisher bridging (2021) uses a type without specifying the corresponding `<xs:import>` tag. Presumably MSXML allows this but the spec doesn't.
* Likewise, if you're not validating on MSXML you may encounter problems with regular expressions that use features not in the canonical XSD spec (just comment them out) or `maxOccurs` and pathologically slow validation times, you can just replace any `maxOccurs > 1000` with `unbounded` to fix that.

Once you have those fixed files you can load them into an XSD validation engine keyed by namespace and then validate manifests that use a mix of features for different Windows versions.

**Comment by riverar** [comment]
I brought this up with the AppInstaller folks years ago and they weren't even aware their schemas were shipping with `AppxPackaging.dll` 😂. I just yank them out of the file like you.
