### ISSUE TITLE
Unnecessary dependency to MS Defender

### ISSUE THREAD

**Issue by StenApp** [microsoft/WindowsAppSDK#4013]
### Describe the bug

Without the folder C:\ProgramData\Microsoft\Windows Defender
I get 0x80070057 - Errors when updating store apps.
Smartscreenps.dll must also be there.

### Steps to reproduce the bug

Disabling files of defender ( I want to ger rid of it/ uninstall it/ disable it completely) breaks half of windows 11, start menu, search in taskbar and notification center 

### Expected behavior

Apps that use appSDK work without the need of defender files or folder being there!

### NuGet package version

None

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Other

### Additional context

I use Win 11 23H2
I used update ms store apps

**Comment by StenApp** [comment]
https://github.com/ionuttbara/windows-defender-remover/issues/81#issue-1857955728

**Comment by StenApp** [comment]
https://github.com/ionuttbara/windows-defender-remover/issues/98#issue-1965319196

**Comment by StenApp** [comment]
https://github.com/ionuttbara/windows-defender-remover/issues/83#issue-1861327793

**Comment by riverar** [comment]
Not relevant to Windows App SDK, your only option is to file Windows Defender feedback in Feedback Hub.

**Comment by hez2010** [comment]
It is the smartscreen component that checks the source and certification of applications. 
Even if you want to completely turn off/uninstall the Defender you shouldn't remove the smartscreen component as it's being used by a large variant from 1st to 3rd party applications.

**Comment by DrusTheAxe** [comment]
>It is the smartscreen component that checks the source and certification of application installation packages.
>
>Not relevant to Windows App SDK, your only option is to file Windows Defender feedback in Feedback Hub.

+1

This is an OS issue, not WinAppSDK. Please share your feedback via the Feedback Hub app.
