### ISSUE TITLE
HTTP Error 500 when sending a notification throught Windows Notification Server

### ISSUE THREAD

**Issue by Diegorro98** [microsoft/WindowsAppSDK#4015]
### Describe the bug

Months ago I followed these [instructions for push notifications](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push-notifications/push-quickstart) and everything worked fine. I was able to create a notification channel,  successfully request an access token, and send a raw notification.

Now I can do everything but sending the notification. I get an 500 HTTP error. Also if force the app to expire the channel by creating a new one (so 410 error should appear) I get the same 500 HTTP error.

The HTTP response doesn't return any relevant info in the headers.

There isn't many information about this issue, but docs at [Troubleshooting push notifications](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push-notifications/troubleshooting#:~:text=500%20Internal%20Server,area%2DNotifications%20label.) mentions that I should report this issue here.

### Steps to reproduce the bug

Follow the steps from [Quickstart: Push notifications in the Windows App SDK](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push-notifications/push-quickstart)

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

The only thing that has changed since last time that it worked is the Azure subscription, which back on days was an Azure free month subscription (I got it just to test Windows push notifications).

**Comment by Diegorro98** [comment]
Update: The reason why I wasn't receiving notifications wasn't related to this issue. I able to send notifications and receive the notification at my app but the HTTP error 500 remains there.

**Comment by AjinKuriakose** [comment]
Facing same issue. 
Able to send and receive the notification but the response status is 500 with no headers set.

**Comment by Diegorro98** [comment]
Is working again!
@AjinKuriakose can you confirm that is working for you also? if yes I will close the issue

**Comment by AjinKuriakose** [comment]
Just tested this again and I'm still seeing the same behavior : The notification is delivered but the response status is 500 with no headers. 

@Diegorro98 : Did you make a change or did it happen to start working correctly all of a sudden?

**Comment by Diegorro98** [comment]
@AjinKuriakose no, no changes were made. It started working again suddenly.

I'm sorry to hear that the issue still remains for you, I will leave the issue open then.

**Comment by Diegorro98** [comment]
Update: The issue is back although I'm receiving the notifications, and I didn't change anything...

**Comment by Diegorro98** [comment]
Back again here. Since a while ago the notification response was the right one again, but I forgot to mention here.

**Comment by anupriya13** [comment]
@Diegorro98 If it's working for you, shall I close it then?
