### ISSUE TITLE
What's new in Windows app SDK 1.5 experimental 1?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#4021]
### Describe the bug

What's new in Windows app SDK 1.5 experimental 1?
Windows app sdk 1.5 experimental 1 更新了什么？

At present, the Windows app SDK 1.5 experimental 1 has provided an installation package in nuget, but no changelog has been provided, and we hope to release a changelog soon
目前 Windows app sdk 1.5 experimental 1 已经在nuget中提供了安装包，但是还没有提供更新日志，希望能尽快发布一份更新日志

### Steps to reproduce the bug

None

### Expected behavior

See describe

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/d2a0d566-81f4-4afc-b6e4-b0b4ddd318f9)

### NuGet package version

Windows App SDK 1.4.3: 1.4.231115000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

None

**Comment by Scighost** [comment]
From [UWP Community Discord Server](https://discord.com/channels/372137812037730304/671870147354427422/1181964969697349804)

https://cdn.discordapp.com/attachments/671870147354427422/1181964969823174696/diff_1.4_to_1.5_exp1.html

**Comment by Gaoyifei1011** [comment]
> From [UWP Community Discord Server](https://discord.com/channels/372137812037730304/671870147354427422/1181964969697349804)
> 
> https://cdn.discordapp.com/attachments/671870147354427422/1181964969823174696/diff_1.4_to_1.5_exp1.html

Thank you very much for your reply. It was very helpful

**Comment by Scighost** [comment]
> Is this a diff compared to 1.4? Or all available APIs in 1.5

Only diff APIs.

**Comment by DarranRowe** [comment]
From what I remember of the generated .idl files from the 1.5 experimental 1 .winmd files, all of these changes are still marked as experimental. So don't expect any of the experimental APIs to be available in the 1.5 previews or release. I could have missed something not marked as experimental though.
Although the UWP support API for Application is interesting. Could this mean that desktop11:AppLifecyleBehaviour be closer that I though?

**Comment by ghost1372** [comment]
1.5 exp release note published

**Comment by riverar** [comment]
Can probably close this issue now, as the docs have been updated: https://learn.microsoft.com/windows/apps/windows-app-sdk/experimental-channel#version-15-experimental-150-experimental1
