### ISSUE TITLE
.NET 8 Regression with binding(?) to Win2D(?)

### ISSUE THREAD

**Issue by knightmeister** [microsoft/WindowsAppSDK#4025]
### Describe the bug

Firstly, I apologise for the vague title. I'm also unsure where the best place to raise this is, and I ultimately settled on this repository as it was the focal point for Reunion.

[Reproduction repository available here](https://github.com/knightmeister/WinUIAVPBrokenNet8).

I noticed this while updating my WinUI app to .NET8. I make use of the `AnimatedVisualPlayer` control to play Lottie animations.

Using the latest version of the WindowsAppSDK and associated build tools, under .NET 8 I get the following exception:

![image](https://github.com/microsoft/WindowsAppSDK/assets/1528425/d86d9d3d-ce16-4091-bb8e-3af80cbec3ac)

It looks like there is some COM class that isn't registered or available for some reason under .NET 8. The same code works perfectly fine under .NET 6.

The reproduction repository `main` branch is .NET 6 and it works. Switch to the `NET8` branch and you will see it crash.

### Steps to reproduce the bug

See the repository in the previous section.

### Expected behavior

App does not crash when using `AnimatedVisualPlayer`.

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

All latest packages are being used for testing.

**Comment by DarranRowe** [comment]
There are a couple of potential things to try.
1) Try this with the Windows App SDK 1.5 Experimental 1 and Win2D 1.1.1. Both of these packages have the .NET 8 build fixes in them.
2) As per the Windows App SDK 1.4 release notes. Try enabling UseRidGraph and doing the win10 -> win substitutions mentioned.

IIRC, Win2D is copied to the package/application directory and without UseRidGraph, the copy looks in runtimes\win-$(Platform)\native\ which doesn't exist in the older packages.

**Comment by knightmeister** [comment]
Thanks @DarranRowe, I tried using the latest versions without luck however `UseRidGraph` made it work.

**Comment by DarranRowe** [comment]
That is interesting. Using Windows App SDK 1.5-e1 and Win2D 1.1.1, I have no issues.
Were you caught out by the fact that the latest Win2D versions seem to require the 10.0.22621.0 TFM? In other words, the target framework must be set to netx.0-windows10.0.22621.0 for it to build, where the x is the major .NET version you wish to target.

**Comment by knightmeister** [comment]
> Were you caught out by the fact that the latest Win2D versions seem to require the 10.0.22621.0 TFM? In other words, the target framework must be set to netx.0-windows10.0.22621.0 for it to build, where the x is the major .NET version you wish to target.

Yeah, quite possibly. I had an issue directly referencing Win2D causing it to fail to build, and because time was short when I hit that I just used the `UseRidGraph` in the csproj which fixed it.
