### ISSUE TITLE
Overlapping text in toast with header created in a collection

### ISSUE THREAD

**Issue by sonnin** [microsoft/WindowsAppSDK#4026]
### Describe the bug

When creating a toast in a collection. Windows automatically adds a textual note "via Notification Visualizer" (name of the application).
When the toast contains a header. The same textual note "via..." is added on top of the header text. This makes it very difficult to read the header text.

### Steps to reproduce the bug

1. Start Notification Visualizer app
2. Create a "sample" collection
3. Create a toast with the following 
```
<toast>
  <header id="6289" title="Test header" arguments="header"/>
  <visual>
    <binding template="ToastGeneric">
      <text>This is a simple toast message</text>
      <text>With a header in a collection</text>
    </binding>
  </visual> 
</toast>
```

4. pop it

### Expected behavior

Header text is fully visible and not overwritten.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/28400676/4c49c1b0-67ba-45dc-aaa2-2c4927d61c02)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (21H2): Build 19044

**Comment by anupriya13** [comment]
Not repro:
<img width="296" alt="image (1)" src="https://github.com/microsoft/WindowsAppSDK/assets/54227869/3afa0e9c-e7b3-45fe-8aaa-b9a17612c34d">

**Comment by sonnin** [comment]
Is this on Windows 10 or 11?

**Comment by anupriya13** [comment]
> Is this on Windows 10 or 11?

Windows 11

**Comment by bitdisaster** [comment]
@anupriya13  Can we re-open this. The bug is still very much alive on 
Edition	Windows 11 Enterprise
Version	24H2
Installed on	‎6/‎9/‎2025
OS build	26100.7840
Experience	Windows Feature Experience Pack 1000.26100.291.0


<img width="377" height="256" alt="Image" src="https://github.com/user-attachments/assets/6c957eac-3fbe-4176-98b6-8c95afde483e" />
