### ISSUE TITLE
AppSDK 1.5 experimental 1 download links are broken

### ISSUE THREAD

**Issue by lhak** [microsoft/WindowsAppSDK#4032]
### Describe the bug

All of the download links here:

![image](https://github.com/microsoft/WindowsAppSDK/assets/38145893/047834c9-be01-4da7-8cde-a1839c271da5)

do not work.

### Steps to reproduce the bug

-

### NuGet package version

None

**Comment by kythant** [comment]
Apologies. We missed a step to activate these links. Thanks for bringing this to our awareness. This should be fixed now.
