### ISSUE TITLE
Missing API to access and control AdaptiveMediaSource representations

### ISSUE THREAD

**Issue by aschultz** [microsoft/WindowsAppSDK#4096]
When using AdaptiveMediaSource to play DASH and HLS content, the API surface for controlling the content handling is currently very limited. It only provides access to a list of bitrates and the ability to set the min/max desired bitrates.

A single video track might have many different resolutions and codecs available, but none of that data is currently accessible to apps. Nor is there any way to prefer or disable certain representations. If you try to use VideoTrack.GetEncodingProperties() to get data about a track, it seems to give back data for only one representation (often the lowest quality).

A single audio track might have multiple codecs available, like AAC for stereo and AC3 for 5.1 surround. There's no way to choose one as the active option or indicate a preference.

There should be an API exposing the list of tracks, and the representations available for each track, providing metadata about the representations and an option to disable a representation.

Example use cases:
1. Filtering out representations that a platform has trouble playing. On Xbox, a 4K representation might consume too much video memory, so it is desirable to remove it from the list of options and cap out at 1080p. Whereas on PC we may be ok with going to 4K for the same content. In the same vein, there may be both H264 and HEVC representations available. On a device without hardware HEVC support, an app may want to disable the HEVC representations to avoid poor performance.
2. Selecting an audio format. An audio track might be available in several formats, like AAC for stereo and AC3/EC3 for 5.1 surround, and a user may want to choose a preferred format.

**Comment by codendone** [comment]
This is a Windows API outside the scope of WinAppSDK. I logged this [internal issue](http://task.ms/48798317) for the owners of AdaptiveMediaSource to look at this issue.

**Comment by tom-huntington** [comment]
Did you try [MediaPlaybackItem](https://learn.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybackitem?view=winrt-26100)?

>The [MediaPlaybackItem](https://learn.microsoft.com/en-us/uwp/api/Windows.Media.Playback.MediaPlaybackItem) class extends the functionality of MediaSource, allowing you to manage and select from multiple audio, video, and metadata tracks contained in a media item.
