### ISSUE TITLE
Add cookie with Windows.Web.Http.HttpCookieManager does not work on Server 2019 with IE Enhanced Secuirty Configuration set to true

### ISSUE THREAD

**Issue by HO-COOH** [microsoft/WindowsAppSDK#4098]
### Describe the bug

A customer reported a network issue. He is using Windows Server 2019, build 17763. After hours of debugging, I found out that the it's because of the default settings of enhanced IE security is set to true, and therefore all cookies were not sent. After disabling that setting, the issue was resolved.

### Steps to reproduce the bug

1. Open Server Manager
2. Set enhanced IE security to true
3. Use this code
```cpp
    winrt::Windows::Web::Http::Filters::HttpBaseProtocolFilter filter;
    winrt::Windows::Web::Http::HttpCookie cookie; //Set cookie as needed
    filter.CookieManager().SetCookie(cookie);
    winrt::Windows::Web::Http::HttpClient client{filter};
    client.SendAsync(...); //Send a request
```
4. Run and capture the traffic with something like fiddler, observe the cookie in the header

### Expected behavior
This setting should not affect apps using WinRT apis, otherwise should be clearly documented

### NuGet package version

Windows App SDK 1.4.4: 1.4.231219000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 1809 (17763, October 2018 Update)

### IDE

Visual Studio 2022

### Additional context

Server2019 17763

**Comment by bpulliam** [comment]
This is a Windows API, not a WinAppSDK one.  Please log an issue on Feedback and it will be directed to the correct team.  Thanks!
