### ISSUE TITLE
Have you forgot to generate projection dll for wasdk 1.5 new winmd?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#4152]
### Describe the bug

Have you forgot to generate projection dll for wasdk 1.5 new winmd?

In the latest Windows app sdk 1.5-exp2, we can see that two new winmd files were added, but the corresponding WinMD files were not generated.dll. It is hoped that the projection.dll will be generated in the next version for c#.NET 6+ calls

Microsoft.Windows.System.Workloads.winmd
Microsoft.Windows.Management.Deployment.winmd

### Steps to reproduce the bug

See below

### Expected behavior

Generate projection.dll for those winmd

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/d08ef4cd-da69-4d95-ae9d-8de3a0705cd5)
![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/4a03f41a-7b3e-4184-9057-1eabb617333f)

### NuGet package version

Windows App SDK 1.5 Experimental 2: 1.5.240124002-experimental2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DrusTheAxe** [comment]
Yes &lt;sheepish grin&gt; Addressed via #4154 

Thanks for bringing this to our attention!

**Comment by Gaoyifei1011** [comment]
> Yes <sheepish grin> Addressed via #4154
> 
> Thanks for bringing this to our attention!

Ok, thank you very much. Hope to bring in projection.dll for workloads api soon

**Comment by codendone** [comment]
Also related: #4155
