### ISSUE TITLE
What's new in Windows app sdk 1.5preview1

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/WindowsAppSDK#4173]
### Describe the bug

What's new in Windows app sdk 1.5preview1

### Steps to reproduce the bug

None

### Expected behavior

Please provide update information

### Screenshots

NONE

### NuGet package version

Windows App SDK 1.5 Experimental 2: 1.5.240124002-experimental2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

None

**Comment by ghost1372** [comment]
See here
https://ghost1372.github.io/wasdkOMD/omd/WinAppSDK1.5.240205001-preview1_v1.4.231219000.html

**Comment by codendone** [comment]
Release notes are now posted: https://learn.microsoft.com/windows/apps/windows-app-sdk/preview-channel#version-15-preview-1-150-preview1
