### ISSUE TITLE
App (Toast) Notification Activation not supported on arm64

### ISSUE THREAD

**Issue by wbokkers** [microsoft/WindowsAppSDK#4227]
### Describe the bug

On ARM64, when having the windows.toastNotificationActivation extension to the manifest, the app will crash when showing app notifications when running as a normal user. When running as an administrator, the app does not crash, but no toast notification will be shown.

See: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs

### Steps to reproduce the bug

1. Use app notifications in the app, using this approach:  https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/app-notifications/app-notifications-quickstart?tabs=cs
2. Try to show app notifications.
3. AppNotificationManger.IsSupported() returns false
4. Remove or show a notification using AppNotificationManager.Default instance.
5. Crash when using as normal user / no notifications when running as administrator.

Example stack trace:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/4835617/84b686f7-5a3a-4bea-b0c0-60103b16907c)

### Expected behavior

Even when AppNotificationManger.IsSupported() returns false, showing a notifications still work on x64 on most systems. 
I expect this to be the case on arm64 as well.

Or at least, do not crash the app. 

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by anupriya13** [comment]
Hi @wbokkers , 
Can you confirm the Visual Studio Version? Are you using VS 2022 17.6 (LKG15) or VS 2022 17.8 (LKG16 ) or any other version?

**Comment by wbokkers** [comment]
Hi @anupriya13, I am not sure. I always use the latest version at every moment. Currently I do avoid using App Notifications and use my own in-app notification implementation. Users seem to like this more and notifications are easier detected, so I do not need the feature anymore.

**Comment by satkh** [comment]
can you please share this screenshot from your vs .. Help -> About Microsoft  Visual Studio .
![image](https://github.com/microsoft/WindowsAppSDK/assets/167398920/64ad3f27-ab23-4529-8c80-bc27051be20f)

**Comment by wbokkers** [comment]
I can, but I am sure I updated VS since I submitted the issue.
![image](https://github.com/microsoft/WindowsAppSDK/assets/4835617/d710f0a9-3c52-4947-bf3e-212bc688e8bc)

**Comment by satkh** [comment]
Can you run on 17.9 and update if it's still crashing?

**Comment by wbokkers** [comment]
I don't use app notification anymore, so there is no code to test, but as soon I have time, I will check.

**Comment by will-velazquez** [comment]
For the record, there's a minimum reproducible sample here, that has been tested with 17.9 and is still broken: https://github.com/stegru/NotificationTest

**Comment by anupriya13** [comment]
@will-velazquez yes, we are aware of this, and we are working on the fix. It's a compiler bug for ARM SV2 which was fixed for LKG 16+. I will update it here once it's fixed / backported.

**Comment by anupriya13** [comment]
@will-velazquez This issue is fixed

**Comment by will-velazquez** [comment]
@anupriya13 Thanks for the heads-up. How should I go about testing? I tried again with the code in https://github.com/stegru/NotificationTest and still the app crashing.
Should I upgrade AppSDK, build tools version, Visual Studio version, or anything else?

**Comment by anupriya13** [comment]
@will-velazquez Can you try updating OS to ge?

**Comment by will-velazquez** [comment]
Thanks @anupriya13 , can confirm on our side that it works now on 24H2 26120.1930

**Comment by anupriya13** [comment]
Thanks for the confirmation! :)
Closing this issue now.
