### ISSUE TITLE
Question: Will Project Reunion 0.5 support WebView2 WebResourceResponseReceived event?

### ISSUE THREAD

**Issue by VagueGit** [microsoft/WindowsAppSDK#424]
`WebResourceResponseReceived` is required to required to read the response from a web request. Pretty fundamental really.

**Comment by VagueGit** [comment]
Do xaml apps process payments through a payment gateway? Do xaml apps subscribe to web services at all?

How do xaml developers subscribe to web resources if they are unable to read the response to a web request?

I'm surprised this issue hasn't had much attention and I wonder if xaml apps are meant to engage with the wider app ecosystem. The wider app ecosystem embraces web services. Economically and socially we are largely dependent on web services.

Is xaml app development intended to be disconnected from the web services ecosystem? I must be missing something ...

**Comment by chigy** [comment]
This is supported in the latest WinAppSDK.
