### ISSUE TITLE
NavigationViewItem Dropdown Behavior 

### ISSUE THREAD

**Issue by Wandtket** [microsoft/WindowsAppSDK#4243]
### Describe the bug

When users click the arrow on a NavigationViewItem in a NavigationView a blank dropdown appears.

When PaneDisplayMode is set to Top, it shows blank, when set to default tapping the arrow does nothing and prevents it from opening.

Touchscreens are also showing unexpected behavior such as menu items not being clickable. 

### Steps to reproduce the bug

Create a new WinUI Desktop App
Add a NavigationView with Menu items
Set the PaneDisplayMode to Top
Click the arrow instead of the item.

### Expected behavior

Dropdown should always show items regardless of where a user clicks.

### Screenshots

![Dropdown gif](https://github.com/microsoft/WindowsAppSDK/assets/13137508/91a9431b-52f4-4a7f-94b6-ddef5b7100b0)

https://github.com/microsoft/WindowsAppSDK/assets/13137508/fb352063-cc19-4e6a-bda1-31c15cf490e8

### NuGet package version

Windows App SDK 1.5.0: 1.5.240227000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by belka-ew** [comment]
I'm experiencing the same issue.
