### ISSUE TITLE
App crashes when we try to create 2 XAML containers (such as a Window & a DesktopWindowXamlSource)

### ISSUE THREAD

**Issue by raphael3292383** [microsoft/WindowsAppSDK#4246]
### Describe the bug

When we try to create 2 XAML containers (like a Window & a DesktopWindowXamlSource) in a XAML Islands app, the application freezes, then crashes.

### Steps to reproduce the bug

* 1: Create a XAML Islands WinForms app with WASDK
* 2: Try creating multiple XAML containers (like 2 Microsoft.UI.Xaml.Window) 

### Expected behavior

I expected the app to work.

### NuGet package version

Windows App SDK 1.5 Preview 1: 1.5.240205001-preview1

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
When you selected 1.5 Preview 1, did you mean Preview 1. If you did, try updating to the release version of 1.5.
This report makes me think of microsoft/microsoft-ui-xaml#8806. This does look like it is fixed in 1.5.

**Comment by raphael3292383** [comment]
I can't find the appropriate Windows App Runtime executable on MS's website

**Comment by DarranRowe** [comment]
Try [here](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads).

**Comment by raphael3292383** [comment]
Yes, it seems like they fixed it in 1.5
