### ISSUE TITLE
WindowsAppSDKSelfContained & PublishSingleFile - Error

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#4247]
### Describe the bug

`<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`
`<PublishSingleFile>true</PublishSingleFile>`
These two, when used together in a Windows App SDK 1.5 app (Packaged), still gives error:
![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/0527bf46-8ff9-4fe0-acd9-4586a7372912)

I am using Windows App SDK 1.5.240227000 and .NET 8

### Steps to reproduce the bug

Create a new WinUI 3 Packaged App in VS and add copy these on your csproj file:
`<PropertyGroup>`
`  <OutputType>WinExe</OutputType>`
`  <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>`
`  <TargetPlatformMinVersion>10.0.22621.0</TargetPlatformMinVersion>`
`  <RootNamespace>Schoolr</RootNamespace>`
`  <ApplicationManifest>app.manifest</ApplicationManifest>`
`  <Platforms>x86;x64;ARM64</Platforms>`
`  <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>`
`  <PublishProfile>win10-$(Platform).pubxml</PublishProfile>`
`  <UseWinUI>true</UseWinUI>`
`  <EnableMsixTooling>true</EnableMsixTooling>`
`  <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>`
`  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>`
`  <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>`
`  <PublishSingleFile>true</PublishSingleFile>`
`</PropertyGroup>`

Make sure you fix the RID-related errors first.

### Expected behavior

We should be able to produce a self-contained, packaged, and single-file WASDK/WinUI 3 app

### NuGet package version

Windows App SDK 1.5.0: 1.5.240227000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ghost1372** [comment]
Just add
`<WindowsPackageType>None</WindowsPackageType>` in your csproj file

**Comment by Scottj1s** [comment]
This restriction is by design - packaged apps have specialized deployment behavior, which is not compatible with single-file publishing and deployment.
