### ISSUE TITLE
SatelliteResourceLanguages property is ignored when publishing a self-contained unpackaged .NET app, 

### ISSUE THREAD

**Issue by majaeger** [microsoft/WindowsAppSDK#4288]
### Describe the bug

I am building a self-contained app which is en-US only. I am setting the below property to attempt to limit the satellite assemblies that are included when publishing my app, but it seems that WindowsAppSDKSelfContained does not respected this.

<SatelliteResourceLanguages>en</SatelliteResourceLanguages>

### Steps to reproduce the bug

Set the below properties in a .net unpackaged app.

    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <DefaultLanguage>en-US</DefaultLanguage>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    
   
Publish the app and examine the publish directory.

### Expected behavior

Expected: Only en satellite assemblies present
Actual: All languages present

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/24962807/6fdeecbe-0e3b-4c72-bbab-fd96bcd7b1a8)

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
Dupe of #3843 ?

**Comment by majaeger** [comment]
Looks like it

**Comment by mfaguilar** [comment]
In case it is of use to someone else as well... I had to do this as a workaround to fix it (nothing else I tried worked for me), in the project file put:

```
<Target Name="RemoveUnwantedSatelliteAssemblies" AfterTargets="Publish">
  <ItemGroup>
    <CultureDirsToRemove Include="$(PublishDir)af;$(PublishDir)ar;$(PublishDir)az;$(PublishDir)bg;$(PublishDir)bn;$(PublishDir)bn-BD;$(PublishDir)bs;$(PublishDir)ca;$(PublishDir)cs;$(PublishDir)da;$(PublishDir)de;$(PublishDir)el;$(PublishDir)fa;$(PublishDir)fi;$(PublishDir)fi-FI;$(PublishDir)fr;$(PublishDir)fr-BE;$(PublishDir)he;$(PublishDir)hi;$(PublishDir)hr;$(PublishDir)hu;$(PublishDir)hy;$(PublishDir)id;$(PublishDir)is;$(PublishDir)it;$(PublishDir)ja;$(PublishDir)ko;$(PublishDir)ko-KR;$(PublishDir)ku;$(PublishDir)lv;$(PublishDir)ms;$(PublishDir)ms-MY;$(PublishDir)mt;$(PublishDir)nb;$(PublishDir)nb-NO;$(PublishDir)nl;$(PublishDir)pl;$(PublishDir)pt;$(PublishDir)pt-BR;$(PublishDir)ro;$(PublishDir)ru;$(PublishDir)sk;$(PublishDir)sl;$(PublishDir)sr;$(PublishDir)sr-Latn;$(PublishDir)sv;$(PublishDir)th;$(PublishDir)th-TH;$(PublishDir)tr;$(PublishDir)uk;$(PublishDir)uz;$(PublishDir)uz-Cyrl-UZ;$(PublishDir)uz-Latn-UZ;$(PublishDir)vi;$(PublishDir)zh-CN;$(PublishDir)zh-Hans;$(PublishDir)zh-Hant" />
  </ItemGroup>
  <RemoveDir Directories="@(CultureDirsToRemove)" ContinueOnError="true" />
</Target>
```

**Comment by cdock1029** [comment]
@ssparach that other issue was closed so is fixing this not planned?

**Comment by aepot** [comment]
Any progress? I'm also interested in this issue to be resolved.

Found this solution: https://github.com/microsoft/microsoft-ui-xaml/discussions/8524
But unfortunately it doesn't work.
