### ISSUE TITLE
TypedEventHandler no support naot

### ISSUE THREAD

**Issue by oven425** [microsoft/WindowsAppSDK#4302]
### Describe the bug

use Windows.UI.Notifications.ToastNotification's Activated  event
cause TypeInitializationException and PlatformNotSupportedException
in asp.net core project .net8 and naot

### Steps to reproduce the bug

1. build code in asp.net core like bleow
```c#
var notifygroup = app.MapGroup("notification");

notifygroup.MapGet("message", (ToastNotifier notifier) =>
    {
        var bb = new ToastContentBuilder()
            .AddArgument("action", "viewConversation")
            .AddArgument("conversationId", 9813)
            .AddText("Andrew sent you a picture")
            .AddText("Check this out, The Enchantments in Washington!");
        var toast = new ToastNotification(bb.GetXml());
        if (Environment.OSVersion.Platform == PlatformID.Win32NT)
        {
            toast.Activated += Toast_Activated;
        }
            
        notifier.Show(toast);
    });

void Toast_Activated(ToastNotification sender, object args)
{
    System.Diagnostics.Trace.WriteLine(args);
}
```
2. call http method , and excute toast.Activated += Toast_Activated can throw exception

### Expected behavior

should can work in naot mode

### Screenshots

![localhost_5193_notification_message](https://github.com/microsoft/WindowsAppSDK/assets/2818366/ff5d31c5-6c6d-412d-adaa-4cf47821b861)

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by Gaoyifei1011** [comment]
> ### Describe the bug
> use Windows.UI.Notifications.ToastNotification's Activated event cause TypeInitializationException and PlatformNotSupportedException in asp.net core project .net8 and naot
> 
> ### Steps to reproduce the bug
> 1. build code in asp.net core like bleow
> 
> ```cs
> var notifygroup = app.MapGroup("notification");
> 
> notifygroup.MapGet("message", (ToastNotifier notifier) =>
>     {
>         var bb = new ToastContentBuilder()
>             .AddArgument("action", "viewConversation")
>             .AddArgument("conversationId", 9813)
>             .AddText("Andrew sent you a picture")
>             .AddText("Check this out, The Enchantments in Washington!");
>         var toast = new ToastNotification(bb.GetXml());
>         if (Environment.OSVersion.Platform == PlatformID.Win32NT)
>         {
>             toast.Activated += Toast_Activated;
>         }
>             
>         notifier.Show(toast);
>     });
> 
> void Toast_Activated(ToastNotification sender, object args)
> {
>     System.Diagnostics.Trace.WriteLine(args);
> }
> ```
> 
> 2. call http method , and excute toast.Activated += Toast_Activated can throw exception
> 
> ### Expected behavior
> should can work in naot mode
> 
> ### Screenshots
> ![localhost_5193_notification_message](https://private-user-images.githubusercontent.com/2818366/318284767-ff5d31c5-6c6d-412d-adaa-4cf47821b861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDU5NjUsIm5iZiI6MTcxMTk0NTY2NSwicGF0aCI6Ii8yODE4MzY2LzMxODI4NDc2Ny1mZjVkMzFjNS02YzZkLTQxMmQtYWRhYS00Y2Y0NzgyMWI4NjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMDQyNzQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk1NTkxZjE0YjY5NjA2M2I5NTgzMDhiNmY4MzAxODg2OTZhYzgxYmRkMzE0MDNiZGE1YTI3MWVjYTZjMWJiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I0pIIXmJ5CdUxIFFgV7Z-73YX_D8PZhC-Q3U-zb2UBU)
> 
> ### NuGet package version
> Windows App SDK 1.5.1: 1.5.240311000
> 
> ### Packaging type
> _No response_
> 
> ### Windows version
> Windows 11 version 22H2 (22621, 2022 Update)
> 
> ### IDE
> Visual Studio 2022
> 
> ### Additional context
> _No response_

Since the Windowsappsdk uses csWinRT in c#, csWinRT currently does not support nativeaot, you can keep an eye on the dynamics of the cswinrt repository

**Comment by manodasanW** [comment]
As per previous post, CsWinRT and WinAppSDK AOT support is in the works.  I will be updating the following discussion once we have something folks can try out: https://github.com/microsoft/WindowsAppSDK/discussions/3856
