### ISSUE TITLE
ResourceLoader can't find resources

### ISSUE THREAD

**Issue by YexuanXiao** [microsoft/WindowsAppSDK#4312]
### Describe the bug

I added Strings/en-US/Settings.resw in my packaged app, but ResourceLoader("Settings") throws an exception.

Everything works fine when using a parameterless constructor, or when referencing the resource in XAML.

### Steps to reproduce the bug

Using [ResourceLoader(String)](https://learn.microsoft.com/zh-cn/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourceloader.-ctor?view=windows-app-sdk-1.5#microsoft-windows-applicationmodel-resources-resourceloader-ctor(system-string)).

### Expected behavior

Constructs a ResourceLoader that references the specified resource.

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (26090)

### IDE

Visual Studio 2022-preview

### Additional context

Documents:

https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.applicationmodel.resources.resourceloader.-ctor?view=windows-app-sdk-1.5#microsoft-windows-applicationmodel-resources-resourceloader-ctor(system-string)

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/mrtcore/localize-strings?source=recommendations

**Comment by YexuanXiao** [comment]
The old and obsolete API Windows.ApplicationModel.Resources.ResourceLoader has the correct behavior, but it's not a real solution to the problem.

**Comment by roxk** [comment]
I'm not sure if this is intended but you need to say which pri you want to use now. So, instead of just `ResourceLoader("Settings")`, you should write `ResourceLoader(ResourceLoader.GetDefaultResourceFilePath(), "Settings")`.

If this is intended, doc should be updated.

**Comment by ghost1372** [comment]
duplicate #2406

**Comment by bpulliam** [comment]
duplicate
