### ISSUE TITLE
WindowsAppSDK-VersionInfo.json: Release.MajorMinor.HexUInt32 is not hex value

### ISSUE THREAD

**Issue by ynkdir** [microsoft/WindowsAppSDK#4338]
### Describe the bug

In microsoft.windowsappsdk.1.5.240404000.nuget/WindowsAppSDK-VersionInfo.json, Release.MajorMinor.HexUInt32 is 00010005.
Maybe it should be "0x00010005".

### Steps to reproduce the bug

See nuget package.

### NuGet package version

Windows App SDK 1.5.2: 1.5.240404000

**Comment by bpulliam** [comment]
What scenario is this causing an issue? We are not doing any addition or other operations on it, so is there any effect of this?

**Comment by ynkdir** [comment]
I am writing a python projection for WindowsAppSDK https://github.com/ynkdir/py-win32more.  It uses version information to call mddbootstrap API.

I want to update the version information in my library to follow each WindowsAppSDK update.  I wrote script and python's json parser raised parse error for the value 00010005.

I can write my update script with avoiding the error any way.   I just thought that 00010005 is not intended value.

**Comment by DrusTheAxe** [comment]
Thanks for the bug report! I've cooked  a fix in main for 1.6
