### ISSUE TITLE
Mapping between a XAML namespace and a CLR namespace in WinUI 3

### ISSUE THREAD

**Issue by peter0302** [microsoft/WindowsAppSDK#4354]
### Discussed in https://github.com/microsoft/WindowsAppSDK/discussions/2946

<div type='discussions-op-text'>

<sup>Originally posted by **vladimir-stoyanov** September  8, 2022</sup>
Is it possible to map between a XAML namespace and a CLR namespace in WinUI 3? 

For example in WPF, the following attribute: [XmlnsDefinition](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.xmlnsdefinitionattribute?view=windowsdesktop-6.0) is placed in the AssemblyInfo.cs file in order to achieve this. 

Is this achievable in WinUI 3 and if so how? </div>

To add, `XmlnsDefinition` is there in `Microsoft.UI.Xaml.Markup` but apparently it's not an attribute class so it's unclear how to use it.

**Comment by bpulliam** [comment]
This is already being tracked in the discussion.

**Comment by peter0302** [comment]
It's in the discussion except no one replied in 1.5 years.
