### ISSUE TITLE
Exception Thrown by comparison of TargetPlatformVersion

### ISSUE THREAD

**Issue by CADTraveller** [microsoft/WindowsAppSDK#4381]
### Describe the bug

I just started a new UserControl Library Project using .Net 8.  I've added WindowsAppSDK via Nuget.  As soon as the package installs there a warning about TargetPlatformVersion.  The Project no loger loads, throwing this exception:

A numeric comparison was attempted on "$(TargetPlatformVersion)"
that evaluates to "" instead of a number, in condition
"'$(TargetPlatformVersion)' < '10.0.18362.0'".
C:\Users\cc\.nuget\packages\microsoft.windowsappsdk\1.5.24040400
0\buildTransitive\Microsoft.InteractiveExperiences.Common.targets

### Steps to reproduce the bug

Start a new Library Project under .NET 8
Add the WindowsAppSDK via Nuget. I used the latest stable :
  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240404000" />
Unload the Project. You can no longer re-load it. It throws the error shown in the description.

Adding a TargetPlatformVersion entry to .csproj does not help

<TargetPlatformVersion>10.0.18362.0</TargetPlatformVersion>

### Expected behavior

I'd expect to be able to add the SDK without destroying my Project

### NuGet package version

Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Additional context

I'm actually running W11 23H2 Build 22631.3527 which is not listed as an option

**Comment by DarranRowe** [comment]
What is the TargetFramework for the project?
If you set it to a fully versioned one, like `<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>`, does that help?

**Comment by CADTraveller** [comment]
Thanks for the reply @DarranRowe.

If I add that line to specify the TargetFramework I get this error:

NETSDK1005	Assets file 'C:\Users\cc\OneDrive\Desktop\WindowAppSDK\WpfApp1\WpfCustomControlLibrary1\obj\project.assets.json' doesn't have a target for 'net8.0-windows10.0.19041.0'. Ensure that restore has run and that you have included 'net8.0-windows10.0.19041.0' in the TargetFrameworks for your project

I also get this:
 There was no runtime pack for Microsoft.WindowsDesktop.App.WPF available for the specified RuntimeIdentifier 'win10-arm'

I realize that last is a known breaking change. If I modify the .csprof file with:

<RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
<UseRidGraph>true</UseRidGraph>

Then I can get the empty project to build.

Since I can't exactly reproduce my originial issue, I understand this could be hard to address. Note that I couldn't reproduce my original error, but I did get a nice crop of new ones ;-}

 I'm very surprised that a new Project with the latest recommended platform and packages requires so much manual editing of the project file.

**Comment by CADTraveller** [comment]
I do think this package should be updated to be a little more user-friendly.  However, the below .csproj does allow me to build successfully, after some manual editing and multiple load/unload cycles.

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net8.0-windows10.0.22621.0</TargetFrameworks>
    <RuntimeIdentifiers>win-x64;win-x86</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.5.240428000" />
  </ItemGroup>

</Project>
