### ISSUE TITLE
Hot restart

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/WindowsAppSDK#44]
# Proposal: Hot restart

## Summary

[Hot reload](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2019) is a feature that's been out there for a while and helps get an immediate visual of the XAML in the opened editor, but that doesn't take into account lower-level functionality.

Hot restart takes it a step further and has your app re-rendered whenever it's underlying C# has changed too.

In some technologies out there this feature has been there since day #1 and is extremely useful. Would be very nice to have this in UWP.

**Comment by stevewri** [comment]
Should both hot reload and hot restart apply to Win32 apps that are using XAML via WinUI?

**Comment by weitzhandler** [comment]
Hot Restart should become a thing in .NET.
Ideally any app that can possibly support it.

**Comment by weitzhandler** [comment]
And BTW @stevewri, as yourself and other official as members or collaborators of this repo, for people to distinguish who they're getting their response from.

**Comment by andrewleader** [comment]
C# hot reload is supported in VS 2022! And it is supported in WinUI 3 apps but you have to change a project setting first, we're working on adding docs for that.
