### ISSUE TITLE
Scale transforms don't apply to ComboBox popups

### ISSUE THREAD

**Issue by Foda** [microsoft/WindowsAppSDK#4424]
### Describe the bug

When running as an packaged or unpackaged app, applying a `RenderTransform` or `CompositeTransform` doesn't scale the ComboBox popup. Using a `Viewbox` also does not work properly.
![image](https://github.com/microsoft/WindowsAppSDK/assets/890772/7704c0f5-8aca-4570-a954-541756d7b72e)

This also results in wrong hit-testing too.

### Steps to reproduce the bug

1. Add the following into a sample app:
```xaml
<ComboBox
   Width="300"
   Height="50">
   <ComboBox.RenderTransform>
       <ScaleTransform ScaleX="2" ScaleY="2" />
   </ComboBox.RenderTransform>
   <ComboBox.Items>
       <x:String>Hello world</x:String>
       <x:String>Hello world</x:String>
       <x:String>Hello world</x:String>
       <x:String>Hello world</x:String>
       <x:String>Hello world</x:String>
   </ComboBox.Items>
</ComboBox>
```
2. Debug the app

### Expected behavior

The ComboBox popup should also scale to the parent ComboBox

### NuGet package version

None

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

This issue is affecting customers using Dotnet MAUI

**Comment by codendone** [comment]
This issue was fixed in [1.5.2](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-152-15240404000):
> Fixed a problem where ShouldConstrainToRootBounds="false" popups/flyouts don't apply any inherited scale transform. For more info, see GitHub issues [#9118](https://github.com/microsoft/microsoft-ui-xaml/issues/9118) and [#9433](https://github.com/microsoft/microsoft-ui-xaml/issues/9433).
