### ISSUE TITLE
Drag-and-drop in elevated WinUI3 applications is not supported

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/WindowsAppSDK#4433]
### Describe the bug

Rearranging controls such as ListViewItems, TabViewItems, etc. using drag and drop makes the application crash when the user runs the application in elevated mode, as an administrator. In normal mode, the issue is not present.
1.	Is there a workaround for handling the above-mentioned issue?
2.	Why doesn't the elevated WinUI3 application support drag-and-drop operations?
3.	Is the Windows App SDK team planning to address the drag-and-drop issue in an upcoming release?

### Steps to reproduce the bug

1. Run the WinUI3 controls gallery application with elevated privileges as an administrator.
2. Go to TabView control examples page.
3. Rearrange the Tabs by dragging and dropping.

### Expected behavior

Drag-and-drop should work in both normal and elevated modes without causing the application to crash.

### NuGet package version

Windows App SDK 1.5.3: 1.5.240428000

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by codendone** [comment]
Same as #3921. We're tracking this here: microsoft/microsoft-ui-xaml#7690
