### ISSUE TITLE
Incorrect WindowsTargetPlatform[Min]Version in *.vcxproj 

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/WindowsAppSDK#445]
Almost(!) everything in Reunion's consistent

1x; dev\MRTCore\mrt\Microsoft.ApplicationModel.Resource
```
   <WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0.18362.0</WindowsTargetPlatformVersion>
    <WindowsTargetPlatformMinVersion>10.0.17134.0</WindowsTargetPlatformMinVersion>
 ```

2x: test\DynamicDependency\data\Framework.Math.Add + Framework.Math.Multiply
```
    <WindowsTargetPlatformVersion>10.0.19041.0</WindowsTargetPlatformVersion>
    <WindowsTargetPlatformMinVersion>10.0.17763.0</WindowsTargetPlatformMinVersion>
```
 
20+ (everyone else)
```
   <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
```

The 2x (Framework.Math.*) are the only correct ones?

All the project files should be in sync.

Also, this is waaay too manual to ensure it stays correct. Can we add something to PRojectReunion.props that verifies this @ build-time and fails if values aren't as expected?

**Comment by DrusTheAxe** [comment]
P.S. `<PlatformToolset>` has a similar problem

Almost(!) all *.vcxproj in Project Reunion say
```
    <PlatformToolset>v142</PlatformToolset>
```

Only exception is dev\MRTCore\mrt\mrm\UnitTests\BaseUnitTests.vcxproj
```
    <PlatformToolset Condition="$(VisualStudioVersion) &gt;= 16.0">v142</PlatformToolset>
    <PlatformToolset Condition="$(VisualStudioVersion) &gt;= 15.0 and $(VisualStudioVersion) &lt; 16.0">v141</PlatformToolset>
    <PlatformToolset Condition="$(VisualStudioVersion) &lt; 15.0">v140</PlatformToolset>
```

and the similar-but-different dev\MRTCore\mrt\Microsoft.ApplicationModel.Resources\src\Microsoft.ApplicationModel.Resources.vcxproj
```
    <PlatformToolset>v140</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '15.0'">v141</PlatformToolset>
    <PlatformToolset Condition="'$(VisualStudioVersion)' == '16.0'">v142</PlatformToolset>
```

**Comment by dhoehna** [comment]
@DrusTheAxe something like this: https://github.com/microsoft/ProjectReunion/tree/user/ToolsetAndWindowsVersionMismatch/AddingToProps

I moved both the Platform Toolset and Windows' version stuff to the prop file.  I have also changed all vcxproj files to use this property sheet.  I haven't tested to make sure anything build yet.

**Comment by LegendaryBlair** [comment]
Agreed with @dhoehna internally, treated this issue as won't fix.
