### ISSUE TITLE
DeviceInformation::FindAddAsync returns empty collection when specifying a usb device.

### ISSUE THREAD

**Issue by Tunghohin** [microsoft/WindowsAppSDK#4457]
### Describe the bug

DeviceInformation::FindAddAsync returns empty collection when specifying a usb device.

https://github.com/microsoft/cppwinrt/issues/1420

### Steps to reproduce the bug

```   cpp
auto devices = DeviceInformation::FindAllAsync(
    DeviceClass::VideoCapture
).get();
for (auto&& dev : devices) {
    fmt::println(stderr, L"{}", dev.Properties()
                                          .TryLookup(L"System.Devices.DeviceInstanceId")
                                          .try_as<winrt::hstring>()
                                          .value_or(L"None")
                                          .c_str());
}
fmt::println(stderr, "{}", devices.Size());
```
output: 
![e094238f350befad2228bb14d8975ed](https://github.com/microsoft/cppwinrt/assets/88049360/ab186f9f-0381-4cc2-9900-2194826bd2b1)
```cpp
auto devices = DeviceInformation::FindAllAsync(
    UsbDevice::GetDeviceSelector(0x0603, 0x8612)
).get();
for (auto&& dev : devices) {
    fmt::println(stderr, L"{}", dev.Properties()
                                          .TryLookup(L"System.Devices.DeviceInstanceId")
                                          .try_as<winrt::hstring>()
                                          .value_or(L"None")
                                          .c_str());
}
fmt::println(stderr, "{}", devices.Size());
```
gets a empty collection

**Comment by DarranRowe** [comment]
The problem here is that the [Windows.Devices.Usb](https://learn.microsoft.com/en-us/uwp/api/windows.devices.usb?view=winrt-22621) documentation states that it doesn't provide access to some USB devices. In particular, it states that this namespace is for WinUSB devices only. Have you verified that the device you are trying to access is WinUSB compatible?

To give an example, my system does have a WinUSB compatible device.

![Screenshot 2024-05-30 213845](https://github.com/microsoft/WindowsAppSDK/assets/52577874/785c79a5-1d49-415b-9844-ba12295d7183)

![Screenshot 2024-05-30 213851](https://github.com/microsoft/WindowsAppSDK/assets/52577874/cfb7efdd-7d9c-4ab4-be29-597e4bb066e5)

```
#include <Windows.h>

#include <string>
#include <format>

#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.Foundation.Collections.h>
#include <winrt/Windows.Devices.h>
#include <winrt/Windows.Devices.Enumeration.h>
#include <winrt/Windows.Devices.Usb.h>

int wmain()
{
	auto devices = winrt::Windows::Devices::Enumeration::DeviceInformation::FindAllAsync(
		winrt::Windows::Devices::Usb::UsbDevice::GetDeviceSelector(0x1e71, 0x300c)
	).get();

	for (auto device : devices)
	{
		auto fmt_string = std::format(L"{}", std::wstring_view(device.Id()));
		_putws(fmt_string.c_str());
	}

	return 0;
}
```

This gave me the following output:
`\\?\USB#VID_1E71&PID_300C&MI_00#9&fbe3bfd&0&0000#{dee824ef-729b-4a0e-9c14-b7117d33a817}`

So it works fine for me on my system when the device is properly declared as a WinUSB device.

**Comment by DarranRowe** [comment]
As a follow up to this, I did get an opportunity to try this out with a video capture USB device.

![Screenshot 2024-06-01 151321](https://github.com/microsoft/WindowsAppSDK/assets/52577874/dc87384c-0c68-430a-b7eb-94b4073fb17e)

![Screenshot 2024-06-01 151329](https://github.com/microsoft/WindowsAppSDK/assets/52577874/5effe341-5700-4bb5-ad20-746a7224fafc)

![Screenshot 2024-06-01 151346](https://github.com/microsoft/WindowsAppSDK/assets/52577874/f98ce8a0-bd73-4dfd-9b5b-7797b66b32df)

The code used was the same as above, except it had the VID changed to 0x07ca and PID changed to 0xd553 to reflect the device. As you can see, it successfully obtained an instance of the DeviceInformation. So again, can you confirm that the device is a WinUSB device?

**Comment by Tunghohin** [comment]
> As a follow up to this, I did get an opportunity to try this out with a video capture USB device.
> 
> ![Screenshot 2024-06-01 151321](https://private-user-images.githubusercontent.com/52577874/335806895-dc87384c-0c68-430a-b7eb-94b4073fb17e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTE4ODMsIm5iZiI6MTcxNzI1MTU4MywicGF0aCI6Ii81MjU3Nzg3NC8zMzU4MDY4OTUtZGM4NzM4NGMtMGM2OC00MzBhLWI3ZWItOTRiNDA3M2ZiMTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE0MTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4NDBlY2QzOTI1NGY5ZWVkZTgwZmUzZGE2NmQ5NTZmMTUzY2E4ZjE1YTFlZTllNjMxYjExMWFhYTY5OWZhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KxmZYRBIRwXseTtvqfvnaZz7NxgWCL-HGTm7KK33P6g)
> 
> ![Screenshot 2024-06-01 151329](https://private-user-images.githubusercontent.com/52577874/335806901-5effe341-5700-4bb5-ad20-746a7224fafc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTE4ODMsIm5iZiI6MTcxNzI1MTU4MywicGF0aCI6Ii81MjU3Nzg3NC8zMzU4MDY5MDEtNWVmZmUzNDEtNTcwMC00YmI1LWFkMjAtNzQ2YTcyMjRmYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE0MTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNDRjNzc1ODdjMGM2MjdjOWI4MDhlOTY2YzFlZjUzYTczZTBmMDRjMWM2NGZiOTQ2OWQ1NjJkY2QxMTU0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.piWLzF5T_tDdHg4hXciRg79DEzbiXyL-J7WFztGkNIo)
> 
> ![Screenshot 2024-06-01 151346](https://private-user-images.githubusercontent.com/52577874/335806907-f98ce8a0-bd73-4dfd-9b5b-7797b66b32df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTE4ODMsIm5iZiI6MTcxNzI1MTU4MywicGF0aCI6Ii81MjU3Nzg3NC8zMzU4MDY5MDctZjk4Y2U4YTAtYmQ3My00ZGZkLTliNWItNzc5N2I2NmIzMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE0MTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkYWIzYTkyNzk1YzdjMjJmNjY3ZDE0OTg2NTk3YzJhYTg0YjdjMGFmYTE4NjE5MjZmYWIwOGFhZjFhZDVkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hOQDvNYCFTy_Q1dO8ehgdPZN9kGE4hETvSeLLvZqaVY)
> 
> The code used was the same as above, except it had the VID changed to 0x07ca and PID changed to 0xd553 to reflect the device. As you can see, it successfully obtained an instance of the DeviceInformation. So again, can you confirm that the device is a WinUSB device?


I observed that my usb capture uses the usbccgp.sys driver instead of the winusb.sys driver, is this technically considered a winusb device?

**Comment by DarranRowe** [comment]
>I observed that my usb capture uses the usbccgp.sys driver instead of the winusb.sys driver, is this technically considered a winusb device?

No.

![Screenshot 2024-06-01 165818](https://github.com/microsoft/WindowsAppSDK/assets/52577874/abce6c14-90b7-4f3c-b136-c1e71500da4b)

While usbccgp is in the driver stack for a WinUSB device, as clearly documented by the Windows.Devices.Usb Namespace documentation, a WinUSB device will have a very specific compatible ID. If the device does not have the USB\MS_COMP_WINUSB compatible ID then it is not a valid WinUSB device.

This information can be easily obtained from device manager.
