### ISSUE TITLE
Ensure consistent project and nuget versions across repo

### ISSUE THREAD

**Issue by jonwis** [microsoft/WindowsAppSDK#448]
> Should be 16.0?
> MRT's *.vxcproj say 15.0 but everything else in Reunion says 16.0

_Originally posted by @DrusTheAxe in https://github.com/microsoft/ProjectReunion/pull/444#discussion_r575502195_

The ES should have some sort of check that ensures we're being consistent in the tools we're using.

**Comment by DrusTheAxe** [comment]
See Incorrect WindowsTargetPlatform[Min]Version in *.vcxproj #445 for more details

**Comment by EHO-makai** [comment]
@huichen123, do you have an issue to address the VS version in your project file?

**Comment by EHO-makai** [comment]
Assigning to @BenJKuhn to get into the ES backlog.

**Comment by huichen123** [comment]
It should be ok to update MRTCore VS version and WindowsTargetPlatform[Min]Version.

**Comment by BenJKuhn** [comment]
There are a number of different "version" aspects that this could cover. Most version considerations have been either consolidated, simplified away, or moved to management by Maestro at this point, so I'm closing out this issue.
