### ISSUE TITLE
Add Debug_x64 + Debug_Arm64 to the build pipeline

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/WindowsAppSDK#449]
Add Debug_x64 and Debug_Arm64 to the build pipeline

The build pipeline currently builds:

- Debug_x86
- Release_x64
- Release_x64
- Release_Arm
- Release_Arm64

All architectures are built as Release but only x86 is built as Debug. We should build all flavors as Debug+Release.

(arm will presumably be dropped soon per Final decision: No ARM32 support (only ARM64) #406)

**Comment by BenJKuhn** [comment]
At the moment it looks like our nightly builds aren't building debug builds of any flavor. That said, it would probably make more sense to build x64 as debug. I don't think I would build anything else on a scheduled basis, just out of resource usage considerations.

**Comment by DrusTheAxe** [comment]
That's new. We used to build some debug (x86?). I know because I questioned (on multiple occasions) why we were building some debug flavors but not others (and why the least-useful flavor)

I 2nd the motion for standard debug x64 builds

Can one manually trigger a pipeline to create other debug flavors? If not, can we add that option?

   - Howard
________________________________
