### ISSUE TITLE
CameraCaptureUI.CaptureFileAsync() No Longer Returns when PhotoSettings.AllowCropping Is True

### ISSUE THREAD

**Issue by LGE-AUGMENSYS** [microsoft/WindowsAppSDK#4530]
### Describe the bug

In our UWP app, we use the CameraCaptureUI.CaptureFileAsync() API to take photos and it used to be fine, whether we set the PhotoSettings.AllowCropping to true or false. We get the result file and can proceed with our work.

Since a recent update (maybe last month) on Windows 11, this breaks if PhotoSettings.AllowCropping is set to true. The camera app still shows up, but nothing seems to happen when you click on the shutter button. Upon further investigation, we found out that a photo is saved under our app's TempState folder. However, we never receive the file result for our CameraCaptureUI.CaptureFileAsync() call.

This was not the case at all before the OS update.

### Steps to reproduce the bug

The code snippet we use is as the following.

var mCamCaptureUi = new CameraCaptureUI();
mCamCaptureUi.PhotoSettings.AllowCropping = true;
StorageFile capturedMedia = await mCamCaptureUi.CaptureFileAsync(CameraCaptureUIMode.PhotoOrVideo);
if (capturedMedia != null)
{
    ...
}

Use the code above to launch the camera app, click the shutter button.

### Expected behavior

The camera app should capture the photo and present it with the cropping UI, allowing further processing and eventually returning the result to the caller.

### NuGet package version

None

### Packaging type

Unpackaged

### IDE

Visual Studio 2022

### Additional context

Windows 11 Enterprise 23H2 (22631.3737) - I could not find this in the "Windows version" list.

**Comment by codendone** [comment]
I logged an [internal bug](http://task.ms/52268225) to track this OS/Camera/Photos issue. Closing this as External from WinAppSDK.

**Comment by LGE-AUGMENSYS** [comment]
> I logged an [internal bug](http://task.ms/52268225) to track this OS/Camera/Photos issue. Closing this as External from WinAppSDK.

Could you please share updates on this issue when they become available? Or is there a public link we should follow instead?
Thanks and BR.

**Comment by stegh** [comment]
we have the same issue: "photo is saved under our app's TempState folder. However, we never receive the file result for our CameraCaptureUI.CaptureFileAsync() call."

**Comment by LGE-AUGMENSYS** [comment]
@codendone 
Could you please inform us how we can get updates on the ticket status?
If CameraCaptureUI is not a part of the WindowsAppSDK and there's a better place to report this issue, we would also appreciate it if you could point us the way.

**Comment by codendone** [comment]
Update: The owning team reports this issue as fixed. The fix will be rolling out via Windows Update later this year.
