### ISSUE TITLE
Windows.Storage.StorageLibrary.RequestAddFolderAsync() throws COMException

### ISSUE THREAD

**Issue by hjc4869** [microsoft/WindowsAppSDK#4590]
### Describe the bug

This could be reproduced easily with a simple API call below. Similarly, StorageLibrary.RequestRemoveFolderAsync() does not work either.

It's probably caused by the underlying folder picker requiring an initialization with WinRT.Interop.InitializeWithWindow() call, but Windows.Storage.StorageLibrary API does not expose the folder picker to the API caller.

### Steps to reproduce the bug

```
var libraryFolders = await StorageLibrary.GetLibraryAsync(KnownLibraryId.Music);
var folder = await libraryFolders.RequestAddFolderAsync();
```

### Expected behavior

A folder picker shows up

### NuGet package version

Windows App SDK 1.5.5: 1.5.240627000

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

**Comment by DarranRowe** [comment]
Unfortunately this is [documented](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api#methods-that-use-the-request-naming-pattern). Issues like these are major sticking points in using packaged applications in an AppContainer.
If you are not targetting an AppContainer (i.e. setting the entrypoint to windows.partialTrustApplication or you explicitly set uap10:TrustLevel to AppContainer), the [shell library API](https://learn.microsoft.com/en-us/windows/win32/shell/library-ovw) is usable. If you are targetting an AppContainer, be aware that the file pickers also don't work.

**Comment by JesseCol** [comment]
Hi, you might try following the instructions here if you haven't already: https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#windows-sdk

Please let us know if it didn't work for you.

Thanks!
