### ISSUE TITLE
GetForUnpackaged Not available in new Microsoft.Windows.Storage API - v1.6-preview1

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#4644]
### Describe the bug

after updating to v1.6-preview1 i can access **Microsoft**.Windows.Storage API and i can use `GetForDefault` but `GetForUnpackaged` which detailed [here](https://github.com/microsoft/WindowsAppSDK/blob/53a901455238156740fd9545cfba9e1660257618/specs/applicationdata/ApplicationData.md#44-unpackaged-app-using-localpath) is not available.
Is it a bug or was it intentional?

### Steps to reproduce the bug

1.Create new App
2.v1.6-preview1
3.Use new ApplicationData API for UnPackaged

### NuGet package version

Windows App SDK 1.6 Preview 1: 1.6.240807006-preview1

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022-preview, Visual Studio 2022

**Comment by YLepper** [comment]
I think it was intentional that `GetForUnpackaged()` isn't available.
It was stated in the pull request: #4057 

> vFuture (ApplicationDataContract v2, vFuture)
>    GetForUnpackaged() backed by an unpackaged variant of M.W.S.ApplicationData.cpp + M.W.S.ApplicationDataContainer.cpp

**Comment by DrusTheAxe** [comment]
> I think it was intentional that `GetForUnpackaged()` isn't available. It was stated in the pull request: #4057
> 
> > vFuture (ApplicationDataContract v2, vFuture)
> > GetForUnpackaged() backed by an unpackaged variant of M.W.S.ApplicationData.cpp + M.W.S.ApplicationDataContainer.cpp

+1

P.S. That's why it's marked with contract version 2 and a `feature` attribute (aka experimental)

```
        [feature(Feature_ApplicationData)]
        [contract(ApplicationDataContract, 2)]
        static ApplicationData GetForUnpackaged(String publisher, String product);
```

Preview and stable builds omit experimental features.

**Comment by ghost1372** [comment]
Thank you @DrusTheAxe 
but, can we use it in v1.6 version? in next preview or stable release?
