### ISSUE TITLE
TextDecorations Type Conflict in 1.6 Preview 1

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/WindowsAppSDK#4646]
### Describe the bug

I can't seem to get rid of a conflict error in my WinUI 3 C# project. Please see the attached error below:

The type 'TextDecorations' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Microsoft.Windows.SDK.NET, Version=10.0.26100.38, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

As per the release note of Windows App SDK 1.6 Preview 1, I need to add the Microsoft.Windows.SDK.NET.Ref into my csproj file.
Looking into the nuget gallery, the latest version is 10.0.26100.42, so I entered that one instead of 10.0.22621.38 (example shown in the release notes). This is what I exactly typed:

`<WindowsSdkPackageVersion>10.0.26100.42</WindowsSdkPackageVersion>`

Secondly, as per the release note again, I also need CsWinRT, so I installed the nuget for that with version 2.1.1.

Can someone please have a look? Thank you.

### Steps to reproduce the bug

1. Create a new VS 2022 project using the "Blank App, Packaged (WinUI 3 in Desktop)" template.
2.  Change the Target Framework to .NET 9.0, Target OS version to 10.0.26100.0, Supported OS version to 10.0.22621.0
![image](https://github.com/user-attachments/assets/e32afcd2-2d5d-451c-82dd-1fbe11aafa63)
3. Update the Microsoft.WindowsAppSDK NuGet package to 1.6.240807006-preview1
4. Update the Microsoft.Windows.SDK.BuildTools NuGet package to 10.0.26100.1
5. Install Microsoft.Windows.CsWinRT NuGet package version 2.1.1
6. In the csproj file, enter the `<WindowsSdkPackageVersion>10.0.26100.42</WindowsSdkPackageVersion>` under the `<PropertyGroup>`node

### NuGet package version

Windows App SDK 1.6 Preview 1: 1.6.240807006-preview1

### Packaging type

Packaged (MSIX)

### Windows version
Windows 11 23H2

### IDE

Visual Studio 2022-preview

**Comment by manodasanW** [comment]
There are a handful of types that we discovered in WinUI that are conflicting with the new Windows SDK projection.  We plan on addressing them by marking these types as forwarded to the Windows SDK projection.  In the interim, if you don't need to target `26100` and can target `22621` instead, you can downgrade your Windows SDK projection version to `.35-preview` to get unblocked.

```<WindowsSdkPackageVersion>10.0.22621.35-preview</WindowsSdkPackageVersion>```

If you do need to target 26100 for the new OS APIs available there, I can look at figuring out another workaround to unblock you in the interim.

**Comment by DJRM2021** [comment]
I changed the `<WindowsSdkPackageVersion>` in the csproj file to 10.0.22621.35-preview. However, I am now having this issue:
![image](https://github.com/user-attachments/assets/fe291b33-93d5-4e9c-82cf-94e3729dfafb)

I also have these in the csproj file:
`<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.1.1" />`
`<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1" />`
`<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240807006-preview1" />`

My target framework is: 
`<TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>`
`<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>`
`<SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>`

**Comment by manodasanW** [comment]
That is a known issue that has been addressed in the `Microsoft.Web.WebView2` package.  The WinAppSDK NuGet currently declares a dependency on at least version 1.0.2646-prerelease for the WebView2 package.  The fix is in 1.0.2651.64 and later.  If you declare an explicit dependency on `Microsoft.Web.WebView2` for 1.0.2651.64 or later, NuGet should restore the package with the fix.

**Comment by DJRM2021** [comment]
I think WebView2 should be transitively referenced by Windows App SDK NuGet. Thank you for the help.
