### ISSUE TITLE
Critical UI Bug: Qt Application Window Fails to Render Correctly on Monitors with Scaling

### ISSUE THREAD

**Issue by Alicedrop** [microsoft/WindowsAppSDK#4652]
### Describe the bug

I have developed a window using Qt (PySide6), and I encountered a problem when dragging the window between two monitors. The issue specifically occurs when the secondary monitor is set to 150% or other options except  100%  scaling.

When I drag the window from one monitor to another, sometimes the window display becomes distorted, and only about a quarter of the content is visible. Despite the visual distortion, the window still responds to clicks and other interactions as if the full content were displayed normally. The window returns to normal only after I interact with another application window, such as clicking on it.

I also report this bug on Microsoft Commumity. 
https://answers.microsoft.com/en-us/windows/forum/windows_11-wintop_display/critical-ui-bug-qt-application-window-fails-to/cbda0b25-91cd-43f3-9cf4-305555d9a8b6?messageId=28167823-e72f-4bfd-a756-d34408c77e32

### Steps to reproduce the bug

1. Create an Qt Main window with pyside6 at Qt.FramelessWindowHint and Qt.WA_TranslucentBackground
```python
self.setWindowFlags(Qt.FramelessWindowHint)
self.setAttribute(Qt.WA_TranslucentBackground)
```
2. Make sure there is at least 2 screens connected to the computer, Set the secondary screen at 125%  scaling or higher.
3. Drag the window among these screens. 
4. Then you can see the window is sliced.
![image](https://github.com/user-attachments/assets/82736789-a836-4bb3-9f48-17f0c9141e10)

![image](https://github.com/user-attachments/assets/0ea4d16f-1f49-4ade-8e0e-0c438340998e)

### Screenshots

![image](https://github.com/user-attachments/assets/03e104f5-7794-4e11-a750-3395efd3b5e6)
![image](https://github.com/user-attachments/assets/f7217c9c-e2eb-4c50-9d5e-ab0ceddecd7f)

### NuGet package version

None

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Other

**Comment by codendone** [comment]
It sounds like this is not using Windows App SDK. Closing as external.
