### ISSUE TITLE
App Sdk 1.6 Sdk.Net.dll lower version

### ISSUE THREAD

**Issue by jarno9981** [microsoft/WindowsAppSDK#4696]
### Describe the bug

A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly.

### Steps to reproduce the bug

install app sdk 1.6 and then rebuild it and the error will show up

### Expected behavior

that the project compiles on version 1.6 

### Screenshots

<img width="959" alt="error" src="https://github.com/user-attachments/assets/1b3f0097-211e-4db1-a769-925aed57dec3">

### NuGet package version

Windows App SDK 1.6.0: 1.6.240829007

### Packaging type

Packaged (MSIX)

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

**Comment by jarno9981** [comment]
related to SDK 8.0.401 is available but SDK 8.0.402 not for download

**Comment by manodasanW** [comment]
The WinAppSDK release did come out before the .NET SDK servicing update.  But you can follow the [steps in the release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#c-project-changes-1) where you can temporarily specify the `WindowsSdkPackageVersion` property and add a `Microsoft.Windows.CsWinRT` 2.1.1 package reference.  Once the .NET SDK servicing update is out, you can remove the temporary steps.

**Comment by ghost1372** [comment]
@manodasanW 
can you tell us how we can track next .NET SDK servicing update? Should we wait for the Visual Studio update?
How can we find out that the .NET SDK has been updated?

**Comment by jarno9981** [comment]
> @manodasanW 
> can you tell us how we can track next .NET SDK servicing update? Should we wait for the Visual Studio update?
> How can we find out that the .NET SDK has been updated?

Latest .net 8 and latest vs studio 2022 preview

**Comment by LeonSpors** [comment]
This is my temporary solution. Just add it to your **.csproj** and you are good to go.

```csproj
<!-- Workaround, see https://github.com/microsoft/WindowsAppSDK/issues/4696 -->
<ItemGroup Condition="'$(NETCoreSdkVersion)' == '8.0.401'">
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.1.1" />
</ItemGroup>

<PropertyGroup Condition="'$(NETCoreSdkVersion)' == '8.0.401'">
    <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>
</PropertyGroup>
```

**Comment by jarno9981** [comment]
> This is my temporary solution. Just add it to your **.csproj** and you are good to go.
> 
> ```csproj
> 
> <ItemGroup Condition="'$(NETCoreSdkVersion)' == '8.0.401'">
>     <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.1.1" />
> </ItemGroup>
> 
> <PropertyGroup Condition="'$(NETCoreSdkVersion)' == '8.0.401'">
>     <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>
> </PropertyGroup>
> ```

Will try it later

**Comment by ghost1372** [comment]
> This is my temporary solution. Just add it to your **.csproj** and you are good to go.
> 
> ```
> 
> <ItemGroup Condition="'$(NETCoreSdkVersion)' == '8.0.401'">
>     <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.1.1" />
> </ItemGroup>
> 
> <PropertyGroup Condition="'$(NETCoreSdkVersion)' == '8.0.401'">
>     <WindowsSdkPackageVersion>10.0.22621.38</WindowsSdkPackageVersion>
> </PropertyGroup>
> ```

Is `== '8.0.401' ` suitable? Or should we use `<= '8.0.401'` ?

**Comment by jarno9981** [comment]
@LeonSpors  still same issue 'This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref 10.0.26100.38 or later.
    Please update to .NET SDK 6.0.134, 6.0.426, 8.0.109, 8.0.305 or 8.0.402 (or later).
    Or add a temporary Microsoft.Windows.SDK.NET.Ref reference which can be added with:
        <PropertyGroup>
            <WindowsSdkPackageVersion>10.0.26100.38</WindowsSdkPackageVersion>
        </PropertyGroup>


'

**Comment by jarno9981** [comment]
even after adding it to csproj

**Comment by jarno9981** [comment]
The runtime pack for Microsoft.Windows.SDK.NET.Ref was not downloaded. Try running a NuGet restore with the RuntimeIdentifier 'any'.

**Comment by jarno9981** [comment]
fixed with official docs and .net 9 preview 7 is working to

**Comment by manodasanW** [comment]
> @manodasanW can you tell us how we can track next .NET SDK servicing update? Should we wait for the Visual Studio update? How can we find out that the .NET SDK has been updated?

Once the .NET SDK release is out, this [site](https://dotnet.microsoft.com/download/dotnet/8.0) would be updated.

**Comment by jarno9981** [comment]
The fact that even a stable release of app sdk is just fucked because of the fact it cannot build

**Comment by jarno9981** [comment]
@codendone it works for empty projects but for existing project it crashes

**Comment by jarno9981** [comment]
Upgrading to latest visual studio 2022 preview works it fixed the wierd .dll issue

**Comment by fubar-coder** [comment]
Of course it "fixed" it ... by installing a preview version of .NET 9.0. This problem isn't fixed yet for all people using .NET 8.0
