### ISSUE TITLE
Visual Studio Templates don't build

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/WindowsAppSDK#4784]
### Describe the bug

Using the "Blank app, packaged using packaging project for windows application" in Visual Studio 2022 fails to build completely due to NETSDK1083.

### Steps to reproduce the bug

1. Create package-project blank WinUI3 app
2. Fix WindowsSdkPackageVersion
3. Build using command line (`msbuild /bl "/p:Configuration=Debug;Platform=x64"`)

### Expected behavior

No error `NETSDK1083`.

### Screenshots

Binlog: [msbuild.binlog.zip](https://github.com/user-attachments/files/17292238/msbuild.binlog.zip)
Repro Project: [IKVM507.zip](https://github.com/user-attachments/files/17292269/IKVM507.zip)

### NuGet package version

Windows App SDK 1.6.1: 1.6.240923002

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022

### Additional context

This is an official template, which should work out of the box. I don't get why the conditional is included, as it fails immediately.

```
.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.251308be
 MSBuild version:   17.11.3+0c8610977
```

**Comment by haonanttt** [comment]
Hi @AliveDevil , from the Binlog you attached, the issue you report likely related to [.NET SDK uses a smaller RID graph](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph), which you could also see from the error log.

To solve this problem, please try to follow [Recommended action](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/rid-graph#recommended-action) section. And if you have any further question, please let me know.

**Comment by AliveDevil** [comment]
That's the point of this issue.
That this construct:
```
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
```
doesn't work.
