### ISSUE TITLE
Whaere is Microsoft.Windows.AI.Generative?

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/WindowsAppSDK#4816]
There is a lot of public documentation, including https://learn.microsoft.com/en-us/windows/ai/apis/phi-silica and https://learn.microsoft.com/en-us/windows/ai/apis/phi-silica-api-ref?source=recommendations that explains how to use local models on your Copilot+PC, and that the Microsoft.Windows.AI.Generative namespace is part of the WindowsAppSDK, however, it doesn't appear that it's even on the roadmap. Is this a dead-end?

**Comment by filipw** [comment]
according to the [experimental releases page](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-16-experimental-160-experimental2), the latest version is `1.6 Experimental (1.6.0-experimental2)`
but it also says

> Phi Silica and OCR APIs are not included in this release. These will be coming in a future 1.6 release.

**Comment by RDMacLachlan** [comment]
This is coming in a future release.

**Comment by connorMicrosoft** [comment]
Hey folks, we're super happy to share that several new AI APIs have gone live as part of our 1.7 Experimental 3 release! We really appreciate your patience and acknowledge this is releasing later than initially expected. We're excited for you to try them out! Please let us know your thoughts/feedback.

[Release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-17-experimental-170-experimental3)
[Docs](https://learn.microsoft.com/en-us/windows/ai/apis/)
[Samples](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples)

**Comment by MikeYeager** [comment]
I'm not seeing the Microsoft.Windows.AI namespace after updating the SDK to 1.7 Experimental 3. I restarted VS and re-built. I have not yet updated Windows to the latest Insider Preview. Could that possibly be the issue? Thanks.

**Comment by connorMicrosoft** [comment]
> I'm not seeing the Microsoft.Windows.AI namespace after updating the SDK to 1.7 Experimental 3. I restarted VS and re-built. I have not yet updated Windows to the latest Insider Preview. Could that possibly be the issue? Thanks.

Hey Mike, [Windows 11 Insider Preview Build 26120.3073 (Dev and Beta Channels)](https://blogs.windows.com/windows-insider/2025/01/31/announcing-windows-11-insider-preview-build-26120-3073-dev-and-beta-channels/) or later must be installed on your device.

**Comment by MikeYeager** [comment]
I'll get that updated tonight. Thanks!
