### ISSUE TITLE
InputNonClientPointerSource.GetForWindowId throws UnauthorizedAccesException in unpackaged WinForms app

### ISSUE THREAD

**Issue by joreg** [microsoft/WindowsAppSDK#4877]
I'm starting from the [cs-winforms-unpackaged](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing/cs/cs-winforms-unpackaged) sample which works as such.

Now i want to add some interactive areas to the titlebar following the [full-customization example](https://learn.microsoft.com/en-us/windows/apps/develop/title-bar#full-customization-example).

The problem is that calling:

    InputNonClientPointerSource.GetForWindowId(myWindowId);

throws an UnauthorizedAccesException.

What could i be doing wrong?

**Comment by Gaoyifei1011** [comment]
> I'm starting from the [cs-winforms-unpackaged](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing/cs/cs-winforms-unpackaged) sample which works as such.
> 
> Now i want to add some interactive areas to the titlebar following the [full-customization example](https://learn.microsoft.com/en-us/windows/apps/develop/title-bar#full-customization-example).
> 
> The problem is that calling:
> 
> ```
> InputNonClientPointerSource.GetForWindowId(myWindowId);
> ```
> 
> throws an UnauthorizedAccesException.
> 
> What could i be doing wrong?

probably need you to initialize dispatcherqueue
