### ISSUE TITLE
Why WASDK v1.6.241106002 removed from Nuget?

### ISSUE THREAD

**Issue by ghost1372** [microsoft/WindowsAppSDK#4887]
### Describe the bug

Why WASDK v1.6.241106002 removed from Nuget?

![Image](https://github.com/user-attachments/assets/eb99f389-1bdc-4955-b44c-8be83b629a6a)

### Steps to reproduce the bug

https://www.nuget.org/packages/Microsoft.WindowsAppSDK/

### NuGet package version

None

**Comment by ghost1372** [comment]
@RDMacLachlan 
@duncanmacmichael

**Comment by dotMorten** [comment]
It's technically still there but has been unlisted: https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.6.241106002

**Comment by codendone** [comment]
See #4881, and specifically: https://github.com/microsoft/WindowsAppSDK/issues/4881#issuecomment-2480939942

**Comment by ghost1372** [comment]
thank you❤️
