### ISSUE TITLE
Where to find the Microsoft.Windows.AI.Generative namespace?

### ISSUE THREAD

**Issue by Gusha-nye** [microsoft/WindowsAppSDK#4902]
The current Microsoft documentation has the application of Phi-3's API and its required namespace Microsoft.Windows.AI.Generative. and describes Microsoft.Windows.AI.Generative as part of the Windows Application SDK (https://learn.microsoft.com/en-us/windows/ai/apis/phi-silica and https://learn.microsoft.com/en-us/windows/ai/apis/phi-silica-api-ref?source=recommendations). But using Copilot+PC in Visual studio, I created either WinUI3 application or .NET Forms application and installed the various versions of Windows Application SDK given in Microsoft's documentation (including Experimental, Stable, and Preview) through Nuget Package Manager in VS. But still can't find the Microsoft.Windows.AI.Generative namespace, how to solve this problem?  Is it because all the current releases don't contain this namespace or it requires some specific environment configuration?

**Comment by ghost1372** [comment]
you need to wait for wasdk v1.7, AI Api is not released yet

**Comment by Gusha-nye** [comment]
> you need to wait for wasdk v1.7, AI Api is not released yet

Thank you for your reply

**Comment by filipw** [comment]
1.7 experimental-2 was released yesterday and it does not have the Phi Silica APIs. What happened?

https://github.com/microsoft/WindowsAppSDK/releases/tag/v1.7-exp2
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-17-experimental-170-experimental2

**Comment by ghost1372** [comment]
> 1.7 experimental-2 was released yesterday and it does not have the Phi Silica APIs. What happened?
> 
> https://github.com/microsoft/WindowsAppSDK/releases/tag/v1.7-exp2
> https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-17-experimental-170-experimental2

There is a showcase for Windows Copilot Runtime APIs, but it is unclear it is included in exp2 or it is in a new nuget package or mybe next exp

**Comment by connorMicrosoft** [comment]
Hey folks, we're super happy to share that several new AI APIs have gone live as part of our 1.7 Experimental 3 release! We really appreciate your patience and acknowledge this is releasing later than initially expected. We're excited for you to try them out! Please let us know your thoughts/feedback.

[Release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-17-experimental-170-experimental3)
[Docs](https://learn.microsoft.com/en-us/windows/ai/apis/)
[Samples](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples)
