### ISSUE TITLE
Project Reunion project system should be decoupled from installed Windows SDK

### ISSUE THREAD

**Issue by evelynwu-msft** [microsoft/WindowsAppSDK#546]
The .NET 5 project templates for Project Reunion (via the `TargetFramework` property) have a dependency on a specific version of the Windows SDK (currently `19041`). This can result in being unable to successfully compile a newly-created Project Reunion app with a fresh VS install if VS changes the default installed Windows SDK (WinUI encountered [this](https://github.com/microsoft/microsoft-ui-xaml/issues/4062) as its own project templates specify `18362` as the target Windows version but VS 16.9 changed the default installed Windows SDK to `19041`) since MRT Core defaults to locating `makepri.exe` from an existing Windows SDK installation.

To avoid this, the Project Reunion Nuget package should specify a Nuget package dependency against [`Microsoft.Windows.SDK.BuildTools`](https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools/10.0.18362.3-preview); this will result in the requisite SDK tools being acquired from the Nuget package rather than depending on a pre-existing installation of a specific SDK version.

**Comment by riverar** [comment]
Is there a cooresponding `Microsoft.Windows.SDK.BuildTools` for targeting 19041+?

**Comment by riverar** [comment]
Think you want https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts/10.0.19041.1 for Reunion use right? (Your link points to the 18362 nuget.)

**Comment by alwu-msft** [comment]
For this particular issue, we specifically need the BuildTools Nuget package; ideally it would be the 19041 tools (I don't know why nothing newer than 18362 is available, but that might just be because the issue has yet to be forced) but to the best of my knowledge the 18362 tools are still sufficient.

**Comment by riverar** [comment]
@alwu-msft Sorry, in correcting your link I also pasted the wrong link. Doh! I now see the tooling is stuck at 18362 for some reason.

**Comment by Scottj1s** [comment]
Microsoft.Windows.SDK.BuildTools is not a complete replacement for the Windows SDK (as the title of this issue suggests) - it only contains build tools, not libs, includes, metadata, etc.  You could instead adopt the [Microsoft.Windows.SDK.CPP](https://www.nuget.org/packages/Microsoft.Windows.SDK.CPP/) package, which does provide those assets, but at over 100MB, users may prefer to stick with the Windows SDK.  If the original problem here was that mt.exe couldn't find a dependency, based on [hardcoded assumptions](https://github.com/microsoft/microsoft-ui-xaml/issues/4062#issuecomment-771249074), maybe we should fix that?  As a stopgap, we could assert a specific version of the Windows SDK.

**Comment by alwu-msft** [comment]
Yeah, we're fixing the mt.exe/makepri.exe hard-coded assumptions (via the BuildTools package). That's an interesting point about headers/libs/metadata/etc. Those weren't really on our radar as there isn't a hard dependency on a specific version of the SDK there (our templates are set up to use whatever is the highest version installed).
