### ISSUE TITLE
Add AppLifecycleTests to Helix

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/WindowsAppSDK#557]
The github pipeline runs as a built-in Administrator account thus it always runs tasks as Elevated.
Dynamic Dependencies doesn't support elevation (today)
Thus AppLifecycle's tests can't be run directly by the github pipeline
But Helix is now up for test execution

Add the AppLifecycleTests to the Helix test environment

https://task.ms/34107070

**Comment by LegendaryBlair** [comment]
Close this issue as the internal task is cut.
