### ISSUE TITLE
DevCheck doesn't verify VS components

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/WindowsAppSDK#584]
`tools\DevCheck.ps1` (conveniently accessible by running `tools\DevCheck.cmd`) verifies the local development environment is ready and often can (and will) update the environment as needed e.g. make sure the TAEF service is installed.

Building ProjectReunion.sln and others in the repository require many Visual Studio components, not all of them obvious. Trying to build without the right components installed can be a frustrating experience to identify what's missing and which of Visual Studio Updater's zillions of options are needed. DevCheck needs to verify the required components are present. This includes the right versions of the Windows SDK, .NET Core and other components. These can be detected via [vswhere.exe](https://github.com/Microsoft/vswhere) to check for the expected [workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019).

DevCheck currently pulls down the latest vswhere to do checks (unless -Offline is specified). It can also be found at `%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe`. DevCheck should use the local copy by default and grab and use the remote copy if -VSWhere:Latest is specified.

**Comment by riverar** [comment]
@DrusTheAxe If you want to try farming this out to the community, I'd be happy to work on this.

**Comment by DrusTheAxe** [comment]
> @DrusTheAxe Howard Kapustein FTE If you want to try farming this out to the community, I'd be happy to work on this.

Submissions are always welcome :-)

By all means, have at it. It's something we've long talked about to reduce dev pain. Mine finally exceeded the tolerable threshold so I started the ball rolling but always more to do... I've got more urgent tasks on my plate and I expect others do too so you're not likely to see much competition near term.

Particular pain points I'm aware of:

* Windows SDKs - we need RS5 + latest. I forget the build numbers, they're referenced in ProjectReunion_DLL.vcxproj. MRTCore happens to have a reference to a different version, which is a bug; all *.vcxproj should reference the same SDKs
* ARM64 tools - couple of folks had troubling building due to not having the ARM64 compiler installed
* .NET Core - I saw this recently, think I was building one of MRTCore's (test?) projects

Those are just the past problematic items I know offhand. There's more we should verify - whatever components are required to build everything in this repository. The intent is you can run DevCheck once when setting up your environment, and then occasionally to verify you're still good e.g. it should check for a VS2019's version >= x and since VS updates nigh weekly we'll probably update the check to semi-regularly (probably per milestone, maybe more often if important).

As for the VS component tests...we want DevCheck to flag but not fix; that's best handled by the developer. So the logic for each component amounts to

```powershell
$output = $vswhere args
if ($output -contains expected)
{
    Write-Host "Visual Studio Blah...OK"
}
else
{
    Write-Host "Visual Studio Blah...Badness"
}
```

where 'Blah' is ideally whatever name VSUpdater calls it (so it's easy for devs to know which of the zillion similarly named components to pick)

**Comment by DrusTheAxe** [comment]
I just hopped onto another machine and found out (the hard way) the following components are required or opening projectreunion.sln produces several errors about not understanding ARM64 in ProjectReunion_DLL and AppLifecycle(Tests?) projects

VS needs these 2 components to satisfy
* C++ Universal Windows Platform support for v142 build tools (ARM64)
* MSVC v142 - VS 2019 C++ ARM64 build tools (Latest)

**Comment by DrusTheAxe** [comment]
I had VSInstaller export configs from a couple of machines and compared to help figure out commonalities:

```
{
  "version": "1.0",
  "components": [
    "Microsoft.Component.MSBuild",
    "Microsoft.Component.VC.Runtime.UCRTSDK",
    "Microsoft.ComponentGroup.Blend",
    "Microsoft.Net.Component.4.8.SDK",
    "Microsoft.NetCore.Component.Runtime.3.1",
    "Microsoft.NetCore.Component.Runtime.5.0",
    "Microsoft.NetCore.Component.SDK",
    "Microsoft.VisualStudio.Component.AppInsights.Tools",
    "Microsoft.VisualStudio.Component.ClassDesigner",
    "Microsoft.VisualStudio.Component.CodeMap",
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Microsoft.VisualStudio.Component.DiagnosticTools",
    "Microsoft.VisualStudio.Component.GraphDocument",
    "Microsoft.VisualStudio.Component.Graphics.Tools",
    "Microsoft.VisualStudio.Component.IntelliCode",
    "Microsoft.VisualStudio.Component.IntelliTrace.FrontEnd",
    "Microsoft.VisualStudio.Component.JavaScript.TypeScript",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.VisualStudio.Component.Roslyn.LanguageServices",
    "Microsoft.VisualStudio.Component.SQL.CLR",
    "Microsoft.VisualStudio.Component.SQL.LocalDB.Runtime",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.TypeScript.4.1",
    "Microsoft.VisualStudio.Component.UWP.VC.ARM64",
    "Microsoft.VisualStudio.Component.VC.ASAN",
    "Microsoft.VisualStudio.Component.VC.ATL",
    "Microsoft.VisualStudio.Component.VC.CMake.Project",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.Component.VC.DiagnosticTools",
    "Microsoft.VisualStudio.Component.VC.Tools.ARM64",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Microsoft.VisualStudio.Component.Windows10SDK.17134",
    "Microsoft.VisualStudio.Component.Windows10SDK.17763",
    "Microsoft.VisualStudio.Component.Windows10SDK.18362",
    "Microsoft.VisualStudio.Component.Windows10SDK.19041",
    "Microsoft.VisualStudio.ComponentGroup.ArchitectureTools.Native",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.VisualStudio.Workload.NativeDesktop",
  ]
}
```

Some of those aren't necessary but all the required components are in there. A starting point for the DevCheck vswhere work.

**Comment by bpulliam** [comment]
Fixed with https://github.com/microsoft/WindowsAppSDK/pull/3188
