### ISSUE TITLE
Add a WACK check to the build pipeline

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/WindowsAppSDK#585]
The build pipeline runs (or will) various tools against the repository and build artifacts (credscan, binskim, etc). The [Windows App Certification Kit](https://developer.microsoft.com/en-us/windows/downloads/app-certification-kit/) should be added to the build process.

**Comment by BenJKuhn** [comment]
Note I've also opened this in our internal scheduling system as a [here (Microsoft FTE only)](https://dev.azure.com/microsoft/OS/_workitems/edit/32125757).

**Comment by BenJKuhn** [comment]
this would be a nice-to-have, but since the application packages are full-trust apps, not UWP, the amount of coverage this would provide is marginal. It will still run on store submission, but so far has not been a source of friction. Closing for now.
