### ISSUE TITLE
Files are copied twice into application package

### ISSUE THREAD

**Issue by lhak** [microsoft/WindowsAppSDK#587]
**Describe the bug**

The packaging project copies files twice into the package output folder. One time into the root directory and one time into a subdirectory

**Steps to reproduce the bug**

1. Create a new c# winui desktop project 
2. Build and deploy the package
3. Observe that multiple files get copied twice into the AppX output directory and in the subfolder with the application name (e.g. Microsoft.ui.xaml.dll). Same issue can be observed when building an msix package
4. Adding a file (e.g. a text file) to the project, setting its type to "content" and enabling the "copy to output folder" option results in the same issue

**Expected behavior**

Files should only be copied once. Preferably, they should be copied into the root directory of the package folder to avoid differences to future unpackaged deployment. 

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.ProjectReunion 0.5.0-prerelease]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

http://task.ms/37784910

**Comment by EricJohnson327** [comment]
Verified no repro in latest builds.
