### ISSUE TITLE
DevCheck: Verify Powershell ExecutionPolicy

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/WindowsAppSDK#635]
Building ProjectReunion.sln fails with cryptic errors if Powershell's ExecutionPolicy isn't set appropriately e.g.

```
("Error: Store IsDiskFile() failed." (-2147024893/0x8007003) An unexpected error has occurred"
```

DevCheck needs to verify ExecutionPolicy and set it if necessary e.g.

```
PS C:\WINDOWS\system32> get-executionpolicy -list

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted
```

Suggestion: `Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser`

**Comment by riverar** [comment]
Rather than affect the entire machine, I propose we evaluate if these scripts are necessary and if so, perhaps shell out explicitly at that time with `-ExecutionPolicy Bypass`.

**Comment by riverar** [comment]
Taking notes, don't mind me.

This is required because of `DynamicDependencyLifetimeManager.Msix` dependency at this time.

https://github.com/microsoft/ProjectReunion/blob/90f5bb8efd3bad0361caa7bdbc75cd111df1c6ec/test/DynamicDependency/data/DynamicDependencyLifetimeManager.Msix/Makefile.mak#L56-L58

https://github.com/microsoft/ProjectReunion/blob/90f5bb8efd3bad0361caa7bdbc75cd111df1c6ec/tools/MakeAppxManifestFromTemplate.cmd#L1-L3

**Comment by DrusTheAxe** [comment]
Not just that project. Generally speaking, anything using Powershell to supplement VS processing. The *.msix projects do it to assist in package generation but there's likely more things in the future. For instance [Update DynamicDependencies use build information (version, package names, DDLM CLSID, etc) #561](https://github.com/microsoft/ProjectReunion/issues/561) may need a script assist

**Comment by DrusTheAxe** [comment]
> Rather than affect the entire machine, I propose we evaluate if these scripts are necessary and if so, perhaps shell out explicitly at that time with `-ExecutionPolicy Bypass`.

They are necessary, for the forseeable future at least (long-term I'd like to see them go away if/when we can bake out *.props etc logic).

`-ExecutionPolicy Bypass` is interesting. I'm not clear on all the implications but it's something to consider. Thanks for the suggestion

**Comment by riverar** [comment]
Fair, just taking some notes as I'm working on DevCheck now.

I don't think adding more scripts is the right approach for versioning. (I proposed GitVersion tasks in another issue somewhere.) I think we should generally try to avoid scripting in general during build, unless absolutely necessary.

**Comment by DrusTheAxe** [comment]
> we should generally try to avoid scripting in general during build, unless absolutely necessary.

Absolutely agreed. In this case it might be possible to replace the script with multiple appxmanifest varying only by architecture. Has its own ugly implications. And 0% script may not be possible but it's an admirable goal - long as the cure isn't worse than the disease.

**Comment by DrusTheAxe** [comment]
DevCheck.cmd runs powershell with -ExecutionPolicy Unrestricted -NoLogo -NoProfile

That seems to address the concerns. If further improvements are desired (or suggested) we can follow up with a new issue a bit more fine tuned given the current state of the world
