### ISSUE TITLE
Treat warnings as errors

### ISSUE THREAD

**Issue by aeloros** [microsoft/WindowsAppSDK#670]
We should enable warnings as errors in the project reunion code base.

**Comment by BenJKuhn** [comment]
This is a great suggestion. The binaries come from various projects, but we can certainly turn this on in the open repo, and we can also enforce this during aggregation by validating the build settings that are captured in the PDB's. Assigned to @DefaultRyan.

**Comment by aeloros** [comment]
We should make sure this get's done sooner than later, as it's hard to stop the influx of warnings if it gets out of hand. :)

**Comment by bpulliam** [comment]
There are OneBranch warnings keeping us from doing this.
