### ISSUE TITLE
Launcher.LaunchFileAsync fails after explorer.exe has been restarted

### ISSUE THREAD

**Issue by mqudsi** [microsoft/WindowsAppSDK#69]
I know this isn't the right repository for it, but I honestly don't know where else to post this.

On Windows 10 (I believe all versions but confirmed on 18363), there is some sort of core functionality that is not restarted when the main explorer.exe instance (the one hosting the start menu and the desktop) is killed (e.g. `taskkill /f/ im explorer.exe`) and then subsequently restarted (e.g. by running `explorer.exe` in the task manager's run dialog), UAP apps are no longer able to use `Launcher.LaunchAsync()` to launch files associated with non-UAP applications.

e.g. 

* before restarting explorer.exe, trying to open `foo.jpg` or `foo.pdf`, `Launcher.LaunchAsync` returns true
* after restarting explorer.exe, trying to open `foo.jpg` associated with the UAP photos app: `Launcher.LaunchAsync()` returns true
* after restarting explorer.exe, trying to open `foo.pdf` associated with Adobe Acrobat DC (non-UAP app), `Launcher.LaunchAsync()` returns false

**Comment by Jaiganeshkumaran** [comment]
@mqudsi This is an internal Windows bug, so you should report this to Microsoft via Feedback hub.

**Comment by jonwis** [comment]
Thanks for the report, we're looking at this via http://task.ms/26890318

**Comment by mqudsi** [comment]
Thanks, @jonwis. If at all possible, I'd appreciate a tip on the resolution, whenever that may be.

**Comment by mqudsi** [comment]
fwiw, it also happens if explorer was exited cleanly (via ctrl+shift+right-click on taskbar followed by "Exit Explorer") then restarted.

**Comment by andreww-msft** [comment]
Hi @mqudsi - thanks for filing this issue. We have investigated, but unfortunately we cannot reproduce the issue, so I suspect it might be something specific to your machine - might be worth checking you have all the latest updates, etc.

**Comment by mqudsi** [comment]
I'm still on 18363, so I guess there's hope it's been fixed in an update!
