### ISSUE TITLE
FileActivatedEventArgs should have an optional NeighboringFilesSortOrder property

### ISSUE THREAD

**Issue by benstevens48** [microsoft/WindowsAppSDK#736]
# Proposal: FileActivatedEventArgs should have a NeighboringFilesSortOrder property

## Summary
The `FileActivatedEventArgs` class should have a property `NeighboringFilesSortOrder` which has a type equivalent to [Windows.Storage.Search.SortEntry](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.sortentry?view=winrt-19041), and it should be nullable since it's optional. This would be set by the launcher (e.g. File Explorer) when launching an app with a single file, in order to suggest an initial ordering of neighboring files. For example if a file is double-clicked in File Explorer, then File Explorer will provide the file path along with current sort order of the directory (maybe only if it is not in the default name-ascending order).

## Rationale
* In UWP the `FileActivatedEventArgs` class has a `NeighboringFilesQuery` property to access the neighboring files. There are many problems with this, in addition to the fact that it suffers from the slow speed of creating StorageFiles. For example, it seems to use the indexer, so it is unreliable and frequently misses all or some files in the directory. It's also awkward to save it for later use etc. However, one good thing about it is that when provided by File Explorer, it uses the current sort order of the folder, which is intuitively what the user expects. (I have seen a user sort photos by date in File Explorer then open the first one by double-click and rely on the fact that the app loads the photos in the same order). Currently I don't think there is a way of maintaining this behavior without the neighboring files query. Hence the solution of adding a `NeighboringFilesSortOrder` property.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to (mostly) maintain the ordering functionality offered by UWP's NeighboringFilesQuery without having to use NeighboringFilesQuery  (assuming the necessary file access permissions) | Must |
| This proposal will allow the launcher to signify the intent of loading neighboring files, either by the presence of `NeighboringFilesSortOrder` or an additional boolean property. | Could |
| This proposal will change file access permissions | Won't |

## Important Notes
This would require cooperation of the launching app - most importantly, File Explorer would probably need to be updated to provide this property.

There is another discussion to be had on file access permissions (that's another reason why NeighboringFilesQuery exists, and I think a lot of us would like to be able to work around that problem) but it should happen separately.

## Open Questions
Should there be another property `bool IncludeNeighboringFiles` or similar, to suggest that neighboring files should be loaded (just as a hint to the app being launched)? This could be inferred from the presence of `NeighboringFilesSortOrder`, but it might be best to allow that to be null to indicate no preference in the sort order, but still allow the indication that neighboring files should be loaded.

Should `NeighboringFilesSortOrder` actually be of type `IVectorView<SortEntry>`, i.e. a list, which covers the most general case of ordering? This would match [QueryOptions.SortOrder](https://docs.microsoft.com/en-us/uwp/api/windows.storage.search.queryoptions.sortorder?view=winrt-19041).

**Comment by andrewleader** [comment]
Hey @andreww-msft, we think this feature request might be related to AppLifecycle.

**Comment by andreww-msft** [comment]
Hi @benstevens48  - my apologies for the delay in replying. Thanks for the suggestion. I've added it to the backlog for consideration for a future release. Internal ID for reference is 37595633.
