### ISSUE TITLE
Unable to build after adding third-party library (SyncFusion)

### ISSUE THREAD

**Issue by nickrandolph** [microsoft/WindowsAppSDK#745]
**Describe the bug**
Adding a reference to the SyncFusion WinUI NuGet package ([Syncfusion.Chart.WinUI](https://www.nuget.org/packages/Syncfusion.Chart.WinUI)) causes a build error:
_NETSDK1148	A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly._

**Steps to reproduce the bug**
1. Install the [Project Reunion extension](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion) for Visual Studio
2. Create a new application based on the "Blank App, Packaged (WinUI 3 in Desktop)" Visual Studio template 
3. Fix application to ensure it builds and runs ([instructions here](https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release))
4. Add reference to [Syncfusion.Chart.WinUI](https://www.nuget.org/packages/Syncfusion.Chart.WinUI) NuGet package 
5. Application fails to build and run with error
_NETSDK1148	A referenced assembly was compiled using a newer version of Microsoft.Windows.SDK.NET.dll. Please update to a newer .NET SDK in order to reference this assembly._

**Expected behavior**
Application should continue to build and run

**Screenshots**
![image](https://user-images.githubusercontent.com/1614057/115318232-b48f1200-a1c0-11eb-8969-bc058674b7de.png)

NuGet package version: 0.5.5

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)            | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by jeganraj-m** [comment]
@nickrandolph 
Can you explicitly set your .NET SDK to the latest version as below and check?
![image](https://user-images.githubusercontent.com/74640452/115352462-03df3d80-a1d5-11eb-89c3-060a9834e11a.png)

Refer 1st step in upgrade guideline. Syncfusion controls works fine on our side after making this change. 

https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release

**Comment by nickrandolph** [comment]
@jeganraj-m I had this as step 3 in my repro steps. Still fails to build

**Comment by jeganraj-m** [comment]
@nickrandolph I followed your steps and checked Syncfusion controls, but it works for me.
I have attached the project, can you check what i'm missing?
[SyncTest.zip](https://github.com/microsoft/ProjectReunion/files/6342316/SyncTest.zip)

Note: The only change I made in your replication steps is updated the SDK version from 10.0.18362.16 to 10.0.19041.16

**Comment by nickrandolph** [comment]
Yep, tried again with updating to latest sdk version (i.e. changing 18362 to 19041) and forcing a rebuild. This seems to work. 
@andrewleader is this a workaround that should be added/changed in the update documentation?

**Comment by andrewleader** [comment]
@zaryaf @anawishnoff  it looks like we might need to add this note/workaround to the docs, can you look into that?

**Comment by anawishnoff** [comment]
Thanks for pointing this out! Looks like that version number does need to get updated in the docs. 

@Scottj1s Do you see any issues with this?

**Comment by manodasanW** [comment]
The version number used is dependent on what the app is targeting.  If they are targeting 19041, they should specify 19041.16 in the FrameworkReference update.  If they are targeting 18362, they should specify 18362.16.  We should update the docs to reflect that.

**Comment by anawishnoff** [comment]
Thanks for the clarity here @manodasanW! I'll follow up with you about doc updates.
