### ISSUE TITLE
DeriveAppContainerSidFromAppContainerName doesn't work if container name same as caller package family name

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/WindowsAppSDK#787]
**Describe the bug**

When [`DeriveAppContainerSidFromAppContainerName`](https://docs.microsoft.com/en-us/windows/win32/api/userenv/nf-userenv-deriveappcontainersidfromappcontainername) is used get sid for a package family name, if package family name is same as caller package family name the function call succeeds (no error code returned) but sid isn't retrived.

**Steps to reproduce the bug**

1. Create sample cppwinrt console application.
2. Create new packaging project and add the above console application project as reference.
3. Add following snippet to the main function with required headers and namespaces, and deploy the package.
```
PSID pSid = NULL;
check_hresult(DeriveAppContainerSidFromAppContainerName(Package::Current().Id().FamilyName().c_str(), &pSid ));
if (pSid == NULL)
{
    printf("Failed to retrieve sid");
}
```
4. When running the console app see output on console.

**Expected behavior**

Should retrieve sid even if package family name are same.

**Version Info**

Not applicable.

NuGet package version:  Not applicable

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

This is necessary for [sharing named objects](https://docs.microsoft.com/en-us/windows/uwp/communication/sharing-named-objects) between uwp and win32 process packaged together.

**Comment by soumyamahunt** [comment]
Not sure if this issue is scope of reunion but it sill is an issue with windows api.

**Comment by andrewleader** [comment]
Hi @soumyamahunt, thanks for reporting this.

I think there might be a different way of using this API, but looking at the docs you referenced, they don't explain much at all, seems like we definitely have to improve our docs.

The main dev that knows this area the best is currently out-of-office till 5/17. Another dev mentioned that this API you're using will drive the SID of a **child** AppContainer if it's invoked from **within** an AppContainer - you can NOT use this API to pass in a package family name and get the SID of the (non-child) AppContainer within which you're currently running.

We'll hopefully have a better answer the week of 5/17 for you, I apologize for the delay. I'll work with the team to get the docs updated too!

**Comment by zrajnai-shapr3d** [comment]
Any updates on this?!

**Comment by LegendaryBlair** [comment]
If you pass the package full name or name, the SID can be retrieved. 

`DeriveAppContainerSidFromAppContainerName(Package::Current().Id().FullName().c_str(), &pSid3)`
`DeriveAppContainerSidFromAppContainerName(Package::Current().Id().Name().c_str(), &pSid)`

Hi @soumyamahunt, Let me know if you still require package family name.

**Comment by LegendaryBlair** [comment]
No additional response from customer, hence closing the issue.
