### ISSUE TITLE
Investigate options for dynamic allocation of the SharedProcessList.

### ISSUE THREAD

**Issue by aeloros** [microsoft/WindowsAppSDK#791]
this constant governs how many simultaneous (temporary) instances of a single instance app we can arbitrate amongst?

_Originally posted by @EHO-makai in https://github.com/microsoft/ProjectReunion/pull/772#discussion_r622491885_

**Comment by haonanttt** [comment]
Confirmed with Scott that this issue is primarily a reminder and can be closed, as its value has diminished given the significant complexities involved
