### ISSUE TITLE
Cannot create app packages if app references C++ class library. Reunion 0.5.7

### ISSUE THREAD

**Issue by mjfusa** [microsoft/WindowsAppSDK#824]
**Describe the bug**

When attempting to **Publish** > **Create app packages** for a Reunion desktop app, the following error is generated:

```C++/CLI projects targeting .NET Core cannot use SelfContained=true.	App12Reunion (Package)	C:\Program Files\dotnet\sdk\5.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets```

If the app is referencing a .NET 5.0 C++ Class Library. This library does not contain or expose any WinRT types. This app builds and runs without problems.

**Steps to reproduce the bug**

1. Clone this project: https://github.com/mjfusa/Sample-Reunion-Store-IAP.git
2. Right Click on App12Reunion app , Add > Project Reference > CPPClassLibrary
3. Follow Steps 8 - 10 below.

Or follow these steps to create project:
1. In Visual Studio 2019, select File -> New -> Project.
2. In the project drop-down filters, select C#, Windows, and WinUI, respectively.
3. Select the Blank App, Packaged (WinUI 3 in Desktop) project type and click Next.
4. Accept all defaults to create the project.
5. Right click on Solution. Select Add New Project. Select CLR Class Library (.NET Core) C++
6. Accept all defaults to create the project.
7. Right Click on Main app created in Step3, Add > Project Reference > Check the Class Library created in Step 5.
8. Build and run app.
9. No build or runtime error should be observed.
10. Right click on Packaging Project. Select Publish > Create App Packages - Follow sideloading path and x64 only.

**Expected behavior**

Packages should be created without errors.

**Actual behavior**
Package build interrupted with build error - _see in description above._

**Version Info**

Project Reunion 0.5.7

NuGet package version: 

Microsoft.ProjectReunion 0.5.7

21H1 19043

**Additional context**

**Comment by astritz** [comment]
This looks not to be related to WindowsAppSDK, but rather a problem with including the Class Library when SelfContained.

The same issue was encountered here:
https://github.com/dotnet/sdk/issues/12345
... with a subsequent reply containing a work-around:
```
<!-- Disable the .NET SDK error that prevents using SelfContained=true -->
<Target Name="_CheckForLanguageAndFeatureCombinationSupport"></Target>

```
