### ISSUE TITLE
Proposal: Expose OCR APIs

### ISSUE THREAD

**Issue by BillHoag** [microsoft/WindowsAppSDK#867]
# Proposal: Expose OCR APIs for use by unpackaged desktop apps

## Summary
As noted [here](https://docs.microsoft.com/en-us/uwp/api/Windows.Media.Ocr?view=winrt-20348), currently, Windows.Media.Ocr classes are only available to desktops with package identity (installed and run from an MSIX package). This proposal would like to have OCR features available to unpackaged desktop apps.

## Rationale
* Windows.Media.Ocr is a largely untapped resource due to its constraints of availability.
* Unpackaged desktop apps in particular cannot use Windows OCR.
* Project Reunion would provide a consistent form of access to both packaged and unpackaged apps.
* Project Reunion would be a great way to provide OCR in a consistent way to many types of Windows apps.
* Greater availability of OCR will help improve Accessibility of features, especially for users with visual impairments.
* Greater usage of OCR can generate feedback and impetus for improvements to OCR.

## Scope
| Capability | Priority |
| :---------- | :------- |
| Include the full set of OCR APIs and functionality | Must |
| Initial slice could include a subset of OCR APIs and functionality | Could |

## Important Notes
OCRs APIs and functionality should be available to unpackaged native and managed desktop apps, as well as packaged apps.

**Comment by andrewleader** [comment]
Hey Bill, thanks for the feature request! I'll talk with the team about looking at this for a future version of Reunion.

**Comment by chigy** [comment]
Thank you for the feature request. In order for us to be transparent to our community members, we are proactively closing any feature requests that we do not believe we can realistically get to in the next 1-2 years. If you feel this is feature is critical and urgent, and need to be prioritized over other issues our team is currently looking to delivering, please add detailed information about how the app ecosystem would benefit from it when reopening the issue. It will be very helpful for us, thanks!

**Comment by grishy** [comment]
Hey @chigy !
What do you think about this feature now?

**Comment by chigy** [comment]
@grishy There are no new information for us to think differently about this feature request. Do you have some new thoughts you want to share?

**Comment by lauren-ciha** [comment]
I'd also like to add: there are new OCR APIs available in [Windows App SDK 1.7.2 and above](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/release-notes/windows-app-sdk-1-7?pivots=stable#version-172-17250513003). See the [tutorial](https://learn.microsoft.com/en-us/windows/ai/apis/text-recognition) and [API reference](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.windows.ai.imaging?view=windows-app-sdk-1.8) for more information. These APIs do require package identity, however, you can add package identity to an unpackaged app by [granting package identity with external location](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps-overview). Would this fit your use case?

For links: https://github.com/microsoft/WindowsAppSDK/issues/867
