### ISSUE TITLE
Failing AppLifecycle unit tests

### ISSUE THREAD

**Issue by pmpurifoy** [microsoft/WindowsAppSDK#878]
AppLifecycle unit tests failing some tests:
Test::AppLifecycle::FunctionalTests::GetActivatedEventArgsForFile_Win32 [Failed]
Test::AppLifecycle::FunctionalTests::GetActivatedEventArgsForProtocol_Win32 [Failed]
Test::AppLifecycle::FunctionalTests::SingleInstanceTest_Win32 [Failed]
Test::AppLifecycle::APITests::GetActivatedEventArgsIsNull_UAP [Blocked]
 
1. Clean/Build PR
2. Run AppLifecycle unit tests

Expected Behavior:
All test cases passing.

This is happening on main branch.

Test::AppLifecycle::APITests::GetActivatedEventArgsIsNull_UAP [Blocked] 
- This test is blocked because it cannot find the PRfwk dependency when the test is ran.

**Comment by DrusTheAxe** [comment]
No longer a problem
