### ISSUE TITLE
Missing symbols for many Project Reunion binaries.

### ISSUE THREAD

**Issue by WamWooWam** [microsoft/WindowsAppSDK#884]
**Describe the bug**
Visual Studio is unable to find symbols for the following Project Reunion binaries on the Microsoft Symbol Server:

 - ~~`dcompi.dll` (x86/x64)~~ Available as of 30/05/2021
 - ~~`Microsoft.InputStateManager.dll` (x86/x64)~~ Available as of 30/05/2021
 - ~~`Microsoft.UI.Input.dll` (x86/x64)~~ Available as of 30/05/2021
 - ~~`Microsoft.DirectManipulation.dll` (x86/x64)~~ Available as of 30/05/2021
 - `Microsoft.UI.Windowing.dll` (x86/x64)
 - `Microsoft.UI.Windowing.Core.dll` (x86/x64)

**Steps to reproduce the bug**
 - Throw an exception or hit a breakpoint basically anywhere within a WinUI 3 project with native code debugging enabled, the default `myButton_Click` handler works fine.
 - Open the Modules viewer in Visual Studio (Debug -> Windows -> Modules)
 - Note the Project Reunion binaries marked `Cannot find or open the PDB file.`

**Expected behavior**
Visual Studio and other tools are able to load symbols for all Project Reunion binaries.

**Screenshots**
![image](https://user-images.githubusercontent.com/11337731/119999820-0f8b0480-bfca-11eb-873a-03f9ee401afd.png)
![image](https://user-images.githubusercontent.com/11337731/119999878-1e71b700-bfca-11eb-8d33-d1e5a4c0bf16.png)

**Version Info**
NuGet package version: 
Microsoft.ProjectReunion 0.8.0-preview
Microsoft.ProjectReunion.Foundation 0.8.0-preview
Microsoft.ProjectReunion.InteractiveExperiences 0.8.0-preview
Microsoft.ProjectReunion.WinUI 0.8.0-preview

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 (19043)            |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
I'm honestly not sure if we're meant to be able to access `Microsoft.UI.Windowing` however the `Microsoft.ProjectReunion.InteractiveExperiences` package does exist and is consumable.

**Comment by WamWooWam** [comment]
It appears some additional symbols are now available on the Microsoft Symbol Server, however some still aren't. I've updated the primary issue to reflect this.

**Comment by riverar** [comment]
Also missing (0.8-preview):
* DWriteCore.dll
* Microsoft.Web.WebView2.Core.dll

**Comment by andrewleader** [comment]
@axelandrejs or @BenJKuhn would this fall under your responsibility?

**Comment by riverar** [comment]
Any updates? Really don't want this issue to bleed into 1.0 release!

**Comment by andrewleader** [comment]
@DefaultRyan is looking into this

**Comment by DefaultRyan** [comment]
I tried the latest 0.8.7 build, and I don't see Microsoft.UI.Windowing.Core.dll included there, but I am now successfully loading symbols from WebView2. There are missing symbols for the old 0.8.x version of DWriteCore, but I don't realistically see that binary getting serviced any time soon.

If there are any other remaining symbol issues, or new ones that have cropped up, please let us know.
