### ISSUE TITLE
Elevated/administrator isn't supported in MSIX WinAppSDK app on Windows 10

### ISSUE THREAD

**Issue by ivberg** [microsoft/WindowsAppSDK#896]
Feature status | Available in | Explanation
----|----|---
🔄️<br>In preview | Windows Insider Build 22000 | Supporting elevated packaged apps using framework package APIs (like WinAppSDK and WinUI 3) required **OS-level changes**. Thus, this fix is only available in Windows 11 and higher. You can try Windows Insider Build 22000 which should have this fix!

**Describe the bug**
Cannot F5/Debug Administrator Project Reunion App.

Program will elevate and launch. Visual Studio Debugger will appear to attach to the process but no breakpoints can be hit.

Workaround: Detach and re-attach to process OR deploy/launch app and then attach to it.

**Steps to reproduce the bug**

1. Produce a C# Reunion 0.5 OR Reunion 0.8 Preview app
2. Modify app.manifest
--app.manifest--
`
\ <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
     <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator"/>
      </requestedPrivileges>
    </security>
  </trustInfo>  \
`
3. For MSIX package modify capabilities to allow Elevation
`
 \ <Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <rescap:Capability Name="allowElevation" />
  </Capabilities>  \
`

**Expected behavior**
You can launch and debug app w/o needing workarounds

**Screenshots**

**Version Info**

Reunion 0.5 OR Reunion 0.8 Preview app
`
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7" />
`

OR
`
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21996)              | Yes   |
| May 2020 Update (19041)            |  ?  |
| November 2019 Update (18363)       | ? |
| May 2019 Update (18362)            | ?  |
| October 2018 Update (17763)        | ? |

**Additional context**

**Comment by andrewleader** [comment]
Thanks for reporting this, I'm working on finding the right team that owns this area!

**Comment by ivberg** [comment]
Verified issue still happens on AppSDK 0.8 & VS 10.6.2

**Comment by zsolt3991** [comment]
I have another version of the same issue. Upon configuring the prerequisites to run app as Administrator the App is crashing after the UAC popup. I have not managed to get a clear exception message, it creates a message in windows events, all that I could find is it is happening in the Native part as it does not even get to the App.cs constructor.

It happens with my custom app that worked on WinUI 3 Preview 2 (I think) and never since it was rolled into Project Reunion and now AppSDK. It also happens if I try a blank app and just add the Admin requirements.

It is not clear from the project documentation if running as admin is supported at all, most clues pointing to the fact that it is not. 

Not a great experince promoting AppSDK UI as replacement for legacy Win32 app UI when the advantages over UWP are not even materialized yet.

**Comment by iceberg1370** [comment]
I think Admin is supported. It has been working fine but it does make debugging harder with some of the VS issues. I usually just post attach and that works fine but obviously harder when you have a startup crash. I ended up temporarily taking off admin to debug the startup crash and to see what the exception is. Once you have the exception handy check the other issues to see if it’s the same exception/issue that I already logged.

**Comment by zsolt3991** [comment]
My App works "fine" with Admin rights disabled, it launches and does not throw any exceptions in the App side. The app template has nothing added to it besides the admin changes and it still crashed. Just tried to check if both 32 and 64 bit builds exhibit same behavior, it seems to be consistent.

Maybe I am missing some preview SDK on my system and it is trying to launch with something incompatible.

This is what Reliability Monitor says of the crash: (it seems to point to COM Class not registered Exception)

`
Problem Event Name:	MoAppCrash
Package Full Name:	3675ee57-7396-4c36-8507-12a8dc851e3e_1.0.0.0_x86__emv2xhwxy6y9e
Application Name:	praid:App
Application Version:	1.0.0.0
Application Timestamp:	609308a3
Fault Module Name:	StackHash12_3a5
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	00000000
Exception Code:	80040154
Exception Offset:	0
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	1048
Additional Information 1:	9dd4
Additional Information 2:	9dd4e384ffe3b444dba2bfae1dd7be39
Additional Information 3:	961a
Additional Information 4:	961a3727873fe91ee04d86bd6362c93f
`

**Comment by ivberg** [comment]
@zsolt3991 I think your crashing issue sounds like a separate issue either fixed in 0.8.1 or in your app. This bug is not about the app crashing, but that you can't launch an Admin app in VS and debug it (which you can for a normal WinAppSDK app).

Probably related to #973

**Comment by zsolt3991** [comment]
@ivberg I just tested 0.8.1 on Windows 10 and still experience the crash, including Debugging being stuck in Visual Studio, not even a sign that the process crashed in VS, it looks like I am debugging but nothing happens. 

It does not sound like what is described in #973, I think its probably a third different issue. Even the template app crashes for me if I run it as admin. I am starting to think its my Windows SDK version 10.1.19041.685 is the only one installed, this is the latest I can install through the VS Installer.

**Comment by ivberg** [comment]
That sucks you @zsolt3991  are getting a crash that is hard to debug. Here is what I would recommend to debug & work around this issue for now.

1. Download SysInternals ProcDump - https://docs.microsoft.com/en-us/sysinternals/downloads/procdump
2. Run SysInternals in this mode "-w | Wait for the specified process to launch if it's not running."
b. Eg. procdump.exe -w MyWinSDKAdminApp.exe
3. Launch your app and see crash
4. SysInternals will write a .dmp file
5. Open dump file in Visual Studio open dialogue
6. Alternatively, for another debugger you can try Windbg Preview. However, it's more complicated to use (than V) and  .NET stuff is not straigtforward. https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86

**Comment by ParkhutRoman** [comment]
@zsolt3991 try new emty project using [WindowsTemplateStudio](https://marketplace.visualstudio.com/items?itemName=WASTeamAccount.WindowsTemplateStudio). After 0.8 problems with running as admin gone. Maybe you have problem in 1 of 2 project files, or manifest. 
P.s. ReAttach helps with post attach debugging, but some low level errors slip through.

**Comment by qmatteoq** [comment]
I'm getting the same experience on my machine running Windows 10 19043.1149. Here are my steps:

1) I create a new empty WinUI 3 in desktop project with C#
2) I build and deploy the Windows Application Packaging Project
3) I open the Start menu and I launch the app: everything is working well.
4) I right click on the icon in the Start menu and I choose "Run as administrator": I get the UAC prompt, but then the app crashes and all I can see is the following error logged in Event Viewer:

```
Faulting application name: App5.exe, version: 1.0.0.0, time stamp: 0x609308a3
Faulting module name: Microsoft.UI.Xaml.dll, version: 3.0.0.2107, time stamp: 0x763d55be
Exception code: 0xc000027b
Fault offset: 0x00242779
Faulting process id: 0x8f78
Faulting application start time: 0x01d78538052af341
Faulting application path: C:\Program Files\WindowsApps\34939758-d83c-4617-8632-6a790b7f9275_1.0.1.0_x86__e627vcndsd2rc\App5\App5.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.8_8001.186.2159.0_x86__8wekyb3d8bbwe\Microsoft.UI.Xaml.dll
Report Id: 07e3b0bf-8515-4fce-bf44-6c16a2945ca0
Faulting package full name: 34939758-d83c-4617-8632-6a790b7f9275_1.0.1.0_x86__e627vcndsd2rc
Faulting package-relative application ID: App
```

I don't get the same experience with a traditional Win32 packaged app (for example, a WPF app based on .NET 5).

**Comment by whatever000wh** [comment]
> I don't get the same experience with a traditional Win32 packaged app (for example, a WPF app based on .NET 5).

https://github.com/microsoft/WindowsAppSDK/discussions/671#discussioncomment-1032396
see the two comments there .

**Comment by ParkhutRoman** [comment]
https://github.com/ParkhutRoman/AsAdminWindowsAppSDK for pp who lazy to try WindowsTemplateStudio and edit 2 files and update 1 nuget

**Comment by qmatteoq** [comment]
I will give it a try, but I'm getting the same behavior with my original project, which is created with Windows Template Studio. Additionally, based on @andrewleader comment in the other issue, it seems running as admin is an unsupported scenario, either with packaged or unpackaged apps.

**Comment by andrewleader** [comment]
@qmatteoq if you're running Windows 11 Insider builds, you should be able to run a packaged WinUI 3 app in elevated mode. The OS-level bug fix should be in the latest Insider builds.

Otherwise, this won't work for older versions of Windows (it's an OS-level issue, packaged apps running elevated cannot access non-inbox WinRT APIs - that's why a WPF packaged app not using WinAppSDK works, but when you use WinAppSDK APIs, it doesn't work)

**Comment by qmatteoq** [comment]
Thanks Andrew! I haven't tried this on Windows 11, so your explanation totally makes sense!

**Comment by mshaikhcool** [comment]
@andrewleader now dup of https://github.com/microsoft/WindowsAppSDK/issues/1407

**Comment by ivberg** [comment]
This seems to have regressed in WinAppSDK 1.0. Now even on Win11 I get this error at runtime "this app can't be activated from an elevated context"

**Comment by DrusTheAxe** [comment]
> This seems to have regressed in WinAppSDK 1.0

Regressed from what?

WinAppSDK 1.0 doesn't support elevation. There were some very specific (i.e. complicated) permutations of Windows version, application and use that could possibly work elevated but they were very narrow paths to tread and ever harder to explain (yes, even amongst ourselves). So rather than an inconsistent and, frankly, extremely fragile solution we added some explicit checks to provide consistent behavior.

[Elevation support](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/37-elevated-admin-support) is [on the roadmap for 1.1](https://github.com/microsoft/WindowsAppSDK#roadmap)

**Comment by riverar** [comment]
@DrusTheAxe I think they mean it regressed from what Andrew said earlier:

> @qmatteoq if you're running Windows 11 Insider builds, you should be able to run a packaged WinUI 3 app in elevated mode.

**Comment by DrusTheAxe** [comment]
> @DrusTheAxe I think they mean it regressed from what Andrew said earlier (and observed results in recent Insider builds until 22533):
> 
> > [...] if you're running Windows 11 Insider builds, you should be able to run a packaged WinUI 3 app in elevated mode.

Ah yes thank you. [That was Jul'30](https://github.com/microsoft/WindowsAppSDK/issues/896#issuecomment-890005213), predating the decision for 1.0 (Stable) release not to support elevation. Andrew's post was before we fully understood the complex dance required for it to work.

Some things flat out don't work elevated (e.g. Bootstrap API) but WinUI3 posed a common case where it often wouldn't outright fail in obvious and easy to grok ways (worse, by users - not just devs), so there's a check for elevation in app startup to detect and fail.

Trust me this decision wasn't reached easily or lightly. But we made the tough call not to support elevation in 1.0 and prioritize it for vNext, rather than favor a fragile, complicated, cryptic and easy to hit (usually fatal) error.

If elevation is of interest to you please [let us know](https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/37-elevated-admin-support). Sharing your voice will help ensure we prioritize our efforts to best meet your needs.

**Comment by ivberg** [comment]
> > This seems to have regressed in WinAppSDK 1.0
> 
> Regressed from what?
> 
> WinAppSDK 1.0 doesn't support elevation. 
Exactly, since 1.0 doesn't support elevation - and 0.5.x to 0.8.x at least under certain scenarios did in Win11 - this is a regression.   

Also a regression from the perspective of ReUnion apps should be able to do all the same things a win32 app could. Win32 apps don't run in a container and support elevation.

Good to hear it's coming in 1.1

**Comment by p-monteiro** [comment]
Adding to this, Hot Reload is also gone when the app (and VS) is running elevated, which gives us no way to rapidly evolve an app without constant rebuilds.

Tested with 1.1.0-preview3 under build 25115.

**Comment by DrusTheAxe** [comment]
> Adding to this, Hot Reload is also gone when the app (and VS) is running elevated

Is HotReload supported by elevated apps?

Is HotReload supported when VS is running elevated?

These are HotReload questions and VS questions, independent of WinAppSDK. I'm not well versed in HotReload's nuances (well, not yet ;-)) so I'm trying to understand if HotReload has issues regarding elevation or only elevation + WinAppSDK. Which is an overly broad statement, more specifically which aspects of WinAppSDK are in play here -- is your app packaged or unpackaged? Are you using WinUI? Are you using WinAppSDK/MSIX or WinAppSDK/SelfContained? Is your app SelfContained?

**Comment by p-monteiro** [comment]
Nonetheless, the only marketed way of "visually" developing a WinUI3 app without a designer is not available when using a (very soon) supported scenario.

HotReload works with VS elevated if the app is not run elevated. I guess it is related to the problem that when debugging the app elevated the debugger is not correctly attached (as mentioned by @ivberg).

I'm using WindowsAppSDK 1.1.0-preview3, with WinUI3 Packaged. My project was created by the Template Studio.

**Comment by p-monteiro** [comment]
Nonetheless, the only marketed way of "visually" developing a WinUI3 app without a designer is not available when using a (very soon) supported scenario.

HotReload works with VS elevated if the app is not run elevated. I guess it is related to the problem that when debugging the app elevated the debugger is not correctly attached (as mentioned by @ivberg).

I'm using WindowsAppSDK 1.1.0-preview3, with WinUI3 Packaged. My project was created by the Template Studio.

**Comment by mikebattista** [comment]
Elevation support shipped with the 1.1 release.

See https://github.com/microsoft/WindowsAppSDK/releases/tag/v1.1.0 and https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel#elevation.

**Comment by ivberg** [comment]
Opened new bug #2880 since the issue of attaching debugger in this issue was actually never fixed

**Comment by KWodarczyk** [comment]
I am having issue in windows 10, i am using windowsAppsSdk 1.1.2, os build  19042.1889 and KB5013942 is installed, but i don't get UAC prompt at all and get Access to the path 
'C:\Users\User\AppData\Local\Packages\d6db082e-ebd5-4308-9506-217a18cf4f18_w75fv9h06kgky is denied. Works fine on windows 11
