### ISSUE TITLE
Adjust default desktop title bar for tablet mode

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#900]
In Universal Windows Platform apps, the title bar gets adjusted automatically for the tablet mode. When you enable tablet mode, the maximize button is hidden in UWP apps however in desktop apps, it's shown without being disabled or hidden but it won't do anything when clicked. A custom title bar could solve these issues but it's a lot of work. It would be better if the system hides the maximize button for all desktop apps when in tablet mode. Also in UWP apps, the caption buttons are only visible when you hover on top in tablet mode but that may not be easy to discover.

**Comment by riverar** [comment]
Good catch @Jaiganeshkumaran.

Can confirm default WinUI 3 desktop apps are resized but the restore system caption button does nothing. That's a bit confusing.

![tabletmode_restore](https://user-images.githubusercontent.com/475132/120423105-9c152a00-c31e-11eb-83a6-714c9eb6bf4a.gif)

The tricky part here is determining if the app called `SetTitleBar` and customized the titlebar. I'd expect in that scenario, Windows would leave the buttons alone.

**Comment by andrewleader** [comment]
@rkarman is this your area of ownership? Any thoughts? Seems like a potential good feature request for the future!

**Comment by rkarman** [comment]
Now that Windows 11 is out of the bag I assume everyone has seen that there is no longer a specific Tablet Mode in the product (see [Feature deprecations and removals](https://www.microsoft.com/en-us/windows/windows-11-specifications#table3) for Windows 11). I have created a feature under the windowing node in Productboard (id: 10542271) tracking this request for future planning cycles to find out what the priority might be to address this for Windows 10 only.

**Comment by riverar** [comment]
@Jaiganeshkumaran Are you still seeing this behavior with the new tablet _posture_ in Windows 10/11? I don't have cycles to test this at the moment.
