### ISSUE TITLE
ApplicationView.SetPreferredMinSize should allow sizes larger than 500x500px

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#911]
Currently ApplicationView.SetPreferredMinSize ignores any value above 500x500px so it's not possible to have the minimum size larger than 500x500px however, some apps with a lot of content may want to use a larger minimum size. This is possible in desktop apps but not UWP apps.

**Comment by andrewleader** [comment]
Thanks for requesting this! We'll consider this for a future version, but don't have any plans to share.

**Comment by Jaiganeshkumaran** [comment]
The minimum default size for Win32 apps is also inconsistent with the one for UWP which should be the same.

**Comment by mdtauk** [comment]
> The minimum default size for Win32 apps is also inconsistent with the one for UWP which should be the same.

Core Window and UWP's Titlebar aligns to the 4px grid, and ideally the default metrics in the MSStyles would be updated to match.

Some of the "Sun Valley" "Cherry Hill" designs seem to have a taller 40/48px titlebar - so both UWP and Win32 Titlebars may both need updating

**Comment by rkarman** [comment]
We don't currently have any plans to change the UWP ApplicationView APIs. I've filed an item to keep this in the backlog ( http://task.ms/38108324 ). Closing the issue here as feature is not going to be supported in any foreseeable WinAppSDK release.
