### ISSUE TITLE
Build errors when using TFM of 17763

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#921]
**Describe the bug**
This is a **known issue** (we need to update the NuGet package dependencies in the Microsoft.ProjectReunion.WinUI NuGet package). Despite Project Reunion supporting down to build 17763 of Windows 10, if you use the .NET TFM of `net5.0-windows10.0.17763` or set the packaging project's `<TargetPlatformVersion>` to 17763 or lower, the project won't build, receiving build errors like `Project XYZ is not compatible with uap10.0.17763`.

**Workaround**
Update your TFM to `net5.0-windows10.0.18362` or higher, and in your packaging project, update your `<TargetPlatformVersion>` to 18362 or higher. This will not prevent you from running on 17763 (MinVersion declares that). This only affects what APIs are available (more APIs will be available by targeting a higher version).

**Steps to reproduce the behavior:**
1. Create a 0.5 or 0.8 Preview WinUI 3 desktop app
2. Change the TFM to `net5.0-windows10.0.17763`, or change the packaging project's `<TargetPlatformVersion>` to 17763
3. Try to build the project

**Expected behavior**
Building and deploying should succeed, since Project Reunion supports down to 17763.

**Version Info**

NuGet package version: 
Version 0.5.7 and 0.8.0-preview

**Root cause**
The `Microsoft.ProjectReunion.WinUI` NuGet package declares a dependency on `net5.0-windows10.0.18362` or higher, when this instead should be targeting `net5.0-windows10.0.17763`. Internal bug number 33525703.

**Comment by asklar** [comment]
@andrewleader how should this work for libraries (as opposed to apps)? we have a winrt library written (in C++) that we are projecting onto C# / reunion via cswinrt, we would like to make the library available to the most number of apps, but when using 17763 we hit this issue.

**Comment by andrewleader** [comment]
Fixed in upcoming 1.0 Preview 2. You'll now be able to use a TFM of 17763 in apps (or libraries) with WinAppSDK 1.0 Preview 2.
