### ISSUE TITLE
Address AppLifecycle comments from Push Notifications PR

### ISSUE THREAD

**Issue by danielayala94** [microsoft/WindowsAppSDK#926]
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647720668
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647722057
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647723191
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647723677
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647738627
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647748642
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647749318
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647753265
https://github.com/microsoft/ProjectReunion/pull/823#issuecomment-857077610
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647755955
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647758069
https://github.com/microsoft/ProjectReunion/pull/823#issuecomment-857207980
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647829683
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647831383
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647832079
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647832786
https://github.com/microsoft/ProjectReunion/pull/823#issuecomment-857218420
https://github.com/microsoft/ProjectReunion/pull/823#issuecomment-857224140
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647838155
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r647839502

**Comment by danielayala94** [comment]
A few more comments from latest review:

https://github.com/microsoft/ProjectReunion/pull/823#issuecomment-859905716
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r650260518
https://github.com/microsoft/ProjectReunion/pull/823#discussion_r650264034

**Comment by pmpurifoy** [comment]
https://github.com/microsoft/ProjectReunion/pull/823#issuecomment-862515669

**Comment by pmpurifoy** [comment]
[https://github.com/microsoft/ProjectReunion/pull/823#discussion_r652992371](url)

**Comment by aeloros** [comment]
working through the list.  in my current topic branch I have all except these changed:

https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647838155
https://github.com/microsoft/WindowsAppSDK/pull/823#issuecomment-857224140
https://github.com/microsoft/WindowsAppSDK/pull/823#issuecomment-857218420
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647831383
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647829683
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647755955
https://github.com/microsoft/WindowsAppSDK/pull/823#issuecomment-857077610
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647738627
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647722057
https://github.com/microsoft/WindowsAppSDK/pull/823#discussion_r647720668
