### ISSUE TITLE
Cannot install Global Windows Hotkey for ReUnion app

### ISSUE THREAD

**Issue by ivberg** [microsoft/WindowsAppSDK#941]
**Describe the bug**
Cannot install Global Windows Hotkey for ReUnion app.

ReUnion promises to be the bring forward Windows development and be additive in that you can run full trust and access underlying handles or APIs if there are not yet available in ReUnion.

I have found this mostly to be true, but there is one area I cannot get to work at all, using global hotkeys. I am using a DotNet Core 5.0 C# app and none of the samples I tried on the web seem to work for a ReUnion app.

In this case, ReUnion doesn't seem to be just extra pkgs to reference, as the .csproj seems quite different than say a WPF app that would support this.

**Steps to reproduce the bug**
1. Go to aka.ms/winui, try WinUI 3, and follow the instructions for creating a C# ReUnion 0.5 Desktop app.
2. Attempt to follow any of these samples or instructions for global hotkeys. Namespaces will be missing (like using System.Windows.Interop) and I haven't been able to find any NuGet pkgs to satisfy code refs or rewrite the samples

https://www.bing.com/search?q=c%23+global+windows+hotkey
https://stackoverflow.com/questions/2450373/set-global-hotkeys-using-c-sharp
http://www.pinvoke.net/default.aspx/user32/RegisterHotKey.html
https://social.technet.microsoft.com/wiki/contents/articles/30568.wpf-implementing-global-hot-keys.aspx

**Expected behavior**
That C# ReUnion apps can setup Windows global hotkeys just like WinForms or WPF apps

**Screenshots**

**Version Info**
ReUnion 0.5

NuGet package version: 
  PackageReference Include="Microsoft.ProjectReunion" Version="0.5.7"
  PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7"
  PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7"

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.40)              | Yes  |

**Comment by ivberg** [comment]
In theory we could maybe modify this example - https://social.technet.microsoft.com/wiki/contents/articles/30568.wpf-implementing-global-hot-keys.aspx

If we port over the WPF implementation and get access to the underlying HWND. In theory ReUnion allows this and provides IWindowNative.WindowHandle
https://docs.microsoft.com/en-us/windows/apps/winui/reference/iwindownative-windowhandle
var hwnd = this.As<IWindowNative>().WindowHandle;

However, even after adding the required refs:
using System.Runtime.InteropServices;
using WinRT;

You still get a reference error:
Error	CS0246	The type or namespace name 'IWindowNative' could not be found (are you missing a using directive or an assembly reference?)

**Comment by LegendaryBlair** [comment]
The Win32 API RegisterHotKey should fulfill the requirement, hence closing the stale issue.

**Comment by ivberg** [comment]
@LegendaryBlair did you actually test with RegisterHotKey ?   That API was listed in the original bug as not working. I would suggest verifying this truly work and providing that example before closing this issue.

**Comment by mominshaikhdevs** [comment]
@LegendaryBlair if your tests didn't work, please consider reopening this issue or assign it to someone who works in this area.

**Comment by castorix** [comment]
> [@LegendaryBlair](https://github.com/LegendaryBlair) did you actually test with RegisterHotKey ? That API was listed in the original bug as not working. I would suggest verifying this truly work and providing that example before closing this issue.

I had tested _RegisterHotKey_ in this test sample [WinUI3_DesktopDuplication](https://github.com/[castorix/WinUI3_DesktopDuplication](https://github.com/castorix/WinUI3_DesktopDuplication))
(I just recompiled in 1.6 and it still works...)

**Comment by LegendaryBlair** [comment]
@ivberg I have tested in Visual studio 2022 (Version 17.11.6) with project template "Blank App, Packaged (WinUI3 in Desktop)" C# app, which will install WinAppSDK 1.6 for me. It worked for me.
