### ISSUE TITLE
Warning on Blank App created with Project Reunion 0.8 RC

### ISSUE THREAD

**Issue by sibille** [microsoft/WindowsAppSDK#952]
**Describe the bug**
We're seeing the following warning on an app created with the Project Reunion 0.8 RC

`Package 'Microsoft.ProjectReunion.InteractiveExperiences 0.8.0-rc' was restored using 'net5.0-windows10.0.19041, .NETCoreApp,Version=v3.1, .NETCoreApp,Version=v3.0, .NETCoreApp,Version=v2.0, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, net5.0-windows10.0.17763, net6.0-windows10.0.17763, .NETFramework,Version=v4.6.1' instead of the project target framework 'UAP,Version=v10.0.17763'. This package may not be fully compatible with your project.`	

**Steps to reproduce the bug**
1. Create a new Blank App, Packaged (WinUI 3 in Desktop) or open the attached [SampleApp](https://github.com/microsoft/ProjectReunion/files/6688032/SampleApp.zip)
2. Build it

=> See warning 

**Version Info**

NuGet package version: 
 Example: [Microsoft.ProjectReunion 0.8.0-rc] -->

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by KennyTK** [comment]
I am also getting this warning with ProjectReunion.InteractiveExperiences 0.8.0 and 0.8.1 on May 2020 Update (19041)

**Comment by ionvasilian** [comment]
Thanks for the report, the warning is harmless. We'll have the issue addressed in the next preview of the 1.0 SDK.

**Comment by ionvasilian** [comment]
The issue was addressed in WindowsAppSDK 1.0. @sibille let us know if you're still encountering the warning. Thanks again for the report.
