### ISSUE TITLE
WebView2 AddHostObjectToScript Not Implemented Error

### ISSUE THREAD

**Issue by Finnur** [microsoft/WindowsAppSDK#958]
**Describe the bug**
I'm not sure if this belongs here or in the WebView2 feedback Repo, but I posted it here since it's using the WebView2 that is bundled with the Project Reunion Project
When trying to use 'WebView2.CoreWebView2.AddHostObjectToScript' it gets a not implemented error.

**Steps to reproduce the bug**

1. Add a Webview2 to your Project Reunion 0.8 WinUI 3 in Desktop project
2. Add a NavigationStarting event to the webview and Call AddHostObjectToScript from it (https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript)
3. Get an error and the console log will say "Exception thrown at 0x00007FFDDAC03B19 (KernelBase.dll) in WebViewTest.exe: WinRT originate error - 0x80004001 : 'Not implemented'."

**Expected behavior**
Host object gets added the the website and is accessable from javascript

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.ProjectReunion 0.8.0-preview] 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by asklar** [comment]
Tracked internally by https://task.ms/31936636

**Comment by Finnur** [comment]
Is there any ETA on when this will be fixed?  It is still broken in the WindowsAppSdk 1.0 Experimental1 version.

**Comment by codendone** [comment]
There isn't an ETA currently for the direct `CoreWebView2.AddHostObjectToScript` API. However, if you have or can create a COM object (rather than a WinRT object) you can theoretically achieve what you need via [ICoreWebView2Interop.AddHostObjectToScript](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/interop/icorewebview2interop). Here is some sample code:
```
    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("912b34a7-d10b-49c4-af18-7cb7e604e01a")]
    public interface ICoreWebView2Interop
    {
        void AddHostObjectToScript([In] string name, [In] ref object obj);
    }

#pragma warning disable CS0618
    [ClassInterface(ClassInterfaceType.AutoDual)]
#pragma warning restore CS0618
    [ComVisible(true)]
    public class MyObject
    {
        public string Prop { get; set; } = "Example property from host object";
    }
```

And then in some function:
```
var interop = myWebView2.CoreWebView2.As<ICoreWebView2Interop>();
interop.AddHostObjectToScript("myObject", new MyObject());
```

**Comment by Finnur** [comment]
That works and solves my problem, thank you very much.
