### ISSUE TITLE
Proposal: MapControl MapStyleSheet hiding sun and stars

### ISSUE THREAD

**Issue by izubiaurre** [microsoft/WindowsAppSDK#960]
## Summary
UWP MapControl shows stars and the sun at some random place on the sky like in the image below. MapControl MaoStyleSheet should provide a setting entry to change stars and sun visibility (hide/show).
![7xhKD](https://user-images.githubusercontent.com/1365320/122994459-c8194d80-d3a8-11eb-80ad-f3473860131f.jpg)

## Important Notes
<!-- Please include any other important details.
MapStyleSheet Editor also should provide this option once applied in the API.

**Comment by btueffers** [comment]
We're tracking this internally now so we'll be closing the GitHub issue. Thank you for the feedback!
