### ISSUE TITLE
UWP apps should be able to customize title bar context menu

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/WindowsAppSDK#961]
Today desktop apps are able to customize the title bar context menu by adding additional options in the menu but I've not seen a way to do this under UWP.

**Comment by SeriouslyWhyIAmAGhost** [comment]
@andrewleader @btueffers this issue should be closed for the same  reason (`CoreWindow`)  #159 #173  #302 got closed.

**Comment by rkarman** [comment]
As per previous comment, and as [announced](https://github.com/microsoft/WindowsAppSDK/discussions/1615), the Windows App SDK is focusing on desktop-based project types and we're working on making it easy to [migrate](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/overall-migration-strategy) from UWP to desktop, which will provide you the ability to add items to the title bar context menu today using user32 APIs.
