### ISSUE TITLE
Changing Field of View or Pitch value on UWP MapControl camera changes altitude of camera

### ISSUE THREAD

**Issue by izubiaurre** [microsoft/WindowsAppSDK#971]
**Describe the bug**

Changing Field of View or Pitch value on UWP MapControl camera changes altitude of camera.

**Steps to reproduce the bug**

1- Place the camera in MapControl on the ground (as nearest altitude as possible). 
2- Narrowing the angle of view, the camera starts gaining altitude, when nearer to the ground or surface of the map the more visible is the effect. Same happens when changing Pitch values, at certain angles camera gains altitude also.

This is the code I use to set altitude of the MapCamera, the Pitch, FoV, ...

```
newCamera = new MapCamera(cameraVR.GroundGeopoint, cameraVR.Heading, cameraVR.Pitch, cameraVR.Roll, cameraVR.FoV);
MapScene mapScene = MapScene.CreateFromCamera(newCamera);
mapPosition.TrySetSceneAsync(mapScene, MapAnimationKind.None);
```
GroundGeopoint is the location of the camera "stuck" to the ground, even if it's alaways levitating some meters above the ground.

**Expected behavior**

The expected behavior should be not to change the altitude of the camera when playing with the Field of View and Pitch values and to give the possibility to place the camera at the altitude desired by the user (even the difference between ground altitude and camera is 0).

**Comment by btueffers** [comment]
We're tracking this item internally now. Thank you for the feedback!

**Comment by riverar** [comment]
Shouldn't this issue remain open until the problem is resolved? cc: @andrewleader

**Comment by andrewleader** [comment]
@riverar for platform bugs (like bugs in the platform UWP MapControl), we track those internally. This bug isn't related to the Windows App SDK, it's a platform bug (which we use either Feedback Hub for public feedback or our Azure DevOps to track everything internally).
