### ISSUE TITLE
Adding an icon to a package with build action None still adds it to the .pri resource

### ISSUE THREAD

**Issue by dotMorten** [microsoft/WindowsAppSDK#980]
**Describe the bug**
When building a class library with the ability to pack into a nuget package, an included icon for the nuget package will be referenced by the .pri file.
This results is a nuget package that fails to deploy, due to the lack of this file in the lib folder, but it could also mean that resources are getting deployed that the developer never explicitly told it to include.

**Steps to reproduce the bug**

1. Create a new WinUI class library (C#):
2. Add an icon in the folder above, and include it in the project for nuget icons. Project should look like this:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>WinUIClassLib</RootNamespace>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <PackageIcon>icon.png</PackageIcon> <!-- add this -->
  </PropertyGroup>

  <ItemGroup>
    <None Include="../icon.png" Link="icon.png" Pack="true" PackagePath="\icon.png" /> <!-- add this -->
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0" />
  </ItemGroup>
</Project>
```
3. Right-click the project and select "Pack"
4. Inspect the .pri file that is generated and placed in the nuget package. It'll contain a reference to this icon file. But since it isn't packed with the package below the lib folder, it'll fail to deploy this package.

Full repro:
[WinUIClassLib.zip](https://github.com/microsoft/WindowsAppSDK/files/6712327/WinUIClassLib.zip)

I did find this in `Microsoft.ApplicationModel.Resources.PriGen.targets` but to me it seems incorrect to assume `None` files should be included:
```xml
  <!-- The .NET/C# project system does not add the .resw files added to the project to PRIResource, unlike the UWP
       project system (this is expected since .resw files were historically UWP specific). That is needed for the
       .resw files to be indexed during PRI generation. Likewise, image files need to be added to Content for them
       to be indexed. These files exist in the None list by default (meaning without app developer intervention).
       We address this requirement here so that the app developer doesn't need to manually intervene. -->
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
    <!-- Add .resw files to PRIResource so they are indexed. -->
    <PRIResource Include="@(None->WithMetadataValue('Extension', '.resw'))" />
    <!-- Add image files to PRIResource so they are indexed. -->
    <Content Include="@(None->WithMetadataValue('Extension', '.png'))" />
    <Content Include="@(None->WithMetadataValue('Extension', '.bmp'))" />
    <Content Include="@(None->WithMetadataValue('Extension', '.jpg'))" />
    <Content Include="@(None->WithMetadataValue('Extension', '.dds'))" />
    <Content Include="@(None->WithMetadataValue('Extension', '.tif'))" />
    <Content Include="@(None->WithMetadataValue('Extension', '.tga'))" />
    <Content Include="@(None->WithMetadataValue('Extension', '.gif'))" />
  </ItemGroup>
```
Especially this comment:
> Likewise, image files need to be added to Content for them to be indexed. These files exist in the None list by default (meaning without app developer intervention). We address this requirement here so that the app developer doesn't need to manually intervene. 

IMHO if I chose not to include files (implicitly or explicitly), it shouldn't just be chosen for me. The NuGet packaging scenario is one obvious scenario, but there could just as well be resources here that I never intended to actually ship but just keep for other reasons. And even if I _explicitly_ set a build action to `None` (as above), it gets forced in anyway. This doesn't seem like the correct way to configure default items.
I believe the way to do default globbing/includes should be done in the SDK instead. See here for references: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props-desktop

I did confirm by removing this entry from the Foundation nuget package, the problem goes away.

This seems to have been introduced by #771

There is also no simple workaround that I can see. Even doing this will cause it to be added regardless:
```xml
<ItemGroup>
    <Content Remove="icon.png" />
</ItemGroup>
```
You can however do this:
```
  <ItemGroup>
    <Content Remove="icon.png" />
    <None Remove="icon.png" />
  </ItemGroup>
```
But that is very counter-intuitive, and now I can't pack the icon with my nuget package.

**Expected behavior**
Don't include files with build action `None` into the resource file.

**Version Info**
VS16.10

NuGet package version: 
0.8.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by dotMorten** [comment]
CC @rohanp-msft I believe this behavior was introduced by your PR.

**Comment by dotMorten** [comment]
I wonder if, based on this: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#enabledefaultembeddedresourceitems
this would be a slightly better way?

```xml
  <PropertyGroup>
     <EnableDefaultPRIResourceItems Condition="'$(EnableDefaultPRIResourceItems)'==''">true</EnableDefaultPRIResourceItems>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp' AND '$(EnableDefaultPRIResourceItems)'=='true' AND '$(EnableDefaultItems)'=='true'">
    <!-- Add .resw files to PRIResource so they are indexed. -->
    <PRIResource Include="**\*.resw" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/> 
    <!-- Add image files to PRIResource so they are indexed. -->
    <Content Include="**\*.png" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/> 
    <Content Include="**\*.bmp" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
    <Content Include="**\*.jpg" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
    <Content Include="**\*.dds" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
    <Content Include="**\*.tif" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
    <Content Include="**\*.tga" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
    <Content Include="**\*.gif" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder)"/>
  </ItemGroup>
```

At least here it won't include none-files that I've linked in from a different folder, explicitly setting it to `None`, and it gives an identicaly way to other resources to opt out of this behavior.

**Comment by dotMorten** [comment]
Ignore the above. It still doesn't allow me to avoid a PNG to get included that I don't want included, unless I use the `DefaultItemExcludes` or `EnableDefaultPRIResourceItems` properties, which IMHO are a bit too pervasive for removing a single file.

**Comment by huichen123** [comment]
This is a known issue, and there is a workaround at https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel.

**Comment by dotMorten** [comment]
@huichen123 Thanks but doing this in `Directory.Build.targets` has lots of other ripple effects and could go wrong.

**Comment by dotMorten** [comment]
Any update on this?

**Comment by rohanp-msft** [comment]
Hello Morten, the fix is in the works for 1.0 Preview 1 or Preview 2.

**Comment by dotMorten** [comment]
Awesome. Thanks. I'm a few hours in today trying to workaround it in a good way (so far we've been manually post-edited the packages which is error prone). But since you're fixing it, I'll stop looking for a workaround for now.

**Comment by rohanp-msft** [comment]
@dotMorten Morten, I have a change for this issue that's in review right now. It's this: https://github.com/microsoft/WindowsAppSDK/pull/1389. I couldn't add you as a reviewer there for some reason, so letting you know here.
