### ISSUE TITLE
WindowsAppSDK / ReUnion 0.8 C# app won't compile as x64 (but will as AnyCPU)

### ISSUE THREAD

**Issue by ivberg** [microsoft/WindowsAppSDK#981]
**Describe the bug**
ReUnion 0.5 and 0.8 Preview app was compiling fine before on x64. Now after upgrading to 0.8 it won't compile. I had to switch back to AnyCPU.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'System' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)	MyAppUI	C:\src\MyApp\MyAppUI\MyAppUI\obj\x64\Debug\net5.0-windows10.0.19041.0\App.g.i.cs	27	Active

Generated code that won't compile (even after multiple cleans and obj deletions)
            global::Microsoft.UI.Xaml.Application.Start((p) => {
                var context = new global::Microsoft.System.DispatcherQueueSynchronizationContext(global::Microsoft.System.DispatcherQueue.GetForCurrentThread());
                global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
                new App();
            });

DispatcherQueue is one of the namespace changes in 0.8

Trying these steps didn't help:
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/update-existing-projects-to-the-latest-release

**Steps to reproduce the bug**
1. Presumably you repro this with a C# 0.8 app created from scratch. However, I am repro'ing on my existing app
2. Compile app as x64 and make sure x64 is selected in Project VS props

**Expected behavior**
App can compile and deploy as x64

**Screenshots**

**Version Info**
    PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
    PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0" />
    PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0" />

NuGet package version: 
See above

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.41)              | Yes  |

**Additional context**

**Comment by asklar** [comment]
@ivberg I hit this as well - I think this happens when you mix the _Preview_ Reunion VSIX with the release nuget package. That line should use `Microsoft.UI.Dispatching` instead of `Microsoft.System`. Try deleting all outputs (bin, obj), ensuring you have the non-preview VSIX, and rebuilding.

**Comment by iceberg1370** [comment]
Yep unless my system is in an odd state underneath despite everything says 0.8 including VSIX and NuGet pkgs. Yes the namespace breaking changes hit and I had to use Microsoft.UI.Dispatching instead. This error doesn’t happen on AnyCpu/x86 and only on x64. I also tried clean both auto and manual, VS restarts but nothing helped. 

Can u try repro on x64 @asklar ?

**Comment by asklar** [comment]
@iceberg1370 yes I was using x64 to repro - uninstalling the vsix/installing the release vsix, deleting the bin/obj folder and .assets.cache file fixed it for me. If that doesn't work try it again and also delete your %userprofile%\.nuget folder. If all that doesn't work, enable build logging (you'll need to install [this vsix](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools)) and share a binlog.

**Comment by iceberg1370** [comment]
Good detailed tips @asklar ! Will try them out.

**Comment by asklar** [comment]
@ivberg ping back if you're still blocked

**Comment by ivberg** [comment]
Previously I had upgraded from 0.5.7 to 0.8 using the VS Extension updater. Per @asklar comment I tried uninstalling the ReUnion MSIX, restarted VS (to complete the uninstall), then reinstalled the VSIX. This seems to make the x64 compile error go away however there is now a new error on run. Will diagnose separately

**Comment by ivberg** [comment]
Hit this same issue on 0.8.1 as well so re-opening

1.	Repro – have an app that uses Dispatcher in the old namespace
                Microsoft.System.DispatcherQueueHandler handler = () => UpdateSystemPageUI(mainWindow, systemStats);
                this.DispatcherQueue?.TryEnqueue(Microsoft.System.DispatcherQueuePriority.Normal, handler);
2.	Upgrade VSIX in VS from 0.5.7 to 0.8.1. Requires VS restart.
3.	Upgrade Nuget pkgs to 0.8.1
4.	Rebuild app, you will get compile errors for the namespace. Make changes like:
                DispatcherQueueHandler handler = () => UpdateSystemPageUI(mainWindow, systemStats);
                this.DispatcherQueue?.TryEnqueue(DispatcherQueuePriority.Normal, handler);
5.	Those errors will go away but you will be left with errors in App.g.i.cs like in the issue
6.	Clean or rebuild project – doesn’t help
7.	Clean solution – doesn’t help
8.	VS restart in combo with Solution clean (7) – Seems to fix issue similar to last time

**Comment by asklar** [comment]
fyi @alwu-msft

**Comment by RealTommyKlein** [comment]
This is because Visual Studio/MSBuild caches the Xaml compiler MSBuild task, so even after updating to 0.8 Visual Studio uses the 0.5 Xaml compiler (which generates the incorrect DispatcherQueue namespace) until Visual Studio restarts and potentially all MSBuild.exe instances are killed.

**Comment by ivberg** [comment]
This is now covered in the release upgrade notes

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/update-existing-projects-to-the-latest-release#update-from-05-stable-to-08-stable

5. If your solution fails to build, clean the build output, restart Visual Studio, and try re-running the app.
