### ISSUE TITLE
Default WinUI3 (Reunion 0.8.0) won't start (System.Reflection.TargetInvocationException)

### ISSUE THREAD

**Issue by mprevot** [microsoft/WindowsAppSDK#992]
**Describe the bug**

At start of a default WinUI3 app: start fails with:

System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'

**Steps to reproduce the bug**

Create a default desktop app project with WinUI3, min target/target: 19041

**Expected behavior**

It is supposed to start.

**Version Info**

Win ProjectReunion 0.8.0

NuGet package version: 
0.8.0

Win10 21H1 enterprise
19043.1081 (Windows Feature Experience Pack 120.2212.3530.0)

Visual studio 2019 16.10.2 enterprise

**Comment by MarkBQE** [comment]
Same issue after upgrading to Reunion 0.8.0

**Comment by riverar** [comment]
Are you starting the app project or the packaging project?

**Comment by MarkBQE** [comment]
I am starting the packaging project. Exact same code was working fine with 0.8 preview

**Comment by nickrandolph** [comment]
I assume you've done a full clean of bin/obj folders - 0.8 has changes even from the preview that you need to flush away.....

**Comment by mprevot** [comment]
I start the app instead of the package project. That was the issue, the launch of the package works properly.

**If one can't use the app for launch (usually the output type "windows application" is executable), there should be an undertandable warning explaining this. This is a UX or design breaking change.**
