### ISSUE TITLE
UWP blank app crashes when hiding virtual keyboard in tablet mode

### ISSUE THREAD

**Issue by anovik** [microsoft/WindowsAppSDK#994]
**Describe the bug**
If you launch any UWP app with Windows 10 Tablet Mode enabled, then display virtual keyboard through panel, then hide the virtual keyboard - the app crashes.

**Steps to reproduce the bug**
I've attached the minimal app UWP with Reunion with the bug. Launch it with tablet mode enabled, show virtual keyboard and then hide it  - the app will crash. There is no related code in the app, so it is Project Reunion/WinUI3 bug I think. Minimal app with UWP only (without Project Reunion) works fine. 
[VKTest.zip](https://github.com/microsoft/WindowsAppSDK/files/6726425/VKTest.zip)

NuGet package version: 
WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview

Windows app type: UWP

Windows 10, Desktop

**Comment by SeriouslyWhyIAmAGhost** [comment]
@andrewleader @btueffers this issue should be closed for the same  reason (`CoreWindow`)  #159 #173  #302 got closed.

**Comment by anovik** [comment]
Agree with closing this issue, I've migrated my app to WinUI3 desktop and this issue has gone away.
