### ISSUE TITLE
Windows 11 Support

### ISSUE THREAD

**Issue by sconan32** [microsoft/WindowsAppSDK#998]
**Describe the bug**
The Blank WinUI3 Win32 App Crashes on Win11 Build 22000.51

**Steps to reproduce the bug**

1. Create a blank WinUI3 win32 packaged App on VS2019 16.11 preview 2
2. Click on 'Run..' With 'x86' or 'x64' config

**Expected behavior**
It should work normally.

**Screenshots**

![屏幕截图 2021-06-29 162419](https://user-images.githubusercontent.com/1318948/123763574-84699b00-d8f6-11eb-9979-f77e6034f870.png)
**Version Info**

NuGet package version: 

[Microsoft.ProjectReunion 0.8.0-stable] 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.51)              |  Yes   |

**Comment by asklar** [comment]
This is tracked by https://task.ms/34005792 and has been fixed; I believe the fix will go out in the next Windows App SDK servicing event.

**Comment by martibravo** [comment]
When is the next Windows App SDK release gonna be? Are we going to have to wait until October for the 1.0 release?

**Comment by asklar** [comment]
@jonwis can you comment on servicing / timelines for 0.8?
